src/fabric/src/fabric_db_info.erl
Unlike most other fabric_db_* message handlers, the accumulator
for fabric_db_info has 3 terms. When a rexi timeout occurs, it
returns `{timeout, Accumulator}`; the case clause handling this
needs to expect 3 terms in the Accumulator instead of 2.
I can't see a good precedent for testing this but I'm happy to add a test if somebody can point me to an example.
Fixes #2350
=> Fix timeout case clause in fabric_db_info

rebar.config.script, src/couch_expiring_cache/README.md, src/couch_expiring_cache/include/couch_expiring_cache.hrl, src/couch_expiring_cache/rebar.config, src/couch_expiring_cache/src/couch_expiring_cache.app.src, src/couch_expiring_cache/src/couch_expiring_cache.erl, src/couch_expiring_cache/src/couch_expiring_cache_fdb.erl, src/couch_expiring_cache/src/couch_expiring_cache_server.erl, src/couch_expiring_cache/test/couch_expiring_cache_tests.erl
This implements an FDB backed key value cache, where each entry has a "stale" and "expires" time associated with it. Once the current time exceeds the "expires" time, the entry is automatically removed.
Potentially useful for implementing e.g. interfaces to external systems such as OAuth 2.
```
make check apps=couch_expiring_cache
```
=> Expiring cache

src/couch/src/couch_multidb_changes.erl
The test broke during the removal of view-based changes PR
Issue: https://github.com/apache/couchdb/pull/2324
=> Fix multidb changes test

src/smoosh/src/smoosh_utils.erl, src/smoosh/test/exunit/scheduling_window_test.exs
Smoosh's exunit tests use UTC, so they sometimes fail when run in non-GMT time zones:
```
1) test in_allowed_window returns true when to < from < now (SmooshSchedulingWindowTest)
src/smoosh/test/exunit/scheduling_window_test.exs:53
Assertion with == failed
code:  assert :smoosh_utils.in_allowed_window('test_channel') == true
left:  false
right: true
stacktrace:
src/smoosh/test/exunit/scheduling_window_test.exs:59: (test)
* test in_allowed_window returns false when from < to < now (0.5ms)
2) test in_allowed_window returns false when from < to < now (SmooshSchedulingWindowTest)
src/smoosh/test/exunit/scheduling_window_test.exs:44
Assertion with == failed
code:  assert :smoosh_utils.in_allowed_window('test_channel') == false
left:  true
right: false
stacktrace: …
```
=> Make smoosh use UTC for scheduling window

test/elixir/test/partition_mango_test.exs
When creating a Mango index in the Elixir tests, we need to block until the database reports the index as available. This workaround was present in the python Mango tests but did not
get ported to Elixir when the partitioned Mango tests were added.
Presumably this is needed to workaround an underlying race condition between the index write and the ddoc cache.
let's see if it reliably passes in CI...
=> Address flakey Mango Elixir tests

rel/overlay/bin/remsh
This adds a couple of improvements to remsh following an incident where I needed to use it in a CouchDB deployed via Helm. The CouchDB docker container and Helm chart both utilize `ERL_FLAGS` to set the Erlang cookie. Unfortunately, this interferes with `./remsh`, which adds it's own `-setcookie` parameter when calling `erl` - you end up with multiple `-setcookie` and, in the case of the Helm chart, multiple `-name` parameters, resulting in Erlang failing to connect to the remote node.
The PR firstly sets `ERL_FLAGS` to empty when invoking `erl`, to avoid conflicts with explicitly set parameters. Secondly, it attempts to automatically locate the cookie from `ERL_FLAGS` or `vm.args` which should yield a better default than `monster` in most cases.
Testing is a little tricky as it requires …
=> Remsh improvements

rebar.config.script
Soft drop support for Erlang 19 with a warning and be more clear in the
warnings about the broken versions of Erlang 20+.
=> Update warning/error messages for Erlang versions

Makefile, src/dreyfus/test/elixir/test/partition_search_test.exs, test/elixir/lib/couch/db_test.ex, test/elixir/test/all_docs_test.exs, test/elixir/test/attachment_names_test.exs, test/elixir/test/attachment_paths_test.exs, test/elixir/test/attachments_multipart_test.exs, test/elixir/test/attachments_test.exs, test/elixir/test/basics_test.exs, test/elixir/test/bulk_docs_test.exs, test/elixir/test/cluster_with_quorum_test.exs, test/elixir/test/cluster_without_quorum_test.exs, test/elixir/test/compact_test.exs, test/elixir/test/copy_doc_test.exs, test/elixir/test/lots_of_docs_test.exs, test/elixir/test/partition_crud_test.exs, test/elixir/test/partition_ddoc_test.exs, test/elixir/test/partition_helpers.exs, test/elixir/test/partition_size_limit_test.exs, test/elixir/test/partition_size_test.exs, test/elixir/test/partition_view_update_test.exs, test/elixir/test/reduce_test.exs, test/elixir/test/reshard_all_docs_test.exs, test/elixir/test/reshard_basic_test.exs, test/elixir/test/reshard_changes_feed.exs, test/elixir/test/rewrite_test.exs
Switch `make elixir` to use n = 1. This matches how the javascript tests are run and hopefully should make the elixir tests a little more consistent and less flaky.
Tests should pass on Travis and Jenkins
=> Switch make elixir to use n = 1

test/elixir/lib/step/config.ex, test/elixir/lib/step/create_db.ex, test/elixir/lib/step/user.ex
This suppresses the following warnings emitted during `make exunit`:
```
==> couchdbtest
Compiling 12 files (.ex)
warning: variable "config_file" is unused (if the variable is not meant to be used, prefix it with an underscore)
test/elixir/lib/step/config.ex:15
warning: variable "setup" is unused (if the variable is not meant to be used, prefix it with an underscore)
test/elixir/lib/step/create_db.ex:44
warning: variable "step" is unused (if the variable is not meant to be used, prefix it with an underscore)
test/elixir/lib/step/create_db.ex:44
warning: variable "setup" is unused (if the variable is not meant to be used, prefix it with an underscore)
test/elixir/lib/step/user.ex:35
warning: variable "setup" is unused (if the variable is not meant to be used, prefix it with an underscore) …
```
=> Fix exunit compiler warnings

src/couch/priv/couch_ejson_compare/couch_ejson_compare.c, test/javascript/tests/design_docs.js
Fix `make javascript` on macOS. Found this while testing the SpiderMonkey 60 PR. Apparently something changed recently that broke really old code which admittedly had free after use bugs.
`make javascript`
=> Fix js tests

rel/files/couchdb.in
This is the continuation of commit 649b808 "Allow override of
`-args_file` and `-config` parameters (#1095)".
This allows setting the `-couch_ini` files location if needed, using
`COUCHDB_INI_FILES` env var:
- If unset (the default), `-couch_ini` argument won't be passed.
- If set (to a file, or list of files like
`COUCHDB_INI_FILES=/chroot/etc/couchdb/default.ini`
`/chroot/etc/couchdb/default.d ...`) it will allow running CouchDB with
different settings. A useful case is being able to run multiple
CouchDB servers on the same machine.
=> Allow override of `-couch_ini` parameter

configure
A .git directory found in src/ usually indicates that the code in the
enclosing directory is managed from said .git directory. This can lead
to confusion, and developers opening PRs against obsolete repos when, as
happens frequently, a formerly separate repository becomes integrated
into the primary repo.
This patch changes the configure script to warn when it finds such .git
directories.
Example output:
```
$ ./configure --dev --skip-deps
==> configuring couchdb in rel/couchdb.config
WARNING unexpected .git directory src/couch_tests/.git
WARNING unexpected .git directory src/rexi/.git
WARNING unexpected .git directory src/mem3/.git
WARNING unexpected .git directory src/smoosh/.git
WARNING unexpected .git directory src/couch_mrview/.git
WARNING unexpected .git directory src/couch/.git …
```
=> Warn about orphan .git directories

rebar.config.script
This adds 5 minutes to the 19.x Travis job.
=> Remove pause after Erlang version warning

src/fabric/src/fabric2_fdb.erl
Previously the per-request nonce value was set as the transaction name and so
in the trace logs multiple transactions ended up having the same `TransactionID`
which was pretty confusing.
To fix the issue, append a transaction ID to the name. The ID is guaranteed to
be unique for the life of the VM node.
=> Improve transaction name setting when tracing FDB transactions

Makefile, rel/overlay/etc/default.ini, src/couch/src/couch_db_updater.erl
Change the default security object for all databases, both clustered and local to admin only.
No additional testing is needed but the existing tests might need to authenticate where they didn't previously.
https://github.com/apache/couchdb/issues/2191
=> All databases now admin-only by default

build-aux/show-test-results.py
This allows developers to locate long running tests and errors after
running `make check`.
`make check`
`./build-aux/show-test-results.py --suites=25 --tests=25 --sort=fixture`
=> Add show-test-results.py script

src/couch_replicator/src/couch_replicator.erl, src/couch_replicator/src/couch_replicator_scheduler.erl, src/couch_replicator/src/couch_replicator_utils.erl
Instead of a string, null or object, it should now be only a null or an object.
https://github.com/apache/couchdb-documentation/pull/465
=> Switch replicator "info" error message to be an object

src/couch/rebar.config.script
This is a recurrence of #1450 caused by ec416c3
(SpiderMonkey 60 PR), where a case clause in
rebar.config.script lacks a match when configure
has not yet been run yet. Not being able to run 
make clean|distclean on a new checkout breaks
package building under Debian.
/cc @jiangphcn
=> Fix double "make clean" again

src/couch/src/couch_doc.erl, src/couch/src/couch_server.erl, src/couch/test/eunit/couch_db_doc_tests.erl
This is in preparation for [per-document access control](https://github.com/apache/couchdb/issues/assigned/janl) which is
going to use this field. We are adding this in 3.0 because per-
document access control will not be ready for 3.0, but added in
3.1 or later.
This commit allows a future version of CouchDB with per-document
access control to replicate with CouchDB 3.0, to make upgrades and
interoperability easy.
The per-documnet access control code is not going to store the
_access property in the document body like this patch does, but
is going to store it in an extra field inside of #doc and
assert access control for a document without having to load the
entire document body.
=> Allow special document member _access

rebar.config.script
This basically just extends the black list to cover the `21.{0,1}`
release range. This is due to a compiler bug [1] which is a duplicate of
[2].
[1] https://bugs.erlang.org/browse/ERL-981
[2] https://bugs.erlang.org/browse/ERL-807
---
I'm not 100% on this. Technically this range contains the bug as mentioned in the tickets, however I've got no idea if anywhere in our code base actually triggers the bug. I can't think of anyone that's reported mysterious errors on these versions but we're not running things against it in Travis either. So basically a big ol' shrug either way from me at this point. Though my risk adversity leans toward blacklisting.
=> Blacklist all 21.x releases older than 21.2.3

src/couch/priv/stats_descriptions.cfg, src/mango/src/mango_cursor.erl
see https://github.com/apache/couchdb/issues/1913
=> feat: add metric counter for unindexed mango queries. Closes #1913

rel/overlay/etc/default.ini, src/couch_log/src/couch_log_writer_journald.erl
based on the stderr logger but changed:
- doesn't output the timestamp, the journal already has a timestamp
- output the log level as <num> where num is defined as in `sd-daemon(3)`
https://www.freedesktop.org/software/systemd/man/sd-daemon.html
in local.ini:
```
[log]
writer = journald
```
run it as a systemd service:
```
systemd-run -E HOME=$HOME ./bin/couchdb
```
Before:
```
Feb 09 22:01:27 archaeopteryx couchdb[186]: [info] 2019-02-09T22:01:27.754346Z couchdb@127.0.0.1 <0.223.0> -------- Apache CouchDB 2.3.0-abafc2bf2 is starting.
Feb 09 22:01:27 archaeopteryx couchdb[186]: [info] 2019-02-09T22:01:27.754545Z couchdb@127.0.0.1 <0.224.0> -------- Starting couch_sup
Feb 09 22:01:27 archaeopteryx couchdb[186]: [notice] 2019-02-09T22:01:27.764981Z couchdb@127.0.0.1 <0.92.0> -------- …
```
=> a systemd-journald compatible log output on stderr

rel/overlay/etc/default.ini, src/couch/src/couch_bt_engine.erl, src/couch/src/couch_server.erl, src/couch/src/couch_util.erl, src/couch/test/eunit/couch_server_tests.erl
This makes `couch_server` able to handle quite a bit more load.
`make check`
=> Optimize couch server

src/couch/priv/couch_js/60/main.cpp, src/couch/priv/couch_js/60/util.cpp, src/couch/priv/couch_js/60/util.h, src/couch/test/eunit/couch_js_tests.erl, test/javascript/tests/auth_cache.js, test/javascript/tests/cookie_auth.js, test/javascript/tests/users_db.js, test/javascript/tests/utf8.js, test/javascript/tests/view_errors.js
Fix tests on SpiderMonkey 60. It turns out one of our tests is fast enough on the newer SpiderMonkey that it can cause an OOM before a timeout.
Fixes #2397 
`make check`
=> Sm 60 make oom errors fatal

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
When I added FreeBSD nodes to the Jenkins worker pool, builds started failing, because FreeBSD doesn't have docker.
This correctly uses the new `docker` label for machines capable of running containerised builds, everywhere it matters.
=> Jenkins: Use 'docker' label for dockerised builds

test/elixir/test/cookie_auth_test.exs
Adam K noticed that we aren't setting the session cookie correctly which
appears to have made this test fail randomly. Why its random and not
consistent is currently unknown.
Run on Jenkins
=> Set the session correctly

build-aux/Jenkinsfile.full
This PR drops Debian jessie, adds Debian buster, and adds CentOS 8 to the binary platform build matrix on `master`.
=> Jenkins: update binary platform matrix

src/fabric/src/fabric_view_all_docs.erl, src/fabric/src/fabric_view_map.erl, src/mango/src/mango_cursor_view.erl, src/mango/test/15-execution-stats-test.py
The previous implementation of Mango execution stats relied on
passing the docs_examined count from each shard to the coordinator
in the view_row record. This failed to collect the count of
documents read which weren't followed by a match (in a given shard).
For example, if an index was scanned but no documents were matched,
the docs_examined would be 0, when it should be equal to the number
of documents in the index.
This changes the implementation so that docs examined is passed
only when each shard has completed its index scan. This requires a new
handler in fabric so care needs to be taken if including this in a rolling cluster upgrade.
The work is split into 2 commits in order to support mixed-version upgrades. The first commit
includes only the message handlers, so can be safely …
=> Fix missing mango execution stats

src/smoosh/src/smoosh_server.erl
Start couch_log to make sure that couch_log_server process exists and is able to write log instead of getting noproc error during test.
```
smoosh_server:585: t_invalid_view...*failed*
in function gen_server:call/2 (gen_server.erl, line 206)
in call from couch_log:log/3 (src/couch_log.erl, line 73)
in call from smoosh_server:get_priority/2 (src/smoosh_server.erl, line 329)
in call from smoosh_server:'-t_invalid_view/1-fun-0-'/2 (src/smoosh_server.erl, line 587)
in call from smoosh_server:'-t_invalid_view/1-fun-3-'/2 (src/smoosh_server.erl, line 587)
**exit:{noproc,{gen_server,call,
[couch_log_server,
{log,{log_entry,warning,<0.32767.3>,
[70,97,105,108,101,100|...],
"--------",
["2020",45,[[...]|...],45|...]}}]}}
output:<<"">>
```
```
make check apps=smoosh
smoosh_server:520: …
```
=> Address flaky test failure on t_invalid_view/1

rel/files/couchdb.in
#2143 added a syntax error to couchdb.in, resulting in an error on startup:
```
/opt/couchdb/bin/couchdb: 51: /opt/couchdb/bin/couchdb: Syntax error: Unterminated quoted string
```
This adds the missing parentheses.
One way is to build the couchdb-dev image and check that it starts.
=> Fix missing parentheses in couchdb.in

src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_many_leaves_tests.erl
Design doc writes could fail on the target when replicating if with non-admin
credentials. Typically the replicator will skip over them and bump the
`doc_write_failures` counter. However, that relies on the POST request
returning a `200 OK` response. If the authentication scheme is implemented such
that the whole request fails if some docs don't have enough permission to be
written, then the replication job ends up crashing with an ugly exception and
gets stuck retrying forever. In order to accomodate that scanario write _design
docs in their separate requests just like we write attachments.
Fixes: #2415
=> Use separate requests to write design when replicating

Makefile
Since we switched from Travis to Jenkins, let's see how tests run without
retries in the new environment.
For reference, retries were introduced in: https://github.com/apache/couchdb/commit/220462a1dd2d921fc4ecba3488f5fedefb75217f
=> Remove EUnit retries on failure

src/couch_mrview/src/couch_mrview_index.erl, src/mem3/src/mem3_sync_event_listener.erl
We encountered a case_clause error when reading the header for a .view
file as the response was {ok, {Sig, nil}} where Sig is neither the
expected sig or the pre-upgrade sig (though surely the pre-1.2 goop is
not firing anymore).
We now log this specific issue and then proceed as if we found no
valid header.
=> Reset a view shard if the signature is wrong

src/couch_replicator/src/couch_replicator_api_wrap.erl, src/couch_replicator/src/couch_replicator_scheduler.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_error_reporting_tests.erl
Previously many HTTP requests failed noisily with `function_clause` errors.
Expect some of those failures and handle them better. There are mainly 3 types
of improvements:
1) Error messages are shorter. Instead of `function_clause` with a cryptic
internal fun names, return a simple marker like `bulk_docs_failed`
2) Include the error body if it was returned. HTTP failures besides the error
code may contain useful information in the body to help debug the failure.
3) Do not log or include the stack trace in the message. The error names are
enough to identify the place were they are generated so avoid spamming the
user and the logs with them. This is done by using `{shutdown, Error}` tuples
to bubble up the error the replication scheduler.
Fixes: https://github.com/apache/couchdb/issues/2413 …
=> Improve replicator error reporting

src/couch/src/couch_bt_engine.erl, src/dreyfus/src/dreyfus_httpd.erl, src/dreyfus/src/dreyfus_index_updater.erl, src/dreyfus/src/dreyfus_util.erl, src/mem3/src/mem3_rep.erl
We now only support OTP 20+, with 19 at a stretch. erlang:now/0
was deprecated in OTP 18, so we can now suppress these warnings:
```
/home/joant/couchdb/src/dreyfus/src/dreyfus_index_updater.erl:62: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
/home/joant/couchdb/src/dreyfus/src/dreyfus_index_updater.erl:83: Warning: erlang:now/0: Deprecated BIF. See the "Time and Time Correction in Erlang" chapter of the ERTS User's Guide for more information.
```
Also, some unused variables were removed:
```
/home/joant/couchdb/src/couch/src/couch_bt_engine.erl:997: Warning: variable 'NewSeq' is unused
/home/joant/couchdb/src/mem3/src/mem3_rep.erl:752: Warning: variable 'TMap' is unused …
```
=> Eliminate multiple compiler warnings

src/couch/priv/couch_js/60/main.cpp
We've had a number of segfaults in the `make javascript` test suite. The
few times we've been able to get core dumps all appear to indicate
something wrong in the JIT compiler. Disabling the JIT compilers appears
to prevent these segfaults.
=> Disable JIT compiler on SpiderMonkey 60

src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_stats.erl, src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_retain_stats_between_job_runs.erl, test/elixir/test/replication_test.exs
Two related fixes (as 2 separate commits):
1) Preserve replication job stats when jobs are re-created.
2) Properly account for replication stats when splitting bulk docs batches. 
Commit comments have better summaries but the main idea is improve how we keep track of replication stats. Some of those like `doc_write_failures` count is quite important.
=> Improve replication stats handling

.gitignore, rebar.config.script, rel/overlay/etc/default.ini, src/couch/src/couch_httpd_auth.erl, src/couch/test/exunit/same_site_cookie_tests.exs
Adds a new configuration field, `couch_httpd_auth.same_site` which sets the `SameSite` attribute of the CouchDB auth cookie. If no value is set (the default), no `SameSite` attribute is added.
This also updates Mochiweb to v2.20 as this is required for `SameSite` support.
Set the `samesite: strict` value in default.ini and verify that the SameSite attribute is detected by a browser (e.g. Chrome dev tools).
* Refs #2221
* Documentation PR: https://github.com/apache/couchdb-documentation/pull/473
=>  Update Mochiweb and add SameSite support to auth cookie

src/ken/rebar.config.script
After moving ken from https://github.com/apache/couchdb-ken to https://github.com/apache/couchdb/tree/master/src/ken. The directory structure related to ken is changed for downstream including Cloudant. Increase more way to detect presence of hastings for Ken so that Ken can work correctly for geospatial index.
make check apps=hastings
```
module 'hastings_bookmark'
module 'hastings_format_legacy_local'
module 'hastings_index_updater'
module 'hastings_purge_docs_test'
Hastings Purge Tests
hastings_purge_docs_test:69: test_purge_single...[0.494 s] ok
hastings_purge_docs_test:84: test_purge_multiple...[1.115 s] ok
hastings_purge_docs_test:103: test_purge_multiple2...[0.637 s] ok
hastings_purge_docs_test:129: …
```
=> Adjust way to detect presence of hastings for Ken

src/dreyfus/src/dreyfus_fabric.erl, src/dreyfus/src/dreyfus_fabric_group1.erl, src/dreyfus/src/dreyfus_fabric_group2.erl, src/dreyfus/src/dreyfus_fabric_info.erl, src/dreyfus/src/dreyfus_fabric_search.erl, src/dreyfus/src/dreyfus_util.erl, src/fabric/src/fabric_db_partition_info.erl, src/fabric/src/fabric_util.erl, src/fabric/src/fabric_view.erl
Previously any failed node or rexi worker error resulted in requests failing
immediately even though there were available workers to keep handling the
request. This was because the progress check function didn't account for the
fact that partition requests only use a handful of shards which, by design, do
not complete the full ring.
Here we fix both partition info queries and dreyfus search functionality. We
follow the pattern from fabric and pass through a set of "ring options" that
let the progress function know it is dealing with partitions instead of a full
ring.
make eunit
=> Fix fabric worker failures for partition requests

src/mem3/src/mem3_sync_event_listener.erl
Noticed mem3_sync_event_listner tests still fails intermetently, add a debug
log to it to hopefully find the cause of the failure.
=> Debug mem3_sync_event_listener flakiness

INSTALL.Unix.md, build-aux/Jenkinsfile.full, configure
Fixes #2449 and our "full" builds.
Includes modification to `configure` to disallow SM60+aarch64, and documents it in `INSTALL.Unix`.
What do you think @davisp @jiangphcn ?
=> [Jenkins] Revert to SM 1.8.5 for arm64

src/mango/src/mango_cursor.erl, src/mango/src/mango_cursor_special.erl, src/mango/src/mango_cursor_text.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_idx_text.erl, src/mango/src/mango_selector.erl, src/mango/src/mango_selector_text.erl, src/mango/src/mango_util.erl, src/mango/test/02-basic-find-test.py, src/mango/test/21-empty-selector-tests.py, src/mango/test/mango.py
Mango text indexes currently throw function clauses when queries in two
situations:
1) Empty Selector
2) Operators with empty arrays.
We fix this issue and change the behavior as follows:
1) Any empty selector will fall back on _all_docs (like json indexes).
2) $or, $and, $in, $all that specify an empty arrays
will be treated as no-op when combined with other operators.
3) A single no-nop query such as {"$or": []} will not be executed and
return nothing just like json indexes.
4) $nin with an empty array will return all docs that match the field,
just like json indexes.
New tests were added to the python suite and can be run with
MANGO_TEXT_INDEXES=1 nosetests test/21-empty-selector-tests.py
This requires a clouseau setup. 
The issue is this PR.
=> fix empty queries

rel/overlay/etc/default.ini, src/couch/priv/stats_descriptions.cfg, src/mango/src/mango_cursor.erl, src/mango/src/mango_cursor_text.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_execution_stats.erl, src/mango/src/mango_selector.erl, src/mango/test/05-index-selection-test.py, src/mango/test/12-use-correct-index-test.py
Improve instrumentation of Mango with the following metrics:
* `mango.query_invalid_index`: number of mango queries that generated an invalid index warning
* `mango, docs_examined`: number of documents examined by mango queries (the same value returned by execution_stats for individual queries). This is counted on the shard level (i.e. where the work occurs) rather than at the query coordinator.
* `mango.quorum_docs_examined`: number of documents examined by mango queries, using cluster quorum. These are always evaluated by the query coordinator.
* `mango.results_returned`: number of rows returned by mango queries
* `mango.query_time`: histogram of the length of time processing mango queries
* `mango.too_many_docs_scanned`: number of mango queries that generated an index scan warning
* …
=> Mango metrics

src/mango/src/mango_cursor_text.erl
When Mango text indexes fetch the doc object for each hit, a not_found atom may be returned if the indexed document revision no longer exists in the primary index (see [mango_cursor_text:get_json_docs/2](https://github.com/apache/couchdb/blob/bf6b98420c6a79c2f2d144edb4164b070b686afb/src/mango/src/mango_cursor_text.erl#L333)).
This manifests in the couchdb logs as:
```
req_err(2299526675) unknown_error : function_clause#012 [<<"mango_selector:match/2 L57">>,<<"mango_cursor_text:handle_hit/3 L182">>,<<"mango_cursor_text:handle_hits/2 L169">>,<<"mango_cursor_text:execute/1 L145">>,<<"mango_cursor_text:execute/3 L116">>,<<"mango_httpd:handle_find_req/2 L189">>,<<"mango_httpd:handle_req/2 L38">>,<<"chttpd:handle_req_after_auth/2 L322">>]
```
This commit handles this explicitly in …
=> Handle not_found atom in mango text indexes

test/elixir/README.md, test/elixir/lib/couch.ex, test/elixir/test/etags_head_test.exs, test/javascript/tests/etags_head.js
This fixes up the contribution from @jjrodrig 
https://github.com/apache/couchdb/pull/2464
Thank you!
A few minor updates to the original PR:
* Rebased & squashed the commits
* Disabled the javascript test
* Fixed an unused var in `test/elixir/lib/couch.ex`
=> Port etags tests to elixir

src/chttpd/src/chttpd_auth.erl, src/couch/src/couch_httpd_auth.erl
In #2411 we introduced a setting to allow _up to not require authentication when require_valid_user is set to true. However it was flawed and caused an infinite loop, rendering the /_up handler ineffective.
We move the check to the party_mode_handler and remove the infinite loop.
dev/run with all combinations of the two config flags, _up handler called with curl to confirm behaviour.
#2411 for original PR that this corrects.
=> Fix infinite loop in default_authentication_handler

src/couch/src/couch_sup.erl
Changes the URI logged at startup to report the address(es) that
`chttpd` is bound to rather than `httpd`. Previously it was a bit
confusing that it always reported that Couch had started on
port 5986 which is deprecated and not intended to be user-facing.
Start CouchDB and check that the log reports the URI that you use to interact with Couch.
=> Log clustered URIs at startup

src/chttpd/src/chttpd_node.erl, test/elixir/test/config_test.exs
Using the backend port 5986 it was possible to reload config from disk
using the _config/_reload endpoint. This ports it to the `/_node` API on the frontend port.
Launch CouchDB e.g. using `./dev/run`. Change the `local.ini` somehow and run:
```
curl localhost:15984/_node/_local/_config/_reload -XPOST
```
Verify the change using 
```
curl localhost:15984/_node/_local/_config`
```
=> Add POST /_node/<node>/_config/_reload

mix.exs, rebar.config.script, src/couch/include/couch_eunit_proper.hrl, src/couch/rebar.config.script, src/couch/test/eunit/couch_key_tree_prop_tests.erl, src/mem3/rebar.config.script, src/mem3/test/eunit/mem3_ring_prop_tests.erl
It was already used in the IOQ2 work so all the plumbing to pull it in during
dev testing was there and it seems awkward to have two different property
testing framework for just a handful of tests.
It is still an optional component and is not included in the release.
=> Replace Triq with PropEr

src/chttpd/src/chttpd.erl, src/ctrace/README.md
This PR adds an ability to selectively enable opentracing for HTTP requests
with X-B3-... headers. This is helpful in following cases:
- tracing all requests with X-B3-... headers
`all = (#{external := E}) when E == true -> true`
- tracing all requests to specific database with X-B3-... headers
```
all = (#{external := E, 'db.name' := Db})
when E == true andalso Db == <<"foo">> -> true
```
- tracing requests to specific endpoint with X-B3-... headers
```
db.design.view.read = (#{external := E, 'design.id' := Name})
when E == true andalso Name == <<"bar">> -> true
```
I want to remind that we support following X-B3-... headers:
- `X-B3-TraceId`
- `X-B3-SpanId`
- `X-B3-ParentSpanId`
- `B3` which is in the following format
`<TraceId>-<SpanId>-<1 | 0>-<ParentSpanId>`
0. Run test suite …
=> Add `external`  tag to opentrace events

build-aux/show-test-results.py, src/mango/test/15-execution-stats-test.py, src/mango/test/21-empty-selector-tests.py
```
would reformat /home/jenkins/couchdb/build-aux/show-test-results.py
would reformat /home/jenkins/couchdb/src/mango/test/15-execution-stats-test.py
would reformat /home/jenkins/couchdb/src/mango/test/21-empty-selector-tests.py
Oh no! 💥 💔 💥
3 files would be reformatted, 29 files would be left unchanged.
make[1]: *** [Makefile:214: python-black] Error 1
```
=> Python black cleanups

src/couch_views/include/couch_views.hrl, src/couch_views/src/couch_views_fdb.erl, src/couch_views/src/couch_views_reader.erl
Changes map indexes to store the original key and value in a single
FDB row.
All tests should pass
=> Change map indexes to be stored in one row

src/dreyfus/src/dreyfus_fabric_search.erl
Previously we erroneously got ring opts before and after figuring out live
shards if some shards were not live there was a badmatch failure.
=> Remove reduntant get_ring_opts call in in dreyfus_fabric_search

src/couch/src/couch_util.erl
In a59540132 we introduced a default increase in process priority for `couch_server` to high.
While tracking down #2437 , I managed to git bisect the problem to this commit.
This lead me to this thread on erlang-questions:
http://erlang.org/pipermail/erlang-questions/2018-June/095677.html
Notably:
> a single high-priority process in a tight loop stops all other processes, including those of max priority.
This problem surfaces on Erlang 21 and 22 specifically - and is exactly what we're seeing.
While we could do a specific version check, I think it would be healthier for now to disable this specific optimization by default, and only re-enable once we can track down what's going on in 21/22 that is causing scheduler collapse in this fashion.
`while true; do make eunit apps=mem3; done` …
=> Revert default priority change for couch_server

rel/overlay/etc/default.ini
Left this out of #2487 by accident - update to `default.ini`
=> Revert prio flag in default.ini

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
Docker images have updated versions of Erlang - so Jenkinsfile must follow.
Unfortunately this breaks PRs until this PR is merged, because now `couchdbdev/debian-buster-erlang-all` has different versions of Erlang in it than `Jenkinsfile.pr` does.
We can possibly factor some of this out and avoid the PR-blocking change by having the `-all` image have aliases like `/usr/local/kerl/{low,medium,high}/activate` to the three versions.
The `Jenkinsfile.full` version needs to be explicit so that packages are built appropriately for downstream.
At one point @kocolosk wanted to use tagging to improve build times and avoid the forced pull every time, but my experience was that when tags move, docker doesn't always pick it up, leading us back to having to merge a PR every time we want or need to …
=> Jenkins: bump Erlang versions

src/mango/src/mango_selector_text.erl, src/mango/test/06-basic-text-test.py, src/mango/test/user_docs.py
When a user issues a range query $lt, $lte, $gt, $gte for text indexes,
the query is translated into a MIN, MAX range query against clouseau.
If not quoted, an error occurs:
```
{"error":"text_search_error","reason":"Cannot parse
'(a_3astring:[\"\" TO string\\ containing\\ space})'..}
```
This is because the string is broken up into 3 tokens which the parser
cannot parse. If we add quotes to the string, the the range query works
correctly.
Tests added to mango test suites, but requires clouseau to be setup. Text tests have already
been run and passes.
=> quote strings for all text values

rebar.config.script
Bump ioq to 2.1.3 to get rid of repetitive "Missing stats db" errors
ref: https://github.com/apache/couchdb-ioq/commit/4843f3709b4be997cf8424c44f856523fd31b7d1
=> Bump ioq to 2.1.3

.gitignore, rebar.config.script
Closes #2391 except for bumping Fauxton and docs.
@willholley can you tell me if we need the last couple of changes in Fauxton in 3.0.0 or not?
@davisp Do we need the changes to jiffy in CouchDB? We're fairly far back on that dependency.
=> bump ets_lru, khash revs

src/couch_expiring_cache/src/couch_expiring_cache_server.erl
This ets table was a holdover from when couch_expiring_cache was a non-
library OTP application. It is unused, and would prevent multiple users
of the library in the same project.
```
make eunit apps=couch_expiring_cache
```
=> Delete unused ets table creation

src/setup/src/setup.erl
Per the topic and discussion over in #2463 , it's probably best if we don't auto-create this in the setup wizard anymore.
=> Setup wizard: do not create _global_changes

rebar.config.script, rel/overlay/etc/default.ini, src/ctrace/README.md, src/ctrace/src/ctrace_config.erl
This PR adds support for http reporter for open tracing library. The http reporter is useful in following two cases:
- when you deployment doesn't include jaeger agents and you want to communicate directly to jaeger server
- when spans are greater than max udp packet size (65Kb).
1. update rel/overlay/etc/default.ini as follows
```
diff --git a/rel/overlay/etc/default.ini b/rel/overlay/etc/default.ini
index 592445c28..69091eab3 100644
--- a/rel/overlay/etc/default.ini
+++ b/rel/overlay/etc/default.ini
@@ -572,15 +572,15 @@ min_priority = 2.0
;   - jaeger.thrift over udp
;   - jaeger.thrift over http
; ## Common settings
-; enabled = false ; true | false
-; app_name = couchdb ; value to use for the `location.application` tag
-; protocol = udp ; udp | http - which reporter to use
+enabled = …
```
=> Add http reporter

Makefile, build-aux/couchdb-build-release.sh
This ensures that the only place an RC tag is visible is in the final
tarball. To ensure we can identify CouchDB versions in the wild, each
OTP app has the original git sha placed in the {id, :hash} field.
Plus a little bit of style cleanup.
Big thanks to @dch for starting this in #1927.
```
git tag -a 3.0.0-RC1 -m "3.0.0-RC1"
make dist
grep vsn apache-couchdb-3.0.0-RC1/src/couch/src/couch.app.src
git tag -d 3.0.0-RC1
rm -rf apache-couchdb-3.0.0-RC1*
```
Replaces #1927 
- [N/A] Changes are covered by tests
- [N/A] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [N/A] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation
=> Stop propagating RC tags into dist archive

src/chttpd/src/chttpd_node.erl, src/couch/src/couch_httpd.erl, src/couch/src/couch_httpd_db.erl
In #2336 we removed node-local HTTP access and redirected all traffic through `/_node/{node-name}/...`. This sneakily routes a new MochiWeb request through to couch_httpd under the covers.
Unfortunately, in the process we ended up URL-decoding the URL, meaning the passed-through URL couldn't include `%2F` for accessing individual shards.
This reintroduces URL encoding to fix the problem.
It also introduces support to query a specific view shard through `/_node/{node-name}/{db-shard}/{ddoc}/`. This allows inspection of individual view shard sizes.
```
dev/run -n 1 -a admin:password
curl -X PUT http://admin:password@localhost:15984/abc
curl -X PUT http://admin:password@localhost:15984/abc/_design%2ffoo -d '{"language":"javascript","views":{"all":{"map":"function(doc) { emit(doc._id, …
```
=> Fix node-specific shard access via HTTP

.gitignore, LICENSE, NOTICE, rebar.config.script, rel/reltool.config
Adds `recon` to our releases. 
All of these should succeed:
```
make check
make release && rel/couchdb/bin/couchdb & && rel/couchdb/bin/remsh
make dist && ls apache-couchdb-*/src/recon
```
Closes #2510 .
- [N/A] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [Pending] A PR for documentation changes has been made in https://github.com/apache/couchdb-documentation
=> Add recon for user convenience

src/mango/src/mango_cursor.erl, src/mango/test/05-index-selection-test.py, src/mango/test/12-use-correct-index-test.py
The CouchDB API defines the warning field returned by _find to be
a string (and this is what Fauxton expects). 5d55e289 was missing
a string conversion and returned the warning(s) as an array. This
restores the intended behaviour.
Run the mango unit tests.
https://github.com/apache/couchdb/commit/5d55e289760959eb2fc228acb2ed00d57ddd4dee
=> Return mango warnings as a delimited string

mix.exs, mix.lock, src/chttpd/src/chttpd.erl, src/chttpd/test/exunit/test_helper.exs, src/chttpd/test/exunit/tracing_test.exs, test/elixir/lib/couch.ex
The B3 header parsing introduced in https://github.com/apache/couchdb/pull/2309 is broken. When b3 header is set the chttpd request is crashing with the following message:
```
[error] 2020-02-03T21:25:39.049590Z dbcore@172.30.138.101 <0.23004.0> -------- CRASH REPORT Process  (<0.23004.0>) with 0 neighbors crashed with reason: bad argument in call to binary:split("C10B5B9C9F06385D04BD6B3A57971D8C-1AEA26A4FE496E13-0000000000000000", <<"-">>, [global]) at 
chttpd:get_trace_headers/1(line:1305) 
<= chttpd:root_span_options/1(line:1271) 
<= chttpd:start_span/1(line:1253) 
<= chttpd:before_request/1(line:270) 
<= chttpd:handle_request_int/1(line:243) 
<= mochiweb_http:headers/6(line:128) 
<= proc_lib:init_p_do_apply/3(line:247); 
initial_call: …
```
=> Fix b3 header

src/dreyfus/src/dreyfus_httpd.erl, test/javascript/tests/view_errors.js
Fixes #2520
we misspelled the key name for highlight_post_tag, so it was not translated into query params.
Verify that the post tag substitution happens;
curl localhost:5984/db1/_design/bar/_search/bar -Hcontent-type:application/json -d '{"q":"foo:piece", "highlight_fields": ["foo"], "highlight_pre_tag":">", "highlight_post_tag":"<"}'
https://github.com/apache/couchdb/issues/2520
=> Fix highlight_post_tag parsing from json request body

Makefile, Makefile.win
In progress - not yet tested - attempt to normalise `Makefile` and `Makefile.win` ahead of our 3.0.0 release.
Time permitting, Monday I'll get my Windows environment set up again, with the latest build chain and SM60, and make sure this does what we expect.
=> Makefile parity; remove [un]install tgts

src/couch/src/couch_auth_cache.erl, src/couch/src/couch_secondary_sup.erl, src/couch/test/eunit/couch_auth_cache_tests.erl, test/javascript/tests/reader_acl.js, test/javascript/tests/security_validation.js
Since the backend port is closed by default, remove the cache service
since it was shown to cause monitor leaks, and it just consumes resources
running in the background when almost nobody uses it. The few utility scripts
that might use the backend port can just get the auth docs directly from the
db.
Issue: https://github.com/apache/couchdb/issues/2493
(Thanks to @davisp for the code snippet and the original idea)
=> Simplify couch_auth_cache

src/couch_replicator/src/couch_replicator_clustering.erl
Observed on FreeBSD Jenkins test runner:
```
function couch_replicator_clustering:setup/0 (src/couch_replicator_clustering.erl, line 257)
**error:{badmatch,{error,{already_started,<0.3165.0>}}} in module 'couch_replicator_clustering'
```
=> Fix race condition in couch_replicator_clustering eunit setup

rebar.config.script
bump the docs repo to new 3.0.0 tag
closes #2509
=> bump docs repo

test/elixir/README.md, test/elixir/test/reduce_builtin_test.exs, test/elixir/test/reduce_false_test.exs
This PR ports reduce_false and reduce_builtin tests into Elixir test suite. I've checked the reduce_false_temp but it seems it's been contempled by reduce_false, so I have not included it in.
```
make elixir tests=test/elixir/test/reduce_false.exs
make elixir tests=test/elixir/test/reduce_builtin_test.exs
```
=> Port reduce_false.js and reduce_builtin.js to Elixir

src/chttpd/src/chttpd_db.erl, src/fabric/src/fabric2_util.erl, test/elixir/test/all_docs_test.exs
Encodes the startkey/endkey so that if a startkey is not binary it will return the expected results.
=> Encode startkey/endkey for all_docs

build-aux/Jenkinsfile.full
CentOS 8 now supports SM 60. This matches the changes over in couchdb-ci and couchdb-pkg:
https://github.com/apache/couchdb-ci/commit/1a6f6f7ec3590c13fa624c97deb5e78fea881ed7
https://github.com/apache/couchdb-pkg/commit/31a57df88666ab483cc81aee7e5abeb265c10767
We'll need to merge this to `3.x` and `3.0.x` as well.
=> Bump SM to 60 on CentOS 8

src/fabric/test/fabric2_doc_att_tests.erl
Attachment names should all be binaries.
=> Fix doc attachment tests

src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_changes_fold_tests.erl, src/fabric/test/fabric2_test.hrl
This is a 3rd approach.
Simplified even more after talking with @davisp 
This one is driven by an optioned passed in to fold_range. There is also just a single fold_range callback as opposed to two as before.
Previous approach: https://github.com/apache/couchdb/pull/2532
=> Use multi-transactional iterators

src/couch_views/src/couch_views_indexer.erl
Index builder performs writes in the same transaction as the changes feed so we can't use iterators as they disable writes.
=> Use {restart_tx, false} option in view index builder changes feed

src/couch/src/couch_util.erl, src/couch/test/eunit/couch_util_tests.erl
It can be desirable in some cases for decoded JSON to e.g. return
maps instead of the default data structure, which is not currently
possible.
This exposes a new function `couch_util:decode/2`, the second
parameter being a list of options passed to `jiffy:decode/2`.
```
$ make eunit apps=couch suites=couch_util_tests tests=json_decode_test_
```
=> Expose `couch_util:decode/2` to support jiffy options

src/couch_mrview/src/couch_mrview_index.erl
I found a .view file with a db_header in production (cause unknown but
I'm hoping it's manual intervention).
This patch means we'll reset the index if we find something other than
a view header when looking for one.
Not entirely sure tbh, renaming and moving a .couch file to a .view maybe?
https://github.com/apache/couchdb/pull/2438
=> Reset if we don't get a view header

src/mem3/src/mem3_sync.erl, src/mem3/test/eunit/mem3_seeds_test.erl
After commit 27bb45043435828915bdcbdc130b685e5533bbd8 local _users is only
created the first time it is used. So in most case it's expected to not exist.
Update local_dbs to return it only if it is actually created.
=> Handle possibly missing local _users db in mem3_sync:local_dbs()

src/chttpd/src/chttpd_db.erl
Previously each doc was read in a separate transaction. It turns out that size limits do not apply to read-only transactions so we don't have to worry about that here. Also transaction restart are already implemented so we don't have to worry about timeouts either.
=> Re-use changes feed main transaction when including docs

src/couch_jobs/src/couch_jobs.erl, src/couch_jobs/src/couch_jobs_type_monitor.erl, src/fabric/include/fabric2.hrl
We already handle them in couch_jobs_type_monitor so let's do it in
`couch_jobs:wait_pending` as well. Recent fixes in FDB 6.2 didn't completely
fix the issue and there are still spurious 1009 errors dumped in the logs. They
seem to be benign as far as couch_jobs operation goes as type monitor code
already showed, so let's not pollute the logs with them.
=> Handle spurious 1009 (future_version) errors in couch_jobs pending

src/couch_jobs/src/couch_jobs.hrl, src/couch_jobs/src/couch_jobs_fdb.erl, src/couch_jobs/test/couch_jobs_tests.erl
Previously, if the metadata key is bumped in a transaction the same transaction
could not be used to add jobs with `couch_jobs`. That's because metadata is a
versionstamped value, and when set, it cannot be read back until that
transaction has committed. In `fabric2_fdb` there is a process dict key that is
set which declares that metadata was already read, which happens before any db
update, however `couch_jobs` uses it's own caching mechanism and doesn't know
about that pdict key.
It would be tempting to re-use the same pdict key and just set it from
whichever module calls `ensure_current`, however that would be incorrect, as
the two modules don't actually share the same `Db` handle objects, so they do
need to re-read the most recent key.
Ideally we'd implement a single `couch_fdb` …
=> Let couch_jobs use its own metadata key

rebar.config.script, rel/overlay/etc/default.ini, src/chttpd/src/chttpd_auth_request.erl
This diverges from `3.0.x` by riding `3.0.0`; we want the `-RC3` tag in `3.0.x` because it will be invariant. `3.0.0` as a tag may move with late breaking announcements / warnings about 3.0.0, possibly found after its release.
Now also with cherry-picked fix from #2576.
=> bump 3.x docs to actual 3.0.0 tag

src/fabric/test/fabric2_db_misc_tests.erl
It's possible for other couch_epi plugins to interfere with this test,
so mock `couch_epi:decide/5` to always return `no_decision`.
```
make eunit apps=fabric suites=fabric2_db_misc_tests
```
=> Improve validate_dbname test

src/couch/priv/stats_descriptions.cfg
We started to emit that in CouchDB 4.x for temporary views and possibly other endpoints.
=> Add 410 status code to stats_descriptions

test/elixir/lib/couch.ex
This PR fixes few replicator elixir tests. The tests were broken by https://github.com/apache/couchdb/pull/2519
```
git clean -xffd && ./configure --dev && make && make elixir tests=test/elixir/test/replication_test.exs
```
I have two tests still failing locally. However these two were failing prior to https://github.com/apache/couchdb/pull/2519.
* https://github.com/apache/couchdb/pull/2519
=> Fix base url in tests

test/elixir/test/changes_async_test.exs, test/elixir/test/changes_test.exs, test/javascript/tests/changes.js
This PR ports the changes.js test suite into the elixir test suite. 
I've found in changes.js a significant amount of code that is not being executed as it expected to be executed in a browser or it is commented. I've recovered these test cases and placed into changes_async_test.exs where asynchronous changes operations are tested. Synchronous operations are tested at changes_test.exs. 
```
make elixir tests=test/elixir/test/changes_test.exs
make elixir tests=test/elixir/test/changes_async_test.exs
```
N/A
=> Port changes.js test suite into elixir

src/chttpd/src/chttpd_changes.erl
Since we started re-using the main changes feed transaction to open the docs 1bceb55, we also started to pass the transactional db handle to the ddoc cache. However ddoc cache uses a `spawn_monitor` to open docs, and since our transaction objects are tied to the owner process the open was failing with a `badarg` error from erlfdb.
```
make eunit apps=fabric,couch_jobs,couch_views
```
and
```
make elixir tests=test/elixir/test/basics_test.exs,test/elixir/test/replication_test.exs,test/elixir/test/map_test.exs,test/elixir/test/all_docs_test.exs,test/elixir/test/bulk_docs_test.exs
```
=> Do not use the ddoc cache to load filter design documents

src/mem3/src/mem3_sync_event_listener.erl
There's a race between the meck:wait call in setup and killing the
config_event process. Its possible that we could kill and restart the
config_event process after meck:wait returns, but before
gen_event:add_sup_handler is called. More likely, we could end up
killing the config_event gen_event process before its fully handled the
add_sup_handler message and linked the notifier pid.
This avoids the race by waiting for config_event to return that it has
processed the add_sup_handler message instead of relying on meck:wait
for the subscription call.
=> Fix mem3_sync_event_listener test

test/elixir/README.md, test/elixir/test/form_submit_test.exs, test/javascript/tests/form_submit.js
Ported `form_submit` js test to Elixir
Just issue `make elixir`
None
=> Port form_submit.js test to Elixir

src/fabric/src/fabric_db_create.erl, src/fabric/test/eunit/fabric_db_create_tests.erl
Previously concurrent db creation requests could get past `db_exists/1` and try
to create the db shard document. The first one would succeed but others could
fail with a `500 {"error":"error", "reason":"conflict"}` error instead of `412`.
Handle the race condition by checking if db exists after getting a conflict
error and return a 412 response.
Fixes: #2613
```
make eunit apps=fabric suites=fabric_db_create_tests
```
To verify the validity of the test can comment out the `{error, conflict}` clause and it should fail in the `?assertEqual` line with a `conflict error` instead of `file_exists`
=> Handle race condition during concurrent db creation

test/elixir/README.md, test/elixir/test/form_submit_test.exs, test/javascript/tests/form_submit.js
Ref.: picking #2608 commits and porting them to the 3.0.x branch
=> Port form submit test to elixir in 3.0.x

rel/overlay/etc/default.ini, src/couch_views/src/couch_views_fdb.erl, src/couch_views/src/couch_views_indexer.erl, src/couch_views/test/couch_views_indexer_test.erl
Limits the size that a key and value that can be indexed in a map function.
If the key or value exceeds the size the document is not indexed for the design document and an error is logged.
`make eunit app=couch_views`
=> Fdb set view limits

src/chttpd/src/chttpd.erl
Sometime it is useful to be able to trigger open tracing using single header in the request. 
For such cases this PR introduces `X-Couch-Trace` header. This header combined with the following config in `default.ini` would cause tracing of the request. 
```
[tracing.filters]
all = (#{external := External}) when External == true -> true
```
*Note*: 
- We check for existence of the header and don't care about its value
- This feature could allow malicious user to launch resource exhaustion attack on tracing infrastructure (elastic search backend of jaeger). You are absolutely safe if you don't use `(#{external := External}) when External == true`.
1. update rel/overlay/etc/default.ini as follows
```
diff --git a/rel/overlay/etc/default.ini b/rel/overlay/etc/default.ini
index …
```
=> Add support for X-Couch-Trace header

build-aux/Jenkinsfile.full
[21:53:08]  <+Wohali>	jan____: If you want to add Mac build support, you need to edit apache/couchdb:build-aux/Jenkinsfile.full
[21:53:18]  <+Wohali>	I don't think you want to add a Mac build to every PR, do you? Just the main builds, yeah?
[21:53:51]  <+Wohali>	You'll want to clone the section for FreeBSD:  https://github.com/apache/couchdb/blob/master/build-aux/Jenkinsfile.full#L126-L159
=> feat: add mac ci

src/mango/rebar.config, src/mango/test/mango.py, src/mango/test/user_docs.py
Mango Python tests don't always clean up after themselves. This deletes databases and documents created by the tests.
```
nosetests --nocapture src/mango/test
```
Before this PR, running the tests as above will leave databases and users docs around. With this PR applied, those databases and docs get deleted.
=> Clean up mango test dbs and docs

src/mango/README.md, src/mango/TODO.md, src/mango/test/README.md
This reformats the Mango README and TODO documents to be easier to read
and maintain by wrapping long lines, and removing trailing whitespace.
This was originally included in the `fdb-mango-index` branch work, but has been moved into a separate commit to make it easier to apply to maintenance branches.
N/A
=> Improve mango markdown

src/couch_views/src/couch_views_fdb.erl, src/couch_views/src/couch_views_indexer.erl, src/couch_views/test/couch_views_indexer_test.erl
Clean up view size limit enforcement
Both a performance and style cleanup. This reduces the number of ets
calls by roughly `2 * 2 * $num_docs * $num_views`. The first factor of
two is because this avoids re-calculating the size twice for both the id
and map indexes. The second factor of two is because we have to lookup
two different settings.
Stylistically this also moves the logic out of the fdb modules. Keeping
key/value structure and update logic is already pretty complicated so we
should avoid mixing external application logic into those modules as
much as possible for our sanity.
The behavior is slightly changed vs the original patch as well.
Originally only the view that contained the errant key or value was
affected. However, pre-existing behavior where a document fails to be …
=> Clean up view size limit enforcement

rel/overlay/etc/default.ini
This PR makes puts the "users_db_security_editable" configuration option in the correct location in the ini file.
This PR fixes issue #2643
=> Move "users_db_security_editable" to the correct location in the ini file

rel/files/eunit.ini, rel/overlay/etc/default.ini, src/couch_jobs/src/couch_jobs_fdb.erl, src/couch_jobs/test/couch_jobs_tests.erl, src/couch_views/src/couch_views.erl, src/couch_views/src/couch_views_sup.erl, src/couch_views/test/couch_views_indexer_test.erl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_index.erl, src/fabric/src/fabric2_sup.erl, src/fabric/test/fabric2_index_tests.erl
Implement a simple index auto-updater
The main logic is as follows:
- After doc update transaction(s) are completed in the `fabric2_db` module,
call the `fabric2_index:db_updated(Db)` function.
- `fabric2_index:db_updated(Db)` inserts a `{DbName, Timestamp}` tuple into
one of the sharded ets tables. The tuple is inserted using `ets:insert_new`,
which ensures only the first entry succeeds and others will be ignored,
until that entry is cleared.
- Each ets table in `fabric2_index` has a simple monitor process that
periodically scans that table. If it finds databases which have been
updated, it notifies all the indices which have registered with
`fabric2_index` to build indices.
Index auto-building is enabled for couch_views application in a separate commit.
Then there is another commit to …
=> Index auto-updater

src/fabric/src/fabric2_fdb.erl, test/elixir/test/map_test.exs
Fixes an issue where the first k/v was skipped if the startkey_docid
was included.
tests should pass
This is needed for #2585
=> Fix bug in reverse folding with startkey_docid

src/couch_jobs/src/couch_jobs.erl, src/couch_jobs/src/couch_jobs_fdb.erl, src/couch_jobs/test/couch_jobs_tests.erl
When a job is either pending or finished and the job is resubmitted
with new data the job data is updated.
Tests should pass
This is needed for #2585
=> couch_jobs resubmit updates job data

src/chttpd/src/chttpd_changes.erl
Use `fabric2_db:is_clustered/1` instead of `couch_db:is_clustered`
=> Fix _changes with a _view filter

src/couch_expiring_cache/src/couch_expiring_cache_server.erl
Seeing log errors like the following:
```
CRASH REPORT Process epep_fdb_decision_cache (<0.633.0>) with 0 neighbors exited with reason: {bad_info,{#Ref<0.2506675824.3127640065.49278>,ready}} at gen_server:handle_common_reply/8(line:726) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {couch_expiring_cache_server,init,['Argument__1']}, ancestors: [epep_sup,<0.596.0>], message_queue_len: 0, messages: [], links: [<0.614.0>], dictionary: [{rand_seed,{#{bits => 58,jump => #Fun<rand.8.15449617>,next => #Fun<..>,...},...}},...], trap_exit: false, status: running, heap_size: 2586, stack_size: 27, reductions: 7493102
```
This should handle those errors, and prevent the crashes.
=> Handle spurious erlfdb future

src/fabric/src/fabric_rpc.erl
If a filtered changes feed hit a rewind we would send a bare `integer()`
value for the Seq. If this was used again during a rewind it causes a
competely rewind to zero due to not having the `node()` and UUID
`binary()` values to calculate a new start seq.
=> Send correct seq values for filtered changes

src/couch/src/couch_httpd_auth.erl, src/couch/test/eunit/couchdb_cookie_domain_tests.erl
We failed to set the domain attribute when deleting the session cookie, resulting in the creation of an empty cookie without a domain attribute instead.
Follow the steps in the related case and note that the cookie is deleted with this patch.
https://github.com/apache/couchdb/issues/2655
=> Set cookie domain when DELETE'ing

src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_db_crud_tests.erl
Previously those endoints would break when transactions time-out and are retried. To fix it we re-use the mechanism from changes feeds.
There is a longer discussion about this on the mailing list:
https://lists.apache.org/thread.html/r02cee7045cac4722e1682bb69ba0ec791f5cce025597d0099fb34033%40%3Cdev.couchdb.apache.org%3E
=> Handle transaction timeouts in list_dbs and list_dbs_info

src/jwtf/src/jwtf.erl, src/jwtf/test/jwtf_tests.erl
The "alg" check can now take list of algorithms that are supported,
which must be from the valid list of algorithms.
The new functionality is covered by eunit tests.
https://github.com/apache/couchdb/pull/2648/
=> Enhance alg check

src/fabric/src/fabric2_util.erl, src/fabric/test/fabric2_changes_fold_tests.erl, src/fabric/test/fabric2_db_crud_tests.erl, src/fabric/test/fabric2_test_util.erl
* There was a good amount of duplication between `_db_crud_tests` and
`_changes_fold_tests`, so make a common test utility module so both suites can
use.
* Clean up test names. Previously some were named `tx_too_long` but since the
official FDB error is `transaction_too_old` rename them to match a bit
better.
* `list_dbs_info` implementation uses queue of 100 futures to parallelize fetching.
So its test was updated to create more than 100 dbs. Creating 100 dbs took
about 3 seconds so added a small parallel map (pmap) utility function to help
with that.
To test:
`make check-fdb`
=> Refactor "tx too old" tests

Makefile, dev/run, src/mango/test/user_docs.py, test/elixir/README.md, test/elixir/lib/couch.ex, test/elixir/test/config/test-config.ini, test/elixir/test/proxyauth_test.exs, test/elixir/test/users_db_test.exs, test/javascript/tests/proxyauth.js
This PR ports the proxyauth tests from js to elixir. This test was disabled in the js test suite.
The proxy_authentication_handler should be enabled at startup as the changes on chttpd.authentication_handlers config property is not hot-reloaded by CouchDB. An option has ben added to the dev/run script in order to specify a config file to be placed at etc/local.d folder.
Makefile for elixir target now includes a custom config file that enables all the auth handlers for testing.
```
make elixir tests=test/elixir/test/proxyauth_test.exs
```
for checking new dev/run option:
```
dev/run -n 1 --locald-config test/elixir/test/config/test-config.ini
```
should place the test-config.ini file at dev/lib/node1/etc/local.d folder
This PR allows to #2648 to include integration tests for the new JWT …
=> Port elixir proxyauth tests from js to elixir

src/jwtf/src/jwtf.erl, src/jwtf/test/jwtf_tests.erl
Throw if an unknown check is passed to jwtf:decode
N/A
https://github.com/apache/couchdb/pull/2648
=> Throw if an unknown check is passed to jwtf:decode

src/fabric/test/fabric2_db_crud_tests.erl
* Made a silly error building the accumulator list:
`[Row, Acc]` -> `[Row | Acc]`
* Left some debugging code in `list_dbs_tx_too_old` test
The test was supposed to setup only 1 failure in the user callback
Check with:
```
make eunit apps=fabric suites=fabric2_db_crud_tests
```
=> A few minor cleanups in fabric2_db_crud_tests

src/couch_views/src/couch_views_indexer.erl, src/fabric/src/fabric2_db.erl, test/elixir/test/map_test.exs
If a doc has more than 1 branch add the conflict revs to the _conflicts field of the view so that
it can be used when the doc is mapped.
```
$ mix test test/elixir/test/maps_test.exs
```
=> add _conflicts field to docs for views

src/chttpd/src/chttpd_db.erl, src/fabric/test/fabric2_doc_fold_tests.erl
Previously transactions could time-out, retry and re-emit the same data. Use
the same mechanism as the _list_dbs and _changes feeds to fix it. Additional
detail in the mailing list discussion:
https://lists.apache.org/thread.html/r02cee7045cac4722e1682bb69ba0ec791f5cce025597d0099fb34033%40%3Cdev.couchdb.apache.org%3E
```
make check-fdb
```
=> Handle transaction timeouts in _all_docs

test/elixir/README.md, test/elixir/test/design_docs_test.exs, test/javascript/tests/design_docs.js
This PR ports the design_docs.js test suite into the elixir test suite
```
make elixir tests=test/elixir/test/design_docs_test.exs
```
N/A
=> Port design_docs.js tests from js into elixir

test/elixir/README.md, test/elixir/test/design_docs_test.exs, test/javascript/tests/design_docs.js
Port design_docs tests from js to elixir
Merging #2641 into 3.0.x
=> Port design_docs tests from js to elixir (#2641) - 3.0.x

test/elixir/README.md, test/elixir/test/design_docs_test.exs, test/javascript/tests/design_docs.js
Port design_docs tests from js to elixir 
Merging #2641 into 3.x
=> Port design_docs tests from js to elixir (#2641) - 3.x

test/elixir/test/utf8_test.exs
Just a little fix: we had an unused variable inside the utf8 test suite.
Just issue `make elixir` or have a look at the CI
=> Ignore unused string variable inside utf8 test case

rel/overlay/etc/default.ini, src/smoosh/src/smoosh_server.erl
1. Normalise code against 3.0 `default.ini` values
1. Fully specify the defaults in `default.ini` so there's no magic/disconnect
Tests pass
To come: PR against the docs to reflect the new default ratio of 2.0, not 5.0.
=> Update smoosh defaults, default.ini

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/http_test.exs, test/elixir/test/jsonp_test.exs, test/elixir/test/method_override_test.exs, test/javascript/tests/changes.js, test/javascript/tests/http.js, test/javascript/tests/jsonp.js, test/javascript/tests/method_override.js
This PR ports the following tests into the elixir test suite:
- http.js
- method_override.js
- jsonp.js
I've included in this PR a fix on the changes.js ported message that was not placed in the correct function. 
Also, I noticed that there was a JSONP related test that was commented on changes.js an now it is moved to jsonp_test.exs
```
make elixir tests=test/elixir/test/http_test.exs
make elixir tests=test/elixir/test/method_override_test.exs
make elixir tests=test/elixir/test/jsonp_test.exs
```
N/A
=> Port http, method_override and jsonp tests into elixir test suite

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/http_test.exs, test/elixir/test/jsonp_test.exs, test/elixir/test/method_override_test.exs, test/javascript/tests/changes.js, test/javascript/tests/http.js, test/javascript/tests/jsonp.js, test/javascript/tests/method_override.js
Port http, method_override and jsonp tests into elixir test suite 
Merging #2646  into 3.0.x
=> Port http, method_override and jsonp tests into elixir test suite - 3.0.x

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/http_test.exs, test/elixir/test/jsonp_test.exs, test/elixir/test/method_override_test.exs, test/javascript/tests/changes.js, test/javascript/tests/http.js, test/javascript/tests/jsonp.js, test/javascript/tests/method_override.js
Port http, method_override and jsonp tests into elixir test suite
Merging #2646 into 3.x
=> Port http, method_override and jsonp tests into elixir test suite - 3.x

src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_server.erl, src/fabric/test/fabric2_db_crud_tests.erl, src/fabric/test/fabric2_db_misc_tests.erl
Previously it was possible for a database to be re-created while a `Db` handle was open and the `Db` handle would continue operating on the new db without any error.
To avoid that situation ensure instance UUID is explicitly checked during open and reopen calls. This includes checking it after the metadata is loaded in `fabric2_fdb:open/2` and when fetching the handle from the cache.
Also, create a `{uuid, UUID}` option to allow specifying a particular instance UUID when opening a database. If that instance doesn't exist raise a `database_does_not_exist` error.
=> Fix database re-creation

test/javascript/tests/design_docs_query.js, test/javascript/tests/design_options.js, test/javascript/tests/design_paths.js, test/javascript/tests/erlang_views.js, test/javascript/tests/form_submit.js
This PR adds 'couchTests.elixir = true;'  to js tests that were already ported. 
The ported tests that were incorrectly tagged are:
- design_docs_query.js
- design_options.js
- design_paths.js
- erlang_views.js
- form_submit.js
```
make couch
make javascript
```
the result should be ...
```
...
test/javascript/tests/design_docs.js                           ported to elixir
test/javascript/tests/design_options.js                        ported to elixir
test/javascript/tests/design_paths.js                          ported to elixir
test/javascript/tests/erlang_views.js                          ported to elixir
...
test/javascript/tests/form_submit.js                           ported to elixir
...
```
N/A
=> Fix ported to elixir tag

src/fabric/src/fabric2_fdb.erl
The e520294c7ee3f55c3e8cc7d528ff37a5a93c800f commit inadvertently changed the `fabric2_fdb:refresh/1` head matching to accept db instances with no names. `couch_jobs` uses those but they are not cached in `fabric2_server`. So here we return to the previous matching rule where contexts without names don't get refreshed from the cache.
=> Fix couch_jobs after recent db re-creation commit

mix.exs, rel/overlay/etc/default.ini, src/couch/src/couch_httpd_auth.erl, src/jwtf/src/jwtf_app.erl, src/jwtf/src/jwtf_keystore.erl, src/jwtf/src/jwtf_sup.erl, test/elixir/test/jwtauth_test.exs
This enhances the JWT authentication handler in the following ways;
* Multiple keys are allowed, identified by the "kid" attribute in the token.
* A default key (called "_default") is used if there is no "kid" attribute.
* Support for EC keys.
* Support for RSA keys.
Test coverage is pretty good but real world testing is a good idea too.
N/A
=> Jwt enhancements

src/chttpd/src/chttpd_db.erl, src/couch_views/src/couch_views.erl, src/couch_views/test/couch_views_info_test.erl
This is a WIP to add the `_info` endpoint for views stored in fdb. Currently, I am unsure of the backwards compatibility for some of the fields returned by traditional couchdb views.
Info can be divided into 3 categories: 
1) Status of the build - In traditional views, we looked at
**a) the update seq of the view**
b) committed seq
c) number of clients waiting to commit
d) number of clients waiting
e) if the indexer is still running
We can determine **a)** by calling `couch_views_fdb:get_update_seq/2` (note it's a binary instead of couch_mrview's `update_seq` values which are integers).  In traditional views, **b)-d)** refers the number of workers in a queue that are waiting to start indexing and then committing. I'm not sure how this transfers over to fdb as workers are part of the …
=> add info endpoint for fdb stored views

rel/files/couchdb.cmd.in
On Windows, our PATH could inadvertently bring in DLLs that conflict with those we ship ourselves, such as OpenSSL. This would lead to startup errors.
This patch forces our PATH variable to just the bare minimum: our own binary path first, followed by the bare minimum Windows path.
```
make -f Makefile.win release
rel\couchdb\bin\couchdb.cmd
```
Closes #2680
=> Ensure clean PATH for Windows couchdb.cmd

src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_fdb.erl
In CouchDB 4.0, directories and indirection access in FoundationDB are already used to better build data model. One key/value pair is used to build reference from Dbkey to DbPrefix. All other key/value pairs are based on DbPrefix instead of DbKey. This decouples the direct relationship between DBName and data in this database. The current implementation for `DBKey -> DBPrefix` is `{?ALL_DBS, DbName} -> {?DBS, DbName}`. So you can see below information in FoundationDB using fdbcli, etc.
```
{?ALL_DBS, DbName} -> {?DBS, DbName}
{?DBS, DbName, other part of key} -> <value>
```
To support soft-deletion, especially allowing one database to be deleted/re-created multiple time, we need to use different DbPrefix for the same DbKey/DBName. The proposed change is to use a unique value allocated via …
=> Set DbPrefix with value allocated by erlfdb_hca

src/couch/src/couch_httpd_auth.erl, test/elixir/test/jwtauth_test.exs
As a followon to https://github.com/apache/couchdb/pull/2648, I'd like to include support for roles in JWTs.
Chalk this up to my newness with couchdb, I thought simply being an admin user would inherit roles 😉 
Basically I need a way to allow my servers to generate short lived `_admin` tokens to perform admin commands from my main application logic.  Example: Ensuring per-user databases are provisioned.
=> Add support for roles to be obtained from JWTs.

src/fabric/src/fabric2_db.erl, src/fabric/test/fabric2_get_design_docs_tests.erl
This is a more efficient method to get all of the design documents than
relying on fabric2_db:fold_docs which doesn't load doc bodies in
parallel.
WIP: Still need to write tests.
=> Implement fabric2_db:get_design_docs/1

src/couch/src/couch_httpd_auth.erl, test/elixir/test/jwtauth_test.exs
Following some discussion about naming for the claim, it's been determined that it would be better to make it clear that this value is CouchDB specific.
Constraining the token name this way also reduces the likelihood of an accidental collision with other schemas participating in the same token.
=> Make the JWT roles claim more CouchDB specific

test/elixir/README.md, test/elixir/test/purge_test.exs, test/javascript/tests/purge.js
This PR ports the purge.js test into the elixir test suite
```
make elixir tests=test/elixir/test/purge_test.exs
```
N/A
=> Port purge.js into elixir test suite

test/elixir/README.md, test/elixir/test/purge_test.exs, test/javascript/tests/purge.js
Port purge.js into elixir test suite
Merging #2704 into 3.0.x
=> Port purge.js into elixir test suite - 3.0.x

test/elixir/README.md, test/elixir/test/purge_test.exs, test/javascript/tests/purge.js
Port purge.js into elixir test suite
Merging #2704 into 3.x
=> Port purge.js into elixir test suite - 3.x

src/couch_views/src/couch_views_indexer.erl, src/couch_views/src/couch_views_jobs.erl, src/couch_views/test/couch_views_indexer_test.erl, src/fabric/src/fabric2_fdb.erl
Add the db instance id to indexing job data. During indexing ensure the
database is opened with the `{uuid, DbUUID}` option. After that any stale db
reads in `update/3` will throw the `database_does_not_exist` error.
In addition, when the indexing job is re-submitted in `build_view_async/2`,
check if it contains a reference to an old db instance id and replace the job.
That has to happen since couch_jobs doesn't overwrite job data for running
jobs.
=> Handle db re-creation in view indexing

src/couch/src/couch_keywrap.erl
pure Erlang implementation of the AES KW (and KW^-1) Algorithm specified in NIST Special Publication 800-38F for AES 256 bit keys only.
Eunit tests are included.
This is the first part of CouchDB 4.0's native encrypted-at-rest feature.
=> Implement AES KW algorithm

src/chttpd/src/chttpd.erl
Currently we return a 500 but a 400 return code makes more sense
```
$ http  $DB1/db1/_changes?since=0-1345
HTTP/1.1 400 Bad Request
{
"error": "invalid_since_seq",
"reason": "0-1345",
"ref": 442671026
}
```
=> Return a 400 error code for an invalid update sequence

src/couch/include/couch_eunit.hrl, src/fabric/src/fabric_rpc.erl, src/fabric/test/eunit/fabric_rpc_tests.erl, src/mem3/src/mem3_reshard_dbdoc.erl, src/mem3/src/mem3_rpc.erl, src/mem3/src/mem3_shards.erl, src/mem3/src/mem3_util.erl
This is a continuation of the work in https://github.com/apache/couchdb/pull/2672 to fix issues around secondary shard creation when nodes re-enter a cluster after a database was created while the node was down (or potentially in maintenance mode).
This PR introduces logic to handle the following four scenarios while opening a db in context of `fabric_rpc` and `mem3_rpc`:
1) the db already exists
- just return the db as normal
2) the db does not exist locally, but the dbs db doc with db create options is present
- load the db create options and create the local shard
3) the db does not exist locally but it's not a sharded database
- just create the local db as expected
4) the db does not exist locally, it's a sharded database, and the dbs db doc is not present
- throw an error and prevent …
=> Fix create db options on secondary shard creation

rel/overlay/etc/default.ini, src/jwtf/src/jwtf_keystore.erl, src/jwtf/test/jwtf_keystore_tests.erl, test/elixir/test/jwtauth_test.exs
We now insist that the server config specifies the key type of the key and use this
when looking up the key for a given token. This prevents the RS256<>HS256 known
attack where an attacker discovers a public key trusted by the server and forges an
HS256 using its encoded form.
Covered by new unit tests.
N/A
=> Only trust the servers declaration of JWT key type

rel/overlay/etc/default.ini, src/couch/src/couch_httpd_auth.erl, src/jwtf/src/jwtf.erl, src/jwtf/test/jwtf_tests.erl, test/elixir/test/jwtauth_test.exs
This PR;
* fixes the broken required_claims property (due to my misunderstanding of `proplists:get_keys`).
* Removes the enhancement to the `alg` check as it is superceded by the binding of algorithm type and key value in jwtf_keystore.
* Changes the default required_claims to include nbf and exp. Administrators can remove either or both restriction if they choose.
All changes covered by unit and/or integration tests in this PR.
N/A
=> Enhance JWT controls (again)

src/couch/src/couch_server.erl
This copy slowed down the `erlang:spawn_link/3` call considerably.
Measurements in the wild showed the cost of that `spawn_link/3` going
from roughly 8 uS to 800 uS.
=> Do not copy the #server.lru field to async openers

test/elixir/test/cookie_auth_test.exs
Some times jenkins is failling during cookie_auth_test.exs initialization. 
```
[2020-03-22T16:10:58.479Z] CookieAuthTest
[2020-03-22T16:11:04.587Z]   * test cookie auth
* test cookie auth (5022.9ms)
[2020-03-22T16:11:04.587Z] 
[2020-03-22T16:11:04.587Z]   1) test cookie auth (CookieAuthTest)
[2020-03-22T16:11:04.588Z]      test/elixir/test/cookie_auth_test.exs:206
[2020-03-22T16:11:04.588Z]      Assertion with == failed
[2020-03-22T16:11:04.588Z]      code:  assert resp.status_code() == expect_response
[2020-03-22T16:11:04.588Z]      left:  404
[2020-03-22T16:11:04.588Z]      right: 200
[2020-03-22T16:11:04.588Z]      stacktrace:
[2020-03-22T16:11:04.588Z]        test/elixir/test/cookie_auth_test.exs:107: CookieAuthTest.open_as/3
[2020-03-22T16:11:04.588Z] …
```
=> Improve cookie_auth_test.exs initialization

.credo.exs, .gitignore, Makefile, mix.exs, mix.lock, rebar.config.script, rel/files/eunit.ini, rel/overlay/etc/default.ini, src/couch_rate/README.md, src/couch_rate/src/couch_rate.app.src, src/couch_rate/src/couch_rate.erl, src/couch_rate/src/couch_rate.hrl, src/couch_rate/src/couch_rate_app.erl, src/couch_rate/src/couch_rate_config.erl, src/couch_rate/src/couch_rate_ets.erl, src/couch_rate/src/couch_rate_limiter.erl, src/couch_rate/src/couch_rate_pd.erl, src/couch_rate/src/couch_rate_sup.erl, src/couch_rate/test/exunit/couch_rate_config_test.exs, src/couch_rate/test/exunit/couch_rate_limiter_test.exs, src/couch_rate/test/exunit/test_helper.exs, src/couch_views/README.md, src/couch_views/src/couch_views_indexer.erl, src/couch_views/test/couch_views_indexer_test.erl, src/couch_views/test/couch_views_trace_index_test.erl
Current implementation uses global configuration option to determine the batch size for a background index build. This approach is sub-optimal because it is not taking the design doc write amplification factors into account. The amount of writes and therefore transaction time depends on multiple factors, such as:
* complexity of JavaScript function
* size of the document
* number of indexes
* number of emits from JavaScript function
This makes every database unique. Which requires independent control of a batch size. The idea is to implement a feedback control algorithm (rate limiter) to control batch size and delay between batches.
```
make couch && ERL_LIBS=`pwd`/src EXUNIT_DEBUG=true mix test --trace src/couch_rate/test/exunit/
make eunit …
```
=> Use `couch_rate` application for `couch_view`

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/view_offsets_test.exs, test/javascript/tests/view_offsets.js
Just ported `view_offsets.js` to Elixir test suite.
Run `make elixir tests=test/elixir/test/view_offsets_test.exs`
=> Port view_offset.js to elixir test suite

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/view_offsets_test.exs, test/javascript/tests/view_offsets.js
Just porting view_offset_test.exs test suite to `3.0.x` branch.
=> Merge in 3.0.x: Port view_offset.js to elixir test suite

src/chttpd/src/chttpd_httpd_handlers.erl, src/chttpd/src/chttpd_misc.erl, src/chttpd/test/eunit/chttpd_deleted_dbs_test.erl, src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_util.erl, src/fabric/test/fabric2_db_crud_tests.erl
Instead of automatically and immediately removing data and index in database after a delete operation, soft-deletion allows to restore the deleted data back to original state due to a “fat finger”or undesired delete operation, up to defined periods, such as 48 hours.
In CouchDB 3.0, soft-deletion of database is implemented in [1]. The .couch file is renamed with the .<timestamp>.deleted.couch file after soft-deletion is enabled, and such file can be changed back to .couch for the purpose of restore. If restore is not needed and some specified period passed, the .<timestamp>.deleted.couch file can be deleted to achieve deletion of database permanently.
In CouchDB 4.0, with the introduction of FoundationDB, the data model and storage is changed. In order to support soft-deletion, we propose …
=> soft-deletion for database

src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_doc_att_tests.erl
In CouchDB < 4.x we compressed document bodies by default, so enable it
for 4.x as well.
Use the basic term_to_binary compression mechanism for:
- Document bodies
- Local document bodies
- Attachments, but only if they have not already been compressed.
=> Compress doc bodies and attachments

src/couch_jobs/src/couch_jobs_fdb.erl, src/couch_jobs/test/couch_jobs_tests.erl
Fix the case when a job is removed while there are subscribers waiting for it.
Most of the logic was already there except:
* Handle the case when when data decoded from subscription results could be
`not_found`, in that case we just pass that atom back as is.
* Need to notify the watch when jobs are removed or couch_jobs_notifiers would
wake up and send notification messages.
=> Fix job removal notifications

src/mango/src/mango_plugin.erl
Previously we used the value returned from couch_epi apply as is.
However it returns a list of arguments passed in the same order.
```
./configure --dev && make && make mango-test
```
* Fixes https://github.com/apache/couchdb/pull/2767
=> Fix incorrect usage of couch_epi in mango plugin

src/fabric/test/fabric2_index_tests.erl
Previously in the the test we first set up the callback, then disabled the
indexing. By that time, there was a chance that building could have started
especially in a slower execution environment.
=> Fix flaky fabric2_index test

test/elixir/README.md, test/elixir/test/recreate_doc_test.exs, test/javascript/tests/recreate_doc.js
This PR ports the recreate_doc.js test into the elixir test suite
```
make elixir tests=test/elixir/test/recreate_doc_test.exs
```
=> Port recreate doc test into elixir 

test/elixir/README.md, test/elixir/test/recreate_doc_test.exs, test/elixir/test/reduce_builtin_test.exs, test/elixir/test/reduce_false_test.exs, test/javascript/tests/recreate_doc.js
Port recreate docs test into elixir 
Merge #2765 into 3.x
Note: I added to this PR 2 test that were ported but not merged into 3.x
=> Port recreate docs test into elixir - 3.x

test/elixir/README.md, test/elixir/test/recreate_doc_test.exs, test/elixir/test/reduce_builtin_test.exs, test/elixir/test/reduce_false_test.exs, test/javascript/tests/recreate_doc.js
Port recreate docs test into elixir 
Merge #2765 into 3.0.x
Note: I added to this PR 2 test that were ported but not merged into 3.0.x
=> Port recreate docs test into elixir - 3.0.x

src/couch/src/couch_bt_engine_compactor.erl, src/couch/src/couch_btree.erl, src/couch/src/couch_emsort.erl, src/couch/src/couch_file.erl, src/couch/test/eunit/couch_bt_engine_compactor_ev.erl, src/couch/test/eunit/couch_bt_engine_compactor_ev_tests.erl
Reviving an old compactor optimization from PR #806.  I'm also going to add in some work from #1006 to give us better visibility on compaction id_seq copy phases.
`$ make check`
=> 3.x optimize compactor

.gitignore, Makefile, Makefile.win, bin/warnings_in_scope, configure, configure.ps1, emilio.config
Add `emilio` erlang linter to ensure unified style.
- do a fresh clone and run `./configure` (make sure `bin/emilio` script is created)
- run `./configure` again and make sure it doesn't try to install `emilio` again
- Update any erlang files in any dependency (except files mentioned in `ignore` section of `emilio.config`)
- Run `make emilio` and make sure that:
- produced warnings are only for (± 3) updated lines
- make fails with non 0 exit code  
- Run `bin/emilio -c emilio.config src | bin/warnings_in_scope -s 0` to see warnings from `emilio`
- make sure produced warnings are only for updated lines
- Run `bin/emilio -c emilio.config src` and make sure dependencies mentioned in `ignore` section of `emilio.config` are ignored
- test it on windows if you have access to it (I don't have …
=> Integrate emilio

.gitignore, Makefile, Makefile.win, bin/warnings_in_scope, configure, configure.ps1, emilio.config
Add emilio erlang linter to ensure unified style.
Cherry pick https://github.com/apache/couchdb/pull/1944/commits/522627eb88d8a280b62a125cf008991438848865 commit from https://github.com/apache/couchdb/pull/1944 master
- do a fresh clone and run `./configure` (make sure `bin/emilio` script is created)
- run `./configure` again and make sure it doesn't try to install `emilio` again
- Update any erlang files in any dependency (except files mentioned in `ignore` section of `emilio.config`)
- Run `make emilio` and make sure that:
- produced warnings are only for (± 3) updated lines
- make fails with non 0 exit code  
- Run `bin/emilio -c emilio.config src | bin/warnings_in_scope -s 0` to see warnings from `emilio`
- make sure produced warnings are only for updated lines
- Run `bin/emilio -c …
=> Integrate emilio - erang linter

src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_stats.erl, src/chttpd/test/eunit/chttpd_stats_tests.erl
Stats are reported at the end of a request. With changes feeds,
sometimes this can take a long or never end at all. This allows
stats to be reported when changes are flushed and sent to user.
=> report changes stats intermittently

src/couch_expiring_cache/src/couch_expiring_cache_fdb.erl, src/couch_expiring_cache/src/couch_expiring_cache_server.erl, src/couch_expiring_cache/test/couch_expiring_cache_tests.erl, src/fabric/include/fabric2.hrl
When an existing key is inserted with different timestamps, the primary
key is the same but the primary value is different from the existing one.
Currently, this results in a new expiry key being inserted, but the old
one is not deleted, and lingers until it is removed by the inexorable
advance of time via the `remove_expired` server messages.
This checks whether there's already primary key for the inserted key,
and if so, cleans up the existing expiry key before proceeding with the
insert.
```
make eunit apps=couch_expiring_cache
```
=> Clean up existing expiry key on update

src/fabric/src/fabric2_db.erl
Small optimisation: Fetch doc in same transaction as _all_doc row
make check should pass
=> Fetch doc in same transaction as _all_doc row

src/mango/src/mango_selector.erl, src/mango/test/21-empty-selector-tests.py
Previously, in https://github.com/apache/couchdb/pull/1783, the logic
was wrong in relation to how certain operators interacted with empty
arrays. We modify this logic to make it such that:
{"foo":"bar", "bar":{"$in":[]}}
and
{"foo":"bar", "bar":{"$all":[]}}
should return 0 results.
=> fix operator issue with empty arrays

src/setup/src/setup.erl
the `log` module does not exist, good facepalm error here ;D
=> fix: use correct logging module name, fixes #2797

src/setup/src/setup.erl
Co-authored-by: Joan Touzet <wohali@users.noreply.github.com>
=> fix: use correct logging module name, fixes #2797 (#2798)

src/couch_views/src/couch_views_epi.erl, src/couch_views/src/couch_views_plugin.erl, src/couch_views/src/couch_views_updater.erl
Adds an epi plugin to couch_views_updater
all tests should still pass
=> Add after_interactive_write plugin to couch_views_updater

src/chttpd/src/chttpd_db.erl, src/couch_views/src/couch_views_indexer.erl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, test/elixir/test/all_docs_test.exs
Adds a fold_docs function that will fetch the docs for a list of
Doc Id's in parallel. This is used for _all_docs?keys=["id1", "id2"].
All existing tests should pass
=> Add fold_docs for DocId list

src/mango/src/mango_json_bookmark.erl
The safe property prevents creation of new atoms among other things, prudent to have it here.
craft a weird bookmark I guess
N/A
=> safer binary_to_term in mango_json_bookmark

src/chttpd/test/eunit/chttpd_session_tests.erl, src/chttpd/test/eunit/chttpd_test.hrl, src/couch/src/couch_httpd_auth.erl
Currently, result of GET `/_session` reports the `authentication_db` of
the obsolete admin port 5986. This updates it to report the actual db
used for authentication, provided it is configured. Otherwise, it omits
`authentication_db` entirely from the session info.
```
make check
```
=> Report the chttpd_auth authentication db in session info

configure, rebar.config.script, rel/reltool.config, src/aegis/rebar.config.script, src/aegis/src/aegis.app.src, src/aegis/src/aegis.erl, src/aegis/src/aegis.hrl, src/aegis/src/aegis_app.erl, src/aegis/src/aegis_key_manager.erl, src/aegis/src/aegis_keywrap.erl, src/aegis/src/aegis_noop_key_manager.erl, src/aegis/src/aegis_server.erl, src/aegis/src/aegis_sup.erl, src/aegis/test/aegis_basic_test.erl, src/aegis/test/aegis_server_test.erl, src/chttpd/src/chttpd.erl, src/couch_views/src/couch_views_fdb.erl, src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_fdb.erl
A new application, aegis, is introduced to provide strong at-rest
protection of CouchDB data (where possible).
Currently we encrypt the following values (if enabled):
1. Document content
2. Attachment content
3. Index values
Things not encrypted:
1. _all_docs
2. _changes
3. doc id
4. doc rev
5. Index keys
6. All other metadata
Co-Authored-By: Eric Avdey <eiri@apache.org>
Co-Authored-By: Robert Samuel Newson <rnewson@apache.org>
=> Add native encryption support

Makefile, Makefile.win
Python formatting problems have been slipping by the CI system. This PR aims to fix that.
The branch, as-is, has a formatting issue in `src/mango/test/21-empty-selector-tests.py` and should fail.
=> Ensure python black runs on all .py files

src/couch_mrview/src/couch_mrview_index.erl
We've seen a crash if DbPartitioned is false and ViewPartitioned is
true, which is obviously nonsense. The effect of the `nocase` is the
termination of the couch_index_server gen_server, which is a serious
amplification of a small (user-initiated) oddity.
=> View is partitioned if db and view are partitioned

src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_misc.erl
The etag values were hardcoded. Remove them for now until we decide on a way to set the etag's correctly.
All existing tests should pass.
=> Remove etag from changes and _list_dbs

src/fabric/test/fabric2_tx_options_tests.erl
Temporary `disable fabric2_tx_options_tests` till they changed to detect if tx setting option available on fdb side.
=> Temporary disable fabric2_tx_options_tests

src/couch/rebar.config.script
Mozilla did this years ago:
https://hg.mozilla.org/mozilla-central/rev/41d9d32ab5a7
=> Suppress offsetof gcc warnings for SM60

src/fabric/src/fabric2_server.erl, src/fabric/test/fabric2_tx_options_tests.erl
And an extra level of error checking to erlfdb:set_option since it could fail
if we forget to update erlfdb dependency or fdb server version is too old. That
operation can fail with an error:badarg which is exactly how list_to_integer
fails and result in a confusing log message.
=> Re-enable the tx options tests

src/couch_expiring_cache/src/couch_expiring_cache_server.erl, src/couch_expiring_cache/test/couch_expiring_cache_tests.erl
In its current incarnation, the so-called "simple lifecycle" test is
prone to numerous failures in the CI system [1], doubtless because it's
riddled with race conditions. The original author makes many assumptions
about how quickly an (actual, unmocked) FDB instance will respond to a
request.
The primary goal is to stop failing CI builds, while other
considerations include: keeping the run time of the test as low as
possible, keeping the code coverage high, and documenting the known
races.
Specifically:
- Increase the `stale` and `expired` times by a factor of 5 to decrease
sensitivity to poor FDB performance.
- Change default timer from `erlang:system_time/1` to `os:timestamp` on
the assumption that the latter is less prone to warping [2].
- Decrease the period of the cache server reaper …
=> Improve robustness of couch expiring cache test

src/fabric/test/fabric2_db_crud_tests.erl
On CI creating a 100 dbs in a row was too much to do in 5 seconds so bump it to
15.
=> Fix list_dbs_info_tx_too_old flaky test

.gitignore, build-aux/Jenkinsfile.full
This PR adds Ubuntu Focal Fossa to our CI build matrix.
Coupled with a [small change to the `couchdb-pkg` repo that's already landed](https://github.com/apache/couchdb-pkg/commit/734ed6467a1f1c0555fd2261abbc24f856f4a8ca), it also simplifies the arguments required for package build down to `make`. Nice!
https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/jenkins-fossa-sm68/5/pipeline/275/
=> Add Ubuntu Focal (20.04) + SM68 to Jenkins

Makefile, Makefile.win, rel/reltool.config, version.mk
* Backport of fix for #2852
* Version number bump
* Fix for Windows `python-black*` Makefile targets
=> 3.x backports verbump

Makefile.win
I really need to get a Windows machine into the CI matrix.
Perhaps we can have it run builds on any branch named `windows-*`. We certainly won't want it to run on every branch.
=> Fix python-black target for Windows

Makefile, Makefile.win, rel/reltool.config, version.mk
* Backport of fix for #2852
* Version number bump
* Fix for Windows `python-black*` Makefile targets
=> 3.0.x backports verbump

test/elixir/README.md, test/elixir/test/replicator_db_bad_rep_id_test.exs, test/elixir/test/replicator_db_by_doc_id_test.exs, test/javascript/tests/replicator_db_bad_rep_id.js, test/javascript/tests/replicator_db_by_doc_id.js
This PR ports replicator_db_bad_rep_id and  replicator_db_by_doc_id  tests to elixir test suite.
```
make elixir tests=test/elixir/test/replicator_db_bad_rep_id_test.exs
make elixir tests=test/elixir/test/replicator_db_by_doc_id_test.exs
```
N/A
=> Port replicator_db_bad_rep_id and  replicator_db_by_doc_id tests to elixir test suite

src/mango/test/16-index-selectors-test.py
Design docs using type <<"text">> (either via replication or traditional POST)should be ignored.
=> add test to make sure type <<"text">> design docs are ignored

rel/overlay/etc/default.ini, src/aegis/src/aegis_server.erl, src/aegis/test/aegis_server_test.erl, src/fabric/src/fabric2_util.erl
This converts aegis's key cache into LRU with hard expiration time.
The cache evicts the least recently used entries when number of entries in the cache exceeds "cache_limit" parameter with default set to 100000.
Additionally keys removed once their lifetime exceeds "cache_max_age_sec" parameter with default set to 30 minutes.
` make eunit apps=aegis suites=aegis_server_test tests=lru_cache_with_expiration_test_`
=> Convert aegis key cach to LRU with hard expiration time

src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_db_fold_doc_docids_tests.erl, test/elixir/test/all_docs_test.exs
=> fetch local docs in fold_docs function

src/couch_views/src/couch_views.erl, src/couch_views/src/couch_views_jobs.erl, src/couch_views/test/couch_views_info_test.erl
Previously we always returned `false` because the result from `couch_jobs:get_job_state` was expected to be just `Status`, but it is `{ok, Status}`. That part is now explicit so we account for every possible job state and would fail on a clause match if we get something else there.
Moved `job_state/2` function to `couch_view_jobs` to avoid duplicating the logic on how to calculate job_id and keep it all in one module.
Tests were updated to explicitly check for each state job state.
=> Fix couch_views updater_running info result

src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_db_expiration.erl, src/fabric/src/fabric2_sup.erl, src/fabric/test/fabric2_db_crud_tests.erl
Allow to permanently delete those soft-deleted databases under background. In general, the soft-deleted database can be kept from several hours to several days. Later, they need to be deleted to reclaim disk space. So one criteria can be specified to decide how to select which soft-deleted databases to be deleted.
make check apps=fabric tests=crud_test_,scheduled_db_remove_error_test_
```
INFO:  Cover compiling /Users/jiangph/fdb/fdb-dbcore-0413/fdb-dbcore/src/couchdb/src/fabric
Test scheduled database remove operations
fabric2_db_crud_tests:77: scheduled_db_remove_error_test_ (scheduled_remove_deleted_dbs_with_error)...[0.026 s] ok
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[done in 0.082 s]
Test database CRUD …
```
=> Background database deletion

src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_view.erl, src/chttpd/test/exunit/pagination_test.exs, src/couch_mrview/include/couch_mrview.hrl, src/couch_mrview/src/couch_mrview_http.erl, src/couch_views/src/couch_views_http.erl, src/couch_views/src/couch_views_util.erl
This PR implements a pagination API proposed in [RFC](https://github.com/apache/couchdb-documentation/pull/530).
Running `make check` should be sufficient.
You can also test manually using:
```
make eunit apps=couch_mrview tests=check_completion_test
curl -u adm:pass -X PUT "http://127.0.0.1:15984/test"
curl -u adm:pass -X PUT "http://127.0.0.1:15984/test/foo" -d '{"value": "foo"}' | jq '.'
curl -u adm:pass -X PUT "http://127.0.0.1:15984/test/bar" -d '{"value": "bar"}' | jq '.'
curl -u adm:pass -X PUT "http://127.0.0.1:15984/test/baz" -d '{"value": "baz"}' | jq '.'
curl -u adm:pass "http://127.0.0.1:15984/test/_all_docs" | jq '.'
curl -u adm:pass "http://127.0.0.1:15984/test/_all_docs?limit=1" | jq '.'
curl -u adm:pass …
```
=> Pagination API

rel/overlay/etc/default.ini, src/couch/src/couch_httpd.erl, src/couch/src/couch_httpd_auth.erl, test/elixir/test/jwtauth_test.exs
e.g;
[jwt]
required_claims = {iss, "hello"}
fixes https://github.com/apache/couchdb/issues/2886
=> allow configurability of JWT claims that require a value

rebar.config.script, rel/overlay/etc/default.ini, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_update_docs_tests.erl
Bulk docs transaction batching
* Interactive (regular) requests are split into smaller transactions, so
larger updates won't fail with either timeout so or transaction too large
FDB errors.
* Non-interactive (replicated) requests can now batch their updates in a few
transaction and gain extra performance.
Batch size is configurable:
```
[fabric]
update_docs_batch_size = 5000000
```
=> Add batching for _bulk_docs

src/fabric/src/fabric2_db_expiration.erl
Improve log of permanently deleting databases. The log will be changed to `[notice] 2020-05-21T02:52:44.925392Z nonode@nohost <0.1820.0> -------- Permanently deleting eunit-test-db-1003fd212922d7dec0d25876feacf194 database with timestamp 2020-05-21T02:52:43Z`
make check apps=fabric tests=crud_test_,scheduled_db_remove_error_test_
```
Test scheduled database remove operations
fabric2_db_crud_tests:77: scheduled_db_remove_error_test_ (scheduled_remove_deleted_dbs_with_error)...[0.049 s] ok
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[done in 0.109 s]
Test database CRUD operations
fabric2_db_crud_tests:37: crud_test_ (create_db)...[0.027 s] ok
fabric2_db_crud_tests:38: crud_test_ (open_db)...[0.015 s] ok
fabric2_db_crud_tests:39: crud_test_ (delete_db)...[0.021 s] ok …
```
=> Improve log of permanently deleting databases

src/chttpd/test/exunit/pagination_test.exs, src/couch_views/src/couch_views_http.erl
This PR fixes a one off problem when limit is given in query parameter and it's value is less than page_size.
```
make eunit apps=couch_views tests=check_completion_test
```
* fixes https://github.com/apache/couchdb/pull/2870
=> Fix handling of limit query parameter

src/couch_jobs/src/couch_jobs_activity_monitor.erl, src/couch_views/src/couch_views_jobs.erl
Increase couch_views job timeout by 20 seconds. This will set a larger jitter
when multiple nodes concurrently check and re-enqueue jobs. It would reduce the
chance of them bumping into each other and conflicting.
If they do conflict in activity monitor, catch the error and emit an error log.
We gain some more robustness under load for a longer timeout for jobs with
workers that have suddenly died getting re-enqueued.
=> Improve load handling in couch_jobs and couch_views

src/fabric/test/fabric2_update_docs_tests.erl
In a constrained CI environment transactions could retry multiple times so we
cannot rely on precisely counting erlfdb:transactional/2 calls.
=> Remove erlfdb mock from update_docs/2,3 test

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/auth_cache_test.exs, test/elixir/test/compact_test.exs, test/elixir/test/partition_size_limit_test.exs, test/elixir/test/purge_test.exs, test/elixir/test/replication_test.exs, test/elixir/test/rev_stemming_test.exs, test/elixir/test/users_db_test.exs, test/javascript/tests/rev_stemming.js
This PR ports rev_stemming.js test into the elixir test suite
```
make elixir tests=test/elixir/test/rev_stemming_test.exs
```
=> Port rev_stemming into elixir test suite

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/auth_cache_test.exs, test/elixir/test/compact_test.exs, test/elixir/test/partition_size_limit_test.exs, test/elixir/test/purge_test.exs, test/elixir/test/replication_test.exs, test/elixir/test/rev_stemming_test.exs, test/elixir/test/users_db_test.exs, test/javascript/tests/rev_stemming.js
Backport into 3.x PR #2879 - Port rev_stemming into elixir test suite
=> 3.x backport - Port rev_stemming into elixir test suite

rel/overlay/etc/default.ini, src/fabric/src/fabric2_db.erl
Observed a number of timeouts with the previous default
=> Lower the default batch size for update_docs to 2.5MB

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_db_doc_size_tests.erl
Let users specify the maximum document count for the _bulk_docs requests. If the document count exceeds the maximum it would return a 413 HTTP error. This would also signal the replicator to try to bisect the _bulk_docs array into smaller batches.
=> Introduce _bulk_docs max_doc_count limit

src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_server.erl, src/fabric/test/fabric2_db_misc_tests.erl
Ensure fabric2_server operations do not evict newer handles by comparing the metadata version to the what's already in the table. Also, remove on_commit handler and instead update the fresh db handle right away to let concurrent request see the updated handle as soon as possible.
=> Prevent eviction of newer handles from fabric2_server cache

src/couch_jobs/src/couch_jobs.erl
Under load accept loop can blow up with timeout error from
`erlfdb:wait(...)`(https://github.com/apache/couchdb-erlfdb/blob/master/src/erlfdb.erl#L255)
so guard against it just like we do for fdb transaction timeout (1031) errors.
=> Handle error:{timeout, _} exception in couch_jobs:accept

src/couch_views/src/couch_views_indexer.erl, src/couch_views/src/couch_views_jobs.erl, src/couch_views/test/couch_views_cleanup_test.erl
Use couch_jobs's `no_schedule` accept option to speed up job dequeuing.
This optimization allows dequeung jobs more efficiently if these conditions are
met:
1) Job IDs start with a random prefix
2) No time-based scheduling is used
Both of those can be true for views job ids can be generated such that
signature comes before the db name part, which is what this commit does.
The way the optimisation works, is random IDs are generating in pending jobs
range, then, a key selection is used to pick either a job before or after
it. That reduces each dequeue attempt to just 1 read instead of reading up to
1000 jobs.
=> Improve efficiency of couch_jobs:accept/2 for views

src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_db_crud_tests.erl, src/fabric/test/fabric2_db_misc_tests.erl
As per ML [discussion](https://lists.apache.org/thread.html/rb328513fb932e231cf8793f92dd1cc2269044cb73cb43a6662c464a1%40%3Cdev.couchdb.apache.org%3E) add a `uuid` field to db info results in order to be able to uniquely identify a particular instance of a database. When a database is deleted and re-created with the same name, it will return a new `uuid` value.
```
$ http get $DB/db1
HTTP/1.1 200 OK
{
"cluster": {
"n": 0,
"q": 0,
"r": 0,
"w": 0
},
"compact_running": false,
"data_size": 0,
"db_name": "db1",
"disk_format_version": 0,
"disk_size": 0,
"doc_count": 0,
"doc_del_count": 0,
"instance_start_time": "0",
"purge_seq": 0,
"sizes": {
"external": 2,
"views": 0
},
"update_seq": "000000000000000000000000",
"uuid": "b00a3d1632df7c15d12ca08299922c55"
}
$ http delete $DB/db1
$ http put …
```
=> Include database uuid in db info result

rel/overlay/etc/default.ini, src/couch/src/couch_httpd_auth.erl
This PR makes the `_couchdb.roles` custom claim configurable from the `local.ini` file, so it can be used with any OpenID Connect (OIDC) compliant service, such as Auth0 (https://auth0.com/docs/api-auth/tutorials/adoption/scope-custom-claims)
1. In your `local.ini` file, under the `[jwt_auth]` section, add this line:
```ini
roles_claim_name = https://example.com/roles
```
2. Use this token to send some requests to your CouchDB instance: https://jwt.io/#debugger-io?token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyLCJodHRwczovL2V4YW1wbGUuY29tL3JvbGVzIjpbIl9hZG1pbiIsInNvbWUtb3RoZXItcm9sZSJdfQ.gQCW8lXpdOwUwtTX3bEjir8rX_W54677KYe9OVguTC4
#2913
=> feat(auth): Allow a custom JWT claim for roles

src/couch/src/couch_server.erl
This will only report "fips" in the welcome message if FIPS mode
was enabled at boot (i.e, in vm.args).
build/use a fips enabled openssl, set vm.args to enable it, and confirm presence of feature flag.
N/A
=> Report if FIPS mode is enabled

rel/overlay/etc/default.ini, src/couch_views/src/couch_views_indexer.erl, src/couch_views/src/couch_views_server.erl, src/couch_views/test/couch_views_server_test.erl, src/couch_views/test/couch_views_trace_index_test.erl
Optimize couch_views by using a separate set of acceptors and workers. Previously, all `max_workers` where spawned on startup, and were to waiting to accept jobs in parallel. In a setup with a large number of pods, and 100 workers per pod, that could lead to a lot of conflicts  being generated when all those workers race to accept the same job at the same time.
The improvement is to spawn only a limited number of acceptors (5, by default), then, spawn more after some of them become workers. Also, when some workers finish or die with an error, check if more acceptors could be spawned.
As an example, here is what might happen with `max_acceptors = 5` and `max_workers = 100` (`A` and `W` are the current counts of acceptors and workers, respectively):
1. Starting out:
`A = 5, W = 0`
2. After …
=> Split couch_views acceptors and workers

src/couch_replicator/src/couch_replicator_scheduler.erl
Previously, when pending jobs were picked in the `ets:foldl` traversal, both
running and non-running jobs were considered and a large number of running jobs
could displace pending jobs in the accumulator. In the worst case, no crashed
jobs would be restarted during rescheduling.
=> In replicator, when rescheduling, pick only pending jobs which are not running

rebar.config.script
https://github.com/apache/couchdb-erlfdb/releases/tag/v1.2.2
=> Bump erlfdb to v1.2.2

src/mango/src/mango_opts.erl
This caused a breaking change in some client APIs. We add `w` and `r` back temporarily.
Regression tests should be okay.
- [] Changes are covered by tests
=> add back r and w options

src/fabric/include/fabric2.hrl
Reserve aegis namespace under `?CLUSTER_CONFIG` to prevent possible name clashes in the future.
=> Reserve aegis namespace under ?CLUSTER_CONFIG

src/dreyfus/src/dreyfus_httpd.erl, src/dreyfus/test/elixir/test/partition_search_test.exs
According to https://docs.couchdb.org/en/master/ddocs/search.html there
are parameters for searches that are not allowed for partitioned queries.
Those restrictions were not enforced, thus making the software and docs
inconsistent.
This PR adds them to validation so that the behavior matches the one
described in the docs.
Run the tests included with the PR or perform them manually.
=> Make restricted partition search parameters return bad request

src/dreyfus/src/dreyfus_httpd.erl, src/dreyfus/test/elixir/test/search_test.exs
To use multiple `drilldown` parameters users had to define
`drilldown` multiple times to be able supply them.
This caused interoperability issues as most languages require
defining query parameters and request bodies as associative
arrays, maps or dictionaries where the keys are unique.
This change enables defining `drilldown` as a list of lists so
that other languages can define multiple drilldown keys and values.
Run the tests included
=> Allow drilldown for search to always be specified as list of lists

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_db_doc_size_tests.erl
Let admin users specify the maximum document count for the `_bulk_get` requests via `max_bulk_get_count` configuration. If the document count exceeds the maximum it would return a 413 HTTP error. The implementation is based on https://github.com/apache/couchdb/pull/2910.
```
make && make eunit apps=chttpd tests=all_test_
```
N/A
=> Add max_bulk_get_count configuration option

test/javascript/tests/reduce_builtin.js, test/javascript/tests/reduce_false.js, test/javascript/tests/reduce_false_temp.js
This PR sets ported to elixir tag for `reduce_builtin.js` and `reduce_false.js` tests that have been already ported to elixir. 
The reduce_false_temp.js is skiped as it is not meaningfull after 2.0 version as temporary views are not longer supported.
`make javascript` should produce:
```
....
test/javascript/tests/reduce_builtin.js        ported to elixir
test/javascript/tests/reduce_false.js          ported to elixir
test/javascript/tests/reduce_false_temp.js     skipped
...
```
N/A
=> Save time in the build by setting ported to elixir tag in reduce related JS tests

test/javascript/tests/reduce_builtin.js, test/javascript/tests/reduce_false.js, test/javascript/tests/reduce_false_temp.js
Backport into 3.x - PR #2967
This PR sets ported to elixir tag for `reduce_builtin.js` and `reduce_false.js` tests that have been already ported to elixir.
The `reduce_false_temp.js` is skipped as it is not meaningful after 2.0 version as temporary views are no longer supported.
=> 3x backport - Save time in the build by setting ported to elixir tag in reduce related JS tests

test/elixir/README.md, test/elixir/test/reader_acl_test.exs, test/javascript/tests/reader_acl.js
This PR ports `reader_acl.js` test into the elixir test suite 
```
make elixir tests=test/elixir/test/reader_acl_test.exs
```
N/A
=> Port reader_acl test into elixir test suite

src/couch_epi/test/eunit/couch_epi_tests.erl
The `couch_epi` test suite is flaky. The result of the tests depends on the order of applications eunit runs.
The failures happen when `crypto` app is not running prior to starting couch_epi test suite. This PR changes the way we start `couch_epi` to insure its dependencies are automatically started. 
There is no good way to reproduce the issue. We just run full test suite to make sure there are no new regressions.
```
make check
```
N/A
=> Start all required deps automatically in test

test/elixir/README.md, test/elixir/test/reader_acl_test.exs, test/javascript/tests/reader_acl.js
This PR backports #2969 into 3.x
Ports `reader_acl.js` test into the elixir test suite
`make elixir tests=test/elixir/test/reader_acl_test.exs`
N/A
=> 3x backport - Port reader_acl test into elixir test suite

test/elixir/lib/couch/db_test.ex, test/elixir/test/view_update_seq_test.exs, test/javascript/tests/view_update_seq.js
This PR ports `view_update_seq.js` into elixir test suite
There are some failures related to this test:
https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FPullRequests/detail/PR-2973/1/pipeline/62
https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/master/189/pipeline/57
I expect that the elixir version will be more robust as we remove a 5 seconds wait continuously requesting "/" from couchdb test server. 
```
[2020-06-29T16:35:18.202Z] test/javascript/tests/view_offsets.js                          ported to elixir
[2020-06-29T16:35:18.202Z] test/javascript/tests/view_pagination.js                       ported to elixir
[2020-06-29T16:35:20.581Z] test/javascript/tests/view_sandboxing.js                       pass …
```
=> Port view_update_seq.js into elixir

test/elixir/lib/couch/db_test.ex, test/elixir/test/view_update_seq_test.exs, test/javascript/tests/view_update_seq.js
This PR backports #2974 into 3.x
Ports `view_update_seq.js` into elixir test suite
```
make elixir tests=test/elixir/test/view_update_seq_test.exs
```
#2974
=> Backport 3.x - Port view_update_seq.js into elixir

src/ioq/src/ioq.erl
Before the bypass existed, ioq would call `gen_server:call()`
on hehalf of it calling module with the queueing logic in between.
Commit e641a740 introduced a way to bypass any queues, but the
delegated `gen_server:call()` there was added without a timeout
parameter, leading to a default timeout of 5000ms.
A problem manifests here when operations that are sent through
ioq that take longer than that 5000ms timeout. In practice, these
operations should be very rare and this timeout should be a help
on overloaded systems. However, one sure-fire way to cause an issue
on an otherwise idle machine is raise the max_document_size and
store unreasonably large documents, think 50MB+ of raw JSON).
Not that we recommend this, but folks have run this fine on 2.x
before the ioq changes and it isn’t too …
=> fix: set gen_server:call() timeout to infinity on ioq bypass

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/view_compaction_test.exs, test/javascript/tests/view_compaction.js
This PR ports view_compaction.js test into the elixir test suite
I've modified the tests to use 1.000 docs and not 10.000 docs like the original one. With this change, the execution time is reduced in 10 seconds. 
```
make elixir tests=test/elixir/test/view_compaction_test.exs
```
N/A
=> Port view_compaction test to elixir

test/elixir/README.md, test/elixir/lib/couch/db_test.ex, test/elixir/test/view_collation_raw_test.exs, test/elixir/test/view_compaction_test.exs, test/javascript/tests/view_collation_raw.js, test/javascript/tests/view_compaction.js
This PR backports #2987 and #2977 into 3.x
```
make elixir
```
#2987 and #2977
=> Backport 3x - Port view_collation_raw and view_compaction tests into elixir 

Makefile, Makefile.win
Adding emilio check into Makefile was a mistake. Without automatic linter it is almost impossible to fix the style. Also emilio doesn’t allow disabling the checks. The idea was that by checking only warnings around (+-3 lines) modified lines we could gradually update the style as we go. However by updating these extra lines we trigger even more warnings and you end up changing style for the whole module. Things like “402 - import declaration found” is especially hard to fix.
1. Change style for one of the erlang source files
2. Run tests `make check` - the execution output should pass the point where emilio warnings are displayed
=> Do not fail when emilio detects errors

src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_misc.erl, src/chttpd/test/eunit/chttpd_handlers_tests.erl
Currently the EPI plugins have no easy way to modify body of the document in
before request. There are complicated approaches via overriding compression header.
In any case you are obligated to serialize your data structure into JSON. 
This is due to the fact that `chttp:json_body/1` expects compressed body.
We can rely on the fact that `MochiReq:recv_body/1` returns binary to allow
passing of already parsed JSON terms (objects and lists). 
If we do so we can modify request's body as easy as:
```
Req#httpd{req_body = {[{<<"hello">>, <<"couch">>}]}}
```
`make check`
=> Simplify using `req_body` for JSON requests

test/elixir/lib/couch.ex
Previously the auth was injected unconidtionally. There were two problems:
1. no way to specify `basic_auth` credentials
2. no way to disable injection
Due to #2 it was impossible to use other user than hardcoded `adm` in `Couch.login/3`.
The following should be sufficient to test for regressions
```
```
=> Fix auth injection in test helper

src/couch/src/couch_bt_engine_compactor.erl
When compactor finds an old compaction file, before the state was upgraded to a a proplist, the state will be `Root` from `emsort`, which is a `{BB, Prev}` tuple not an integer.
Fixes https://github.com/apache/couchdb/issues/2941
=> Fix compactor bind_emsort clause

build-aux/Jenkinsfile.full, build-aux/logfile-uploader.py
Because of ASF Infra changes, couchdb-vm2.apache.org is going away and will be replaced by couchdb-vm before August 1st 2020.
This PR adds redirection through a new CNAME, logs.couchdb.org, for the logfile uploader.
It also uses repo-nightly.couchdb.org instead of couchdb-vm2.a.o.
This requires @janl to get the new CNAME in before this can land.
=> New cname for couchdb-vm2, see INFRA-20435

test/elixir/README.md, test/elixir/test/view_multi_key_all_docs_test.exs, test/elixir/test/view_multi_key_design_test.exs, test/javascript/tests/view_multi_key_all_docs.js, test/javascript/tests/view_multi_key_design.js, test/javascript/tests/view_multi_key_temp.js
This PR ports the multi key view query related tests into the Elixir test suite:
- `view_multi_key_all_docs.js` has been ported into `view_multi_key_all_docs_test.exs`
- `view_multi_key_design.js` has been ported into `view_multi_key_design_test.exs`
- `view_multi_key_temp.js` has been disabled and not ported as it refers to temporary views which is not supported since 2.x. This test cases is already covered by the previous test cases.
```
make elixir tests=test/elixir/test/view_multi_key_all_docs_test.exs
make elixir tests=test/elixir/test/view_multi_key_design_test.exs
```
N/A
=> Port view multi_key js tests into elixir test suite

src/couch_views/src/couch_views_http.erl
Fix a failing test case related to handling of a previous bookmark when `descending` is true. 
```
```
This is a fixup for https://github.com/apache/couchdb/pull/2904
=> Fix 'first page should not return previous bookmark' test

test/elixir/README.md, test/elixir/test/update_documents_test.exs, test/elixir/test/view_multi_key_all_docs_test.exs, test/elixir/test/view_multi_key_design_test.exs, test/elixir/test/view_sandboxing_test.exs, test/javascript/tests/update_documents.js, test/javascript/tests/view_multi_key_all_docs.js, test/javascript/tests/view_multi_key_design.js, test/javascript/tests/view_multi_key_temp.js, test/javascript/tests/view_sandboxing.js
This PR backports #3022, #3021  and #2992 to 3.x branch
```
make elixir
```
#3022, #3021  and #2992
=> 3.x backport - Port view_sandboxing, view_multi_key and update_documents tests into elixir

src/chttpd/src/chttpd_misc.erl, src/couch_jobs/src/couch_jobs.erl, src/couch_views/src/couch_views_indexer.erl, src/couch_views/src/couch_views_util.erl, src/couch_views/test/couch_views_active_tasks_test.erl, src/fabric/src/fabric2_active_tasks.erl
Active Tasks requires TotalChanges and ChangesDone to show the progress
of long running tasks. This requires `count_changes_since/2` to be
implemented. Unfortunately, that is not easily done  with
foundationdb. This commit replaces TotalChanges with the
versionstamp + the number of docs as a progress indicator. This can
possibly break existing api that relys on TotalChanges. ChangesDone
will still exist, but instead of relying on the current changes seq
it is simply a reflection of how many documents were written by the
updater process.
The new responses look like this:
```
[
{
"node": "node1@127.0.0.1",
"pid": "<0.622.0>",
"changes_done": 199,
"current_version_stamp": "8131141649532-0-198",
"database": "testdb",
"db_version_stamp": "8131141649532-0-999",
"design_document": …
```
=> add active_tasks for view builds using version stamps

src/setup/src/setup.erl
Resolves #2858
Fixes cluster setup failure when uuid is not set. 
Added code to call `couch_server:get_uuid()` to ensure that uuid is set. 
Sample docker-compose file
```
version: '3'
services:
couch1:
image: couchdev
environment:
- COUCHDB_USER=user
- COUCHDB_PASSWORD=pass
- COUCHDB_SECRET=secret
- NODENAME=10.0.0.10
networks:
couch:
ipv4_address: 10.0.0.10
command: "-setcookie cookie"
volumes:
- ./data1:/opt/couchdb/data
couch2:
image: couchdev
environment:
- COUCHDB_USER=user
- COUCHDB_PASSWORD=pass
- COUCHDB_SECRET=secret
- NODENAME=10.0.0.11
networks:
couch:
ipv4_address: 10.0.0.11
command: "-setcookie cookie"
volumes:
- ./data2:/opt/couchdb/data
networks:
couch:
driver: bridge
ipam:
config:
- subnet: 10.0.0.0/16
```
Sample script
```
curl …
```
=> fix: finish_cluster failure due to missing uuid

src/mango/src/mango_selector.erl, src/mango/test/03-operator-test.py
Proposition of a new Mango query operator that allows to query on the keys of a map.
It is related to the already existing `$elemMatch` but instead on the elements of an array it is applied on the keys 
of a map.
For the name of the operator I don't know what's best suited, I used `$keyMapMatch`.
https://github.com/apache/couchdb-documentation/pull/574
=> New mango operator proposal : match keys of a map

src/chttpd/src/chttpd_db.erl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_server.erl, src/fabric/test/fabric2_db_crud_tests.erl, src/fabric/test/fabric2_db_security_tests.erl
Previously, if a database was re-created on another node, a request with that database might have found the previous db instance in the cache. In that case it would have correctly reopened the db while in a transaction, but, because
the old db instance was deleted it would throw a database_does_not_exist which was not the correct behavior.
To prevent that from happening, introduce an `interactive = true|false` option when opening a database. User requests may specify that option and then when the db is re-opened, it will allow it to automatically upgrade to the new db instance instead of returning an error.
Background processes will still get a `database_doest_not_exist` error if they keep a db open which has now been re-created.
The interactive option may also be used in the future to …
=> Allow interactive requests to reopen a re-created db instance

rel/files/couchdb.cmd.in
Provide full path to `epmd.exe` on Windows at startup time.
0. `make -f Makefile.win release`
1. Ensure `epmd.exe` is not running
2. Start `rel\couchdb\bin\couchdb.cmd`
3. Validate that Erlang directly launches `epmd.exe` using Procmon
=> Windows: provide full path to epmd

src/aegis/src/aegis.app.src.script
Optionally add a key manager application as a dependency
N/A
N/A
=> Optionally add a key manager application as a dependency

src/couch_views/src/couch_views_indexer.erl, src/couch_views/test/couch_views_map_test.erl, test/elixir/test/map_test.exs
Add support for the `_local_seq` option to views https://docs.couchdb.org/en/stable/api/ddoc/views.html#view-options
`make check` should pass
=> add local_seq option to views

src/couch/rebar.config.script
When building couch_js in RHEL, there is one error occurring with "undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'". This commit is to adjust binding library to address this issue.
```
Compiling priv/couch_ejson_compare/couch_ejson_compare.c
/usr/bin/ld: priv/couch_js/60/main.o: undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'
//usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ERROR: sh(cc priv/couch_js/60/http.o priv/couch_js/60/main.o priv/couch_js/60/utf8.o priv/couch_js/60/util.o -L/usr/local/lib -std=c++14 -lmozjs-60 -lm   -L"/usr/local/lib/erlang/lib/erl_interface-3.10.2.2/lib" -lerl_interface -lei -o priv/couchjs)
failed with return code 1 and …
```
=> fixup: Build couch_js for redhat linux

src/chttpd/src/chttpd_db.erl, src/couch/src/couch_util.erl
Db creation request accepts shard specific parameters `q`, `n` and `placement`, but passes them to `fabric` without validation. This leads to `badarg` crash in case of invalid parameter.
```bash
$ curl -u $(ADMIN):$(PASS) -X PUT -v "http://localhost:5984/test?q="
...
> PUT /test?q= HTTP/1.1
>
< HTTP/1.1 500 Internal Server Error
...
< Server: CouchDB/3.1.0 (Erlang OTP/20)
<
{"error":"unknown_error","reason":"badarg","ref":1446616448}
[error] 2020-08-13T17:39:05.160578Z couchdb@localhost.dev <0.18183.20> 7b4593be34 req_err(1446616448) unknown_error : badarg
[<<"erlang:list_to_integer/1">>,<<"mem3_util:q_val/1 L255">>,<<"mem3:choose_shards/3 L206">>,<<"fabric_db_create:generate_shard_map/2 L68">>,<<"fabric_db_create:go/2 L31">>,<<"chttpd_db:create_db_req/2 …
```
=> Validate shard specific query params on db create request

src/couch_index/src/couch_index_server.erl
If a ddoc is added immediately after database creation (_users and
_replicator when couchdb is used in a multi-tenant fashion), we can
crash couch_index_server in handle_db_event, as mem3_shards:local
throws an error.
=> Don't crash couch_index_server if the db isn't known yet

src/couch_replicator/src/couch_replicator_api_wrap.erl
If we don't handle it, it throws an error when trying to encode the full URL
string, for example:
```
badarg,[
{mochiweb_util,quote_plus,2,[{file,"src/mochiweb_util.erl"},{line,192}]},
{couch_replicator_httpc,query_args_to_string,2,[{file,"src/couch_replicator_httpc.erl"},{line,421}]},
{couch_replicator_httpc,full_url,2,[{file,"src/couch_replicator_httpc.erl"},{line,413}]},
{couch_replicator_api_wrap,open_doc_revs,6,[{file,"src/couch_replicator_api_wrap.erl"},{line,255}]}
]
```
This is also similar to what we did for open_revs encoding: https://github.com/apache/couchdb/commit/a2d0c4290dde2015e5fb6184696fec3f89c81a4b
`make check`
https://github.com/apache/couchdb/commit/a2d0c4290dde2015e5fb6184696fec3f89c81a4b
=> Handle jiffy returning an iolist when encoding atts_since query string

src/couch_views/src/couch_views_reader.erl
Any error there would just be generating a case clause.
Remove the `{not_found, missing}` clause since it was accidentally matching on the `Rev` string and it is included in the `_Else` clause anyway.
=> Do not use (catch ...) in couch_views_reader:load_docs/4

src/couch_jobs/src/couch_jobs_fdb.erl
During job removal, it was not cleared from the active area so
active_tasks would mistakenly believe the job still existed. When we
try to actually open the data it is not there and not_found error
would be issued. @nickva  found this issue during replication work.
Regression test run passes.
=> clear jobs data in active area during removal

src/chttpd/src/chttpd.erl
Backport #3092 to 3.x.
Closes #1600 and closes #2877 and closes #2041 .
=> 3.x backport: don't log client disconnects

dev/run, src/couch_mrview/src/couch_mrview_util.erl, src/mango/src/mango_cursor_view.erl, test/elixir/test/partition_mango_test.exs
When partition_query_limit is set for couch_mrview, it limits how many
docs can be scanned when executing partitioned queries. But this limits
mango's doc scans internally. This leads to documents not being scanned
to fulfill a query. This fixes:
https://github.com/apache/couchdb/issues/2795
Unit Test added.
=> bypass partition query limit for mango

src/mango/src/mango_cursor_text.erl, src/mango/test/08-text-limit-test.py
Previously, we passed in the unpacked version of the bookmark with
the cursor inside the options field. This worked fine for _find because
we didn't need to return it to the user. But for _explain, we return
the value back as unpacked tuple instead of a string and jiffy:encode/1
complains. Now we correctly extract the bookmark out of options, unpack
it, and then pass it separately in it's own field. This way options
retains it's original string form for the user so that invalid_ejson
is not thrown.
Regression tests should pass. If you create a text index, simply use _explain with a bookmark and verify the results.
=> fix bookmark passing with text indexes

src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_view.erl, src/chttpd/test/exunit/pagination_test.exs, src/couch_views/src/couch_views_http.erl
The pagination relied on id of the document. However for views it should use
combination of key and id.
The change is covered by tests. 
```
```
- https://github.com/apache/couchdb/pull/2870 - Pagination API 
- https://github.com/apache/couchdb/pull/2904 - Add support for previous bookmark
=> Fix ordering of page_size based pagination for views

src/fabric/src/fabric2_active_tasks.erl, src/fabric/test/fabric2_active_tasks_tests.erl
Empty maps maybe useful to initialize the data in some cases but we don't want
to emit an entry in the output with just an empty map.
While at it, add some tests to check the basics.
=> Handle empty maps in active_tasks data structure

src/dreyfus/src/dreyfus_fabric_cleanup.erl, src/dreyfus/test/elixir/test/search_test.exs
In some situation where design document for search index created by customer is not valid, the _search_cleanup endpoint will stop to clean up. This will leave some search index orphan. The change is to allow to continue to clean up search index even if there is invalid design document for search.
make elixir tests=src/dreyfus/test/elixir/test/search_test.exs
```
SearchTest
* test clean up search index with invalid design document (55.1ms)
ReshardHelpers
PartitionHelpers
Finished in 0.07 seconds
1 test, 0 failures
```
=> Allow to continue to cleanup search index even if there is invalid design document

src/dreyfus/src/dreyfus_fabric_cleanup.erl, src/dreyfus/test/elixir/test/search_test.exs
backport https://github.com/apache/couchdb/pull/3118 to 3.x
make elixir tests=src/dreyfus/test/elixir/test/search_test.exs
```
SearchTest
* test clean up search index with invalid design document (55.1ms)
ReshardHelpers
PartitionHelpers
Finished in 0.07 seconds
1 test, 0 failures
```
=> 3.x backport: Allow to continue to cleanup search index even if there is invalid ddoc

src/jwtf/src/jwtf_keystore.erl, src/jwtf/test/jwtf_keystore_tests.erl
#3070  Overview
Improve jwtf keystore error handling
Covered by eunit.
N/A
=> Improve jwtf keystore error handling

src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_db_test.erl
When copying a doc, the returned JSON contains two `"ok"` fields:
`curl -H'Destination: copied' --request COPY  http://adm:pass@127.0.0.1:15984/foo/5cdc97838a8c748f7352d488ab0004c6`
```JSON
{"ok":true,"ok":true,"id":"foo/copied","rev":"1-967a00dff5e02add41819138abb3284d"}
```
`make eunit apps=chttpd suites=chttpd_db_test`
=> Make COPY doc return only one "ok"

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/test/eunit/chttpd_delayed_test.erl
When set, every response is sent once fully generated on the server
side. This increases memory usage on the nodes but simplifies error
handling for the client as it eliminates the possibility that the
response will be deliberately terminated midway through due to a
timeout.
The config value can be changed at runtime without impacting any
in-flight responses.
Set `[chttpd] delay_until_end` to true then confirm that streamed responses are now sent non-stream (i.e, with a Content-Length header and not in chunked transfer mode).
N/A
=> Add option to delay responses until the end

src/couch_jobs/src/couch_jobs.erl
This mostly helps with flaky tests where some jobs might complete before the type monitor discovers this particular type, so opt to always re-scan and start notification monitors when any type timeout is set.
=> Update all the type monitors after setting any couch jobs type timeout

rebar.config.script
This can't be released until https://github.com/apache/couchdb-documentation/pull/586 and https://github.com/apache/couchdb-fauxton/pull/1292 are merged and both repos are tagged/released correctly. In Fauxton's case this involves a `grunt couchdb` run, see https://github.com/apache/couchdb-fauxton/pull/1289
=> Bump fauxton, docs for 3.1.1 release

src/smoosh/src/smoosh_channel.erl
Smoosh monitors the compactor pid to determine when the compaction jobs
finishes, and uses this for its idea of concurrency. However, this isn't
accurate in the case where the compaction job has to re-spawn to catch up on
intervening changes since the same logical compaction job continues with
another pid and smoosh is not aware. In such cases, a smoosh channel with
concurrency one can start arbitrarily many additional database compaction jobs.
To solve this problem, we added a check to see if a compaction PID exists for
a db in `start_compact`. But this is the wrong approach because it’s for a
shard that comes off the queue. So it’s a different shard and the following
can occur:
1. Enqueue a bunch of stuff into channel with concurrency 1
2. Begin highest priority job, Shard1, in channel …
=> move remonitor code into DOWN message

src/chttpd/src/chttpd.erl, src/chttpd/test/eunit/chttpd_delayed_test.erl
We need to call StartFun as it might add headers, etc.
=> Fix buffer_response=true

test/elixir/README.md, test/elixir/test/view_conflicts_test.exs, test/elixir/test/view_errors_test.exs, test/elixir/test/view_include_docs_test.exs, test/javascript/tests/view_conflicts.js, test/javascript/tests/view_errors.js, test/javascript/tests/view_include_docs.js
This PR ports following tests into Elixir test suite:
- view_conflicts.js
- view_errors.js
- view_include_docs.js
```
make elixir tests=test/elixir/test/view_conflicts_test.exs
make elixir tests=test/elixir/test/view_errors_test.exs
make elixir tests=test/elixir/test/view_include_docs_test.exs
```
N/A
=> Port view_conflicts.js, view_errors.js and view_include_docs.js into elixir

src/couch/src/couch_db.erl, src/smoosh/src/smoosh_channel.erl
This fixes a94e693f32672e4613bce0d80d0b9660f85275ea because a race
condition exisited where the 'DOWN' message could be received
before the compactor pid is spawned. Adding a synchronous call to
get the compactor pid guarantees that the couch_db_updater process
handling of finish_compaction has occurred.
=> fix race condition

build-aux/Jenkinsfile.full
Without this, all Jenkins builds will fail.
=> Drop Jenkins ppc64le builds (for now)

src/ebtree/src/ebtree.erl
Fix bug in ebtree:umerge_members/4
`make check`
=> Fix bug in ebtree:umerge_members/4

src/chttpd/src/chttpd_node.erl
This is a first pass at fixing https://github.com/apache/couchdb/issues/3160 for reporting proper run_queue statistics.
=> Workaround dirty schedulers in run_queue stats

Makefile, Makefile.win
Backport PR #2684 into 3.x
This change is required by ProxyAuthTests and JWT tests int he elixir test suite which are failing in the windows build, see #3158 and #3159 
This PR fixes #3158 and fixes #3159
=> Backport 3.x -Update Makefile.win to Include locad configs and clean configs in devclean

test/elixir/README.md, test/elixir/test/view_conflicts_test.exs, test/elixir/test/view_errors_test.exs, test/elixir/test/view_include_docs_test.exs, test/javascript/tests/view_conflicts.js, test/javascript/tests/view_errors.js, test/javascript/tests/view_include_docs.js
Backport this PR #3025 to 3.x
The PR ports view_conflicts.js, view_errors.js and view_include_docs.js into elixir test suite
=> Backport 3.x - Port view_conflicts.js, view_errors.js and view_include_docs.js into elixir

src/chttpd/src/chttpd_rewrite.erl, test/javascript/tests/rewrite_js.js
During the porting of rewrite_js.js tests into the elixir test suite I've found an erroneous behavior in the JS-rewrite functionality. 
When a rewritten request contains a BODY (POST/PUT) and the rewrite rule rewrites the query string, this query string is ignored in the final request. The following case illustrates this issue.
1 - Create a design document with a rule that rewrites the query string, like this one:
```
{
"_id": "_design/n", 
"rewrites": "function (r) { return {path: '../../_changes', query: {'filter': '_doc_ids'}};};"
}
```
any request should be rewritten to `_changes?filter=_docs_ids`
```
curl -XPOST -u adm:pass -H "Content-type: application/json" \
-d '{"_id": "_design/n", "rewrites": "function (r) { return {path: '\''../../_changes'\'', query: {'\''filter'\'': …
```
=> JS-Rewrite: Preserve query string rewrite when the request contains a body

test/elixir/test/reshard_all_docs_test.exs, test/elixir/test/reshard_basic_test.exs, test/elixir/test/reshard_changes_feed.exs, test/elixir/test/update_documents_test.exs, test/elixir/test/view_collation_raw_test.exs, test/elixir/test/view_collation_test.exs, test/elixir/test/view_compaction_test.exs, test/elixir/test/view_conflicts_test.exs, test/elixir/test/view_errors_test.exs, test/elixir/test/view_include_docs_test.exs, test/elixir/test/view_multi_key_all_docs_test.exs, test/elixir/test/view_multi_key_design_test.exs, test/elixir/test/view_sandboxing_test.exs
Some elixir test cases don't have actual module tag. Add tags to help include or exclude them in CI test.
make elixir
=> Add module tag to elixir test cases

src/couch_replicator/src/couch_replicator_filters.erl, src/couch_replicator/src/couch_replicator_job.erl, src/couch_replicator/src/couch_replicator_jobs.erl, src/couch_replicator/test/eunit/couch_replicator_transient_jobs_tests.erl
There are two fixes:
1)  Fix transient replication job state wait logic
Make sure to handle both `finished` and `pending` states when waiting for a
transient jobs. A transient job will go to the `failed` state if it cannot
fetch the filter from the source endpoint. For completeness, we also account
for `pending` states in there in the remote chance the job get rescheduled
again.
2) Fix error reporting when fetching replication filters
Don't unnecessarily unwrap the fetch error since `error_info/1` can already
handle the current shape. Also, make sure to translate the reason to binary for
consistency with the other filter fetching errors in the
`couch_replicator_filters` module.
The end-to-end test in the second commits checks the waiting behavior and the error reporting.
=> Fix transient replication jobs failure handling

src/couch_replicator/src/couch_replicator.erl
This is mainly for compatibility with CouchDB 3.x
Ref: https://docs.couchdb.org/en/stable/api/server/common.html#scheduler-jobs
=> Add node and pid to _scheduler/jobs output

test/elixir/test/security_validation_test.exs, test/javascript/tests/security_validation.js
This PR completes the porting of security_validation.js test into Elixir. 
security_validation.js was partially ported and this PR completes that work.
```
make elixir
```
N/A
=> Complete the port of security_validation tests to Elixir

test/elixir/README.md, test/elixir/lib/couch.ex, test/elixir/test/users_db_security_test.exs, test/javascript/tests/users_db_security.js
This PR ports `users_db_security.js` tests into the elixir test suite. During the porting of this test I needed to add support for raw responses to Couch.Session module.
This is the last active test to be ported from the javascript test suite. The javascript test suite can be removed from the main build process as there are no more test being ran. I'll prepare a separate PR for this.
`make javascript` All test should be skipped or ported
`make elixir` All test should pass
N/A
=> Port users_db_security javascript tests to elixir

src/couch_replicator/include/couch_replicator_api_wrap.hrl, src/couch_replicator/src/couch_replicator_api_wrap.erl, src/couch_replicator/src/couch_replicator_utils.erl
Previously there was an attempt to keep backwards compatibility with 3.x replicator plugins by transforming the auth into a proplist with `maps:to_list/1`. However, that didn't account for nested properties, so we could have ended up with a top level of props with maps for some values. Instead of making things too complicating, and doing a nested transform to proplists, just keep the auth object as a map and let the plugins handle the compatibility issue.
=> Keep auth properties as a map in replicator's httpdb record

Makefile, Makefile.win
All the active JS tests have been ported to elixr. The current `make javascript` execution is not performing any test.
I propose to remove it from the main build process.
This PR removes `@$(MAKE) javascript` from the `check` target
``` make check``` should not run the javascript test suite
N/A
=> Proposal for removing javascript tests from main build process

src/couch_replicator/src/couch_replicator_job.erl
This value is emitted in _active_tasks and was previously emitting `null` values from the state record's defaults.
=> Properly initialize `user` in replication job's state

.asf.yaml
This PR re-enables merge commits (disabled in https://github.com/apache/couchdb/pull/3020). As such I will follow the same stipulations there before merging, that we need 3 +1 votes to proceed.
=> Merge commits main

Makefile, Makefile.win, test/elixir/README.md, test/elixir/lib/couch.ex, test/elixir/test/users_db_security_test.exs, test/javascript/tests/users_db_security.js
This PR backports the last test ported to elixir and javascript target removal form the build process.
- Port users_db_security javascript tests to elixir #3190
- Proposal for removing javascript tests from main build process #3192
```make check``` should pass without running js tests
#3190 
#3192
=> 3x backport - final javascript tests ported to elixir

src/couch_replicator/src/couch_replicator_job.erl
Previously there was an attempt to shortcut some of the job initialization if replication ID in the job data and the newly computed one matched. However, that logic was wrong as it skipped over the job data state update.
The effect was that if a job was in a pending state, and it re-initialized, say when a node restarted, its job data would still indicate it as "pending" until the next checkpoint. If the job is continuous, and there are no more updates on the source, the state of the job would stay in "pending" indefinitely.
=> Do not shortcut replicator job initialization if replication ID matches

src/couch_mrview/src/couch_mrview_http.erl, test/elixir/test/all_docs_test.exs, test/elixir/test/view_test.exs
When using a POST with request body to pass parameters to a view-like request the boolean parameters are accepting only JSON strings, but not booleans. For example the stable parameter works with "true" and "false" but not true and false.
`mix test --trace test/elixir/test/all_docs_test.exs`
and
`mix test --trace test/elixir/test/view_test.exs`
This fixes #3200 .
=> Fix boolean POST to view-like endpoints

src/couch_replicator/src/couch_replicator_httpc.erl
`Headers1` is not used anywhere
=> Removed unused variable in merge headers unit test

src/couch_replicator/src/couch_replicator_httpc.erl
This is a backport of https://github.com/apache/couchdb/pull/3211 from main
=> Properly combine base and extra headers when making replicator requests

.github/ISSUE_TEMPLATE/config.yml
This presents new links on the New Issue page, similar to this:
=> Direct people to Discussions/docs from new issue

src/chttpd/src/chttpd.erl, test/elixir/test/bulk_docs_test.exs
If transaction exceeds byte limit using the `_bulk_docs` endpoint,  the `{u'reason': u'2101', u'ref': 3853288219, u'error': u'erlfdb_error'}` with 500 error code was returned.  This is user-friendly. Using this PR is to provide meaningful error message to users. 
The test python code:
```
import requests, json, random, string, os
print(requests.post(
"http://127.0.0.1:15984/foo/_bulk_docs"
, json={
"docs":
[
{"foo": "".join(random.choice(string.ascii_lowercase) for x in range(16000000))}
]}
, auth=('foo', 'bar')
).json())
```
Original response:
```
{u'reason': u'2101', u'ref': 3853288219, u'error': u'erlfdb_error'}
```
New response:
```
{u'reason': u'The request transaction is larger than 10MB', u'error': u'transaction_too_large'}
```
make elixir tests=test/elixir/test/bulk_docs_test.exs …
=> convert erlfdb_error 2101 to transaction_too_large

src/chttpd/src/chttpd_db.erl, test/elixir/test/all_docs_test.exs, test/elixir/test/attachment_names_test.exs
This PR solves the problem described at the issue #1988 
PUT & POST operations for creating documents in a database enforce different validation rules over the attachment names of the new document.
When a document is created with a PUT operation "_foo.txt" is not accepted as a valid attachment name. If the document is created by a POST operation the "_foo.txt" attachment name is accepted.
This is an inconsistent behavoiur in the API as not accepted attachment names can be created. 
```
make elixir tests=test/attachment_names_test.exs
```
This PR fixes #1988
=> Fix #1988 - Validate attachment names on POST /db/doc

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/couch_views/src/couch_views_reader.erl, src/couch_views/src/couch_views_trees.erl, src/couch_views/src/couch_views_util.erl, src/couch_views/test/couch_views_custom_red_test.erl
Disable custom reduce functions by default.
Custom reduce functions are notoriously difficult to implement correctly and often lead to fairly bad user experience when they're inevitably misunderstood or used incorrectly. The feature will remain available via config toggle for at least 4.0.
`make check`
=> Disable custom reduce functions by default

src/chttpd/src/chttpd.erl, test/elixir/test/bulk_docs_test.exs
If transaction exceeds byte limit using the `_bulk_docs` endpoint,  the `{u'reason': u'2101', u'ref': 3853288219, u'error': u'erlfdb_error'}` with 500 error code was returned.  This is user-friendly. Using this PR is to provide meaningful error message to users. 
The test python code:
```
import requests, json, random, string, os
print(requests.post(
"http://127.0.0.1:15984/foo/_bulk_docs"
, json={
"docs":
[
{"foo": "".join(random.choice(string.ascii_lowercase) for x in range(16000000))}
]}
, auth=('foo', 'bar')
).json())
```
Original response:
```
{u'reason': u'2101', u'ref': 3853288219, u'error': u'erlfdb_error'}
```
New response:
```
{u'reason': u'The request transaction is larger than 10MB', u'error': u'transaction_too_large'}
```
make elixir tests=test/elixir/test/bulk_docs_test.exs …
=> convert erlfdb_error 2101 to transaction_too_large for main

src/couch_views/src/couch_views_trees.erl, src/couch_views/test/couch_views_red_test.erl
Before this change a reduce call that contained no rows would end up
returning the "default" value of the given reduce function which is
whatever it would return when given an empty array as input. This
changes the behavior to return `{"rows": []"}` when there are no
rows in the requested range.
`make check`
=> Fix empty reduce output to match 3.x behavior

src/chttpd/src/chttpd_db.erl, test/elixir/test/attachment_names_test.exs
This PR backports the fix for apache/couchdb#1988 into 3.x branch.
This change has been merged into main with PR #1997 
```
make elixir
```
PR #1997 
Issue #1988
=> 3.x backport - Fix apache/couchdb#1988 -  Validate attachment names

src/chttpd/test/exunit/pagination_test.exs, src/couch_views/src/couch_views_http.erl
The `total_rows` field suppose to be a number of documents in the database/view.
See https://docs.couchdb.org/en/stable/api/ddoc/views.html.
When new pagination API was introduced the meaning of `total_rows` field was
changed to number of rows in the query results. The PR reverts this
accidental change.
make check
- https://github.com/apache/couchdb/pull/2870 - Pagination API
=> Fix semantics of total_rows

src/couch_expiring_cache/.suppressed, src/couch_expiring_cache/src/couch_expiring_cache.erl, src/couch_expiring_cache/src/couch_expiring_cache_fdb.erl
Too many parallel attempts to insert the same keys can result in
`{erlfdb_error, 1020}`, which translates to:
"Transaction not committed due to conflict with another transaction"
This attempts to mitigate the problem by using a snapshot to
read the primary key during cache insertion.
```
make eunit apps=couch_expiring_cache
```
=> Use snapshot for expiring cache insertion

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
This drops the mandate to always pull the latest Docker containers for Jenkins builds, in light of the new nightly Jenkins job @ https://ci-couchdb.apache.org/job/jenkins-cm1/job/Update%20Docker%20Containers/ .
=> Jenkins: do not alwaysPull true

Makefile, Makefile.win
Currently `npm install --production` is used when creating the Fauxton release. Due to changes in https://github.com/apache/couchdb-fauxton/pull/1299, build time tools (like `grunt`) will no longer be available when installing dependencies with the `--production` flag.
To account for this new behavior, this PR removes the `--production` flag on both Makefiles. 
Note this change only impacts what is installed inside the `node_modules` folder, but it has no impact on the Fauxton assets generated and copied to the `share/www` folder.
```
git clone https://github.com/apache/couchdb-fauxton src/fauxton
make fauxton with_fauxton=1
```
Then `ls share/www` to verify the assets were created.
https://github.com/apache/couchdb-fauxton/pull/1299
=> Remove '--production' flag when building Fauxton

src/couch/src/couch_query_servers.erl, src/couch/test/eunit/couch_query_servers_tests.erl
A document with lots of conflicts can blow up couchjs if the user
calls _changes with a javascript filter and with `style=all_docs` as
this option causes up to fetch all the conflicts.
All leaf revisions of the document are then passed in a single call to
ddoc_prompt, which can fail if there's a lot of them.
In that event, we simply try them sequentially and assemble the
response from each call.
Should be backported to 3.x
Covered by unit test but a manual test would proceed as follows;
You need to create a highly conflicted document and lower couchjs's memory allowance for a practical test. Here's how I did it;
1) edit dev/run;
```
-    qs_javascript = toposixpath("%s %s" % (couchjs, mainjs))
+    qs_javascript = toposixpath("%s -S 1048576 %s" % (couchjs, mainjs))
```
2) create a filter; …
=> Retry filter_docs sequentially if the patch exceeds couchjs stack

src/aegis/src/aegis.erl, src/aegis/src/aegis_key_manager.erl, src/aegis/test/aegis_server_test.erl, src/fabric/src/fabric2_fdb.erl
This PR adds encryption-related information to the db info blob (GET /dbname). At
minimum a boolean "enabled" flag is present, but the key manager might add additional fields.
eunit
N/A
=> Add an "encryption" object to db info

src/couch/src/couch_db.erl, src/smoosh/src/smoosh_channel.erl
Smoosh monitors the compactor pid to determine when the compaction jobs
finishes, and uses this for its idea of concurrency. However, this isn't
accurate in the case where the compaction job has to re-spawn to catch up on
intervening changes since the same logical compaction job continues with
another pid and smoosh is not aware. In such cases, a smoosh channel with
concurrency one can start arbitrarily many additional database compaction jobs.
To solve this problem, we added a check to see if a compaction PID exists for
a db in `start_compact`. But wee need to add another check because this check
is only for shard that comes off the queue. So the following can still occur:
1. Enqueue a bunch of stuff into channel with concurrency 1
2. Begin highest priority job, Shard1, in channel
3. …
=> 3.x porting - add remonitor code to DOWN message (#3144)

src/couch/src/couch_util.erl, src/couch/test/eunit/couch_util_tests.erl
Cherry picked from `main` branch.
It can be desirable in some cases for decoded JSON to e.g. return
maps instead of the default data structure, which is not currently
possible.
This exposes a new function `couch_util:json_decode/2`, the second
parameter being a list of options passed to `jiffy:decode/2`.
=> Expose `couch_util:json_decode/2` to support jiffy options

src/mem3/test/eunit/mem3_seeds_test.erl
This is to fix the possible failure of `mem3_seeds_test: a_test_ (optional local _users db in mem3_sync:local_dbs())...[0.029 s] ok` because local databases do not always include `_dbs` and `_nodes`.
make check skip_deps+=couch_epi apps=mem3
=> fix check_local_dbs test

src/couch_views/src/couch_views_trees.erl, src/ebtree/src/ebtree.erl, src/fabric/test/fabric2_tx_options_tests.erl
Caching in ebtree was incorrect in the presence of FoundationDB transaction retries. This removes the caching feature and use of that feature. Luckily it was never measured to have a major impact on performance so this should have minimal effects.
`make check`
=> Remove ebtree caching

src/ebtree/src/ebtree.erl
If the root node is a prefix of any UUID then we end up accidentally clearing any UUID that shares that prefix.
`make check`
=> Avoid deleting UUID keys that start with zeros

src/couch/src/couch_httpd.erl
When we call `couch_httpd:json_body/1` we can have `req_body` already set.
In this case we should return the field as is without any attempt to
decompress or decode it. This PR brings the approach we use in `chttpd`
into `couch_httpd`.
```
make check
```
We port an approach from https://github.com/apache/couchdb/pull/2991 into `couch_httpd`
=> Use `req_body` field if present

src/couch/src/couch_att.erl
If an attachment was stored uncompressed but later is replicated
internally to a node that wants to compress it (based on
content-type), couchdb compares the uncompressed md5 with the
compressed md5 and fails. This breaks eventual consistency between
replicas.
This PR removes the unnecessary MD5 check that is, in these specific
circumstances, always called with mismatched arguments.
1. Upload an attachment with a content-type not included in compressible_type config
2. change compressible_type to include this content-type
3. stop a node
4. delete the hosting shard of the attachment
5. start the node.
6. observe md5_mismatch errors in the log.
N/A
=> Couch att erroneous md5 mismatch

rebar.config.script
https://github.com/apache/couchdb-erlfdb/releases/tag/v1.2.3
=> Bump erlfdb to v1.2.3

src/couch_views/src/couch_views_indexer.erl, src/couch_views/test/couch_views_indexer_test.erl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_changes_fold_tests.erl, src/fabric/test/fabric2_snapshot_tests.erl
View indexers create conflicts when reading from the changes feed which can prevent the indexer from making progress on databases that are being updated continuously.
I'm marking this as a draft because it doesn't yet address the situation of a single doc being updated repeatedly and there's no tests proving it works either. (Second time's a charm!)
I should add a test.
=> Ensure view build progress

src/chttpd/src/chttpd.erl, src/couch_replicator/src/couch_replicator_httpd.erl, src/couch_replicator/test/eunit/couch_replicator_db_tests.erl, test/elixir/test/basics_test.exs
Some responses are missing default headers. This PR fixes that issue.
Run the tests included and/or the manual ones mentioned in the original issue ticket.
`make eunit apps=couch_replicator suites=couch_replicator_db_tests`
and
`mix test --trace test/elixir/test/basics_test.exs:523`.
#3261
=> Add missing default headers to responses

src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_misc.erl, src/chttpd/src/chttpd_show.erl, src/chttpd/test/eunit/chttpd_handlers_tests.erl, src/couch/src/couch_httpd.erl
When we call couch_httpd:json_body/1 we can have req_body already set.
In this case we should return the field as is without any attempt to
decompress or decode it. This PR brings the approach we use in chttpd
into couch_httpd.
backported from #3268 and #2991
`make check`
- #2991
- #3268
=> Req body json 3.x

src/chttpd/src/chttpd.erl, src/couch_replicator/src/couch_replicator_httpd.erl, test/elixir/test/basics_test.exs, test/elixir/test/replication_test.exs
This is a backport of #3279 .
This closes #3261 .
=> Backport add missing default headers to responses to 3.x

Makefile, Makefile.win, mix.exs, test/elixir/lib/suite.ex, test/elixir/test/config/skip.elixir, test/elixir/test/config/suite.elixir, test/elixir/test/test_helper.exs
New `elixir-suite` Makefile target is added. It runs a predefined set of elixir
integration tests.
The feature is controlled by two files:
- test/elixir/test/config/suite.elixir - contains list of all available tests
- test/elixir/test/config/skip.elixir - contains list of tests to skip
In order to update the `test/elixir/test/config/suite.elixir` when new tests
are added. The one would need to run the following command:
```
MIX_ENV=integration mix suite > test/elixir/test/config/suite.elixir
```
The number of enabled tests in this PR is 237, while `make check` has only 80.
1) Make sure that tests discovery works
```
MIX_ENV=integration mix suite
```
2) Make sure the tests run and pass by using `make elixir-suite`
- somewhat related to https://github.com/apache/couchdb/issues/1515 in a …
=> Add ability to control which Elixir integration tests to run

src/couch/priv/couch_js/1.8.5/help.h, src/couch/priv/couch_js/60/help.h, src/couch/priv/couch_js/68/help.h, src/couch/rebar.config.script
Closes #2906 
* Added a suffix to the first line of couchjs with the (static) version number compiled
* Update rebar.config.script
* In couchjs -h replaced the link to jira with a link to github
Co-authored-by: simon.klassen <simon.klassen>
Co-authored-by: Jan Lehnardt <jan@apache.org
=> 2906 couchjs sm version (#2911)

src/custodian/rebar.config.script, src/custodian/src/custodian.app.src.script, src/custodian/src/custodian_db_checker.erl, src/custodian/src/custodian_monitor.erl, src/custodian/src/custodian_noop_monitor.erl, src/custodian/src/custodian_server.erl
Enable build time configurable monitor for custodian and remove custom
sensu events.
```
make eunit apps=custodian
```
=> Support pluggable custodian monitor

src/couch_replicator/src/couch_replicator_httpc.erl
While CouchDB itself never responds with a 408 Request Timeout it is possible for a proxy to do so. The CouchDB Replicator treats a 408 as a permanent error, increments doc_write_failures, and keeps going. This is undesirable. This patch reorders the clauses in couch_replicator_httpc so we can easily treat a 408 the same way we treat any 5xx code (by retrying).
TBD
N/A
=> treat 408 as a retryable error condition

src/couch_replicator/src/couch_replicator_httpc.erl
While CouchDB itself never responds with a 408 Request Timeout it is possible for a proxy to do so. The CouchDB Replicator treats a 408 as a permanent error, increments doc_write_failures, and keeps going. This is undesirable. This patch reorders the clauses in couch_replicator_httpc so we can easily treat a 408 the same way we treat any 5xx code (by retrying).
TBD
N/A
=> treat 408 as a retryable error condition (#3303)

src/chttpd/test/eunit/chttpd_session_tests.erl, src/couch/src/couch_httpd.erl, src/couch/src/couch_httpd_auth.erl
All endpoints but `_session` support gzip encoding and there's no practical reason for that.
This PR enables gzip decoding on compressed requests to `_session`.
`make eunit apps=chttpd suites=chttpd_session_tests`
This fixes #3300 .
This is #3322 cherry-picked to `main`.
=> Allow gzipped requests to _session

src/chttpd/src/chttpd.erl, src/mango/src/mango_cursor_view.erl
If a mango query exceeds the 5 seconds for a transaction it sends a nasty error:
```
89e90f4c55 req_err(2721591552) erlfdb_error : 1031
[<<"erlfdb_nif:erlfdb_future_get/1">>,<<"erlfdb:do_transaction/2 L686">>,<<"fabric2_fdb:do_transaction/2 L171">>,<<"fabric2_fdb:transactional/2 L142">>,<<"mango_cursor_view:execute/3 L142">>,<<"mango_httpd:handle_find_req/2 L197">>,<<"mango_httpd:handle_req/2 L37">>,<<"chttpd:handle_req_after_auth/2 L330">>]
```
This cleans that up and adds a better error. We also remove the `{restart_tx, true}` for a mango query that uses `_all_docs` to make it consistent with a mango query that uses a view.
=> Timeout transaction

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, README-DEV.rst, configure, erlang_ls.config
This PR adds a Dockerfile and associated configuration to enable developers to quickly provision an environment with all dependencies installed to work on CouchDB 3.x.
The container configuration also installs the [Erlang Language Server](https://erlang-ls.github.io) extension. That extension needs a minimal configuration file in the root of the project in order to find the include files, so I've added that as well. We could likely iterate and enhance that configuration file further with linters, dialyzers configurations, etc.
If you have VS Code with the "Remote - Containers" extension installed, opening the CouchDB repo should cause the editor to offer to start the development container. The container will include all the dependences necessary to
* build CouchDB using `./configure; …
=> Add a .devcontainer configuration for 3.x

.gitignore, Makefile, dev/boot_node.erl, dev/make_boot_script, dev/monitor_parent.erl, dev/run
This patch introduces an escript that generates an Erlang .boot script to start CouchDB using the in-place .beam files produced by the compile phase of the build. This allows us to radically simplify the boot process for dev nodes as Erlang computes the optimal order for loading the necessary modules, and the previous logic in `boot_node` was, well, _not_ optimal 😄 
In addition to the simplification this approach offers a nice startup time speedup, at least when working inside a container environment. In my test with the stock .devcontainer it reduces startup time from about 75 seconds down to under 5 seconds 🚀 
I had initially introduced a new `devnode` target in the Makefile but figured just invoking the script if the `devnode.boot` file is missing would be sufficient. Note that this …
=> Simplify and speedup dev node startup

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yaml, Makefile, configure, erlang_ls.config, rel/files/eunit.config
This creates a development environment with a FoundationDB server and a CouchDB layer in two containers, sharing a network through Docker Compose.
It uses the FDB image published to Docker Hub for the FDB container, and downloads the FDB client packages from foundationdb.org to provide the development headers and libraries. www.foundationdb.org is actually not trusted in Debian Buster by default, so we have to download the GeoTrust_Global_CA.pem. The following link has more details:
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962596
Once the Docker Compose setup is running, VS Code executes the `create_cluster_file.bash` script to write down a cluster file containing the IP address in the compose network where the FDB service can be found. This cluster file is used both for a …
=> Add a development container for VS Code / GitHub Codespaces

rel/overlay/etc/default.ini, src/couch/src/couch_att.erl, src/couch/test/eunit/couch_doc_tests.erl
The current default for `max_attachment_size` is `infinity`. This PR changes that to 1 gibibyte.
No testing, this is just a default change.
N/A
=> Set a finite default for max_attachment_size

src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_db_attachment_size_tests.erl, src/couch/src/couch_httpd.erl
This is the backport of 235d1e9 to `main`.
This is related to https://github.com/apache/couchdb/issues/1943
=> Fix PUT of multipart/related attachments support for Transfer-Encoding: chunked

src/setup/src/setup.erl
This PR backports #3036 into 3.x 
It resolves the issue #2858
=> 3.x backport - fix: finish_cluster failure due to missing uuid (#3036)

src/chttpd/src/chttpd.erl, test/elixir/test/bulk_docs_test.exs
Ensure a reasonable error message should an FDB error reach the top of the request handling stack.
This change also removes the inappropriate usage of the 408 Request Timeout status code. a 1031 transaction_timeout from FDB is sent if the transaction takes too long, which is typically not even started until after we've received the full request.
Just break something. :)
https://github.com/apache/couchdb/issues/3354
=> Handle all erlfdb error codes

src/couch/src/couch_task_status.erl
This allows users to verify that compaction processes are suspended
outside of any configured strict_window.
N/A
N/A
=> Show process status in active_tasks

rel/overlay/etc/default.ini, src/couch/src/couch_db_engine.erl, src/couch/src/couch_db_updater.erl, src/couch/src/couch_lru.erl, src/couch/src/couch_primary_sup.erl, src/couch/src/couch_server.erl, src/couch/test/eunit/couch_bt_engine_compactor_ev_tests.erl, src/couch/test/eunit/couch_db_split_tests.erl, src/couch/test/eunit/couch_db_tests.erl, src/couch/test/eunit/couch_server_tests.erl, src/couch/test/eunit/couchdb_db_tests.erl, src/couch_pse_tests/src/cpse_util.erl
Break up the monolithic couch_server to avoid a bottleneck.
Heavy usage.
N/A
=> Couch server sharding

src/chttpd/src/chttpd_node.erl, src/couch/src/couch_server.erl
This helps ease transition from singleton couch_server to
multiple. The "couch_server" message queue is simply the sum of the
couch_server_X message queues.
N/A
https://github.com/apache/couchdb/pull/3366
=> Add "couch_server" aggregate to _system output

src/jwtf/test/jwtf_keystore_tests.erl
The `config` application depends on `couch_log`, so include it when setting up and tearing down tests.
Without this change, I'm seeing e.g.
```
module 'jwtf_keystore'
module 'jwtf_keystore_tests'
*** context setup failed ***
**in function gen_server:call/3 (gen_server.erl, line 223)
in call from jwtf_keystore_tests:setup/0 (test/jwtf_keystore_tests.erl, line 24)
**exit:{{noproc,{gen_server,call,
[couch_log_server,
{log,{log_entry,notice,<0.19418.3>,
["config",58,32,91,[...]|...],
"--------",
"2021-02-16T05:56:53.981693Z"}}]}},
{gen_server,call,
[config,
{set,"jwt_keys","hmac:hmac","aGVsbG8=",
#{persist => true,reason => nil}},
30000]}}
```
```
make check apps=jwtf
```
=> Include necessary dependency in jwtf keystore test setup & teardown

src/chttpd/src/chttpd_db.erl, src/couch/src/couch_changes.erl, test/elixir/test/changes_test.exs
During `POST` on `/{db}/_changes` with a custom filter, nodes attempt to [read the request payload](https://github.com/apache/couchdb/blob/3.x/src/couch/src/couch_changes.erl#L241), unless the request body already stored on a request record. When this is happening on a node foreign to the original http request, reader process quits with `exit:normal` and as a result the whole fabric request hangs until a timeout.
This patch switches filter reader to `chttpd_external:json_req_obj/2` for more descriptive exit message, adds reading of the payload on the request handler and validates that payload, when present, is a proper JSON object.
Related tests been added to the elixir tests
`make elixir tests=test/elixir/test/changes_test.exs`
Closes #3087
=> Read and validate JSON payload on POST to _changes

rel/apps/config.config
This defines a configuration file which specifies sections and fields
for config values that are redacted from logs. Specifically, all
values from the "admins" section and the value of "password" in the
"replicator" section are redacted.
This must be tested with its companion PR below.
In a remsh, set an admin password: `config:set("admins", "admin1", "secretpassword").`, and then reload: `config:reload().` and you should see the following redactions in the log:
```
[notice] 2021-02-20T06:16:30.672944Z node1@127.0.0.1 <0.196.0> -------- config: [admins] admin1 set to '****' for reason nil
[notice] 2021-02-20T06:17:13.720003Z node1@127.0.0.1 <0.196.0> -------- Reload detected config change admins.admin1 = '****'
```
https://github.com/apache/couchdb-config/pull/35
=> Configure sensitive config values for redaction

src/couch_views/test/couch_views_indexer_test.erl, src/ebtree/src/ebtree.erl
There was a bug in `ebtree:lookup_multi/3` that prevented some lookup keys from matching if they happened to first be compared against another lookup key that doesn't exist.
`make check`
N/A
=> Fix view row bug

src/ebtree/src/ebtree.erl
Replace the `=:=` comparison with a collate `eq` call.
=> use collate in lookup

src/ebtree/src/ebtree.erl
A tidier version of https://github.com/apache/couchdb/pull/3384 that
saves an unnecessary call to collate.
=> Optimize lookup/3

dev/run
Since `main` isn't necessarily clustered as it was "pre-`main`", setting the default node number to 1 makes startup times quicker.
=> Set default nodes in dev/run to 1

src/jwtf/src/jwtf.erl
Previously, if a JWT claim was present, it was validated regardless of
whether it was required.
However, [according to the spec](https://tools.ietf.org/html/rfc7519#section-4):
> all claims that are not understood by implementations MUST be ignored
which we interpret to mean that we should not attempt to validate
claims we don't require.
With this change, only claims listed in required checks are validated.
```
make eunit apps=jwtf
```
=> Ignore unchecked JWT claims

rebar.config.script, src/couch_views/src/couch_views_indexer.erl
This patch causes the indexing subsystem to use snapshot isolation when reading from the database. This reduces commit conflicts and ensures the index can make progress even in the case of frequently updated docs.
In the pathological case, a document updated in a fast loop can cause the indexer to stall out entirely when using serializable reads. Each successful update of the doc will cause the indexer to fail to commit if it processed that document. The indexer will retry with a new GRV but the same target DbSeq. In the meantime, our frequently updated document will have advanced beyond `DbSeq` and so the indexer will finish its job without indexing the document at all. This process can be repeated ad infinitum and the document will never actually show up in a view response.
Snapshot …
=> Relax isolation level when indexer reads from DB

Makefile
Quoting from https://github.com/apache/couchdb-erlfdb/pull/15:
> There are also bare references to `make` in couchdb's `Makefile` that need to be replaced with `@$(MAKE)`.
I'm precisely addressing this.
If the CI is happy, I assume we can be happy too.
=> Update Makefile stripping remaining direct make refs

rebar.config.script
This brings in the necessary fix for FreeBSD by including `/usr/local/{lib|include}`
=> Bump erlfdb to 1.2.6

src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_tx_options_tests.erl
1) First, as a cleanup, remove DB `Options` from the `init_db/3` call. We always follow `init_db/3` (sometimes called through `fabric2_fdb:transactional(DbName, ...)` with a `create(TxDb, Options)` or `open(TxDb, Options)`where we overrode `Options` anyway. The only time we didn't follow it up with a `create/2` or `open/2` is when dbs are deleted where `Options` wouldn't matter.
2) Add a new `fabric2_fdb:transactional(DbName|Db, TxOptions, Fun)` call which allows specifying per-transaction TX options in the `TxOptions` arg. The format of `TxOptions` is `#{option_name_as_atom => integer | binary}`
=> Allow applying per-transaction options with fabric2_fdb:transactional/3

rel/overlay/etc/default.ini, src/couch_views/src/couch_views_indexer.erl
Previously, the view indexer used the default retry limit (100) from the `fdb_tx_options` config section. However, since the batching algorithm relies on sensing errors and reacting to them, retrying the batch 100 times before erroring out was not optimal. So value is lowered down to 5 and it's also made configurable.
=> Lower the view indexer transaction retry limit

rebar.config.script
The main feature is a fix to use buggify settings on the client
(`enc` update was reverted from an intermediate release)
https://github.com/apache/couchdb-erlfdb/releases/tag/v1.2.7
https://github.com/apache/couchdb-erlfdb/releases/tag/v1.2.8
=> Bump erlfdb to v1.2.8

src/chttpd/src/chttpd_external.erl, src/chttpd/test/eunit/chttpd_external_test.erl
When function `chttpd_external:json_req_obj/2` acquiring `peer` it's always trying to read it from a socket, which doesn't work on a foreign node, because socket is unavailable there. We, however, read `peer` at request time in `chttpd:handle_request_int/1` and store it in `#httpd` record.
This change makes advantage of that and changes `chttpd_external:json_req_obj/2` to read `peer` from the stored record first and fail back to the socket reading only when it's not available there.
There was no tests for `chttpd_external` module, so I've added a new test suite `chttpd_external_test` that covers  the changes. To run an isolated run execute: `make eunit apps=chttpd suites=chttpd_external_test`
=> Use stored peer when available in json_req_obj

rebar.config.script
https://github.com/apache/couchdb-erlfdb/releases/tag/v1.3.0
=> Bump erlfdb to v1.3.0

src/chttpd/src/chttpd_db.erl, test/elixir/lib/couch.ex, test/elixir/test/changes_async_test.exs, test/elixir/test/config/skip.elixir
The `ChangesAsyncTest` tests were broken and disabled. This PR fixes and re-enables them.
`mix test --trace test/elixir/test/changes_async_test.exs`
=> Fix and re-enable ChangesAsyncTest

src/couch_jobs/test/couch_jobs_tests.erl
It turns out fabric is dependent on couch_jobs because of db expiration module.
So when couch_jobs was restarted multiple times per test case it could have
brought down fabric. However, since couch_jobs needs fabric for transactional
stuff it ended up brining couch_jobs app down as well.
To fix it:
* Switch to explicitly starting/stopping fabric and couch_jobs together
* Break apart bad_messages* tests to individually test each type of message
as app restarts in the middle of the tests kept killing fabric and
intermittently killing couch_jobs a well.
* Also make the tests look nicer by re-using ?TDEF_FE macros from
`fabric2_test`, this we can avoid the `?_test(begin... end).` pattern.
* Remove `meck:unload` since we don't really `meck` anything in the module
* Don't need to spend time …
=> Fix couch_jobs to be less flaky

test/elixir/lib/couch/db_test.ex
Since we run `elixir` tests with `-n 1` we can just use `_local`
=> Remove _membership call from set_config_raw in integration tests

config/integration.exs
All `mix test` runs were starting with
```
Cannot configure base applications: [:kernel]
These applications are already started by the time the configuration
executes and these configurations have no effect.
If you want to configure these applications for a release, you can
specify them in your vm.args file:
-kernel config_key config_value
Alternatively, if you must configure them dynamically, you can wrap
them in a conditional block in your config files:
if System.get_env("RELEASE_MODE") do
config :kernel, ...
end
and then configure your releases to reboot after configuration:
releases: [
my_app: [reboot_system_after_config: true]
]
This happened when loading config/config.exs or
one of its imports.
```
I haven't been able to find references to `Mix.Config`'s `error_logger` in `kernel` …
=> Remove error message on mix test

src/mango/test/17-multi-type-value-test.py
The last few builds ([83](https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/main/83/pipeline/) and [84](https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/main/84/pipeline/)) were failing with `AssertionError`s that I assume are due to some race. This change sets `wait_for_built_index=True` for them to hopefully avoid the issues.
=> Set wait_for_built_index=True for 17-multi-type-value-test.py

src/couch/priv/couch_js/86/help.h, src/couch/priv/couch_js/86/main.cpp, src/couch/priv/couch_js/86/util.cpp, src/couch/priv/couch_js/86/util.h, src/couch/rebar.config.script, support/build_js.escript
This is mainly in preparation for natively supporting Apple Silicon, as the build system required for SM68 is not support there.
The main bulk is copied from the SM68 implementation, this is the effective diff, plus some odds and ends in the rebar config.
h/t https://github.com/mozilla-spidermonkey/spidermonkey-embedding-examples/blob/esr78/docs/Migration%20Guide.md and the SpiderMonkey team chat https://chat.mozilla.org/#/room/#spidermonkey:mozilla.org <3
```diff
--- 68/main.cpp	2021-03-13 13:03:33.000000000 +0100
+++ 86/main.cpp	2021-03-13 13:50:54.000000000 +0100
@@ -22,17 +22,20 @@
#endif
#include <jsapi.h>
#include <js/CompilationAndEvaluation.h>
#include <js/Conversions.h>
#include <js/Initialization.h>
#include <js/SourceText.h>
+#include <js/StableStringChars.h>
#include …
```
=> Support SpiderMonkey 86

Makefile, configure, rebar.config.script, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_stats.erl, src/couch/include/couch_db.hrl, src/couch/rebar.config.script, src/couch/src/couch_httpd.erl, src/couch/src/couch_proc_manager.erl, src/couch/src/couch_query_servers.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/ddoc_cache/src/ddoc_cache_entry.erl, src/fabric/src/fabric_rpc.erl, src/fabric/src/fabric_view_all_docs.erl, src/mango/rebar.config.script, src/mango/src/mango_httpd.erl, src/mango/src/mango_util.erl, src/rexi/src/rexi_server.erl
this PR pulls together all the various sub-module changes required to support Erlang/OTP 23.
Closes https://github.com/apache/couchdb/issues/3115
This currently includes a commit from https://github.com/apache/couchdb/pull/3421 because I couldn't run this locally otherwise. The PRs can land one after another, though.
=> Support Erlang/OTP 23

src/couch_log/src/couch_log_monitor.erl
Starting with OTP 21 there is a new logging system, and we forgot to add the legacy error logger handler for it. Without it, `couch_log` cannot emit gen_server, supervisor and other such system events.
Luckily, there is OTP support to enable legacy error_logger behavior and that's what we're doing here. The `add_report_handler/1` call will auto-start the `error_logger` app if needed, and it will also add an `error_logger` handler to the global `logger` system.
We also keep the `gen_event:add_sup_handler/3` call, as that will ensure we'll find out when `error_logger` dies so that
`couch_log_monitor` can restart everything.
Someday(TM) we'll write a proper log event handler for the new logger and have nicely formatted structured logs, but it's better to do that once we don't have to support …
=> Fix error_logger reports for OTP >= 21

src/chttpd/src/chttpd_node.erl
Fix typo causing not saving of configuration changes from chttpd_node
N/A
- The bug was introduced in https://github.com/apache/couchdb/pull/3031
=> Fix typo causing not saving of configuration changes from chttpd_node

test/elixir/test/concurrent_writes_test.exs, test/elixir/test/config/suite.elixir
Add a variant of the concurrent write test that updates each document with a different value and assert that the view has the right answer.
N/A
N/A
=> Add Secondary data tests with updates test

test/elixir/test/concurrent_writes_test.exs
* `Secondary data tests with updates and queries`: This one is just like the
`Secondary data tests with updates` but adds intermettent queries while
updates are taking place.
* `Secondary data tests with deletes and queries`: This one deletes and
queries intermetently. This one was specifically crafted to trigger the
`ebtree:lookup_multi/3` error and hopefully other similar ones. The
retry_until section at the end was added to differentiate between the case
were we returna partial view and when the view is actually broken and it
will never "catch up". Once we start returning only completed views, we
remove that section.
=> Add more concurrent write tests

build-aux/Jenkinsfile.full
According to https://wiki.centos.org/FAQ/General#What_is_the_support_.27.27end_of_life.27.27_for_each_CentOS_release.3F  CentOS 6 is now discontinued. This PR removes it from the matrix.
=> Remove CentOS 6 from CI

test/elixir/test/changes_async_test.exs
CI runs on main such as https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/main/98/pipeline/ are failing with timeouts.
This PR increases that timeout.
=> Increase timeout for process response in changes async test

src/couch_replicator/test/eunit/couch_replicator_many_leaves_tests.erl
It's a CPU-intensive test and so it often times out in CI. So try to increase its timeout and also decrease the size of attachments and the number of design docs. We cannot decrease the number of leaves as that's the thing that's being
tested.
=> Make "make leaves" replication test less flaky

test/elixir/test/changes_async_test.exs
CI is still sometimes failing with a [`timeout`](https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/main/104/pipeline/#step-216-log-1751) for `continuous filtered changes` elixir test. This PR increases the timeout at hand.
=> Increase timeout for continuous filtered changes elixir test

src/couch_views/include/couch_views.hrl, src/couch_views/src/couch_views.erl, src/couch_views/src/couch_views_indexer.erl, src/couch_views/src/couch_views_jobs.erl, src/couch_views/src/couch_views_reader.erl, src/couch_views/test/couch_views_active_tasks_test.erl, src/couch_views/test/couch_views_indexer_test.erl, src/couch_views/test/couch_views_map_test.erl
View indexer saves both the GRV it used during the view update, and
the committed versionstamp in the couch_jobs job data section. Then,
the view reader uses those versionstamps to emit a consistent snapshot
of the view.
* The committed versionstamp ensures that the view results can be
emitted even if the view gets updated between the time the view
finished and the reader gets notified.
* The indexer GRV ensures that the view will emit the same doc
revisions in case when include_docs=true option is used as what it
read during the time it indexed the data.
The view reader uses those two versionstamps only if it initiates the
view build itself and then waits for it to build, to ensure that it
doesn't operate on stale GRVs.
Because the committed version is only available after the main …
=> Consistent view emits using indexer's GRVs and committed versionstamps

rel/overlay/etc/default.ini, src/couch_views/src/couch_views_batch_impl.erl
The indexer transaction time is decreased in order to allow enough time for the client to re-use the same GRV to emit doc bodies.
This PR goes along with another [PR], where emitted doc bodies in a view responses now come from the same database read version as the one used by the indexer. Since the batcher previously used 4.5 seconds as the maximum, that left little time to read any doc bodies.
[PR]: https://github.com/apache/couchdb/pull/3391
Issue: https://github.com/apache/couchdb/issues/3381
=> Decrease the view indexer transaction time

rebar.config.script, src/chttpd/src/chttpd_node.erl, src/couch_log/src/couch_log_config.erl, src/couch_log/src/couch_log_config_dyn.erl, src/couch_log/src/couch_log_formatter.erl, src/couch_log/src/couch_log_sup.erl, src/couch_log/test/eunit/couch_log_config_test.erl, src/couch_log/test/eunit/couch_log_formatter_test.erl, src/couch_replicator/src/couch_replicator_httpc_pool.erl, src/setup/src/setup.erl, src/setup/src/setup_httpd.erl
This PR started as a port of https://github.com/apache/couchdb/pull/3031 (Clean up logs) into 3.x branch. The main goal of the PR is to remove sensitive data from the logs.
However as it was pointed out by reviewers it might be not the right approach to convert shape of gen_server state for a CouchDB version which is already widely deployed. Another problem with the scope of the PR is lack of definition of sensitive data. There are multiple points of view on the sensitive data:
- user credentials
- user documents
- design documents 
This means that there is no generic solution which would fit all. In order to solve this problem for the purposes of this PR the sensitive data are defined as "user credentials". 
Before going further down with description of the solution presented in the PR. …
=> Clean up logs 3.x.v2

rebar.config.script, src/couch_jobs/src/couch_jobs.erl, src/couch_jobs/src/couch_jobs_activity_monitor.erl, src/couch_jobs/src/couch_jobs_notifier.erl, src/couch_jobs/src/couch_jobs_type_monitor.erl, src/couch_views/src/couch_views_indexer.erl, src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_test_util.erl, src/fabric/test/fabric2_tx_options_tests.erl
Improve retryable FDB error handling
After running the Elixir suite under the buggify" mode, we noticed retryable errors were not handled well. In some cases we handled some errors (1009) but not others (1007, 1031). Some other retryable errors were not considered at all.
So here we use the newly defined constants and `ERLFDB_IS_RETRYABLE/2` guard from erlfdb v1.3.1 to make handling of these errors a bit more consistent.
=> Improve retryable FDB error handling

src/chttpd/src/chttpd.erl
We've noticed that http client in some cases getting a stacktrace. This problem
can be reproduced when shard files are truncated and user try to call `/_all_docs`.
The depth of the stack trace was not sufficient to uncover that the error is
coming from
[`couch_mrview:all_docs_fold/4`](https://github.com/apache/couchdb/blob/3.x/src/couch_mrview/src/couch_mrview.erl#L383)
We've made a hypothesis that we are getting an `EXIT` whenever we call a
`gen_server` from the request process.
As a confirmation of this hypothesis there was an error logged from
[`rexi_server:init_p/3`](https://github.com/apache/couchdb/blob/3.x/src/rexi/src/rexi_server.erl#L144).
```
[error] 2021-01-28T17:06:16.357719Z node1@127.0.0.1 <0.2558.0> f674d6062d rexi_server:
from: node1@127.0.0.1(<0.2485.0>)
mfa: …
```
=> Remove stack traces on EXIT

rebar.config.script
https://github.com/apache/couchdb-erlfdb/releases/tag/v1.3.2
=> Bump erlfdb to v1.3.2

rel/overlay/etc/default.ini, src/couch_log/src/couch_log_config.erl, src/couch_log/src/couch_log_config_dyn.erl, src/couch_log/src/couch_log_formatter.erl, src/couch_log/src/couch_log_sup.erl, src/couch_log/test/eunit/couch_log_config_test.erl
Do not log by default potentially long list of messages received by terminated process. Currently we log `messages` field in the termination report. This means that we try to process whole message queue of a process before we write the log entry.
An example of a log message we are trying to reduce is as follows:
```
Jan 13 20:18:22 c-fdbcore-perf-api-546dc8d4d8-6hx5n db error [error] 2021-01-13T20:18:22.322515Z dbcore@172.30.74.10 <0.381.0> -------- CRASH REPORT Process fabric2_txids (<0.381.0>) with 0 neighbors exited with reason: {bad_info,{#Ref<0.3875778607.1050673154.132562>,ready}} at gen_server:handle_common_reply/8(line:726) <= proc_lib:init_p_do_apply/3(line:247); initial_call: {fabric2_txids,init,['Argument__1']}, ancestors: [fabric2_sup,<0.377.0>], message_queue_len: 1, …
```
=> Configurable filter fields

src/couch/priv/couch_ejson_compare/couch_ejson_compare.c
Previously, mango tests with objects as keys were failing on CentOS 6 and CentOS 7. The reason for the failures was that old libicu collation algorithms didn't consider the `<<255,255,255,255>>` as the highest sortable string as CouchDB intends it to be. Later versions of libicu, at least as old as 59, [started to do that]( https://www.unicode.org/reports/tr35/tr35-collation.html#tailored_noncharacter_weights). However, as long as we support CentOS 7 we can fix the issue by explicitly checking for the highest marker.
=> Fix collation issue for older versions of libicu library

src/couch/src/couch_db.erl, src/couch/test/exunit/fabric_test.exs, src/couch_eval/src/couch_eval.erl, src/couch_index/src/couch_index_server.erl, src/couch_js/src/couch_js.erl, src/couch_mrview/src/couch_mrview.erl, src/couch_replicator/test/eunit/couch_replicator_test_helper.erl, src/fabric/src/fabric2_db.erl, src/fabric/test/fabric2_doc_crud_tests.erl, src/mango/src/mango_eval.erl, test/elixir/lib/setup/common.ex
Change the validate ddoc check to use couch_eval.
Also add in some extra functions in couch_eval so that the try_compile
will work.
All current design doc tests should pass.
=> Validate ddoc uses couch_eval

src/chttpd/src/chttpd_sup.erl, src/couch/src/couch_sup.erl
The uri_file config parameter was not supported in the switch to chttpd. Pulling the relevant section of code in from couch_sup.erl.
Booting up couchdb with specific cluster port set and port 0.
=> Support uri_file write for chttpd

build-aux/Jenkinsfile.pr
We now host our CI containers directly under the Apache Docker Hub
org.
In addition, the newly rebuilt buster-erlang-all image has 4 Erlang
releases in it, corresponding to the latest version available in each
supported major release today:
* 20.3.8.26 (against which our 3.2 binaries will be built)
* 21.3.8.22
* 22.3.4.17
* 23.3.1
This PR changes our PR builds to run against all 4 of these versions.
=> [CI] Move to new containers, expand Erlang matrix

build-aux/Jenkinsfile.full
This is the companion PR to #3504, and moves our "full" builds to the new containers as well.
It drops CentOS 6 because we are no longer able to build these containers, now that their repositories are gone.
=> [CI] Move to new containers for full build

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
This should work around rate limiting that @bessbd and I have seen.
The creds are stored in Jenkins on https://ci-couchdb.apache.org/ . If you would like the account password, let me know.
=> Add docker creds to CI run

rebar.config.script, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_handlers.erl, src/chttpd/src/chttpd_stats.erl, src/couch/include/couch_db.hrl, src/couch/src/couch_proc_manager.erl, src/couch_js/src/couch_js_proc_manager.erl, src/couch_replicator/src/couch_replicator_job.erl, src/couch_replicator/src/couch_replicator_parse.erl, src/couch_views/src/couch_views_indexer.erl, src/couch_views/src/couch_views_updater.erl, src/ctrace/src/ctrace.erl, src/fabric/src/fabric2_db_expiration.erl, src/fabric/src/fabric2_index.erl, src/fabric/src/fabric2_util.erl, src/mango/src/mango_httpd.erl
This patch introduces a macro and inserts it everywhere we catch errors
and then generate a stacktrace.
So far the only thing that is a little bit ugly is that in two places,
I had to add a header include dependency on couch_db.erl where those
modules didn’t have any ties to couchdb/* before, alas. I’d be willing
to duplicate the macros in those modules, if we don’t want the include
dependency.
=> feat: work around get_stacktrace deprecation/removal

src/couch/include/couch_db.hrl
`OTP_RELEASE` is the one mentioned in:
https://erlang.org/doc/reference_manual/macros.html#predefined-macros
See: https://github.com/apache/couchdb/pull/3422#issuecomment-821943769
=> Swap OTP_VERSION with OTP_RELEASE macros

test/elixir/lib/step/user.ex
`fabric.get_doc_info/3` requires three arguments, but this line was only using one.
```
make elixir
```
=> Use correct args in get_doc_info

src/couch_jobs/src/couch_jobs.erl, src/couch_jobs/src/couch_jobs.hrl, src/couch_jobs/src/couch_jobs_activity_monitor.erl, src/couch_jobs/src/couch_jobs_fdb.erl, src/couch_jobs/src/couch_jobs_notifier.erl, src/couch_jobs/src/couch_jobs_server.erl, src/couch_jobs/src/couch_jobs_type_monitor.erl, src/couch_jobs/src/couch_jobs_util.erl, src/couch_jobs/test/couch_jobs_tests.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_changes_fold_tests.erl
Add AIMD-based batching to couch_jobs activity monitor and notifier
couch_jobs activity monitor is responsible for checking jobs which have not
been updated often enough by their workers and re-enqueuing them. Previously
when the number of jobs grew high enough, couch_jobs could fail to either
iterate through all the jobs and timeout with a 1007, try to re-enqueue too
many jobs such that the sum of the commit data would end up being larger than
the 10MB FDB limit.
couch_jobs notifier is in charge notifying subscribers when job state changes.
If the jobs are updated, it would notify if it noticed updates, otherwise it
would notify if job switch to a new state, update -> pending, update ->
finished, etc. Previously if there were too many jobs and/or the cluster was
overloaded it was …
=> Add batching to couch jobs

src/couch_jobs/test/couch_jobs_tests.erl
Previously we deleted the ets handle cache, then bumped the FDB metadata. That has a race condition if anything else, like `fabric2_indexing` or other `couch_jobs` users, tried to get a `jtx()` handle before the metadata bump. In that
case, they would have re-inserted a handle with a stale `md_version` and the test assertions would fail.
The fix is to first bump the md version, then delete the handles.
=> Fix flaky couch_jobs metadata test

src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_server.erl, src/fabric/test/fabric2_changes_fold_tests.erl, src/fabric/test/fabric2_db_crud_tests.erl
There are 2 commits:
1. After recent improvements to how retries are handled in `fabric2_fdb`, Elixir
integration tests can often pass when running under "buggify" mode. The chance 
of re-sending response data during retries is now much lower, too. However,
there are still some instances of that type of failure when running `_all_dbs`
tests. To trigger it would have to run the all_dbs test from basics_tests.exs a
few thousands times in a row. The reason for the failure is that retryable
errors might be still thrown during the `LayerPrefix = get_dir(Tx)` call, and
the whole transaction closure would be retried in [2]. When that happens,
user's callback is called twice with `meta` and it sends `[` twice in a row to
the client [3], which is incorrect.
A simple fix is to not call `meta` or …
=> Improve retry handling in _all_dbs, _dbs_info and _deleted_dbs

src/couch_log/src/couch_log_monitor.erl, src/couch_log/test/eunit/couch_log_config_listener_test.erl
Previously we installed two of them, one through the `error_logger:add_report_handler/1` call and another through the `gen_event:add_sup_handler/3`. The first one was to setup `logger` handler, but the second was was still needed so we're notified if event manager died.
The fix is to do what `error_logger:add_handler/1` does [1] and instead of calling the `gen_event:add_handler/3`, call `gen_server:add_sup_handler/3`.
[1] [error_logger.erl#L453-L455](https://github.com/erlang/otp/blob/40922798411c2d23ee8a99456f96d6637c62b762/lib/kernel/src/error_logger.erl#L453-L455)
=> Install only one couch log error handler

configure, rel/overlay/etc/default.ini
Couch_prometheus's additional http server should be off by default
and the port should have a default value of 17986 when running
`make release`.  The http server was mistakenly left on without a port
and that led to startup issues.
`make release` should install correctly after running `configure`.
I performed the above step and the `default.ini` in `rel/couchdb` shows:
```
[prometheus]
additional_port = false
bind_address = 127.0.0.1
port = 17986
```
=> fix default values for prometheus templates

src/chttpd/src/chttpd.erl
Improve error message when unsupported language is specified for map. Without this change the error causes 500 with unclear reason. 
1. Create database `curl -u adm:pass -X PUT -H 'Content-Type: application/json'  http://127.0.0.1:15984/test`
2. Try creating design doc with unsupported language and map function
```
curl -u adm:pass -X PUT -H 'Content-Type: application/json' -d '{"_id": "_design/python", "language": "python", "views": {"diet": {"map": ""}}}' http://127.0.0.1:15984/test/_design/python5
```
3. Make sure `#2` display following message
```
{"error":"unknown_eval_api_language","reason":"unsupported language in design doc: `python`","ref":2476823177}
```
- Follow up for https://github.com/apache/couchdb/pull/3481
=> Add clause for unknown_eval_api_language

src/couch_replicator/src/couch_replicator_auth_session.erl
When the username and password contains @, the replicator authentication will break.
This PR fixes that bug by unquoting the credentials.
make eunit apps=couch_replicator suites=couch_replicator_auth_session
This fixes #2892
=> Fix bug in replicator authentication for password contains @

src/dreyfus/src/dreyfus_index_manager.erl
This enables offheap message queue support for the `dreyfus_index_manager` process. Like the `couch_server` process, this process can become overloaded with messages which very quickly causes issues. Switching the message queue off heap helps alleviate that to some extent.
=> Add offheap MQ support for dreyfus_index_manager

src/couch/src/couch_att.erl, src/couch/test/eunit/couch_doc_json_tests.erl
Previously the default value for md5 field was `<<>>`. This value changed to
undefined when we switch to using maps instead of erlang records.
The change break the `couch_att:to_json/4` funciton because `base64:encode/1`
cannot handle atom `undefined`.
The issue happens for inline attachments only this is why it wasn't discovered
earlier.
1. run test suite
2. there is a manual way to test it as well
```
curl -u adm:pass -X PUT -H 'Content-Type: application/json' http://127.0.0.1:15984/test
curl -u adm:pass -X PUT -H 'Content-Type: application/json' -d '{"_id": "_design/ddd", "language": "javascript", "views": {"diet": {"map": ""}}, "_attachments": {"foo.txt": {"content_type": "text/plain", "data": "VGhpcyBpcyBhIGJhc2U2NCBlbmNvZGVkIHRleHQ="}}}' http://127.0.0.1:15984/test/_design/ddd
``` …
=> Handle the case when md5 field is undefined

Makefile, rel/files/buggify-eunit.config, test/elixir/test/config/buggify-test-config.ini
Add `buggify-elixir-suite` target to run Elixir integration tests under FoundationDB's client buggify mode [1]. In this mode, the FDB C client in the `erlfdb` application will periodically throw mostly retryable errors (`1009`, `1007`, etc). Transaction closures should properly handle retryable errors without side-effects such as re-sending response data to the user more than once or, attempt to re-read data from the socket after it was already read once.
In order to avoid false positives, provide a custom .ini settings file which disables transaction timeouts (`1031` errors). Those are not retryable by default, as far as the `on_error` callback is concerned. Ff we do have timeouts set ( = 60000), it signals the FoundationDB client that we expect to handle timeouts in buggify mode, so it …
=> Introduce buggify integration test mode

rebar.config.script, src/couch_replicator/src/couch_replicator_connection.erl
This is a port from main https://github.com/apache/couchdb/pull/3551
Set the `worker_trap_exits = false` setting to ensure our replication worker pool properly cleans up worker processes.
Ref: https://github.com/apache/couchdb/pull/3208
=> Bump ibrowse to 4.4.2 + couchdb patches

build-aux/Jenkinsfile.pr, rebar.config.script, src/couch/src/couch_hotp.erl, src/couch/src/couch_httpd_auth.erl, src/couch/src/couch_passwords.erl, src/couch/src/couch_util.erl, src/jwtf/src/jwtf.erl
Switching crypto functions to use the new ones such as:
```
crypto:hmac(Alg, Key, Message) -> crypto:mac(hmac, Alg, Key, Message)
```
Needed to bump dependencies:
* Bumped meck to 0.9.2. New meck from upstream supports Erlang
24. Also required bumping folsom since it depends on meck
* Example in passage module would not compile, so commented out
the parse transform. Required bumping jaeger passage since it
depends on passage
No 24 `kerl` support yet so test it with 24 locally.
=> Erlang 24 support

src/couch_eval/src/couch_eval.erl, src/couch_eval/test/couch_eval_error_tests.erl, src/couch_eval/test/error_tests.erl, src/couch_views/src/couch_views_indexer.erl, src/couch_views/test/couch_views_indexer_test.erl
When `ApiMod:acquire_map_context` returns with `{error, any()}`, the caller(s) fail with `badmatch`. This PR changes the caller hierarchy so that those `{error, _}` are propagated back and a failing `update` gets retried (up to `retry_limit` times).
I tested manually: `curl -XPUT -HContent-type:application/json -d'{"views": { "testView": { "map": "function(doc) {if(doc.name) {emit(doc.name)};}" } }, "language": "javascript"}'  http://adm:pass@127.0.0.1:15984/foo/_design/fooDD2` and `curl http://adm:pass@127.0.0.1:15984/foo/_design/fooDD2/_view/testView` and I watched as the `badmatch` log entries disappeared after the change.
=> Add error propagation to couch_eval and couch_views_indexer

test/elixir/test/config/skip.elixir
I was walking through the skipped elixir tests and I just realized the `ConfigTest` tests are passing with no change.
Fun fact, they may have already been passing for some time: https://github.com/apache/couchdb/pull/3465#pullrequestreview-622784583
=> Re-enable skipped ConfigTest elixir tests

rebar.config.script, src/couch/src/couch_hotp.erl, src/couch/src/couch_httpd_auth.erl, src/couch/src/couch_passwords.erl, src/couch/src/couch_util.erl, src/jwtf/src/jwtf.erl, test/elixir/test/proxyauth_test.exs
The main fix is to switch crypto functions to use the new versions for 22+ while keeping Erlang 20 still working:
```
crypto:hmac(Alg, Key, Message) -> crypto:mac(hmac, Alg, Key, Message)
```
=> Erlang 24 support for 3.x branch

src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_fdb_tx_retry_tests.erl
Previously, if a transaction got a `commit_unknown_result`, during the next successful attempt that result would be returned to the user. However, if the next attempt was another retryable error, then the committed result was ignored
and the whole transaction would be applied again. This could result in document update transactions conflicting with themselves as described in issue https://github.com/apache/couchdb/issues/3560
To prevent that from happening we remember that there was an `commit_unknown_result` error during the course of any previous retries and try to return that result.
=> Use the last commit result even when there are intermediate retries

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_changes.erl, src/chttpd/src/chttpd_cors.erl, src/chttpd/src/chttpd_external.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/src/chttpd_xframe_options.erl, src/chttpd/test/eunit/chttpd_util_test.erl, src/couch/src/couch_httpd.erl, src/couch/src/couch_httpd_vhost.erl, src/couch/test/eunit/couchdb_cors_tests.erl, src/couch/test/eunit/couchdb_mrview_cors_tests.erl, src/couch_replicator/test/eunit/couch_replicator_small_max_request_size_target.erl, test/elixir/test/config_test.exs, test/elixir/test/http_test.exs, test/elixir/test/jsonp_test.exs, test/elixir/test/rewrite_test.exs, test/javascript/tests/rewrite.js
Solved conflicts from "cherry-pick" 3.x commit with kdiff3 merge tool.
make eunit apps=chttpd suites=chttpd_util_test
This fixes #3472
=> Moved some config options from httpd to chttpd

test/elixir/test/config/skip.elixir, test/elixir/test/cookie_auth_test.exs
The only test in the group is passing. This PR re-enables it.
=> Re-enable more elixir tests

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_util_test.erl, src/couch/src/couch_httpd.erl, src/couch/src/couch_httpd_auth.erl, src/couch/src/couch_passwords.erl, src/fabric/src/fabric2_users_db.erl, test/elixir/test/cookie_auth_test.exs, test/elixir/test/users_db_security_test.exs, test/elixir/test/users_db_test.exs
Solved conflicts from "cherry-pick" 3.x commit with kdiff3 merge tool.
make eunit apps=chttpd suites=chttpd_util_test
This fixes #3472
=> Moved couch_httpd_auth options to chttpd_auth main

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_util_test.erl, src/couch/src/couch_httpd.erl, src/couch/src/couch_httpd_auth.erl, src/couch/src/couch_passwords.erl, src/couch/src/couch_users_db.erl, src/couch_mrview/src/couch_mrview_http.erl, src/global_changes/test/eunit/global_changes_hooks_tests.erl, test/elixir/test/cookie_auth_test.exs, test/elixir/test/users_db_security_test.exs, test/elixir/test/users_db_test.exs, test/javascript/tests/replicator_db_by_doc_id.js
Move configuration options from [couch_httpd_auth] to [chttpd_auth].
make eunit apps=chttpd suites=chttpd_util_test
This fixes #3472
=> Moved couch_httpd_auth options to chttpd_auth 3.x

src/couch/rebar.config.script
Without this flag, spidermonkey 60 fails to compile on mac OS 10.15.7 since warnings are fatal.
=> Do not warn for invalid offset with spidermonkey 60 on mac

src/chttpd/src/chttpd_show.erl
This code is generating an unused function compilation warning.
=> Delete unused chttpd_show:apply_etag/2 function

src/couch_replicator/src/couch_replicator.erl, src/couch_replicator/src/couch_replicator_auth_session.erl, src/couch_replicator/src/couch_replicator_docs.erl, src/couch_replicator/src/couch_replicator_httpc.erl, src/couch_replicator/src/couch_replicator_ids.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_utils.erl
Previously, there were two ways to pass in basic auth credentials for
endpoints -- using URL's userinfo part and encoding the them in an
`"Authorization": "basic ..."` header. Neither one is ideal for these reasons:
* Passwords in userinfo doesn't allow using ":", "@" and other characters.
However, even after switching to always unquoting them like we did recently
[1], would break authentication for usernames or passwords previously
containing "+" or "%HH" patterns, as "+" might now be decoded to a " ".
* Base64 encoded headers need an extra step to encode them. Also, quite often
these encoded headers are confused as being "encrypted" and shared in a
clear channel.
To improve this, revert the recent commit to unquote URL userinfo parts to
restore backwards compatibility, and introduce a …
=> Improve basic auth credentials handling in replicator

src/aegis/rebar.config.script, src/aegis/src/aegis.erl, src/aegis/src/aegis_server.erl, src/aegis/test/aegis_server_test.erl, src/couch_js/test/couch_js_proc_manager_tests.erl
- Add aegis eunit coverage
- Decrease likelihood of key expiring from cache while in use
- Fix test which breaks when aegis configured with operational key manager
- Add `aegis:key_manager/0` function
`make eunit apps=aegis` should pass with default `aegis_noop_key_manager` and any operational key manager you might choose.
=> Aegis improvements

rebar.config.script
This reverts the update to ibrowse to always unquote userinfo
(username and password) in endpoint URLs, as it has issues with
compatibility since it would unqoute passwords which had a literal '+'
as ' ' for example.
There is a new recommended way of specifying passwords which may
contain '@', ':' and other such symbols in
https://github.com/apache/couchdb/commit/1860ebbf2fa1731a62f3c9b107b2e52811489c1e.
Issue: https://github.com/apache/couchdb/issues/2892
=> Bump ibrowse to 4.4.2-3

rebar.config.script
It doesn't really work as we have functionality relying on 20.0+ features. One particular instance is in [1].
Issue: https://github.com/apache/couchdb/issues/3571
[1] https://github.com/apache/couchdb/blob/ce596c65d9d7f0bc5d9937bcaf6253b343015690/src/couch/src/couch_emsort.erl#L363-L366
=> Erlang 19 is not supported for 3.x

rebar.config.script
* mochiweb : upgrade crypto functions to support OTP 23+
* ibrowse : update time functions and fix flaky unit test
Backport of https://github.com/apache/couchdb/pull/3610
=> Bump ibrowse to 4.4.2-4 and mochiweb to v2.21.0

rebar.config.script
Previously, in 4.4.2-4 ibrowse upstream rebase also included the commit which
unconditionally unquoted userinfo credentials. Since we know have a better way
of handing basic auth creds bump ibrowse with a rebase which doesn't include
that commit.
=> Bump ibrowse to 4.4.2-5

.devcontainer/Dockerfile
This URL is a 404 now, but fortunately we don't care as foundationdb.org is no longer dependent on GeoTrust at all in its root of trust.
Open the project in VS Code using the Remote - Containers extension and check to see if the editor starts up successfully. Alternatively, just try to build the CouchDB layer container using the instructions in `.devcontainer/Dockerfile`
=> Remove attempt to download GeoTrust CA

src/chttpd/test/eunit/chttpd_util_test.erl
In their current form, some of these tests rely on configuration props
set with specific values in `rel/overlay/etc/default.ini`, which makes
them prone to breakage when those values change, or when tests run in
non-default configuration.
This change deletes all config settings in the relevant sections under
test, and then adds those under test back explicitly.
=> Improve robustness of chttpd_util_test

src/chttpd/src/chttpd_auth_cache.erl, src/custodian/src/custodian_db_checker.erl, src/custodian/src/custodian_util.erl
These system db defaults were left unchanged when this code was
imported from Cloudant. This changes them to CouchDB defaults.
=> Fix custodian default system dbs

rebar.config.script, rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_misc.erl, src/chttpd/src/chttpd_prefer_header.erl, src/chttpd/src/chttpd_sup.erl, src/chttpd/test/eunit/chttpd_util_test.erl, src/couch/src/couch_att.erl, src/couch/src/couch_httpd.erl, src/couch/src/couch_proc_manager.erl, src/couch/src/couch_query_servers.erl, src/couch/src/couch_uuids.erl, src/couch_eval/src/couch_eval.erl, src/couch_js/src/couch_js_proc_manager.erl, src/couch_js/src/couch_js_query_servers.erl, src/couch_prometheus/src/couch_prometheus_sup.erl, src/couch_replicator/test/eunit/couch_replicator_large_atts_tests.erl
Normalize some configuration options to comment out the default.ini file in the main branch.
This fixes #3473
=> Normalize config options main

src/couch_replicator/src/couch_replicator_docs.erl
With the move from using a forked ibrowse to upstream [1], the
ibrowse options for socks5 proxy settings all changed to a `socks5_`
prefix.
[1] https://github.com/apache/couchdb/pull/3551
```
make eunit apps=couch_replicator suites=couch_replicator_docs tests=parse_proxy_params_test
```
=> Use correct socks5 proxy ibrowse options

dev/format_check.py, dev/format_lib.py
https://github.com/apache/couchdb/pull/3568 [broke CI on main](https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/main/175/pipeline) by using current python features. 
This PR fixes that by applying a [workaround](https://stackoverflow.com/a/53209196) to make the formatter scripts compatible.
=> Fix formatter python compatibility

.gitignore
Rebar3 is now cloned after the merge of https://github.com/apache/couchdb/pull/3637/commits/dd0b666e743f6466910b278000a865bb087da451 but is not added to the `.gitignore`.
N/A
Rebar3 is now cloned after the merge of https://github.com/apache/couchdb/pull/3637/commits/dd0b666e743f6466910b278000a865bb087da451.
=> Add rebar3 to .gitignore

rel/overlay/etc/default.ini, src/chttpd/test/eunit/chttpd_socket_buffer_size_test.erl, src/couch/include/couch_db.hrl, src/couch/src/couch_att.erl, src/couch/src/couch_doc.erl, src/couch/test/eunit/couch_doc_json_tests.erl, src/couch/test/eunit/couch_doc_tests.erl, src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_server.erl, src/fabric/test/fabric2_db_misc_tests.erl, test/elixir/test/bulk_docs_test.exs
Currently the `max_document_size`, `binary_chunk_size`, `max_attachment_size`, and `max_document_id_length` parameters can exceed the [limits of FDB](https://apple.github.io/foundationdb/known-limitations.html). This PR checks these parameters against hardcoded limits to ensure that the limits of FDB are not exceeded.
Change the parameters to integers above the hardcoded limits:
- Greater than 8000000 bytes for `max_document_size`
- Greater than 96000 bytes for `binary_chunk_size`
- Greater than 8000000 bytes for `max_attachment_size`
- Greater than 512 bytes for `max_document_id_length`
Then, add log statements to ensure that the limits are not exceeded. That is, `max_document_size` should remain at 8000000 bytes or below, `binary_chunk_size` should remain at 96000 bytes or below, …
=> Fix FDB max_document_size, binary_chunk_size, max_attachment_size, and max_document_id_length checks checks

rel/overlay/etc/default.ini, test/elixir/test/bulk_docs_test.exs
Normalize config options, comment out `[couchdb]: max_document_size`.
https://github.com/apache/couchdb/pull/3636
=> Comment out [couchdb]: max_document_size

src/dreyfus/src/dreyfus_rpc.erl, src/fabric/src/fabric_rpc.erl, src/fabric/src/fabric_util.erl, src/mem3/src/mem3_rpc.erl, src/mem3/src/mem3_shards.erl, src/mem3/src/mem3_util.erl, src/mem3/test/eunit/mem3_shards_test.erl
This PR is to address the shortcomings detailed in https://github.com/apache/couchdb/issues/3631.
This exports the `mem3_utils` library for merging db creation options lists, and then ensures that anytime a shard is created it fetches the existing db configuration to do so.
This fixes the issues described in `mem3_shards.erl`, `fabric_util.erl`, and `dreyfus_rpc.erl`.
This PR does _not_ address adding partition database creations options on the 5986 interface for `couch_httpd_db.erl`.
Not sure what the best way to test this is other than running the test suite. I had originally planned on adding tests first, but constructing the test system for these tests is quite tricky to do. Maybe someone else has a nice idea on that front.
Core issue: https://github.com/apache/couchdb/issues/3631 …
=> 3631 3.x fix pq shard creation

src/chttpd/src/chttpd_db.erl
=> Fix "error":"case_clause" using latest=true and an old revision with conflicting children as rev

test/elixir/lib/step/start.ex
Fixes:
```
warning: unknown compiler variable "___MODULE__" (expected one of __MODULE__, __ENV__, __DIR__, __CALLER__, __STACKTRACE__)
src/couchdb/test/elixir/lib/step/start.ex:62: Couch.Test.Setup.Step.Start.teardown/2
```
=> Fix __MODULE__ compiler variable warning

src/chttpd/src/chttpd_db.erl
This is a port of https://github.com/apache/couchdb/pull/3424/commits/a8622f0cca40d8f2338ec24b40f14d013a0f69d4 to main
Issue #3424
=> Fix "error":"case_clause" using latest=true

src/chttpd/src/chttpd_db.erl, test/elixir/test/attachments_test.exs
Currently, a DELETE request for a non existent attachment responds with a 200 OK even if the attachment is missing. This PR changes the response code for nonexistent attachments to a 404 NOT FOUND `{"error":"not_found","reason":"Document is missing attachment"}`
```
% curl -X PUT http://localhost:15984/demo/38 -H 'Authorization: Basic YWRtOnBhc3M=' -d '{"name": "whatever"}'
{"ok":true,"id":"38","rev":"1-a0f595984a7c4cf1dafc4cf4c04081d6"}
% curl -X DELETE 'http://adm:pass@localhost:15984/demo/38/notexisting.txt?rev=1-a0f595984a7c4cf1dafc4cf4c04081d6'
{"error":"not_found","reason":"Document is missing attachment"}
```
Deleting not existing attachment responds 200 instead of 404: https://github.com/apache/couchdb/issues/2146
=> Fix response code for nonexistent attachment

src/chttpd/src/chttpd_test_util.erl, src/couch/src/couch_doc.erl, src/couch/src/test_util.erl, src/couch_eval/src/couch_eval.erl, src/couch_js/src/couch_js.erl, src/couch_replicator/test/eunit/couch_replicator_test_helper.erl, src/couch_views/test/couch_views_active_tasks_test.erl, src/couch_views/test/couch_views_cleanup_test.erl, src/couch_views/test/couch_views_custom_red_test.erl, src/couch_views/test/couch_views_error_test.erl, src/couch_views/test/couch_views_indexer_test.erl, src/couch_views/test/couch_views_info_test.erl, src/couch_views/test/couch_views_map_test.erl, src/couch_views/test/couch_views_red_test.erl, src/couch_views/test/couch_views_server_test.erl, src/couch_views/test/couch_views_size_test.erl, src/couch_views/test/couch_views_trace_index_test.erl, src/couch_views/test/couch_views_updater_test.erl, src/couch_views/test/couch_views_upgrade_test.erl, src/fabric/test/fabric2_doc_crud_tests.erl
With Couchdb on fdb, we want all javascript and language specific functionality to run through `couch_eval`. 
This moves the `validate_doc_update` check to run through `couch_eval` instead of going directly through `couch_query_servers`. 
All existing tests should pass. 
https://github.com/cloudant-labs/ateles/pull/29
=> Run the validate doc update function through couch_eval

src/chttpd/src/chttpd_db.erl, test/elixir/test/attachments_test.exs
This is a fixup for pr https://github.com/apache/couchdb/pull/3685
(Using a separate PR as can't push to contributor's private fork)
Which fixed a bug introduced in https://github.com/apache/couchdb/pull/3673
The behavior we are trying to preserve is:
```
DELETE with a bad rev or without a rev of an existing doc and attachment should return a 409
DELETE with a non-existent attachment name should return a 404
```
The get_attachment handler was shifted to the left an indentation level, so make it easier to view the diff, switch to "Hide whitespace changes" in the diff option.
make && make elixir tests=test/elixir/test/attachments_test.exs
=> Fix response code for existing att and wrong rev

src/chttpd/src/chttpd_db.erl, test/elixir/test/attachments_test.exs
Port ba638783b5d87b855939dae69fd63ffd41cb5ed7 from 3.x
This should fix the edge case where deletion with a bad rev was returning a
404. Now it should return a 409.
Issue: https://github.com/apache/couchdb/issues/2146
make && make elixir tests=test/elixir/test/attachments_test.exs:102
=> Port attachment deletion fix from 3.x

rebar.config.script, rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_cors_test.erl, src/couch/src/couch_httpd.erl, test/elixir/test/basics_test.exs
Currently CouchDB encodes '+' into ' ' in non-query parts of URLs. This is against CouchDB standards. See the original issue [here](https://issues.apache.org/jira/browse/COUCHDB-883).
Note: This is an opt-in policy for 3.x.
Since changing the way that '+' is encoded is a breaking change, there is a backward incompatibility issue with 3.x. For example, prior to this change if a user had created a document named `my doc`, they would have used an HTTP request similar to `% curl -X PUT http://localhost:15984/mydb/my+doc -H"Authorization: Basic YWRtOnBhc3M="` and the `my+doc` would have been encoded into `my doc`. However, with this change, `my+doc` would be encoded into `my+doc`.
A test case has been added to test creating a document whose id contains a '+' with `encode_plus = true` and …
=> Improve handling of + in urls 3.x

src/couch_index/src/couch_index.erl
The function `couch_index:handle_info(maybe_close, ...) ->` was triggering an `erlang:send_after` call to the registered process `self` rather than the process `self()` corresponding to the relevant index process.
=> Ensure maybe_close message is sent to correct process

src/chttpd/src/chttpd_changes.erl, src/couch/src/couch_query_servers.erl, src/couch_eval/src/couch_eval.erl, src/couch_js/src/couch_js.erl, src/mango/src/mango_eval.erl, test/elixir/test/changes_test.exs
Use couch_eval when filtering docs with a filter function or a map
function. This allows CouchDB to configured to use different engines
through couch_eval.
All existing tests should pass
=> Use couch_eval for changes filtering

Makefile
They used to be disabled before the last major ibrowse upgrade.
On MacOS and FreeBSD the following tests fails periodically:
```
ibrowse_tests: running_server_fixture_test_ (Pipeline too small signals retries)...*failed*
in function ibrowse_tests:'-small_pipeline/0-fun-5-'/1 (test/ibrowse_tests.erl, line 150)
in call from ibrowse_tests:small_pipeline/0 (test/ibrowse_tests.erl, line 150)
**error:{assertEqual,[{module,ibrowse_tests},
{line,150},
{expression,"Counts"},
{expected,"\n\n\n\n\n\n\n\n\n\n"},
{value,"\t\n\n\n\n\t\t\n\n\t"}]}
output:<<"Load Balancer Pid     : <0.494.0>
```
But seems to pass more reliable on Linux for some reason. It would be nice to run the tests of course but having a passing full platform suite is more important.
=> Disable running ibrowse tests

src/smoosh/operator_guide.md
The smoosh `operator_guide.md` has been updated to use rpc:multicall in the examples. The previous examples used a library not included in CouchDB for some of the rpc commands.
=> Smoosh update operator guide to use rpc:multicall

rel/files/couchdb.in
Rebar mustache templating engine has a bug when handling the `}}}` brackets in a case like `{...{{var}}}`. So we work around the issue by using a separate variable.
This is an alternate fix for issue: https://github.com/apache/couchdb/pull/3617
=> Fix fauxton_root templating in bin/couchdb script

src/couch_eval/src/couch_eval.erl
Fixes this warning:
```
couchdb/src/couch_eval/src/couch_eval.erl:168: Warning: this clause cannot match because a previous clause at line 167 always matches
```
```
make eunit apps=couch_eval
```
=> Fix 'clause cannot match' compiler warning

src/couch_views/test/couch_views_indexer_test.erl
Increase timeout for multiple ddoc indexer test to help prevent:
```
couch_views_indexer_test:48: indexer_test_ (multiple_design_docs)...*timed out*
```
=> Increase timeout for multiple ddoc indexer test

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_external.erl, src/chttpd/src/chttpd_misc.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_csp_tests.erl, src/chttpd/test/eunit/chttpd_db_test.erl, src/couch_mrview/src/couch_mrview_show.erl
This introduces CSP settings for attachments and show/list funs and
streamlines the configuration with the existing Fauxton CSP options.
Deprecates the old `[csp] enable` and `[csp] header_value` config
options, but they are honoured going forward.
They are replaced with `[csp] utils_enable` and `[csp] utils_header_value`
respectively. The funcitonality and default values remain the same.
In addition, these new config options are added, along with their
default values:
```
[csp]
attachments_enable = true
attachments_header_value = sandbox
showlist_enable = true
showlist_header_value = sandbox
```
These add `Content-Security-Policy` headers to all attachment requests
and to all non-JSON show and all list function responses.
Co-authored-by: Nick Vatamaniuc <vatamane@gmail.com> …
=> feat: add more fine-grained CSP support

rel/overlay/etc/default.ini, src/fabric/src/fabric_util.erl
Previously, users with low {Q, N} dbs often got the `"No DB shards could be opened."` error when the cluster is overloaded. The hard-coded 100 msec timeout was too low to open the few available shards and the whole request would crash with a 500 error.
Attempt to calculate an optimal timeout value based on the number of shards and the max fabric request timeout limit.
The sequence of doubling (by default) timeouts forms a geometric progression. Use the well known closed form formula for the sum [0], and the maximum request timeout, to calculate the initial timeout. The test case illustrates a few examples with some default Q and N values.
Because we don't want the timeout value to be too low, since it takes time to open shards, and we don't want to quickly cycle through a few initial …
=> Improve fabric_util get_db timeout logic

src/couch_views/src/couch_views_batch_impl.erl, src/couch_views/test/couch_views_active_tasks_test.erl
Several couch_views eunit tests are prone to timeouts when run on resource constrained build systems. This improves the robustness of those tests by either increasing the timeout, in the case of active tasks tests, or by separating the monolithic "bad config" test into several smaller tests.
```
make eunit apps=couch_views
```
=> Improve views tests

src/couch/src/couch_db_split.erl, src/mem3/test/eunit/mem3_reshard_test.erl
Previously, if the source db purge sequence > `purge_infos_limit`, shard splitting would crash with the `{{invalid_start_purge_seq,0}, [{couch_bt_engine,fold_purge_infos,5...` error. That was because purge sequences were always copied starting from 0. That would only work as long as the total number of purges stayed below the purge_infos_limit threshold. In order to correctly gather the purge sequences, the start sequence must be based off of the actual oldest sequence currently available.
An example of how it should be done is in the `mem_rpc` module, when [loading purge infos](https://github.com/apache/couchdb/blob/4ea9f1ea1a2078162d0e281948b56469228af3f7/src/mem3/src/mem3_rpc.erl#L206-L207), so here we do exactly the same. The `MinSeq - 1` logic is also evident by inspecting the …
=> Fix splitting shards with large purge sequences

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_external.erl, src/chttpd/src/chttpd_misc.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_csp_tests.erl, src/chttpd/test/eunit/chttpd_db_test.erl, src/couch_mrview/src/couch_mrview_show.erl
The original [commit](https://github.com/apache/couchdb/commit/64281c0358e206a54e3b1386a7bc3b3e7c30547f) was in the 3.x branch
This introduces CSP settings for attachments and show/list funs and
streamlines the configuration with the existing Fauxton CSP options.
Deprecates the old `[csp] enable` and `[csp] header_value` config
options, but they are honoured going forward.
They are replaced with `[csp] utils_enable` and `[csp] utils_header_value`
respectively. The functionality and default values remain the same.
In addition, these new config options are added, along with their
default values:
```
[csp]
attachments_enable = false
attachments_header_value = sandbox
showlist_enable = false
showlist_header_value = sandbox
```
When enabled, these add `Content-Security-Policy` headers to all …
=> feat: backport fine-grained CSP support to 3.1.x

src/fabric/src/fabric_view_map.erl
Previously, as soon as one row returned, we immediately stopped, erroneously
assuming that meta for all ranges have already been received. However, it was
possible that we'd get meta from range `00-7f`, then a row from `00-7f` before
getting meta from `7f-ff` and thus we'd return an empty result.
To fix the issue we simply re-use the already existing limit=0 clause from the
[fabric_view:maybe_send_row/1](https://github.com/apache/couchdb/blob/9f081914fe1fd7f31c2c1c7b3ead89427cf342f3/src/fabric/src/fabric_view.erl#L124-L134) function which will wait until there is a complete
ring before returning. That relies on updating the counters (the ring) only
with meta return and not with view rows, so if the ring is complete, we know we
only completed with meta.
The other issue with limit=0 clause …
=> Fix meta result for views when limit = 0

src/fabric/src/fabric_view_map.erl
Restrict the limit=0 clause to the sorted=false case as originally intended
The limit=0 clause was introduced in commit 4e0c97bf which added
sorted=false support. It accidentally matches when the user specifies
limit=0 and causes us not to apply the logic that ensures we collect a
{meta, Meta} message from each shard range and then send the
total_rows and offset fields.
repro steps described in https://github.com/apache/couchdb/issues/3750
https://github.com/apache/couchdb/issues/3750
=> Fix limit0 for views again

test/elixir/lib/suite.ex
The state management logic in ensure_exunit_started is incorrect. It doesn't store the fact that exunit is already started.
```
make elixir-suite
```
The problem was introduced in https://github.com/apache/couchdb/pull/3286
=> Fix logic in ensure_exunit_started

Makefile, Makefile.win, config/integration.exs, dev/run, mix.exs, test/elixir/lib/suite.ex, test/elixir/test/config/skip.elixir, test/elixir/test/config/suite.elixir, test/elixir/test/test_helper.exs
The main purpose of this PR is to port https://github.com/apache/couchdb/pull/3286 to 3.x. Which adds ability to run elixir suite against already running instance of CouchDB. However due to various changes to underlying build infrastructure few other commits and PRs were added into the mix.
- https://github.com/apache/couchdb/pull/3286
- https://github.com/apache/couchdb/pull/3415
- Extract support for `--erlang-config` flag from https://github.com/apache/couchdb/commit/fff07ba136cfa7433647e974355068b43e63199c 
There were couple of fixups to make test suite pass
- 3.x uses `Code.require_file` to inject `partition_helpers.exs` and `reshard_helpers.exs`. The original implementation of `Couch.Test.Suite` in [#3286](https://github.com/apache/couchdb/pull/3286) didn't support test helpers. 
- …
=> Port 3286 - Add ability to control which Elixir integration tests to run

src/fabric/src/fabric_view.erl, src/fabric/src/fabric_view_map.erl
We do that by matching the comparator function behavior used during row [merging](https://github.com/apache/couchdb/blob/3.x/src/fabric/src/fabric_view_map.erl#L244-L248) with the comparison function used when sorting the rows on view [shards](https://github.com/apache/couchdb/blob/3.x/src/couch_mrview/src/couch_mrview_util.erl#L1103-L1107). This goes along with the constraint in the `lists:merge/3` docs which indicates that the input lists should be sorted according to the same [comparator](https://erlang.org/doc/man/lists.html#merge-3) as the one passed to the `lists:merge/3` call.
The stability of returned rows results from the case when both keys match as equal. Now `lists:merge/3` will favor the element in the existing rows list instead of always …
=> Make view merge row aggregation in fabric stable

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_changes.erl
Restores the ability for a couchdb administrator to set an upper limit to the duration of a continuous changes feed originally introduced in https://github.com/apache/couchdb/commit/c6ad114ec797874a7eccf741fecb7139b117948b but lost in the FDB work.
Set up a continuous changes feed with a heartbeat, observe that it does not terminate naturally. Set the [fabric] changes_duration parameter to some positive integer value and retest. The changes feed should not return any new updates after that duration and the response will _end_ when the database is next updated (but will not return that update in the response).
=> support maximum changes_duration configuration option

src/chttpd/test/eunit/chttpd_db_test.erl
Remove redundant CSP tests, and cleanup unused variables, extra whitespace.
```
make eunit apps=chttpd
```
=> Remove redundant CSP tests

src/couch/rebar.config.script
Patch fixes couch_js + SM78 compilation on FreeBSD 13.0-RELEASE amd64.
during 3.2.0-rc.1 testing, with FreeBSD SpiderMonkey 78 (which will be only supported SpiderMonkey after the Great Python 2 Deprecation at end of September), following error occurs:
```
Compiled src/couch_changes.erl
Compiling /tmp/couch/3.2.0/rc.1/apache-couchdb-3.2.0/src/couch/priv/couch_js/86/main.cpp
In file included from /tmp/couch/3.2.0/rc.1/apache-couchdb-3.2.0/src/couch/priv/couch_js/86/main.cpp:24:
In file included from /usr/local/include/mozjs-78/jsapi.h:31:
In file included from /usr/local/include/mozjs-78/js/CallArgs.h:74:
/usr/local/include/mozjs-78/js/Value.h:164:55: warning: bitwise operation between different enumeration types ('JSValueTag' and 'JSValueType') is deprecated …
```
=> align spidermonkey cflags across couch_js settings

rebar.config.script
Based off of the upstream 1.0.9 + CouchDB clone changes
https://github.com/apache/couchdb-jiffy/releases/tag/CouchDB-1.0.9-1
=> Bump jiffy to CouchDB-1.0.9-1

Makefile.win
Missed file in f85cff669f20cee0a54da7bb8c645dfc4d2de5c9
12:29 <+vatamane> Wohali: +1 to merge the fix to 3.x for windows
=> Fix Windows makefile for Fauxton

rel/overlay/etc/local.ini
The appropriately named `hack_local_ini` function in dev/run lives up
to its name by adding a random `secret` to the end of whichever
section contains the line `"; require_valid_user = false\n"`.
[Recent commits](https://github.com/apache/couchdb/pull/3808) updated the `setup` application from
`couch_httpd_auth` to `chttpd_auth` without also changing this line
in local.ini, which had the fun effect of causing `setup` to fail with
this error:
```
[error] 2021-10-30T18:50:15.019274Z node1@127.0.0.1 <0.817.0> 85d0421b9c setup sync_admin results [{badrpc,{'EXIT',{function_clause,[{config,set,["chttpd_auth","secret",undefined,true,nil],[{file,"src/config.erl"},{line,189}]},{rpc,'-handle_call_call/6-fun-0-',5,[{file,"rpc.erl"},{line,197}]}]}}},{badrpc,{'EXIT',{function_clause,[{config,set,["chtt …
```
=> fix(local.ini): straggling s/couch_httpd_auth/chttpd_auth/

src/fabric/src/fabric_view.erl
Previously, view reduce collation with keys relied on the keys in the rows returned from the view shards to exactly match (=:=) the keys specified in the args. However, in the case when there are multiple rows which compare equal with the unicode collator, that may not always be the case.
In that case when the rows are fetched from the row dict by key, they should be matched using the same collation algorithm as the one used on the view shards.
=> Fix reduce view row collation with unicode equivalent keys

build-aux/Jenkinsfile.full
Should fix:
```
Warning: A secret was passed to "mail" using Groovy String interpolation, which is insecure.
```
=> Fix Jenkins email quoting failures

src/couch/priv/couch_ejson_compare/couch_ejson_compare.c
Add `static` modifiers to some of the newer functions.
Fix function protype for get_collator to be `void`. This squashes this warning on MS compiler:
```
'get_collator': no function prototype given: converting '()' to '(void)'
```
=> Cleanup couch_ejson_compare C module

src/couch/src/couch_httpd_auth.erl
DELETE /_session does not work if the SameSite attribute is enabled when using browsers that enforce it because we forgot to add the property when deleting the cookie. This PR adds the SameSite attribute if enabled.
Enable SameSite, login via the dashboard, then log out. Observe that the AuthSession cookie has a value before log out but not after.
=> Add SameSite setting when clearing session cookie

src/chttpd/src/chttpd_misc.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_db_test.erl, src/chttpd/test/eunit/chttpd_dbs_info_test.erl
Add `GET _dbs_info` API
It can accept `startkey/endkey/limit/skip` query string parameters as support for the existing `GET _all_dbs` API endpoint.
make eunit apps=chttpd suites=chttpd_dbs_info_test
Docs: https://github.com/apache/couchdb-documentation/pull/699
=> add GET _dbs_info

rel/overlay/etc/vm.args, src/couch_dist/src/couch_dist.erl
* Fix quoting so that it works with all OTP versions 20 through 24 [1].
* Dist API in 20 [2] did not have a `listen/2` [3] callback. Implement
`listen/1` so we're compatible with all the supported OTP versions.
[1] https://github.com/apache/couchdb/issues/3821#issuecomment-985089867
[2] https://github.com/erlang/otp/blob/maint-20/lib/kernel/src/inet_tcp_dist.erl#L71-L72
[3] https://github.com/erlang/otp/blob/master/lib/kernel/src/inet_tcp_dist.erl#L79-L80
* Follow the nice instructions by @jiahuili430 [here](https://github.com/apache/couchdb/issues/3821#issuecomment-985089867). Try with Erlang 20 and then 23, for example.
My setup with 20 looked like:
vm.args:
```
-proto_dist couch
-couch_dist no_tls '"clouseau@127.0.0.1"'
-couch_dist no_tls '"node1@127.0.0.1"'
-ssl_dist_optfile …
```
=> Fix TLS custom (couch) dist for Erlang 20

.github/workflows/ubuntu.yml
Setup Ubuntu manual CI to accept variables for fdb and mozjs packages; downgrade fdb and upgrade mozjs.
The CI can be triggered manually in actions on a clone of this branch.
There have been recurrent issues fetching fdb 6.3.22 that will probably resolve soon, but the need to raise these versions will come up regularly,
=> Ubuntu CI: wget pull cleanup and downgrade fdb to workaround a cdn problem

src/couch/src/couch_httpd_auth.erl
Send all the cookie attributes whenever we send a cookie. Only the value of AuthSession varies.
Configure the same-site and/or domain attribute in the nodes config.
1) Acquire a session cookie successfully then log out. Confirm AuthSession is the empty string.
2) Acquire a session cookie successfully then attempt to acquire a session cookie with the wrong password. Confirm AuthSession is the empty string.
=> Always send all cookie attributes

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr, src/chttpd/src/chttpd_misc.erl, src/chttpd/test/eunit/chttpd_dbs_info_test.erl, src/couch/test/eunit/couchdb_vhosts_tests.erl, src/couch_replicator/test/eunit/couch_replicator_filtered_tests.erl, src/couch_replicator/test/eunit/couch_replicator_retain_stats_between_job_runs.erl
Previously, we ran it in the dist building stage. However, unlike in main, in 3.x that stage is run with Erlang 20 where erlfmt check is skipped. To fix that we run erlfmt in a separate stage with Erlang 23.
The second commit re-runs erlfmt and fixes a few  more files which slipped through the cracks one set of files is from a recent PR, the others are some test modules which had been skipped during the initial reformatting.
This is the output and failure without the second commit to prove that erlfmt-check would fail:
```
[2021-12-13T05:01:59.058Z] + make erlfmt-check
[2021-12-13T05:01:59.058Z] ERLFMT_PATH=/home/****/workspace/****-cm1_PullRequests_PR-3872/bin/erlfmt python3 dev/format_check.py
[2021-12-13T05:02:15.195Z]   > Checking formatting...
[2021-12-13T05:02:15.195Z]   > …
```
=> Run erlfmt-check in a separate stage

src/chttpd/src/chttpd_node.erl, src/couch/src/couch_secondary_sup.erl, src/couch_index/src/couch_index.app.src, src/couch_index/src/couch_index_server.erl, src/couch_index/test/eunit/couch_index_ddoc_updated_tests.erl, src/couch_mrview/test/eunit/couch_mrview_ddoc_updated_tests.erl
We added sharding to `couch_server` in #3366. This PR applies a similar enhancement to `couch_index_server`. 
A fake `index_server` appears in `_system` output with the aggregated message queue length of all the new `index_server_*` processes.
erlfmt also reformatted some unrelated parts of a test module that I changed, presumably someone forgot to run it in a previous PR...
Run the test suite, etc. The change should be invisible except that couchdb should handle load better.
#3366.
=> Sharded couch index server

Makefile, Makefile.win, rebar.config.script
Since Erlang 19.0 there is an [ERL_COMPILER_OPTIONS](https://www.erlang.org/doc/man/compile.html#env_compiler_options-0) environment variable which the compiler will consult.
Run `make clean && ERL_COMPILER_OPTIONS='[no_line_info,deterministic,no_debug_info]' make`.
Capture module-info from some module (something like `couch_db:module_info(compile).` perhaps). Then, run `make clean && make` and see if the changes took effect. With `no_debug_info` there should be almost no extra info shown.
Remove ERL_OPTS handling from rebar.config* scripts: https://github.com/apache/couchdb/issues/3841
=> Remove ERL_OPTS

configure, src/couch/src/couch_db.erl
Previously, when a database shard is moved to a new node, and there are no subsequent updates, the changes feed sequence rewound to the previous epoch. In case of a first shard move, it would rewind to 0.
To fix the issue, update `owner_of/2` and `start_seq/3` functions to account for the case when epoch sequence can exactly match the current db update sequence.
Fixes #3885
=> Fix changes feed rewinds after a shard move with no subsequent db updates

.github/workflows/ubuntu.yml, Makefile.win, configure, src/couch/priv/couch_js/86/main.cpp, src/couch/rebar.config.script
Changes to couchdb4 with spidermonkey 91 to function on windows and hopefully linux/arm64 (I do not yet have a build of a recent enough fdb in my distribution to test on arm).
For Windows it is necessary to install foundationdb and then edit the \bin\couchdb.cmd to add foundationdb's bin folder, then fauxton verify should pass.
[Reference binaries](https://github.com/lostnet/couchdb-glazier/releases/tag/msdeps7)
#3883 #3149
=> Feat/support sm91 4.x from lostnet

build-aux/Jenkinsfile.pr
Just bumping the patch releases we use to test PRs against, and adding Erlang 24 to the mix.
Jenkins
=> Update Jenkins Erlang versions, add 24

build-aux/Jenkinsfile.pr, mix.exs
This PR switches away from using a single container image with multiple Erlang versions installed via kerl and instead uses specific images for each version of Erlang against which we want to test a PR.
It also relies on tags like '20', '21' ... '24' instead of specific Erlang versions, so we can push updated images with new patch releases without needing to also file a PR to modify the Jenkinsfile configuration. The "Update Docker Containers" Jenkins job may need a small tweak to ensure that we can pick up the updated images behind those tags.
The matrix we are testing PRs against after this change looks like
| Erlang | OS | Elixir | JS |
|-------|-------|-----| ------ |
| 20.3.8.26 | Debian 10 (Buster) | v1.9.4 | 60 |
| 21.3.8.24 | Debian 11 (Bullseye) | v1.11.4 | 78 |
| 22.3.4.24 | …
=> Use Debian Stable, add Erlang 24 to CI

build-aux/Jenkinsfile.full
Remove Ubuntu Xenial from the CI matrix as discussed on the ML.
=> Remove CI support for Ubuntu 16.04

src/chttpd/src/chttpd_db.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/fabric/src/fabric_db_info.erl, src/mem3/src/mem3.erl
Set instance_start_time to the creation time of the database to
restore the ability for the replicator to detect a db recreation event
during a replication. Without this, a replication can fail to notice
the db was deleted and recreated, write the checkpoint document for
the in-progress replication and keep going, whereas what should happen
is the replication should reset from sequence 0.
Resolves https://github.com/apache/couchdb/issues/3897
=> Non-zero instance start time

build-aux/Jenkinsfile.pr, mix.exs, src/chttpd/test/exunit/pagination_test.exs
This PR has a small improvement to the Elixir test suite, and adds the `credo` style check earlier in the pipeline. It also reconfigures the per-stage timeouts so that they ignore time spent in the build queue waiting for a docker-based agent to free up.
Finally, it refactors the pipeline to use a larger number of explicit steps in each stage. This improves the developer experience navigating the Jenkins UI, as we can see timings for each phase of the build, and if a step fails the logs that are displayed will be scoped just to that step.
Jenkins
#3895 was the first PR to convert the Jenkinsfile to use specific images for each Erlang version.
=> Improve CI pipeline for PRs

build-aux/Jenkinsfile.full, build-aux/README.md
This is one of those situations where you go in to make a small change, see an opportunity for some refactoring, and get sucked into a rabbit hole that leaves you wondering if you have any idea how computers actually work. My initial goal was simply to update the Erlang version used in our binary packages to a modern supported release. Along the way I decided I wanted to figure out how to eliminate all the copypasta we generate for making any change to this file, and after a few days of hacking here we are. This rewrite has the following features:
* Updates to use Debian 11 (current stable) as the base image for building releases and packaging repos.
* Defaults to Erlang 24.2 as the embedded Erlang version in packages.
* Dynamically generates the parallel build stages used to test and …
=> Refactor Jenkins build to dynamically generate test stages

Makefile
Add `make exunit` target to `make check` so exunit tests will  run in CI.
```
make check
```
=> Enable exunit in check target

test/elixir/test/attachments_test.exs, test/elixir/test/design_docs_test.exs
This is a back port of @kocolosk's work on main:
The code that generates suite.elixir will repreatedly strip the "test "
from the name of the test when writing the file, resulting in a mismatch
between the actual test name and what's in suite.elixir. You can see
this by searching for e.g. COUCHDB-497 in the suite file.
I tried using String.replace_prefix instead of String.replace_leading in
test_name() but that function seems to get called multiple times during
the test grouping. Simpler to just avoid naming the tests that way for
now.
https://github.com/apache/couchdb/commit/e91779cbf122f5a822c884d89c1c55a44a548ee4
=> Back port: Do not start test name with "test "

src/fabric/src/fabric_doc_update.erl
The previous response order of
```
{accepted, [{Doc1, {accepted, Doc2}}, {Doc2, {accepted, Doc1}}
```
looked a bit odd so update the order to look as expected.
=> Fix doc order in fabric_doc_update tests

src/couch/src/couch_server.erl, src/couch/src/test_util.erl, src/fabric/test/eunit/fabric_rpc_tests.erl
The `fabric_rpc_tests` pollutes the state of `shards_db` which causes flakiness
of other tests. This PR fixes the problem by configuring temporary `database_dir`.
The important implementation detail is that we need to wait for all `couch_server`
processes to restart. Before initroduction of sharded couch server in the
https://github.com/apache/couchdb/pull/3366 this could be done as:
```erlang
test_util:with_process_restart(couch_server, fun() ->
config:set("couchdb", "database_dir", NewDatabaseDir)
end),
```
This method has to be updated to support sharded `couch_server`. Following auxiliary
functions where added:
- `couch_server:names/0` - returns list of registered names of each
`couch_server` process
- `test_util:with_processes_restart/{2,4}` - waits all process to be restarted …
=> Execute fabric_rpc_tests in clean database_dir

src/chttpd/test/eunit/chttpd_dbs_info_test.erl
Since GET `_dbs_info` will return all dbs info, it's a bit fragile. If there is any
garbage database created by other tests, then it will fail.
Added two methods to avoid test instability:
- Configure a temporary `database_dir` to avoid CI test failure
- Add a filtering function`filter_dbs/2` to avoid local test failure
`make eunit apps=chttpd suites=chttpd_dbs_info_test`
https://github.com/apache/couchdb/pull/3832
https://github.com/apache/couchdb/pull/3921
=> Execute chttpd_dbs_info_tests in clean database_dir

build-aux/Jenkinsfile.full
Som miscellaneous fixes with the ultimate goal of ensuring that Debian 11 packages get published to http://repo-nightly.couchdb.org.
apache/couchdb-pkg#89 is required as well.
=> Fix publication of nightly packages

src/fabric/src/fabric_doc_update.erl
In a rare, unsupported scenario, a user can call _bulk_docs with
`new_edits:false` and a VDU that denies the update of certain documents.
When nodes are out of sync (under load and mem3_repl can't keep up),
an update may or may not update the revision tree.
When two nodes extend the revision tree and forbids the update,
but one node is behind, an `{error, W, [{Doc, FirstReply} | Acc]}`
is returned instead of `{ok, _}` or `{accepted, _}`. The _bulk_docs
request does not accept {error, _} which leads to a function_clause.
This fix changes the return value to:
`{accepted, W, [{Doc, {forbidden, Msg}} | Acc]}`
when any of the nodes forbids the update.
Updating one document is also addressed so if the same issue occurs
during one document update, a 403 is still returned.
This should not affect …
=> Fix new_edits:false and VDU function_clause

src/dreyfus/src/dreyfus_fabric_info.erl, src/dreyfus/src/dreyfus_rpc.erl
Include the index signature in _search_info output (to match _info for views)
N/A
N/A
=> Include index sig in _search_info response

src/mem3/src/mem3_rep.erl
`replicated_edits` should be `replicated_changes`
=> Fix replicated_changes typo for purge doc updates

src/couch/src/couch_debug.erl, src/couch_index/src/couch_index_debug.erl, src/couch_index/src/couch_index_server.erl
Recent refactor of `couch_index_server` made it a sharded implementation. This means multiple processes are in play now. This made it somewhat harder to bounce in production in case of problems. Also the `couch_debug:print_linked_processes(couch_index_server)` had an assumption that `couch_index_server` is a single process.
This PR does two very related things 
1. fixes `couch_debug:print_linked_processes(couch_index_server)`
2. adds `couch_index_debug` module with auxiliary functions to restart `couch_index_server` processes safely. 
1. compile, start, remsh
2. `couch_debug:print_linked_processes(couch_index_server).`
```
|name                                              | reductions | message_queue_len |    memory    |id
|--------------------------------------------------|------------|- …
```
=> Debug for sharded index server

src/couch_replicator/src/couch_replicator_scheduler_job.erl
`ibrowse` responses may crash the job process with a function clause in `handle_info/2`. Ignore those with a note that aliases should hopefully fix this issue in the future.
=> Fix function clause in couch_replicator_scheduler_job

rel/overlay/etc/default.ini, src/couch/src/couch_httpd_multipart.erl
The code that forwards attachment data to cluster nodes via fabric has a
hard-coded timeout of five minutes for nodes to request the data. Making
this configurable lets us mitigate the impact of issue #3939, which
causes requests to block if one of the nodes already has the given
attachment and doesn't end up requesting the data for it.
- https://github.com/apache/couchdb/issues/3939
- https://github.com/apache/couchdb/pull/3940
=> Make the timeout for receiving requests from attachment writers configurable

Makefile.win, configure, configure.ps1, src/couch/priv/couch_js/86/main.cpp, src/couch/rebar.config.script
Supporting changes necessary to build/test spidermonkey 91esr on windows and linux/arm64 for the 3.x.
- Linux/AMD_64: normal CI Tests
- Windows I am using the following:
https://github.com/lostnet/couchdb-glazier/blob/main/.github/workflows/ci.yml
- Linux/Arm64: I previously [tested 68/78](https://github.com/lostnet/couchdb-nix-debug) and yocto seems to be using 60, hopefully with arm specific patches.
- #3873
- #3149
- Passing the fopen'ed JS file to mozjs was fragile due to [MS Boundaries](https://docs.microsoft.com/en-us/cpp/c-runtime-library/potential-errors-passing-crt-objects-across-dll-boundaries?view=msvc-170). I have moved JS::CompileUtf8File to JS::CompileUtf8Path which implements the logic within mozjs, but will result in lumping failures to fopen with other compile errors that …
=> Feat/support sm91 3.x from lostnet

src/couch/src/couch_key_tree.erl
sets to due to a compiler bug in 22 consumes too much memory and is slower on Erlang 22+
Reproducer: https://gist.github.com/nickva/ddc499e6e05678faf20d344c6e11daaa
With sets:
```
couch_key_tree:gen_and_stem().
{8,6848.812683105469}
```
With maps:
```
couch_key_tree:gen_and_stem().
{0,544.000732421875}
```
=> Opimtize key tree stemming by using maps instead of sets

src/smoosh/test/smoosh_tests.erl
Remove `-include` so that downstream integrations will continue to work and the internal header file remains internal.
`make eunit apps=smoosh`
Prefer `include_lib` for downstream integration: https://github.com/apache/couchdb/pull/3965
=> Remove include couch_db_int

src/couch/test/eunit/couch_key_tree_tests.erl
`couch_key_tree:stem/2`, as seen in https://github.com/apache/couchdb/pull/3963, has a potential to consume quite a bit of memory. Replacing sets with maps helped in that case, however since stemming has a non-tail recursive section, there is a chance in future versions of Erlang to experience the same behavior again.
As a safeguard, add a memory limit test by stemming a larger conflicted rev tree while limiting the maximum process heap size. For that, use the nifty `max_heap_size` process flag, which ensures a process is killed if it starts using too much memory.
To reduce the flakiness, use a deterministic tree shape by using a hard-coded seed value and leave a decent margin of error for the memory limit.
Ref: https://github.com/apache/couchdb/pull/3963
=> Add test to ensure rev tree stemming doesn't take too much memory

src/couch/src/couch_db.erl, src/smoosh/src/smoosh_channel.erl
Currently, smoosh can recover compaction jobs for databases that do not exist. This PR ensures that the database file exists before recovering the compaction job plus a minor typo fix.
`make eunit apps=smoosh`
=> Fix smoosh enqueueing not found dbs and typo

src/chttpd/src/chttpd_misc.erl, src/chttpd/test/eunit/chttpd_dbs_info_test.erl, src/couch_mrview/src/couch_mrview.erl, src/fabric/src/fabric_view_all_docs.erl
Previously, the `skip` and `limit` parameters of GET `_all_dbs` and `_dbs_info` did not work correctly. If we have 2 _design/* docs and 2 dbs (db1, db2), and we set skip=2, it will return db1 and db2, which is incorrect. Same as the `limit`. This PR will fix it.
```
make eunit apps=chttpd suites=chttpd_dbs_info_test
```
https://github.com/apache/couchdb/pull/3832
=> Fix skip and limit parameters

.gitignore
We include ioq in the main repo currently so it doesn't make sense to ignore it.
=> Do not git ignore src/ioq subfolder

src/chttpd/src/chttpd_misc.erl, src/dreyfus/src/dreyfus.erl, src/mango/src/mango_idx.erl, src/mango/src/mango_native_proc.erl
calling connected() every time causes spurious 503's when clouseau
is temporarily unavailable, which is usually masked by retry logic.
=> Search is available if it was ever available since start

src/jwtf/src/jwtf.erl, src/jwtf/test/jwtf_tests.erl
Jiffy throws exceptions with a descriptive reason that is not JSON-encodable. We attempt to construct a 400 Bad Request and fail, causing the request handling process to crash and no response to the client. Improve on this.
with jwtf authenticator handler enabled;
curl -v http://localhost:15984/test -Hcontent-type:application/json -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCIsImtpZCI6ImZvbyJ9.eyJraWQiOiJmb28iLCJzdWIiOiJhZG1pbiIsIm5hbWUiOiJhZG1pbiIsInJvbGVzIjpbInRlc3QxIiwidGVzdDIiXX0=.xftH2byj7LV9/YqqacmyZfcxQt+/h0etsgtRj6aL4AE="
https://github.com/apache/couchdb/issues/3976
=> Cause a 400 Bad Request if decoding JWT token fails

src/couch/src/couch_bt_engine.erl
Smoosh was broken in 5ed8d54bd834a43a41eba11524171217f141e0cb with the introduction of is_compacting which attempts to cons (`++`) a binary with a list.
Run couchdb for a few seconds with databases and observe the absence of smoosh_server crashing with a `badarg`
https://github.com/apache/couchdb/pull/3766
=> Convert DbName to list before cons

share/server/filter.js, share/server/loop.js, share/server/render.js, share/server/util.js, share/server/views.js, src/couch/priv/couch_js/86/main.cpp
Object.prototype.toSource() is available in all versions of spidermonkey that we support but, in later versions, must be explicitly enabled. The value of the result of toSource() is significant and we'd like to keep it.
We missed a spot when enabling the flag, which this PR corrects.
Since toSource() will always work, I have removed all the guarding added in commit aaa3921cb1cc1c96052630ac8a53ec2471e638d8 that would call toString() (with its unhelpful output) as a fallback.
=> Ensure Object.prototype.toSource is always available

Makefile, Makefile.win, src/mango/requirements.txt, src/mango/test/README.md, src/mango/unittest.cfg, test/elixir/test/view_errors_test.exs
Issues that came up testing on windows.
- nose->nose2 due to python2to3 adding code that no longer works in python 3.10 and nose1's general state.
- replacing now() timestamp usages with a random variable to get around a clock miscalculation on windows causing transient 409 errors.
The normal test suite runs should catch any issues.
These changes relate to testing of the windows glazier building process on new build systems/CI.
=> Window test suite difficulties (nose2, timestamps)

src/mango/requirements.txt
Updating hypothesis to a recent version broke on older linux releases because it removed python 3.6 support as soon as it was EOLed.
This needs to pass standard jenkins CI runs and should also work on python 3.10+. 
https://github.com/apache/couchdb/pull/3980
=> mango_tests: revert hypothesis back for python3.6 compat

build-aux/Jenkinsfile.full
Debian Stretch is out of official support and uses python 3.5 which is EOL so this blocks using recent versions of nose2, hypothesis, etc.
This hopefully drops stretch in the pipeline. I do not know how to test it in advance.
https://github.com/apache/couchdb/pull/3980
https://github.com/apache/couchdb-documentation/pull/714
=> Remove CI support for Debian 9 (stretch)

src/mango/src/mango_error.erl, src/mango/src/mango_opts.erl, src/mango/test/01-index-crud-test.py
Creating an index with `"ddoc":""` or `"name":""` should return a `400 Bad Request`.
```bash
curl -X DELETE $db/abc && curl -X PUT $db/abc
curl -X POST $db/abc/_index -H 'Content-Type: application/json' -d '{"ddoc": "", "index": {"fields": ["foo"]}}'
curl -X POST $db/abc/_index -H 'Content-Type: application/json' -d '{"name": "", "index": {"fields": ["bar"]}}'
{"error":"invalid_empty_string","reason":"Index name/ddoc cannot be empty"}
```
https://github.com/apache/couchdb/issues/1472
=> Creating index with empty "name"/"ddoc" should return 400

rel/overlay/etc/default.ini, src/mem3/src/mem3_reshard_index.erl, src/mem3/src/mem3_reshard_job.erl, src/mem3/test/eunit/mem3_reshard_test.erl
Previously we didn't check responses from get_state/2 or await/2 functions when building indices. If an index updater crashed, and the index never finished building, the get_state/2 call would simply return an error and the process would exit normally. Then, the shard splitting job would count that as a success and continue to make progress.
To fix that, make sure to check the response to all the supported indexing types and wait until they return an `ok` result.
Additionally, increase the index building resilience to allow for more retries on failure, and for configurable retries for individual index builders.
=> Improve index building during shard splitting

src/chttpd/src/chttpd_db.erl, src/couch/src/couch_util.erl, src/fabric/src/fabric.erl, src/fabric/src/fabric_doc_update.erl
Under heavy load, fabric_update_doc workers will return `timeout` via
rexi. Therefore no responses will populate the response dictionary.
This leads to `badargs` when we do `dict:fetch` for keys that do not exist.
This checks for the existence of the key and then returns undefined
if it does not exist, which aligns with the same code path of when we
the number of docs < 100.
In this solution, we're masking the fact that workers failed their updates. `handle_message`
is never called since no workers return. The returned `Health` value is actually `ok`. It solves
the badargs but we need to consider a correct response. I don't think 200 is correct.
1) We can return `{error,...}` and also change it for < 100 docs. Possible Breaking change.
2) We can return `{error,...}` for only > 100 docs. …
=> use undefined for timed out responses

rebar.config.script, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_external.erl, src/couch/src/couch_httpd.erl
Previously on error they exited `normal`, and now exit with the `{shutdown, Error}` reason.
See: https://github.com/mochi/mochiweb/commit/e56a4dce6b360c5c5d037e8de33dd267790092e4
=> Handle request processes exiting with `{shutdown, Error}`

rebar.config.script
https://github.com/apache/couchdb-mochiweb/commit/077b4f801ba8f853a9649a9c0f055b8e4f33dcca
=> Bump mochiweb to include the {shutdown, Error} in acceptor recycler

src/couch/src/couch_debug.erl
Implement `couch_debug:print_table/2` to facilitate memory leak detections.
=> Implement print_table/2

Makefile, rebar.config.script
jiffy changelog: https://github.com/davisp/jiffy/compare/1.0.9...1.1.1
b64url changelog: https://github.com/apache/couchdb-b64url/compare/1.0.2...1.0.3
=> Bump jiffy to 1.1.1 and b64url to 1.0.3

rel/overlay/etc/default.ini, src/smoosh/src/smoosh_channel.erl, src/smoosh/src/smoosh_priority_queue.erl, src/smoosh/src/smoosh_server.erl, src/smoosh/src/smoosh_utils.erl
With a few channels around these add up and make local development not as ergonomic. Let's turn them to `debug` and users can always toggle them to info or error if needed.
=> Reduce smoosh compaction log level to debug

src/chttpd/src/chttpd_db.erl, src/couch/src/couch_httpd_multipart.erl, src/fabric/src/fabric_rpc.erl, test/elixir/test/attachments_multipart_test.exs, test/elixir/test/config/suite.elixir
This PR adds an extra `hello_from_writer` message into the handshake between the process that reads the multipart attachment data from the socket and the writer processes (potentially on remote nodes) that persist the data into each shard file. This ensures that even in the case where a writer does not end up asking for the data (e.g. because the revision already exists in the tree), the parser will monitor the writer and therefore know when the writer has exited.
The patch makes some assumptions that the attachment flush function is executed in the same process as the initial one that is spawned to handle the fabric_rpc work request. That's true today, but if it changed in the future it would be a non-obvious breakage to debug.
I'm not crazy about this solution to be quite honest, but I …
=> Ensure the multipart parser always learns about the workers

rel/overlay/etc/default.ini, src/rexi/src/rexi.erl
It should save some dist bandwidth when workers are canceled at the end of fabric requests. The feature has been available since 3.0.x (3 years ago) so opt to enable it by default.
Users who do a rolling upgrade from 2.x could still set it to `false` and then, after the upgrade completes, delete it to return it to default (true).
=> Default rexi use_kill_all to true

src/couch/src/couch_file.erl, src/fabric/src/fabric_doc_update.erl, src/rexi/src/rexi.erl, src/smoosh/src/smoosh_channel.erl, src/smoosh/src/smoosh_server.erl, src/smoosh/src/smoosh_utils.erl
Remove some dead code.
* Unused include files
* Experimental functionality (schemas) in smoosh
* Unused exported functions from `couch_file`
* `append_binary_md5/2`
* `assemble_file_chunk/1`
* `append_term_md5/2`
* `append_term_md5/3`
* `pread_binaries/2`
* `pread_iolists/2`
=> Dead code cleanup

src/jwtf/src/jwtf.erl, src/jwtf/test/jwtf_tests.erl, test/elixir/test/jwtauth_test.exs
ES256 support is apparently broken. Here's a test to prove it. I don't know the fix, though. I tried the same example (from jwt.io) with another library (https://github.com/G-Corp/jwerl) and it also fails. Is... Is erlang the problem?
=> Fix jwtf support for ES* algorithms

src/chttpd/src/chttpd.erl
We handle mochiweb's `{shutdown, Error}` exit. However, chttpd itself exits with a plain `exit(shutdown)`, and in that case, our nested catch statements [1] will emit an "unknown_error" log line. So, make sure to handle that as well
in order to keep the log noise down.
[1] `handle_req_after_auth/2` is nested inside [`process_request/1`](https://github.com/apache/couchdb/blob/3.x/src/chttpd/src/chttpd.erl#L386) and both call `catch_error/4`
=> Handle exit(shutdown) error in chttpd

src/chttpd/test/eunit/chttpd_revs_diff_tests.erl, src/couch/src/couch_db.erl, src/couch/src/couch_httpd_db.erl, src/fabric/src/fabric_rpc.erl
The implementation was duplicated because fabric needed to return a response ([]) for existing revs. It doesn't seem worth it to keep a whole separate copy just to handle the [] case. Instead, make the primary couchdb implementation    always return [] and just filter it out for the local httpd endpoint handlers.
It seems we didn't have any _revs_diff tests, so add a few basic tests along the way.
Also, it turns out we still support the _missing_revs API. That's an endpoint that's not used by the replicator since before 1.2 days. At some point it might be worth removing it, but for now ensure we also test it alongside _revs_diff.
=> Remove duplicate _revs_diff implementation

src/couch/src/couch_util.erl
This function is used in the hot path of _revs_diff and _bulk_docs API calls. Those could always use a bit more optimization:
* In `_revs_diff` it's used when fetching all the FDIs to see which docs are
missing in `couch_btree:lookup/2`.
* In `_bulk_docs` it's used in the `fabric_doc_update` when finalizing the
response.
Using erlperf in #4051 noticed an at most 5x speedup from using a map instead of a dict. Since a map already falls back to a proplist for small sizes, skip the length guard.
Some examples runs with 500 keys:
```
> f(Keys), f(Res), {Keys, Res} = Gen(500), ok.
> erlperf:run(#{runner => {couch_util, reorder_results2, [Keys, Res, 100, dict]}}).
2407
> erlperf:run(#{runner => {couch_util, reorder_results2, [Keys, Res, 100, map]}}).
11639
```
Using a map without the guard, …
=> Optimize couch_util:reorder_results/2,3

src/couch/src/couch_key_tree.erl
Issue originally discovered by @iilyak using https://comby.dev/
=> Avoid using length/1 guard for >0 or ==0 tests in couch_key_tree

src/couch/src/couch_key_tree.erl, src/couch/src/test_util.erl, src/couch/test/eunit/couch_key_tree_tests.erl, src/couch_pse_tests/src/cpse_test_fold_changes.erl, src/mem3/test/eunit/mem3_ring_prop_tests.erl
Previously, we always fully traversed the search keys list, when we partitioned it into possible and impossible sublists. The optimization is we can stop traversing early if the search keys are sorted as soon as we hit a key that is `>=` than the current position in the tree. To keep things simple we can use the [lists:splitwith/2](https://github.com/erlang/otp/blob/40922798411c2d23ee8a99456f96d6637c62b762/lib/stdlib/src/lists.erl#L1426-L1435) function which seems to do what we want.
=> Optimize couch_key_tree:find_missing/2

src/chttpd/test/eunit/chttpd_revs_diff_tests.erl, src/couch/src/couch_db.erl
"Possible ancestors" are all the leaf revisions with a position less than any of the missing revisions. Previously, for every leaf revision we potentially checked every missing revision. And with missing revisions list being sorted from smallest to largest, that meant often traversing most of the missing revisions list. In general, it meant performing `O(R * M) `operations, where `R` is the number of leaf revision, and `M` is the number of missing revisions.
The optimization is instead of comparing against every single missing revision we can compare only against the highest one. If a leaf revision is less than highest missing revision, then it is already a possible ancestor, so we can stop checking. Thus, we can go from a quadratic `O(R * M)` to an `O(R) + O(M)` complexity, which, when …
=> Reduce complexity of "possible_ancestors" from quadratic to linear.

rebar.config.script
Before merging this PR, PR [couchdb-snappy#16](https://github.com/apache/couchdb-snappy/pull/16) in couchdb-snappy needs to get merged and tagged with CouchDB-1.0.8
=> Add Erlang 25 support

rel/overlay/etc/default.ini, src/couch/src/couch_db.erl, src/couch_pse_tests/src/cpse_test_purge_docs.erl, src/fabric/src/fabric_doc_purge.erl, src/mem3/src/mem3_rep.erl
It seems we had forgotten to enable it and in the case a node if off-line when a clustered purge request is issued, and then re-join they won't know to process any purge requests issued to other nodes.
After enabling it @jjrodrig had noticed that sometimes we were getting a duplicate UUID purge error thrown. That's because now there is a chance for a race between the internal replicator and the interactive request, when they both handle the exact same purge request. So, instead of throwing a duplicate UUID request, consider a duplicate purge request a no-op, that's the second commit in the PR.
=> Enable replicating purge requests between nodes

src/couch_replicator/test/eunit/couch_replicator_error_reporting_tests.erl
This fixes the replicator eunit failure: https://github.com/apache/couchdb/pull/4060#issuecomment-1154391783
=> Erlang 25 compatibility - http_uri:parse -> uri_string:parse

build-aux/Jenkinsfile.full
We had to set spidermonkey to 78 in the PR CI builds so do the same for full builds.
This the same PR as  https://github.com/apache/couchdb/pull/4072 just pushed from a jenkins- branch so it can run the full build
=> Fix full CI build

src/couch/src/couch_db.erl
If the given UserRoles/Roles/Names aren't lists, ordersets:from_list/1
or lists:member will fail with an error. Prevent this with Erlang
Pattern Matching or the Robot Butt Rule[1].
Thanks @nickva
[1] https://medium.com/erlang-battleground/ode-to-the-robot-butt-bbd69e69beb2
=> Prevent error:function_clause in check_security/3 if roles claim is malformed

rel/overlay/etc/vm.args
* file IO is using dirty IO schedulers and not the async IO thread pool
* `-smp enable` does nothing, it's always enalbed
* kernel polling is always enabled
```
% erl +SDio 16
Erlang/OTP 23 [erts-11.2.2.13] [source] [64-bit] [smp:12:12] [ds:12:12:16] [async-threads:1]
> erlang:system_info(kernel_poll).
true
> erlang:system_info(dirty_io_schedulers).
16
```
=> Update vm.args for Erlang 23+
