- LICENSE
- NOTICE
moment.js was added to Fauxton. This PR just updates the licensing list.
> Adding licence for moment.js lib

- LICENSE
- NOTICE
Licenses for:
React.js
Flux.js
es5-shim.js
Also fix the moment.js path
> New Licenses used in Fauxton

- share/doc/src/api/server/common.rst
- src/couchdb/couch_httpd_misc_handlers.erl
> Week of day for past expiration date 1990-01-01 is Monday

- INSTALL.Unix
rebar must be installed for configuration before compilation
> Updating INSTAL.Unix for debian related dependencies

- rel/reltool.config
Needed for https://github.com/apache/couchdb-chttpd/pull/43
> Make sure we start `setup` application

- test/javascript/tests/csrf.js
> CSRF tests

- dev/run
This PR is a part of https://github.com/apache/couchdb-couch/pull/80
> Setup dev cluster with common CSRF secret

- LICENSE
- NOTICE
from 95f913a57ce8aa8aa08252a2af6d80b776c4f459 in couchdb-fauxton
> Take out references to jquery.form.js

- test/javascript/tests/csrf.js
> Adapt csrf test to hit form data endpoint

- dev/run
Retry database creation during cluster setup
> Retry database creation during cluster setup

- .gitignore
- .travis.yml
- Makefile
- README-DEV.md
- rebar.config.script
- run-tests.sh
This adds:
- Help for make targets
- Dialyze-related targets
- Ability to run eunit and dialyze targets in rebar-style way
- Ability to run specific javascript test with make javascript
Also README-DEV updates with instructions how to use this.
> Improve developing experience

- rel/overlay/etc/default.ini
> Remove configurable replicator db name

- src/couchdb/couch_httpd_misc_handlers.erl
> Fix favicon caching on leap year

- rebar.config.script
Bring in following commits:
- Don't rely on timer:sleep after update in tests
> Update couch_epi to fix test suite

- rebar.config.script
Jira: COUCHDB-2988 (Mango Selectors for _changes feeds).
> Mango Selectors for _changes feeds

- dev/run
- rebar.config.script
- rel/reltool.config
needs https://github.com/apache/couchdb-chttpd/pull/119
> remove cassim from build until fixed

- rel/overlay/etc/default.ini
> Document default_security property

- rebar.config.script
This includes all the changes made to couch_mrview since the last deps update
> Update to the latest mrview

- test/javascript/tests/cookie_auth.js
- test/javascript/tests/users_db.js
Did some work on cookie_auth and users_db. Unfortunately, deleting user docs seems broken now (you can reproduce it by manually creating one in admin party and trying 2 remove it again). I guess I won't get much further this week, but maybe it helps already... (for more comments and the remaining users_db_security see https://issues.apache.org/jira/browse/COUCHDB-2991)
> Auth tests wip

- test/javascript/couch.js
- test/javascript/couch_test_runner.js
- test/javascript/tests/cookie_auth.js
- test/javascript/tests/users_db.js
- test/javascript/tests/users_db_security.js
Thanks to @sebastianrothbucher and @rnewson for their tireless effort in getting this going <3
This is the last major one before 2.0 RCs. Let’s get this shipped!
> fixes auth tests in JS suite.

- test/javascript/run
This enables the new couchjs test suite functions.
COUCHDB-3057
---
> Enable test suite functions in the test suite

- .gitignore
Ignore these files in rel:
snap.ini
snap_run*
snapcraft.yaml
> Git ignore rel/snap*

- configure
Add snapd browser-support interface to allow couchjs to control process priority
> Allows couchjs to run under snap confinement

- .gitignore
Per Wohali's request on https://github.com/apache/couchdb/pull/460
> Tell Git to ignore snap files so they don't clutter things

- share/server/views.js
Add `log` as another option for `query_config.reduce_limit` instead of `true`
or `false` only. This warns user without crashing the view.
Account for reduce functions code size when checking for overlflow. Code size
was previously implicitly included in input size, skewing the result of
overflow check.
Increase threshold for overflow check. Before it was only 200. This
should prevent false positives in case users have a large accumulator object to
collect various stats.
(PR-ing to discuss. Ok to postpone this after 2.0 release if not needed a 2.0 bug fix)
> Improve reduce function overlow handling

- README.rst
As we embrace GH more, it's high time to publicize our build status a bit better.
> Add Travis and Jenkins build status images to README

- src/mem3/src/mem3_shards.erl
This is a PR for a branch which is already used for PR.
It adds a few tests for the new features and a fix.
https://github.com/apache/couchdb/pull/476
> Couchdb 3376 fix mem3 shards fixes

- rel/overlay/etc/default.ini
> Clarify & correct require_valid_user setting

- src/couch/src/couch_auth_cache.erl
The couch_auth_cache process was attempting to track its various
monitors and then based on its monitor history decide if a 'DOWN'
message meant it should reinitialize or exit. With the new pluggable
storage engine work there was a subtle change to monitors which ended up
causing couch_auth_cache to receive a monitor from the file descriptor
before it received the monitor from the database's main pid. This
reordering was enough for couch_auth_cache to exit which ended up
causing errors in the test suite with race conditions when the test
tried to open an auth db before couch_auth_cache had restarted and
created the database.
However, if we step back and think harder, we'll never get a monitor
message we didn't ask for so rather than attempt to track specific
monitors we just reinitialize …
> Fix couch_auth_cache reinitialization logic

- src/couch_replicator/test/couch_replicator_small_max_request_size_target.erl
Increase timeout for test case that has timed out in CI before.
Needs to run in CI to see if comes up again.
https://issues.apache.org/jira/browse/COUCHDB-3408
> chore: double test timeout see COUCHDB-3408

- src/couch/test/couchdb_compaction_daemon_tests.erl
Increased test timeout, trying to reduce flakyness.
https://issues.apache.org/jira/browse/COUCHDB-3344
> increase timeout for compaction daemon tests COUCHDB-3344

- src/couch_replicator/test/couch_replicator_compact_tests.erl
See https://github.com/apache/couchdb/pull/520
> improve test follow up for #520

- test/javascript/couch_test_runner.js
- test/javascript/tests/show_documents.js
Added debug out to failing test.
https://issues.apache.org/jira/browse/COUCHDB-3343
> add debugging for failing test COUCHDB-3343

- src/couch/src/test_util.erl
This allows us to make some better assertions/logging when starting our
application list on what should and should not already be started.
None. This is a minor tweak to the way eunit tests start their required applications so that we can make a few different assertions and add a log notice when starting applications. This is for the chttpd tests that fail with a warning about couch_epi.
> Pre-calculate application start order

- src/mem3/src/mem3_rep.erl
If minimum checkpointed sequence is greater or equal to source db sequence,
do not start an internal replication task. The typical case is when checkpoint
sequence is equal to the db sequence. Previously replication task was started
always wrote a checkpoint document even if no database changes. This resulted
in a flurry of writes during cluster startup.
* Start 3 node dev cluster with ./dev/run
* Create a database
* Stop cluster
* Start cluster again
* Connect with ./dev/remsh
* After 10-20 seconds sample `couchdb.database_writes` statistic:`couch_stats:sample([couchdb,database_writes]).`
* On master it would 128 or so
* With this PR it would be 0
> Skip internal replication if changes already replicated

- README-DEV.rst
This option is no longer available.
> Remove "--prefix" option from README-DEV

- src/chttpd/test/chttpd_db_test.erl
> chore: more test debugging for COUCHDB-3415

- src/couch/test/couchdb_os_daemons_tests.erl
Fix for https://github.com/apache/couchdb/issues/571
> chore(test): increase test timeout #571

- src/couch_mrview/src/couch_mrview_util.erl
There are a race condition in `get_view/4`, between acquiring index's Pid and getting
its state, that surface when the same signature DDoc got rapidly deleted and re-created.
This patch addresses this by adding retry logic to `get_view_index_state`.
Running in while loop `make javascript suites=builtin_reduce.js` should not yield exceptions in long run.
apache/couchdb#548
> Add retry to get_view_state

- src/couch/src/couch_att.erl
Previously attachment uploading would fail if non-PSE nodes would push
attachment to PSE nodes. This PR handles dynamic translation of previous
attachment streamer format to the new PSE-version.
> Handle attachments in a mixed cluster environment.

- src/chttpd/test/chttpd_db_test.erl
The timeout=1 (1ms) parameter would some times trigger extra newlines to be
included in the response body. The use of `binary:split/2` would then
return different portions of the body depending on timing in the
cluster. This change adds a helper function to split out all newlines in
the response and then returns the last non-empty line.
This also removes introspection of the clustered update sequence since
this is an HTTP API behavior tests and those are defined as opaque
values.
COUCHDB-3415
make check apps=chttpd
Whatever this PR turns out to be...
> Account for extra newlines in response body

- src/couch_log/test/couch_log_config_listener_test.erl
To test a config listener's restart we are deleting event handler in config_event and then immediately checking event manager.
This creates race when we can be a slightly early and catch old handler yet to be removed or slightly late and get new handler that already been installed.
This patch trying to address this by doing the check immediately after old handler exits and then incrementally waiting for new handler to be installed.
Run for an isolated test:
```bash
make eunit apps=couch_log suites=couch_log_config_listener_test tests=couch_log_config_test_
```
Fixes #581
> Wait for listener's exit during restart test

- src/couch/test/couchdb_compaction_daemon_tests.erl
Test `couchdb_compaction_daemon_tests` periodically crashes with database not been idle after compaction completion. The reason been a race condition when index compacting process can be a bit slow (2ms is enough) to release db monitor after `swap_compacted` call. There are also amount of CRASH messages in test log related to premature unload of meck and indexers crashes on teardown, which makes troubleshooting harder.
This patch addresses the CRASH messages by refactoring the test's setup and teardown and adding monitor on compacting process to resolve the race.
`make eunit apps=couch suites=couchdb_compaction_daemon_tests tests=compaction_daemon_test_` should successfully pass and `couch.log` in `src/couch/.eunit` shouldn't have CRASH messages.
Fixes #564
> Fix compaction daemon tests

- src/couch/src/couch_server.erl
> Fix mismatch between MAX_DBS_OPEN and default.ini

- src/couch/test/couchdb_file_compression_tests.erl
> Fix eunit timeout option for compression tests

- src/couch/test/couch_changes_tests.erl
Couldn't remove all sleeps as they are also used to
assert that nothing happened in a period of time or
to track generalized progress over a period of time
(the heartbeat test).
Issue #630
> Remove some sleeps from change feed test.

- INSTALL.Unix.md
> Improve UNIX dependency installation docs (Node.JS, Sphinx)

- src/chttpd/src/chttpd.erl
Previously it returned a 500 error.
> Make replication filter fetch error for _replicate return a 404

- src/chttpd/src/chttpd.erl
- src/couch/src/couch_uuids.erl
- src/couch/test/couch_work_queue_tests.erl
- src/couch/test/couchdb_views_tests.erl
- src/couch_replicator/test/couch_replicator_large_atts_tests.erl
- src/couch_replicator/test/couch_replicator_many_leaves_tests.erl
- src/couch_replicator/test/couch_replicator_missing_stubs_tests.erl
- src/ddoc_cache/src/ddoc_cache_util.erl
crypto:rand_bytes is deprecated.
> use crypto:strong_rand_bytes

- src/couch/src/couch_changes.erl
Use fully qualified call to allow hot code upgrade.
> Allow keep_sending_changes to use hot code upgrade

- src/mango/src/mango_idx_text.erl
We weren't stopping the correct set of applications as well as
forgetting to unload meck. I've also changed the test generators so that
they execute all of the provided assertions.
Fix #687
> Fix test teardown

- src/couch/test/couchdb_views_tests.erl
The previous version of this test relied on trying to bump into the
all_dbs_active error from the couch_server LRU. This proves to be rather
difficult to reliably provide assertions on behavior. In hindsight all
we really care about is that the compactor holds a monitor against the
database and then we can trust couch_server will not evict anything that
is actively monitored.
Fixes #680
> Simplify regression test for COUCHDB-1283

- src/couch/test/couch_db_mpr_tests.erl
Previous default timeout of 5 seconds was not enough when running in an
environment where disk access is severly throttled.
To add a timeout, changed the test function into a test generator. That also
made the `with` construct un-necessary.
Fixes #695
> Increase timeout in couch's couch_db_mpr_tests module to 30 seconds

- src/couch/test/couchdb_views_tests.erl
This makes sure that we correctly synchronize with the process running
compaction before we perform our desired assertions.
Fixes #701
> Fix regression test for COUCHDB-1283

- .travis.yml
- Makefile
- src/mango/test/01-index-crud-test.py
- test/build/test-run-couch-for-mango.sh
Update our travis file to run the mango tests
> run mango tests on travis

- BUGS.md
- COMMITTERS.md
- README.rst
Minor cleanup. Also going to use this to test if we can review our own PRs for commit purposes.
> Update README Jenkins link and minor misc. cleanup

- src/mango/src/mango_cursor_view.erl
Remove commented code that accidentally got merged in.
> remove commented out code

- src/couch_mrview/test/couch_mrview_ddoc_updated_tests.erl
issue #757
`make check apps=couch_mrview tests=ddoc_update_test_`
757
> Avoid race condition in couch_mrview_ddoc_updated_tests

- src/mango/test/03-operator-test.py
- src/mango/test/user_docs.py
Clarify behaviour for null / missing fields. Convert tests to unittest assertions for clearer errors.
This is just testing / clarifying existing behaviour - all tests are expected to pass.
> Improve Mango operator tests

- src/couch_replicator/src/couch_replicator_ids.erl
Previously users had to URL encode replication IDs when using
`_scheduler/jobs/<job_id>` endpoint because Mochiweb incorrectly decoded the
`+` character from URL path. So users were forced to encode so that the
replicator would correctly receive a `+` after Mochiweb parsing.
`+` is decoded as ` ` (space) probably because in query strings that's a valid
application/x-www-form-urlencoded encoding, but that decoding is not meant for
decoding URL paths, only query strings.
Notice RFC 3986 https://tools.ietf.org/html/rfc3986#section-2.2
`+` is a `sub-delim` (term from RFC)  and in the path component it can be used
unquoted as a delimiter.
https://tools.ietf.org/html/rfc3986#section-3.3
Indeed, the replication ID is a compound ID and `+` is a valid delimiter
which separates the base part from …
> Fix replication ID parsing in URL paths

- src/fabric/src/fabric_db_info.erl
The patch adds a "cluster" block into a database info with values for database's `q`, `n` and default `w` and `r`. This enhancement can help with debugging, operations and performance analysis.
Changes specific tests:
`make eunit apps=fabric suites=fabric_db_info`
Fixes #812
> Add cluster info to database information

- Jenkinsfile
This PR adds support to the Jenkins CI build chain for Debian 9 (stretch) and drops support for Ubuntu 12.04.
Jenkins is green with this updated Jenkinsfile + associated changes already merged into couchdb-ci and couchdb-pkg.
> Jenkins: Add Debian 9 (stretch), drop Ubuntu 12.04 (precise)

- src/couch_peruser/test/couch_peruser_test.erl
> fix: peruser tests: use spinlocks instead of timer:sleep()

- src/couch/include/couch_eunit.hrl
> feat: port time funs, as per #883

- src/couch_peruser/test/couch_peruser_test.erl
Fix for https://github.com/apache/couchdb/pull/923
> fix(peruser_test): on slow CI vms, we can get Cluster timeouts

- share/www/script/test/config.js
- src/couchdb/couch_httpd_misc_handlers.erl
- src/couchdb/couch_util.erl
This is backport of https://github.com/apache/couchdb/pull/914
> Blacklist some config sections from HTTP PUT/DELETE operations

- src/chttpd/src/chttpd_auth_cache.erl
- src/couch/src/couch_users_db.erl
This reverts commit 42adcc1a0849f65f9ef4d55aafe11b3aa59512a9.
https://github.com/apache/couchdb/commit/0ce05d26a565188aa4e2b0181788b244fe385e01
Follow-up for #944
> Revert "feat: reject user docs with duplicate keys"

- .travis.yml
- INSTALL.Unix.md
- Makefile
- NOTICE
- dev/run
- rebar.config.script
- rel/overlay/etc/default.ini
- src/chttpd/src/chttpd_misc.erl
- src/chttpd/src/chttpd_view.erl
- src/couch/include/couch_eunit.hrl
- src/couch/priv/couch_js/help.h
- src/couch/priv/couch_js/main.c
- src/couch/priv/couch_js/util.c
- src/couch/priv/couch_js/util.h
- src/couch/src/couch_httpd_misc_handlers.erl
- src/couch/src/couch_util.erl
- src/couch_peruser/test/couch_peruser_test.erl
- src/couch_replicator/src/couch_replicator_worker.erl
- src/mango/test/mango.py
- test/javascript/couch.js
- test/javascript/run
- test/javascript/tests/config.js
- test/javascript/tests/erlang_views.js
- test/javascript/tests/view_errors.js
- test/javascript/tests/view_sandboxing.js
This is all cherry picks from master, no independent commits.
Pre-approved by @janl
> More updates for 2.1.1 candidate

- src/ejson/ejson.erl
1.x companion for https://github.com/apache/couchdb/commit/0ce05d26a565188aa4e2b0181788b244fe385e01
> ejson dupes

- .travis.yml
- configure.ac
- src/couch_plugins/src/couch_plugins.erl
- src/couch_replicator/test/couch_replicator_large_atts_tests.erl
- src/couch_replicator/test/couch_replicator_many_leaves_tests.erl
- src/couch_replicator/test/couch_replicator_missing_stubs_tests.erl
- src/couchdb/Makefile.am
- src/couchdb/couch_httpd_auth.erl
- src/couchdb/couch_passwords.erl
- src/couchdb/couch_rand.erl
- src/couchdb/couch_server.erl
- src/couchdb/couch_util.erl
- src/couchdb/couch_uuids.erl
- src/erlang-oauth/oauth.erl
- src/mochiweb/mochiweb.erl
- src/mochiweb/mochiweb_multipart.erl
- src/my-first-couchdb-plugin/Makefile
- test/couchdb/couch_auth_cache_tests.erl
- test/couchdb/couch_btree_tests.erl
- test/couchdb/couch_file_tests.erl
- test/couchdb/couch_work_queue_tests.erl
- test/couchdb/couchdb_attachments_tests.erl
- test/couchdb/couchdb_views_tests.erl
mostly 2.x backports from @nickva, thanks! :)
> R20 compat for 1.x.x

- src/couch_mrview/src/couch_mrview_http.erl
In https://github.com/apache/couchdb-couch/pull/29 the possible
security errors went from only "unauthorized" to "unauthorized" and
"forbidden", but the corresponding check for both was not done in
couch_mrview_http. This addresses that problem and fixes #974.
* https://github.com/apache/couchdb-couch/pull/29
> Look for forbidden and unauthorized in is_admin

- Jenkinsfile
See https://github.com/apache/couchdb/pull/986
> Revert to ubuntu Jenkins label, uids now standardised

- src/couch_replicator/README.md
I noticed a typo. I assume by "Fetchig" you meant "Fetching" so I submitted this PR.
> (typo) fetchig -> fetching

- src/couch_replicator/src/couch_replicator_clustering.erl
Replicator clustering module is in charge of keeping track of when the cluster
is stable or unstable. A cluster is said to be "stable" if there weren't any
new nodes added or removed for some period of time.
Replicator document processor uses cluster state to determine what to do with
document updates as they come in. If a document update comes during a time when
cluster is unstable, the update is skipped. The idea is that when cluster
becomes stable again, all the documents will be rescanned anyway.
In order for document updates to not be dropped, there is an implicit
constraint when cluster becomes stable again (couch_replicator_notifier
gen_event broadcasts `{cluster, stable}` event), any subsequent calls to
`couch_replicator_clustering:is_stable()` would return `true`. If that's not …
> Fix replicator cluster stability race condition

- src/chttpd/rebar.config
- src/couch_index/rebar.config
- src/couch_mrview/rebar.config
- src/fabric/rebar.config
- src/rexi/rebar.config
Enable coverage reports for more applications
> Add coverage reports to more applications

- rel/plugins/eunit_plugin.erl
We are using `unique_monotonic_integer` to name the test databases in unit testing. That means that on erlang R > 18 we are always creating databases with the same names.
When a unit tests crashing or suites don't cleaning up on teardown, they are leaving behind
old database files, so on a next run, in dev environment, tests' setup fails with `database exists` exception.
This fix cleans up old database files prior running the unit tests, making sure we are always running the test from the same blank state.
- Run test suite, e.g. `make check apps=couch`.
- Confirm that there are temporary test databases in `$PWD/tmp/data` and `/$PWD/tmp/tmp_data` left behind.
- Run `rebar setup_eunit`. It's going to fail with "One or more files already exist on disk and were not generated", but it'll clean …
> Cleanup data dirs in eunit_plugin before test run

- src/couch_peruser/test/couch_peruser_test.erl
Fix a random mashup of test object generators with normal assertions. Should help with test's flakiness due to races and insure the test is actually testing what it's claiming it's testing.
Complete test suite should pass.  For isolated test: `make eunit apps=couch_peruser`
> Fix couch_peruser_test

- Makefile
> Create all needed directories to build docs

- rebar.config.script
> Bump config to 1.0.2 for dialyzer related fixes

- src/couch/src/couch_httpd_multipart.erl
Occasionally it's possible to lose track of our RPC workers in the main
multipart parsing code. This change monitors each worker process and
then exits if all workers have exited before the parser considers itself
finished.
Fixes part of #745
This was tested under the conditions for 745 which are non-trivial but can be duplicated by reading that PR.
Issue #745 was the original report for this issue
> Prevent chttpd multipart zombie processes

- src/couch/src/couch_bt_engine.erl
Somehow managed to fix without getting it into the PSE PR that was
merged the other day.
curl _local_docs endpoint
> This fixes couch_bt_engine:fold_local_docs/4

- rebar.config.script
This adds fixes to handle non-persistent set_integer/set_boolean values
> Bump config dependency to 1.0.3

- .gitignore
- rebar.config.script
- src/setup/.gitignore
- src/setup/LICENSE
- src/setup/README.md
- src/setup/src/setup.app.src
- src/setup/src/setup.erl
- src/setup/src/setup_app.erl
- src/setup/src/setup_epi.erl
- src/setup/src/setup_httpd.erl
- src/setup/src/setup_httpd_handlers.erl
- src/setup/src/setup_sup.erl
- src/setup/test/t-frontend-setup.sh
- src/setup/test/t-single-node.sh
- src/setup/test/t.sh
Import the couchdb-setup repo via a git subtree merge.
Closes #567 & Closes #566.
> Import setup

- rebar.config.script
> Switch to using a mirrored triq dependency

- src/couch_replicator/README.md
While reviewing the very nice documentation for couch_replicator, I went ahead and made a few cleanup changes for spelling etc.
This is a documentation-only change.
> Minor documentation cleanup for couch_replicator

- src/couch/src/couch_db_updater.erl
Regression since introduction of PSE
> call commit_data where needed

- src/couch/src/test_util.erl
With db headers moved into engine's state, any `fake_db` call that is trying to setup sequences for tests (e.g. in mem3_shards) crashing with context setup failed.
It's not trivial to compose a proper `engine` field outside of couch app, so instead this fix makes `fake_db` to set engine transparently, unless it provided explicitly in a payload.
Without this change running `make eunit apps=mem3 suites=mem3_shards` would crash with 
```
...
*** context setup failed ***
**in function erlang:setelement/3
called as setelement(undefined,{db,1,<<"dbs">>,undefined,
{couch_bt_engine,undefined},
nil,nil,undefined,undefined,
{user_ctx,null,[],undefined},
[],undefined,nil,nil,...},0)
in call from test_util:'-fake_db/1-fun-0-'/3 (src/test_util.erl, line 244)
in call from lists:foldl/3 (lists.erl, line …
```
> Adopt fake_db to PSE changes

- test/javascript/tests/reduce_builtin.js
> Add JS integration tests for _approx_count_distinct

- .gitignore
> Add hyper directory to .gitingore file

- Makefile
Add new 3rd party modules into `skip_deps` for eunit run
Standard test should pass
> Update `skip_deps` for 3rd parties eunit

- src/chttpd/src/chttpd.erl
Previously, when we fail authorization but pass authentication, we use
the old HttpReq which drops user_ctx (so it is undefined). This change retains the authenticated HttpReq which includes a user_ctx. This allows for after_requests to utilize a user_ctx that is not
undefined.
Eunit test added to chttpd module.
https://github.com/apache/couchdb/issues/1374
> Refactor process_request to not drop req

- Jenkinsfile
Thanks to Just Some Enterprises for donating the compute power!
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-freebsd/5/pipeline/43 all green for FreeBSD.
We're not going to build FreeBSD packages; that'll be up to FreeBSD to continue supporting via the pkg/ports tree mechanisms, which I know @dch is working on. All this does is validate that you can build CouchDB on FreeBSD (and run all the tests successfully) given installing prerequisites via these scripts:
https://github.com/apache/couchdb-ci/commit/5dda73deec3b1e320135133fc72b3983ca0f0f23
> Add regression runs on new dedicated FreeBSD VM

- .travis.yml
we don’t need to run the full test matrix twice for each PR.
> feat: avoid double builds on PRs

- src/setup/src/setup.erl
See https://github.com/apache/couchdb-setup/pull/15 and https://github.com/apache/couchdb-setup/pull/16
Closes #897
> port setup PRs

- test/elixir/test/basics_test.exs
- test/elixir/test/test_helper.exs
Replace racy assertions with retry_until
`mix test --trace test/basics_test.exs`
> Implement retry_until to fix racy assertions

- test/javascript/tests/design_docs.js
> improve ddoc test reliablilty by waiting for ddoc deletion

- rebar.config.script
> bump hyper dependency, fix Windows build

- rebar.config.script
Thanks to @Antonio-Maranhao @garrensmith @popojargo for all the great fixes in Fauxton since the last tag!
> Bump fauxton dependency

- test/elixir/test/batch_save_test.exs
Port batch_save.js
```
$ mix test --trace test/batch_save_test.exs
Excluding tags: [pending: true]
BatchSaveTest
* test batch put with identical doc ids (303.4ms)
* test batch put (615.3ms)
* test batch post (526.9ms)
CouchTestCase
Finished in 1.7 seconds
3 tests, 0 failures
Randomized with seed 973579
```
> Port batch_save.js

- rebar.config.script
Address concern from 2.2.0-RC1 with broken Fauxton in IE11.
> bump fauxton

- test/elixir/test/compact_test.exs
Port compact.js
`mix test --trace test/compact_test.exs`
> Port compact.js

- src/mem3/src/mem3_rep.erl
Previously there were two separate database references and it was not
clear which was used where. This simplifies things by reducing it to a
single instance so that the logic is simpler.
This depends on PR #1366.
> [2/5] Clustered Purge - Simplify mem3_rep

- src/mem3/src/mem3_rep.erl
Previously there were two separate database references and it was not
clear which was used where. This simplifies things by reducing it to a
single instance so that the logic is simpler.
Original PR accidentally merged to the wrong branch:
https://github.com/apache/couchdb/pull/1367
> Simplify logic in mem3_rep

- src/couch_pse_tests/src/cpse_test_purge_seqs.erl
Fix make warnings from cpse_test_purge_seqs.erl file
```
/Users/jiangph/couchdb/src/couch_pse_tests/src/cpse_test_purge_seqs.erl:19: Warning: function setup_each/0 is unused
/Users/jiangph/couchdb/src/couch_pse_tests/src/cpse_test_purge_seqs.erl:24: Warning: function teardown_each/1 is unused
/Users/jiangph/couchdb/src/couch_pse_tests/src/cpse_test_purge_seqs.erl:28: Warning: function cpse_increment_purge_seq_on_complete_purge/1 is unused
/Users/jiangph/couchdb/src/couch_pse_tests/src/cpse_test_purge_seqs.erl:69: Warning: function cpse_increment_purge_multiple_times/1 is unused
/Users/jiangph/couchdb/src/couch_pse_tests/src/cpse_test_purge_seqs.erl:98: Warning: function cpse_increment_purge_seq_on_partial_purge/1 is unused
/Users/jiangph/couchdb/src/couch_pse_tests/src/cpse_test_purge_seqs …
```
> Fix make warning from cpse_test_purge_seqs.erl

- src/mem3/src/mem3.erl
Sometimes in operations it is helpful to re-establish connection between
erlang nodes. Usually it is achieved by calling `net_adm:ping/1`. However
the `ping` function provided by OTP uses `infinity` timeout. Which causes
indefinite hang in some cases. This PR adds convinience function to be
used instead of `net_adm:ping/1`.
1. Start dev cluster using `dev/run --admin=adm:pass`
2. Go to remsh `dev/remsh`
3. Call `mem3:ping('node2@127.0.0.1').` you should see `pong`.
3. Call `mem3:ping('node8@127.0.0.1').` you should see `pang`.
4. Try variant with specified timeout 
- `mem3:ping('node2@127.0.0.1', 100).` you should see `pong`.
- `mem3:ping('node8@127.0.0.1', 100).` you should see `pang`.
N/A
> Implement convinience `mem3:ping/2` function

- src/couch_replicator/src/couch_replicator_doc_processor.erl
- src/couch_replicator/src/couch_replicator_scheduler.erl
- src/couch_replicator/src/couch_replicator_utils.erl
This used to be the case before the scheduling replicator:
https://github.com/apache/couchdb-couch-replicator/blob/master/src/couch_replicator.erl#L166
This is also how replications backed by a document in a _replicator db behave:
https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_doc_processor.erl#L283
> Avoid restarting /_replicate jobs if parameters haven't changed

- src/chttpd/src/chttpd_view.erl
- src/chttpd/test/chttpd_db_bulk_get_test.erl
> fix eunit tests for partitions PR

- .travis.yml
- rebar.config.script
- src/chttpd/src/chttpd.erl
- src/chttpd/src/chttpd_db.erl
- src/chttpd/src/chttpd_external.erl
- src/chttpd/src/chttpd_prefer_header.erl
- src/chttpd/src/chttpd_rewrite.erl
- src/chttpd/test/chttpd_prefer_header_test.erl
- src/couch/src/couch_bt_engine.erl
- src/couch/src/couch_file.erl
- src/couch/src/couch_httpd.erl
- src/couch/src/couch_httpd_auth.erl
- src/couch/src/couch_httpd_db.erl
- src/couch/src/couch_httpd_external.erl
- src/couch/src/couch_httpd_proxy.erl
- src/couch/src/couch_httpd_rewrite.erl
- src/couch/src/couch_httpd_vhost.erl
- src/couch/test/couchdb_http_proxy_tests.erl
- src/couch/test/couchdb_views_tests.erl
- src/couch/test/test_web.erl
- src/couch_index/src/couch_index.erl
- src/couch_log/src/couch_log_monitor.erl
- src/couch_log/test/couch_log_test_util.erl
- src/fabric/src/fabric_doc_attachments.erl
- src/fabric/src/fabric_doc_atts.erl
> Erlang 21 support

- src/chttpd/src/chttpd_db.erl
- src/chttpd/test/chttpd_db_bulk_get_test.erl
This fixes _bulk_get for _users db and probably others I don't know
> Pass user_ctx in _bulk_get

- src/couch/src/couch_db.erl
Fixed in `get_minimum_purge_seq/1` to get proper minimum purge seq, and this includes
- should pass DbName instead of db record to validate client,
- display error when client doesn't exist
- use `mem3:dbname/1` to get DbName for `get_design_docs/1`
make check skip_deps+=couch_epi apps=couch
```
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[done in 2.284 s]
[done in 2.380 s]
=======================================================
All 1339 tests passed.
==> rel (eunit)
==> couchdb (eunit)
```
COUCHDB_3326
> Fix in get_minimum_purge_seq/1

- Makefile.win
Fixes the same thing @eiri just fixed, but for Windows
> Add query server to eunit, Makefile.win

- src/chttpd/src/chttpd_auth_cache.erl
- src/couch/src/couch_compaction_daemon.erl
> feat: do not record server admin requests as cache misses

- src/couch/src/couch_compaction_daemon.erl
Previously the compaction daemon looked for design docs in each shard file.
This worked well for versions < 2.x, however, for clustered databases design
documents will only be found in their respective shards based on the document
id hashing algorithm. This meant that in a default setup of Q=8 only the views
of one shard range, where the _design document lives, would be compacted.
The fix for this issue is to use fabric to retrive all the design documents for
clustered database.
Issue #1579
> Use fabric to get design docs in the compaction daemon

- src/couch/include/couch_db.hrl
- src/couch/src/couch_changes.erl
- src/fabric/src/fabric_rpc.erl
wip fix for #1737 just to see how CI likes this, initial comments welcome
> fix: re-enable _doc_id filter optimisation path

- test/elixir/lib/couch/db_test.ex
- test/elixir/test/all_docs_test.exs
- test/elixir/test/cluster_with_quorum_test.exs
- test/elixir/test/cluster_without_quorum_test.exs
- test/elixir/test/rewrite_test.exs
- test/elixir/test/security_validation_test.exs
- Fix broken formatting preventing tests from running
- Wrap racy test assertion in `retry_until` loop
- Don't automatically fail tests if quorum not met on db creation, db deletion or doc creation
`make elixir`
> Elixir test improvements

- rel/overlay/etc/vm.args
Addresses https://github.com/apache/couchdb-documentation/issues/375
> Improve vm.args template comments

- Jenkinsfile
> Move Jenkins to use Erlang 19 for initial build step

- src/chttpd/test/chttpd_purge_tests.erl
Fix a test timeout on Jenkins.
> Fix timeout in chttpd_purge_tests

- .travis.yml
- Makefile
- test/elixir/README.md
- test/elixir/lib/couch.ex
- test/elixir/lib/couch/db_test.ex
- test/elixir/mix.exs
- test/elixir/test/bulk_docs_test.exs
- test/elixir/test/lots_of_docs_test.exs
- test/elixir/test/partition_all_docs_test.exs
- test/elixir/test/partition_crud_test.exs
- test/elixir/test/partition_mango_test.exs
- test/elixir/test/partition_view_test.exs
- test/elixir/test/partition_view_update_test.exs
configure Travis to run the Elixir tests. Since all partition tests are in Elixir it's important we start getting them to run with each build. I've kept the elixir command separate from `make check` until we are able to run the Elixir tests on Jenkins.
Travis should pass
> Elixir travis

- test/elixir/test/lots_of_docs_test.exs
This test is a little flaky. This should hopefully improve it a bit.
Travis tests should all pass.
> add w:3 for lots of docs test

- Makefile
- test/elixir/test/basics_test.exs
- test/elixir/test/compact_test.exs
- test/elixir/test/conflicts_test.exs
- test/elixir/test/delayed_commits_test.exs
- test/elixir/test/lots_of_docs_test.exs
- test/elixir/test/partition_ddoc_test.exs
- test/elixir/test/partition_view_update_test.exs
- test/elixir/test/replication_test.exs
Add back the elixir tests to make check. I want to use this branch to try and fix any flaky tests.
Elixir tests should pass more consistently 
https://github.com/apache/couchdb/issues/1902
> Add back elixir tests to make check

- src/couch/src/couch_db.erl
- src/couch_mrview/test/couch_mrview_purge_docs_tests.erl
The default type for docid is binary, and this change is to extend to support list for docid when using couch_db:purge_docs/3.
make check apps=couch_mrview tests=view_purge_test_
```
Map views
couch_mrview_purge_docs_tests:62: test_purge_single...[0.220 s] ok
couch_mrview_purge_docs_tests:127: test_purge_partial...[0.181 s] ok
couch_mrview_purge_docs_tests:166: test_purge_complete...[0.125 s] ok
couch_mrview_purge_docs_tests:236: test_purge_nochange...[0.160 s] ok
couch_mrview_purge_docs_tests:271: test_purge_index_reset...[0.433 s] ok
couch_mrview_purge_docs_tests:329: test_purge_compact_size_check...[0.861 s] ok
couch_mrview_purge_docs_tests:95: test_purge_single_for_docid_with_list...[0.118 s] …
```
> Support list for docid when using couch_db:purge_docs/3

- rebar.config.script
This allows to keep features on config process restart.
N/A
N/A
> Update config dependency to 2.1.6

- src/couch_mrview/src/couch_mrview_updater.erl
This is a follow up PR to fix compilation warnings introduced in https://github.com/apache/couchdb/pull/1642
```
make eunit apps=couch tests=couch_index_ioq_priority_test_
```
- https://github.com/apache/couchdb/pull/1642
> Remove compilation warnings

- test/elixir/lib/couch/db_test.ex
- test/elixir/test/partition_size_test.exs
More fixes to the tests for Jenkins.
Jenkins should pass
> fixes to tests

- rebar.config.script
Update `smoosh` application to avoid using deprecated APIs (`erlang:now`). 
```
make eunit apps=smoosh
```
- https://github.com/apache/couchdb-smoosh/pull/2
> Update smoosh to 1.0.1

- Makefile
- Makefile.win
Also fix dumb S&R \ vs / bug in URL.
> Warn people to edit both Makefiles.

- test/elixir/README.md
- test/elixir/test/attachments.exs
Rewrite attachment.js in elixir
Tests should pass and match attachments.js
> Jenkins add attachment test

- test/elixir/test/multiple_rows_test.exs
I just ported `multiple_rows.js` to the Elixir test suite.
Just issue `make elixir`
none
> test: port multiple_rows.js to Elixir test suite

- .github/ISSUE_TEMPLATE/rfc.md
> Add security item to the RFC template

- rebar.config.script
> Promote ibrowse 4.0.1-1

- src/mem3/src/mem3_reshard_api.erl
- src/mem3/test/mem3_reshard_api_test.erl
To avoid inadvertently splitting all the shards in all the ranges due to user
error, introduce an option enforce the presence of node and range job creation
parameters.
> Allow restricting resharding parameters

- src/mem3/src/mem3_reshard.erl
Also make it divisible by default Q and N
> Increase max number of resharding jobs

- src/fabric/src/fabric_streams.erl
In fabric streams logic, after replacements are processed, the full ring
assertion was made for the waiting and replaced workers. But, in cases when
some of the workers already returned results, the assertion would fail, since
those ranges would be missing.
The fix is to consider not just waiting and replaced workers, but also the
results that were already processed.
> Fix full ring assertion in fabric stream shard replacements

- src/couch/src/couch_db.erl
Backport of fix to master for 2.3.x. Original commit follows:
Originally we posited that duplicate UUIDs could never be created.
However due to operations interventions its possible to unintentionally
copy UUIDs in ways that violate this assumption. Instead of crashing the
process we just reset the seq to zero and log a warning as was done in
the other instances when we have mismatches in the epoch history.
> Fix epoch mismatch errors (#2027)

- src/mem3/src/mem3_rep.erl
Before shard splitting it was possible to replicate shards even if there were in the shard map. This commit brings back that behavior.
> Make mem3_rep:go work when target shards are not yet present in shard map

- .github/PULL_REQUEST_TEMPLATE.md
Improve our PR template with feedback from @kocolosk about updating `default.ini`.
Also, make it clear our expectations around simultaneous documentation PRs.
None.
#2037
> Improve PR template with @kocolosk feedback

- .travis.yml
- rebar.config.script
> Add erlang 22 support

- src/couch/src/couch_file.erl
- src/couch/test/couch_file_tests.erl
This changes `couch_file` to ensure that errors are raised when a call
to `fsync` fails. It will also stop the couch_file process to ensure
that anything handling a failed `fsync` won't attempt to retry the
operation and experience issues discovered by Postgres [1].
[1] http://danluu.com/fsyncgate/
See http://danluu.com/fsyncgate/
`make eunit`
However, I don't have a good test to assert that the `couch_file` pid exits since the `file` module is quite difficult to get mocked. I'm all ears on how to make this better. My only thought was that I'd have to export a function that can be mocked but it seems weird to have `handle_call` calling a fully qualified exported function just to test that.
> Make sure that fsync errors are raised

- src/mem3/src/mem3_sync_event_listener.erl
Config setting was asynchronous and the waiting function was not
waiting for the actual state value to change just that the state
function was returning.
The fix is to wait for the config value to propagate to the state.
> Fix flaky mem3_sync_event_listener EUnit test

- src/couch/test/couch_passwords_tests.erl
- src/mem3/test/mem3_rep_test.erl
- src/mem3/test/mem3_reshard_api_test.erl
- src/mem3/test/mem3_reshard_changes_feed_test.erl
- src/mem3/test/mem3_reshard_test.erl
- src/mem3/test/mem3_sync_security_test.erl
This is the full set of changes that got EUnit tests to pass across the board on Jenkins for me, except for a change to `mem3_sync_event_listener` that @nickva already addressed separately.
This is a rebase of another branch where you can see Jenkins made it through the EUnit portion of the test suite: https://builds.apache.org/blue/organizations/jenkins/CouchDB/activity?branch=jenkins-fix-eunit-timeouts
> Fix EUnit timeouts

- src/mem3/src/mem3_sync_event_listener.erl
Fix a race condition in state matching, also parameterize the state
field in wait_state.
> Fix mem3_sync_event_listener EUnit test

- src/couch/test/eunit/couch_db_split_tests.erl
- src/couch_mrview/test/eunit/couch_mrview_purge_docs_fabric_tests.erl
- src/ddoc_cache/test/eunit/ddoc_cache_no_cache_test.erl
- test/elixir/lib/couch.ex
Extends timeouts in places where we have seen test failures on Jenkins.
This branch will be tested by Jenkins automatically.
> More timeouts fixes for Jenkins

- src/couch_replicator/src/couch_replicator_scheduler.erl
Fix replication rescheduling Running < MaxJobs corner case
Previously, when total number of replication jobs exceed `MaxJobs`, if some  jobs crashed, additional jobs didn't start immediately to bring the running total up to the `MaxJobs` limit. Then, during rescheduling, the `Running == MaxJobs, Pending > 0` guard would fail and jobs would not rotate. In other words, if at least one job crashed, rotation didn't happen.
The fix is to simplify the rotation logic to handle the `Running < MaxJobs`  case. First, up to `Churn` number of jobs are stopped, then enough jobs are started to reach the `MaxJobs` limit. The rotation logic case handles the `start_pending_jobs/3` case so there is no need to call that separately before rotation happens.
```
make eunit apps=couch_replicator …
```
> Fix replication rescheduling Running < MaxJobs corner case

- src/couch_views/test/couch_views_trace_index_test.erl
Add a trace test for couch_views
> add trace test for couch_views

- src/fabric/src/fabric2_fdb.erl
Previously if a VDU was updated in the `before_doc_update/3` handlers, the Db
handle wasn't refreshed soon enough such that the `prepare_and_validate/3`
would not see the newly update VDU and would not run it.
To fix make a stale Db throws an exception which bubbles up all the way to
`fabric2_fdb:transactional/2` where the transaction is retried again with a
reopened Db.
During `reopen/1` make sure to properly transfer the `user_ctx` property to the
new handle, and also make sure `user_ctx` is removed from `db_options` to avoid
caching it in `fabric2_server`.
> Fix DB reopen behavior

- src/couch_views/src/couch_views_reader.erl
Implement update_seq for couch_views
> Implement update_seq for couch_views

- src/couch_views/test/couch_views_encoding_test.erl
Start stop config and couch_drv in `setup/0` and `teardown/1` instead of the
test function itself.
> Fix couch_views encoding test

- src/chttpd/test/eunit/chttpd_db_test.erl
- src/mem3/src/mem3_util.erl
Database property might be changed after shard map was overwritten, for example,
1. create one database
```
curl -u foo:bar 'http://127.0.0.1:15984/pqdb1?partitioned=true&q=1' -X PUT
{"ok":true}
```
2. check database property
```
(node1@127.0.0.1)1> rp(mem3_shards:for_db(<<"pqdb1">>)).
[{shard,<<"shards/00000000-ffffffff/pqdb1.1566571320">>,
'node1@127.0.0.1',<<"pqdb1">>,
[0,4294967295],
undefined,
[{props,[{partitioned,true},
{hash,[couch_partition,hash,[]]}]}]},
{shard,<<"shards/00000000-ffffffff/pqdb1.1566571320">>,
'node2@127.0.0.1',<<"pqdb1">>,
[0,4294967295],
undefined,
[{props,[{partitioned,true},
{hash,[couch_partition,hash,[]]}]}]},
{shard,<<"shards/00000000-ffffffff/pqdb1.1566571320">>,
'node3@127.0.0.1',<<"pqdb1">>,
[0,4294967295],
undefined,
[{props,[{partitioned,true}, …
```
> Keep database property after overwriting shard map

- src/chttpd/src/chttpd_db.erl
- src/couch_views/src/couch_views_util.erl
- test/elixir/test/basics_test.exs
Also add mrargs validation to match what master does and provide some
helpful feedback to the users.
Test with:
```
make elixir tests=test/elixir/test/basics_test.exs
...
* test _all_docs/queries works (28.5ms)
...
```
> Implement _all_docs/queries

- src/chttpd/src/chttpd_db.erl
- src/fabric/src/fabric2_db.erl
- src/fabric/src/fabric2_fdb.erl
- test/elixir/test/basics_test.exs
Test with
```
$ make elixir tests=test/elixir/test/basics_test.exs
...
* test _design_docs works (90.4ms)
* test _local_docs works (183.5ms)
...
```
> Implement _design_docs and _local_docs namespacing

- src/couch_views/src/couch_views_indexer.erl
Improve build performance by fetching all the docs for the changes feed at once instead of one at a time.
All current tests should pass
> View async doc fetch

- src/chttpd/src/chttpd_db.erl
- test/elixir/test/basics_test.exs
Implement setting and getting _revs_limit
```
$ make elixir tests=test/elixir/test/basics_test.exs
...
* test Check _revs_limit (28.6ms)
...
```
> Implement setting and getting _revs_limit

- src/fabric/src/fabric2_db.erl
- src/fabric/test/fabric2_db_security_tests.erl
This brings this to parity with master `couch_db:open/2` logic:
https://github.com/apache/couchdb/blob/master/src/couch/src/couch_db.erl#L166
There are two separate cases that have to be handled:
1) Db was already opened and cached. In that case, call `check_is_member(Db)`
which reads the security from the Db to ensure we don't authorize against a
stale security doc. Otherwise, the delay could be as long as the last write
that went through that node. A potential future optimization could be to have
a timestamp and only get the new security context if last refresh hasn't
happened recently.
2) Db was not cached, and was just opened. To avoid running another two read
transactions to get the security doc after the main transaction finished, call
a version of check_is_member which gets the …
> Check members after db is opened

- rel/reltool.config
- version.mk
> Bump to 3.0.0

- src/fabric/src/fabric2_fdb.erl
- src/fabric/test/fabric2_doc_count_tests.erl
Do not decrement `doc_count` stat if document was previously missing, or if it
was already deleted.
Deleted documents could be brought in by replication. In that case, if there
were more replicated documents than the current `doc_count`, the `doc_count`
could even underflow the 64 bit unsigned integer range and end up somewhere in
the vicinity of 2^64. The counter, of course, would still be incorrect even if
it didn't underflow, the huge value would just make the issue more visible.
> Fix doc counts for replicated deletions

- test/elixir/test/replication_test.exs
We test that a newly deleted document is replicated to the target and it bumps
the deleted doc count but doesn't change doc count.
Another thing to test is that an already deleted document is replicated in
where its revision path was extended on the source then gets replicated to the
target. In that case neither del doc count not doc count are bumped.
> Add more deleted docs replication cases to integration test

- rebar.config.script
Update Fauxton to version 1.1.20
N/A
https://github.com/apache/couchdb/issues/2177
The checklist does not apply in this case.
> Update fauxton to version 1.1.20

- rebar.config.script
Update fauxton to version 1.2.0. This includes partitioned db and search support.
N/A
> Update fauxton to version 1.2.0

- src/couch_jobs/src/couch_jobs_fdb.erl
- src/fabric/src/fabric2_fdb.erl
- src/fabric/src/fabric2_txids.erl
It was suggested in another PR's discussion:
https://github.com/apache/couchdb/pull/2107#pullrequestreview-274431487
> DRY out CouchDB FDB prefix fetching

- src/chttpd/src/chttpd.erl
To trace FDB transactions:
1. Enable tracing in erlfdb application environment:
`network_options = [{trace_enable, ...}]`
OR with an environment variable:
`FDB_NETWORK_OPTION_TRACE_ENABLE = ""`
2. Set `[fabric] fdb_trace=true` configuration value
3. Add the `x-couchdb-fdb-trace:true` header to each request that should be
traced.
The transaction name is set to the nonce value, which is already used by
CouchDB to track API requests.
Only transactions started from the main request process will be traced. So if a
process is spawned without inheriting the `erlfdb_trace` process dict key, that
transaction will not be traced.
> Enable FDB transaction tracing

- rebar.config.script
* Detect dreyfus/hastings correctly
> update ken to 1.0.6

- src/couch_replicator/src/couch_replicator_scheduler.erl
When rescheduling jobs, make sure to stops existing job as much as needed to
make room for the pending jobs.
> Avoid churning replication jobs if there is enough room to run pending jobs

- test/elixir/test/map_test.exs
Add a test to show we can handle view swaps in fdb land
Test should pass
> add test to prove we can view swap

- src/couch_replicator/src/couch_replicator_docs.erl
- src/couch_replicator/test/eunit/couch_replicator_proxy_tests.erl
Previously if a proxy was specified it was used for both source and target
traffic. However, as mentioned in #2272, since both source and target now are
URLs, instead of one being a "local" database, it makes sense to allow separate
proxy settings for source and target endpoints.
We are still allowing an old style, single proxy setting. However, if users set
both the old style proxy and a per-endpoint one, an exception is raised about
the settings being mutually exclusive.
Fixes #2272
> Implement separate source and target replication proxies

- src/couch_replicator/src/couch_replicator_connection.erl
- src/couch_replicator/src/couch_replicator_httpc.erl
- src/couch_replicator/src/couch_replicator_httpc_pool.erl
> Include proxy host and port in connection pool key

- src/couch_views/src/couch_views.erl
If the view is already built, read the view status and view
in the same transaction. This will improve view read latency.
All current tests should pass
> Optimize view read latency when the view ready

- src/couch_views/src/couch_views_indexer.erl
- src/couch_views/src/couch_views_jobs.erl
- test/elixir/test/map_test.exs
If a map indexing job fails. Return the error back to any waiting requests and finish the job.
Tests should pass
> return indexing errors to request

- .credo.exs
- .gitignore
- Makefile
- Makefile.win
- mix.exs
- mix.lock
This PR adds coverage information to the results produced by ExUnit (when it is used as a unit testing framework). 
```
./configure
make exunit
firefox cover/excoveralls.html
```
N/A
> Exunit cover

- .travis.yml
> Log test failures on Travis

- src/couch/src/couch_db_split.erl
- src/couch/src/couch_server.erl
- src/couch/test/eunit/couch_db_split_tests.erl
- src/couch/test/eunit/couch_db_tests.erl
- src/mem3/test/eunit/mem3_reshard_test.erl
During the initial copy phase target shards are opened outside the
couch_server. Previously, it was possible to manually (via remsh for instance)
open the same targets via the couch_server by using the `couch_db:open/2` API
for example. That could lead to corruption as there would be two writers for
the same DB file.
In order to prevent such a scenario, introduce a mechanism for the shard
splitter to lock the target shards such that any regular open call would fail
during the initial copy phase.
The locking mechanism is generic and would allow local locking of shards for
possibly other reasons in the future as well.
`make eunit`
> Lock shard splitting targets during the initial copy phase

- src/setup/src/setup.erl
- src/setup/test/t-frontend-setup.sh
See https://github.com/apache/couchdb/issues/1752
> Feat/1752/setup UUID and auth secret

- src/chttpd/src/chttpd_auth_request.erl
- src/couch/include/couch_js_functions.hrl
> feat: add read-only _metrics role for _stats and _system endpoints

- rebar.config.script
See https://github.com/apache/couchdb-hqueue/pull/2
> bump hqueue dep for Windows build

- src/couch_replicator/src/couch_replicator_worker.erl
The `batch_doc(Doc)` code was previously used for local endpoints when flushing docs with attachments. After that code was removed, the [remote_doc_handler/2]( https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_worker.erl#L274 ) filters out all docs with attachments before they even get to the doc flusher so `batch_doc/1` effectively always returns `true`.
> Remove unused batching code from replicator

- test/javascript/run
- test/javascript/tests/design_docs.js
Adding debug logging for JavaScript test failures on Jenkins.
> Debug javascript test failures

- src/chttpd/test/eunit/chttpd_purge_tests.erl
> Fix chttpd_purge_tests.erl

- test/javascript/run
> Remove debug logging from test/javascript/run

- src/mem3/src/mem3_reshard_job.erl
- src/mem3/test/eunit/mem3_reshard_test.erl
Previously the target was reset only when the whole job started, but not when
the initial copy phase restarted on its own. If that happened, we left the
target around so the retry failed always with the `eexist` error.
Target reset has a check to make sure the shards are not in the global shard
map, in case someone manually added them, for example. If they are found there
the job panics and exists.
> When shard splitting make sure to reset the targets before any retries

- rel/overlay/etc/default.ini
Some rexi and reshard parameters
Issue: https://github.com/apache/couchdb/issues/2457
> Add a few missing settings to the default.ini file

- build-aux/Jenkinsfile.full
Minimal but it might help until #2437 is fixed.
> [Jenkins] Try to cleanup hung beam.smp (FreeBSD)

- build-aux/Jenkinsfile.full
Reopening #2453 with branch name that will also test the full build.
> Enable building on Power (ppc64le) architecture

- src/dreyfus/src/dreyfus_fabric_search.erl
> Fix misspelling in dreyfus

- rebar.config.script
Update couchdb-config to 2.1.7. 
This brings in fix for raising notification events on config reload from disk.
> Update couchdb-config to 2.1.7

- rel/overlay/etc/default.ini
Settings in `default.ini` should be the defaults. Also a little text cleanup for clarity.
> Fix ini file setting for #2296

- rel/files/couchdb.in
- rel/overlay/bin/remsh
this fixes the Mac binary build
> fix: allow spaces in startup paths

- Makefile
- src/mango/test/user_docs.py
> python-black style cleanup

- rebar.config.script
- src/couch/src/couch_util.erl
PR for updating our rebar.config.script dependencies.
`make check`
#2391
> Update dependencies for 3.0

- src/fabric/src/fabric2_fdb.erl
- src/mango/src/mango_indexer.erl
> Refactor mango indexer hook

- src/mango/README.md
- src/mango/TODO.md
- src/mango/test/README.md
Wrap lines to 80 chars and remove trailing whitespace
> Wrap lines to 80 chars and remove trailing whitespace

- rebar.config.script
- src/couch/test/eunit/couch_js_tests.erl
- test/javascript/tests/view_errors.js
Update jiffy to fix Windows and CentOS builds.
> Update jiffy 1.0.3

- src/mango/src/mango_idx.erl
- src/mango/test/01-index-crud-test.py
- src/mango/test/15-execution-stats-test.py
> Test improvements

- src/mango/rebar.config
- src/mango/src/mango_cursor_view.erl
- src/mango/src/mango_fdb.erl
- src/mango/src/mango_idx.erl
- src/mango/src/mango_indexer.erl
- src/mango/src/mango_jobs.erl
- src/mango/test/eunit/mango_indexer_test.erl
- src/mango/test/eunit/mango_jobs_indexer_test.erl
> Mango eunit test fixes

- src/mem3/src/mem3_sync.erl
- src/mem3/test/eunit/mem3_seeds_test.erl
This is a companion PR for the main 3.0.x one:
https://github.com/apache/couchdb/pull/2560
> Handle possibly missing local _users db in mem3_sync:local_dbs()

- rebar.config.script
Bump our documentation repository to include Windows installer improvements
> bump docs rev

- Makefile
- Makefile.win
Bring in Makefile from `master` with all the latest goodies
`$ make && make eunit apps=couch_jobs,couch_views,fabric` should still work
> Sync Makefile with master

- src/setup/src/setup.erl
> fix: single node state

- src/setup/src/setup.erl
Even 3.x up with 3.0.x changes
> fix: single node state (#2574)

- src/setup/src/setup.erl
- src/setup/src/setup_httpd.erl
Really fix #2557 
so sorry for getting the merge base wrong four times in a row
> Fix/single node status 3.0.x

- test/elixir/test/changes_async_test.exs
- test/elixir/test/changes_test.exs
- test/javascript/tests/changes.js
This PR ports the changes.js test suite into the elixir test suite which is already merged to master
> Port changes.js test suite into elixir (sync with master)

- rebar.config.script
> Bump to jiffy 1.0.4

- src/mem3/src/mem3_sync_event_listener.erl
> 3.x fix mem3 sync event listener test

- src/mem3/src/mem3_sync_event_listener.erl
> Fix mem3_sync_event_listener test

- README.rst
(mainly to test a new CI builder)
> doc: link README-DEV in README

- test/elixir/README.md
- test/elixir/test/form_submit_test.exs
- test/javascript/tests/form_submit.js
Ref.: picking https://github.com/apache/couchdb/pull/2608 commits and porting them to the `3.x` branch
> Port form submit test to elixir in 3.x branch

- build-aux/Jenkinsfile.full
> feat: add mac ci (#2622)

- build-aux/Jenkinsfile.full
> Jenkins mac 3.x

- src/couch_views/src/couch_views_jobs.erl
> Fix couch_views type in wait_for_job

- src/fabric/src/fabric2_sup.erl
Enable fdb feature
```
$ dev/run -a adm:pass -n 1
$ curl -u adm:pass -H 'Content-Type: application/json' localhost:15984 | jq .features
```
should include `fdb`
> Enable fdb feature

- src/couch_views/test/couch_views_indexer_test.erl
* Use the `row/3` helper function in a few more places
* Make a `run_query/3` function to shorten all the query calls
* A few minor emilio suggesions (whitespace, comma issues, ...)
```
$ ~/src/emilio/emilio src/couch_views/test/couch_views_indexer_test.erl
$ make eunit  apps=couch_views suites=couch_views_indexer_test
```
> Reformat and simplify couch_views_indexer_test module

- src/fabric/src/fabric2_fdb.erl
This PR adds additional sub spans for the get doc operations. In particular, it adds new spans so that the loading of the revs and the loading of the doc body in `fabric2_db:open_doc` are separated out into individual spans: https://github.com/apache/couchdb/blob/prototype/fdb-layer/src/fabric/src/fabric2_db.erl#L533-L539
> Add additional get_doc spans

- src/fabric/test/fabric2_doc_fold_tests.erl
Check that on a transaction restarts `database_does_not_exist` error is
thrown properly if database was re-created.
Also we forgot to properly unload the mocked erlfdb module in
`tx_too_old_mock_erlfdb/0` so we make sure to do that, otherwise it
has a chance of messing up subsequent tests.
See also: https://github.com/apache/couchdb/pull/2691#issuecomment-602110084
> Add a fabric doc fold test when db is re-created

- test/javascript/tests/design_docs_query.js
- test/javascript/tests/design_options.js
- test/javascript/tests/design_paths.js
- test/javascript/tests/erlang_views.js
- test/javascript/tests/form_submit.js
Fix ported to elixir tag 
Merging #2695 into 3.0.x
> Fix ported to elixir tag - 3.0.x

- test/javascript/tests/design_docs_query.js
- test/javascript/tests/design_options.js
- test/javascript/tests/design_paths.js
- test/javascript/tests/erlang_views.js
- test/javascript/tests/form_submit.js
Fix ported to elixir tag 
Merging #2695 into 3.x
> Fix ported to elixir tag - 3.x

- test/elixir/README.md
> Fix missing apexes in test/elixir/README.md

- test/elixir/README.md
- test/elixir/test/view_pagination_test.exs
- test/javascript/tests/view_pagination.js
Ported the `view_pagination.js` to Elixir test suite.
Just issue `make elixir` :-)
> Port view_pagination integration test to elixir test suite

- test/elixir/README.md
- test/elixir/test/view_pagination_test.exs
- test/javascript/tests/view_pagination.js
Backport of `view_pagination_test.exs` to `3.x` branch
Just issue `make elixir` or see the CI output
> Port view_pagination integration test to elixir test suite - 3.x

- test/elixir/README.md
- test/elixir/test/view_pagination_test.exs
- test/javascript/tests/view_pagination.js
Backport of `view_pagination_test.exs` to `3.0.x` branch
Just issue `make elixir` or see the CI output
> Port view_pagination integration test to elixir test suite - 3.0.x

- src/fabric/src/fabric2_events.erl
- src/fabric/test/fabric2_db_misc_tests.erl
* Avoid a cause clause error in `after 0` when the database is deleted
* Handle db re-creation by checking the instance UUID during `fabric2_db:open/2`
Since we added a few extra arguments switch to use a map as the `State`
> Improve fabric2_events

- src/couch/src/couch_server.erl
- src/couch_replicator/src/couch_replicator_scheduler.erl
- src/mem3/src/mem3_reshard.erl
Removes the following features from the welcome message:
- reshard
- partitioned
- pluggable-storage-engines
- access-ready
- scheduler
```
make check-fdb
```
> Don't advertise unimplemented features

- src/fabric/src/fabric2_util.erl
- test/elixir/test/all_docs_test.exs
Change `_all_docs` to do raw collation instead of view collation. 
`make check-fdb` should pass.
> All docs raw collation

- src/chttpd/src/chttpd_auth.erl
- src/chttpd/test/eunit/chttpd_auth_tests.erl
> Fix/up except 3.0.x

- src/chttpd/src/chttpd_auth.erl
- src/chttpd/test/eunit/chttpd_auth_tests.erl
> fix: require_valid_user exception logic

- rel/overlay/etc/default.ini
- src/couch/include/couch_eunit.hrl
- src/couch/src/couch_httpd_auth.erl
- src/couch/test/eunit/couchdb_cookie_domain_tests.erl
- src/fabric/src/fabric_rpc.erl
- src/fabric/test/eunit/fabric_rpc_tests.erl
- src/mem3/src/mem3_reshard_dbdoc.erl
- src/mem3/src/mem3_rpc.erl
- src/mem3/src/mem3_shards.erl
- src/mem3/src/mem3_util.erl
Backports of fixes from master.
> 3.0.x backports from master

- test/elixir/README.md
- test/elixir/lib/couch/db_test.ex
- test/elixir/test/view_offsets_test.exs
- test/javascript/tests/view_offsets.js
Just porting `view_offset_test.exs` test suite to `3.x` branch.
> Merge in 3.x: Port view_offset.js to elixir test suite

- test/elixir/test/cookie_auth_test.exs
Improve cookie_auth_test.exs initialization
Merge #2724 into 3.0.x
> Improve cookie_auth_test.exs initialization - 3.0.x

- test/elixir/test/cookie_auth_test.exs
Improve cookie_auth_test.exs initialization
Merge #2724 into 3.x
> Improve cookie_auth_test.exs initialization - 3.x

- src/couch_rate/src/couch_rate_limiter.erl
View updates can have batches with zero writes
> Fix couch rate limiter bug

- .gitignore
- rebar.config.script
- src/couch/.gitignore
- src/couch/rebar.config.script
This change allows creation of local `src/couch/rebar.config` and `rebar.config`
files to set additional configuration options. This is useful for:
- disabling deprecation warnings `{nowarn_deprecated_function, MFAs}`
- control debugging in eunit tests
- `DEBUG` - `{eunit_compile_opts, [{d, DEBUG, true}]}`
- `NODEBUG` - `{eunit_compile_opts, [{d, NODEBUG, true}]}`
Regression testing `./configure && make check apps=couch` should be enough.
Functionality testing:
- update `rebar.config.script` to print the final config term.
```
diff --git a/rebar.config.script b/rebar.config.script
index b3ea2c933..3a2687015 100644
--- a/rebar.config.script
+++ b/rebar.config.script
@@ -223,7 +223,7 @@ AddConfig = [
{post_hooks, [{compile, "escript support/build_js.escript"}]}
],
-lists:foldl(fun({K, V}, …
```
> Merge keys from rebar.config

- src/fabric/src/fabric2_db.erl
- src/fabric/src/fabric2_fdb.erl
- src/fabric/test/fabric2_db_misc_tests.erl
By default, transactions are used to check metadata, and possibly
reopen the db, to get a current db handle. However, if a `max_age`
option is provided and db handle was checked less than `max_age`
milliseconds ago, use properties from that cached handle instead.
The main use of this feature be in pluggable authorization handlers
where it might be necessary to inspect the security doc multiple times
for the same request before a final decision is made.
`revs_limit/1` was updated as well, mainly for consistency since it is
almost identical to `get_security/1`.
> Allow using cached security and revs_limit properties

- src/chttpd/src/chttpd_httpd_handlers.erl
Fix a typo in error message
N/A
N/A
> Fix typo in error message

- rebar.config.script
> Bump fauxton to v1.2.3 (#2515)

- src/mango/src/mango_selector.erl
- src/mango/test/21-empty-selector-tests.py
Cherry pick https://github.com/apache/couchdb/pull/2805.
> fix operator issue with empty arrays (#2805 cherry pick)

- src/mango/src/mango_idx.erl
> Fix mango test suite

- .gitignore
- build-aux/Jenkinsfile.full
Cherry pick fix to build 3.x packages on Focal.
> Add Ubuntu Focal (20.04) + SM68 to Jenkins

- rebar.config.script
> Bump docs, fauxton

- rebar.config.script
> bump docs, fauxton for 3.1.0

- test/javascript/cli_runner.js
This PR optimizes the time required to process each JS test tagged as skipped or ported to elixir. 
Previous to this PR before each JS test execution it is checked if CouchDB is running even if the test was tagged as skipped or ported. When a test is tagged as skipped or ported it should no be executed so the is running check is not required.
This PR cuts the test execution without checking if CouchDB is running improving the test suite execution time. In my dev host there is a gain of 30 secs.
```
make javascript
```
N/A
> Improve js test suite execution time

- test/javascript/cli_runner.js
Backport into 3.x - Improve js test suite execution time #2859
> Backport #2859 into 3.x - Improve js test suite execution time 

- src/couch_views/src/couch_views.erl
return correct not implemented for reduce
> return correct not implemented for reduce

- Makefile
- Makefile.win
- rebar.config.script
This PR enables ExUnit tests.
make check
- prerequisite PR https://github.com/apache/couchdb-erlfdb/pull/6
> Re-enable ExUnit tests

- src/fabric/test/fabric2_db_crud_tests.erl
- src/fabric/test/fabric2_dir_prefix_tests.erl
- src/fabric/test/fabric2_index_tests.erl
- src/fabric/test/fabric2_tx_options_tests.erl
Add some longer timeouts and fix a race condition in db cleanup tests
(Thanks to @jdoane for the patch)
> Fix a few flaky tests in fabric2_db

- src/fabric/src/fabric2_fdb.erl
Fix compiler warning.
```
make check
```
> Fix compiler warning

- src/couch_jobs/test/couch_jobs_tests.erl
Sometimes this test fails on Jenkins but doesn't fail locally. The attempted fix is to make sure to simply retry a few times for the number of children in the supervisor to be the expected values. Also extend the timeout to 15 seconds.
> Fix flaky couch_jobs type monitor test

- LICENSE
As per discussion on dev@ from Justin McLean, this was an incorrect "Happy new year" change.
Snuck in back in https://github.com/apache/couchdb/pull/1838 . tsk tsk @janl :wink:
> Fix license file

- src/couch_jobs/src/couch_jobs_activity_monitor.erl
> Fix wrong catch 1020 in couch jobs

- src/couch_jobs/src/couch_jobs.erl
And also against too many conflicts during overload
> Guard couch_jobs:accept_loop timing out

- src/couch_jobs/src/couch_jobs.erl
When waiting to accept jobs and scheduling was used, timeout is limited based on the time scheduling parameter. When no_schedule option is used, time scheduling parameter is set to 0 always, and so in that case, we have to  special-case the limit to return `infinity`.
Later on when we wait for the watch to fire, the actual timeout can still be limited, by a separate user specified timeout option, but if user specifies `infinity` there and sets `#{no_schedule => true}` then we should respect and  never return `{error, not_found}` in response.
> Fix couch_jobs accept timeout when no_schedule option is used

- test/elixir/README.md
- test/elixir/test/view_collation_raw_test.exs
- test/javascript/tests/view_collation_raw.js
This PR ports view_collation_raw.js test into the elixir test suite
```
make elixir tests=test/elixir/test/view_collation_raw_test.exs
```
N/A
> Port view_collation_raw.js into elixir test suite

- src/chttpd/test/exunit/pagination_test.exs
- src/couch_views/src/couch_views_http.erl
This PR extends pagination API with support for `previous` bookmark as per [RFC-014](https://github.com/apache/couchdb-documentation/pull/530)
```
```
*  [RFC-014](https://github.com/apache/couchdb-documentation/pull/530)
* https://github.com/apache/couchdb/pull/2870
> Add support for previous bookmark

- test/elixir/README.md
- test/elixir/test/view_sandboxing_test.exs
- test/javascript/tests/view_sandboxing.js
This PR ports view_sandboxing.js into elixir
```
make elixir tests=test/elixir/test/view_sandboxing_test.exs
```
N/A
> port view_sandboxing.js into elixir

- test/elixir/README.md
- test/elixir/test/update_documents_test.exs
- test/javascript/tests/update_documents.js
This PR ports the update_documents.js test into the Elixir test suite
```
make elixir tests=test/elixir/test/update_documents_test.exs
```
N/A
> Port update_documents.js into elixir test suite

- src/ebtree/src/ebtree.erl
the Order parameter to open is only used if the ebtree does not yet exist, otherwise we proceed with the stored order.
N/A
> Use stored order without complaint

- src/ebtree/src/ebtree.erl
Pass fdb key to the encode_fun
This commit also removes the get/wait/future split as it made it much
harder to pass the fdb key down. Since those functions only call each
other, there is no loss of functionality.
> Pass fdb key to the encode_fun

- src/ebtree/src/ebtree.erl
This removes spurious conflicts and allows concurrent writing to
non-overlapping parts of the tree.
run the test suite
> Only call erlfdb:set if the node changes

- test/elixir/test/replication_test.exs
After _active_tasks was implemented on FDB, single-node (previous) _active_tasks implementation, had stopped working. It turns out were were relying on it to run Elixir replication tests.
To not lose test coverage, and before we implement replicator on FDB, switch the tests to use `_scheduler/jobs`.
> Use _scheduler/jobs instead of _active_tasks in replication Elixir tests

- src/ebtree/src/ebtree.erl
Fix another case of relying on erlang term comparison where we shouldn't.
N/A
N/A
> Call collate for group equality

- src/ebtree/src/ebtree.erl
> Ebtree fixes

- src/ebtree/src/ebtree.erl
I removed the "intense" test as we're now confident in the basic design, and the non intense tests verify the functionality just as completely. I reduced the number of k/v's in other tests as well. test coverage remains at 94% before and after.
run the tests :P
N/A
> Speed up ebtree test suite without losing coverage

- src/couch_index/src/couch_index_server.erl
This should prevent unexpected exit messages arriving which crash
couch_index_server.
Patch suggested by davisp.
Closes #3061.
Under high query load with ddoc deletes, observe that couch_index_server does not terminate.
N/A
> Unlink index pid and swallow EXIT message if present

- src/couch_index/src/couch_index_server.erl
If a ddoc is added immediately after database creation (_users and
_replicator when couchdb is used in a multi-tenant fashion), we can
crash couch_index_server in handle_db_event, as mem3_shards:local
throws an error.
Create new $prefix/_replicator ddocs while under heavy indexing load elsewhere and observe a crash without this patch, and no crash with it.
#3068
> Don't crash couch_index_server if the db isn't known yet

- src/couch_rate/src/couch_rate_limiter.erl
Fixes the case where no writes are done for an index, the rater limiter
assumed it was a failure.
> Add has_failure for couch_rate_limiter

- src/couch/rebar.config.script
When building couch_js in RHEL, there is one error occurring with "undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'". This commit is to adjust binding library to address this issue.
```
Compiling priv/couch_ejson_compare/couch_ejson_compare.c
/usr/bin/ld: priv/couch_js/60/main.o: undefined reference to symbol '_ZTVN10__cxxabiv117__class_type_infoE@@CXXABI_1.3'
//usr/lib64/libstdc++.so.6: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
ERROR: sh(cc priv/couch_js/60/http.o priv/couch_js/60/main.o priv/couch_js/60/utf8.o priv/couch_js/60/util.o -L/usr/local/lib -std=c++14 -lmozjs-60 -lm   -L"/usr/local/lib/erlang/lib/erl_interface-3.10.2.2/lib" -lerl_interface -lei -o priv/couchjs)
failed with return code 1 and …
```
> fixup: Build couch_js for redhat linux

- src/chttpd/src/chttpd.erl
> Don't log client disconnects

- src/aegis/src/aegis_server.erl
Clear sensitive flag at end of public api functions
In a remsh, call one of these functions, then verify the sensitive process flag is not set.
N/A
> Clear sensitive flag at end of public api functions

- dev/run
Backport of  3004513c12592b19b5b77a6edcfdef5f4450716d
> update dev/run formatting to adhere to python format checks

- src/dreyfus/src/dreyfus_httpd.erl
- src/dreyfus/test/elixir/test/partition_search_test.exs
This is a backport of `master`'s 6659dbbd7c556b8dc00c075e331d7b106d44088d to `3.x`.
> Make restricted partition search return bad request

- src/couch_mrview/src/couch_mrview_util.erl
- src/mango/src/mango_cursor_view.erl
- test/elixir/test/partition_mango_test.exs
Backports:
https://github.com/apache/couchdb/pull/3105
> bypass partition query limit for mango

- src/fabric/src/fabric2_db.erl
- src/fabric/test/fabric2_doc_crud_tests.erl
This makes it compatible with CouchDB <= 3.x where we can create deleted
documents.
How to check:
```
$ http put $DB1/mydb
$ http put $DB1/mydb/foo _deleted:='true' a=b
{
"id": "foo",
"ok": true,
"rev": "1-ad7eb689fcae75e7a7edb57dc1f30939"
}
```
> Allow creating new deleted documents

- src/couch_replicator/src/couch_replicator.erl
Previously there was an error thrown which prevented emitting _scheduler/docs responses. Instead of throwing an error, return `null` if the URL cannot be parsed.
> Handle malformed URLs when stripping URL creds in couch_replicator

- rel/reltool.config
- version.mk
> bump version to 3.1.1

- src/couch_views/test/couch_views_active_tasks_test.erl
Fix flaky couch_views_active_tasks_test
`make check`
> Fix flaky active tasks test

- src/chttpd/src/chttpd.erl
- src/chttpd/test/eunit/chttpd_delayed_test.erl
We need to call StartFun as it might add headers, etc.
> Fix buffer_response=true (#3145)

- src/couch_replicator/src/couch_replicator.erl
Previously, in 3.x, we used to re-parse the endpoint URLs with `ibrowse_lib:parse_url/1` which threw an error if the URL was invalid. So we try to preserve that same logic.
Backport some tests from 3.x to make sure URL stripping works when URL is valid and also use the nicer `?TDEF` and `?TDEF_FE` test helpers.
> Add url validation in replicator creds stripping logic

- src/couch_replicator/test/eunit/couch_replicator_job_server_tests.erl
Job exits are asynchronous so we ensure we wait for exit signals to be handled before checking the state.
> Fix flaky couch_replicator_job_server tests

- src/couch_views/src/couch_views_batch_impl.erl
> Fix couch views batch impl

- src/chttpd/src/chttpd_node.erl
This PR addresses issue #3160 for the `main` branch, and has a companion PR for the 3.x branch: https://github.com/apache/couchdb/pull/3161.
> 3160 main fix run queue metric

- rel/overlay/etc/default.ini
- src/couch/src/couch_query_servers.erl
- src/couch_views/include/couch_views.hrl
- src/couch_views/src/couch_views.erl
- src/couch_views/src/couch_views_fdb.erl
- src/couch_views/src/couch_views_indexer.erl
- src/couch_views/src/couch_views_reader.erl
- src/couch_views/src/couch_views_trees.erl
- src/couch_views/src/couch_views_updater.erl
- src/couch_views/src/couch_views_util.erl
- src/couch_views/test/couch_views_cleanup_test.erl
- src/couch_views/test/couch_views_indexer_test.erl
- src/couch_views/test/couch_views_red_test.erl
- src/couch_views/test/couch_views_size_test.erl
- src/couch_views/test/couch_views_updater_test.erl
- src/couch_views/test/couch_views_upgrade_test.erl
- src/fabric/src/fabric2_fdb.erl
- src/mango/src/mango_cursor_view.erl
- src/mango/src/mango_idx_view.erl
- src/mango/src/mango_idx_view.hrl
- test/elixir/test/reduce_builtin_group_level_tests.exs
Full map/reduce implementation using ebtree's
`make check`
These are a few other attempts at reduce functions with various tradeoffs and limitations.
#2456
#2984 
#3018
> Feature ebtree views

- test/elixir/README.md
- test/elixir/test/list_views_test.exs
- test/elixir/test/show_documents_test.exs
- test/javascript/tests/list_views.js
- test/javascript/tests/show_documents.js
This PR ports show_documents,js and list_views.js to the Elixir test suite
```
make elixir
```
N/A
> Port show_documents and list_views to Elixir

- README.rst
- build-aux/Jenkinsfile.pr
* Restore SM v60 flag for configure in PR builds
* s/master/main for README.md badge
> Fixes to CI process for main branch

- INSTALL.Unix.md
Backport of main, minor tweaks
> minor INSTALL.Unix.md patches (#2536)

- src/couch_replicator/src/couch_replicator_httpc.erl
Previously we subtly relied on one set of headers being sorted, then sorted the other set of headers, and ran `lists:ukeymerge/3`. That function, however, needs both arguments to be sorted in order for it to work as expected. If one argument wasn't sorted we could get duplicate headers easily, which is what was observed in testing.
A better fix than just sorting both sets of keys, is to use an actual header processing library to combine them so we can account for case insensitivity as well.
> Properly combine base and extra headers when making replicator requests

- src/couch_mrview/src/couch_mrview_http.erl
- test/elixir/test/all_docs_test.exs
- test/elixir/test/view_test.exs
> Fix boolean POST to view-like endpoints

- rebar.config.script
> update to latest fauxton 1.2.6

- src/couch_views/src/couch_views_trees.erl
This just enables the same aegis layer for database data for views.
`make check`
> Allow administrators to optionally encrypt views

- src/couch/src/couch_query_servers.erl
- src/couch/test/eunit/couch_query_servers_tests.erl
A document with lots of conflicts can blow up couchjs if the user
calls _changes with a javascript filter and with `style=all_docs` as
this option causes up to fetch all the conflicts.
All leaf revisions of the document are then passed in a single call to
ddoc_prompt, which can fail if there's a lot of them.
In that event, we simply try them sequentially and assemble the
response from each call.
Covered by unit test, but manual test as follows;
You need to create a highly conflicted document and lower couchjs's memory allowance for a practical test. Here's how I did it;
1) edit dev/run;
```
-    qs_javascript = toposixpath("%s %s" % (couchjs, mainjs))
+    qs_javascript = toposixpath("%s -S 1048576 %s" % (couchjs, mainjs))
```
2) create a filter;
```
curl …
```
> Retry filter_docs sequentially if the patch exceeds couchjs stack

- src/couch_mrview/src/couch_mrview_index.erl
merged to 3.x for https://github.com/apache/couchdb/pull/2558
> Reset if we don't get a view header

- src/mango/src/mango_selector.erl
- src/mango/test/03-operator-test.py
Merged to 3.x for https://github.com/apache/couchdb/pull/3041
> added $keyMapMatch Mango operator

- src/mango/test/06-basic-text-test.py
- src/mango/test/mango.py
Update mango tests.
Remove unnecessary parameters and disable test for not implemented feature.
1. Start couchdb instance `dev/run --admin=adm:pass --no-join`
2. Setup venv
```
cd src/mango
python3 -m venv venv
. venv/bin/activate
pip3 install -r requirements.txt
```
3. Run mango tests
```
venv/bin/nosetests
```
> Fix mango tests

- src/couch/src/couch_query_servers.erl
- src/couch/test/eunit/couchdb_os_proc_pool.erl
Previously, if an error was thrown in a `with_ddoc_proc/2` callback, the process was still returned to the process pool in the `after` clause. However, in some cases, for example when processing a `_list` response, the process might
end up stuck in a bad state state, such that it could not be re-used anymore. In such a case, a subsequent user of that `couch_js` process would end up throwing an error and crashing.
Fixes #2962
> Do not return broken processes to the query process pool

- .gitignore
- Makefile
- dev/boot_node.erl
- dev/make_boot_script
- dev/monitor_parent.erl
- dev/run
Same as #3337 but for main instead of 3.x.
> Simplify and speedup dev node startup (main branch)

- README.rst
Fixing links after branch renaming (master -> main).
Nothing to test, no code change.
> fixing links after master->main branch rename

- INSTALL.Unix.md
- src/couch_replicator/README.md
- src/ctrace/README.md
Fixing additional links after branch renaming (master -> main)
Nothing, no code change
> fix additional links after branch renaming (master -> main)

- src/couch/src/couch_server.erl
Preserve max_dbs_open division during config change
change the couchdb max_dbs_open property and verify that each couch_server_X process only gets 1/num_servers() of it.
N/A
> Preserve max_dbs_open division during config change

- test/elixir/test/basics_test.exs
Depending on the situation, the session context may have elements other than `_admin`. This PR relaxes the check to make the test case more robust.
> Make session elixir test more robust

- src/couch_views/src/couch_views_indexer.erl
Previously, when an erlfdb error occured and a recursive call to `update/3` was made, the result of that call was always matched against `{Mrst, State}`. However, in the case when the call had finalized and returned the `couch_eval:release_map_context/1` response, the result would be `ok` which would blow with a `badmatch` error against `{Mrst, State}`.
> Fix badmatch in couch_views_indexer

- test/elixir/test/bulk_docs_test.exs
- test/elixir/test/config/suite.elixir
https://github.com/apache/couchdb/pull/3355 removed a test case. This PR re-adds it slightly changed so that it reflects the current functionality.
`mix test --trace test/elixir/test/bulk_docs_test.exs:134`
> Re-add transaction size exceeded test

- src/couch_jobs/test/couch_jobs_tests.erl
The errors see in #3417 seem to indicate the expiration jobs are interfering with the couch_jobs tests, to prevent that prevent expiration_db job gen_server from starting at all.
Fixes #3417
> Fix more couch_jobs flakiness

- src/jwtf/src/jwtf.erl
- src/jwtf/test/jwtf_keystore_tests.erl
Port JWTF fixes from 3.x
- https://github.com/apache/couchdb/commit/b3cc40e690addf50602d26ef28b74a16c04f5932
- https://github.com/apache/couchdb/commit/331894a6acb4565c71d800f2e63206101dfbb48c
```
make eunit apps=jwtf
```
> Port JWTF fixes from 3.x

- src/chttpd/src/chttpd_changes.erl
- test/elixir/test/config/skip.elixir
`_changes?filter=_design` was returning a 
```
{
"error": "unknown_error",
"reason": "function_clause",
"ref": 240731020
}
```
This PR fixes that and re-enabled the related elixir test.
`mix test --trace test/elixir/test/changes_test.exs:220`
> Fix _changes?filter=_design

- src/couch/priv/couch_js/86/help.h
- src/couch/priv/couch_js/86/main.cpp
- src/couch/priv/couch_js/86/util.cpp
- src/couch/priv/couch_js/86/util.h
- src/couch/rebar.config.script
- support/build_js.escript
port of #3421 from `3.x` to `main`
> feat(couchjs): add support for SpiderMonkey 86

- test/elixir/test/config/skip.elixir
- test/elixir/test/config_test.exs
Some general cleanup and making sure we check for a config entry that always exists by default.
> Refactor config_test.exs

- src/couch_jobs/src/couch_jobs_type_monitor.erl
This continues improvements to retryable error handling started in https://github.com/apache/couchdb/pull/3460. Here we add the same logic we already have for the `erlfdb:wait/2` call in [loop function](https://github.com/apache/couchdb/blob/main/src/couch_jobs/src/couch_jobs_type_monitor.erl#L55-L57)  to the `get_vs_and_watch/1` section.
`couch_jobs_type_monitor` is meant to be linked to and run in a continuous loop as long as the parent process is alive. If FDB becomes unavailable the main process which we linked to or other main component (the whole application) should crash and fail as opposed to the type monitor itself. Still, to avoid running in a tight loop we use the holdoff interval to sleep a bit before recursing. The typical values of the holdoff is around 50-100 msec.
> Retryable error fixes in couch_jobs_type_monitor

- rebar.config.script
To bring in a future `timeout` fix:
* https://github.com/apache/couchdb-erlfdb/commit/55022a566df3d98a543148ce7a0e2eb6773909ae
> Bump erlfdb to v1.3.3

- src/couch/rebar.config.script
- src/couch/test/eunit/couch_js_tests.erl
- support/build_js.escript
Good to go, got the failing test fixed. Closes #3476 
/cc @janl @dch @davisp
> [3.x] Add support for Spidermonkey 78

- src/couch/rebar.config.script
- src/couch/test/eunit/couch_js_tests.erl
- support/build_js.escript
Port of #3500 to main. Pre-approved...
> Add support for Spidermonkey 78

- build-aux/Jenkinsfile.full
- build-aux/Jenkinsfile.pr
This is the `main` cherry-pick for #3508 .
> Add docker creds to CI run (c.f. #3508)

- rel/overlay/etc/default.ini
- src/couch/src/couch_users_db.erl
- test/elixir/test/users_db_test.exs
This pull request adds a new setting for password requirements.
Closes #2951.
A user should not be able to change their password, if it does not
match the requirements set by the admin.
> password requirement

- build-aux/Jenkinsfile.full
- build-aux/Jenkinsfile.pr
- build-aux/show-test-results.py
This is cherry-pick of #3504 and #3505 to main as discussed in https://github.com/apache/couchdb/issues/3115#issuecomment-819059556
> Jenkins main new containers

- build-aux/show-test-results.py
This a cherry-pick from `main`
> Switch show-test-results.py to use python 3

- build-aux/logfile-uploader.py
https://ci-couchdb.apache.org/job/jenkins-cm1/job/PullRequests/job/PR-3541/1/ was failing with an unrelated `python-black` failure. This PR fixes the issue. The diff is produced by `make python-black-update`
https://github.com/apache/couchdb/pull/3541
> Reformat build-aux/logfile-uploader.py

- rel/overlay/etc/default.ini
- src/fabric/src/fabric2_users_db.erl
- test/elixir/test/config/skip.elixir
- test/elixir/test/users_db_test.exs
This pull request ports #3483 to `main`.
It also append its test to the skip-list.
Once the users db is fully re-implemented, remove the `users password requirements` test in `test/elixir/test/config/skip.elixir`.
This closes #2951 and is a port of #3483.
> Password requirement port

- src/couch_replicator/src/couch_replicator_auth_session.erl
This is a port of the 3.x PR https://github.com/apache/couchdb/pull/3541
> Fix bug in Replicator authentication for password contains @

- src/couch/src/couch_query_servers.erl
- test/elixir/test/basics_test.exs
> Delete unused variables

- rebar.config.script
Upgrade random -> rand
https://github.com/apache/couchdb-hyper/releases/tag/CouchDB-2.2.0-7
> Bump hyper dependency to 2.2.0-7

- rel/overlay/etc/default.ini
Forgot to add this to https://github.com/apache/couchdb/pull/3588
> Document aegis.cache_deletion_grace_sec

- rel/overlay/etc/default.ini
- src/smoosh/src/smoosh_server.erl
As discussed in #3047 and #3019.
> Improve smoosh defaults for slack channel

- rebar.config.script
- rel/overlay/etc/default.ini
- src/chttpd/src/chttpd.erl
- src/chttpd/src/chttpd_db.erl
- src/chttpd/src/chttpd_misc.erl
- src/chttpd/src/chttpd_prefer_header.erl
- src/chttpd/src/chttpd_sup.erl
- src/chttpd/test/eunit/chttpd_util_test.erl
- src/couch/src/couch_db.erl
- src/couch/src/couch_doc.erl
- src/couch/src/couch_httpd.erl
- src/couch/src/couch_httpd_misc_handlers.erl
- src/couch/src/couch_proc_manager.erl
- src/couch/src/couch_query_servers.erl
- src/couch/src/couch_server.erl
- src/couch/src/couch_uuids.erl
- src/couch/test/eunit/couch_doc_json_tests.erl
- src/couch_replicator/src/couch_replicator_docs.erl
- src/couch_replicator/src/couch_replicator_ids.erl
- src/couch_replicator/test/eunit/couch_replicator_create_target_with_options_tests.erl
- src/custodian/src/custodian_util.erl
- src/fabric/src/fabric_doc_attachments.erl
- src/fabric/src/fabric_doc_atts.erl
- src/ioq/src/ioq.erl
- src/mem3/src/mem3.erl
- src/mem3/src/mem3_util.erl
- src/mem3/test/eunit/mem3_util_test.erl
- src/setup/src/setup_httpd.erl
- test/elixir/test/config_test.exs
Normalize some configuration options to comment out the default.ini file.
fixes #3473
> Normalize some config options

- src/couch_replicator/src/couch_replicator_api_wrap.erl
- src/couch_replicator/test/eunit/couch_replicator_proxy_tests.erl
This is a port of the 3.x PR https://github.com/apache/couchdb/pull/3634 to main
> Use correct socks5 proxy ibrowse options

- build-aux/Jenkinsfile.full
Bring back ppc64le builds
s390x seems to fail, possibly related to mozjs60 so skip it for now. Also
FoundationDB doesn't build on either architecture.
> 3.x build on ppc64le

- configure
- dev/run
- rebar.config.script
- rel/overlay/etc/default.ini
- rel/reltool.config
- setup_eunit.template
- src/chttpd/src/chttpd_node.erl
- src/couch/src/couch.app.src
- src/couch_prometheus/src/couch_prometheus.app.src
- src/couch_prometheus/src/couch_prometheus.hrl
- src/couch_prometheus/src/couch_prometheus_app.erl
- src/couch_prometheus/src/couch_prometheus_http.erl
- src/couch_prometheus/src/couch_prometheus_server.erl
- src/couch_prometheus/src/couch_prometheus_sup.erl
- src/couch_prometheus/src/couch_prometheus_util.erl
- src/couch_prometheus/test/eunit/couch_prometheus_e2e_tests.erl
- src/couch_prometheus/test/eunit/couch_prometheus_util_tests.erl
This is a port of https://github.com/apache/couchdb/pull/3416.
> Port prometheus 3.x

- rebar.config.script
- src/chttpd/src/chttpd_node.erl
- src/couch/rebar.config.script
- src/couch/src/couch_server.erl
> report Erlang and JS version in welcome message

- test/elixir/lib/step/create_db.ex
- test/elixir/lib/step/user.ex
- test/elixir/lib/utils.ex
This eliminates several warnings when running `make exunit`.
```
make exunit
```
> Use correct fabric function names in elixir tests

- rebar.config.script
This PR bumps the mochiweb version to include the new `unquote_path/1` function.
N/A
Improve handling of + in URLs: https://github.com/apache/couchdb/pull/3638
> Bump mochiweb version

- dev/run
> Fix dev/run -n > five

- src/chttpd/test/exunit/pagination_test.exs
Replace couch_js with js_engine in exunit pagination test.
See: https://github.com/apache/couchdb/commit/3907e9f0abd2bfc26e8384a819939ea964daf157
```
make exunit
```
> Replace couch_js with js_engine in exunit pagination test

- src/chttpd/test/exunit/pagination_test.exs
- src/chttpd/test/exunit/tracing_test.exs
Suppress compiler warnings
```
make exunit
```
> Suppress compiler warnings

- src/chttpd/test/exunit/test_helper.exs
- src/couch/test/exunit/test_helper.exs
Suppress excessive debug logging of the form:
```
mix test --cover --trace src/chttpd/test/exunit/pagination_test.exs:232
* test Legacy API (10 docs) : _all_docs/queries
12:40:01.895 [debug] [user: "adm", what: :login_attempt]
12:40:01.906 [debug] [username: 'adm', what: :successful_cookie_auth]
12:40:01.925 [debug] [username: 'adm', what: :successful_cookie_auth]
12:40:01.934 [debug] [username: 'adm', what: :successful_cookie_auth]
12:40:01.944 [debug] [username: 'adm', what: :successful_cookie_auth]
12:40:01.952 [debug] [username: 'adm', what: :successful_cookie_auth]
12:40:01.960 [debug] [username: 'adm', what: :successful_cookie_auth]
12:40:01.968 [debug] [username: 'adm', what: :successful_cookie_auth]
12:40:01.977 [debug] [username: 'adm', what: :successful_cookie_auth]
12:40:01.985 …
```
> Set structured logger to info level for exunit tests

- src/fabric/src/fabric_view_map.erl
- test/elixir/test/view_multi_key_design_test.exs
Results should now be returned in descending {key, doc_id} order.
The idea is to reverse the key list before sending it to the workers, so they will emit rows in reverse order. Also, using the same reversed list when building the KeyDict structure on the coordinator. That way the order of the
sent rows and the expected coordinator sorting order will match.
For testing, enhance an existing multi-key Elixir view test to test both ascending and descending cases.
> Properly sort descending=true view results when a key list is provided

- rebar.config.script
> Bump docs dependency for the 3.1.2 release

- rebar.config.script
To include another changelog entry: https://github.com/apache/couchdb-documentation/commit/4f00da0b0cedf63ebf391e43b1a56bb36f7d0f96
> Bump docs for 3.2.0-RC2

- src/couch/src/couch_httpd_auth.erl
- src/setup/src/setup.erl
> fix(setup): straggling s/couch_httpd_auth/chttpd_auth/

- src/chttpd/src/chttpd_auth_request.erl
> feat(prometheus): allow users with _metrics role to read

- src/weatherreport/src/weatherreport_node.erl
The arity 0 version does not exist.
Fixes dialyzer warning:
```
{warn_callgraph,{"src/weatherreport_node.erl",126},
{call_to_missing,[weatherreport_check_nodes_connected,check,
0]}}
```
```
make check
```
> Use `weatherreport_check_nodes_connected:check/1`

- src/chttpd/src/chttpd_db.erl
- src/chttpd/test/eunit/chttpd_db_test.erl
Use `_bulk_docs` with "new_edits": false and without `_rev` should respond with 400 Bad Request instead of 500 Server Error.
When "new_edits": false, the request should always include revision info as `_rev` or `_revisions`
**Ref:**
[1] https://docs.couchdb.org/en/stable/api/document/common.html?highlight=%20use%20only%20by%20the%20replicato#put--db-docid
[2] https://docs.couchdb.org/en/stable/api/database/bulk-api.html?highlight=bulk_docs#db-bulk-docs
`make eunit apps=chttpd suites=chttpd_db_test`
**Manual testing:**
If any document does not have `_rev`, will raise **400 Bad Request**.
```
$ curl -X DELETE $DB/demo; curl -X PUT $DB/demo
$ curl -X POST $DB/demo/_bulk_docs \
-H 'Content-Type: application/json' \
-d '{
"docs": [{"_id": "FishStew", "_rev": "1-1", "value": 1},
{"_id": …
```
> _bulk_docs and new_edits: false should provide revision info

- test/elixir/test/replication_test.exs
- test/elixir/test/utf8_test.exs
- test/elixir/test/view_offsets_test.exs
Eliminates the following:
```
warning: variable "epoch" is unused (if the variable is not meant to be used, prefix it with an underscore)
src/couchdb/test/elixir/test/replication_test.exs:1756: ReplicationTest.seq_to_shards/1
warning: variable "uuid" is unused (if the variable is not meant to be used, prefix it with an underscore)
src/couchdb/test/elixir/test/replication_test.exs:1756: ReplicationTest.seq_to_shards/1
warning: variable "string" is unused (if the variable is not meant to be used, prefix it with an underscore)
src/couchdb/test/elixir/test/utf8_test.exs:32: UTF8Test."test UTF8 support"/1
warning: variable "repeated_view_offset_test_fun" does not exist and is being expanded to "repeated_view_offset_test_fun()", please use parentheses to remove the ambiguity or change the …
```
> Eliminate elixir test compiler warnings

- erlang_ls.config
This fixes some of the include issues.
> improve erlang_ls.config

- src/couch/src/couch_httpd_auth.erl
Send all the cookie attributes whenever we send a cookie. Only the value of AuthSession varies.
Configure the same-site and/or domain attribute in the nodes config.
1) Acquire a session cookie successfully then log out. Confirm AuthSession is the empty string.
2) Acquire a session cookie successfully then attempt to acquire a session cookie with the wrong password. Confirm AuthSession is the empty string.
> Always send all cookie attributes

- Makefile.win
- configure.ps1
- rebar.config.script
- src/ebtree/rebar.config
This PR is updates/ports relating to building on windows.
Regular CI checks on windows should show no regressins. For windows, building is more tricky, I am currently using this workflow:
https://github.com/lostnet/couchdb-glazier/blob/main/.github/workflows/ci.yml
#3873
> Add rebar3 and erlfmt install commands to configure.ps1 #3873

- src/jwtf/src/jwtf.erl
Currently, `decode/3` performs various checks on a JWT, and then
base64 decodes and finally JSON decodes the token. However, in some
cases, it's desirable to skip the decoding steps, and just return the
token payload in binary form.
This exposes `decode/4` where the 4th argument is a decoder fun that
defaults to `decode_b64url_json/1` for `decode/3` to retain existing
behavior, but also exposes `decode_passthrough/1` in case a client
wants to avoid any decoding steps.
```
make check
```
> Expose `decode/4` to skip decoding steps

- build-aux/Jenkinsfile.full
Remove Ubuntu Xenial from the CI matrix as discussed on the ML.
> Remove support for Ubuntu 16.04

- dev/format_all.py
- dev/format_check.py
- dev/format_lib.py
- src/chttpd/src/chttpd_changes.erl
- src/chttpd/src/chttpd_db.erl
- src/chttpd/test/eunit/chttpd_cors_test.erl
- src/couch/src/couch_httpd_auth.erl
- src/couch_eval/src/couch_eval.erl
- src/couch_replicator/src/couch_replicator_api_wrap.erl
- src/couch_replicator/test/eunit/couch_replicator_filtered_tests.erl
- src/couch_replicator/test/eunit/couch_replicator_retain_stats_between_job_runs.erl
- src/couch_views/src/couch_views_batch_impl.erl
- src/fabric/src/fabric2_db.erl
- src/fabric/src/fabric2_fdb.erl
- src/fabric/src/fabric2_server.erl
This is stacked on top of #3905. It applies @nickva 's enhancements to erlfmt from #3837 and then commits the new formatting suggestions that popped up once the new config was in place.
Jenkins
> Port erlfmt improvements and apply formatting suggestions

- src/chttpd/src/chttpd_misc.erl
If a design document exists in shards db, GET `_dbs_info` will throw a `time out` error. 
`make eunit apps=chttpd suites=chttpd_dbs_info_test`
https://github.com/apache/couchdb/pull/3832
> Fix corner case for GET `_dbs_info`

- src/ddoc_cache/test/eunit/ddoc_cache_tutil.erl
- src/fabric/test/eunit/fabric_db_create_tests.erl
- src/fabric/test/eunit/fabric_rpc_tests.erl
Clear junk test dbs before running chttpd_dbs_info_tests to avoid flaky errors.
`make eunit`
https://github.com/apache/couchdb/pull/3832
> Clear junk test dbs before running chttpd_dbs_info_tests

- build-aux/Jenkinsfile.full
Clean cherry-pick of 6594045 from #3925
> Fix publication of nightly packages

- README.rst
> Use https as default protocol for links

- src/couch/test/eunit/couchdb_views_tests.erl
Couldn't reproduce flakiness locally but it failed in CI at least twice.
Try to extend the wait timeout and poll frequency, and set `commit_freq = 0` for some tests.
Thanks to @noahshaw11 for pointing out the issue
> Fix flaky collator auto-upgrade test

- .gitignore
- src/couch/src/test_util.erl
- src/smoosh/rebar.config
Make it simpler to add a `rebar.config` file in applications, and enable smoosh eunit test coverage via `rebar.config` file.
```
make eunit apps=smoosh
```
> Smoosh eunit coverage

- src/ddoc_cache/src/ddoc_cache_lru.erl
Current implementation of `ddoc_cache_lru:remove_key/2` assumes that
lookups always return values, but these log entries beg to differ:
```
[error] 2021-12-10T02:25:21.622743Z node1@127.0.0.1 <0.18923.9> -------- gen_server ddoc_cache_lru terminated with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:308) <= ddoc_cache_lru:handle_info/2(line:219) <= gen_server:try_dispatch/4(line:637) <= gen_server:handle_msg/6(line:711) <= proc_lib:init_p_do_apply/3(line:249)
[error] 2021-12-10T02:25:21.623418Z node1@127.0.0.1 <0.18923.9> -------- CRASH REPORT Process ddoc_cache_lru (<0.18923.9>) with 0 neighbors crashed with reason: no match of right hand value not_found at ddoc_cache_lru:remove_key/2(line:308) <= ddoc_cache_lru:handle_info/2(line:219) <= …
```
> Handle `not_found` lookups removing ddoc cache key

- rel/overlay/etc/default.ini
- src/couch/src/couch_bt_engine.erl
- src/couch/src/couch_db_updater.erl
- src/smoosh/src/smoosh_channel.erl
- src/smoosh/src/smoosh_priority_queue.erl
- src/smoosh/src/smoosh_server.erl
- src/smoosh/src/smoosh_utils.erl
Create new config options in `couchdb` and `smoosh` sections to enable
finer control of compaction logging levels.
```
make check
```
> Configurable compaction log levels

- dev/remsh
- dev/remsh-tls
- rel/overlay/bin/remsh
- rel/overlay/etc/vm.args
- rel/reltool.config
- src/couch/src/couch_sup.erl
- src/weatherreport/src/weatherreport_node.erl
- version.mk
Merge 3.2.2 release fixes into 3.x
> Merge 3.2.x to 3.x

- rebar.config.script
Waiting on https://github.com/mochi/mochiweb/pull/242
> Revert mochiweb update until the next release

- src/fabric/src/fabric_doc_update.erl
Previously when handling mismatched responses for replicated changes, where some response were `noreply` and some were `forbidden`, the `{DocID, Rev}` tuple was dropped from the response, which resulted in `update_doc_result_to_json` failing as it expects an `{{DocId, Rev}, Error}` argument instead of just `Error`.
Make sure to keep and return the reply as is in `check_forbidden_msg/1`.
> Fix function_clause error for replicated changes with a target VDU

- rebar.config.script
https://github.com/mochi/mochiweb/releases/tag/v3.0.0
> Bump mochiweb to 3.0

- src/couch/src/couch_debug.erl
Implement `couch_debug:memory_info/1` to facilitate memory leak detections.
> Implement memory_info functions

- src/couch/src/couch_debug.erl
Fix `busy` functions to work with pids.
> Fix busy functions to work with pids

- src/couch/src/couch_debug.erl
Implement `resource_hoggers` to facilitate memory leak detections.
> Implement resource_hoggers

- src/fabric/src/fabric.erl
- src/smoosh/src/smoosh_server.erl
- src/smoosh/src/smoosh_utils.erl
Continuing the theme in https://github.com/apache/couchdb/pull/4032
* Remove another unused include file (thanks eralng_ls!)
* Remove all the schema smoosh functionality
> More dead code cleanups

- build-aux/Jenkinsfile.full
Comment them out for the time being
> FreeBSD workers are offline

- src/fabric/src/fabric_doc_update.erl
Previously `fabric_doc_update` message handler crashed with a `function_clause` error the first time it encountered an `all_dbs_active` error.
Opt to handle it as a `rexi_EXIT` with a hope that some workers would still return a valid result.
> Handle all_dbs_active in fabric_doc_update

- .asf.yaml
As per ML discussion 5 days ago https://lists.apache.org/thread/x4lc6vhthj1vkt2xpd0ox5osh959qsc4
> Move main -> fdbmain

- build-aux/Jenkinsfile.full
Owner indicated the instance has gone away
> Skip PPC64 CI builds

- README.rst
After changing branch 3.x -> main, show status in README
> Display main build status in README

- src/couch/src/couch_app.erl
- src/couch/src/test_util.erl
- src/couch_mrview/src/couch_mrview_http.erl
- src/mem3/src/mem3.erl
- src/mem3/src/mem3_reshard_httpd.erl
- src/mem3/src/mem3_util.erl
Fix miscellaneous compiler warnings.
```
make eunit
```
> Compiler warning fixes

- README.rst
Fix IRC url
Renaming master -> main for contributing template
> Small url fixes

- build-aux/Jenkinsfile.full
- build-aux/Jenkinsfile.pr
Since we're not uploading logs skip setting up and fetching creds and IO log environment variable setup.
> Skip nightly package uploads since nothing seems to be using them

- src/smoosh/src/smoosh_channel.erl
- src/smoosh/src/smoosh_server.erl
There is a subtle race condition where smoosh attempts to open a deleted db when remonitoring a compaction job or starting a compaction job. This PR handles `not_found` errors for these two cases.
`make eunit apps=smoosh`
> Fix not_found error smoosh

- test/elixir/test/config/skip.elixir
- test/elixir/test/proxyauth_test.exs
After reverting #4094, bringing this back as a seperate fix.
> Fix proxyauth_test and remove it from skipping tests

- src/fabric/src/fabric_view_changes.erl
We always ran a regex match for it, then failed, and tried the regular pattern. Regexes are pretty fast (15-30 microseconds on my laptop), but it's still a waste of resources. For comparison a `config:get/3` is about a microsecond, so it's like needlessly performing 10 extra config lookups per `_changes` feed request.
Improve unit tests by having more cases and one test per case.
Remove unreachable `"now"` clause in `validate_start_seq/2`. By that point `get_start_seq/2` should have transformed `"now"` into a proper sequence so it's confusing validating that case as passing. At that point it should be considered a 
failure, which is what one of the new unit tests checks for.
> Remove the long deprecated bigcouch 0.4 change sequence support

- src/docs/src/api/server/common.rst
- src/docs/src/config/auth.rst
Document undocumented _versions endpoint.
> Document _versions endpoint

- src/mem3/test/eunit/mem3_reshard_api_test.erl
These warnings occur when compiling with OTP 25:
```
src/mem3/test/eunit/mem3_reshard_api_test.erl:50:57: Warning: variable '_Persist' is already bound. If you mean to ignore this value, use '_' or a different underscore-prefixed name
```
```
make eunit apps=mem3 suites=mem3_reshard_api_test
```
> Fix variable already bound warnings

- src/fabric/src/fabric_ring.erl
- src/mem3/src/mem3_util.erl
This option is useful when we want to accumulate at least R result copies for each document. Typically R=2 in a default 3 node cluster. Without shard splitting, this would simply be waiting for at least R copies returned from each range. However, in the case when shard copies don't have exactly the same range boundaries, the correct logic is to try to completely cover the ring at least R times. The algorithm for checking if the ring can be covered is already implemented, we just add it as an option to `fabric:handle_response/4,5`.
This is essentially another preparatory PR to implement the optimized `fabric:bulk_get(...)` API as described in issue #4183 and it's just split out as a separate commit as it's a fairly standalone change.
Additionally, had noticed that the unit tests in …
> Introduce {rmin, R} option for fabric:handle_response/4,5

- src/couch/src/couch_lru.erl
- src/couch/src/couch_server.erl
We've observed `couch_db:incref/1` being called with `undefined` under load. On examination of couch_server it seems we unlock an `#entry` unilaterally, which can leave an `#entry` where lock is `unlocked` but `db` is not yet populated, and hence the value based to `incref` is the default for the record, which is `undefined`.
This patch modifies close_db_if_idle to only proceed if it finds an unlocked #entry.
> Fix spurious unlock in close_db_if_idle

- src/couch_prometheus/test/eunit/couch_prometheus_e2e_tests.erl
Currently, applications are restarted during individual tests, resulting in noisy output:
```
module 'couch_prometheus_e2e_tests'
Prometheus E2E Tests
couch_prometheus_e2e_tests:66: node_call_chttpd...ok
Application config was left running!
Application asn1 was left running!
Application b64url was left running!
Application public_key was left running!
Application ssl was left running!
Application couch_dist was left running!
Application couch_epi was left running!
Application khash was left running!
Application couch_event was left running!
Application folsom was left running!
Application couch_stats was left running!
Application hyper was left running!
Application ibrowse was left running!
Application inets was left running!
Application hqueue was left running!
Application compiler was …
```
> Quiet prometheus end to end tests

- src/docs/src/conf.py
- src/docs/templates/layout.html
- src/docs/templates/pages/index.html
Some internal changes after upgrading httpdomain to sphinxcontrib.httpdomain
> Fixing API Quick Reference

- src/couch_prometheus/src/couch_prometheus_server.erl
Previously, the cast `refresh` message didn't explicitly cancel the previous timer. If a `gen_server:call(Server, refresh)` was made and a `refresh` message was already in the message queue, it was possible to end up with two parallel refresh periods (cycles): one with the regular refresh period, the other generated by the regular refresh gen_server call.
In addition, drain all the previous refresh messages before scheduling a new timer. This should further help lower the chance of refresh cycles piling up on top of each other.
The fix is mostly theoretical as technically I don't think anything triggers a `refresh` gen_server:call/2 calls in practice. It would have to be a manual or an externally scripted call.
> Avoid refresh messages piling up in prometheus server

- src/docs/src/api/server/authn.rst
- src/docs/src/config/auth.rst
Introduce new roles_claim_path parameter and
add missing roles_claim_name description.
Continue from https://github.com/apache/couchdb-documentation/pull/737
> Introduce roles_claim_path

- src/couch/src/couch_httpd_auth.erl
- src/couch/src/couch_server.erl
Thanks to Ilya for noticing and catching these!
> A few more Erlang <23 cleanups

- .gitignore
- rebar.config.script
- src/config/LICENSE
- src/config/src/config.app.src.script
- src/config/src/config.erl
- src/config/src/config_app.erl
- src/config/src/config_listener.erl
- src/config/src/config_listener_mon.erl
- src/config/src/config_notifier.erl
- src/config/src/config_sup.erl
- src/config/src/config_util.erl
- src/config/src/config_writer.erl
- src/config/test/config_tests.erl
- src/config/test/fixtures/config_default_test.ini
- src/config/test/fixtures/config_tests_1.ini
- src/config/test/fixtures/config_tests_2.ini
- src/config/test/fixtures/default.d/extra.ini
- src/config/test/fixtures/local.d/extra.ini
As per consensus in ML discussion https://lists.apache.org/thread/9dphqb6mjh1v234v15rcft7mfpjx9223
> Integrate config app into main repo

- src/smoosh/src/smoosh_server.erl
Fixes the case when get_index/3 returns a `database_not_found` error.
> Fix smoosh get_priority/2 case clause

- src/smoosh/src/smoosh_server.erl
Make sure we don't do an O(n) filtering when enqueuing processes terminate.
Also, cleanup an old code_change clause, and add a tiny optimization to avoid unnecessary external calls.
> Optimize smoosh enqueuing

- .gitignore
- rebar.config.script
- src/b64url/.gitignore
- src/b64url/LICENSE
- src/b64url/Makefile
- src/b64url/README.md
- src/b64url/c_src/b64url.c
- src/b64url/rebar.config
- src/b64url/src/b64url.app.src
- src/b64url/src/b64url.erl
- src/b64url/test/b64url_tests.erl
- src/b64url/test/benchmark.escript
- src/ets_lru/.gitignore
- src/ets_lru/LICENSE
- src/ets_lru/Makefile
- src/ets_lru/src/ets_lru.app.src
- src/ets_lru/src/ets_lru.erl
- src/ets_lru/test/ets_lru_test.erl
- src/khash/.gitignore
- src/khash/LICENSE
- src/khash/Makefile
- src/khash/README.md
- src/khash/c_src/hash.c
- src/khash/c_src/hash.h
- src/khash/c_src/khash.c
- src/khash/rebar.config
- src/khash/src/khash.app.src
- src/khash/src/khash.erl
- src/khash/test/gen_term.erl
- src/khash/test/khash_test.erl
As discussed on the mailing list https://lists.apache.org/thread/opvsmz1pwlnv96wozy5kp7ss896l9lfp
> Integrate b64url, ets_lru and khash into the main repo

- src/docs/src/conf.py
to match current patch version.
> Bump release version of 3.2.2 docs

- src/docs/src/config/ioq.rst
- src/ioq/src/ioq.erl
- src/mem3/src/mem3_reshard_index.erl
- src/mem3/src/mem3_reshard_job.erl
This lets users bypass it just like any other ioq classes.
Improving on https://github.com/apache/couchdb/pull/4267
> Add a proper reshard jobs ioq class

- src/ddoc_cache/test/eunit/ddoc_cache_lru_test.erl
To hopefully fix a flaky test I noticed:
```
module 'ddoc_cache_lru_test'
...
ddoc_cache_lru_test:97: with (check_cache_refill)...*failed*
...
in function meck_proc:wait/6 (src/meck_proc.erl, line 171)
in call from ddoc_cache_lru_test:check_cache_refill/1 (test/eunit/ddoc_cache_lru_test.erl, line 204)
**error:timeout
```
> Increase ddoc_cache test timeouts

- src/smoosh/test/smoosh_tests.erl
Should help with the failures in
```
smoosh_tests:21: smoosh_test_ (t_index_cleanup_happens_by_default)...[0.117 s] ok
smoosh_tests:22: smoosh_test_ (t_index_cleanup_can_be_disabled)...*failed*
in function meck_proc:wait/6 (src/meck_proc.erl, line 171)
in call from smoosh_tests:t_index_cleanup_can_be_disabled/1 (test/smoosh_tests.erl, line 167)
in call from eunit_proc:run_test/1 (eunit_proc.erl, line 531)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 356)
in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 514)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 456)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 346)
**error:timeout
output:<<"">>
```
Looking at runtimes there it …
> A few more smoosh test flaky fixups

- src/fabric/src/fabric_doc_update.erl
Previously we handled `{bad_request, Msg}` but not `{forbidden, Msg}`, so a `before_doc_update` handler which wanted to emulate the VDU `forbidden` response ended up crashing with an unhandled clause instead.
(Note: The replicator doc validation BDU wasn't affected as those BDU calls are made directly from fabric since `*_replicator` shards are "special" system dbs).
> Fix handling forbidden exceptions from workers in fabric_doc_update

- configure
- configure.ps1
- src/couch/rebar.config.script
Set Spidermonkey 91 as the new default version.
> Set Spidermonkey 91 as default

- src/fabric/src/fabric_util.erl
- src/rexi/src/rexi_server.erl
> Delete unused include_lib attributes

- build-aux/Jenkinsfile.pr
Merging this separately to help out the original PR https://github.com/apache/couchdb/pull/4380
This is my +1 for this commit. The discussion is still taking place in the original PR
> Set the SpiderMonkey version for the first phase of PR builds

- src/docs/src/partitioned-dbs/index.rst
https://docs.couchdb.org/en/stable/partitioned-dbs/index.html#partitions-by-example
The first example is a partitioned database using a partitioned query, so here we should use `ddoc.json`.
> Docs: Fix example code in Partitioned Databases

- src/couch_replicator/test/eunit/couch_replicator_scheduler_docs_tests.erl
For completeness, make sure to test replicator doc updates with `update_docs=true` setting as well.
Issue: https://github.com/apache/couchdb/pull/4423
> Test the update_docs=true case in replicator scheduler docs test

- src/docs/src/replication/conflicts.rst
- Add `adm:pass` to DB's URL to prevent unauthorized error
- Add `new_edits:false` to the request JSON object to generate conflicts
- Code reformatting by Rubyfmt
```bash
$ ./configure --dev && make && ./dev/run --admin=adm:pass
$ gem install rest-client
$ ruby test.rb
```
Fix https://github.com/apache/couchdb/issues/4225
> Modify conflict ruby example

- src/docs/src/best-practices/reverse-proxies.rst
> docs(typo): Fix server name duplicate

- src/couch/test/eunit/couchdb_file_compression_tests.erl
Use the simpler `?TDEF_FE` macro and fix timeout usage bug. EUnit timeout is in seconds, while test_util:wait/2 takes milliseconds. This was revealed due a slow disk IO speed on the new s390x worker.
Issue: https://github.com/apache/couchdb/issues/4521
> Improve compression eunit test suite

- Makefile
- rel/overlay/bin/remsh
Backport cookie handling for remsh from main. 
Main PR: https://github.com/apache/couchdb/pull/4509
> Backport small fixes from main to 3.2.x

- nouveau/README.md
- nouveau/src/main/java/org/apache/couchdb/nouveau/api/DoubleField.java
- nouveau/src/main/java/org/apache/couchdb/nouveau/api/StringField.java
- nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexTest.java
(all fields are indexed for faceting)
> remove unused facet property

- Makefile
- build-aux/Jenkinsfile.full
- build-aux/Jenkinsfile.pr
- nouveau/nouveau.yaml
- nouveau/src/main/java/org/apache/couchdb/nouveau/api/IndexDefinition.java
- nouveau/src/main/java/org/apache/couchdb/nouveau/core/Index.java
- nouveau/src/main/java/org/apache/couchdb/nouveau/core/IndexManager.java
- nouveau/src/main/java/org/apache/couchdb/nouveau/core/UpdatesOutOfOrderException.java
- src/nouveau/src/nouveau_fabric_info.erl
- src/nouveau/src/nouveau_fabric_search.erl
- src/nouveau/src/nouveau_httpd.erl
- src/nouveau/src/nouveau_maps.erl
- test/elixir/test/config/nouveau.elixir
- test/elixir/test/config/test-config.ini
- test/elixir/test/nouveau_test.exs
enable nouveau in CI
make index creation idempotent if index definition matches
> enable nouveau in CI

- .asf.yaml
- dev/run
- rel/reltool.config
- src/docs/src/whatsnew/3.3.rst
- version.mk
Bring in 3.3.x branch changes into main.
> Merge 3.3.x to main

- src/mem3/src/mem3_sync.erl
Increase internal replicator default batch size and batch count. On systems with a slower (remote) disks, or a slower dist protocol, internal replicator can easily fall behind during a high rate of bulk_docs ingestion. For each batch of 100 it had to sync security properties, make an rpc call to fetch remote target sync checkpoint, open handles, fetch revs diff, etc. If there are changes to sync it would also incur the commit (fsycn) delay as well. It make sense to operate on slightly larger batches to increase performance. I picked 500 as that's the default for the (external) replicator.
It also helps to keep replicating more than one batch once we've brought the source and target data into the page cache, so opted to make it do 5 batches per job run at most.
A survey of other batch size …
> Speed up internal replicator

- src/couch/src/couch_file.erl
Since we're using fractional milliseconds, might as well measure at the nanosecond resolution.
```
rp(couch_stats:sample([fsync,time])).
[{min,19.572592},
{max,41.60692},
{arithmetic_mean,22.214490860169498},
{geometric_mean,22.134517662321407},
{harmonic_mean,22.068093005211708},
{median,22.147823},
{variance,4.5064974888058495},
{standard_deviation,2.1228512639386325},
{skewness,5.243648789818805},
{kurtosis,43.072222638582026},
{percentile,[{50,22.147823},
{75,23.18369},
{90,23.573497},
{95,23.780686},
{99,27.245643},
{999,41.60692}]},
{histogram,[{20.572592,24},
{21.572592,68},
{22.572592,51},
{23.572592,68},
{24.572592,19},
{25.572592,3},
{26.572592,0},
{27.572592,1},
{28.572592,0},
{29.572592,0},
{30.572592,0},
{31.572592,0},
{32.572592,0},
{33.572592,0},
{34.572592,0}, …
```
> Improve fsync metrics time calculation

- src/couch/src/couch_db.erl
- src/couch/src/couch_db_updater.erl
`couch_db` and `couch_db_updater` modules are the only place using "non-rep" to refer to "local" documents and "merge conflicts" to refer to "replicated changes", so rename them to make them consistent with the rest of the codebase.
> Rename NonRep -> Local and merge_conflicts -> replicated_changes

- src/couch_replicator/src/couch_replicator_scheduler_job.erl
During cluster upgrades from 3.2 to 3.3 when instance start time switched from being always  `0` to an actual timestamp, replication jobs will crash when endpoints are upgraded. Replication jobs were started when endpoint emitted a `0` and then it becomes a non-`0` value which will crash the next checkpoint attempt.
After the crash jobs will restart and continue fine where they left off without rewinding. However they will make a logging mess while they crash. All four workers will exit with the `{checkpoint_commit_failure,...}` error. This commit make it the checkpoint ignore mismatches if one of the instance start times is 0.
Issue: https://github.com/apache/couchdb/issues/4621
> Handle replicator instance start time during upgrades better

- src/couch/src/couch_db_split.erl
- src/mem3/src/mem3_rep.erl
- src/mem3/src/mem3_reshard_job.erl
- src/mem3/test/eunit/mem3_reshard_test.erl
Previously, internal replicator (mem3_rep) replicated purge infos to/from all the target shards. Instead, it should push/pull changes only to appropriate ranges if those purge infos belong there based on database's hash function.
Users experienced this error as a failure in database which contains purges, which was split twice in a row. For example, if a Q=8 database is split to Q=16, then split again from Q=16 to Q=32, the second split operation might fail with a `split_state:initial_copy ...{{badkey,not_in_range}` error. The misplaced purge infos would be noticed only during the second split, when the initial copy phase would crash because some purge infos do not hash to neither one of the two target ranges. Moreover, the crash would lead to repeated retries, which generated a huge job …
> Fix purge infos replicating to the wrong shards during shard splitting.

- src/mango/test/mango.py
Databases used for integration testing are being recreated by unbounded recursion which can blow up the stack in case of unrecoverable errors.  This change revisits the respective parts of the implementation in the following ways:
- Replace the tail recursion for a regular loop.
- Set an upper limit for the number of tries.
- Signal the problem with a more descriptive message.
- Introduce an increasing delay between the subsequent tries for tolerance against transient errors.
> chore(`mango`): revisit test database recreation logic

- rel/overlay/etc/default.ini
- src/couch_replicator/src/couch_replicator.erl
- src/couch_replicator/src/couch_replicator_doc_processor.erl
- src/couch_replicator/src/couch_replicator_scheduler_job.erl
- src/couch_replicator/src/couch_replicator_utils.erl
- src/docs/src/config/replicator.rst
Log insecure replication requests to guide administrators before they activate additional security measures (like disabling http protocol).
Will be covered by tests
N/A
> Add optional logging of security issues when replicating

- README-DEV.rst
The PR contains a fix to the Sphinx broken hyperlink found in the docs.
> docs: update sphinx resource hyperlink

- src/docs/src/api/database/security.rst
- src/docs/src/api/document/attachments.rst
- src/docs/src/best-practices/forms.rst
- src/docs/src/best-practices/iso-date.rst
- src/docs/src/cluster/sharding.rst
- src/docs/src/config/intro.rst
- src/docs/src/ddocs/views/collation.rst
- src/docs/src/ddocs/views/pagination.rst
- src/docs/src/intro/api.rst
- src/docs/src/intro/curl.rst
- src/docs/src/intro/security.rst
- src/docs/src/maintenance/compaction.rst
- src/docs/src/partitioned-dbs/index.rst
- src/docs/src/setup/single-node.rst
fix https://github.com/apache/couchdb/issues/4642
> docs: add `adm:pass` to URL examples

- src/mem3/src/mem3_rep.erl
- src/mem3/test/eunit/mem3_rep_test.erl
When replication jobs are started with just shard names (paths), mem3_rep creates `#shard{}` records from those and fills in some fields like `name` and `node`. However we had left the `range` field as `undefined`. Until a recent fix to avoid duplicating document purges [1], we didn't care about ranges, so it was just untidy but not a big problem. Since the fix, we rely on having a proper ranges and would get function or case clause errors during purge infos pulling and pushing operations.
The fix is to use the `mem3:range/1` function to obtain the range based on the shard path if we can. In some cases we may replicate node local databases, so we still have to account for the cases that ranges may be `undefined`.
In addition to the fix, improve the tests coverage by testing replication of …
> Fix undefined range in mem3_rep purge replication logic

- nouveau/build.gradle
(https://github.com/dropwizard/dropwizard/releases)
> upgrde to dropwizard 4.0.1

- rebar.config.script
Upgrade to the latest proper version to fix some makefile targets under Windows.
> deps: upgrade proper

- src/couch_replicator/src/couch_replicator_api_wrap.erl
- src/couch_replicator/src/couch_replicator_worker.erl
- src/couch_replicator/test/eunit/couch_replicator_error_reporting_tests.erl
Documents with attachments are written as individual HTTP PUT multipart requests. If a document PUT request fails with a 401, 403 or 413 error, the expectation is that the replicator would skip over that document, increment the `doc_write_failures` metric and continue replicating. That behavior is by design. However, previously, before this commit, documents were also skipped in case of any unknown 4xx error. This commit switches the default behavior such that unexpected 4xx errors do not continue. If the error is intermittent, the job will crash, retry, and would eventually succeed. If the error is persistent, exponential backoff will keep it from retrying indefinitely in a tight loop.
Documents will be skipped only for 401/403/413/415 HTTP error and for 400 error code a reason related …
> Crash replication jobs on unexpected 4xx errors

- src/docs/src/api/database/bulk-api.rst
- src/docs/src/api/local.rst
Add documentation for `_design_docs/queries` and `_local_docs/queries`.
Related PR: https://github.com/apache/couchdb/pull/4682
> docs: `_design_docs/queries` and `_local_docs/queries`

- nouveau/build.gradle
insist on 11 as a minimum but don't insist on 11 itself.
> set nouveau minimum java version

- README.rst
> Update docs badge icon

- Makefile
- Makefile.win
Currently main CI deb packages are failing.
Issue: https://github.com/apache/couchdb/issues/4706#issuecomment-1690198451
> Try to fix deb package builds in the main CI

- src/docs/src/install/search.rst
Set an example cookie like in the cluster setup docs.
> Ban the last monster

- src/chttpd/src/chttpd_db.erl
- src/chttpd/test/eunit/chttpd_purge_tests.erl
- src/docs/src/api/database/misc.rst
- src/fabric/src/fabric.erl
- src/fabric/src/fabric_db_purged_infos.erl
- src/fabric/src/fabric_rpc.erl
- Expose the internal purged_infos API to users
- Add tests and documentation for `_purged_infos`
```bash
$ export DB="http://adm:pass@127.0.0.1:5984"
$ curl -XDELETE $DB/db
{"ok":true}
$ curl -XPUT $DB/db
{"ok":true}
$ curl -XPOST $DB/db/_bulk_docs \
-H 'Content-Type: application/json' \
-d '{"docs": [{"_id":"a", "val":1}, {"_id":"b", "val":2}, {"_id":"c", "val":3}]}'
[{"ok":true,"id":"a","rev":"1-08d53a5760b95fce6df2e2c5b008be39"},
{"ok":true,"id":"b","rev":"1-b57c77a9e6f7574ca6469f0d6dcd78bb"},
{"id":"c","error":"conflict","reason":"Document update conflict."}]
$ curl -XPOST $DB/db/_purge \
-H 'Content-Type: application/json' \
-d '{"a":["1-08d53a5760b95fce6df2e2c5b008be39"], "b":["1-b57c77a9e6f7574ca6469f0d6dcd78bb"]}'
{"purge_seq":null, …
```
> Add `_purged_infos` endpoint

- src/couch_replicator/src/couch_replicator_utils.erl
Previously when transient replication jobs were canceled their `#rep` record's source and target fields would be `undefined`. That was accounted for in the http usage logger when it's enabled and resulted in a badrecord 500 error.
Fix: https://github.com/apache/couchdb/issues/4760
> Fix badrecord error when replicator is logging http usage

- src/mem3/test/eunit/mem3_reshard_test.erl
Saw this one fail multiple times already.
Previously, we were counting the exact number of calls each of the mocked functions were called. However, those calls were made from separate processes with non-deterministic number of retries each, so sometimes, there could be 8 calls, 9 or 10. (Confirmed by adding random sleep in `mem3_reshard_index:retry/3` to reproduce it locally).
We mainly care that the shard is split, the indices finished building, and that those mocked index functions were called more than 4 times due to retries so let's make the test do that instead.
> Fix flaky mem3 reshard test

- src/nouveau/src/nouveau_index_manager.erl
- src/nouveau/src/nouveau_index_updater.erl
if :update returns an error we will now return this as the rexi reply, making for a better reported error.
N/A
N/A
> avoid badmatch in error cases

- src/couch_replicator/src/couch_replicator_api_wrap.erl
- src/couch_replicator/test/eunit/couch_replicator_error_reporting_tests.erl
Use something more descriptive, especially since it can bubble up to the user level when the replication job crashes.
In order to also log the error causing the failure, move the exit call to the main open_doc_revs body and the remove `retries=0` clause. However, avoid changing the exit value shape and keep it as an atom for now. There is a chance
it might break error handling in the upper API layers in case when we match on error reason "shape".
To test everything end-to-end, modify the test setup to create replication jobs with additional options, when previously it was only a choice between continuous or one-shot.
> Replace replicator open_doc_revs kaboom with something more descriptive

- src/nouveau/src/nouveau_api.erl
- src/nouveau/src/nouveau_index_updater.erl
Use the same connection PID for all index update requests to ensure they are applied in the correct order.
Previously some requests (when purging) were handled by the pool and could get reordered.
N/A
> fix nouveau index updating ordering

- Makefile
- Makefile.win
> Rename find_bugs/find-bugs make target to xref

- src/couch/src/couch_os_process.erl
* `code_change` is not used any longer needed. It's part of 2014 live code upgrade clause at Cloudant at the time [1]
* start_link/2,3 are not used. As a consequence, we do not need to pass in os process and port options. This eliminates the need for mering options into BaseProc.
* Remove `v(1)` as we don't support hot code upgrades.
* Use the ?MODULE name instead of duplicating the module name in gen_server:start_link/3.
[1] https://github.com/apache/couchdb/commit/a229b8d39bfaf302a6cb788dd0654d5e467f84d8
> A few more cleanups in couch_os_process

- src/couch/src/couch_os_process.erl
Custom callback functions are not used any longer. Reading and writing happens only via local writejson/2 and readjson/1 functions. So we directly call those instead of pretending to go through customizable callbacks.
Since we're using these functions directly, we can clean up some exports, too.
> Remove custom read and write callback functions in couch_os_process

- nouveau/build.gradle
upgrade nouveau's lucene version to 9.8.0
N/A
> upgrade nouveau's lucene version to 9.8.0

- Makefile
- Makefile.win
- src/couch/include/couch_js_functions.hrl
`bcrypt` is no longer used in CouchDB, so remove them from the codebase.
> Remove `bcrypt`

- src/fabric/test/eunit/fabric_bench_test.erl
Rapidly creating and deleting a db in the this test triggers a race condition. A potential culprit might be the gen_server cast in https://github.com/apache/couchdb/blob/main/src/mem3/src/mem3_util.erl#L176. To fix the flakiness use the newer `opts_for_db/1` function with a test wait function. This way we may also avoid inadvertently re-creating the shard file due to the `create_if_missing` option from `get_doc_count/1`.
> Fix flaky fabric_bench test

- src/couch/src/couch_httpd_auth.erl
To smooth cluster upgrades, send the original format of AuthSession cookie if MustMatchBasic is false (i.e, when generating a Cookie from a successful cookie_auth_handler call).
Prior to this (and after 50c69a0c68), during an upgrade, a cookie issued by the basic auth handler from an upgraded node will not be parseable by not-upgraded nodes.
With this change a cookie issued by the cookie_auth_handler retains its original format. Only cookies issued by the default_auth_handler will be the new format.
1) Create a mixed state cluster (with a node on code before https://github.com/apache/couchdb/pull/4702 and other nodes with this code or later).
2) acquire a cookie from new node via `/_session`
3) present the cookie  to an old node.
4) cookie should be accepted. …
> Send compatible AuthSession cookie when possible.

- src/ddoc_cache/test/eunit/ddoc_cache_lru_test.erl
This test has been the most flaky one lately.
DDoc cache does quite a bit async process spawning. It's possible that entry processes never finish opening before the test already proceeds and expects all 10 entries to be removed.
Also, to increase isolation between tests switch eunit `setup` to `foreach`. This will restart the whole ddoc app and reduce possible influence of one test on another.
Fix: https://github.com/apache/couchdb/issues/4793
> Another attempt at fixing the flaky ddoc_cache test

- src/couch/test/eunit/couch_stream_tests.erl
On MacOS runner this test can be flaky. On slower workers StreamPid would usually be killed by the time we check is_process_alive/1, however on MacOS it has failed at least once with:
```
module 'couch_stream_tests'
CouchDB stream tests
couch_stream_tests:124: -should_stop_on_normal_exit_of_stream_opener/1-fun-3-...*failed*
in function couch_stream_tests:'-should_stop_on_normal_exit_of_stream_opener/1-fun-3-'/1 (test/eunit/couch_stream_tests.erl, line 124)
[...]
**error:{assert,[{module,couch_stream_tests},
{line,124},
{expression,"not ( is_process_alive ( StreamPid ) )"},
{expected,true},
{value,false}]}
```
To fix it, ensure we wait for the process to die before asserting it's dead. It's a bit redundant to assert it's gone, …
> Fix flaky couch_stream test

- build-aux/Jenkinsfile.full
Until we fix the `Cannot run program "sh"` issue
> Temporarily disable MacOS runner

- nouveau/build.gradle
upgrade dropwizard to 4.0.4
N/A
N/A
> upgrade dropwizard to 4.0.4

- build-aux/Jenkinsfile.full
Bring over a few changes from  main:
* Use latest Erlang 24 patch version
* Exclude missing/disabled workers
> Update Jenkinsfile.full on 3.3.x

- src/ken/src/ken_server.erl
In `ken_server`, when fetching design docs fails with a timeout do not crash with a `badmatch` exception. Instead, resubmit the job for later processing.
This bug was discovered by [Antithesis](https://antithesis.com/) simulation. Thanks to `@LuisMarcano-antithesis` for running the simulation!
The error log lines were:
```
[service_couchdb1] [I] [error] 2023-10-09T15:10:30.484954Z couchdb@10.0.0.11 emulator -------- Error in process <0.2165.0> on node 'couchdb@10.0.0.11' with exit value:
[service_couchdb1] [I] {{badmatch,{error,timeout}},[{ken_server,update_db_indexes,2,[{file,"src/ken_server.erl"},{line,278}]}]}
```
The workload used was https://github.com/nickva/couch-compose-workload
> Handle ddocs fetch timeouts in ken

- rel/reltool.config
- src/docs/src/whatsnew/3.3.rst
- version.mk
Merge 3.3.x changes.
Cherry-pick:
- 3.3.3 version bump
- 3.3.3 release notes
> Merge 3.3.x changes

- .gitignore
A `.hypothesis` directory was observed at the top level of the repo, so ignore them wherever they might be.
> Git ignore all `.hypothesis` directories

- src/docs/src/cve/2023-45725.rst
> Fix typo in 2023-45725 note

- src/couch_index/src/couch_index_server.erl
- src/couch_index/test/eunit/couch_index_crash_tests.erl
Previously we didn't always reply to waiting `get_index` calls as sometimes we clobbered or deleted waiters in by_sig ets table.
Ref: https://github.com/apache/couchdb/pull/4491
> Make sure to reply to couch_index_server clients

- nouveau/build.gradle
> upgrade to lucene 9.9.0

- src/docs/src/conf.py
Load documentation version from local version.mk file.
> feat(docs/3.3.x): Set docs version numbers dynamically from file

- src/docs/src/conf.py
Load documentation version from local version.mk file.
> feat(docs): Set docs version numbers dynamically from file

- src/chttpd/test/eunit/chttpd_changes_test.erl
Add tests for `_changes` with different parameters   
- style=all_docs
- include_docs=true
- conflicts=true
`make eunit apps=chttpd suites=chttpd_changes_test`
> Add tests for `_changes` with different parameters

- src/docs/src/install/index.rst
- src/docs/src/install/snap.rst
This reverts commit e9d703c2139cdb695259c814c79f041e6864b81e.
> Revert "Remove installation via snap package (#4826)"

- src/docs/src/install/snap.rst
> Re-wrote snap installation guide lines for 3.3

- src/docs/src/install/snap.rst
Updated installation guide lines for 3.3.3.
> Re-wrote snap installation guide lines for 3.3 (#4940)

- src/chttpd/test/eunit/chttpd_changes_test.erl
Test `_conflicts` field when there are deleted conflicting docs.
`make eunit apps=chttpd suites=chttpd_changes_test`
Related PR: https://github.com/apache/couchdb/pull/4862
> Add tests for `_changes` endpoint

- src/docs/requirements.txt
- src/docs/src/conf.py
Add sphinxcontrib.jquery to extensions for functional searching.
Thanks @jiahuili430 for investigating and tips to fix the search issue.
> Update Sphinx package version to 7.2.6

- dev/run
Fix `dev/run` setup_configs, generate nouveau configuration when nouveau is enabled
Related PR: https://github.com/apache/couchdb/pull/4956
> Generate nouveau config when nouveau is enabled

- src/fast_pbkdf2/c_src/fast_pbkdf2.c
- src/fast_pbkdf2/rebar.config
After merging, #4963 should be fine.
> Update fast_pbkdf2 to 1.0.6 (e7341dc)

- src/couch/src/couch_proc_manager.erl
- src/couch/src/couch_users_db.erl
- src/docs/rfcs/008-map-indexes.md
- src/docs/src/config/http.rst
- src/docs/src/ddocs/views/intro.rst
- src/docs/src/ddocs/views/joins.rst
- src/mango/src/mango_idx_view.erl
- src/mem3/test/eunit/mem3_reshard_api_test.erl
- src/mem3/test/eunit/mem3_reshard_changes_feed_test.erl
- src/setup/README.md
> remove repetitive word

- src/couch_replicator/src/couch_replicator_sup.erl
Use maps and a few helper function to make it less verbose.
Otherwise it should be the exact same specs as before.
References:
https://www.erlang.org/doc/design_principles/sup_princ.html
https://www.erlang.org/doc/man/supervisor
https://www.erlang.org/docs/17/man/supervisor.html
> Modernize couch replicator supervisor

- src/fabric/test/eunit/fabric_tests.erl
Previously I forgot to assert we actually created the dbs and forgot to clean them up. Also, add a few more cases using a wider variety of delimiters.
> Improve fabric all_dbs test

- src/couch/src/couch_server.erl
Previously we called it as `exit(couch_server_N, config_change)` but exit/2 doesn't know what to do with an atom, it needs a pid.
```
exit(couch_server_1, foo).
** exception error: bad argument
in function  exit/2
called as exit(couch_server_1,foo)
*** argument 1: not a pid
```
This doesn't actually restart the servers as intended and it's also making quite a mess in the eunit logs.
In addition to ensuring we're calling a Pid, use a {shutdown, _} error shape to avoid triggering verbose SASL report as it's an expected condition.
> Fix invalid call to exit/2 in couch_server

- src/couch_replicator/test/eunit/couch_replicator_scheduler_docs_tests.erl
The function `t_scheduler_docs_total_rows` contains a `test_util:wait/3` function with a timeout of 14 seconds, so increase these timeouts to match, and try to avoid this test failure:
```
couch_replicator_scheduler_docs_tests:60: -scheduler_docs_test_main_db_test_/0-fun-0- (t_scheduler_docs_total_rows)...*timed out*
in function timer:sleep/1 (timer.erl, line 235)
in call from test_util:wait/5 (src/test_util.erl, line 237)
in call from couch_replicator_scheduler_docs_tests:t_scheduler_docs_total_rows/1 (test/eunit/couch_replicator_scheduler_docs_tests.erl, line 131)
in call from eunit_proc:run_test/1 (eunit_proc.erl, line 543)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 368)
in call from …
```
> Increase timeout for replicator test

- src/couch_replicator/src/couch_replicator_scheduler_job.erl
Previously, in the rare case the replication job was stopped via `gen_server:stop/3` while it was already crashing, the gen_server:stop/3 call won't return `ok` but instead would exit the calling process. Usually the calling process is couch_replicator_scheduler, so we ended up crashing `couch_replicator_scheduler` process itself.
As per https://www.erlang.org/doc/apps/stdlib/gen_server.html#stop/3,
> The function returns ok if the server terminates with the expected reason.
Any other reason than normal, shutdown, or {shutdown,Term} causes an error report to be issued using logger. An exit signal with the same reason is sent to linked processes and ports.
> Fix replicator scheduler job stopping crash

- src/docs/src/query-server/javascript.rst
c.f. https://github.com/apache/couchdb/pull/4412
> doc: we no longer ship our own JSON as of aabda0c80c336738c683ee69a8c7762a57054081

- dev/run
print log dir on dev/run startup
> print log dir on dev/run startup

- Makefile
- Makefile.win
- configure
- configure.ps1
Replacing the config values 0/1 to false/true for the following keys:
WITH_FAUXTON, WITH_DOCS, WITH_CLOUSEAU, SKIP_DEPS
> chore(dev): Replace 0/1 to false/true for config keys

- configure.ps1
Fix some PSScriptAnalyzer warnings and remove unused variable.
> chore(powershell): Fix PSScriptAnalyzer warnings

- src/couch/src/couch_bt_engine_header.erl
Previously, in #5132 we asserted that the update sequence in the epoch doesn't regress during same node updates, and during node changes. However, we didn't consider the case when the shards are compacting. When that happens, the epochs are copied as is from the old header, so they may have higher update sequences, but the update sequence is set to the default (0) from the new header record instance. As a result, the assertion would fire during compaction in the initialization phase.
> Fix epoch update sequence regression

- src/couch/src/couch_lru.erl
Maps are more ergonomic and usually more performant.
Also add some tests for couch_lru and a few specs with an improved comment indicating what the close function actually doesn't. Previously, it mentions only one of the things: closing oldest idle, however it also bumps busy entries, and clears deleted (or locked) handles from the cache.
This change was originally part of another PR that's now closed: #5165.
Investigation into couch_lru started with issue #5166
> Update couch_lru to use maps

- src/couch/src/couch_lru.erl
Previously, calling insert multiple times for the same db, created multiple tree entries and only one map entry. Fix this but ensuring the cache can never be inconsistent as a result of performing any number of inserts or updates.
This should fix the function clause described in #5168. A detailed example on how this double insert leads to the function clause follows:
* Calling insert twice for database `Db` might make the cache look something like this:
```
{gb_tree([{100, Db}, ..., {200, Db}, ...]), #{..., Db => 200, ...}}
```
* During traversal when closing, if the first entry (100) is idle, we'd try to update it (bump it). But when bumping, we'd pick out `200` as the key to delete from the `Tree`, instead of 100! So we'd delete 200 and may bump to some higher number like `300`.
* To …
> Make sure we never get an inconsistent couch_lru cache

- src/couch/src/couch_bt_engine_header.erl
It can happen during compaction as we figured out in #5163.  In that commit we removed the assertion when we stay on the same node. However, it may still be possible for someone to resume compaction on another node by copying their files and then the assertion could trigger.
Here we remove the assert and add a clause handling the regression. As it's an expected condition during compaction so we refuse to update the epochs list.
> Expect the update sequence in header epochs list to regress

- src/couch_replicator/src/couch_replicator_doc_processor.erl
Previously we used the gen_server timeout mechanism. If the user sets a short interval value then the periodic membership check message could be delivered first and reset the scheduled timeout timer. When that happens the scanner and shard monitor won't start.
To fix it, do not rely on the timeouts, and instead use an explicit message. That should ensure dalyed init will always run.
> Use an explicit message for replicator doc processor delayed init

- src/couch/test/eunit/couch_key_tree_tests.erl
It was a hack anyway, and we had to tweak its limit before, and now again with OTP 27 it seems sensitive to both OTP versions and js engines (probably due to how it could affect the memory allocator?) [1]. Since we're mostly testing an already fixed OTP regression, it's not worth keep fiddling with this flaky test, so let's remove it.
[1] https://github.com/apache/couchdb/pull/5181#pullrequestreview-2249215235
> Remove flaky couch key tree test

- build-aux/Jenkinsfile.pr
- src/config/src/config.erl
- Add OTP 27 to pull request CI list
- Modify some tests according to Erlang version
> Add OTP 27 to pull request CI list

- src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl
- src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
KVs emitted from a single view are sorted in `insert_results/4` [1], so we have to do the same to avoid logging false positives. That may happen if emit order is dependent on dictionary key order, for instance.
[1] https://github.com/apache/couchdb/blob/7ae40cec1c943668dabbc8ad5c3d44005b1ce6fa/src/couch_mrview/src/couch_mrview_updater.erl#L273-L277
> Sort emitted KVs in quickjs scanner

- src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl
- src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
A large number of false positives seen so far have to deal with users using `Date.now()` or `Math.random()` in the map or reduce function bodies. Needless to mention those will always produce false positive results.
Attempt a heuristic approach to avoid scanning views which contain the most common sources of determinism found so far. These include current date fetching and `Math.random()`.
> Avoid scanning functions with non-deterministic behavior

- src/docs/src/best-practices/jsdevel.rst
After scanning a few clusters, it turns out most incompatibilities were between Spidermonkey 1.8.5 and Spidermonkey 91. For CouchDB train has left the station on that mostly, as we've already been shipped SM 60, 78 and 91 versions. However, there are still users which may be stuck on older CouchDB 1.x instances and are planning to update, so for their benefit add the few known issues to the docs.
Also, document a few differences between QuickJS and SM 91, as well as a description on how to try QuickJS out and how to run the scanner.
> Add some notes about JS engine compatibility issues

- src/chttpd/src/chttpd.erl
This was accidentally left over from before replacing logging the invalid path with incrementing a metric.
> Remove unused variable

- src/docs/src/best-practices/jsdevel.rst
Continued from https://github.com/apache/couchdb/pull/5221
> JS engine doc fixes

- src/couch_replicator/src/couch_replicator_utils.erl
This is a continuation of https://github.com/apache/couchdb/pull/5226
> Replace bespoke url parsing/recomposing in couch_replicator_utils

- src/docs/src/whatsnew/3.4.rst
From June [1] until now
[1] https://github.com/apache/couchdb/commit/62b501873b7e7990a64783c134dd8f1fca77780f
> Bring 3.4 whatsnew up-to-date

- src/docs/src/best-practices/jsdevel.rst
QuickJS and v8 both agree with 91.
> Document another incompatibility between SM 1.8.5 and 91

- src/docs/src/whatsnew/3.4.rst
> doc: add JS scanner to highlights, fix some nitpicks

- src/docs/src/api/ddoc/nouveau.rst
- src/docs/src/api/server/common.rst
- src/docs/src/install/nouveau.rst
some nits that came up during release candidate review
> fixup nouveau docs

- src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl
Previously that particular design doc would crash it's validation with a function_clause in the logs which looked messy.
To fix it, add a case statement to expect that they may not be any valid views left, so we just continue without complaints.
> Handle the case when the QuickJS scanner has no valid views

- rel/overlay/etc/default.ini
- src/couch/src/couch_password_hasher.erl
- src/couch/test/eunit/couch_work_queue_tests.erl
- src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl
- src/docs/src/api/ddoc/nouveau.rst
- src/docs/src/api/server/common.rst
- src/docs/src/config/auth.rst
- src/docs/src/install/nouveau.rst
- src/docs/src/whatsnew/3.4.rst
- test/elixir/test/users_db_security_test.exs
- version.mk
Prep-for 3.4.1
* Cherry-pick commits from `main`
* Update whatsnew
* Bump `version.mk`
> 3.4.x cherry pick 3.4.1 changes

- nouveau/build.gradle
upgrade lucene
covered by unit tests
N/A
> nouveau: upgrade Lucene to 9.12.0

- src/docs/src/ddocs/nouveau.rst
closes: https://github.com/apache/couchdb/issues/5273
> fix ranges doc for nouveau

- src/couch_replicator/src/couch_replicator_docs.erl
- src/fabric/src/fabric_doc_open.erl
- src/fabric/src/fabric_doc_open_revs.erl
Previously, when replicator updated replication documents and the user overrode `couch_db:check_is_admin(Db)` such that the replicator app was not admin, the replicator would end up creating conflicts in the updated replicator docs. This was the result of running the after_doc_read/2 [1] callback, which would strip the credentials and then create a random RevId to replace the real RevId.
To fix it, make sure `after_doc_read/2` is skipped when it's the replicator application itself doing the doc reads. This is similar to what we do in the `before_doc_update/3` callback, so we just mirror the same behavior in `after_doc_read/2`.
Moreover, in order to prevent users from pretending to be the replicator app by using the <<"_replicator">> role, switch the replicator role to be an atom …
> Do not generate conflicts from the replicator app

- Makefile
- nouveau/build.gradle
- nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/Lucene9Index.java
- rel/overlay/etc/default.ini
- src/couch_event/src/couch_event.erl
- src/couch_event/src/couch_event_server.erl
- src/couch_replicator/src/couch_replicator_docs.erl
- src/docs/src/api/database/common.rst
- src/docs/src/config/scanner.rst
- src/fabric/src/fabric_doc_open.erl
- src/fabric/src/fabric_doc_open_revs.erl
Bring commits from main into 3.4.x as preparation for 3.4.2
> 3.4.2 prep

- src/nouveau/src/nouveau_fabric_info.erl
- src/nouveau/src/nouveau_fabric_search.erl
- test/elixir/test/config/nouveau.elixir
- test/elixir/test/nouveau_test.exs
Handle {error, Reason} from design_doc_to_index
> nouveau: send 404 for missing index

- src/nouveau/src/nouveau_fabric_info.erl
- src/nouveau/src/nouveau_rpc.erl
- test/elixir/test/nouveau_test.exs
add signature to _nouveau_info
N/A
https://github.com/apache/couchdb/issues/5291
> add signature to _nouveau_info

- src/docs/src/best-practices/jsdevel.rst
> Fixed a few typos in docs

- Makefile
- Makefile.win
- nouveau/src/main/java/org/apache/couchdb/nouveau/api/SearchRequest.java
- nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexSchema.java
- nouveau/src/test/java/org/apache/couchdb/nouveau/api/SearchRequestTest.java
- nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexTest.java
- nouveau/src/test/resources/fixtures/SearchRequest.json
- rel/overlay/etc/default.ini
- src/docs/src/api/ddoc/nouveau.rst
- src/docs/src/best-practices/jsdevel.rst
- src/docs/src/ddocs/nouveau.rst
- src/nouveau/priv/stats_descriptions.cfg
- src/nouveau/src/nouveau_fabric_info.erl
- src/nouveau/src/nouveau_fabric_search.erl
- src/nouveau/src/nouveau_httpd.erl
- src/nouveau/src/nouveau_int.hrl
- src/nouveau/src/nouveau_rpc.erl
- test/elixir/test/config/nouveau.elixir
- test/elixir/test/nouveau_test.exs
Bring in recent commits from main to the 3.4.x branch in preparation for 3.4.2
> Catch up 3.4.x

- build-aux/Jenkinsfile.pr
- src/couch_quickjs/rebar.config.script
- src/docs/src/whatsnew/3.4.rst
- src/nouveau/src/nouveau_fabric_info.erl
- src/nouveau/src/nouveau_fabric_search.erl
* Write whatsnew for 3.4.2
* Catch up 3.4.x with a few more commits from main
> Write whatsnew for 3.4.2 and catch up 3.4.x from main with a few more commits

- .gitignore
- src/dreyfus/src/dreyfus_fabric.erl
- src/dreyfus/src/dreyfus_fabric_group1.erl
- src/dreyfus/src/dreyfus_fabric_group2.erl
- src/dreyfus/src/dreyfus_fabric_info.erl
- src/dreyfus/src/dreyfus_fabric_search.erl
- src/dreyfus/src/dreyfus_index_manager.erl
- src/dreyfus/test/eunit/dreyfus_blacklist_await_test.erl
- src/dreyfus/test/eunit/dreyfus_blacklist_request_test.erl
- src/dreyfus/test/eunit/dreyfus_config_test.erl
- src/dreyfus/test/eunit/dreyfus_test_util.erl
- Git ignore some files.
- Remove unused includes and defines.
Covered by existing tests.
> Dreyfus cleanup

- src/couch_scanner/src/couch_scanner_plugin.erl
They can be deleted while the scanner is running. If that happens the scanner would crash and restart but it makes for a noisy mess in the logs.
> Skip deleted documents in the scanner

- src/couch_replicator/src/couch_replicator_doc_processor.erl
- src/couch_replicator/test/eunit/couch_replicator_scheduler_docs_tests.erl
Previously, when mem3 failed such that it's shards ets table disappeared, while the replicator was processing doc updates, it was possible for the `couch_replicator_utils:owner/2` to raise `error:badarg` (passed through from the ets:* calls) to be registered as a malformed (failed) replicator doc update. After that, the replication job would be effectively stuck in the `failed` state until the user took action to re-create it.
To fix it, change the doc update callback to on only fail jobs on explicit replication doc parse failures (they have `throw({the bad_rep_doc, _}) exception pattern). In any other case let the exception crash the db changes feed and let the supervisor restart it.
> Prevent a broken mem3 app from permanently failing replication

- src/chttpd/src/chttpd_node.erl
- src/chttpd/test/eunit/chttpd_misc_test.erl
When a running Clouseau node is detected, expose a top level `search` field containing the version and search engine name in the `/_node/{node_name}/_versions` endpoint.
```
make eunit apps=chttpd suites=chttpd_mist_test tests=node_test_
```
> Expose Clouseau version in `/_node` endpoint

- src/docs/src/api/server/common.rst
Add documentation for optional `clouseau` section in `_versions` endpoint.
> Document `clouseau` in `_versions` endpoint

- share/server/util.js
- Use `for in` to fix syntax error when using SpiderMonkey 1.8.5
```
[2024-12-12T22:46:32.210Z] Failed to compile script.
[2024-12-12T22:46:32.210Z] SyntaxError: missing ; after for-loop initializer
[2024-12-12T22:46:32.210Z] Stacktrace:
[2024-12-12T22:46:32.210Z] 	@:0
```
- Add backward compatibility
Related PR: https://github.com/apache/couchdb/pull/5321
> Add SpiderMonkey backward compatibility

- src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl
- src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
Expand non-determinism handling to update handlers, filters, and vdus.
> Handle more non-determinism in update, filter and vdus

- Makefile
- Makefile.win
- mix.exs
- test/elixir/lib/step/start.ex
- test/elixir/lib/step/user.ex
- test/elixir/test/attachments_test.exs
- test/elixir/test/auth_lockout_test.exs
- test/elixir/test/basics_test.exs
- test/elixir/test/compact_test.exs
- test/elixir/test/design_docs_test.exs
- test/elixir/test/nouveau_test.exs
- test/elixir/test/replication_test.exs
- test/elixir/test/uuids_test.exs
- test/elixir/test/view_pagination_test.exs
Remove some warnings when running `make elixir`.
`make elixir`
> Bump Elixir version and fix warnings

- NOTICE
> Updated year in NOTICE

- src/couch/src/couch_file.erl
- src/couch/test/eunit/couch_file_tests.erl
Remove `pread_iolist/2`, `IS_OLD_STATE`, `close` cast handler and 0110 upgrade code.
Make `pread_binary/2` return a proper `{error, Error}` term instead of letting it crash with a `badmatch`. It was already documented to return an error tuple.
Implement `pread_binary` and `pread_terms` as instances of `pread_binaries` and `pread_terms`. This reduces code size quite a bit, as the gen_server now only has to handle `{pread_iolists, ...}` and `{append_binaries, ...}` as the main data path calls. Internally, Erlang/OTP VM may still fallback to non-vectorized pread and pwrite versions, but that's handled transparently. Besides, we never really handled it as a fallback anyway, it was just plain code duplication.
Fix bug in `{pread_iolists, ...}` call handler, where it incorrectly matched …
> Cleanup and improve couch_file

- .asf.yaml
Branches get auto-deleted upon PR merges to our default branch.
> chore(dev): Auto-delete branch upon PR merge

- src/couch/src/couch_file.erl
- src/couch/test/eunit/couch_file_tests.erl
It's an almost 10 year old, undocumented, and never worked properly. We tried using it at Cloudant once then promptly disabled it and never touched it again.
What usually reports corruption fairly well is the "read beyond eof" check. As such improve that error:
* Show the total bytes requested
* Show both the current record file position and the actual file size
In some cases we relied on badmatch for error reporting. Instead, use the early throw gen_server trick to return a proper error with a file path and position if pread fail.
> Remove pread_limit config from couch_file

- src/docs/src/api/database/find.rst
and remove some verbiage that looks terrible and is pointless.
> document nouveau type for mango index

- src/docs/src/whatsnew/3.4.rst
Shamelessly copied these from Jan's PR for 3.5.0 :-)
https://github.com/apache/couchdb/pull/5448
> Release notes for 3.4.3

- README.rst
Add links/logos to our CI sponsors.
> Showing sponsors

- src/nouveau/src/nouveau_api.erl
Retry if connection to nouveau is closed.
N/A
https://github.com/apache/couchdb/issues/5470
> nouveau: retry if connection closes

- src/couch_prometheus/src/couch_prometheus.erl
One of our users in #5485 reported they would like to be able have a more detailed picture of node connections and disconnections (are expected nodes connected or disconnected) in prometheus, so that's what this PR does.
We already used per-node metrics for dist channel stats so went with the same format: `{node="..."} 0/1`
```
couchdb_membership{nodes="cluster_nodes"} 3
couchdb_membership{nodes="all_nodes"} 3
couchdb_membership{node="node2@127.0.0.1"} 1
couchdb_membership{node="node3@127.0.0.1"} 1
couchdb_erlang_distribution_recv_oct_bytes_total{node="node2@127.0.0.1"} 40962
couchdb_erlang_distribution_recv_oct_bytes_total{node="node3@127.0.0.1"} 25681
```
Fix: #5485
> Add detailed node membership info to prometheus

- rebar.config.script
- src/exxhash/README.md
- src/exxhash/c_src/xxhash.h
Update both to latest tags / commits
> Update Fauxton and xxHash

- src/docs/src/api/server/common.rst
> doc: add https to allowed replication proxy protocols

- src/dreyfus/src/clouseau_rpc.erl
Add `check_service/1` `check_services/0` to check if clouseau services are alive.
Run CouchDB with Clouseau and run the following commands in remsh:
```bash
(node1@127.0.0.1)1> clouseau_rpc:check_services().
[{sup,alive},{main,alive},{analyzer,alive},{cleanup,alive}]
(node1@127.0.0.1)2> clouseau_rpc:check_service(init).
** exception throw: {not_found,<<"no such service: init">>}
in function  clouseau_rpc:check_service/1 (src/clouseau_rpc.erl, line 363)
(node1@127.0.0.1)3> clouseau_rpc:check_service(main).
{main,alive}
```
Run CouchDB only:
```bash
(node1@127.0.0.1)4> clouseau_rpc:check_services().
** exception throw: {noconnection,<<"Clouseau node is not connected.">>}
in function  clouseau_rpc:check_services/0 (src/clouseau_rpc.erl, line 378)
```
> Improve `clouseau_rpc.erl`

- src/couch/src/couch_db.erl
- src/couch/src/couch_util.erl
- src/mem3/src/mem3_reshard_job.erl
- src/nouveau/src/nouveau_bookmark.erl
- src/smoosh/src/smoosh_persist.erl
These are new in OTP 26 so we can simplify a few lines of code using them.
> Use maps comprehensions and generators in a few places

- src/docs/src/install/troubleshooting.rst
Thanks to @joan-morera for proving the answer in #4926
> Document how to mitigate high memory usage in docker

- src/fabric/src/fabric_db_create.erl
- src/mem3/src/mem3_httpd.erl
- src/mem3/src/mem3_reshard_dbdoc.erl
- src/mem3/src/mem3_util.erl
We were performing the same formatting logic in four places previously, so make it a utility function to DRY out the the code a bit.
> Add a range_to_hex/1 utility function

- src/mem3/src/mem3_sync.erl
Previously, if users updated their shard map and removed a node, it was possible for an in-progress internal replication job to be stuck forever trying to replicate to the now non-existent node.
To fix it, do what we did for dbs a while back -- if the db or nodes are not current, then stop trying to replicate to them.
Fix #5612
Thanks to @andres-mariano for reporting the issue!
> Stop replication jobs to nodes which are not part of the cluster

- src/couch/src/couch_bt_engine.erl
Our header pointer term operations seem a bit too verbose, so "DRY" them out a bit with some common functions. There is no new functionality added or changed, this is a pure refactoring.
During the refactoring, with all the plain atom field names, I had managed to slip through a few typos, so to help with that in the future, turned some of them into defines so the compiler can do the checking for us.
> DRY out couch_bt_engine header pointer term access

- build-aux/Jenkinsfile
> Add Trixie to CI
