apache/couchdb

rebar.config.script
This dependency is used in couch_replicator's test suite
COUCHDB-2540
=> Add meck dependency

Makefile
the attachments.js needs some files in place under _utils. In Futon times, they were just here. Now we have to provide them. When running attachments.js without having the files in place, at least one comparison test will fail (because Couch returns "Not found" instead of the test data).
=> Provide test data files for JS tests

Makefile, dev/run
Since `/_cluster_setup`  requires Admin Party to be fixed it's not suitable for running our JavaScript test suite which requires Admin Party to be on. So the old way to make a cluster is provided now as an option.
Also I a bit modified output to make it nicer and show all possible issues without making a look that it's hanged:
```
[ * ] Setup environment ... ok
[ * ] Ensure CouchDB is built ... ok
[ * ] Prepare configuration files ... ok
[ * ] Start node node1 ... ok
[ * ] Start node node2 ... ok
[ * ] Start node node3 ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... failed: <urlopen error [Errno 111] Connection refused>
[ * ] Check node at http://127.0.0.1:25984/ ... failed: <urlopen error [Errno 111] Connection refused>
[ * ] Check node at http://127.0.0.1:35984/ ... ok
[ * ] …
```
=> Use cluster setup in dev run

src/couchdb/couch_httpd_db.erl
Non-ASCII characters in the "Location:" header must be URL-encoded. This
can happen if a document is inserted with a user-defined "_id"
containing non-ASCII characters or if a filename contains non-ASCII
characters.
Fixes COUCHDB-2673
=> Properly escape Location: HTTP header

INSTALL.Unix
The current documentation doesn't ask to install package
libkjsapi4 as a dependency, which causes the following problem:
Compiling /home/ubuntu/Devel/couchdb/src/couch/priv/couch_js/http.c
/home/ubuntu/Devel/couchdb/src/couch/priv/couch_js/http.c:18:19: fatal error: jsapi.h: No such file or directory
#include <jsapi.h>
^
compilation terminated.
ERROR: compile failed while processing /home/ubuntu/Devel/couchdb/src/couch: rebar_abort
Makefile:22: recipe for target 'couch' failed
make: *** [couch] Error 1
This patch just fix the documentation and adds the package as a
dependency.
=> Fix documentation to add package libkjsapi4

INSTALL.Unix, INSTALL.Windows, configure.ac, share/doc/src/install/unix.rst, share/doc/src/install/windows.rst
Support OTP-18.0.
configure & make checks LGTM, would be nice if somebody can check a linux?
- OSX Yosemite 14.4.0 https://gist.github.com/dch/14fd8f57fd806d94a1de
- FreeBSD 10.1 amd64 https://gist.github.com/dch/2387359cd6c21b9f4de9
A few more warnings appear as expected, crypto & time stuff.
```
erlang:now/0 as we know
calendar:local_time_to_universal_time/1 -> calendar:local_time_to_universal_time_dst/1
crypto:sha_mac/2 -> crypto:hmac/3
crypto:sha/1 -> crypto:hash/2
crypto:md5_init/0 -> crypto:hash_init/1
crypto:md5_update/0 -> crypto:hash_update/1
crypto:md5_final/0 -> crypto:hash_final/1
```
=> build: support OTP-18.0

INSTALL.Unix, INSTALL.Windows, configure.ac, share/doc/src/config/http.rst, share/doc/src/couchapp/views/intro.rst, share/doc/src/install/unix.rst, share/doc/src/install/windows.rst, src/couchdb/couch_db.erl, src/couchdb/couch_db_updater.erl
We had been implicily assuming that clients send us sorted groups, but unsurprisingly that's not always the case. The PR here fixes a case where we broke the sorting, and adds an additional sort inside the `couch_db_updater` server loop since the consequences of screwing this up are so severe.
See [COUCHDB-2735](https://issues.apache.org/jira/browse/COUCHDB-2735).
=> Ensure PK uniqueness when merging updates from multiple clients

dev/run
This gives the option of specificing the seed number when generating the
node name and the port for that node.
e.g.
/dev/run --node-number 5
- node5@127.0.0.1 on port 55894
=> Add `--node-number` to /dev/run options

INSTALL.Unix.md, Makefile, README-DEV.md, configure
It's quite common issue when popular distributives ships rebar 2.0.0, which is heavily outdated and cannot build CouchDB. That means that we cannot recommend people to `apt-get install rebar` in general case. 
This PR adds a trick, that if rebar is missed or has bad version, configure script clones our rebar fork, builds rebar and uses it instead without disturbing user about. If system provides rebar of suitable version then things goes on as before.
cc @janl @micah
=> Install and use own rebar if it missed or has bad version

Makefile, rebar.config.script
This helps to silent error_logger, but only when https://github.com/apache/couchdb-couch-log-lager/pull/1 will get merged as well.
=> Use vm.args for rebar eunit run

configure.ac
Current method only works for versions numbers with only one decimal point. This version splits the version numbers on '.' and compares the elements converted to ints
=> Fix version checking for python pygments. 

dev/run
The dev/run file needs one more path to have backslashes replaced by forward slashes under Windows.
=> Fix a broken path in Windows

rebar.config.script
This adds the fix that fauxton will be correctly built with CouchDB
=> Upgrade fauxton to 1.1.2

test/javascript/couch_test_runner.js, test/javascript/tests/bulk_docs.js, test/javascript/tests/design_docs.js, test/javascript/tests/etags_views.js, test/javascript/tests/reader_acl.js, test/javascript/tests/recreate_doc.js, test/javascript/tests/replication.js, test/javascript/tests/security_validation.js, test/javascript/tests/show_documents.js, test/javascript/tests/users_db.js, test/javascript/tests/users_db_security.js, test/javascript/tests/view_include_docs.js, test/javascript/tests/view_multi_key_design.js, test/javascript/tests/view_offsets.js, test/javascript/tests/view_sandboxing.js
I did put in some more work to get the tests more stable - esp. replication.js (use random-generated databases throughout), the users_db / show_functions / and some other tests are back also. 
For n=1, it seems to be pretty stable already (also on lower computing power), for n=3 there's still work left (so is for the replication_db... tests; however: the core tests would be there already)
we should certainly merge after the RC1, any feedback is welcome still (it makes lots of sense to rebase after #400 and #401 is in - in fact merging them should be done before as this PR depends on them)
BTW: I sat down and drafted a short blog post on my lessons learned so far - any feedback highly welcome: https://gist.github.com/sebastianrothbucher/5e30ebbd98c64330f61ce87a9b8a4d00
=> More test improvements and stabilization

Dockerfile
* no need for backports
* rebar is built by ./configure
* useradd -m already creates home dir
=> update Dockerfile to debian jessie

rel/files/eunit.ini
This sets default security for the eunit tests to "everyone" to allow them pass again
=> Set default_security for the tests to everyone

dev/run
This is the source of my recent failure as documented on dev@couchdb.a.o.
Addresses COUCHDB-3040 but does not completely fix or close it.
=> Use UNIX-style paths for view servers on Windows

rel/overlay/bin/couchdb
Add `-config path/to/sys.config` argument to erlexec.
COUCHDB-2384
=> Point erl to sys.config file

dev/run
If connection succeeds eventually, don't report spurious error when retrying.
Turns `./dev/run` output from this:
```
[ * ] Check node at http://127.0.0.1:15984/ ... failed: [Errno socket error] [Errno 111] Connection refused
[ * ] Check node at http://127.0.0.1:25984/ ... ok
[ * ] Check node at http://127.0.0.1:35984/ ... ok
[ * ] Check node at http://127.0.0.1:15984/ ... ok
```
to this:
```
[ * ] Check node at http://127.0.0.1:15984/ ... ok
[ * ] Check node at http://127.0.0.1:25984/ ... ok
[ * ] Check node at http://127.0.0.1:35984/ ... ok
```
Cleaner and a bit less scary for new developers.
=> Clean up ./dev/run output

rel/overlay/etc/default.ini, rel/overlay/etc/local.ini
A comprehensive grep was run across the source code looking for
references to config:get* functions. This was used to remove any
config settings that no longer are used, and to add new defaults
set in the code explicitly to the ini files. Any newly added lines
were added only as *comments*.
One key change: local.ini still had the [httpd] block for port and
host bindings. As this applies to the "backend" binding and port
now, this section was renamed [chttpd] to ensure new users of 2.0
don't accidentally put their backend port on e.g. port 80.
Fixes COUCHDB-2623.
=> Update default/local ini files with new settings

README-DEV.rst, README.rst
Minor fixes to make sure the README and README-DEV files use proper ReST formatting. This improves the readability of these files *a lot* when they are viewed via the github website.
There was no content changed, just minor format changes.
=> README.rst, README-DEV.rst: Code should be in double backquotes

configure
The AppArmor rules provided by the mount-observe interface have been expanded to cover /bin/df
=> Provides access to check disk usage by calling the df command

rel/overlay/bin/couchdb
couchdb accepts command line arguments like -pidfile and -couch_ini, but they are ignored by bin/couchdb, this patch fixes it.
=> Support pass command line arguments to couchdb when it is called by bash script

test/javascript/run
Currently `test/javascript/run` always returns an exit code of `0`,
regardless of whether any tests fail or not. This makes any sort of
automated testing that expects to inspect the results of the run
invalid.
`make javascript` should now properly fail if any of the JS tests fail.
It also prints a numerical summary of passed/failed tests, similar to
the eunit results.
Fixes COUCHDB-3328
=> Count JS test pass/fails; return proper exit code

Makefile, Makefile.win, README-DEV.rst, Vagrantfile, build-aux/sphinx-build, configure.ps1, test/build/test-configure.sh
As discussed on the mailing list, this removes the PDF and info
builds from the default build.
Depends upon / relates to apache/couchdb-documentation#116 being merged.
Fixes COUCHDB-3329
=> Remove PDF, TeX/LaTeX and texinfo from the build chain

.gitignore, Makefile, configure, snapcfg/snap.ini, snapcfg/snap_run, snapcraft.yaml
Rather than creating a snap package from pre-build binaries, this allows building the snap package directly from source. Makes it possible to use external build automation such as build.snapcraft.io 
On any Ubuntu 16.04 or newer system, apt install "snapcraft" and then run "snapcraft snap" or "make snap". The resulting .snap file can be installed with "snap install --dangerous *.snap"
=> Change snap packaging to build from source

src/mem3/src/mem3_sync_event_listener.erl
The `should_restart_listener` test was failing because the pattern
supplied to meck was wrong. The argument to
`config_notifier:handle_event/2` is of the pattern `{config_change,
Section, Key, Value, Persist}` but the test was only matching a
four-tuple which I assume was missing the `config_change` atom in the
argument.
COUCHDB-3380
=> Fix mem3_sync_event_listener unit test

src/mango/rebar.config.script, src/mango/src/mango_cursor.erl, src/mango/src/mango_cursor_text.erl
The check for whether full text support in mango is available was broken
in that the mango_cursor_text module is only compiled if dreyfus exists
while the check to use the module was a runtime check. Thus is a user
were to add dreyfus after mango had been compiled it would have led to a
runtime error when we attempted to use a module that didn't exist.
This changes the check to a compile time check in both places. And now
that its a compile time define we can remove the need to rename source
files around which causes problems with source control seeing that file
change depending on local configuration.
COUCHDB-3378
=> Fix mango full text detection

src/couch_index/src/couch_index.erl, src/couch_index/src/couch_index_compactor.erl, src/couch_mrview/src/couch_mrview_compactor.erl, src/couch_mrview/src/couch_mrview_index.erl, src/couch_mrview/test/couch_mrview_compact_tests.erl
`couch_index` traps exits, but might get an EXIT message from a crashing mrview_compactor, while it only expects message from its own linked compact process.
This adds a new EXIT info handler to `couch_index_compactor` to prevent the compactor from crashing when a compacting process fails, and also cleans up the view compact file.
We have implemented a new couch_mrview_compact_test `should_remove` which verifies that a crash in the view compacting process doesn't also cause the index or compactor processes to crash. It also ensures `couch_mrview_compactor:remove_compacted/1` is called.
=> 3364 fix view compactor unknown info

src/chttpd/src/chttpd_db.erl, src/chttpd/test/chttpd_db_test.erl, src/couch/src/couch_httpd_db.erl
Prior to the change in this PR, one new document was unexpectedly created after a request is issued to delete attachment on non-existent document. This PR is aimed to address this to return 404 (Not Found) instead of creating new document. 
The newly introduced test case `should_return_404_for_delete_att_on_notadoc` covers the steps to test the change in this PR. In addition, two additional test cases `should_return_409_for_del_att_without_rev` and `should_return_200_for_del_att_with_rev` are introduced to make sure that there is no regression.
```
chttpd db tests
chttpd_db_test:71: should_return_ok_true_on_bulk_update...[0.107 s] ok
chttpd_db_test:86: should_accept_live_as_an_alias_for_continuous...[0.054 s] ok
chttpd_db_test:107: …
```
=> Avoid creation of document if deleting attachment on non-existent doc

src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_test_util.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_mrview/test/couch_mrview_local_docs_tests.erl
This fixes the following issues with `/{db}/_local_docs` endpoint:
1. Query ignores include_docs parameter
2. Query reports incorrect total_rows value, returning total rows for non-local docs instead
3. Query crashes with badrecord when trying to skip records, e.g. when start_key not the first local doc
**This is a rebase of https://github.com/apache/couchdb-couch-mrview/pull/72 which was not merged prior to monorepo coalescence.**
Eunit tests included
COUCHDB-3337
=> Fix _local_docs endpoint

src/couch_replicator/test/couch_replicator_small_max_request_size_target.erl
These tests were disabled because they weren't passing, but the underlying issue has since been fixed. 
This commit re-enables the tests.
=> Re-enable attachment replication tests

src/mem3/src/mem3_shards.erl
There were two issues with mem3_shards that were fixed while I've been testing the PSE code.
The first issue was found by Jay Doane where a database can have its shards inserted into the cache after its been deleted. This can happen if a client does a rapid CREATE/DELETE/GET cycle on a database. The fix for this is to track the changes feed update sequence from the changes feed listener and only insert shard maps that come from a client that has read as recent of an update_seq as mem3_shards.
The second issue found during heavy benchmarking was that large shard maps (in the Q>=128 range) can quite easily cause mem3_shards to backup when there's a thundering herd attempting to open the database. There's no coordination among workers trying to add a shard map to the cache so if a bunch of …
=> Couchdb 3376 fix mem3 shards

rel/overlay/bin/couchup
This commit adds a new Python-based database migration tool, `couchup`.
It is intended to be used at the command-line on the server being
upgraded, before bringing the node (or cluster) into service.
`couchup` provides 4 sub-commands to assist in the migration process:
* `list` - lists all CouchDB 1.x databases
* `replicate` - replicates one or more 1.x databases to CouchDB 2.x
* `rebuild` - rebuilds one or more CouchDB 2.x views
* `delete` - deletes one or more CouchDB 1.x databases
A typical workflow for a single-node upgrade process would look like:
```sh
$ couchup list
$ couchup replicate -a
$ couchup rebuild -a
$ couchup delete -a
```
A clustered upgrade process would be the same, but must be preceded by
setting up all the nodes in the cluster first.
Various optional arguments …
=> New couchup 1.x -> 2.x database migration tool

src/couch/src/couch_db_updater.erl, src/couch/src/couch_file.erl, src/couch/src/couch_server.erl, src/couch/test/couchdb_views_tests.erl
This would revert following commits:
- https://github.com/apache/couchdb/commit/92c25a98666e59ca497fa5732a81e771ff52e07d: Add sys_dbs to the LRU  
- https://github.com/apache/couchdb/commit/2d984b59ed6886a179fd500efe9780a0d0ad62e3: fix compiler and dialyzer warnings
Turns out this commits exhibit bad behavior causing `couch_server` message queue backup in the case when there are many `_replicator` databases in the system.
This brings the old version of the code which known to be working. Therefore the risk is minimal. Running test suite should suffice.
It is related to [COUCHDB-3325](https://issues.apache.org/jira/browse/COUCHDB-3325)
None
=> Revert add sys dbs to lru

Makefile.win
A similar change has already been made to *nix Makefile already.
This is for the Javascript integration test suite to not timeout
when running in Travis. We don't run Windows tests in Travis but
this should speed things a bit, and it's nice to keep both in
sync.
Jira: COUCHDB-3324
Javascript replication test suite should run faster than before this change.
https://github.com/apache/couchdb/pull/470
This needs manual testing from someone with access to Windows machine
=> Disabling replication startup jitter in Windows makefile

build-aux/print-committerlist.sh
- pulls comitternames out of subrepos
- uses local variables instead of globals
- makes use of our .mailmap file in our main repo
- composable: just source it and pipe it into your process
usage in `couchdb-build-release.sh`:
``` sh
sed -e "/^#.*/d" THANKS.in > $RELDIR/THANKS
source "build-aux/print-committerlist.sh"
print_comitter_list >> THANKS;
```
suggested reviewer: @janl
=> build: pull authors out of subrepos

src/mem3/src/mem3_util.erl
During mem3 startup, 2 paths attempt to call `couch_server:create/2` on
`_dbs`:
```
gen_server:init_it/6
-> mem3_shards:init/1
-> mem3_shards:get_update_seq/0
-> couch_server:create/2
```
and
```
mem3_sync:initial_sync/1
-> mem3_shards:fold/2
-> couch_server:create/2
```
Normally, the first path completes before the second. If the second path
finishes first, the first path fails because it does not expect a
`file_exists` response.
This patch simply retries mem3_util:ensure_exists/1 once if it gets back
a `file_exists` response. Any failures past this point are not handled.
Fixes COUCHDB-3402.
/cc @davisp @nickva
=> Fix error on race condition in mem3 startup

src/couch_replicator/src/couch_replicator.erl
=> Fix `badarg` when querying replicator's _scheduler/docs endpoint

src/couch/src/couch_multidb_changes.erl
This is bringing back previous code:
https://github.com/apache/couchdb/blob/884cf3e55f77ab1a5f26dc7202ce21771062eae6/src/couch_replicator_manager.erl#L940-L946
The rationale is the following: during shard scanning a lot of `resume_scan`
messages are sent back to back. This causes the replicator manager to open
change feeds for all of those shards. By delaying `resume_scan` message by
a jitter proportional to the number messages sent to far, it gives replicator
manager a chance to open some change feeds, finish processing them and close
them before newer resume_scan messages arrive.
The random delay average starts 10 msec for first message, up to 1 min for 6000th and higher.
Some sample values:
* For 100 messages, average wait will be 1 second
* For 1000 - 10 seconds
* For 6000 and higher …
=> Apply random jitter during initial _replicator shard discovery

.travis.yml
Travis has 2 build environments: containerised and VM based.  Right now
`sudo:false` selects containers, while `sudo:required` selects the VM
based. Container-based builds guarantee 2 CPU cores and boot faster.
We've been using the latter because we needed a bunch of
`apt-get install` commands. But Travis added native (non-sudo) support
to install packages in containers, and we didn't notice.
This PR switches us to `sudo:false` and uses the new `apt` block to
install required packages.
The PR also updates our Erlang build matrix, using the latest minor
release of each major version we support, and prepares us to enable
IRC notifications to `#couchdb-dev` once the test suite is reliable
again (currently disabled.)
Check the Travis build results on this PR. It is passing.
=> Switch to using Travis containerised builds, update Erlang versions

src/mango/src/mango_cursor_special.erl, src/mango/src/mango_cursor_view.erl, src/mango/test/12-use-correct-index.py
If two indexes can be used, then instead of choosing the index based on
alphabet order of index names, rather choose based on a score. This
score is calculated by determining which index has the least number of
fields
There is a test that proves the issue and passes based on this fix.
https://issues.apache.org/jira/browse/COUCHDB-3357
=> Choose index based on fields match

src/couch/src/couch_stream.erl
In COUCHDB-1946 Adam Kocoloski investigated a memory explosion resulting
from replication of databases with large attachments (npm fullfat). He
was able to stabilize memory usage to a much lower level by hibernating
couch_stream after each write. While this increases CPU utilization when
writing attachments, it should help reduce memory utilization.
This patch is the single change that affected a ~70% reduction in
memory.
No alteration to the spawn of couch_stream to change the fullsweep_after
setting has been made, in part because this can be adjusted at the erl
command line if desired (-erl ERL_FULLSWEEP_AFTER 0).
Replicate a database with a lot of attachments and observe memory usage with and without this patch.
COUCHDB-1946
=> Hibernate couch_stream after each write

src/couch_replicator/src/couch_replicator_httpd.erl
Handle non-default _replicator dbs in _scheduler/docs endpoint.
Previously _scheduler/docs assumed only the default _replicator db.
To provide consistency and to allow disambiguation between a db named
'db/_replicator' and the document named 'db/_replicator' in the
default replicator db, access to the single document API is changed to
always require the replicator db. That is `/docid` should not be
`/_replicator/docid`.
Now these kinds of paths are accepted after `_scheduler/docs`:
* `/` : all docs from default _replicator db
* `/_replicator` : all docs from default replicator db
* `/other%2f_replicator` : non-default replicator db, urlencoded
* `/other/_replicator` : non-default replicator db, unencoded
* `/other%2f_replicator/docid` : doc from a non-default db, urlencoded
* …
=> Handle non-default _replicator dbs in _scheduler/docs endpoint

src/mango/src/mango_selector.erl, src/mango/test/03-operator-test.py
Currently if we have a document like this:
```
doc = {
name: 'Garren',
activities: []
};
```
and then create a selector like this:
```
find({selector: {
activities: {
$allMatch: {
['fishing', 'golf']
}
}
});
```
CouchDB mango will return the above document. This doesn't seem correct since it doesn't actually match the `$allMatch` selector. This PR changes that so that an empty document is false.
There is an additional test added to the Mango tests to prove this works.
=> Return false for empty list

src/mem3/src/mem3_shards.erl
This adds a test to ensure that the changes_listener process exits when
the mem3_shards process is shut down.
N/A
COUCHDB-3398
=> Test changes_listener dies on mem3_shards shutdown

.gitignore, .travis.yml, build-aux/logfile-uploader.py, test/javascript/run
This commit is intended to improve failure analysis in Travis and
Jenkins runs by uploading couch log files after failed test runs.
A new script has been added that, upon invocation from the top-level
directory, tars up all EUnit logfiles and the `dev/logs/node1.log` file.
It then constructs a document based on the running environment (Travis,
Jenkins, manual). The document is posted to a CouchDB instance running
on couchdb-vm.apache.org with credentials passed in the COUCHAUTH
environment variable.
The `.travis.yml` file has been updated to install the script's
prerequisites (python-requests) and with the secret credentials, and to
instruct travis to run the log uploader after any test failure. Similar
steps will be taken to reconfigure Jenkins after these changes are
merged to master. …
=> Add auto log uploader for CI workflow

src/chttpd/test/chttpd_db_test.erl
Add test case to see what trips up this test case in COUCHDB 3415.
This could be as simple as a newline character, but I want to make sure.
This needs to run in CI for a bit until it pops up again.
https://issues.apache.org/jira/browse/COUCHDB-3415
=> chore: add debugging for failing test case, see COUCHDB-3415

src/chttpd/test/chttpd_db_doc_size_tests.erl
Add test case to see what trips up this test case in COUCHDB 3413.
I assume it is one where the cluster returns a 500 error.
This needs to run in CI for a bit until it pops up again.
https://issues.apache.org/jira/browse/COUCHDB-3413
=> chore: add debugging for failing test case, see COUCHDB-3413

src/couch_replicator/test/couch_replicator_compact_tests.erl
Double the timeout for pausing the source writer.
https://issues.apache.org/jira/browse/COUCHDB-3384
****
=> chore: increase timeout for pausing writer COUCHDB-3384

INSTALL.Unix.md
This updates a link to SpiderMonkey release page in INSTALL.Unix.md.
Link in INSTALL.Unix.md "Dependencies" section to "Mozilla SpiderMonkey (1.8.5)" should point to existing page for SpiderMonkey release 1.8.5
This closes #530
=> Fix link to SpiderMonkey in INSTALL.Unix.md

src/couch_replicator/test/couch_replicator_compact_tests.erl
Previously the test relied in the assumption that there are no
couch_tasks which are running concurrently. This commit fixes that assumption
by filtering out all non replication related tasks from the output of
`couch_task_status:all()`.
make eunit apps=couch_replicator
=> Filter out non replicator tasks in test case

src/couch_index/test/couch_index_compaction_tests.erl
Databases are closed asynchronously. However it was not accounted for in
the test case. This commit waits database to close before it makes a
decision to abort the test. It uses default timeout of 5 sec.
I.e. if test case detects that database is still opened after 5 sec
it considers it as failure.
make eunit apps=couch_index tests=compaction_test
=> Whait db close a little bit before failing test

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, README.rst
We're getting ready to move from JIRA to GH Issues. This PR removes references to JIRA and expands our user experience by adding or updating a CONTRIBUTING.md file and GH Issue and PR templates. It also updates the README file to reflect these changes.
Similar PRs are being issued in all repos officially hosted on GitHub:
* apache/couchdb
* apache/couchdb-docker
* apache/couchdb-documentation
* apache/couchdb-fauxton
* apache/couchdb-nano
* apache/couchdb-pkg
=> Add/update contribution guidelines, issue/PR templates for GH Issues

src/couch_replicator/src/couch_replicator_scheduler.erl
That was the intent all along, just forgot to enable before the merge.
Start a 3 node dev cluster.  Query any of the node's top level API:
```
http http://adm:pass@localhost:15984
{
"couchdb": "Welcome",
"features": [
"scheduler"
],
"vendor": {
"name": "The Apache Software Foundation"
},
"version": "2.1.0-a9ad3429e"
}
```
=> Expose replicator scheduler feature in the API

src/chttpd/test/chttpd_db_doc_size_tests.erl, src/chttpd/test/chttpd_db_test.erl, src/chttpd/test/chttpd_open_revs_error_test.erl, src/chttpd/test/chttpd_welcome_test.erl, src/couch/test/couch_db_mpr_tests.erl, src/couch/test/couchdb_auth_tests.erl, src/couch/test/couchdb_mrview_cors_tests.erl, src/couch/test/couchdb_mrview_tests.erl, src/couch/test/global_changes_tests.erl, src/couch_peruser/test/couch_peruser_test.erl
couch_server is responsible for calling hash_admin_passwords whenever
"admin" section of config changes. However as you can see it from
[here](https://github.com/apache/couchdb/blob/master/src/couch/src/couch_server.erl#L219)
the call is asynchronous. This means that our test cases might fail when
we try to use admin user while admin password is not yet hashed.
make eunit
=> Make sure we cache admin pass prior to test run

src/couch_replicator/src/couch_replicator_api_wrap.erl
COUCHDB-3426
Send a better error message when the replicator attempts to open a database it is not authorised to open.
Create a user, create a database, change the security object of the database to exclude the user, then ask the replicator to replicate to that database as the user. You should see a 'forbidden' message in _scheduler/jobs instead of the misleading db_not_found message we currently send.
=> Send a better error when opening a db without authorisation

Jenkinsfile, build-aux/logfile-uploader.py
Our Jenkins setup has been using the traditional Jenkins definition, with a job driven by a shell script sitting in the apache/couchdb-ci repository, and a further script baked into each Docker image. To maintain the build process, ~8GB of new images have to be pushed to Docker Hub, which isn't practical or scalable.
We also now have requests to have Jenkins securely drive our binary deployment process, by triggering .deb/.rpm/Docker/snap builds. With a classic Jenkins job, we have to use dependent/downstream builds to trigger this behaviour, requiring more manual setup in the Jenkins web UI that is difficult to maintain.
This PR adds a Jenkinsfile that uses the new declarative pipeline syntax introduced to Jenkins in February 2017.  It's similar to a .travis.yml file but with additional …
=> Jenkinsfile for multibranch pipeline build

src/couch/src/test_request.erl
Currently it is impossible to pass authentication options to
test_request:request. This commit exports request/5 which accept options
argument.
=> Export test_request:request/5 function

src/couch/src/couch_db_updater.erl, src/couch_mrview/src/couch_mrview_compactor.erl
To predict future compaction results, we log pre-compaction and
post-compaction file sizes. These log results will be used as data
points for regression analysis.
COUCHDB-3417
Users sometimes want to know the results of compaction and how much disk space will be freed up. Unfortunately, using simply data size and disk size to calculate this prediction is misleading due to conflicts and attachments. This approach logs disk size pre and post compaction for db and view shard files. The hope is that with enough data points, users can run regression analysis to heuristically determine a compaction result.
To see the output, one can connect to a node and run compaction on db or view to see the log result. 
```{ok, Db} = couch_db:open(<<"shards/00000000-1fffffff/mydb.1494471596">>, []).``` …
=> Add Compaction Logging

src/couch/src/couch_bt_engine.erl, src/couch/src/couch_db_updater.erl, src/couch/src/test_engine_util.erl
Previously local doc revisions were integers. Keep them that way to allow
downgrading back to previous CouchDB version.
This was issue was discovered by @eiri
=> Fix compatibility with master local document revisions

src/couch_index/src/couch_index.erl, src/couch_index/src/couch_index_server.erl, src/couch_index/test/couch_index_ddoc_updated_tests.erl
Before when a design doc is updated/deleted, only one couch_index process
was notified - the one which shard contained a design doc.
couch_index processes from other shards still continued to exist,
and indexing activities for these processes were still be going on.
The patch notifies couch_index_processes on all shards
`make check apps=couch_index tests=ddoc_update_test_`
[COUCHDB-3400](https://issues.apache.org/jira/browse/COUCHDB-3400)
=> notify couch_index_processes on all shards when ddoc updated

test/javascript/couch_test_runner.js, test/javascript/test_setup.js
restartServer() is still erroring out sometimes in Travis/Jenkins. This
PR both bumps the timeout to 15s as well as changes the detection
mechanism for restart to look for the uptime in _system to reset to a
low number.
This PR also removes the eclipsed redundant restartServer() definition
in couch_test_runner.js.
Closes #553
=> Improve JS test harness restartServer() support fn

rebar.config.script, src/ddoc_cache/src/ddoc_cache_sup.erl
Currently it is impossible to disable the ddoc_cache by specifying `-ddoc_cache max_objects 0` in `vm.args`. This allows such a configuration, paired with a similar change in `ets_lru`.
Add `-ddoc_cache max_objects 0` in `vm.args` and start up couch. It should run correctly.
Related to #559 but does not fix it.
https://github.com/apache/couchdb-ets-lru/pull/4
=> Allow ddoc_cache to be fully disabled

test/javascript/couch_test_runner.js, test/javascript/tests/show_documents.js
The full discussion is in #559, but here is a summary.
Through instrumentation of ddoc_cache and ets_lru I suspect that this is
caused by cache eviction happening after the second GET. While I didn't
instrument exactly where the GET occurs it's clear that it's fairly
late, certainly after the PUT 201 is returned, and likely after the
subsequent GET actually reads from ddoc_cache.
After applying a change to allow me to completely disable the ddoc_cache
(-ddoc_cache max_objects 0 in vm.args) I ran the test on a loop
overnight, and the test never failed (>1000 executions). Previously the
test would fail every 20-30 executions.
TL;DR: we can't guarantee immediate ddoc_cache eviction on a ddoc
update, even for a single .couch file on a single node. (For obvious
reasons we definitely can't …
=> Disable unstable JS _show ETag test

dev/run
https://github.com/apache/couchdb-setup/pull/4
=> add node count handling to ./dev/run

src/couch/test/couchdb_views_tests.erl
Test branch/PR for https://github.com/apache/couchdb/issues/552#issuecomment-305909995
=> feat(test): wait for db and index shutdown

src/couch/src/test_engine_fold_changes.erl, src/couch/src/test_engine_fold_docs.erl
Adds tests to fold_changes and fold_docs to check if deleted are
included or excluded.
=> Test if deleted docs are included/excluded when folding

src/couch_mrview/src/couch_mrview_util.erl
A change in apache/couchdb#576 made any unexpected return from functions called in `get_view_index_state/4` to be presented as `badmatch` and hide the real error.
This unwraps the `badmatch` and re-throw it as an original response.
A test suite `make javascript suites=view_errorsjs`should pass.
Bug introduced in apache/couchdb#576
=> Don't wrap real error in `badmatch` exception

src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_show.erl, src/couch_mrview/src/couch_mrview_show.erl
This fixes encoding issues in responses on following requests:
- PUT: {db}/{design}/_update/{update}/{doc_id}
- PUT: {db}/{doc_id}/{att_id}
The tests would be added in a separate PR
=> Fix encoding issues

rel/overlay/etc/default.ini, src/couch/src/couch_changes.erl
With certain data sets, performance of the `_changes` feed with the `doc_ids` filter falls off a cliff when the number of supplied `doc_ids` exceeds 100.
This change allows configuration of the poor performance threshold:
```
[changes]
max_doc_ids = 100
```
```
[changes]
max_doc_ids = 0
```
```
[changes]
max_doc_ids = 10000
```
Get a big dataset, and compare the performance of `_changes` requests with the `doc_ids` filter when:
```
[changes]
max_doc_ids = 0
```
and
```
[changes]
max_doc_ids = 100
```
with 100 or less doc_ids.
Fixes: https://issues.apache.org/jira/browse/COUCHDB-3425
Related: https://issues.apache.org/jira/browse/COUCHDB-1288
Just this one.
=> Allow configuration of max doc IDs for optimised code path in changes filter

src/couch/src/couch_att.erl
Previously attachment uploading from a PSE to non-PSE node would
fail as the attachment streaming API changed between version.
This commit handles downgrading attachment streams from PSE nodes so that
non-PSE nodes can write them.
=> Handle attachments downgrades in a mixed cluster environment

src/mango/src/mango_selector.erl
length(Values) is O(n) operation. Which could get expensive for long
lists. Change the code to rely on pattern matching to detect non empty
lists.
=> Avoid using length to detect non empty list

src/couch/src/couch_db_updater.erl, src/couch/src/couch_file.erl, src/couch/src/couch_server.erl, src/couch/src/couch_util.erl
Previously idle dbs, especially sys dbs like _replicator once opened
once for scanning would stay open forever. In a large cluster with many
_replicator shards that can add up to a significant overhead, mostly in terms
of number of active processes.
Add a mechanism to close dbs which have an idle db updater. Before hibernation
was used to limit the memory pressure, however that is often not enough.
Some databases are only read periodically so their updater would time
out. To prevent that from happening keep the last read timestamp in
the couch file process dictionary. Idle check then avoid closing dbs
which have been recently read from.
(Original idea for using timeouts in gen_server replies belongs to
Paul Davis)
COUCHDB-3323
Related to previous PR from before monorepo merge: …
=> Close idle dbs

src/couch/src/couch_btree.erl
As it turns out, the original change in COUCHDB-3298 ends up hurting
disk usage when a view emits large amounts of data (i.e., more than
half of the btree chunk size). The cause for this is that instead of
writing single element nodes it would instead prefer to write kv nodes
with three elements. While normally we might prefer this in memory, it
turns out that our append only storage this causes a significantly more
amount of trash on disk.
We can show this with a few trivial examples. Imagine we write KV's a
through f. The two following patterns show the nodes as we write each
new kv.
Before 3298:
[]
[a]
[a, b]
[a, b]', [c]
[a, b]', [c, d]
[a, b]', [c, d]', [e]
[a, b]', [c, d]', [e, f]
After 3298:
[]
[a]
[a, b]
[a, b, c]
[a, b]', [c, d]
[a, b]', [c, d, e]
[a, b]', [c, d]', [e, f]
The …
=> Couchdb 3298 optimize writing btree nodes

src/couch/test/couchdb_os_daemons_tests.erl
Even if it clean up fails use `kill` to avoid failing the next set of tests.
Issue: #571
=> Properly kill OS daemons during test

src/couch_mrview/src/couch_mrview_test_util.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_mrview/test/couch_mrview_changes_since_tests.erl
Prior to the change in this PR, most test cases in two test suites `changes_since_test_` and `changes_index_test_` failed to execute. They were disabled. Considering different scope and historical reason, this PR is aimed to address failure from `changes_since_test_` test suites. The test suite `changes_index_test_` will be another story.
The change not only includes test code, but also includes minor change of couch_mrview_util.erl to satisfy required pattern matches.
```
module 'couch_mrview_changes_since_tests'
changes_since tests
couch_mrview_changes_since_tests:109: test_basic...ok
couch_mrview_changes_since_tests:132: test_basic_since...ok
couch_mrview_changes_since_tests:145: test_basic_count...ok …
```
=> Fix broken eunit test in changes_since_test_ test suite

src/couch/src/couch_io_logger.erl, src/couch/src/couch_os_process.erl
Logging is based on an environment variable:
`COUCHDB_IO_LOG_DIR`
If set, logs will go to that directory.
Logs are per `couch_os_process` Erlang process. There are 3 files saved for
each process:
```
<unixtimestamp>_<erlangpid>.in.log : Input, data coming from the proess
<unixtimestamp>_<erlangpid>.out.log : Output, data going to the process
<unixtimestamp>_<erlangpid>.meta : Error reason
```
Log files are saved as named (visible) files only if an error occurs. If there
is no error, disk space will still be used as long the process is alive. But as
soon as it exists, file will be unlinked and space will be reclaimed.
Issue: #551
=> Log OS process I/O

.travis.yml, Jenkinsfile, build-aux/logfile-uploader.py
Enabled OS process IO logging by setting `COUCHDB_IO_LOG_DIR=/tmp/couchjslogs`
Both Travis and Jenkins then clear and create that directory before tests run.
Also `logfile-uploader.py` was the modified to upload any log files from that directory.
Issue #551
=> Enable OS process IO logging + upload for Travis and Jenkins tests

src/chttpd/src/chttpd.erl, src/chttpd/test/chttpd_db_test.erl, test/javascript/tests/attachments.js
Currently we return a 500 and something like
`{"error":"{not_found,missing}","reason":"{1,<<\"000\">>}"}`
when an attempt is made to put an attachment document with a
non-existent revision.
This changes the behavior to return a 409 and
`{"error":"not_found","reason":"missing_rev"}"`
Test is included with PR
=> Return 409 when put attachment with nonexistent rev

src/couch/test/couchdb_views_tests.erl
There are a race condition in `restore_backup_db_file` function between couch_server eviction of an old db updater and a test quering view on restored db file. The query in test can get old record for the updater and then crash with `noproc` exception.
This change makes `restore_backup_db_file` to wait until start of the new db updater.
The following should pass:
`make eunit apps=couch suites=couchdb_views_tests tests=backup_restore_test_`
Fixes #565
=> Fix race in couchdb_views_tests

src/mango/src/mango_native_proc.erl
When indexing a set of fields for text search, we also create a special
field called $fieldnames. It contains values for all the fields that
need to be indexed. In order to do that, we need a unique list of the
form [[<<"$fieldnames">>, Name, []] | Rest]. The old code would add an
element to the list, and then check for membership via lists:member/2.
This is inefficient. Some documents can contain a large number of
fields, so we will use gb_sets to create a unique set of fields, and
then extract out the field names.
An alternative is to just use lists:usort/1. For small sets, it would be more efficient,
but if a document is large enough thousands of fields, gb_sets seems to perform
more. The tradeoff is that while gb_set could take longer overall for indexing,
it could reduce the …
=> Use efficient set storage for field names

src/couch_replicator/src/couch_replicator_changes_reader.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_worker.erl
Previously there was a race between reporting the source update  sequence
between the the workers and the changes readers. Each one used separate
incrementing timestamp sequences.
In some cases that lead to pending changes being stuck. For example, if changes
reader reported the highest sequence with timestamp 10000, then later workers
reported it with sequences 5000, 5001, 5002, then all those reports would be
ignored and users would see an always lagging pending changes value reported
with timestamp 1000.
The fix is to thread the last_sequence update through the changes queue to
the changes manager, so only its timestamp sequence will be used. This removes
the race condition.
=> Ensure replicator _active_tasks entry reports recent pending changes

CONTRIBUTING.md
Also, there was a typo in the gitbox URL.
This is a minor documentation change.
=> Update CONTRIBUTING.md to reflect monorepo

src/mem3/src/mem3.erl
To decom a node, one normally inserts {"decom":true} into that node's
document via the admin /nodes endpoint. However, it's easy to
accidentally insert {"decom":"true"} instead, in which case the
current mem3 allowed_nodes logic will include that node as allowed,
which is probably not what was intended, and ultimately result in "500
badard" errors sent to the client.
This changes the allowed_nodes algorithm to also accept {"decom":"true"}
to decom a node.
Thanks to Nick Vatamaniuc for discovering this shortcoming.
I've included a new unit test for this code, but I wonder if it's more trouble than it's worth.
=> Also enable node decom using string "true"

test/javascript/tests/design_docs.js
This test case is failing because of late ddoc_cache eviction.
It'd be nice to validate that we correctly invalidate our
cached CommonJS modules, but ddoc_cache makes such a test
infeasible.
See https://github.com/apache/couchdb/commit/85cfc71beb089c7881959c2ac7699b9b35b0f04b#diff-f2fc11abc651cc0b4e99643c85f2a5f6 as well as #559 for more detail.
Closes #632
=> Remove yet another invalid test case (ddoc_cache related)

test/javascript/couch.js
[Issue 548](https://github.com/apache/couchdb/issues/548) points out that tests fail randomly when using ad-hoc queries (i.e. create a design doc, query it, remove it again). Though I can't reproduce it (not even by doing this cycle three times in a row without wait in-between), there is a solution by simply adding comments to the map function (hence changing the signature, allowing two otherwise similar views to co-exist. As it's hardly production relevant (design docs likely won't and probably shouldn't be created and removed all the time - it's a performance no-go in most cases), we actually get *better* tests as they really indicate if things go wrong (instead of failing randomly and being ignored after some time).
In short: improves the quality of javascript tests
This IS a test …
=> Make map functions distinct with each invocation

dev/run, rel/overlay/etc/default.ini, src/couch/test/couchdb_compaction_daemon_tests.erl
This is the #1 potential user footgun we ship by default. Especially with `_global_changes` coming on the scene, this becomes quite the annoying issue. Pro-users can easily disable it, most users will want to have it enabled.
=> Enable compaction daemon by default

src/couch_replicator/src/couch_replicator_changes_reader.erl
The size of the tuple was changed in all clauses of process_change but one.
Remove TS argument from `#doc_info{id = <<>>}` clause of process_change.
make eunit
=> Fix couch_replicator_changes_reader:process_change

dev/run, test/javascript/tests/config.js, test/javascript/tests/delayed_commits.js, test/javascript/tests/proxyauth.js, test/javascript/tests/reader_acl.js, test/javascript/tests/replication.js, test/javascript/tests/rev_stemming.js, test/javascript/tests/rewrite.js, test/javascript/tests/rewrite_js.js, test/javascript/tests/security_validation.js, test/javascript/tests/stats.js
This PR includes 3 small commits to fix up the JS test suite:
1. Really, truly disable the compaction daemon. (The previous approach wasn't working.)
2. Ensure that every JS test cleans up after itself, removing all old databases before exiting.
3. Disable the flaky `stats.js` test, which needs a complete rewrite to make sense. It was my fault re-enabling it even partially for 2.0. Sorry.
`make javascript` and look for all passes.
=> JS test cleanup x3

src/chttpd/src/chttpd_show.erl, src/chttpd/src/chttpd_view.erl, src/fabric/src/fabric.erl, src/fabric/src/fabric_view_map.erl
We don't set db open options to `fabric_view_map` and missing `user_ctx` when opening databases. For admin-only database we inject `user_ctx` for after doc check, pulling it from passed accumulator with assumption it is always `#vacc` record. This is incorrect in case of `list` or `mango` queries and breaks fabric abstraction, where it is spec'ed for acc to be type `any()`
This patch allows to pass db open options  and `user_ctx` along with it to `fabric:query_view/7` and modifies chttpd show and view handlers accordingly.
Javascript test suite should pass:
```
make javascript
```
For manual check on admin-only database the following should work:
```
echo '{"name": "demo", "password": "apple", "roles": [], "type": "user"}' | curl -u $CRED …
```
=> Pass db open options to fabric_view_map

src/couch/src/test_util.erl
Commit 21f9544 enabled the compaction daemon by default. And commit
3afe3ad disabled the compaction daemon at the start of the compaction
daemon tests. Unfortunately, the compaction daemon remains active during
all the other EUnit tests. This has resulted in some strange behaviour,
especially filling the LRU up and `all_dbs_active` errors during tests
that shouludn't be hitting it otherwise (like
`couchdb_views_tests:couchdb_1283` which monkeys with max_dbs_open ).
I attempted to override the [compactions] _default line in the file
rel/files/eunit.ini but specifying `_default=` or `_default=[]` did not
provide the desired behaviour. (This in and of itself is worrying; how would
someone disable the compaction daemon in `local.ini` now?)
This change disables the _default config as part of …
=> Disable compaction daemon on eunit run couch startups

src/couch/src/couch_event_sup.erl
Because `stop/1` is asynchronous, and casts a stop message and as result the
client process could end getting killed during termination/cleanup phase if
this sequence of events took place:
1. Client calls `stop(ListerPid).`
2. couch_event_sup casts a `stop` message to couch_event_sup gen_server
3. `stop` message is delayed and client continues executing.
4. Client calls something like application:stop/1`.
5. `application:stop/1` terminates couch_event_sup gen_server.
6. App termination kills client process because it is still linked.
So this make the stop synchrounous by using call instead of cast.
Issue #644
=> Make couch_event_sup:stop/1 synchronous

src/couch/src/couch_native_process.erl, src/couch/test/couchdb_os_proc_pool.erl
This is a fix for #631. Basically just replacse the couchjs processes with couch_native_proc instances since we're just worried about how the proc manager behaves rather than anything to do with JavaScript.
=> 631 fix os proc pool eunit

src/couch_index/src/couch_index.erl, src/couch_index/src/couch_index_updater.erl
=> 649 fix mrview changes since test

src/couch/test/couchdb_views_tests.erl
=> Fix timeout in couchdb_views_test for couchdb_1283

src/mango/src/mango_cursor_view.erl, src/mango/src/mango_httpd.erl, src/mango/src/mango_util.erl, src/mango/test/13-users-db-find-test.py, src/mango/test/mango.py, src/mango/test/user_docs.py
We don't pass `UserCtx` in `fabric:all_docs/4` call in mango's view query which doesn't matter most of the times, except when we need to check admin credentials to return documents as in case of the queries against `_users`database. As a result we are getting back `null` as a body of the documents and crash. 
Steps described in apache/couchdb#535 shouldn't crash with `case_clause`, but should return a proper document.
Fixes #535
=> Pass UserCtx to fabric's all_docs from mango query

INSTALL.Unix.md
This matches what we do in couchdb-pkg, where we always install to `/opt/couchdb`. It also matches where the Docker images place CouchDB.
Also includes pointers to couchdb-pkg daemon scripts.
=> Change recommended install path to /opt/couchdb

test/javascript/tests/replication.js
The test was flaky for a variety of reasons:
* waitForSeq only waited for 3 seconds and on failure it never explitly
indicated an error and just waited for the comparison below to fail. So made
it wait for 30 seconds and also throw an exception right away if it fails.
* Last waitForSeq was used after task was canceled. So it just wasted time
waiting until timeout as the task was null. So created a function to
wait for task to be null.
* waitForSeq spun in a tight do/while loop querying _active_tasks. In some test
environment with minimal CPU resources that's not the greatest thing to do.
So made it wait for 0.5 seconds between retries.
* waitForSeq waited for replication task's through_seq value to match source
update sequence from source db info. Those don't necessarily match. Instead …
=> Fix replication Javascript test

src/couch/src/couch_os_daemons.erl, src/couch/test/couchdb_os_daemons_tests.erl
Fix flaky os daemons tests
The "should die" test was close to the edge of timing out. Daemon started up,
slept for 1 second then died. However max_retries is 3 so the whole thing was
happening 3 times in a row. The total wait was 4 seconds, but on slow machines
1 extra second was not enough for the overhead of forking the 3 processes and
other setup stuff.
Set restart times to 2. Hopefully 4 seconds should be enough overhead for 2
restarts.
Also adjust sleep time for the "die quickly" test. 1 second there might not
be enough for both restarts, so made it 2 just to be safe.
Also in a separate commit, remove unused TIMEOUT macro from os daemons module
=> Fix flaky os daemons tests

src/couch/src/couch_db.erl, src/couch/src/couch_db_updater.erl, src/couch/test/couchdb_file_compression_tests.erl
In two places where we calculate the ExternalSize of the document body,
we use the Summary which is a compressed version of the doc body. We
change this to use the actual ejson body. In copy_docs we don't have
access to the #doc record so we can't access the meta where we store
the ejson body. Unfortunately, this means we have to decompress the
document body after reading it from disk.
Performance tests were conducted to compare pre-fix External Size values and post-fix External Size Values. Here are the results:
```
Version        Compression    DB Dize      DB External Size
Pre-Fix         snappy            70 MB        46249702       
Pre-Fix         snappy            700 MB      462495533       
Pre-Fix         snappy            2.1 GB        1387486406      
Post-Fix       snappy …
```
=> Use Ejson Body Instead of Compressed Body for External size

src/couch/test/couchdb_file_compression_tests.erl, src/couch_mrview/src/couch_mrview_util.erl
Previously, we were calculating the ExternalSize for views by summing
up all the nodes in the btree. Furthermore, this was the compressed
size. Now we modify the reduce function to return an ExternalSize for
uncompressed values in the KVList.
Performance tests were run to compare External Size Info pre-fix and post-fix.
```
Version        Compression    DB Dize     View External Size
Pre-Fix         snappy            70 MB        26123231     
Pre-Fix         snappy            700 MB      493542711    
Pre-Fix         snappy            2.1 GB       795168531   
Post-Fix       snappy            70 MB        81775342
Post-Fix       snappy            700 MB      818752126        
Post-Fix       snappy            2.1 GB       2457701744       
Pre-Fix         deflate_6        70 MB …
```
=> Calculate ExternalSize Correctly for Views

src/mem3/src/mem3_sync_security.erl, src/mem3/test/mem3_sync_security_test.erl
If dbs do not exist, we catch the error for mem3_sync_security
so that it can continue for databases that do exist.
Eunit Tests added.
COUCHDB-3423
=> Catch Database Do Not Exist Error

src/mango/src/mango_cursor_view.erl, src/mango/src/mango_opts.erl, src/mango/test/13-stable-update-test.py, src/mango/test/mango.py
This brings mango inline with views by supporting the new options
`stable` and `update`.
Fixes #621
See the test for an example on how to test. I'm not really sure of a way to test the `stable` option.
#621
=> Add stable and update support to Mango

src/couch/src/couch_db.erl, src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_http.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_mrview/test/couch_mrview_local_docs_tests.erl, src/fabric/src/fabric_view_all_docs.erl
This is a second attempt to fix `_local_docs` end-point. The [previous one](https://github.com/apache/couchdb/pull/488) didn't work on big enough btree_local, because local btree doesn't have reduction fun, so reuse of `couch_db_updater:btree_by_id_reduce/2` was crashing on a bad match as soon as btree_local was getting kp_node. Also using full fold to calculate `total_rows` value turned out to be resource expensive when a database have significant number of local documents.
This fix avoids calculating of `total_rows` and `offset` instead always setting them to `null` and also setting to `null` `update_seq` when requested, since it doesn't have meaning in context of local documents.
A fabric module `fabric_view_all_docs.erl` was copied and modified as `fabric_view_local_docs.erl`, because …
=> Fix  _local_docs end-point

src/couch/src/couch_changes.erl
"couch_changes.erl:33: Warning: function wait_updated/3 already exported"
=> fix double export of wait_updated/3

src/chttpd/test/chttpd_security_tests.erl
This fixes the problematic test case which was failing in the case when users db exists.
Run `make eunit apps=chttpd tests=all_test` twice
=> 3367 fix test case

src/mem3/test/mem3_util_test.erl
The config:stop is asynchronous which causes test failures with error
like the following
```
{error,{already_started,<0.32662.3>}
```
This is rather hard to test since it is a flaky test. Just make sure that it doesn't make things worse by calling `make eunit apps=mem3 tests=n_val_tes`
=> Use test_util:stop_config in mem3_util_test

src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/test/couch_replicator_compact_tests.erl
This was used from a test only and it wasn't reliable. Because of replicator
job delays initialization the `State` would be either #rep_state{} or #rep. If
replication job hasn't finished initializing, then state would be #rep{} and a
call like get_details which matches the state with #rep_state{] would fail with
the badmatch error.
As seen in issue #686
So remove `get_details` call and let the test rely on task polling as all other
tests do.
=> Remove get_details replicator job gen_server call

test/javascript/tests/replication.js
Replication cancelation doesn't immediately update active tasks. Instead, use
the new `waitReplicationTaskStop(rep_id)` function to propery wait for the
task status.
Issue #634
=> Fix cancellation race in replication.js tests

src/couch/test/couchdb_compaction_daemon_tests.erl
Opening this as a PR so that it gets built by CI to try and diagnose #674. This isn't intended to actually be merged (unless I can't get a failure then maybe I will so it'll be around when that test eventually does fail again).
=> TMP: Add debug logging for failed assertion

src/couch_replicator/test/couch_replicator_large_atts_tests.erl, src/couch_replicator/test/couch_replicator_small_max_request_size_target.erl
Could reproduce issue #633 by limiting disk throughput in a VBox
VM instance to about 5KB. Try to increase the timeouts to let it
handle such apparent slowdowns.
Fixed #633
=> Increase timeout of some replication tests

NOTICE
=> Explicitly mention Facebook "BSD+Patents" license in NOTICE per LEGAL-303

src/couch_peruser/test/couch_peruser_test.erl
The test was repeatedly creating/deleting the exact same DB
name, which is a recipe for disaster. Changed to use unique
DB names.
Closes #705.
=> Fix couch_peruser EUnit test

src/couch/test/couchdb_os_daemons_tests.erl
Looks like an oversight in commit 789f75d.
Closes #703.
=> Do not persist restart times setting in os_daemons_tests

src/couch/test/couch_changes_tests.erl, src/couch/test/couchdb_file_compression_tests.erl, src/couch/test/couchdb_os_daemons_tests.erl, src/couch/test/couchdb_update_conflicts_tests.erl, src/couch/test/couchdb_views_tests.erl, src/couch_replicator/test/couch_replicator_small_max_request_size_target.erl
Several eunit tests tend to fail by timing out when run on
travis-ci. This change increases timeouts on the more commonly failing
tests, and improves test robustness.
=> Increase various eunit test timeouts

src/couch_replicator/src/couch_replicator_httpc.erl, src/couch_replicator/test/couch_replicator_small_max_request_size_target.erl
Disable flaky 413 replication test
It is possible that sometimes a multipart/related PUT with a doc and
an attachment would fail with the connection being un-expectedly
closed before the client (ibrowse) gets to parse the 413 error
response.
That makes the test flaky so it is disabled for now.
In some cases such as when replicator flushes a document received from an
open_revs response, it explicitly sets the number of retries to 0 because
the context for that request might not be restartable and the retry should
happen at a higher level
=> Disable flaky max request size replication test and fix a retry httpc issue

src/chttpd/src/chttpd.erl, src/couch_index/src/couch_index.erl, src/couch_index/src/couch_index_server.erl, src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_index.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_mrview/test/couch_mrview_ddoc_updated_tests.erl, src/fabric/src/fabric_rpc.erl, src/fabric/src/fabric_util.erl, src/fabric/src/fabric_view_map.erl, src/fabric/src/fabric_view_reduce.erl
Currently when ddoc is updated, couch_index and couch_index_updater processes
corresponding to the previous version of ddoc will still exist until
all indexing processing initiated by them is done.
When ddoc of a big database is rapidly modified, this puts a lot
of unnecessary strain on database.
With this change, when ddoc is updated:
* all couch_index processes for the previous version of ddoc will be shutdown
* all linked to them couch_index_updater processes will die as well
* all processes waiting for indexing activity to be finished (waiters
for couch_index:get_status) will receive an immediate reply:
ddoc_updated. Interactive user requests (view queries) will get response:
{404, <<"not_found">>, <<"Design document was updated or deleted.">>}
When design document is updated, stop …
=> Stop indexing activity on ddoc update

src/couch_replicator/test/couch_replicator_compact_tests.erl
Also decrease number of rounds from 5 to 3.
With:
`VBoxManage bandwidthctl ${VM} set Limit --limit 100K`
It needed over 400 seconds to pass with 5 rounds.
Fixes #725
=> Increase timeouts in replicator compactor tests

src/couch_replicator/src/couch_replicator_scheduler_job.erl
Previously, if the replication id algorithm was updated, replicator would
migrate checkpoint documents but keep them in memory. They would be written to
their respective databases only if checkpoints need to be updated, which
doesn't happen unless the source database changes. As a result it was possible
for checkpoints to be lost. Here is how it could happen:
1. Checkpoints were created for current (3) version of the replicator document.
Assume the replication document contains some credentials that look like
'adm:pass', and the computed v3 replication id is "3abc...".
2. Replication id algorithm is updated to version 4. Version 4 ignores
passwords, such that changing authentication from 'adm:pass' to 'adm:pass2'
would not change the replication ids.
3. Server code is updated with version …
=> Save migrated replicator checkpoint documents immediately

src/couch_replicator/src/couch_replicator.hrl, src/couch_replicator/src/couch_replicator_ids.erl
Replications checkpoint to _local documents identified by replication ids. If
replication ids change replication tasks will not be able to find their
previous checkpoints and will rewind their change feeds back to 0. For a large
database that could mean reprocessing millions of documents.
Current version of replication id generation algorithm hashes the full url of
the source, target, their headers, including authorization ones as well, and a
few other things. This means when user changes their password and updates their
replication document, replication ids will change and all the checkpoint will
be invalidated.
Also, it is fairly common to upgrade services from http:// to https://.
Replication endpoint URIs then typically just change their schema part
accordingly. However, schema is …
=> Make replication ID generation more robust. 

rel/overlay/etc/default.ini, src/couch/src/couch_db_updater.erl, src/ddoc_cache/src/ddoc_cache.erl, src/ddoc_cache/src/ddoc_cache.hrl, src/ddoc_cache/src/ddoc_cache_entry.erl, src/ddoc_cache/src/ddoc_cache_entry_custom.erl, src/ddoc_cache/src/ddoc_cache_entry_ddocid.erl, src/ddoc_cache/src/ddoc_cache_entry_ddocid_rev.erl, src/ddoc_cache/src/ddoc_cache_entry_validation_funs.erl, src/ddoc_cache/src/ddoc_cache_lru.erl, src/ddoc_cache/src/ddoc_cache_opener.erl, src/ddoc_cache/src/ddoc_cache_sup.erl, src/ddoc_cache/src/ddoc_cache_value.erl, src/ddoc_cache/test/ddoc_cache_basic_test.erl, src/ddoc_cache/test/ddoc_cache_coverage_test.erl, src/ddoc_cache/test/ddoc_cache_disabled_test.erl, src/ddoc_cache/test/ddoc_cache_entry_test.erl, src/ddoc_cache/test/ddoc_cache_ev.erl, src/ddoc_cache/test/ddoc_cache_eviction_test.erl, src/ddoc_cache/test/ddoc_cache_lru_test.erl, src/ddoc_cache/test/ddoc_cache_no_cache_test.erl, src/ddoc_cache/test/ddoc_cache_open_error_test.erl, src/ddoc_cache/test/ddoc_cache_opener_test.erl, src/ddoc_cache/test/ddoc_cache_refresh_test.erl, src/ddoc_cache/test/ddoc_cache_remove_test.erl, src/ddoc_cache/test/ddoc_cache_test.hrl, src/ddoc_cache/test/ddoc_cache_tutil.erl, test/javascript/tests/rewrite.js
The previous version of ddoc_cache was written to rely on evicting
entries after a maximum TTL. This leads to issues on clusters that have
a large amount of load on databases with a large Q. What ends up
happening is that when a design document is evicted we suddenly have a
thundering herd scenario as every client attempts to reinsert it into
the cache.
This change instead relies on a monitor process for each cache entry
that periodically attempts to refresh the cache. This way normal clients
accessing a popular design document will never hit a point where it
doesn't exist in cache. And we'll have at most one reader trying to
write the value.
make eunit apps=ddoc_cache
You'll find its got 100% test coverage if you enable cover.
One note on the tests that's a bit different than other …
=> Optimize ddoc cache

src/couch/test/couch_auth_cache_tests.erl
The test was racy. Use test_util:wait/1 function there just like other
places like couch_index_compaction_tests
Fixes #724
=> Fix timeout in couch auth test

src/couch_epi/test/couch_epi_tests.erl
Sleeps there not enough when run in a contrained test environment
Adjust timeouts to let tests pass even when setting CPU usage limit down to
1% in my VirtualBox VM.
Also switch to using macro defines to make it look slightly cleaner.
Fixes #731
=> Fix timeouts in couch epi tests

src/couch_replicator/src/couch_replicator_js_functions.hrl
Previously when updating the document with the error or failed states
the document body will not pass the validation function and will
consequently crash either the scheduler or the doc processor.
=> Allow replicator application to always update replicator docs

src/chttpd/src/chttpd.erl
This introduces a new `error_info` clause which allows "503 service unavailable" to be returned to clients.
=> Allow a 503 response to be thrown

src/couch_epi/src/couch_epi.app.src.script
couch_epi calls crypto functions since 9e56cf334c33d4cdb96acbfca9cc9461e2b658aa so should ensure the app is started first.
=> couch_epi depends on crypto app

src/couch/priv/stats_descriptions.cfg
The 503 response was added recently. We need to update the `stats_description.cfg` to include this new return code in order to avoid `"unknown metric: [couchdb,httpd_status_codes,503]"` errors from [here](https://github.com/apache/couchdb/blob/master/src/chttpd/src/chttpd.erl#L1127).
=> Add [couchdb, httpd_status_codes, 503] metric

src/mango/src/mango_idx_text.erl, src/mango/test/07-text-custom-field-list-test.py
The function indexable_fields/1 is supposed to remove extraneous fields
created by the mango_selector_text:convert/1 function so that indexes
will not be bypassed during index selection time. This wasn't working
as expected in the case of $in when the user did not explicitly specify
an array at index time. In fact, we had two different results depending
on whether or not users used all_fields or explicilty specified a
field. Before if you only specified {"name" : "age", "type : "number"}
as a field, you could not query for {"age" : {"$in" : [2, 3]}}. You
had to explicitly add {"name" : "age.[]", "type : "number"} to your
list of indexes so the $in would work. This fixes the scenario and now
should work as expected
Automated Tests added
Github Issue is this PR
=> Fix incorrect indexable_fields for $in

src/mango/src/mango_cursor.hrl, src/mango/src/mango_cursor_special.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_error.erl, src/mango/src/mango_json_bookmark.erl, src/mango/test/14-json-pagination.py
This adds a bookmark that is sent with each query and can be used to
continue a query from a specific key. This will allow users to paginate
mango queries.
=> Add Bookmark support for mango json queries

src/rexi/src/rexi_server.erl
This improve the log messages from rexi. It adds flowing info:
- nonce
- node originator of the request
- mfa of the function called
- client Pid
=> Log additional information on crashes from rexi

src/chttpd/test/chttpd_security_tests.erl
We are setting custom "authentication_db" in `chttpd_security_tests`, but making this change persistent in `eunit.ini` config. As a result the rest of the tests expecting this temporary database to be a proper authentication database and getting background `chttpd_auth_cache` crashes with `database_does_not_exist` exception on attempt to pull `_design/_auth` .
Before:
```bash
$ make clean
$ grep authentication_db tmp/etc/*
grep: tmp/etc/*: No such file or directory
$ make eunit apps=chttpd suites=chttpd_security_tests skip_deps=couch_epi
...
[done in 8.694 s]
=======================================================
All 8 tests passed.
$ grep authentication_db tmp/etc/*
tmp/etc/default_eunit.ini:; authentication_db = _users
tmp/etc/default_eunit.ini:authentication_db = _users …
```
=> Fix leaking chttpd's security tests config

src/chttpd/test/chttpd_db_doc_size_tests.erl, src/chttpd/test/chttpd_open_revs_error_test.erl
Some tests in `chttpd_db_doc_size_tests` and `chttpd_open_revs_error_test` specified incorrectly leading to actual assertions not to be run and the tests throwing warning on first compilation.
This change fixes those tests and doing some general house cleaning.
On `make clean; make eunit apps=chttpd` no warnings should be printed and all the tests should pass.
Before:
```bash
$ make clean
$ make eunit apps=chttpd suites=chttpd_db_doc_size_tests
...
Compiled test/chttpd_db_test.erl
/home/vagrant/git/couchdb/src/chttpd/test/chttpd_db_doc_size_tests.erl:49: Warning: variable 'Else' is unused
/home/vagrant/git/couchdb/src/chttpd/test/chttpd_db_doc_size_tests.erl:121: Warning: a term is constructed, but never used
/home/vagrant/git/couchdb/src/chttpd/test/chttpd_db_doc_size_tests.erl:125: …
```
=> Fix chttpd's tests warnings

test/build/test-run-couch-for-mango.sh
When tests run on Travis they run on Ubuntu where /bin/sh is dash, so bash
specific syntax will throw errors.
Make script more generic by using [ for tests. Also double quotes as suggested:
http://mywiki.wooledge.org/Bashism
Also remove a trailing whitespace and fix final newline
=> Cleanup mango test runner script

src/couch/src/couch_debug.erl
This adds few useful debug tools.
1. List a cluster of linked processes. This function receives the
initial Pid to start from. The function doesn't recurse to pids
older than initial one.
```
167> couch_debug:print_linked_processes(whereis(couch_index_server)).
name                                         | reductions | message_queue_len |  memory
couch_index_server[<0.288.0>]                |   478240   |         0         |  109696
couch_index:init/1[<0.3520.22>]            |    4899    |         0         |  109456
couch_file:init/1[<0.886.22>]            |   11973    |         0         |  67984
couch_index:init/1[<0.3520.22>]        |    4899    |         0         |  109456
couch_index_updater:init/1[<0.3550.22>]  |   19671    |         0         |  26408 …
```
=> Add a debugging utilities for listing processes

src/mango/src/mango_cursor_text.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_execution_stats.erl, src/mango/src/mango_execution_stats.hrl, src/mango/src/mango_httpd.erl, src/mango/src/mango_opts.erl, src/mango/test/15-execution-stats-test.py, src/mango/test/mango.py
Accept an "execution_stats" parameter to _find. If present, return a new "execution_stats" object in the response which contains information about the query executed. Currently, this is only
implemented for json/all_docs indexes and contains:
* total key lookups
* total document lookups (when include_docs=true used)
* total quorum document lookups (when fabric doc lookups used)
Query `_find` with different selectors. Add `"execution_stats":true` to the request body and see that an `"execution_stats"` field is returned. Test with different index types.
This PR adds new unit tests for the execution stats and existing behaviour is already well covered by tests.
=> basic execution statistics for _find

src/mango/src/mango_cursor_view.erl, src/mango/test/02-basic-find-test.py
`_explain` previously returned the options passed in by the user but
not those modified at execution time by Mango. Now we include
index-specific options (mrargs for map/reduce indexes) in the output,
allowing us to see e.g. when include_docs was used.
Manually test by making a request to the `_explain` endpoint from the command line / Fauxton. When a query is fulfilled by a `json` index, you should see an `mrargs` field in the output.
Unit tests should provide good coverage.
=> include mrview options in _explain result

src/chttpd/src/chttpd_show.erl, test/javascript/tests/users_db_security.js
A request to view's `_show` supposed to work on admin-only databases, such as `_users` when accessed with admin's privileges. This fix passes user context to fabric's `open_doc` allowing this to happen.
Included tests could be run as `make javascript suites=users_db_security`
Also "Steps to Reproduce" from issue #653 should now work as expected.
Fixes #653
=> Pass user context when opening a doc in show handler

src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/test/couch_mrview_ddoc_validation_tests.erl
Previously only `views` sections could have a `lib` object. But some users
might choose to have a library for filters for example.
This makes it agree with this section of the wiki:
https://wiki.apache.org/couchdb/CommonJS_Modules
=> Allow libs in other design doc sections besides views

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/test/chttpd_db_attachment_size_tests.erl, src/couch/src/couch_att.erl, src/couch/src/couch_doc.erl, src/couch/src/couch_httpd.erl, src/couch/test/couch_doc_tests.erl, src/couch/test/couchdb_attachments_tests.erl, src/couch_replicator/src/couch_replicator_api_wrap.erl, src/couch_replicator/test/couch_replicator_attachments_too_large.erl, src/fabric/src/fabric_doc_attachments.erl, src/fabric/src/fabric_doc_update.erl
Currently CouchDB has configurable single document body size limits, as well as
http request body limits, and this commit implements attachment size limit.
Maximum attachment size can be configured with:
```
[couchdb]
max_attachment_size = Bytes | infinity
```
`infinity` (i.e. no maximum) is the default value it also preserves the current
behavior.
Fixes #769
=> Implement attachment size limits

src/mango/test/03-operator-test.py, src/mango/test/mango.py, src/mango/test/user_docs.py
Mango operator tests previously only ran against json indexes. This PR ensures they also run against a database with no indexes (i.e. verify "pure" selector behaviour) as well as against json indexes and text indexes (when available). The intention here is to catch any inconsistencies or change in results that might occur due to the index selected (clearly we don't want results to change because a user adds an index!).
Note that text indexes do not currently pass these tests, but are not exercised as part of the CouchDB test suite.
Ensure the test suite runs (CI should handle this).
=> Query operator tests for multiple index types

src/mango/src/mango_cursor.erl, src/mango/src/mango_cursor_text.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_httpd.erl, src/mango/test/12-use-correct-index.py
Previously, index selection for a given query was run twice for each request - once to add
a warning in case a full database scan would be performed and then again when the query was executed.
This moves the warning generation so that it occurs at the end of the query processing and we can use the existing index context to decide whether to add a warning or not.
Whilst only a minor optimisation (which also assumes we don't have cached query plans etc), it
at least moves index selection to where one might expect it to happen i.e. during query planning.
Added a unit test to cover that a warning is appropriately generated. The text index tests should also be run manually.
=> Avoid duplicate index selection in Mango

src/mango/src/mango_error.erl, src/mango/src/mango_httpd.erl, src/mango/test/05-index-selection-test.py
Fixes a regression where a 500 status code was returned when  no index is available to service a _find query because the  sort order does not match any available indexes. This was actually a general issue with _find errors, introduced when index selection moved from `mango_cursor.erl` to `mango_idx.erl` in https://github.com/apache/couchdb-mango/commit/01252f971bef0c8da1d78bf5a7b506b71926ce1b.
In a separate commit, I converted the index selection tests to use `unittest` assertion functions and addressed an issue with a duplicate test name.
Changes covered by unit tests
=> Fix Mango error handling

src/couch/src/couch_compaction_daemon.erl
If the compaction daemon cannot calculate the free space
for a volume, do not crash CouchDB. Instead, log a warning
that free space could not be calculated and continue.
Compaction of the database is not necessarily prevented -
just that the disk space for this specific volume
won't be taken into account when deciding whether
to automatically compact or not.
This is primarily to cope with edge cases arising from
ERL-343, whereby disksup:get_disk_data() returns invalid
paths for volumes containing whitespace, and impacts Erlang 19.x and 20.x.
On MacOS, the error can be reproduced under Erlang 19 by creating a mount point with whitespace (e.g. mounting an installer) and forcing the compaction daemon to run.
#732
=> Do not crash when free space cannot be calculated

rel/overlay/etc/default.ini, src/chttpd/test/chttpd_db_doc_size_tests.erl, src/couch/src/couch_doc.erl, src/couch/src/couch_ejson_size.erl, src/couch/test/couch_ejson_size_tests.erl
max_document_size currently checks document sizes based on Erlang's external
term size of the jiffy-decoded document body. This makes sense because that's
what used to store the data on disk and it's what manipulated by the CouchDB
internals.
However erlang term size is not always a good approximation of the size of json
encoded data. Sometimes it can be way off (I've seen 30% off) and It's hard for
users to estimate or check the external term size beforehand. So for example if
max_document_size is 1MB, CouchDB might reject user's 600KB json document
because Erlang's external term size of that document greater than 1MB.
To fix the issue provide a module which calculates the encoded size of a json
document.
Issue #659
* Opened this is an alternative to …
=> Provide a more accurate size check for max_document_size limit

dev/run
When a JS test requested a restart server we would wip the current log
file. This makes it hard to debug failing tests occasionally when they
happen just after a restart. This change prevents just opens log files
in read/write mode specifically when a test requests a server restart.
The current behavior for interactive use of `dev/run` will continue to
truncate log files on startup.
=> Don't reset logs when JS tests restart the server

src/mango/src/mango_cursor.erl, src/mango/src/mango_idx.erl, src/mango/src/mango_idx_view.erl, src/mango/src/mango_native_proc.erl, src/mango/test/16-index-selectors.py, src/mango/test/mango.py
Adds selector support to json indexes. The selector can be used to
filter what documents are added to the index. When executing a query
the index will only be used if the index is specified in the use_index
field.
=> Add selector support for json indexes

src/couch/src/couch_att.erl, test/javascript/tests/attachments.js
We trust inline attachment to be base64 encoded, so in case it's not provided or invalidly encoded the upload request crashes with `function_clause`.
The change catches decode attempt and re-throws it as 400 error.
Standard eunit and javascript tests should pass.
Fixes #784
=> Don't crash on invalid inline attachments

src/mango/src/mango_idx_view.erl, src/mango/src/mango_selector.erl, src/mango/test/03-operator-test.py, src/mango/test/05-index-selection-test.py, src/mango/test/user_docs.py
JSON index selection in Mango previously deemed an index to be usable if a range scan on the first component of its compound key could be generated from the query selector.
For instance, if I had an index:
[A, B]
is_usable would return true for the selector:
{"A": "foo"}
This is incorrect because JSON indexes only index documents that contain all the fields in the index; null values are ok, but the field must be present. That means that for the above selector, the index would implicitly include only documents where B exists, missing documents where {"A":5} matched but field B was not present.
This commit changes is_usable so that it only returns true if all the keys in the index are required to exist by the selector. This means that in the worst case e.g. none of the predicates can be …
=> Fix mango json index selection

.travis.yml, Makefile, README-DEV.rst
This will force everyone to run the Mango tests with the default
`make check` command, which will also enable it to be run as part
of the Jenkins tests as well. (We were already running these test
in Travis.)
Be forewarned: some of the Mango tests are not reliable and will
need fixup and support soon.
=> Run mango tests with make check

src/mango/src/mango_cursor.erl, src/mango/src/mango_idx.erl, src/mango/src/mango_idx_text.erl, src/mango/src/mango_idx_view.erl, src/mango/src/mango_native_proc.erl, src/mango/test/16-index-selectors.py, src/mango/test/mango.py
To make it easier to distinguish between a selector in _find and a
selector in _index. Rename the selector in the _index to
partialfilterselector. It also gives a bit more of an explanation of
what this selector does.
=> Rename selector to partialfilterselector in indexes

src/couch/include/couch_db.hrl, src/couch/src/couch_compress.erl, src/couch/src/couch_db_updater.erl, src/couch/test/couch_compress_tests.erl, src/couch/test/couchdb_file_compression_tests.erl
Use snappy's `uncompressed_length` and external binary format's binary spec to
get uncompressed size.
http://erlang.org/doc/apps/erts/erl_ext_dist.html
=> Avoid decompressing just to calculate external size

src/couch_replicator/src/couch_replicator_clustering.erl, src/mem3/src/mem3_cluster.erl, src/mem3/test/mem3_cluster_test.erl, src/rexi/src/rexi_server_mon.erl
Instead wait 15 seconds after last cluster configuration change, if there
were no more changes to the cluster, stop rexi buffers and servers for nodes
which are no longer connected.
Extract and reuse cluster stability check from `couch_replicator_clustering`
and move it to `mem3_cluster` module, so both replicator and rexi can use it.
Users of `mem3_cluster` would implement a behavior callback API then spawn_link
the cluster monitor with their specific period values.
This also simplifies the logic in rexi_server_mon as it no longer needs to
handle `{nodeup, _}` and `{nodedown, _}` messages. On any cluster membership
change it will get a `cluster_unstable` message. It then immediately spawns new
servers and buffers if needed. Only when cluster has stabilized it will stop
servers and …
=> Do not buffer rexi messages to disconnected nodes

rel/overlay/etc/default.ini, src/couch_replicator/src/couch_replicator_api_wrap.hrl, src/couch_replicator/src/couch_replicator_docs.erl
Previously an individual failed request would be tried 10 times in a row with
an exponential backoff starting at 0.25 seconds. So the intervals in seconds
would be:
`0.25, 0.5, 1, 2, 4, 8, 16, 32, 64, 128`
For a total of about 250 seconds (or about 4 minutes). This made sense before
the scheduling replicator because if a replication job had crashed in the
startup phase enough times it would not be retried anymore. With a scheduling
replicator, it makes more sense to stop the whole task, and let the scheduling
replicatgor retry later. `retries_per_request` then becomes something used
mainly for short intermettent network issues.
The new retry schedule is
`0.25, 0.5, 1, 2, 4`
Or about 8 seconds.
An additional benefit when the job is stopped quicker, the user can find out
about the problem …
=> Reduce replicator.retries_per_request value from 10 to 5

configure, rel/overlay/bin/remsh
To make this work, I had to change the default -name from the old
couchdb@localhost to couchdb@127.0.0.1. This matches the advice
we already had in vm.args to use FQDN or IP address, anyway.
Once this merges I'll look at doing a Windows version, if possible.
=> Add convenience remsh bash script

src/couch_replicator/src/couch_replicator_scheduler_job.erl
Previously replicator was unnesessarily verbose during crashes. This commit
reduces the vorbosity and make the error messages more helpful.
Most of the replication failures happen in the startup phase when both target
and source are opened. That's a good place to handle common errors, and there
were a few already handled (db not found, lack of authorization). This commit
adds another other common one - inability to resolve endpoint host names. This
covers cases were there user mistypes the host name or there is a DNS issue.
Also during the startup phase, if an error occurs a stacktrace was logged in
addition to the whole state of the #rep{} record. Most of the rep record and
the stack are not that useful compared to how much noise it generates. So
instead, log only a few relevant fields …
=> Clean up replicator logs

rel/overlay/bin/remsh
As requested by @janl . Tested on FreeBSD.
=> Remove bashisms in remsh script

rebar.config.script, src/fabric/rebar.config
Folsom depended on 0.8.2 as well so had to update folsom and bump its tag.
=> Update meck to latest version 0.8.8

src/ddoc_cache/test/ddoc_cache_refresh_test.erl
Replaced with crypto:strong_rand_bytes
Also fixed a missing newline at the end of file.
=> Replace deprecated crypto:rand_bytes call

src/chttpd/src/chttpd_db.erl, src/couch/src/couch_doc.erl, src/couch/src/couch_httpd_db.erl, src/couch/test/couch_doc_json_tests.erl, src/couch/test/couch_doc_tests.erl
Currently, it is impossible to PUT/POST modified shard maps to any
`_dbs/_*` document because the document _ids are reserved. This change
permits these specific db/docid combinations as valid, so PUT/POST
operations can succeed. The specific list comes from SYSTEM_DATABASES.
Unit tests have been added.
Closes #858
=> Whitelist system DB names as valid _dbs docids

src/mango/src/mango_cursor_view.erl, src/mango/test/15-execution-stats-test.py
Mango execution stats previously incremented the result count
at a point where the final result might be discarded. Instead,
increment the count when we know the result is being included
in the response.
Test Mango queries with a limit and that the results_returned in the execution stats matches the number of rows in the response.
=> Correct result count in Mango execution stats

src/couch/rebar.config.script, src/couch/src/couch_debug.erl, src/couch/src/couch_multidb_changes.erl, src/couch/src/couch_rand.erl, src/couch/src/couch_util.erl, src/couch/test/couch_btree_tests.erl, src/couch/test/couch_file_tests.erl, src/couch_log/test/couch_log_test.erl, src/couch_replicator/src/couch_replicator_doc_processor.erl, src/couch_replicator/src/couch_replicator_docs.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/ddoc_cache/test/ddoc_cache_lru_test.erl
Replace with util compatibility functions which use `crypto:rand_uniform/2`
`crypto:rand_uniform/2` will also be deprecated in the future, hopefully by
then we'd move to 18 as the minimum version.
=> Remove usage of deprecated random module.

rebar.config.script
To fix `random` module compatibility issue
=> Bump khash, b64, ioq deps

.travis.yml, rebar.config.script, src/couch/test/couchdb_attachments_tests.erl
The first commit fixes attachments tests to properly account for zlib deflate returning some data before the final chunk.
The second commit enables 20.0 compatibility in rebar.config and also set Travis up to test it.
=> Fix attachments test also 20.0 seems a-ok

src/couch/src/couch_query_servers.erl, src/couch_mrview/src/couch_mrview_http.erl, src/fabric/src/fabric_util.erl, src/fabric/src/fabric_view.erl, test/javascript/tests/view_errors.js
This changes the reduce overflow error to return an error to the client
rather than blowing up the view build. This allows views that have a
single bad reduce to build while not crushing the server's RAM usage.
```make javascript suites=view_errors```
=> Return reduce overflow errors to the client

rel/overlay/etc/default.ini, src/couch_peruser/README.md, src/couch_peruser/src/couch_peruser.app.src, src/couch_peruser/src/couch_peruser.erl, src/couch_peruser/src/couch_peruser_app.erl, src/couch_peruser/src/couch_peruser_sup.erl, src/couch_peruser/test/couch_peruser_test.erl, src/couch_replicator/src/couch_replicator.erl, src/couch_replicator/src/couch_replicator_clustering.erl, src/mem3/src/mem3.erl, test/build/test-run-couch-for-mango.sh
The `couch_peruser` app depends on `couch` having been started, yet it's also set as one of the `[daemons]` in `default.ini`, resulting in `couch_peruser` getting started prior to all of couch having started up. This explodes when calling out to mem3 prior to the mem3 application having been started, which causes various ETS issues as the tables do not exist yet.
This PR removes `couch_peruser` from `[daemons]` and adds in the necessary application and supervision logic to bootstrap this app appropriately.
Fixes #749
=> Make couch_peruser a proper Erlang app

src/couch/rebar.config.script, src/couch/src/couch_auth_cache.erl, src/couch/src/couch_lru.erl, src/couch/src/couch_util.erl, src/couch/src/couch_uuids.erl, src/couch/src/test_util.erl, src/couch_epi/test/couch_epi_tests.erl, src/couch_replicator/src/couch_replicator_worker.erl, src/fabric/src/fabric_db_create.erl, src/mango/src/mango_execution_stats.erl, src/mem3/src/mem3_shards.erl, src/rexi/src/rexi_server.erl
Fix erlang time module compatibility
`now/0` is deprecated since Erlang 18.0, and a set of new time related
functions are available.
Usually `now/0` can be replaced with `os:timestamp/0`, however in some
instances it was used effectively to produce monotonically incrementing values
rather than timestamps. So added a new `couch_util:unique_monotonic_integer/0`.
Most functional changes are in couch_uuid module. There `now/0` was used both
as a timestamp and for uniqueness. To emulate previous behavior, a local
incrementing clock sequence is used. If `os:timestamp/0` does not advance since
last call then the local clock is advanced by 1 microsecond and that's used to
generate the next V1 UUIDs. As soon as os:timestamp/0` catches up, the local
sequence reset to that latest value.
Also …
=> Fix erlang time module compatibility

src/ddoc_cache/src/ddoc_cache_lru.erl
As it turns out I made a bit of a mistake when I forgot that the old
ddoc_cache implementation had an ets_lru process registered as
ddoc_cache_lru. These cast messages were causing that process to crash.
If a cluster had enough design document activity and enough nodes this
would cause nodes with the old ddoc_cache implementation to reboot the
entire VM. This was a cascading failure due to the ets_lru process
restarting frequently enough that it brought down the entire ddoc_cache
application.
Try a rolling reboot upgrade of a large cluster with significant write load on design documents.
=> Fix cluster upgrades when deploying ddoc_cache

src/mango/src/mango_cursor.erl, src/mango/src/mango_error.erl, src/mango/src/mango_idx.erl, src/mango/src/mango_idx_special.erl, src/mango/src/mango_idx_text.erl, src/mango/src/mango_idx_view.erl, src/mango/src/mango_selector.erl, src/mango/test/02-basic-find-test.py, src/mango/test/13-users-db-find-test.py
Mango has an apparently long-standing bug whereby if an index is deemed valid for sorting a query but is not valid according to mango_idx:is_usable, the query planner would fall back to _all_docs silently, therefore ignoring the sort order specified in the query.
This reverses the index selection logic so that the list of usable indexes is generated prior to filtering them based on the sort order specified in the query.
Similar logic is applied to use_index, allowing us to generate a more specific error message when a user specifies an index which isn't valid for the current
selector.
This fix exposes that the change introduced in https://github.com/apache/couchdb/pull/816 may cause existing queries with sort fields to fail (indeed, several queries in our test suite needed fixing), so we …
=> Fix incorrect index selection when sort specified

INSTALL.Unix.md
Hi,
The documentation for installing CouchDB has several operating systems and their respective commands to install the dependencies, except for FreeBSD. I don't know if it is on purpose or not but given that I just installed CouchDB on a digital ocean droplet, it seemed cheap to update the documentation.
Let me know if any additional test is required.
=> Update Unix install dependencies (FreeBSD)

src/mango/src/mango_cursor_view.erl, src/mango/src/mango_idx_view.erl, src/mango/src/mango_idx_view.hrl, src/mango/test/02-basic-find-test.py, src/mango/test/17-multi-type-value-test.py
Mango previously constrained range queries against JSON indexes
(map/reduce views) to startkey=[]&endkey=[{}]. In Mango, JSON
index keys are always compound (i.e. always arrays), but this
restriction resulted in Mango failing to match documents where
the indexed value was an object.
For example, an index with keys:
[1],
[2],
[{"foo": 3}]
would be restricted such that only [1] and [2] were returned
if a range query was issued.
On its own, this behaviour isn't necessarily unintuitive, but
it is different from the behaviour of a non-indexed Mango
query, so the query results would change in the presence of an
index.
Additonally, it prevented operators or selectors which explicitly
depend on a full index scan (such as $exists) from returning a
complete result set.
This commit changes the …
=> Fix maximum key value when using JSON indexes

src/mango/test/16-index-selectors.py
Add a test to show the parital_filter_selector functionality will work
with design docs that don't have a selector defined in it by default
Mango tests should all pass
=> Add test to show selector works with old design docs

src/mango/test/README.md, src/mango/test/mango.py
Previously, the tests hardcoded a target host of `http://127.0.0.1:15984` with username "testuser" and password "testpass". This PR allows the host url and authentication parameters to be configured using environment variables. 
Additionally, we default to n=1 when creating the test databases rather than assuming the target cluster will have a single node.
Run the test suite. Try using a different username / password (following the README) or CouchDB 2.1 host.
=> Mango test configuration

src/mango/test/README.md
Improve formatting in the Mango test README.
=> Mango test README formatting

Makefile, dev/run, src/chttpd/src/chttpd_misc.erl, src/couch/src/couch_httpd_misc_handlers.erl, src/couch/src/couch_util.erl, test/javascript/tests/config.js, test/javascript/tests/erlang_views.js, test/javascript/tests/view_sandboxing.js
Covers clustered and node-local ports.
Includes JS test for clustered port.
=> Blacklist some config sections from HTTP PUT/DELETE operations

src/couch/priv/couch_js/help.h, src/couch/priv/couch_js/main.c, src/couch/priv/couch_js/util.c, src/couch/priv/couch_js/util.h, test/javascript/run, test/javascript/tests/view_sandboxing.js
This changes the couchjs --no-eval flag to --eval and disables
eval() and Function() constructors by default in couchjs.
As this is a major change to compatibility, it should land in the next feature release, not `2.1.1`.
A documentation PR will come after this lands.
=> Disable eval() and Function() constructor in JS by default

src/couch/src/couch_httpd.erl
=> feat: add warning about redirects without a slash

.travis.yml
Enable Erlang 20.1 for Travis (instead of 20.0)
=> Travis: s/20.0/20.1 for build

Makefile, rel/reltool.config, version.mk
RC1 had improper version numbering, and the Makefile script fails when the RC number is 1. This isn't a full workaround but it gets us in place to build and release 2.1.1 proper.
Closes #908
=> Improve release/RC tarball creation, bump ver to 2.1.1

Makefile, rel/reltool.config, version.mk
This is #907 but applied to master. Previously approved by @janl.
Will merge as soon as build passes.
=> Improve rc-cutting process

src/mango/test/mango.py
Mango tests fail due to flaky tests with index deletion. I cannot recreate locally.
@davisp and @garrensmith
mentioned that it could be due to the latest ddoc_cache changes and suggested
changing r=3 to see if that would help. However, we recently changed tests to use
n=1 as default for all dbs created. I wonder if having w=3 and n=1 could be the reason.
We get a 202 back, but the index isn't deleted in time when we go to retrieve it. So changing
w=3  to w=1 to see if that will help. If not, I may add a wait loop inside delete.
Let's see if it passes travis.
https://github.com/apache/couchdb/issues/918
=> Mango test failures

INSTALL.Unix.md
While going to `http://localhost:5984/_utils/verify_install.html` returns `Not found.`, browsing to `http://localhost:5984/_utils/#/verifyinstall` works. Maybe the url is outdated
Follow [INSTALL.Unix.md](https://github.com/apache/couchdb/blob/master/INSTALL.Unix.md) until the "First Run" section and then browse to the <http://localhost:5984/_utils/verify_install.html>
=> Updating verifyinstall URL

src/chttpd/src/chttpd_view.erl, test/javascript/tests/view_errors.js
The request for temporary view is currently returning "403 Forbidden" error, which is implying a permissions issue. Error "410 Gone" seems to fit better.
> [The HTTP 410 Gone client error response code indicates that access to the target resource is no longer available at the origin server and that this condition is likely to be permanent.](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/410)
`make javascript suites=view_errors`
Related to #932
=> Return error 410 on temporary view request

rebar.config.script, src/couch/src/couch_util.erl
Update to use new dedupe_keys option in Jiffy.
```make check```
=> Update jiffy to use dedupe_keys

.travis.yml
It's runs unstable on travis and while 2.x branch no longer supports it, we recommend to use recent Erlang/OTP release as possible to avoid any issues.
=> Mark R15B03 build as flaky

rel/overlay/etc/default.ini, src/couch_replicator/src/couch_replicator_worker.erl
Implement a configurable delay before retrying a document fetch in replicator.
missing_doc exceptions usually happen when there is a continuous replication
set up and the source is updated. The change might appear in the changes feed,
but when worker tries to fetch the document's revisions it talks to a
node where internal replication hasn't caught up and so it throws an exception.
Previously the delay was hard-coded at 0 (that is retrying was immediate). The
replication would still make progress, but after crashing, retrying and
generating a lot of unnecessary log noise. Since updating a source while
continuous replication is running is a common scenario, it's worth optimizing
for it and avoiding wasting resources and spamming logs.
=> Configurable delay before retrying on missing_doc error

share/doc/src/whatsnew/1.7.rst, src/couch_mrview/src/couch_mrview_show.erl, src/couchdb/couch_db.erl, src/couchdb/couch_doc.erl, src/couchdb/couch_httpd_auth.erl, src/couchdb/couch_httpd_db.erl, test/couchdb/Makefile.am, test/couchdb/couch_doc_tests.erl, test/couchdb/couchdb_auth_tests.erl, test/couchdb/eunit.ini, test/couchdb/test_request.erl
COUCHDB-1356
COUCHDB-1447
COUCHDB-2310
COUCHDB-2375
COUCHDB-2534
COUCHDB-2845
=> Several backports from master

share/www/script/test/changes.js, share/www/script/test/erlang_views.js, share/www/script/test/list_views.js
this didn’t trip up https://github.com/apache/couchdb/pull/939 because it looks like js test fails don’t break the build
=> disable js tests that need the native query server

src/mango/src/mango_idx_text.erl, src/mango/src/mango_idx_view.erl, src/mango/test/16-index-selectors-test.py
For Get / _index only return the partial_filter_selector for an index if
it is set to something other than default
=> Do not always return partial_filter_selector

src/chttpd/src/chttpd_db.erl, test/javascript/tests/bulk_docs.js
End-point `_bulk_docs` crashes if provided with non-boolean value for `new_edits` parameter.
This patch changes it to return "Bad Request" error instead.
`make javascript suites=bulk_docs`
=> Return error 400 on invalid new_edits value

src/mango/src/mango_idx.erl
When creating a Mango index, we allow the user to specify
a design document name. This can be of the form "_design/foo"
or just "foo", with the expectation that Mango would
automatically add the "_design" prefix.
This fixes a bug whereby if the user specified "_design/foo",
Mango was prefixing this again, creating a design document called
"_design/_design/foo".
Added a couple of new eunit tests to cover this. To test manually, verify that you can create a mango index using the `"ddoc"` field to specify the design document id, with and without a `"_design/"` prefix.
=> Fix user-specified ddoc name in Mango

Makefile.win, src/couch/include/couch_eunit.hrl
Commit afb7c8e ported the use of `couch_util:unique_monotonic_integer` for the EUnit test suite instead of `erlang:now`. Unfortunately, this resulted in filenames being generated with double-quotation marks in them (`"`), which are invalid filename characters on Windows. This failed many test suites, including `couch_epi` and `couch_log`.
Fortunately, the fix is a single character in the `io_lib:format` string:
```erlang
24> A = integer_to_list(erlang:unique_integer([monotonic, positive])).
"20"
25> N = node().
nonode@nohost
27> io_lib:format("~p-~s", [N, A]).
["nonode@nohost",45,"20"]
28> lists:flatten(io_lib:format("~p-~s", [N, A])).
"nonode@nohost-20"
29> lists:flatten(io_lib:format("~p-~p", [N, A])).
"nonode@nohost-\"20\""
```
There is also an associated fix to `Makefile.win`, porting …
=> Fix eunit and js testsuites on Windows

rel/reltool.config, version.mk
Given PSE work will probably land, we need to bump the minor version number.
=> Version bump to 2.2.0 for future release

src/couch_replicator/src/couch_replicator_httpd.erl
Show 404 for GET request which not handled in previous clauses.
=> 404 status for non using uri in _scheduler (#953)

Jenkinsfile
Previously, we used the `couchdbtest` label to select a specific subset of nodes with a known uid/gid combination for the `jenkins` user. This is necessary to ensure a successful build inside of a docker container without file permissions issues.
Infra has requested to delete that label, and has agreed to standardise the uid/gid to 910/910 across all nodes labelled `ubuntu`. That's done now.
I will also need to merge this change to the 2.1.x branch in a secondary PR.
=> Revert to ubuntu Jenkins label, uids now standardised

src/mango/test/05-index-selection-test.py, src/mango/test/06-basic-text-test.py, src/mango/test/10-disable-array-length-field-test.py, src/mango/test/16-index-selectors-test.py
The text index tests are not routinely run by the Couch CI
(due to an external dependency that isn't shipped with Couch).
This fixes a number of tests that were broken as a result of
recent feature changes.
Run the mango tests with text indexes enabled.
=> Fix Mango text index tests

src/mango/src/mango_idx_text.erl, src/mango/test/07-text-custom-field-list-test.py
When users explicitly defined a text index's fields, and used $exists
with false, we tag false when constructing the query. This led to a
function clause for indexable_fields since we did not account for it.
This fix patches that up, but note that we don't care about the false
value itself since we only care about fields.
New unit tests added to test for this particular operator
This PR is the issue.
=> Fix exists false when field is explicitly defined

src/mango/src/mango_cursor.erl, src/mango/test/05-index-selection-test.py
Throw an error when a user specifies a value in "use_index", of the form [<ddoc id>, <name>], that cannot be used for the current query selector.
Run Mango test suite. Manually test as documented in #988
#988
=> Throw friendly error on invalid use_index value

src/mango/test/mango.py, test/build/test-run-couch-for-mango.sh
877c886d added delays into the Mango test suites to improve stability. However, the failures were never reproduced locally and significantly increase the time that it takes to run the tests. This is a PR to experiment with removing those delays to see whether we can get the test suite stable in Travis without them.
Run the Mango test suite.
#923
=> Improve Mango test suite performance

rel/overlay/etc/default.ini
Somehow entries ended up under [couch_per_user] but should be in the
[replicator] section.
=> Move cluster_start_period and cluster_quiet_period to replicator section

src/mango/src/mango_selector.erl, src/mango/test/05-index-selection-test.py
mango_selector:has_required_fields checks that a list of
indexed fields is covered by a given selector. The implementation
recurses through the selector, tracking fields that encounters.
Unfortunately, this skipped peers of combination operators. For
example,
```
"selector": {
"$and":[
"$and":[
"A": "foo"
],
"$and":[
"B": "bar"
]
]
}
```
would skip the first nested "$and" operator and only return "B"
as a covered field.
This commit explicitly handles this situation (the only combination
operator we care about is $and), so for the above selector we
would correctly identify "A" and "B" as covered fields.
Run the test suite. Test that Query selectors with nested `$and` operators correctly use `json` indexes that should cover them.
=> Fix index validation for nested $and

src/mango/test/02-basic-find-test.py
Adds a test to verify the behaviour of duplicate fields in a Mango selector.
The fix for CVE-2017-12635 (#936) resulted in CouchDB's JSON parser only recognising the last instance of duplicated fields in a JSON object. This represents a breaking change to Mango (_find)
because, previuously, all instances would have been considered when evaluating a selector.
This test verifies that Mango now only considers the last instance of a field, silently ignoring
those that appear before it.
TBD whether we can or should show an error when this occurs, since this leads to predicates
silently being ignored.
Run the Mango test suite.
#936
=> Test duplicate fields in Mango selector

src/mango/src/mango_cursor_view.erl, src/mango/test/05-index-selection-test.py
Handle the case when startkey and endkey are reversed. To create valid JSON we need to
replace the internal representation of the startkey with a string.
Run the test suite. Manual reproduction steps as in case #1023.
Fixes #1023
=> Fix _explain for sort descending

src/couch_replicator/src/couch_replicator_api_wrap.erl, src/couch_replicator/src/couch_replicator_docs.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/test/couch_replicator_create_target_with_options_tests.erl
If you specify "create_target": true in a replicator doc, the replicator creates the target database, with the default q value.
With this PR, it is allowed to specify "create_database_params": {"q": "1"} to have the replicator to create the target database with specified value (currently, the example is q=1 and q can be other value). The example of replication document looks like:
```
{
"source": "http://foo:bar@localhost:15984/db1",
"target": "http://foo:bar@localhost:15984/db22",
"create_target": true,
"continuous": false,
"create_target_params": {"q": "1"}
}
```
One thing to be highlighted is about the value in `source` and `target` field in replication document.
Most of case database in `url` format were specified in replication document. 
```
{
"source": …
```
=> Allow replicator documents to include params for db creation

src/couch_index/test/couch_index_compaction_tests.erl, src/couch_index/test/couch_index_ddoc_updated_tests.erl
Mocked index module missing a couple of methods called on late compaction stages. This leads
to a crash, but since it's happening after the test's assertions, it bring the test to fail.
Also small refactoring to encapsulate all mocking in a single function and move unrelated parts back to test's setup.
` make eunit apps=couch_index`
=> Fix couch index compaction tests

src/mango/src/mango_cursor.erl, src/mango/src/mango_cursor_text.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_error.erl, src/mango/src/mango_idx.erl, src/mango/test/05-index-selection-test.py
If a user specifies a value for use_index that is not valid for the current query - i.e. it does not meet the coverage requirements of the selector or sort fields - attempt to fall back to a valid index (or database scan) rather than returning a 400 error to the client.
When a fallback occurs, populate the "warning" field in the response (as we already do when a full database scan takes place) to feed back to the user that `use_index` was ignored.
This change is partially as mitigation for #816, which may lead to some previously valid indexes being deemed invalid, and also to make `use_index` less brittle for production applications in general. 
Run the test suite. Run some mango queries with and without `use_index`. Observe that a warning is returned in the JSON and in Fauxton.
=> Mango: generate a warning instead of an error when an user-specified index cannot be used

src/couch_replicator/test/couch_replicator_create_target_with_options_tests.erl
Don't need to use local as source since it doesn't test anything specific to
the code in question. Use credentials with http requests as it's a more
realistic scenario. Avoid spawning couch server twice - once to start chttpd
and then to start other couch servers.
=> Fix replicator create target options test

src/mango/src/mango_selector.erl, src/mango/test/05-index-selection-test.py
Implementation of #1011 taking into account recent selector fixes.
Run the mango test suite. Manually run some mango queries with/without JSON indexes and check that the results are as expected.
#1011
=> Allow to use index with or

src/couch/test/couch_db_tests.erl, src/couch/test/couchdb_cookie_domain_tests.erl, src/couch/test/global_changes_tests.erl
Multiple fixes and refactoring for couch tests.
Proper usage of test assertions to detect fixture failing, pre-test config setup cleanup, remove custom loop in favour of standard eunit `foreach` and forechx`
Fix of invalid assertions, remove obsolete helpers, proper usage of test setup.
Remove unused var assignment to avoid compilation warning
`make eunit apps=couch` should pass 1219 tests
=> Fix couch db tests

src/couch_log/src/couch_log.erl, src/couch_log/test/couch_log_test_util.erl, src/couch_stats/src/couch_stats.app.src, src/couch_stats/src/couch_stats.erl, src/couch_stats/src/couch_stats_process_tracker.erl
Add couch_stats tracking back to couch_log using stats defined in
https://github.com/apache/couchdb/blob/master/src/couch_log/priv/stats_descriptions.cfg
```
jiangphs-mbp-2:dev jiangph$ ./remsh
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Eshell V7.2.1  (abort with ^G)
(node1@127.0.0.1)1> couch_stats:sample([couch_log, level, debug]).
169
(node1@127.0.0.1)2> couch_stats:sample([couch_log, level, info]).
13
(node1@127.0.0.1)3> couch_stats:sample([couch_log, level, notice]).
37
(node1@127.0.0.1)4> couch_stats:sample([couch_log, level, warning]).
1
(node1@127.0.0.1)5> couch_stats:sample([couch_log, level, error]).
0
(node1@127.0.0.1)6> couch_stats:sample([couch_log, level, critical]).
0
(node1@127.0.0.1)7> …
```
=> Add couch_stats tracking back to couch_log

rel/haproxy.cfg
- `stats scope .` ends up blocking all backends
- Renaming endpoint from `_stats` to `haproxy_stats` so that it doesn't collide with CouchDB's `_stats` endpoint
- Added a commented out stats auth line so that you can easily password protect
Visit `http://example.com:5984/_stats` now and you won't see any stats for any backends. With my changes you will see the backend specified when you visit `http://example.com:5984/haproxy_stats`
=> Fix haproxy stats

src/mango/src/mango_cursor_special.erl, src/mango/test/03-operator-test.py
01252f97 introduced a "catch-all" feature to Mango that allowed
queries to fall back on a full database scan (_all_docs) when
no valid index was available.
This worked by creating a special index range representing
the full database scan.
For example, a selector:
`{ "_id": "foo" }`
would be translated into a field range of:
`[{ "startkey": "foo", "endkey": "foo"}]`
then prepending the catch-all field range, we would have:
```
[
{ "startkey": null, "endkey": max_json_value},
{ "startkey": "foo", "endkey": "foo"}
]
```
This set gets passed into
mango_cursor_view:choose_best_index to determine most selective
index and field range combination to use. Unfortunately, in
the event that we have one possible index (all_docs) and multiple
valid ranges, it just chooses the first range it finds -
the …
=> Mango: change catch-all field range priority

src/mango/src/mango_idx_text.erl, src/mango/src/mango_native_proc.erl
When soft limit is reached couch_proc_manager evicts idle processes by casting on them `stop`
message. Since mango_native_proc doesn't handle this message it results to its crash with
`invalid_cast` reason.
`make eunit apps=mango` or `make eunit apps=mango suites=mango_native_proc` for isolated test.
`make mango-test` for integration test.
=> Fix mango native proc crash

src/couch_log/src/couch_log.erl
Move `couch_stats:increment_counter/1` to `log/3`  in order to refactor `couch_log.erl`.
```
localhost:dev jiangph$ ./remsh
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Eshell V7.2.1  (abort with ^G)
(node1@127.0.0.1)1> couch_stats:sample([couch_log, level, debug]).
20
(node1@127.0.0.1)2> couch_stats:sample([couch_log, level, info]).
17
(node1@127.0.0.1)3> couch_stats:sample([couch_log, level, notice]).
38
(node1@127.0.0.1)4> couch_stats:sample([couch_log, level, warning]).
3
(node1@127.0.0.1)5> couch_stats:sample([couch_log, level, error]).
0
(node1@127.0.0.1)6> couch_stats:sample([couch_log, level, critical]).
0
(node1@127.0.0.1)7> couch_stats:sample([couch_log, level, alert]).
0
(node1@127.0.0.1)8> …
```
=> Refactor couch_log.erl

src/couch/include/couch_eunit.hrl
This changes naming of temporary eunit databases and files from using unique_monotonic_integer to couch_uuids:random to remove performance penalty and normalize naming across erlang releases.
Also getting rid of unnecessary inter-types convertion.
`make eunit` should come clean. Files in `$PWD/tmp` should be named like `tmp/data/eunit-test-db-a6a4cd31f2addf2791440b3e8b54f860.1515084353.couch` or `tmp/tmp_data/nonode@nohost-018448e4ebb1f85812fd96d56939a620`
=> Use uuid in tmp db names in unit tests

src/mango/test/mango.py
Rapid same database deletion/creation is a known antipattern prone to a race condition, especially on slow VMs.
This fix modifies mango test's helper function used for db recreation to ensure that we are actually starting tests when a database created and empty.
`make mang-test` should finish with something like:
```
...
Ran 278 tests in 7.100s
OK (SKIP=127)
```
=> Make sure mango tests's recreate fun creates db

src/chttpd/test/chttpd_security_tests.erl, src/couch/src/couch_passwords.erl
Before this PR, couch returns unknown_error/function_clause when creating a user with non-string password.
```
curl -u foo:bar http://127.0.0.1:15984/_users  -X POST -H "Content-Type: application/json" -d @test.json
{"error":"unknown_error","reason":"function_clause","ref":1311610859}
```
This PR is aimed to return one friendly error message when creating user with invalid password.
```
curl -u foo:bar http://127.0.0.1:15984/_users  -X POST -H "Content-Type: application/json" -d @test.json
{"error":"forbidden","reason":"Password value of '123' is invalid."}
```
```
more test.json
{
"_id": "org.couchdb.user:test",
"name": "test",
"type": "user",
"roles": [],
"password": 123
}
```
```
make check skip_deps+=couch_epi apps=chttpd tests=all_test_
==> chttpd (eunit)
Running test function(s): …
```
=> Return friendly error message when creating user with invalid password

src/mango/src/mango_native_proc.erl, src/mango/test/16-index-selectors-test.py, src/mango/test/mango.py
Mango text indexes historically supported partial indexes
defined via a "selector" field. This was renamed to
"partial_filter_selector" in b98de40 but the fallback
code did not correctly handle the case where
a "selector" existed alongside a "partial_filter_selector".
This situation can occur when a the _index endpoint is
used to create a text index with a "selector". The resulting
design document contains an empty "partial_filter_selector"
field *and* the "selector" field that was passed in. The
previous implementation of the fallback would detect the
presence of "partial_filter_selector" and use the empty
value (match all docs) instead of faling back to the
"selector" field.
This commit changes the behaviour so that a "selector"
will be used even if an empty "partial_filter_selector"
is …
=> Mango: fallback to "selector" on empty "partial_filter_selector"

src/couch/test/couch_key_tree_tests.erl
Avoid starting 4 applications (config, couch_log, ioq and couch_epi) just to
handle a call to config:get. Instead just mock the config directly.
This also speeds up the test suite a bit.
=> Simplify couch_key_tree test setup

src/couch_epi/rebar.config, src/couch_epi/src/couch_epi_codegen.erl
There are mouthful depreciation warning on epi compilation on none-ancient versions of erlang
```
Warning: erl_scan:token_info/2: removed in 19.0; use erl_scan:{category,column,line,location,symbol,text}/1 instead
```
The module `couch_epi_codegen` actually decides what scan token to use based on `function_exported`, but the warning is thrown anyway.
The patch changes runtime choice between `erl_scan:token_info` and `erl_scan:line` to compilation conditional one based in rebar's `platform_define`.
This is getting rid of compilation deprecation warning and also should speed up things a bit.
Basic recompile to confirm the warning is gone and `make eunit apps=couch_epi` to ensure that things are not broken.
I've tested it on:
- 17.5
- 18.3
- 19.3
- 20.2
=> Remove warning on `couch_epi_codegen` compilation

rel/overlay/bin/couchdb
The existing `couchdb` start script hard-codes the arguments to
`-args_file` and `-config`. Although it is possible to copy this
script and modify it, or modify it in place, that is less than ideal
and can lead to all kinds of difficulties.
This PR adds the following environment variables:
- `ARGS_FILE`: By default, set to the existing hard-coded value.
- `SYSCONFIG_FILE`: By default, set to the existing hard-coded value.
- `COUCHDB_ARGS_FILE`: If non-empty, overrides `$ARGS_FILE`.
- `COUCHDB_SYSCONFIG_FILE`: If non-empty, overrides `$SYSCONFIG_FILE`.
By changing the script to use these environment variables, it makes it easily possible
to use different settings without tinkering with the pristine installed CouchDB environment.
Kindly consider this feature request as a useful, and "mostly …
=> Allow override of `-args_file` and `-config` parameters

src/chttpd/test/chttpd_db_test.erl, src/fabric/src/fabric_view_all_docs.erl
Before this PR, if `keys` parameter is set for `_all_docs` endpoint, there is no `update_seq` and `offset` returned in response even if `update_seq` parameter is set to true. This is not consistent with description in http://docs.couchdb.org/en/2.1.1/api/database/bulk-api.html
```
update_seq (boolean) – Response includes an update_seq value indicating which sequence id of the underlying database the view reflects. Default is false.
```
This PR is aimed to return update_seq and offset with null if `update_seq` is set to true and `keys` is specified as well.
```
curl -X GET 'localhost:15984/db3/_all_docs?update_seq=true&keys=["bar"]&skip=0' -u foo:bar -g|jq .
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   157 …
```
=> Return update_seq and offset when update_seq is true and keys is set

src/couch/src/couch_key_tree.erl, src/couch/test/couch_key_tree_tests.erl
* Fix couch_key_tree:stem/4 case to update `Seen` set for a leaf child
* Fix  `should_create_no_conflicts_on_full_stem`
=> Optimize doc updates 3

src/chttpd/src/chttpd_db.erl, src/chttpd/test/chttpd_db_test.erl, src/couch_mrview/src/couch_mrview_util.erl, test/javascript/tests/basics.js, test/javascript/tests/view_errors.js
Allow to POST to /{db}/_all_docs and specify a queries list in the body, the same way you can do with a regular MapReduce view, like
```
curl -u foo:bar -H "Content-Type: application/json" -X POST -d @multiple_queries.json http://localhost:15984/db97/_all_docs
{"results":[
{"total_rows":30,"rows":[
{"id":"point2","key":"point2","value":{"rev":"1-d942f0ce01647aa0f46518b213b5628e"}},
{"id":"point3","key":"point3","value":{"rev":"1-721fead6e6c8d811a225d5a62d08dfd0"}}
]},
{"total_rows":30,"offset":2,"rows":[
{"id":"point11","key":"point11","value":{"rev":"1-ffb6c2ae737918f8f911e1fce668333e"}},
{"id":"point12","key":"point12","value":{"rev":"1-c32d315f69ce72128244a60d0cbe4628"}},
{"id":"point13","key":"point13","value":{"rev":"1-a9b955ca17f553398cd877629e803c5d"}}, …
```
=> Add support for queries in /{db}/_all_docs POST

src/couch/test/couch_db_tests.erl
I've accidentally overrode custom 2 mins timeout for `should_create_delete_database_continuously` tests to default 5 sec with`?_test` wrapper.  It went unnoticed in local tests and travis, since in general "should_create_delete_database_continuously (100 times)" passes within 1.096s, but Jenkins prove to be more sensitive.
Standard `make eunit apps=couch` should pass. More importantly Jenkins now should not throw timeout on this test.
Fixes: #1122
=> Set eunit timeout on a whole test object

rel/overlay/etc/default.ini, src/couch_peruser/src/couch_peruser.erl, src/couch_peruser/test/couch_peruser_test.erl
At the moment, peruser-managed databases are prefixed with userdb- and that’s hardcoded.
This PR allows users to specify a different prefix, so we make this configurable.
The peruser config section looks:
```
[couch_peruser]
; If enabled, couch_peruser ensures that a private per-user database
; exists for each document in _users. These databases are writable only
; by the corresponding user. Databases are in the following form:
; userdb-{hex encoded username}
enable = false
; If set to true and a user is deleted, the respective database gets
; deleted as well.
delete_dbs = false
; prefix for user databases. If you change this after user dbs have been
; created, the existing databases won’t get deleted if the associated user
; gets deleted because of the then prefix mismatch. …
```
=> Make peruser database prefix configurable

Makefile, Makefile.win, README-DEV.rst
We removed the Dockerfile in 6e57c43a and moved all Docker-related materials to [apache/couchdb-docker](https://github.com/apache/couchdb-docker), but we never cleaned up the Makefile targets or developer documentation.
=> Remove outdated docker targets and docs

src/couch_replicator/src/couch_replicator_docs.erl
Replication document is available for user to check replication status. It includes some credential information. Before this PR, the `oauth` field is removed when replication status is displayed to user.  However, for basic authentication, the credential information is also saved in `headers` field and exposed to users. The aim of this PR is to hide credential information even if customer uses basic authentication case.
```
"source": {
"headers": {
"Authorization": *****
},
"url": "https://testy011-user1.cloudant.com/testy_db_ctkzwqshsk"
},
"target": {
"headers": {
"Authorization": *****
},
"url": "https://testy011-user1.cloudant.com/test-db-auth"
},
```
make check skip_deps+=couch_epi apps=couch_replicator
```
module 'couch_replicator_docs'
couch_replicator_docs: …
```
=> Hide credential information in replication document for reader

src/chttpd/src/chttpd_db.erl, src/chttpd/test/chttpd_db_test.erl, src/couch/src/couch_httpd_db.erl, src/couch/src/test_request.erl
The Fauxton URL request to CouchDB encodes the user input and sets the Destination header with the encoded value of the new ID when sending the COPY request. This PR is aimed to make CouchDB to decode Destination header, and creates the ID without escaped values.
```
jiangphs-mbp-2:geotest jiangph$ curl -u foo:bar http://127.0.0.1:15984/testdb1/point11 -X COPY -H 'Content-Type: application/json'  -H 'Destination: xxx%E5%95%8Axxx'
{"ok":true,"ok":true,"id":"xxx啊xxx","rev":"1-ffb6c2ae737918f8f911e1fce668333e"}
jiangphs-mbp-2:geotest jiangph$ curl -u foo:bar http://127.0.0.1:15984/testdb1/point11 -X COPY -H 'Content-Type: application/json'  -H 'Destination: this/is/an/example'
{"ok":true,"ok":true,"id":"this/is/an/example","rev":"1-ffb6c2ae737918f8f911e1fce668333e"}
```
```
make check …
```
=> Decode destination header for doc copy

rel/overlay/etc/default.ini
Fixes bug introduced by d16f2db901c9b3b24c7189acfec35ec42895bd25.
=> Remove 'smartquote' from default.ini, broke the build

src/couch/src/couch_db.erl, test/javascript/tests/design_docs_query.js
The aim of this PR is to make `_design_docs` to respect query parameters correctly, like parameters for `_all_docs` endpoint.
http://docs.couchdb.org/en/2.1.1/api/database/bulk-api.html
```
curl -u foo:bar http://127.0.0.1:15984/dbname/_all_docs
{"total_rows":10,"offset":0,"rows":[
{"id":"_design/ddoc01","key":"_design/ddoc01","value":{"rev":"1-7407569d54af5bc94c266e70cbf8a180"}},
{"id":"_design/ddoc02","key":"_design/ddoc02","value":{"rev":"1-d942f0ce01647aa0f46518b213b5628e"}},
{"id":"_design/ddoc03","key":"_design/ddoc03","value":{"rev":"1-721fead6e6c8d811a225d5a62d08dfd0"}},
{"id":"_design/ddoc04","key":"_design/ddoc04","value":{"rev":"1-32c76b46ca61351c75a84fbcbceece2f"}},
{"id":"_design/ddoc05","key":"_design/ddoc05","value":{"rev":"1-af856babf9cf746b48ae999645f9541e"}}, …
```
=> Make _design_docs to respect query parameters

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_auth_request.erl, src/chttpd/src/chttpd_httpd_handlers.erl, src/chttpd/src/chttpd_misc.erl, src/chttpd/test/chttpd_dbs_info_test.erl, src/couch/test/chttpd_endpoints_tests.erl
Before this PR, if you want the database info for all databases on a server, you must individually access /{db} for each database. This PR makes a single request to retrieve all of that.
You can specify keys=[....] to select a subset of all databases on a server to monitor.
```
curl -X POST 'localhost:15984/_dbs_info' -u foo:bar -H "Content-Type: application/json"  -d @dblist.json -g|jq .
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100   971    0   938  100    33   104k   3770 --:--:-- --:--:-- --:--:--  114k
[
{
"key": "dbname1",
"info": {
"db_name": "dbname1",
"update_seq": "0-g1AAAAFDeJzLYWBg4MhgTmHgz8tPSTV0MDQy1zMAQsMcoARTIkOS_P___7MSGXAqSVIAkkn2hFQ5gFTFE1KVAFJVT0BVHguQZGgAUkCF85FVGmNVuQCicj9hMw9AVN4nrPIBRCX …
```
=> Introduce new _dbs_info endpoint to get info of a list of databases

Makefile, dev/run, src/fabric/src/fabric_db_create.erl, test/javascript/run, test/javascript/tests-cluster/with-quorum/db-creation.js, test/javascript/tests-cluster/without-quorum/db-creation.js
Current behaviour of DB creation in a cluster degraded situation is not consistent with the general behaviour described for document creation in the same situation.
> The number of copies of a document with the same revision that have to be read before CouchDB returns with a 200 is equal to a half of total copies of the document plus one. It is the same for the number of nodes that need to save a document before a write is returned with 201. If there are less nodes than that number, then 202 is returned. Both read and write numbers can be specified with a request as r and w parameters accordingly.
The current behaviour for database creation in a cluster is:
- Database creation returns 201 - Created if all nodes responds ok
- Database creation returns 202 - Accepted if the quorum is met
- …
=> Fix for issue #603 - Error 500 when creating a db below quorum

Makefile
**make mango-test** is not cleaing previous state in dev/lib so it can be affected by previous mango or javascript test execution
Following execution sequence produces testing errors beffore this PR and not after PR
```
make test-cluster-with-quorum
make mango-test
```` 
Fixes #1134
=> Fix for issue #1134 clean up dev/lib before run mango tests

src/chttpd/src/chttpd_db.erl, src/chttpd/test/chttpd_db_test.erl, test/javascript/tests/basics.js
In the https://github.com/apache/couchdb/pull/1032, queries are supported to `_all_docs`, `_design_docs` and `_local_docs` to address the requirement in https://github.com/apache/couchdb/issues/820.
However, the response schema changes depending on what is POSTed. This makes it quite hard to interact with from static type languages. So we plan to move the implementation to separate endpoint. As the first step, this PR is used to remove queries for _all_docs,  _design_docs and _local_docs.
make check skip_deps+=couch_epi apps=chttpd tests=all_test_
```
==> chttpd (eunit)
Compiled test/chttpd_db_test.erl
Compiled src/chttpd_db.erl
Running test function(s):
chttpd_db_doc_size_tests:all_test_/0
chttpd_db_test:all_test_/0
chttpd_security_tests:all_test_/0
======================== EUnit …
```
=> Remove queries for _all_docs,  _design_docs and _local_docs

configure
As a CouchDB developer, I find myself typing `./configure -c --disable-docs --disable-fauxton` a lot, and I long for a shortcut, so I’m introducing `./configure --dev` as an alias of the above.
=> Add ./configure --dev as alias for -c --disable-{docs,fauxton}

src/couch_replicator/src/couch_replicator.app.src
It depends on and uses `config`. Obviously it still works without it, but this
eliminates Dialyzer errors such as:
`Callback info about the config_listener behaviour is not available`
=> Add config app to couch_replicator app dependencies

src/couch_event/src/couch_event_listener.erl
This knocks out a few dialyzer errors
=> Use callbacks for couch_event_listener behavior

src/couch_replicator/src/couch_replicator_httpc.erl
In some cases the higher level code from `couch_replicator_api_wrap` needs to
handle retries explicitly and cannot cope with retries happening in the lower
level http client. In such cases it sets `retries = 0`.
For example:
https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_api_wrap.erl#L271-L275
The http client then should avoid unconditional retries and instead consult
`retries` value. If `retries = 0`, it shouldn't retry and instead bubble the
exception up to the caller.
This bug was discovered when attachments were replicated to a target cluster
and the target cluster's resources were constrainted. Since attachment `PUT`
requests were made from the context of an open_revs `GET` request, `PUT`
request timed out, and they would retry. However, …
=> Avoid unconditional retries in replicator's http client

src/couch/src/test_engine_util.erl
The compaction test takes quite a long time on purpose to show that we
can run a compaction that has many batches. On resource constrained
build machines like Jenkins and TravisCI this can end up taking longer
than the default 5s timeout.
Run the test suite on a resource constrained build machine (i.e., our Jenkins CI)
=> Increase timeout for storage engine tests

Jenkinsfile
Currently, we run Jenkins CI builds on 11 platforms:
Erlang 18.3 + [centos6|centos7|debian8|debian9|ubuntu1404|ubuntu1604]
"Default" (ships-with-the-distro) Erlang + [same list but not centos6]
The intent was ensure that CouchDB ran fine both with our preferred
Erlang version (right now, 18.3) as well as the Erlang that ships with
various common distributions. This would help ease consumption of
CouchDB by end users, we thought.
With CouchDB 2.1.0 we started providing convenience binary packages,
built with Erlang 18.3. This (along with Docker) has become the most
common way people consume CouchDB today. Those binaries are generated
directly from the Jenkins builds.
Further, Travis CI already runs our test suite against a variety of
Erlang distributions, from 16B03 right through 20.1 (as …
=> Eliminate "default" Erlang platform from Jenkins CI

src/couch/src/couch_db.erl
This was left over from an earlier attempt at being a bit more strict on
removing access to the #db record. Its not used as is obvious by the
fact that the 2-arity version isn't even exported from the module.
`$ make check`
=> Remove unused code for starting compactions

rel/overlay/etc/default.ini, src/couch/src/couch_compaction_daemon.erl, src/couch/test/couchdb_compaction_daemon_tests.erl, src/couch_index/src/couch_index.erl
This PR addresses a number of issues with the Compaction Daemon when run under a db-per-user scenario:
1. with many database and/or many view groups in one or more databases, checking whether a file should be compacted can create significant CPU load. This PR both:
1. spaces the `check_interval` from 5 minutes to 60 minutes,
2. and introduces a 3 second `snooze_period` between compacting any two files.
2. when a view index is opened or closed, we send a `notice` level log line. In this scenario, this balloons the log file for no good benefit. The logs are not demoted to `debug`.
=> Compaction Daemon & db-per-user

src/chttpd/test/chttpd_csp_tests.erl, src/couch/src/couch_httpd_misc_handlers.erl, src/couch/test/couchdb_vhosts_tests.erl
Will help stop people shooting themselves in the foot and/or using
node-local CouchDB as their "main" CouchDB port.
I'll file a separate docs repo PR on this once this merges.
Test results:
```
$ curl -v http://localhost:15986/_utils
*   Trying ::1...
* TCP_NODELAY set
* connect to ::1 port 15986 failed: Connection refused
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to localhost (127.0.0.1) port 15986 (#0)
> GET /_utils HTTP/1.1
> Host: localhost:15986
> User-Agent: curl/7.52.1
> Accept: */*
>
< HTTP/1.1 410 Gone
< Cache-Control: must-revalidate
< Content-Length: 110
< Content-Type: application/json
< Date: Sat, 03 Mar 2018 00:45:22 GMT
< Server: CouchDB/2.2.0-51cb6aecc (Erlang OTP/19)
<
{"error":"no_node_local_fauxton","reason":"The web interface is no longer available on the …
```
=> Prevent access to Fauxton on node-local port (5986)

src/couch/src/couch_key_tree.erl
The spec of `couch_key_tree:merge/2` doesn't include the `path()`
type. However we pass `path()` in few places. One of such places is
`couch_db:prep_and_validate_replicated_updates/5`.
```
{NewTree, _} = couch_key_tree:merge(AccTree,
couch_doc:to_path(NewDoc), RevsLimit),
NewTree
```
The spec for `couch_doc:to_path/1` is defined as:
```
-spec to_path(#doc{}) -> path().
```
This PR adds `path()` type to `couch_key_tree:merge/2` spec.
Run dialyzer tool and make sure there are no complains about `couch_key_tree:merge`
1. Prepare for analysis:
```
make build-plt
```
2. Run analysis 
```
make dialyze apps=couch
```
The dialyzer might fail but it shouldn't fail in analysis of `couch_key_tree`, `couch_db` or `test_engine_util`.
=> Fix dialyzer warning on `couch_key_tree:merge/2`

src/couch_stats/src/couch_stats_process_tracker.erl
The argument names in `couch_stats_process_tracker:track/2` where the wrong way around leading to confusion.
=> Switching `couch_stats_process_tracker:track/2` argument names

src/mango/src/mango_httpd.erl
We used to call non exported function chttpd:send_error/6. Switch to
public `chttpd:send_error/2` for sending error.
induce error in mango or update code as follows 
```
diff --git a/src/mango/src/mango_httpd.erl b/src/mango/src/mango_httpd.erl
index 2e87771..e69001a 100644
--- a/src/mango/src/mango_httpd.erl
+++ b/src/mango/src/mango_httpd.erl
@@ -33,6 +33,8 @@
}).
handle_req(#httpd{} = Req, Db0) ->
+    Stack = erlang:get_stacktrace(),
+    chttpd:send_error(Req, {<<"ErrorStr">>, <<"ReasonStr">>, Stack}),
```
Issue mango query request
```
http --auth=adm:pass http://127.0.0.1:15984/mango_test_ffdbb10509f046cea3883d144586c02d/_index
HTTP/1.1 500 Internal Server Error
Cache-Control: must-revalidate
Content-Length: 59
Content-Type: application/json
Date: Fri, 02 Mar 2018 15:16:21 GMT …
```
=> Use `chttpd:send_error/2` in mango_httpd

src/couch_replicator/src/couch_replicator_auth.erl, src/couch_replicator/src/couch_replicator_auth_session.erl
The `{error, term()}` return type is added to both the `initialize/1`
callback and spec, which matches the underlying implementation.
Prior to this change, `make dialyze` should have displayed an error for these missing return types. That it didn't is presumably a dialyzer bug. In any case, run `make dialyze` should show no additional type check errors.
=> Add error tuple return type to replicator auth spec and callback

rebar.config.script
As discussed in
http://erlang.org/doc/efficiency_guide/binaryhandling.html, the
bin_opt_info option can have the compiler print information about
binary optimizations. Typically, it issues warnings about code that
can not be optimized. For example, with the option enabled, it warns
about this line of code (among many others) like this:
```
src/chttpd/src/chttpd_auth_cache.erl:183: Warning: NOT OPTIMIZED: sub binary is used or returned
```
Not only should having this option enabled draw awareness to existing
sub-optimal binary constructs, it should help developers avoid
creating new ones.
This is a compiler configuration change, so test it by running `make clean && make`. You should now see numerous warnings about failed binary optimizations such as
``` …
```
=> Introduce bin_opt_info erl_opts compilation option

src/couch/src/couch_att.erl
The `couch_att:from_disk_term` function is responible for conversion of
a disk format to #att{} record. However the way it is called
produces a dialyzer complaint.
Because `couch_att:from_disk_term` is always called as
`[couch_att:from_disk_term(Db, T) || T <- Doc1#doc.atts]`.
The `atts` field of `#doc{}` record is defined as
`[couch_att:att()] | binary()`
This is problematic because `att()` definition doesn't include disk
format representation. This commit adds disk format to the spec.
Run dialyzer tool and make sure there are no complains about `couch_att:from_disk_term`
1. Prepare for analysis:
```
make build-plt
```
2. Run analysis 
```
make dialyze apps=couch
```
The dialyzer might fail but it shouldn't fail in analysis of couch_att.
=> Fix dialyzer warning for couch_att:from_disk_term

src/couch/src/couch_file.erl
According to Erlang's [file:open](http://erlang.org/doc/man/file.html#open-2) docs this function returns `{error, Reason}` in case of failure but inside `couch_file:sync` and `init` functions there are no checks for this in two places. Consequently when I received `{error, emfile}` kind of error, process crashed with `badmatch` instead of a proper error.
Simulate `{error, emfile}` conditions (e.g. decrease `ulimit` on your OS) and observe an error.
=> Fix: Proper error handling for file:open() call in couch_file.erl

src/couch/src/test_engine_util.erl
Also make them into defines to be easier to adjust in the future
=> Increase PSE test engine timeouts

src/couch_replicator/src/couch_replicator_worker.erl
That was another place that could leak credentials in case of a crash
To test:
```
make eunit apps=couch_replicator suites=couch_replicator_worker
```
=> Implement format_status/2 for replication worker gen_server

src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_view.erl, src/chttpd/test/chttpd_db_test.erl, src/chttpd/test/chttpd_view_test.erl
Allow to POST to `/{db}/_all_docs/queries` and specify a queries list in the body, the same way you can do 
- for design documents `/{db}/_design_docs/queries`
- for local documents `/{db}/_local_docs/queries`
-  and for a regular MapReduce view `/{db}/_design/{ddoc}/_view/{viewname}/queries`
```
curl -u foo:bar -H "Content-Type: application/json" -X POST -d @multiple_queries.json http://localhost:15984/db/_all_docs/queries
{"results":[
{"total_rows":30,"rows":[
{"id":"point2","key":"point2","value":{"rev":"1-d942f0ce01647aa0f46518b213b5628e"}},
{"id":"point3","key":"point3","value":{"rev":"1-721fead6e6c8d811a225d5a62d08dfd0"}}
]},
{"total_rows":30,"offset":2,"rows":[
{"id":"point11","key":"point11","value":{"rev":"1-ffb6c2ae737918f8f911e1fce668333e"}}, …
```
=>  Support queries endpoints

src/couch_peruser/test/couch_peruser_test.erl
Replaced the `/_config` endpoint call using `config:set()` in the `set_config()` call to be more sure about configuration changes.
https://github.com/apache/couchdb/pull/1068#pullrequestreview-89269772
make check skip_deps+=couch_epi apps=couch_peruser
```
module 'couch_peruser_app'
module 'couch_peruser_sup'
module 'couch_peruser_test'
couch_peruser test
couch_peruser_test:162: should_create_anon_user_db_with_default...[0.002 s] ok
couch_peruser_test:163: should_create_anon_user_db_with_default...ok
couch_peruser_test:152: should_create_user_db_with_default...[0.002 s] ok
couch_peruser_test:153: should_create_user_db_with_default...ok
couch_peruser_test:175: should_create_user_db_with_q4...[0.002 …
```
=> Remove _config call in couch_peruser_test

src/couch/test/couch_passwords_tests.erl
Since we are using 3rd party app for `bcrypt` and `couch_passwords: bcrypt/2` is just an interface for it there are no need to test correctness of the lib itself, just the fact that we are using it properly.
Test `bcrypt_logRounds_18` is kind of a resource hog, so I suggest to remove it to easy a  burden on Travis and Jenkins. This reduces the test runtime on my laptop from 75s to 15s and I suspect the difference for CI will be even greater.
=> Replace resource expensive bcrypt test with shorter version

src/couch/include/couch_js_functions.hrl
We allow to specify `password_scheme` in user doc, but never check that it is one of the supported types. As a result it is possible to successfully create a user that'd throw error 500 on access attempt.
```bash
$ curl -X PUT http://localhost:15984/_users/org.couchdb.user:wooser -d'{"name":"wooser", "roles":[], "derived_key":"0123456789acbdef", "iterations":10, "salt":"heteronym", "password_sha":"alalalalalalalalala", "password_scheme":"wooser", "type":"user"}'
{"ok":true,"id":"org.couchdb.user:wooser","rev":"1-65c51dd556a8b03f040309e87308eda1"}
$ curl http://localhost:15984/_users/org.couchdb.user:wooser -u wooser:wooser
{"error":"case_clause","reason":"wooser","ref":17603030}
```
With this patch validator should output a proper warning
```bash
$ curl -X PUT …
```
=> Validate password_scheme in user doc

src/couch/src/couch_httpd.erl, src/couch_replicator/src/couch_replicator_httpc.erl, src/couch_replicator/test/couch_replicator_small_max_request_size_target.erl
Previously, when the server decided too much data was sent in the client's
request, it would immediately send a 413 response and close the socket. In the
meantime there could be unread data on the socket since the client keeps
streaming data. When this happens the connection is reset instead of going
through regular close sequence. The client, specifically the replicator client,
detected the reset before it had a chance to process the 413 response. This
lead to a retry, since it was interpreted as generic network error, instead of
a proper 413 HTTP error.
The improvement is to flush the receive socket before and after sending a 413
response, then close the connection. This reduces the chance of the socket
being closed with unread data, avoids a TCP reset, and gives the client a
better …
=> Fix 413 response handling and re-enable related couch replicator test

src/couchdb/couch_os_daemons.erl, src/couchdb/couch_os_process.erl
Ref #991.
Inspired by https://github.com/apache/couchdb/commit/f122f94291bfbc87496efca3c04540bb190b985a
=> Allow couchspawnkillable to live in directories with spaces

src/couch/src/couch_os_daemons.erl
See #997 and https://github.com/apache/couchdb/commit/f122f94291bfbc87496efca3c04540bb190b985a for context.
=> Allow couch_os_daemons to live in directories with spaces

src/couch_peruser/test/couch_peruser_test.erl
This PR removes some unreliable helper functions and addresses a race condition in acquiring security object that triggered occasionally test failures.
Local run `make eunit apps=couch_peruser suites=couch_peruser_test`, but most important Travis should stop breaking in couch peruser test suite.
Resolves #1236
=> Fix couch peruser test suite

test/javascript/couch_test_runner.js, test/javascript/tests/users_db_security.js
Closes #1238
1. log errors from waitForSuccess
2. log errors in testFun()
3. spinloop replaces arbitrary wait timeout
=> fix: more reliable password scheme tests

src/mem3/src/mem3_rep.erl
PSE changed the local_tree's join function so we need to update this. Previously we read _local docs out of the btree that ended up just giving us {DocId, {RevId, {BodyProps}}} to our callback. PSE changed things such that we now use couch_db:fold_local_docs which provides `#doc` records.
Shard substitution happens when a changes feed is provided with a since_seq that references a ndoe that does not or has errored out some how. The substitution then goes and looks for an internal replication document so that we don't have to rewrind the changes feed entirely (i.e., we look at the internal replication checkpoint and can rewind to the place where the node-being-replaced last sent us documents).
=> Fix shard substitution in changes feeds

src/couch/src/couch_os_process.erl
This was a latent bad merge that failed to remove the duplicate receive
statement. This ended up discarding the monitor's 'DOWN' message which
leads to an infinite loop in couch_os_proces:killer/1.
=> Fix killing of OS processes

test/javascript/tests/users_db_security.js
On restrained hosts bcrypt and sometimes pbkdf2 can't finish hashing for new users within 5 sec timeout leading to tests failures. This fix makes `loginUser` to actually wait for successful authentication.
Javascript test suite should pass on both Travis and Jenkins
Fixes #1238
=> Make loginUser wait for successful authentication

rel/overlay/etc/default.ini
deflate_N value is more clear description and obvious to replace only N. The same description is used in documentation.
=> fix file_compression value description

src/couch_replicator/src/couch_replicator_httpd.erl
Dialyzer run discovered:
```
Unknown function couch_replicator_httpd_utils:validate_rep_props/1
```
Indeed, the function should be
```
couch_replicator_httpd_util:validate_rep_props/1
```
=> Fix typo in node local _replicate handler

.gitignore, Makefile, Makefile.win, rebar.config.script, src/couch/test/couch_key_tree_prop_tests.erl
Key tree module is a candidate to use property tests on as it mostly deals with
manipulating a single data structure and functions are referentially
transparent, that is, they aren't many side-effects like IO for example.
The test consists of two main parts - generators and properties.
Generators generate random input, for example revision trees, and properties
check that certain properties hold, for example that after stemming all the
leaves are still present in the revtree.
To run the test:
`make eunit apps=couch suites=couch_key_tree_prop_tests`
=> Key tree property tests

src/fabric/src/fabric_doc_attachments.erl
Attachment receiver process is started with a plain spawn. If middleman process
dies, receiver would hang forever waiting on receive. After a long enough time
quite a few of these receiver processes could accumulate on a server.
Fixes #1264
=> Kill fabric attachment receiver when middleman times out

rel/overlay/etc/default.ini, src/couch/src/couch_server.erl
See https://github.com/apache/couchdb/issues/796#issuecomment-359060816
From IRC:
```
15:18 <+Wohali> davisp: is update_lru_on_read something that should be in default.ini?
15:18 <+davisp> Mebbe
15:18 <+davisp> We run it by default cause a good number of clusters would get crushed without it
15:19 <+davisp> But its a behavior change so never made default
```
Discussion welcome.
=> Set update_lru_on_read=false as default

src/couch_replicator/src/couch_replicator_scheduler.erl
Replication jobs are backed off based on the number of consecutive crashes,
that is, we count the number of crashes in a row and then penalize jobs with an
exponential wait based that number. After a job runs without crashing for 2
minutes, we consider it healthy and stop going back in its history and looking
for crashes.
Previously a job's state was set to `crashing` only if there were any
consecutive errors. So it could have ran for 3 minutes, then user deletes the
source database, job crashes and stops. Until it runs again the state would
have been shown as `pending`. For internal accounting purposes that's correct
but it is confusing for the user because the last event in its history is a
crash.
This commit makes sure that if the last even in job's history is a crash user
will see the …
=> In _scheduler/docs fix `crashing` state showing as `pending` sometimes

rel/overlay/etc/default.ini
Documents the heretofore hidden `[couchdb] enable_database_recovery` ini file option.
A similar PR against couchdb-documentation is coming.
=> Document enable_database_recovery ini option

src/couch/src/couch_httpd_multipart.erl
This was introduced in:
https://github.com/apache/couchdb/commit/083239353e919e897b97e8a96ee07cb42ca4eccd
Issue #1286
=> Fix length badarg error in mp parser

rel/overlay/etc/vm.args
enif_send (in bcrypt support) requires beam.smp. So, force its use everywhere.
Fixes #1296
=> Force use of SMP enabled BEAM VM, fixes #1296

rebar.config.script
Pursuant to apache/couchdb-fauxton#1079 we need to bump our fauxton dependency to fix Fauxton builds. (Right now, Jenkins is completely broken because of a renamed dependency in npm-land preventing Fauxton from building.)
=> Bump fauxton to fix CI builds

rel/overlay/etc/vm.args
In chats with @nickva it became clear that this is a recommended setting. I have found this to limit pid explosion (and thus RAM explosion) across multiple production envs, especially where https is used for the replication reader.
We should make it the default going forward.
=> Add SSL session_lifetime limit for ibrowse pids

src/mango/src/mango_idx_view.erl, src/mango/test/12-use-correct-index-test.py
Mango requires that a JSON index can only be used to fulfil
a query if the "selector" field covers all of the fields the
index. For example, if an index contains ["a", "b"] but the
selector only requires field ["a"] to exist in the matching documents,
the index would not be valid for the query (because it only includes
documents containing both "a" and "b").
There is a special case here around built-in fields; _id and _rev
specifically, because they are guaranteed to exist in any matching
documents.
If a user declares an index ["a", "_id"], we can safely exclude "_id"
from the index coverage check, so a selector of {"a": "foo"} should be
able to use this index.
Prior to this commit, a user would have to alter the selector so that
it covered the "_id" field, e.g. {"a": "foo",
"_id": …
=> Mango: implicit coverage for _id and _rev during index selection

Jenkinsfile
* Newly provisioned Docker images
* Add ubuntu bionic (18.04) support
* Add our own couch-js/couch-libmozjs185 pkgs to rolling repo build
This is the last step before releasing Ubuntu 18.04 images as requested in #1314 and to work around the root cause of #1293.
Jenkins should show green in about ~1hr here: https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-new-images/6/pipeline
=> Update Jenkins build process

Jenkinsfile
This is the 2.1.x version of #1347.
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-new-images-2.1.x/1/pipeline can't go green because the current state of the 2.1.x branch is broken (Fauxton fails to build).
=> Update Jenkins build process (2.1.x branch)

src/couch/src/couch.app.src
Releases and dialyzer checks need app dependencies to work properly
Issue: #1346
=> Add hyper app to dependencies

src/couch/src/couch_query_servers.erl, src/couch_mrview/src/couch_mrview.erl, src/fabric/src/fabric_rpc.erl, src/fabric/src/fabric_view.erl
One bugfix and one enhancement here. The bugfix is that the `finalize` operation introduced for `_approx_count_distinct` was not being executed on view requests coming in through the non-clustered interface, so any attempt to use that reduce function there would crash.
The enhancement is to take advantage of that `finalize` operation to optimize the builtin `_stats` reduce function. Previously the reduce function would always write down an ejson form for the 5 statistical quantities to disk as it could never know whether the `rereduce` function was being called during indexing or during querying. Now that we have the `finalize` operation (which only runs at query time) we can store a more compact format on disk and avoid continuously translating back and forth between the compact and …
=> Fix _approx_count_distinct on non-clustered interface, optimize _stats

Makefile, rebar.config.script
This modification allows to run compile on individual applications and makes compiler flag `bin_opt_info` optional to reduce amount of compiler's warnings as discussed [here](https://github.com/apache/couchdb/pull/1215#issuecomment-392826035)
Standard test suite should pass
Command `make apps=chttpd` should compile only `chttpd` application (may need to delete its `ebin` first to actually recompile)
Command `ERL_OPTS=bin_opt_info make apps=chttpd` should recompile `chttpd` with all compiler's warnings.
Discussion on #1215
=> Make `bin_opt_info` optional

src/couch_mrview/src/couch_mrview_index.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_mrview/test/couch_mrview_index_info_tests.erl
It was brought to my attention that the active size looked a bit funny
occasionally as it could be larger than the file size. Given that active
size is defined to be the number of bytes used in a view file it must be
strictly greater than or equal to zero as well as less than or equal to
file size. Thus the great hunt had begun!
While I'd love more than anything to regail you, Dear Reader, with the
tales, the joys, the highs, and yes, even the lows of this search, it
turns out that I cannot. I must not. For there were none!
Turns out this was a trivial bug where we were re-using the ExternalSize
calculation instead of applying `couch_btree:size/1` to all of the
btrees in the `#mrview` records. Simple bug comes with a correspondingly
simple fix.
I also noticed that the info tests were …
=> Fix active size calculations for views

src/couch/src/couch_db.erl, src/couch/src/couch_db_updater.erl, src/couch/src/couch_key_tree.erl, src/couch/test/couch_key_tree_tests.erl
Optimize document updates by reducing the number of times couch_key_tree:stem/2 is called along with improving the performance of couch_key_tree:stem/2.
For the first part this mostly just involves ensuring that we pass paths to couch_key_tree:merge/2 in a specific order and then stem after we're done merging (if required, in the prep_and_validate_replicated_updates a stem is not needed so is avoided entirely).
For the second part, the old stemming algorithm worked by completely disassembling the tree and then reassembling it one path at time by merging back into a tree accumulator. The new algorithm is a recursive descent into the tree tracking depth and distance from leaves while unwinding the stack. This allows us to convert the O(N^2) approach from merging all branches back into the …
=> Optimize doc updates

src/couch/src/couch_server.erl, src/couch/src/couch_util.erl, src/couch_log/src/couch_log_server.erl, src/ddoc_cache/src/ddoc_cache_lru.erl, src/mem3/src/mem3_shards.erl, src/rexi/src/rexi_server.erl
Use `process_flag(message_queue_data, off_heap)` on critical processes on Erlang VMs that support it.
`make eunit`
=> Add set mqd off heap

src/fabric/src/fabric_doc_atts.erl, src/fabric/src/fabric_rpc.erl
Passing closures around is fragile and prevents smooth upgrading. Instead pass
a tuple with a data from the receiver closure explicitly and convert to back to
a local fun locally on each node.
This is a preparatory commit before the switch. To ensure attachment uploading
requests are successful, would need to first install this change on all the
nodes. Then in a separate upgrade step, switch fabric.erl to call
fabric_doc_atts:receiver instead fabric_doc_attatchments:recevier.
=> Prepare to fabric attachment receiver from a fun closure to a tuple

src/mango/src/mango_cursor.erl, src/mango/src/mango_idx.erl, src/mango/src/mango_idx_special.erl, src/mango/src/mango_idx_view.erl, src/mango/src/mango_selector.erl, src/mango/test/02-basic-find-test.py, src/mango/test/18-json-sort.py
This is an user experience improvement. If a selector has a sort field set
then an index is only valid if the prefix of the sort fields match the 
prefix of the index fields. 
e.g Index = [A, B, C] with Sort = [A, B] is a valid sort
but if Sort = [B, C] then it is not valid for this index.
If an indexed field in the selector is constant, eg {A: {$eq: 21}} then
we can add it to the sort list because it won't affect sorting and the
original sort will still be valid.
e.g Index = [A, B] with Sort = [B] and selector has {A: 1}. 
Then we can make the Sort = [A, B].
The sort will work as expected and this will increase the possibility
of the index being chosen. It also helps a user where they might not have
put the correct initial fields in the sort.
See the tests in the PR for examples
=> Add fields to sort based on selector

rebar.config.script
=> Update snappy dep to CouchDB-1.0.1 with 21.0 support

src/couch/src/couch_httpd.erl
During 21.0 testing, the hack to read extra data from the socket to give the
client a better chance of detecting a 413 response ended up failing. Either
process scheduling or IO scheduling was different enough that the test started
failing fairly consistently.
Apply a better fix that's more in-line with the intent -- after responding to
the client with a 413, read a limited amount of data off the socket (1MB).
Limit the maximum time spent doing it to less than 1 second.
Issue #1396
=> A better fix for handling node local 413 responses

INSTALL.Unix.md
Trivial update to reflect build deps for FreeBSD in docs.
Tested on FreeBSD 11.1 + `make check` - all tests pass.
=> Update build dependency docs for FreeBSD

src/couch/src/couch_native_process.erl, src/couch/test/couch_changes_tests.erl
In case when CouchDB has a native query server enabled and we call an Erlang `map` function for the first time (therefore there is no view index) `couch_mrview_updater:start_update` calls `run(State, [<<"map_doc">> , Doc])` from the `couch_native_process` and after this view index is built and data is read from it. Unfortunately when the same Erlang map function is used for changes feed with `_view` filter, `couch_native_process` crashes with:
```
{"error":"error","reason":"{{function_clause,\n     
[{couch_native_process,ddoc,\n          [{evstate, 
```
Changes feed with `_view` filter allows to use existing map function as the filter and it doesn’t query the view index files. Furthermore `seq_indexed` option doesn't work correctly in the mrview (more details in [this …
=> Fix for a function_clause crash in the couch_native_process for Erlang views

src/couch/src/couch_bt_engine.erl, src/couch/src/couch_server.erl
When we delete files with context option set to `delete`, `couch_file` respects configuration flag "enable_database_recovery" and just renames the files in case it's set to true.
This change removes context for compaction files deleted during database deletion to make sure we are actually erasing them and not just renaming and leaving behind.
Change config `rel/overlay/etc/local.ini` and add into `[couchdb]` section 
```
enable_database_recovery = true
delete_after_rename = false
```
Then run
```
curl -X PUT http://127.0.0.1:15984/koi
curl -X POST http://127.0.0.1:15984//koi/_compact
curl -X DELETE http://127.0.0.1:15984/koi
```
Check files in `./dev/lib/node1/data`, without this fix it should look something like:
```
...
|   |-- nodes.couch
|   `-- shards
|       |-- 00000000-1fffffff
| …
```
=> Don't set context for compaction files during db delete

src/couch/src/couch_bt_engine.erl, src/couch/src/couch_bt_engine_header.erl, src/couch/src/couch_db_engine.erl, src/couch/src/test_engine_get_set_props.erl
Add the ability to properties to a database. This would allow us to define if the database supports `shardkeys` or `_access` or anything unique to it.
The eunit tests should all pass.
=> [wip] Create property storage in db engine

src/chttpd/src/chttpd.erl
The https we optimally start doesn’t read any server options, that prevents users from applying things like `{max, 512}` sockets for mochiweb. This PR adds support for this:
```ini
[httpsd]
server_options = [{max, 512}]
```
=> allow socket server configuration for TLS httpd

src/couch/src/couch_db_updater.erl, src/couch/src/couch_key_tree.erl, src/couch/src/test_engine_util.erl, src/couch/test/couch_key_tree_tests.erl
After the https://github.com/apache/couchdb/commit/aebdbc452573f70f4e50d88af5814d0fbe936333#diff-c0abd721a4433ae0399b0c2cbdea8d18
stemming is done separately from merge so stem_interactive option didn't take
effect. That is mostly ok as speed improvements should reduce the need for
that option, but it still might be nice to keep the option (just in case).
Also, a nice side effect is it removes an extra external function from
couch_key_tree module and simplifies the tests a bit.
Related PR: https://github.com/apache/couchdb/pull/958
=> Make stem_interactive option work again

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_auth.erl
=> hook up proxy auth handler to chttpd

src/couch_mrview/src/couch_mrview_compactor.erl
Previously on view compaction, the new index state would not carry
over the associated database update sequence. As a result, views
who were compacted at least once could no longer use the ?update_seq
query option.
Closes #984
=> Views now retain update_seq after compaction.

Jenkinsfile
This PR changes our Jenkins setup to run the `make dist` process on Erlang 17.5.3 instead of R16B03. This will allow us to drop R16B03 support in `rebar.config.script` as proposed in #1427.
https://builds.apache.org/job/CouchDB/job/jenkins-ditch-16b03/ when this lights up green, I will merge this.
=> Replace R16B03 with 17.5.3 for PR#1427

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_auth_request.erl
This is a leftover from the 1.x -> 2.x transition. Adds a config option (bike shed away pls) to block non-admins from accessing `/_all_dbs`, which we should set to `true` in 3.0.0
=> Optionally prevent non-admins from accessing /_all_dbs

configure, src/chttpd/src/chttpd.erl, src/couch/rebar.config.script, src/couch/src/couch_bt_engine.erl, src/couch/src/couch_db.erl, src/couch/src/couch_file.erl, src/couch/src/couch_hash.erl, src/couch/src/couch_httpd.erl, src/couch/src/couch_native_process.erl, src/couch/src/couch_stream.erl, src/couch/src/test_engine_util.erl, src/couch/test/couchdb_attachments_tests.erl, src/couch_epi/src/couch_epi_data.erl, src/couch_epi/src/couch_epi_util.erl, src/couch_index/test/couch_index_ddoc_updated_tests.erl, src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_replicator/src/couch_replicator_ids.erl, src/couch_replicator/test/couch_replicator_many_leaves_tests.erl, src/couch_replicator/test/couch_replicator_test_helper.erl, src/mem3/src/mem3_rep.erl
This aims to enable CouchDB to run in an environment where OpenSSL MD5 hash operations are explicitly disallowed by the operating system, for example: when running in "FIPS mode." Because CouchDB does not make use of MD5 hashes for cryptographic purposes, this workaround does not defeat the purpose of "FIPS mode," provided that the system owner is aware of and consents to its use.
- Add a module that selects the library to use for MD5 hash operations depending on a configure flag. If the flag is used, the module's functions use erlang:md5. If not, the functions use crypto:hash(md5, ...).
- Add to configure and rebar scripts to provide the configure flag and define an environment variable when it is used.
- Replace crypto:hash(md5, ...) calls with calls to functions in the new module. …
=> Make MD5 hash implementation configurable

Makefile, Makefile.win, build-aux/couchdb-build-release.sh, src/chttpd/src/chttpd_misc.erl, src/chttpd/test/chttpd_welcome_test.erl, src/couch/rebar.config.script, src/couch/src/couch_server.erl
=> report git sha on welcome request

src/couch/src/test_request.erl
should close #884 and a lot of other spurious errors.
=> add retry to test_request:request()

rel/overlay/etc/default.ini
If #1253 doesn't make it into 2.2.0, this one should go in.
=> re-raise max_http_request_size to 4GB

src/fabric/src/fabric.erl
Function closures are fragile and attachment uploads would break if
fabric_doc_attachments is different on any of the nodes in a cluster, like it
might happen during a roling cluster upgrade.
Previously fe53e437ca5ec9d23aa1b55d7934daced157a9e3 introduced two versions of
the module one which handles function closure, other which handled message but
only in this commit messages are starting to be sent.
To avoid breakages in attachemnt uploads during the period of a rolling cluster
upgrade, make sure to upgrade to that commit first then upgrade to this change.
Issue #1394
=> Switch fabric attachment reciever to use messages instead of function closures

test/elixir/test/replication_test.exs
Implement `delete_on_exit/1` and use it to delete replication dbs for tests which currently lack clean up. Replace existing on_exit calls with new function.
Before this PR, run `mix test --trace test/replication_test.exs` and then look at `/all_dbs` and notice all the dbs like `random-test-db--576460750833332000--576460752303423488_src` etc.
After deleting those test dbs, apply this PR and run the tests again: all replication dbs should have been cleaned up.
=> Clean up replication dbs on exit

.travis.yml, rebar.config.script
20.x release series is done now, use the latest version for regression testing.
=> bump docs dependency, travis 20.1 -> 20.3

src/couch/src/test_util.erl
Sometimes it is hard to guess what went wrong when application
started via `test_util:start_applications` or `test_util:start_couch`
is unable to start. Since the traceback was truncated.
This change would print the reason in addition to the traceback.
1. Modify code so application is unable to start
```
git diff
diff --git a/src/config_app.erl b/src/config_app.erl
index 8ba58e6..140e6df 100644
--- a/src/config_app.erl
+++ b/src/config_app.erl
@@ -22,7 +22,7 @@
%% ===================================================================
start(_StartType, _StartArgs) ->
-    config_sup:start_link(get_ini_files()).
+    nok = config_sup:start_link(get_ini_files()).
```
2. Run tests for config app `make eunit apps=config tests=config_del_test`
3. Make sure the error is printed
```
Compiled …
```
=> Improve logging from test_util

src/couch/src/couch_query_servers.erl
According to [documentation for _stats reduce function](http://docs.couchdb.org/en/2.2.0/ddocs/ddocs.html#_stats) there is support for the case when map emits array of integers. This PR fixes this use case (fixup for https://github.com/apache/couchdb/commit/5fa3c43f2c7313b18a63c0100ab2b1843bd8ab94). 
```
make check apps=couch tests=reduce_stats_test
```
and following reproducer script courtesy of @nickva  
```
#!/bin/bash
S=${1:-adm:pass@localhost:15984}
DB=${2:-statsdb1}
curl -XDELETE $S/$DB
curl -XPUT $S/$DB
curl -s -XPOST $S/$DB -d '{"_id":"_design/dd2","views":{"v1":{"map":"function(doc){emit(null, doc.x) };","reduce":"_stats"}}}' -H 'Content-Type: application/json'
curl -s -XPOST $S/$DB -d '{"x": [1,2]}' -H 'Content-Type: application/json'
curl $S/$DB/_design/dd2/_view/v1
```
Fixes …
=> Fix _stats reducer when map function emits array

Makefile
Fixed use of find ... -printf "%f" in Makefile. Option "-printf" is not supported on Mac OS, but can be replaced by ```-exec basename```
run ```make list-js-suites``` and  ```make list-eunit-suites``` to make sure it works as expected on both Mac OS and linux
See  issue #1028
=> Fixed use of find ... -printf "%f" in Makefile

src/couch_epi/README.md, src/couch_epi/src/couch_epi_data.erl, src/couch_epi/src/couch_epi_sup.erl, src/couch_epi/test/couch_epi_tests.erl
This fixes the use case when data provider module for `couch_epi` is not a pure functional.
To illustrate the issue let's look at the following code:
```
-export([data/0]).
data() ->
config:get("some_section").
```
We would want to regenerate dynamically compiled module when term returned from `data/0` is changed. However the previous implementation of `module` data provider was relying on `vsn` attribute of a module. Which is valid approach if the data term is hard coded in the module source.
This PR also renames `module` data provider into `static_module`.
```
make eunit apps=couch_epi
```
=> Support callback module data provider

test/elixir/test/conflicts_test.exs
Port conflicts.js
`mix test --trace test/conflicts_test.exs`
=> Port conflicts.js

src/couch/src/couch_att.erl
`#leaf.atts` data structure is a `[{Position, AttachmentLength}, ...]` proplist
which keeps track of attachment lengths and it is used when calculating
external data size of documents. `Position` is supposed to uniquely identify an
attachment in a file stream. Initially it was just an integer file offset. Then,
after some refactoring work it became a list of `{Position, Size}` tuples.
During the PSE work streams were abstracted such that each engine can supply
its own stream implementation. The position in the stream then became a tuple
that looks like `{couch_bt_engine_stream,{<0.1922.0>,[{4267,21}]}}`. This was
written to the file the `#leaf.atts` data structure. While still correct, it is
unnecessarily verbose wasting around 100 bytes per attachment, per leaf.
To fix it use the disk …
=> Reduce size of #leaf.atts keys

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_misc.erl, src/couch/src/couch_app.erl, src/couch/src/couch_httpd_misc_handlers.erl, test/javascript/run, test/javascript/test_setup.js
We need to be able to restart CouchDB from integration test suite.
We used to have this feature, but it was removed.
This PR brings this functionality back under `/_node/$node/_restart`.
1. compile and start CouchDB using `dev/run`
```
make && dev/run --admin=adm:pass
```
2. try to access new endpoint as non authenticated user (you shouldn't be able to)
```
curl -s -X POST 127.0.0.1:35984/_node/node1@127.0.0.1/_restart
```
3. note number of ets tables on the node 
```
curl -s -u adm:pass -X GET 127.0.0.1:35984/_node/node1@127.0.0.1/_system | jq '.ets_table_count'
```
4. trigger restart of the node (the call should succeed)
```
curl -s -u adm:pass -X POST 127.0.0.1:35984/_node/node1@127.0.0.1/_restart
```
5. keep checking the number of ets tables on the node. The call should return `null` …
=> Add `POST /_node/$node/_restart` endpoint

src/couch/src/couch_bt_engine.erl, src/couch/src/couch_db.erl, src/couch/src/couch_db_engine.erl, src/couch/src/couch_db_updater.erl, src/fabric/src/fabric_doc_open.erl
This is the first of five PRs for enabling clustered purge. This is a fairly simple PR that just cleans up a number of minor bugs and typos that were found while testing.
=> [1/5] Clustered Purge - Misc Cleanup

src/couch/src/couch_bt_engine_compactor.erl, src/couch/src/couch_db_engine.erl, src/couch/src/couch_db_plugin.erl
This adds an on_compact hook to the couch_db_plugin. This is so that secondary indices can create their local purge sequence docs when a database is upgraded to use clustered purge.
This depends on PRs #1366, #1367, and #1368.
=> [4/5] Clustered Purge: Add on_compact EPI hook

src/rexi/src/rexi_sup.erl
Previously, as described in issue #1571, `rexi_server_sup` supervisor could die
and restart. After it restarts `rexi_server_mon` would not respan rexi servers
as it wouldn't notice `rexi_server_sup` went away and come back. That would
leave the cluster in a disabled state.
To fix the issue, switch restart strategy to `rest_for_one`. In this case, if a
child at the top dies it will restart all the children below it in the list.
For example, if `rexi_server` dies, it will restart all the children. If
`rexi_server_sup` dies, it will restart `rexi_server_mon`. And then on restart
`rexi_server_mon` will properly spawn all the rexi servers.
Same for the buffers, if `rexi_buffer_sup` dies, it will restart `rexi_buffer_mon`
and on restart it will spawn buffers as expected.
Fixes: #1571
=> Switch rexi_sup restart strategy to rest_for_one

src/couch/src/couch_query_servers.erl, src/couch/test/couch_query_servers_tests.erl
The builting _sum reduce function has no protection against overflowing
reduce values. Users can emit objects with enough unique keys to cause
the builtin _sum to create objects that are exceedingly large in the
inner nodes of the view B+Tree.
This change adds the same logic that applies to JavaScript reduce
functions to check if a reduce function is properly reducing its input.
make check
=> Fix builtin _sum reduce function

src/mem3/src/mem3.erl, src/mem3/src/mem3_util.erl
Improves validation of database creation parameters, giving a more readable error.
Try to create a db with invalid parameters and confirm a clean error response (and no database)
N/A
=> Improve validation of database creation parameters

src/mem3/include/mem3.hrl
The violation of shard record construction is reported in several files, including  `fabric_doc_open_revs.erl`, `cpse_test_purge_replication.erl`, etc. This PR is aimed to address these warnings.
```
src/fabric_doc_open_revs.erl:0: in fabric_doc_open_revs:check_finish_quorum/0[385-396]:Record construction #shard{node::'node1',range::'undefined'} violates the declared type of field range::'_' | ['$1' | '$2' | non_neg_integer()]
src/cpse_test_purge_replication.erl:0: in cpse_test_purge_replication:make_shard/1[196-201]:Record construction #shard{node::atom(),range::[0 | 4294967295,...],opts::'undefined'} violates the declared type of field opts::[any()]
```
Run dialyzer tool and make sure there are no complains about shard record construction
1. Prepare for analysis:
```
make build-plt
``` …
=> Fix dialyzer warning of shard record construction

src/couch/test/couchdb_mrview_tests.erl, src/fabric/src/fabric.erl
The previous implementation was based on a search using
{view_index_dir}/.shards/*/{db_name}.[0-9]*_design/mrview/*
This wildcard includes all shards for all indexes of all databases.
This caused performance issues in the case when there are thousands of databases on the node.
This PR changes the search to look at index_directory of a database.
```
make && make eunit apps=couch tests=mrview_cleanup_index_files_test_
```
N/A
=> Improve cleanup_index_files

src/chttpd/src/chttpd_db.erl, src/chttpd/test/chttpd_db_test.erl
We removed a security call in `do_db_req` in apache/couchdb#1246 to avoid duplicate authorization check and as a result there are now no db validation in noop call `/db/_ensure_full_commit`. This makes it always return a success code, even for the missing databases.
This fix places the security check directly in `_ensure_full_commit` call and adds eunit tests for a good measure.
`make eunit apps=chttpd suites=chttpd_db_test` for isolated tests
Closes apache/couchdb#1585
=> Check if db exists in /db/_ensure_full_commit call

src/fabric/src/fabric_util.erl
If, when a database is created, it was not possible to create any of
the shard files, the database cannot be used. All requests return a
"No DB shards could be opened." error.
This commit changes fabric_util:get_db/2 to create the shard file if
missing. This is correct as that function has already called
mem3:shards(DbName) which only returns shards if the database exists.
It's tricky. You need to have max_dbs_open's worth of files open on all nodes when creating the database. This ensures the _dbs doc is created (as this db is opened at startup and stays open) but none of the shards.
The easiest test is as follows;
1. Create the db
2. stop couchdb (all nodes)
3. delete the .couch files under the 'shards' directory
4. start couchdb
5. try to do anything with the database, get "No DB …
=> Create shard files if missing

src/couch/src/couch_db.erl, src/fabric/src/fabric_view_changes.erl, src/mem3/src/mem3_rep.erl
During a recent rolling upgrade, we observed the changes feed rewinding to a very old version, which caused performance issues for the client since it had to slog through millions of previously seen changes. Unfortunately, there is no logging when the changes endpoint is forced to rewind, so this adds such logging .
Unfortunately, this is not trivial to test.
=> Log error when changes forced to rewind to beginning

src/couch/src/couch_server.erl, src/couch/test/couch_server_tests.erl
There are two separate bugs here being fixed. The first was in `couch_server:terminate/2`. If there was an active open_async process when couch_server died it would throw a function clause when it tried to shutdown the database that wasn't yet open. We just filter out any `#entry{}` record to avoid the issue. This a simple bug but it prevented couch_server from properly generating a SASL report that ended up covering up the second more complex race condition.
The second bug has to deal with a race between deletions and opens as well as the state of couch_server's mailbox. There's a very specific set of operations that have to happen in a particular order to trigger this bug:
1. An in-flight open or creation request that will ultimately succeed. The `'$gen_call'` message must be in …
=> Fix couch server race condition

src/couch/src/couch_server.erl, src/couch/src/couch_util.erl, src/couch_log/src/couch_log_server.erl, src/ddoc_cache/src/ddoc_cache_lru.erl, src/mem3/src/mem3_shards.erl, src/rexi/src/rexi_server.erl
Off-heap messages is an Erlang 19 feature:
http://erlang.org/doc/man/erlang.html#process_flag_message_queue_data
It is adviseable to use that setting for processes which expect to receive a
lot of messages. CouchDB sets it for couch_server, couch_log_server and bunch
of others as well.
In some cases the off-heap behavior could alter the timing of message receives
and expose subtle bugs that have been lurking in the code for years. Or could
slightly reduce performance, so a safety measure allow disabling it.
```
> erlang:process_info(whereis(couch_server), message_queue_data).
{message_queue_data,off_heap}
> config:set("off_heap_mqd","couch_server","false").
ok
> exit(whereis(couch_server), kill).
true
> erlang:process_info(whereis(couch_server), message_queue_data). …
```
=> Allow disabling off-heap messages

src/couch/src/couch_server.erl
This PR provides two performance related improvements to couch_server:
1. Use `{read_concurrency, true}` for the protected `couch_dbs` ETS table used in couch_server.
2. Don't send update_lru messages to couch_server when disabled
More details in the corresponding commit messages.
Standard test suite should do the trick.
=> Couch server improvements

src/couch/src/couch_file.erl
Erlang OTP logs the fact when gen_server behavior crashes. However in case of couch_file the filename is not part of the state. So it is quite hard to figure out what happened given the current log entry format. This PR adds information about filepath to the log entry. Keep in mind though that the filepath value is captured on couch_file:start_link. It is not representing the current file name if file is renamed or moved.
1. Start couchdb `dev/run --admin=adm:pass`
2. Start remsh session `dev/remsh`
3. Inject failure in one of the couch_file processes (by reading with position greater than the file size) 
```
{_Port, Pid, _Fd, _Name} = hd(couch_debug:opened_files()).
couch_file:pread_binary(Pid, 999999999999999).
```
4. Check logs to make sure the following messages are present:
``` …
```
=> Implement couch_file:format_status to log filepath

src/fabric/src/fabric_rpc.erl, src/fabric/test/fabric_rpc_purge_tests.erl
Previosly local node revisions were causing `badmatch` failures in read repair
filter. Node sequences already filtered out local nodes while NodeRevs didn't, so
during matching `{Node, NodeSeq} = lists:keyfind(Node, 1, NodeSeqs)` Node would
not be found in the list and crash.
Example of crash:
```
fabric_rpc:update_docs/3 error:{badmatch,false}
[{fabric_rpc,'-read_repair_filter/3-fun-1-',4,[{file,"src/fabric_rpc.erl"},{line,360}]},
```
=> Ignore local nodes in read repair filtering

src/mango/src/mango_cursor_view.erl
This fixes an issue when doing a rolling upgrade of a CouchDB cluster
and adding commit a6bc72e the nodes that were not upgraded yet would
send through all the docs in the index and those would be passed through
to the user because the co-oridnator would assume it was matched at the
node level. This adds in a check to see if it has been matched at the
node level or not. And then performs a match if required.
This is tricky to test. If you have nodes running an older version of CouchDB, this should stop unmatched docs from being returned to the user.
=> Mango match doc on co-ordinating node

test/elixir/test/compact_test.exs, test/elixir/test/conflicts_test.exs, test/elixir/test/test_helper.exs
This fixes compilation errors from functions duplicated in multiple files by removing the duplicates.
`make` should now compile without failure
=> Remove redundant functions

build-aux/logfile-uploader.py, dev/run, rel/overlay/bin/couchup, test/javascript/run
Recent Linux distributions start defaulting to Python 3, and require
ambiguous scripts to be more explicit.
For example building for Fedora 30 (not released yet) fails with:
ERROR: ambiguous python shebang in /opt/couchdb/bin/couchup:
#!/usr/bin/env python. Change it to python3 (or python2) explicitly.
So this commit changes the four Python scripts to use `python2`.
Note: They seem to be Python-3-compatible, but I couldn't be sure. If
you know they are, please tell me, I'll change it to `python3`.
=> Explicit Python version in scripts

src/couch_replicator/src/couch_replicator_connection.erl
Previously when an owner process crashed before it had a chance to release the
worker to the pool, the worker entry was simply deleted. In some cases that
was ok because ibrowse's inactivity timeout would kick in and connection would
stop itself. In other cases, as observed in practice with _changes feed
connection over TLS protocol, inactivity timeout would never fire, so these
deleted connections would slowly accumulate leaking memory and filling the
process table. TLS connection would keep an associated session
open as well making things even worse.
To prevent the connection leak, explicitly unlink and kill the worker.
=> Improve connection cleanup in replication connection pool

rel/overlay/etc/default.ini, src/rexi/src/rexi_server_mon.erl, src/rexi/src/rexi_utils.erl
This has been solid for years and when not enabled can be a performance
bottleneck.
Fixes #1625
=> Switch rexi server_per_node to true by default

src/couch_replicator/src/couch_replicator_docs.erl
Previously a user could insert a VDU function into one of the _replicator
databases such that it prevents the replicator application from updating
documents in that db. Replicator application would then crash and prevent
replications from running on the whole cluster.
To avoid crashing the replicator when saving documents, log the error
and return `{ok, forbidden}`. The return might seem odd but we are
asserting that forbidden is an OK value in this context and explicitly
handling it. This shape of the return also conforms to the expected
`{ok, _Rev}` result, noticing that `_Rev` is never actually used.
=> Do not crash replicator on VDU function failure

src/couch/src/couch_db.erl
Previously we only checked that the suffix of the database is
matching one of the predefined system databases. We really should
check the prefix against DBNAME_REGEXP to prevent creation of
illegally named databases.
```
make eunit apps=couch tests=validate_dbname_fail_test_,validate_dbname_success_test_,is_systemdb_test_
```
This fixes #1644
=> Validate database prefix against DBNAME_REGEX for system dbs

src/chttpd/src/chttpd_misc.erl
According to [documentation](http://docs.couchdb.org/en/2.2.0/api/server/common.html#active-tasks) CouchDB Server Administrator privileges required to access this end-point. This patch adds the according check.  
Full test suite should pass.
Closes #1643
=> Restrict access to _active_tasks to server admin

src/chttpd/src/chttpd_db.erl, src/couch/priv/stats_descriptions.cfg
Introduce the `couchdb.document_purges` counter
Using metric to see the newly added counter
https://issues.apache.org/jira/browse/COUCHDB-3326
https://github.com/apache/couchdb/pull/1370
=> Add document_purges counter for stats

src/couch/src/couch_file.erl
Previously we were testing if Pos + TotalBytes exceeded the pread
limit. This is the wrong logic entirely. We are trying to prevent an
attempted call to file:pread/3 where the third parameter, the number
of bytes to read, is a very large number (due to a corruption
elsewhere, say). Instead we throw exceed_limit as soon as a file gets
above a certain size.
I switched this to an if statement to make it clear that the "read
past EOF" and "try to read too many bytes" checks are quite distinct
from each other.
=> Test correct condition for exceed_limit error

src/couch/src/couch_bt_engine_header.erl, src/couch/test/couch_bt_engine_upgrade_tests.erl
For databases generated prior to clustered purge builds, the `db_header` record was changed to below, i.e. with purge_tree and purge_seq_tree.
```
-record(db_header, {
disk_version = ?LATEST_DISK_VERSION,
update_seq = 0,
unused = 0,
id_tree_state = nil,
seq_tree_state = nil,
local_tree_state = nil,
purge_tree_state = nil,
purge_seq_tree_state = nil, %purge tree: purge_seq -> uuid
security_ptr = nil,
revs_limit = 1000,
uuid,
epochs,
compacted_seq,
purge_infos_limit = 1000
}).
```
However, the disk_version is still not upgraded and this caused mismatch between disk_version and actual `db_header` record, and there is the following error.
```
**throw:{{invalid_header_size,{db_header,6,1,0,
{5681,{1,0,{size_info,1426,5361}},111},
{5792,1,108},
{24780,[],419}, …
```
=> Upgrade disk version to 7/latest for databases generated prior to clustered purge builds

src/couch/src/couch_bt_engine_header.erl
Fix test failure on `upgrade_v5_test`.
make check skip_deps+=couch_epi apps=couch
```
module 'couch_bt_engine_header'
couch_bt_engine_header: upgrade_v5_to_v7_test...ok
couch_bt_engine_header: upgrade_uuid_test...ok
couch_bt_engine_header: upgrade_epochs_test...ok
couch_bt_engine_header: get_uuid_from_old_header_test...ok
couch_bt_engine_header: get_epochs_from_old_header_test...ok
[done in 0.015 s]
```
https://github.com/apache/couchdb/pull/1657
COUCHDB-3326
=> Fix test failure on upgrade_v5_test

src/couch_log/src/couch_log_formatter.erl, src/couch_log/src/couch_log_sup.erl, src/couch_log/test/couch_log_formatter_test.erl
`gen_server`, `gen_fsm` and `gen_statem` might send extra args when terminating. This
is a recent behavior, and not handling these extra args could lead to couch_log
application crashing and taking down the whole VM with it.
=> Do not crash couch_log application when gen_* servers send extra args

src/mango/src/mango_native_proc.erl
Previously returning null from mango native proc lead to case clause error in
couch_query_servers. Instead return a proper shape but with null results for
each reduction.
=> Avoid crashing if a mango query is reduced

src/chttpd/src/chttpd_sup.erl
The code was incorrect in a sense that it was using is_integer guard,
while `config:get` cannot return integer.
1. Update default.ini to set max_lifetime to 10000
2. Restart chttpd application
3. Try manually insert keys into lru_cache and query them. They all should be removed after 10 seconds
```
lists:foreach(fun(Idx) -> ets_lru:insert(chttpd_auth_cache_lru, Idx, [1,2,3]) end, lists:seq(1, 1000)).
lists:filter(fun(Idx) -> ets_lru:lookup(chttpd_auth_cache_lru, Idx) /= not_found end, lists:seq(1, 1000)).
```
4. Try negative value for the setting check logs to make sure it complains
5. Try putting "some_string" as value check logs to make sure it complains
N/A
=> Fix ets_lru configuration in chttpd application

rebar.config.script
This fixes a memory bug:
https://github.com/apache/couchdb-snappy/commit/2038ad13b1d6926468f25adea110028e3c0b4b0c
=> Update snappy dependency to CouchDB-1.0.2

dev/run
While we wait for #1639, this change will fix the trusty build failures on Jenkins.
They are failing because trusty has Python 2.6 (but the Docker image has python3 in the path as `/usr/local/bin/python` ahead of the 2.6 python):
```
Traceback (most recent call last):
File "dev/run", line 592, in <module>
main()
File "dev/run", line 80, in main
ctx = setup()
File "dev/run", line 94, in setup
setup_configs(ctx)
File "dev/run", line 65, in wrapper
res = func(*args, **kwargs)
File "dev/run", line 203, in setup_configs
write_config(ctx, node, env)
File "dev/run", line 239, in write_config
content = hack_default_ini(ctx, node, content)
File "dev/run", line 289, in hack_default_ini
flags=re.MULTILINE)
TypeError: sub() got an unexpected keyword argument 'flags'
```
=> Remove explicit python version for dev/run (for now)

test/javascript/run
A problem on CentOS 6, which is in our Jenkins test setup, stemming from #1622 again :(
=> Fix JS/Python test harness for Python 2.6

src/chttpd/src/chttpd_db.erl, src/chttpd/test/chttpd_purge_tests.erl
Under situation where mixed nodes exist in one cluster, i.e. some nodes are with clustered purge feature while some nodes are without clustered purge feature, the `accepted` result is returned instead of `ok` when purge request is sent. 
This PR is used to address `badmatch` error where "accepted" returned result is not considered. Otherwise, the following error may occur
```
req_err(3038544381) badmatch : {accepted,[{accepted,[{1,<<217,66,240,206,1,100,122,160,244,101,24,178,19,181,98,142>>}]}]}[<<"chttpd_db:db_req/2 L527">>,<<"chttpd:handle_req_after_auth/2 L320">>,<<"chttpd:process_request/1 L303">>,<<"chttpd:handle_request_int/1 L243">>,<<"mochiweb_http:headers/6 L124">>,<<"proc_lib:init_p_do_apply/3 L247">>]
```
make check skip_deps+=couch_epi apps=chttpd tests=purge_test_
``` …
```
=> Allow to return with accepted for mixed nodes in cluster

src/chttpd/src/chttpd_db.erl, src/couch/src/couch_db.erl, src/couch/src/couch_db_updater.erl, src/couch/test/couchdb_update_conflicts_tests.erl
This PR is mostly a refactoring and addresses the following issues:
- Attempt to create a local document with an invalid revision throwing `badarg` exception.
- The documents with `_local` prefix written into a wrong btree on a bulk operation with `new_edits` set to `false`.
- It is possible to create a document with an empty id on a bulk operation with `new_edits` set to  `false`
New tests are expected to pass.
For manual testing here is an expected change of behaviour:
Readable error on an invalid rev for a local doc creation
``` 
curl -X PUT http://127.0.0.1:15984/koi/_local/alice?rev=0-abcdf -d '{"name":"Alice"}'
{"error":"error","reason":"Invalid rev format"}
```
Correct creation of a local doc on a bulk update
```
$ curl -X POST http://127.0.0.1:15984/koi/_bulk_docs -d …
```
=> Fixes for _local doc update and _bulk_docs operations with new_edits false

src/mango/src/mango_cursor_view.erl, src/mango/test/01-index-crud-test.py, src/mango/test/mango.py
Under situation where the document is deleted while the mrview index for this document is not updated, the returned value from mrview is `{doc,null}`. There is no such consideration in Mango to cause case_clause error. This fix is to consider out-of-sync between documents in database and their index and not to cause 500 when the `_find` endpoint is called.
```
localhost:mytest jiangph$ curl -u foo:bar -X PUT http://localhost:15984/db01
{"ok":true}
localhost:mytest jiangph$ curl -u foo:bar -X POST -H "Content-Type: application/json"  http://localhost:15984/db01 -d @point2.json
{"ok":true,"id":"point2","rev":"1-d942f0ce01647aa0f46518b213b5628e"}
localhost:mytest jiangph$ more queryindex.json
{
"index": {
"fields": ["type"]
},
"name" : "type_json_index",
"type" : "json"
}
localhost:mytest …
```
=> Support out-of-sync between db and index in mango

CONTRIBUTING.md
The URL for Hoodie was displayed instead of being a hyperlink. Displaying the full link may have been intentional, but perhaps not. If so, please disregard this PR.
=> Fix link in contributing doc

src/couch_mrview/src/couch_mrview_compactor.erl
This is a minor consistency issue. Currently when a view compaction
starts it doesn't include the `total_changes` and `changes_done` fields
until the first task status update. This is easy to miss as every other
task type includes those fields from the initial task definition.
The obvious trivial fix is both obvious and trivial.
=> Fix initial view compaction task status

configure
This PR depends on https://github.com/apache/couchdb-rebar/pull/1.
Signed-off-by: Lee Jones <lee.jones@linaro.org>
=> Use CouchDB hosted Mainline Rebar (v2)

src/couch_replicator/src/couch_replicator.hrl, src/couch_replicator/src/couch_replicator_scheduler.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/test/couch_replicator_retain_stats_between_job_runs.erl
Previously stats counts between job runs were reset. So if a job was stopped
and restarted by the scheduler, its docs_written, docs_read, doc_write_failures,
etc., counts would go back to 0. For doc_write_failures this was especially bad
as it hid the fact that some documents were not replicated to the target
because either a VDU failed or one of the limits were hit.
This change preserves stats across job runs. Everytime active tasks is updated,
the stats object in rep record of each job in scheduler's ets table will be
updated asynchronously. On next job start the job will reinitialize from last
saved stats.
Relates somewhat to issue #1159
=> Retain replication stats between job runs

test/elixir/test/helper_test.exs, test/elixir/test/test_helper.exs
Fix bug in epoch millisecond calculation, and improve `retry_until` to work with code containing assertions.
`mix test --trace ./test/helper_test.exs`
=> Improve retry_until

src/couch/src/couch_db_epi.erl, src/couch/src/couch_flags.erl, src/couch/src/couch_flags_config.erl, src/couch/src/couch_util.erl, src/couch/test/couch_flags_tests.erl, src/couch_epi/src/couch_epi.erl, src/couch_epi/src/couch_epi_data_gen.erl
Once in a while we merge a highly experimental features. It is beneficial to be able to have the codepath for these features effectivelly disabled by default until the implementation is stabilized. 
This PR introduces an ability to add feature flag checks for experimental features.   
This feature is for developers only and wouldn't need documentation.
```
[feature_flags]
my_feature||* = false
my_feature||mytestdatabaseprefix* = true
```
Notes:
- The `*` is only allowed at the end of the path
- In order to distinguish between shards and clustered db the following convention is used.
- it is a shard if pattern starts with `/`
- It is also possible to enable multiple flags for the path using alternative syntax
- `mytestdatabaseprefix* = [my_featureA, my_featureB]`
```
case …
```
=> Feature flags

Makefile.win, make.cmd, src/mango/test/15-execution-stats-test.py, test/elixir/lib/couch.ex, test/elixir/mix.exs, test/elixir/mix.lock, test/elixir/run, test/elixir/run.cmd, test/elixir/test/replication_test.exs
`os:timestamp()` on Windows only has millisecond accuracy, leading to the failure of 2 mango tests. This closes #1732 by disabling the `execution_time_ms` check on Windows only, since these 2 tests seem to be completing in <1ms and failing the `> 0` check.
This also fixes the elixir suite by using `127.0.0.1` instead of `localhost`. It's ALWAYS DNS.
The bump to `mix.*` was recommended by @davisp in #1730. Closes #1730.
Trust me on this one - or you can build your own Windows instance if you want...
- _n/a_ Documentation reflects the changes;
=> Test suite fixes for Windows

rebar.config.script, src/chttpd/src/chttpd_misc.erl
When the ini config file is read only,  ini file shouldn't be updated when the endpoint of `_node/_local/_config/` is invoked. 
For example:
```
curl -X PUT localhost:15984/_node/_local/_config/admins/joan -d '"500"'
```
when you check the local.ini file, you shouldn't find out the `joan` key and hash value of `500`
and it also should not return this error like below:
```
{"error":"badmatch","reason":"{badrpc,{'EXIT',{{{badmatch,{error,eacces}},\n  
```
expected returned error should like this:
```
{"error":"bad_request","reason":"eacces"}
```
```
wenwl@wenwl_mbp:~/cloudant/couchdb$ chmod a-w ./dev/lib/node1/etc/local.ini
wenwl@wenwl_mbp:~/cloudant/couchdb$ curl -X PUT localhost:15984/_node/_local/_config/admins/joan1 -d '"500"' -u adm:pass
{"error":"bad_request","reason":"eacces"} …
```
=> Fix nasty 500 error on POST to /_config

src/chttpd/src/chttpd_db.erl, src/chttpd/test/chttpd_purge_tests.erl
Avoid `badmatch` when putting `_set_purge_infos_limit` and getting fabric timeout
```
module 'chttpd_purge_tests'
chttpd db tests
chttpd_purge_tests:87: test_empty_purge_request...[0.009 s] ok
chttpd_purge_tests:104: test_ok_purge_request...[0.285 s] ok
chttpd_purge_tests:141: test_accepted_purge_request...[0.123 s] ok
chttpd_purge_tests:173: test_partial_purge_request...[0.084 s] ok
chttpd_purge_tests:209: test_mixed_purge_request...[0.172 s] ok
chttpd_purge_tests:257: test_overmany_ids_or_revs_purge_request...[0.130 s] ok
chttpd_purge_tests:307: test_exceed_limits_on_purge_infos...[0.140 s] ok
chttpd_purge_tests:350: should_error_set_purged_docs_limit_to0...[0.004 s] ok
chttpd_purge_tests:358: …
```
=> Avoid badmatch when getting fabric timeout

Makefile
After #1602 we requite env variable `COUCHDB_QUERY_SERVER_JAVASCRIPT` to point to js query server. This patch adds the env var on Makefile's `eunit` target returning ability to run the isolated eunit tests without setting that var in each tests' setup.
Isolated tests with query server, e.g. `make eunit apps=couch_mrview suites=couch_mrview_all_docs_tests` should run locally without throwing "unknown query server" exceptions.
=> Set query server env variable in Makefile for isolated eunit tests

src/chttpd/test/chttpd_view_test.erl
Remove unnecessary setting `COUCHDB_QUERY_SERVER_JAVASCRIPT` on chttpd_view_test because this was set via https://github.com/cloudant/db/pull/577
`make check`
https://github.com/apache/couchdb/pull/1602
https://github.com/cloudant/db/pull/577
=> Remove unnecessary setting on chttpd_view_test

src/couch/src/couch_db.erl, src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_test_util.erl, src/couch_mrview/test/couch_mrview_design_docs_tests.erl, src/fabric/src/fabric.erl, src/fabric/src/fabric_design_doc_count.erl, src/fabric/src/fabric_rpc.erl, src/fabric/src/fabric_view_all_docs.erl, test/javascript/tests/design_docs_query.js
We've added a new URL end-point [`/{db}/_design_docs`](http://docs.couchdb.org/en/2.2.0/api/database/bulk-api.html#db-design-docs) reusing existing function for `_all_docs`. As a result the response for the new handler returns `total_rows` meta set to a total number of docs in a database, not just design docs as indicated in the documentation.
This fix adds a custom enumerator for calculating number of ddocs and a new fabric wiring to access it.
For isolated tests:
```bash
make eunit apps=couch_mrview suites=couch_mrview_design_docs_tests
```
and 
```bash
make javascript suites=design_docs_query
```
Closes #1603
=> Fix total_rows value for queries on `_design_docs` handler

src/couch/src/couch_db.erl, src/couch/test/couchdb_db_tests.erl, src/ddoc_cache/src/ddoc_cache_entry.erl, src/ddoc_cache/test/ddoc_cache_basic_test.erl, src/ddoc_cache/test/ddoc_cache_disabled_test.erl, src/ddoc_cache/test/ddoc_cache_entry_test.erl, src/ddoc_cache/test/ddoc_cache_eviction_test.erl, src/ddoc_cache/test/ddoc_cache_lru_test.erl, src/ddoc_cache/test/ddoc_cache_open_error_test.erl, src/ddoc_cache/test/ddoc_cache_open_test.erl, src/ddoc_cache/test/ddoc_cache_refresh_test.erl, src/ddoc_cache/test/ddoc_cache_remove_test.erl, src/ddoc_cache/test/ddoc_cache_tutil.erl
Handle db deletion in couch_db:load_validation_funs
Previously there were quite a few problems with load_validation_funs
in the case when clustered database is deleted.
- the calls to load_validation_funs were failing with `internal_server` error [1]
- the deleted database stayed opened because:
- the caller of the load_validation_funs (update_doc) stayed alive
- the main_pid of the deleted database wasn't killed either
- there was an infinite loop in ddoc_cache_entry trying to recover ddoc from deleted database
The solution is:
- do not call `recover` for deleted database
- close `main_pid`
- use `erlang:error` to crash the caller
[1] - The stack trace was:
```
{database_does_not_exist,[
{mem3_shards,load_shards_from_db,"bailey/meta",[
{file,"src/mem3_shards.erl"},{line,394}]}, …
```
=> handle db deletion in load validation funs

src/couch_epi/src/couch_epi.erl, src/couch_epi/src/couch_epi_plugin.erl
There are few problems with type specs in couch_epi:
- `module` was renamed into `static_module`
- https://github.com/apache/couchdb/commit/0fefc859eb9c18120064317da61a30adaeac5f92#diff-d9e3e3c91d4866fe966666619bda7991
- `callback_module` was added
- https://github.com/apache/couchdb/commit/cf65280466499d652cff1171a2039af49c5677e8#diff-d9e3e3c91d4866fe966666619bda7991
- data provider specification can include options
- https://github.com/apache/couchdb/blob/master/src/couch_epi/src/couch_epi_plugin.erl#L143
This PR fixes these issues.
```
make dialyze
```
=> Fix couch_epi typespec for data provider

rel/overlay/etc/default.ini, src/couch/src/couch_httpd_auth.erl, src/couch_replicator/src/couch_replicator_auth_session.erl
Implement replicator session refresh based on cookie max age
Force couch_replicator_auth_session plugin to refresh the session periodically.
Normally it is not needed as the session would be refreshed when requests start
failing with a 401 (authentication) or 403 (authorization) errors. In some
cases when anonymous writes are allowed to the database and a VDU function is
used to forbid writes based on the authenticated in username, requests with an
expired session cookie will not fail with a 401 and the session will not be
refreshed.
To fix the issue using these two approaches:
1. Use cookie's max-age expiry time to schedule a refresh. To ensure that time
is provided in the cookie, switch the the option to enable it by default. This
handles the issue for endpoints which are updated with …
=> Implement replicator forced session refresh

test/elixir/README.md, test/elixir/test/coffee_test.exs
I just ported `coffee.js` to the Elixir test suite.
Issue `make elixir`
None
=> test: port coffee.js to Elixir test suite

test/elixir/README.md, test/elixir/test/large_docs_text.exs
I just ported `large_docs.js` to the Elixir test suite.
Issue `make elixir` 😬 
None
=> test: port large_docs.js to Elixir test suite

src/couch/src/couch_proc_manager.erl
The configuration of query servers is done via environment variables.
Calling os:getenv every time we need a new query process is expensive.
Instead we extact all configured query servers from the environemt on
`couch_proc_manager` startup and cache them in ets table.
fixes #1772
1. make eunit
2. remsh into running dev cluster and check the following
- `ets:tab2list(couch_proc_manager_servers).` - returns 
- COFFEESCRIPT
- QUERY
- JAVASCRIPT
- update config to enable native query server `config:set("native_query_servers", "enable_erlang_query_server", "true", false).`
- make sure `ets:tab2list(couch_proc_manager_servers).` includes ERLANG
- issue https://github.com/apache/couchdb/issues/1772
- problem introduced in https://github.com/apache/couchdb/pull/1602
=> Cache query servers in ets table

rebar.config.script, rel/reltool.config, version.mk
This is the last step before starting the 2.3.0 release process.
Closes #1749
=> Bump fauxton, docs, version to 2.3.0

Makefile, Makefile.win
This is a simple change of Makefile for consistency sake. Since `dev/run` overrides etc configs on each run functionally it's the same as earlier `@rm` command.
`make elixir` should pass, apart from common races.
=> Use devclean on elixir target for consistency of Makefile

src/couch/src/couch_flags_config.erl, src/couch/test/couch_flags_config_tests.erl
Implementation of eunit tests in the same module with the code we are trying to test is not a good idea. The test suites in the module are conditionally compiled using `-ifdef(TEST).`. This means that depending on phase of the moon the tests can be skipped. They are certainly skipped when `eunit` is used in combination with `meck` library. This problem manifested itself in https://github.com/apache/couchdb/pull/1754 where the tests were originally introduced. The PR was merged because Travis was green and it had a `+1`. However close look at test logs (https://travis-ci.org/apache/couchdb/builds/458820868?utm_source=github_status&utm_medium=notification) on Travis reveal that the tests didn't run (search for couch_flags_config):
```
module 'couch_bt_engine_stream'
module …
```
=> Move tests to suite

src/couch/.gitignore
New rebar leaves behind a clang compile commands database file after compiling the ports. This is a simple update to include it into `.gitignore`
=> Ignore clang compile commands database file

src/mem3/src/mem3_rep.erl
This avoids needlessly making fabric:update_docs calls with emtpy doc lists.
=> Filter out empty missing_revs results in mem3_rep

Makefile, Makefile.win, test/elixir/.credo.exs, test/elixir/.formatter.exs, test/elixir/lib/couch.ex, test/elixir/mix.exs, test/elixir/mix.lock, test/elixir/test/all_docs_test.exs, test/elixir/test/basics_test.exs, test/elixir/test/coffee_test.exs, test/elixir/test/compact_test.exs, test/elixir/test/config_test.exs, test/elixir/test/conflicts_test.exs, test/elixir/test/lots_of_docs_test.exs, test/elixir/test/reduce_test.exs, test/elixir/test/replication_test.exs, test/elixir/test/rewrite_test.exs, test/elixir/test/security_validation_test.exs
This PR adds Credo as the static code analysis tool of choice for the Elixir test suite.
Just issue `make elixir-credo` first, then `make elixir`
#1756
=> Add Credo to Elixir test suite

src/couch/src/couch_db.erl, src/couch/src/couch_util.erl, src/couch_mrview/src/couch_mrview_index.erl
This fixes a silly mistake of using a clustered _all_docs lookup to get a single design document.
Code is covered by `make check`
Clustered purge added the bad code.
=> Fix get minimum purge seq

src/chttpd/test/chttpd_security_tests.erl, src/couch/src/couch_db.erl
This PR will fix function_clause error on invalid DB security objects.
for example when the request body of PUT db/_security endpoint is not a correct json format, if you check the log file you will find the function_clause error.
```
[error] 2018-06-13T16:50:50.479454Z node1@127.0.0.1 <0.3642.0> 3108587a16 rpc couch_db:set_security/2 function_clause [{couch_db,validate_names_and_roles,[[<<"role_a">>]],[{file,"src/couch_db.erl"},{line,594}]},{couch_db,validate_security_object,1,[{file,"src/couch_db.erl"},{line,590}]},{couch_db,set_security,2,[{file,"src/couch_db.erl"},{line,574}]},{fabric_rpc,with_db,3,[{file,"src/fabric_rpc.erl"},{line,289}]},{rexi_server,init_p,3,[{file,"src/rexi_server.erl"},{line,139}]}] …
```
=> Fix function_clause exception on invalid DB security objects

test/elixir/lib/couch/db_test.ex, test/elixir/test/support/couch_test_case.ex
`moduledoc` attribute is now mandatory according to credo policy
`make elixir`
Fix for PR #1801
=> Fix running elixir test suite

test/elixir/README.md, test/elixir/lib/couch.ex, test/elixir/lib/couch/db_test.ex, test/elixir/test/delayed_commits_test.exs
This PR adds a new helper function to `test_helper` allowing to restart a node or the whole cluster and ports `delayed_commits` test.
`make elixir` should pass, output log should include:
```
...
DelayedCommitsTest
* test delayed commit (9208.3ms)
...
```
Closes #1704
=> Port delayed_commits test to Elixir

dev/run, rel/haproxy.cfg
Add support for dev cluster with more than 3 nodes. Even though we have `-n <N>` option for `dev/run` it has a couple of limitations.
- The number of nodes cannot be more than 5. Otherwise we try to allocate tcp ports greater than  65535
- The number of nodes is assumed to be 3 in couple of places
- [in setup application](https://github.com/apache/couchdb/blob/master/src/setup/src/setup.erl#L289:L294)
- [in haproxy config](https://github.com/apache/couchdb/blob/master/rel/haproxy.cfg)
This PR removes the limitation and adds `--auto-ports` which we are planing to use to run Elixir test suite. So we can instantiate a second instance of the cluster specifically for test suite.
1. clean development environment `rm -rf dev/lib`
2. run cluster as follows `dev/run --admin=adm:pass --auto-ports` …
=> Support for more than 3 nodes dev cluster

dev/run
The problem was introduced in https://github.com/apache/couchdb/commit/94eff0d8ddcdb552389b4273f771aba211e4e57c during rebase of https://github.com/apache/couchdb/pull/1774
The location of generated config file is `os.path.join(ctx["devdir"], "lib", "haproxy.cfg")` (see https://github.com/apache/couchdb/commit/94eff0d8ddcdb552389b4273f771aba211e4e57c#diff-d86563699bde00df2cce2613ecbed531R281). We attempt to start haproxy with config located at `os.path.join(ctx["devdir"], "rel", "haproxy.cfg")` (see https://github.com/apache/couchdb/commit/94eff0d8ddcdb552389b4273f771aba211e4e57c#diff-d86563699bde00df2cce2613ecbed531R384). Which is obviously incorrect since we suppose to use generated config file.
Run `dev/run --with-haproxy` and make sure haproxy process is running …
=> Fix haproxy config file location

Makefile, Makefile.win, test/elixir/run, test/elixir/run.cmd
Introduction of an Elixir based integration tests is a great thing. This PR adds an ability to run tests individually from a Makefile. Similar to the way we do it with eunit. 
Individual tests can be specified as:
- `make elixir tests=test/basics_test.exs`
- `make elixir tests=test/basics_test.exs,test/config_test.exs`
- `make elixir tests=test/basics_test.exs:17`
```
make elixir tests=test/basics_test.exs
make elixir tests=test/basics_test.exs,test/config_test.exs
make elixir tests=test/basics_test.exs:17
```
```
make elixir tests=test\basics_test.exs
make elixir tests=test\basics_test.exs,test\config_test.exs
make elixir tests=test\basics_test.exs:17
```
N/A
=> Support specifying individual Elixir tests to run

test/elixir/lib/couch/db_test.ex, test/javascript/test_setup.js
Currently, when a JS or Elixir test restarts a node, it waits 15 or 10 seconds respectively for it to come back.
CI systems have shown this is not enough. Most recent failure is here:
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/master/448/pipeline
but it's been happening semi-regularly since we reworked the restart code.
This PR bumps the timeout to 30s in both places.
=> Increase timeout on restart in JS/elixir tests to 30s

test/elixir/.credo.exs
Suppress credo TODO suggests.
Credo output in `make elixir` looks like:
```shell
Analysis took 3.4 seconds (0.04s to load, 3.4s running checks)
135 mods/funs, found no issues.
```
Discussed in PR #1812.
=> Suppress credo TODO suggests

.travis.yml, rebar.config.script, src/couch/rebar.config.script, src/couch/src/couch_rand.erl, src/couch/src/couch_util.erl
The informal proposal on the couchdb-dev mailing list to change the minimum supported Erlang version to OTP 19 seems to have passed unanimously.
This removes references to earlier versions from travis and rebar files. It also removes platform defines and ifdefs necessary to compile using earlier versions.
The main benefits are speeding up Travis by not having to run tests against two platforms, and simplifying some code, making it easier to reason about and maintain.
`make eunit`
=> Change minimum supported Erlang version to OTP 19

src/couch_pse_tests/src/cpse_test_purge_seqs.erl, src/couch_pse_tests/src/cpse_util.erl
Re-introduce cpse_test_purge_seqs after fixing issue on `cpse_test_purge_seqs:cpse_increment_purge_seq_on_partial_purge/1` with undef issue.
```
cpse_gather: make_test_fun (cpse_increment_purge_seq_on_partial_purge)...*failed*
in function cpse_util:save_doc/3
called as save_doc(<<"db-475a26f2204d6b20d19fc5334d8f4adb">>,{[{'_id',foo},{vsn,2}]},[replicated_changes])
in call from cpse_test_purge_seqs:cpse_increment_purge_seq_on_partial_purge/1 (src/cpse_test_purge_seqs.erl, line 105)
**error:undef
output:<<"">>
```
```
cpse_test_purge_seqs
cpse_gather: make_test_fun (cpse_increment_purge_seq_on_complete_purge)...[0.100 s] ok
cpse_gather: make_test_fun (cpse_increment_purge_multiple_times)...[0.074 s] ok
cpse_gather: make_test_fun (cpse_increment_purge_seq_on_partial_purge)...[0.080 s] ok …
```
=> Re-Introduce cpse_test_purge_seqs

src/couch/include/couch_db.hrl, src/couch/src/couch_db.erl, src/couch/src/couch_db_plugin.erl, src/couch/src/couch_server.erl, src/couch/src/couch_users_db.erl, src/couch/test/couch_db_plugin_tests.erl, src/couch_replicator/src/couch_replicator_docs.erl, src/fabric/src/fabric_doc_update.erl
Pass update type to before_doc_update/3 to allow additional check. The possible update type includes  
- interactive_edit
- replicated_changes
```
make check skip_deps+=couch_epi apps=couch tests=callback_test_
```
=> Update before_doc_update/2 to before_doc_update/3

src/couch_replicator/src/couch_replicator_scheduler_job.erl
Previously `end_time` was generated converting the start_time to universal,
then passing that to `httpd_util:rfc1123_date/1`. However, `rfc1123_date/1`
also transates its argument from local to UTC time, that is it accepts input to
be in local time format.
Fixes #1841
=> Fix end_time field in /_replicate response

src/fabric/src/fabric_doc_open.erl, src/fabric/src/fabric_doc_open_revs.erl
This enables backwards compatbility with nodes still running the old
version of fabric_rpc when a cluster is upgraded to master. This has no
effect once all nodes are upgraded to the latest version.
=> Fix read repair in a mixed cluster environment

src/fabric/src/fabric_doc_open_revs.erl
There was a subtle bug when opening specific revisions in
fabric_doc_open_revs due to a race condition between updates being
applied across a cluster.
The underlying cause here was due to the stemming after a document had
been updated more than revs_limit number of times along with concurrent
reads to a node that had not yet made the update. To illustrate lets
consider a document A which has a revision history from `{N, RevN}` to
`{N+1000, RevN+1000}` (assuming revs_limit is the default 1000). If we
consider a single node perspective when an update comes in we added the
new revision and stem the oldest revision. The docs the revisions on the
node would be `{N+1, RevN+1}` to `{N+1001, RevN+1001}`.
The bug exists when we attempt to open revisions on a different node
that has yet to apply …
=> Fix fabric_open_doc_revs

src/chttpd/test/chttpd_purge_tests.erl, src/fabric/src/fabric_doc_purge.erl
This PR is aimed to solve the following error when sending one purge request with more than 100 docid.
```
<<"{\"error\":\"unknown_error\",\"reason\":\"function_clause\",\"ref\":1363930458}\n">>
```
```
make check skip_deps+=couch_epi apps=chttpd tests=purge_test_
chttpd db tests
chttpd_purge_tests:88: test_empty_purge_request...[0.019 s] ok
chttpd_purge_tests:105: test_ok_purge_request...[0.232 s] ok
chttpd_purge_tests:142: test_ok_purge_request_with_101_docid...[3.268 s] ok
chttpd_purge_tests:162: test_accepted_purge_request...[0.243 s] ok
chttpd_purge_tests:194: test_partial_purge_request...[0.087 s] ok
chttpd_purge_tests:230: test_mixed_purge_request...[0.188 s] ok
chttpd_purge_tests:278: test_overmany_ids_or_revs_purge_request...[0.124 s] ok …
```
=> Support one purge request with more than 100 docid

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/couch/src/couch_db_updater.erl, test/elixir/test/partition_size_limit_test.exs
This implements configurable size limits for partitions (which are not yet merged). This is a separate PR due to the complexity involved.
The point of enforcing limits is so that users don't accidentally footgun themselves by trying to store an entire db using a single partition key. It can be disabled by setting the limit to 0.
`make check`
`make elixir`
#1789
=> Implement partition size limits

rel/overlay/etc/default.ini, src/fabric/src/fabric_util.erl, src/fabric/src/fabric_view_all_docs.erl, src/fabric/src/fabric_view_map.erl, src/fabric/src/fabric_view_reduce.erl, test/elixir/test/partition_all_docs_test.exs
This makes the global timeout for a map/reduce and all_docs request
configurable via the config. It separates the config into global queries
and partition queries so that it is possible to make the global timeout
is for partitioned queries
Add the `global_partition_view_timeout` to the `[fabric]` config. You can then make queries and see if they timeout based on the value set.
=> Add Global timeout for map/reduce queries

test/elixir/lib/couch.ex, test/elixir/test/basics_test.exs
This is a new test for a doc read with etag (`If-None-Match` header) to confirm that it works properly.
Isolated:
`make elixir tests=test/basics_test.exs:88`
Complete:
`make elixir`
Inspired by #1863
=> Add a test for a doc read with etag

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_db.erl, src/couch/test/couch_flags_tests.erl
Add partition feature flag based for #1789
Create something like this in `local.ini`:
```
[feature_flags]
partitions||* = false
partitions||allowed* = true
```
Then:
`curl -X PUT http://localhost:5984/not-allowed?partitioned=true` should throw an error
`curl -X PUT http://localhost:5984/allowed-partition?partitioned=true` should be created
#1789
=> Partition feature flag

.travis.yml, rebar.config.script
Some of the changes to `.travis.yml` are temporary - once the test run looks correct, a screenshot of the output will be added and the known-bad versions will be removed.
In support of #1870 
Closes #1857
=> Blacklist known bad Erlang releases, fixes #1857

rel/overlay/etc/default.ini, src/couch_mrview/include/couch_mrview.hrl, src/couch_mrview/src/couch_mrview_util.erl, test/elixir/test/partition_all_docs_test.exs, test/elixir/test/partition_view_test.exs
This allows us to set a maximun allowed number of documents
to be returned for a global or a partitioned query.
Set a view limit in the default.ini. 
* A query with a limit larger than the max will error
* A query with the limit value below the max will run the query. A
* A query with no limit will use the max limit set.
=> Make view query limits configurable

src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_show.erl, src/chttpd/src/chttpd_stats.erl, src/chttpd/src/chttpd_view.erl
This adds an advanced API for users that want to write some Erlang to be able to collect request level metrics for reporting.
`make check`
=> Add chttpd stats

test/elixir/test/partition_design_docs_test.exs
Fix the url in the test to an actual map/reduce query url. CouchDB then correctly returns a 404.
Run test
=> fix test url to fix test

src/couch/src/couch_server.erl
Rename the `partitions` feature to `partitioned` feature to be consistent with how the flag is used everywhere else.
Using curl
```
curl http://adm:pass@localhost:15984
{"couchdb":"Welcome","version":"2.3.0-17f05b758-dirty","git_sha":"17f05b758","uuid":"fake_uuid_for_dev","features":["partitioned","pluggable-storage-engines","scheduler"],"vendor":{"name":"The Apache Software Foundation"}}
```
Should say partitioned
=> rename partitions feature to partitioned feature

src/chttpd/src/chttpd_auth_request.erl, src/chttpd/test/chttpd_security_tests.erl
This restrict  `_purge` and `_purged_infos_limit` to server admin in terms of the security level required to run them.
Background: there are more discussion on https://github.com/apache/couchdb/issues/1799. However, it would be safer way to allow server admin only to access  `_purge` and `_purged_infos_limit` endpoint for now. We can re-visit this if there is more change requirement.
make check skip_deps+=couch_epi apps=chttpd tests=all_test_
```
chttpd security tests
chttpd_security_tests:147: should_allow_admin_db_compaction...[0.004 s] ok
chttpd_security_tests:163: should_allow_valid_password_to_create_user...ok
chttpd_security_tests:173: should_disallow_invalid_password_to_create_user...ok …
```
=> restrict _purge to server admin

test/elixir/README.md, test/elixir/lib/couch.ex
Make it possible to override elixir couchdb settings via environmental variables
Spin up a local CouchDB cluster with different settings to what Elixir requires by default.
Run `USER=myusername PASS=password COUCH_URL=http://my-couchdb.com mix test `
and make sure the tests will run.
=> Make it possible to override elixir couchdb settings via environmental variables

test/elixir/mix.exs, test/elixir/mix.lock, test/elixir/test/test_helper.exs
Adds the junit formatter for the elixir tests so that Jenkins can read the test output nicely
run `mix test` and then look under `_build/test/lib/foo/test-junit-report.xml` for the xml output
=> Add junit formatter to the elixir tests

src/couch/src/couch_doc.erl, src/couch/test/couch_doc_json_tests.erl
If a doc's revision provided with `_bulk_docs` matches the expected length it assumed to be a parsable hexadecimal. When this is not the case `couch_doc:couch_doc:from_json_obj_validate/2` function crashes with `badarg`.
The fix catches the exception and re-throws it as a `doc_validation` exception to raise "400 Bad Request" error.
`make eunit apps=couch suites=couch_doc_json_tests` or the manual stps from case #1895 
Closes #1895
=> Fix _bulk_docs crash when provided revision can't be parsed

src/couch/src/couch_doc.erl, src/couch/test/couch_db_doc_tests.erl
A companion of #1897, a missed clause of using `parse_revid/1` outside of `try` block causing `unknown_error` crash on an individual doc update with invalid revision.
` make eunit apps=couch suites=couch_db_doc_tests`
Fixes #1895
=> Fix `badarg` crash on an invalid revision for individual doc update

src/setup/src/setup.erl
Sync admin passwords at cluster setup finish
I tested by changing [this line](https://github.com/apache/couchdb/blob/master/dev/run#L425) to remove the `hashify` function like so:
```python
return contents + "\n%s = %s" % (user, pswd)
```
and then started couchdb normally: `dev/run -a adm:pass"`.
In a remsh I confirmed that all admin passwords are hashed the same after setup:
```erlang
(node1@127.0.0.1)1> rpc:multicall(config, get, ["admins"]).
{[[{"adm",
"-pbkdf2-454cf868445b52a1d7a527c20c1622925c8fab3b,561a3a73c5ae6276a2cb0fc47434975d,10"}],
[{"adm",
"-pbkdf2-454cf868445b52a1d7a527c20c1622925c8fab3b,561a3a73c5ae6276a2cb0fc47434975d,10"}],
[{"adm",
"-pbkdf2-454cf868445b52a1d7a527c20c1622925c8fab3b,561a3a73c5ae6276a2cb0fc47434975d,10"}]],
[]}
```
=> Sync admin passwords at cluster setup finish

src/couch/src/couch_debug.erl, src/couch/src/test_util.erl, src/couch/test/couch_index_tests.erl, src/couch_index/src/couch_index_compactor.erl, src/couch_index/src/couch_index_updater.erl, src/couch_mrview/src/couch_mrview_updater.erl
In production we noticed that `io_priority` is not set for view update and compaction. This PR adds appropriate `io_priority` to the processes involved.
```
make eunit apps=couch tests=couch_index_ioq_priority_test_
```
N/A
=> Set io_priority for couch_index pids

src/couch/src/couch_bt_engine.erl, src/couch/src/couch_db_split.erl, src/couch/test/couch_db_split_tests.erl, src/couch/test/couch_server_tests.erl, src/couch_pse_tests/src/cpse_test_copy_purge_infos.erl, src/couch_pse_tests/src/cpse_util.erl
These are tests for the things changed with added shard splitting in couch app. New test suite added to `couch_pse_tests`
Run `make eunit apps=couch suites=couch_bt_engine_tests` and watch out for `cpse_test_copy_purge_infos` section (can't run the suite isolated)
`make eunit apps=couch suites=couch_server_tests tests=get_engine_path_test_`
`make eunit apps=couch suites=couch_db_split_tests`
Goes into #1921
=> Shard split couch tests

Jenkinsfile, test/elixir/lib/couch/db_test.ex, test/elixir/test/all_docs_test.exs, test/elixir/test/bulk_docs_test.exs, test/elixir/test/coffee_test.exs, test/elixir/test/compact_test.exs, test/elixir/test/lots_of_docs_test.exs, test/elixir/test/partition_ddoc_test.exs, test/elixir/test/partition_size_test.exs, test/elixir/test/partition_view_update_test.exs, test/elixir/test/replication_test.exs, test/elixir/test/security_validation_test.exs, test/elixir/test/test_helper.exs, test/elixir/test/view_collation_test.exs
Improve the reliability of Elixir tests on Jenkins.
Add retry_until to some flaky tests. Also add `:skip_on_jenkins` tag
for tests that won't pass with retry_until but pass on Travis.
All builds should pass on Jenkins. See
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-fix-elixir-take-3/3/pipeline/
=> Jenkins fix elixir take 3

src/chttpd/src/chttpd_db.erl, test/elixir/test/partition_mango_test.exs
When sending an incorrect partition query e.g:
/parition/_find, send a 400 with the message:
Partition must not start with an underscore
This makes it consistent with all the other partition requests
Tests should pass and correct message should be returned for `_explain` and `_find`
=> Send correct 400 for missing partition with _find

rebar.config.script
Update folsom to stop using deprecated erlang APIs
```
make eunit
```
- https://github.com/apache/couchdb-folsom/pull/1
=> Update folsom to support newer erlang

rebar.config.script
Upgrade Latest couchdb-ken to use version 1.0.3
=> upgrade ken to 1.0.3

Makefile
Make sure we fail `make eunit` when an individual Erlang app's eunit suite fails.
Run `make eunit`.
=> Fail make eunit upon eunit app suite failure

src/mem3/test/mem3_reshard_changes_feed_test.erl
Tests for changes feed during/after shard split.
Open issues:
- LastSeq inconsistent in "normal" feed right after split when feed pulled with old seq vs new seq
- Continuous feed stops (but don't quit) after shard split 
`make eunit apps=mem3 suites=mem3_reshard_changes_feed_test`
=> Add tests for shard's split changes feed

src/chttpd/test/chttpd_socket_buffer_size_test.erl
Previously this test used to fail on Windows, possibly to due to a full restart
of the chttp and mochiweb applications. It turns out chttpd monitors config
changes and restarts the listner if there any change which affect the listening
socket. One issue with this approach is that restart intensity is limited to 3
times in 10 seconds. To avoid this usue, some redundant tests were removed. The
three tests which are left should cover the same functionality as before,
namely:
1) In the default case, a large enough (7KB) url and header should be parsed.
2) Manually setting `buffer` works and will reduce the maximum header line
length and then the server should return a 400 error.
3) Setting `recbuf` also sets the user land `buffer` value as well with the
same effect as 2).
=> Improve chttpd_socket_buffer_size_test

src/chttpd/src/chttpd.erl, test/javascript/tests/etags_head.js
Some load balancer configurations (HAproxy with compression enabled is
the motivating example) will add W/ to our response ETags if they
modify the response before sending it to the client.
as per rfc7232 section 3.2;
"A recipient MUST use the weak comparison function when comparing
entity-tags for If-None-Match (Section 2.3.2), since weak entity-tags
can be used for cache validation even if there have been changes to
the representation data."
This change improves our ETag checking toward RFC compliance.
1)
create a document
2)
fetch it like;
curl 'foo:bar@localhost:15984/db1/doc1' -i -H'If-None-Match:"1-967a00dff5e02add41819138abb3284d"'
and verify a 304 response
3)
fetch it like;
curl 'foo:bar@localhost:15984/db1/doc1' -i -H'If-None-Match:W/"1-967a00dff5e02add41819138abb3284d"'
and …
=> Ignore weak ETag part

src/mango/src/mango_error.erl, src/mango/src/mango_idx.erl, test/elixir/test/partition_mango_test.exs
The mango sort error can be a bit confusing with using a partitioned
database this gives a little more detail on why mango could not find
a specific index when a sort is used.
Elixir and python mango tests should pass. Create a partitioned database, have a selector that has a sort in it:
```
selector = %{
selector: %{
some: "field"
},
sort: ["some"],
limit: 50
}
```
You should get back different errors depending on a normal database, partitioned database with a partitioned query or a global query on a partitioned database.
=> Added more info for a mango sort error

test/elixir/README.md, test/elixir/test/invalid_docids_test.exs
I just ported the `invalid_docids.js` test suite to Elixir.
Just issue `make elixir`.
None
=> test: port invalid_docids to Elixir test suite

rebar.config.script
Update ioq to version 2.1.1. The update includes a fix for a test case.
```
make eunit apps=ioq
```
- https://github.com/apache/couchdb-ioq/pull/12
=> Update ioq to 2.1.1

test/elixir/test/partition_all_docs_test.exs, test/elixir/test/partition_ddoc_test.exs
• Disable self-admitted flaky "partition _all_docs with timeout" test
• Double timeout for "GET /dbname/_design_docs" test
```
make elixir
```
=> Improve elixir test stability

Makefile
We skip mochiweb, snappy and others already.
=> Skip running PropEr's own unit tests

src/couch/src/couch_bt_engine_compactor.erl, src/couch/src/couch_db.erl
We define a database's external size as:
> Number of bytes that would be required to represent the contents outside of the database (for capacity and backup planning)
Given that we are using JSON as a data serialization format on REST API I assume that `external` should represent a size of uncompressed JSON serialized data.
However we are using `?term_size` for calculating doc's sizes and that gives this definition of `external` a noticeable overhead.
Here is a demo:
```bash
$ cat movies.json | jq .docs[2000]
{
"title": "The Love Light",
"year": 1921,
"cast": [
"Mary Pickford",
"Raymond Bloomer"
],
"genres": [
"Drama"
]
}
$ stat -f%z movies.json 
3386172 
$ curl -X PUT http://127.0.0.1:15984/test -G -d n=1 q=1
{"ok":true}
$ curl -X POST http://127.0.0.1:15984/test/_bulk_docs --data …
```
=> More precise calculation of external docs' size

test/elixir/README.md, test/elixir/test/copy_doc_test.exs
This PR ports copy_doc JavaScript test suite into elixir. 
```
make elixir tests=test/copy_doc_test.exs
```
=> Port javascript copy doc tests into elixir test suite

test/elixir/test/reshard_helpers.exs
Previously the first cluster node was picked. However, when running a test with
a degraded cluster and that node is down the test would fail.
=> In the resharding API test pick the first live node

src/mem3/src/mem3_rpc.erl
When upgrading, the new mem3_rpc:load_checkpoint with a filter hash arg won't
be available on older nodes.
Filter hashes are not currently used anyway, so to avoid crashes on mixed
cluster call the older version without the filter hash part when the filter has
the default <<>> value.
=> Fix upgrade clause for mem3_rpc:load_checkpoint/4,5

rel/overlay/etc/default.ini, src/couch_mrview/src/couch_mrview_index.erl
This decision is an old one, I think, and took the view that an error
from read_header meant something fatally wrong with this index
file. These days, it's far more likely to be something else, a process
crash at the wrong moment, and therefore wiping the index out is an
overreaction.
=> Don't reset_index if read_header fails

src/chttpd/src/chttpd_misc.erl
Adds a new trivial endpoint, `GET /_node/_local`, that returns a JSON object that includes the (Erlang) name of the current node.
1. `dev/run -n 1`
1. `curl http://localhost:15984/_node/_local`
Result should be `{"name":"node1@127.0.0.1"}`.
Closes #2005 
Documentation PR to follow this landing.
=> Expose node name via /_node/_local, closes #2005

src/mem3/src/mem3.erl, src/mem3/src/mem3_rep.erl, src/mem3/src/mem3_sync.erl
Previously, if a database was deleted and re-created while the internal
replication request was pending, the job would have been retried continuously.
mem3:targets_map/2 function would return an empty targets map and mem3_rep:go
would raise a function clause exception if the database as present but it was
an older "incarnation" of it (with shards living on different target nodes).
Because it was an exception and not an {error, ...} result, the process would
exit with an error. Subsequently, mem3_sync would try to handle process exit
and check of the database was deleted, but it also didn't account for the case
when the database was created, so it would resubmit the into queue again.
To fix it, we introduce a function to check if the database shard is part of
the current database shard …
=> Handle database re-creation edge case in internal replicator

src/rexi/src/rexi.erl
In a future release, once all nodes know how to handle kill_all message will
re-enable it.
In low traffic clusters this might not be an issue, as the extra workers would
time out and exit eventually, but in busy clusters this could cause
couch_server and other message backups as while the upgrade is happening
workers would not be terminate quickly enough.
=> Make rexi kill all messages configurable

Jenkinsfile
Because JENKINS-46277 and JENKINS-47106 got fixed, the Jenkinsfile can
be made much simpler and more readable since we are able to use docker
agents directly now.
Other changes:
* We now have an ARM64 build ready to go.
* It's currently failing some couch_btree tests with timeouts.
I've seen these failures on x86_64, though.
* If any one of the builds fails, Jenkins now kills all the rest.
This is useful because, in Jenkins, you can currently only
restart an entire pipeline stage, not just a single entry in the
pipeline. So there's no point in not killing the build fast, for
now. You can see which build actually failed by clicking through each
parallel stage and looking for a failed build step.
* We're trying to save space on the drives:
* We now only keep the last 10 builds and their …
=> Jenkins: Add ARM64, drop trusty, improve Jenkinsfile

src/couch/src/couch_db.erl
Originally we posited that duplicate UUIDs could never be created.
However due to operations interventions its possible to unintentionally
copy UUIDs in ways that violate this assumption. Instead of crashing the
process we just reset the seq to zero and log a warning as was done in
the other instances when we have mismatches in the epoch history.
`make eunit apps=couch suites=couch_db`
=> Fix epoch mismatch errors

rebar.config.script
Update ioq to 2.1.2 to fix flaky test when on powerful machines the latency in ioq is so small that we call log10 with 0
This update also drags additional changes. The full list of commits is:
- [5ff5921](https://github.com/apache/couchdb-ioq/commit/5ff5921) Merge pull request #15 from apache/ioq_update_hist
- [b1ce76d](https://github.com/apache/couchdb-ioq/commit/b1ce76d) Log from 0 is undefined
- [8ada5fa](https://github.com/apache/couchdb-ioq/commit/8ada5fa) Merge pull request #13 from apache/allow-for-dynamic-ioq-classes
- [c0ce268](https://github.com/apache/couchdb-ioq/commit/c0ce268) Add dynamic IOQ class documentation
- [d6e7a78](https://github.com/apache/couchdb-ioq/commit/d6e7a78) Allow dynamic classes in is_valid_class
- …
=> Update ioq to 2.1.2

rel/overlay/etc/default.ini
The code has "infinity" as the default value and not 0
https://github.com/apache/couchdb/blob/master/src/couch_replicator/src/couch_replicator_changes_reader.erl#L124
Then also add missing purge settings. 
http://docs.couchdb.org/en/latest/cluster/purging.html#config-settings
(Except `allowed_purge_seq_lag` which is not found in the code and should probably be removed from docs)
=> Add missing settings to default.ini file

src/couch/test/couchdb_access_tests.erl
Adds some basic Erlang tests for @janl’s access branch, most of which currently fail because things aren’t implemented yet.
`make eunit apps=couch tests=access_test`
https://github.com/apache/couchdb-documentation/pull/424
=> test(access): add some basic tests for access

src/couch/test/couch_btree_tests.erl
These two tests are reliably timing out on ARM hardware in Jenkins. They do a lot of individual btree operations so this is not entirely surprising. Appropriate course of action here is to raise the timeout.
This branch should get built automatically by Jenkins so we can confirm that it fixes the build there.
I've confirmed that the timeout setting works correctly locally (e.g. by lowering it to 0.1 and watching those tests time out).
=> Increase timeouts on two slow btree tests

Makefile
Whole app is retried 2 extra times if it fails.
Added to *nix Makefile only for now. May not be needed for Windows as this is
for CI flakiness mostly.
This is a test PR to see how well this works (or doesn't work).
=> Retry EUnit tests on failure

src/couch_pse_tests/src/cpse_test_purge_replication.erl, src/couch_replicator/src/couch_replicator.erl, src/couch_replicator/src/couch_replicator_api_wrap.erl, src/couch_replicator/src/couch_replicator_doc_processor.erl, src/couch_replicator/src/couch_replicator_doc_processor_worker.erl, src/couch_replicator/src/couch_replicator_docs.erl, src/couch_replicator/src/couch_replicator_filters.erl, src/couch_replicator/src/couch_replicator_ids.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_utils.erl, src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_attachments_too_large.erl, src/couch_replicator/test/eunit/couch_replicator_compact_tests.erl, src/couch_replicator/test/eunit/couch_replicator_filtered_tests.erl, src/couch_replicator/test/eunit/couch_replicator_id_too_long_tests.erl, src/couch_replicator/test/eunit/couch_replicator_large_atts_tests.erl, src/couch_replicator/test/eunit/couch_replicator_many_leaves_tests.erl, src/couch_replicator/test/eunit/couch_replicator_missing_stubs_tests.erl, src/couch_replicator/test/eunit/couch_replicator_selector_tests.erl, src/couch_replicator/test/eunit/couch_replicator_small_max_request_size_target.erl, src/couch_replicator/test/eunit/couch_replicator_use_checkpoints_tests.erl, test/elixir/test/replication_test.exs
`local` replication endpoints do something completely unexpected from a user's
point of view -- they replicate to and from node local databases on a random
node. The only way this worked correctly was if someone used the backend port
(:5986) with a single node database. However, that port is getting closed for 3.x
release as well, so it makes even less sense to keep this functionality around.
For more discussion and voting results see ML list:
https://lists.apache.org/thread.html/ddcd9db93cee363db7da571f5cbc7f2bd24b881a34e1ef734d6a0a1c@%3Cdev.couchdb.apache.org%3E
The `_replicate` HTTP "hack" was left as is, since it does work more or less, however it is inconsistent with what `_replicator` docs do so we should probably mark it as deprecated and remove it in 4.x
`make eunit`
`make elixir` …
=> Remove local replication endpoints in CouchDB 3.x

Makefile
Bash has `let` but other shells might not have it.
=> Fix bash-ism in EUnit retry logic

src/couch_pse_tests/src/cpse_test_purge_replication.erl
It doesn't work on Jenkins but worked locally.
Noticed that we started chttpd even though the clustered port was never used.
Add a wait function in `db_url/1` to make sure to wait until the db is
available via the HTTP interface before continuing.
=> Fix cpse_test_purge_replication eunit test

Jenkinsfile, Makefile, mix.exs, rebar.config.script
This is a non-trivial refactor of the Jenkins setup:
* Builds are moved back into the workspace. Parallel builds run in unique sub-folders which seems to avoid the clashes we had observed in the past.
* The large build_script is split out into smaller parts as sequential stages. Cleanup operations are deferred to `post` actions to enable retrieval of the test results.
* Test results are captured and saved in the Jenkins UI.
* Various fixes to platform labels and configuration that should get the nightly builds running again.
=> Refactor Jenkins setup to enable test result capture

rel/overlay/etc/default.ini, src/couch_jobs/src/couch_jobs_fdb.erl, src/fabric/src/fabric2_dir_prefix_tests.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_server.erl, src/fabric/src/fabric2_txids.erl
Specifying a custom prefix allows having multiple CouchDB instances on a single
FDB cluster. This can be used for one form of multi-tenancy. It can also be
used for integration testing by creating a temporary prefix then deleting all
data in that directory when the test has finished.
```make eunit apps=fabric```
=> Configurable FDB directory prefixes for CouchDB instances

src/dreyfus/src/dreyfus_fabric_cleanup.erl, src/dreyfus/src/dreyfus_util.erl
```
(dbcore@db6.ibm-cluster1.cloudant.net)1> dreyfus_fabric_cleanup:go(<<"db1">>).
** exception error: no function clause matching
lists:foldl(#Fun<dreyfus_fabric_cleanup.2.102674665>,[],[]) (lists.erl, line 1262)
in function  dreyfus_fabric_cleanup:go/1 (src/dreyfus_fabric_cleanup.erl, line 28)
```
```
(node1@127.0.0.1)1> dreyfus_fabric_cleanup:go(<<"db1">>).
ok
```
=> fixup for dreyfus_fabric_cleanup:go/1

src/couch_views/src/couch_views_indexer.erl
This fixes an issue where we get a new javascript query server for every 100 docs. We only need 1 server while the index is building.
=> only fetch 1 query server for indexing

src/couch_epi/src/couch_epi_sup.erl, src/couch_epi/test/eunit/couch_epi_basic_test.erl
Modern versions of erlang support specification of supervisor's childspecs as maps. This PR adds support for this in `couch_epi` process replacement mechanism.
`make eunit apps=couch_epi` for isolated tests
=> Support map childspecs in couch_epi supervisor's children replacement

src/couch/test/exunit/fabric_test.exs, src/fabric/src/fabric.erl, test/elixir/lib/setup/common.ex
Previous implementation of `fabric:cleanup_index_files` assembled a regexp by concatenating active signatures.
The approach caused regexp to exceed system limit in the case of huge number of them. 
The stacktrace looked like follows: 
```
2> fabric:cleanup_index_files().
** exception error: no match of right hand side value {error,{"regular expression is too large",37555}}
in function  fabric:cleanup_index_files/1 (src/fabric.erl, line 519)
in call from fabric:'-cleanup_index_files/0-lc$^0/1-0-'/1 (src/fabric.erl, line 501)
in call from fabric:'-cleanup_index_files/0-lc$^0/1-0-'/1 (src/fabric.erl, line 501)
```
This implementation uses different approach. It relies on the fact that view files are named as `${signature}.view`. This means that the signature of the file can be easily …
=> Refactor fabric:cleanup_index_files

dev/run
Sometimes admin party mode causes the 'dev/run' to fail with
```
http.client.RemoteDisconnected: Remote end closed connection without response
```
This PR makes this use case more robust.
- run `dev/run --admin=adm:pass`
N/A
=> Do not fail 'dev/run' on connection close

test/elixir/lib/ex_unit.ex
We had a number  of problems with using meck and eunit. In fact these problems were one of the driving factors to switch to exunit. ExUnit has a reliable teardown behaviour. Which allows as to do a proper cleanup after meck. This PR adds an unconditional call to :meck.unload() into `on_exit` callback. This would guaranty that we wouldn't have leftover mocked modules in subsequent tests.
Hard to test. 
- This PR is a replacement for https://github.com/apache/couchdb/pull/2121
=> Call :meck.unload() automatically after every test

Jenkinsfile, Makefile, Makefile.win, src/chttpd/test/eunit/chttpd_db_test.erl, src/chttpd/test/eunit/chttpd_view_test.erl, src/couch/test/eunit/couch_bt_engine_upgrade_tests.erl
Omitting COUCHDB_VERSION caused the EUnit build of the replicator to have a corrupted User-Agent header. It tried to construct a version using git, but when building from a release tarball there is no git repo so the UA had a git error message in it. This error message contained a newline, which plausibly confused some part of the HTTP stack and caused replicator HTTP requests to hang.
The second commit removes the attempt to publish packages for Ubuntu 14.04, as we're no longer building them for that (EOL) platform.
See https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-cpse-debugging/18/pipeline/, which is building this branch before my cleanup rebase (the final diff from master is identical).
The specific test that was quite regularly failing without this patch …
=> Ensure EUnit inherits appropriate environment variables

src/couch/test/eunit/couch_db_split_tests.erl, src/ddoc_cache/test/eunit/ddoc_cache_lru_test.erl, test/elixir/lib/couch/db_test.ex, test/elixir/test/reshard_helpers.exs
This is straightforward, just adjusting more timeouts in the Jenkins whack-a-mole game. The one novelty here is that some of these timeouts are not timeouts waiting for _any_ response, but timeouts waiting for a specific observable, e.g. that documents show up in the database after an async update.
As I'm only adjusting timeouts here and previous similar changes have already been approved I'm going to go ahead and merge this one.
https://builds.apache.org/blue/organizations/jenkins/CouchDB/detail/jenkins-elixir-retry-until-flakes/6/
=> More timeout adjustments for Jenkins

src/fabric/test/fabric2_doc_fold_tests.erl
Add timeout for 'fold_docs-with_different_keys' test
make eunit apps=fabric tests=doc_fold_test_
N/A
=> Add timeout for 'fold_docs-with_different_keys' test

mix.exs, mix.lock, test/elixir/lib/couch.ex
There were couple of hacks in `test/elixir/lib/couch.ex`
We've got changes needed to remove them into `httpotion` 3.1.3.
The changes were introduced in:
- https://github.com/myfreeweb/httpotion/pull/118
- https://github.com/myfreeweb/httpotion/pull/130
This PR updates `httpotion` to 3.1.3 and removes the hacks from `couch.ex`
1. Make sure tests pass `make elixir`
2. Make sure we set timeouts in calls to ibrowse
2.1. Start iex `iex -S mix`
2.2. Make sure calls to ibrowse have `.....{inactivity_timeout,55000}], 60000)`
```
:dbg.tracer()
:dbg.p(:erlang.pid_to_list(self()), :c)
:dbg.tp(:ibrowse, :send_req, :x)
Couch.request!(:post, "http://google.com", [])
```
PRs in `httpotion`:
- https://github.com/myfreeweb/httpotion/pull/118
- https://github.com/myfreeweb/httpotion/pull/130
=> Update httpotion to 3.1.3

src/couch_replicator/src/couch_replicator.erl, src/couch_replicator/src/couch_replicator_docs.erl
When the `_scheduler/docs` response is generated, the replication docs are
parsed and credentials are stripped by `couch_replicator:strip_url_creds/1`.
When local endpoint support was removed, that function didn't properly catch
the parsing error for local endpoints and as a result was error-ing out the
whole response.
The fix is to catch the error and return the endpoint as is. The catch is
specific to that error, so turned the long binary message into a shorter, but
hopefully still obvious atom.
`_scheduler/docs` response would look like:
```
{
"docs": [
{
"database": "_replicator",
"doc_id": "r",
"error_count": 1,
"id": null,
"info": "local_endpoints_not_supported",
"last_updated": "2019-08-20T16:09:53Z",
"source": "http://adm:*****@127.0.0.1:15984/s/",
"start_time": …
```
=> Fix _scheduler/docs response for local replication endpoints

src/chttpd/src/chttpd_db.erl, src/fabric/src/fabric.app.src, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_db_plugin.erl, src/fabric/src/fabric2_epi.erl, src/fabric/src/fabric2_sup.erl
This mostly equivalent to the `couch_db` EPI plugin, but using fabric2 calls
and without some of the functions that are not relevant to FDB such as
on_compact/1 and others..
Unfortunately had to revert fabric2_sup to tuples temporarily until we rebase
from master and pick up commit 1db0294eb1093066773760b75a200d99aa453be8
=> Implement fabric2_db EPI plugin

src/couch_views/src/couch_views_indexer.erl
That is needed when indexing authentication dbs like `_users`.
=> Open dbs with admin privileges in couch_views_indexer

src/mango/src/mango_error.erl
We should only send a 400 Bad Request if there is genuinely something
wrong with the request, otherwise we mislead users and sysadmins.
Induce a search failure that is unrelated to the request itself, confirm you get a 500 status code.
This does change existing behaviour, but in a good way. Only genuinely bad requests will get a 400 code.
N/A
(no existing test to update. No new config params. The `_find` endpoint already documented to throw a 500).
=> Send a 500, not a 400, for unknown search errors

src/fabric/src/fabric_view_all_docs.erl
In query for `all_docs` with passed `keys` array it is possible for `doc_receive_loop/6` to timeout and trigger `badmatch` exception.
The fix changes code to accept `timeout` as a possible response and passes it to Callback to process.
It's kind of hard to induce timeout on that all_docs read without actual code tweaking, so base tests just need to pass.
Described in #2149
=> Fix badmatch in fabric_view_all_docs

test/elixir/test/compact_test.exs
Skipping CompactTest due to compaction failure
Refer:- https://github.com/apache/couchdb/pull/2127
=> Skipping CompactTest due to compaction failure

rel/overlay/etc/default.ini, src/fabric/src/fabric2_db.erl, test/elixir/test/basics_test.exs
This is done for compatibility with CouchDB < 4.x where this limit was
implicitly enforced by the file system's max filename size. The default value
enforces the same limit for FDB in case users decide to replicate back and
forth between old and new instances with 'create_target = true' option.
=> Add a max db name length config option

src/fabric/src/fabric2_db.erl, test/elixir/test/basics_test.exs
On master `_local_docs&update_seq=true` returns the update sequence of the
database. Even though it might not make much sense since updating local docs
doesn't bump the sequence, it's probably a good idea to stay consistent.
It's also worth mentioning another inconsistency is when FDB returns a
`total_rows` count for `_local_docs` while master returns `null`. I think
that's probably acceptable. Master would return the count if had it available
easily and having it seems like a useful thing and an improvement.
To test:
```
make elixir tests=test/elixir/test/basics_test.exs
```
=> Handle update_seq for _local_docs

src/chttpd/src/chttpd_changes.erl, src/chttpd/src/chttpd_db.erl
On master this is happening in `fabric_view_changes` but on FDB we don't go
through that module anymore, so we do in `chttpd_changes` module instead.
=> Handle _changes since=now param

src/chttpd/src/chttpd_auth_cache.erl
This stack trace comes up in user support a lot, mostly in unrelated discussions. This should remove a red herring stack trace and simplify support.
Start a node without going through the setup procedure. Or delete the `_users` db and restart a node.
=> feat: less scary error message

src/chttpd/src/chttpd_changes.erl, src/chttpd/src/chttpd_db.erl
`TimeoutFun` was already returning `{ok|stop, UserAcc}` so there was no need to
wrap it another `{ok, ...} tuple.
Also TimeoutFun was calling user with`{timeout, _ResponseType}` not just timeout, so added a clause to handle that as well.
=> Fix _changes heartbeat option

src/fabric/src/fabric.erl
This PR is not to cleanup ongoing compact files using fabric:cleanup_index_files/1
make exunit tests=src/couch/test/exunit/fabric_test.exs
```
17:55:56.045 [debug] Calling 'teardown/3' for 'Elixir.Couch.Test.Setup.Step.Config'
* test Fabric miscellaneous API Get inactive_index_files (1146.4ms)
Finished in 1.2 seconds
1 test, 0 failures
```
https://github.com/apache/couchdb/pull/2101
=> do not cleanup ongoing compact files using fabric:cleanup_index_files/1

dev/run
Sometimes there is a need to specify additional arguments for the beam process we start from dev/run.
In particular the feature is handy for:
- changing emulator flags
- simulate OOM via available RAM restrictions
- enable module loading tracing
- configure number of schedulers
- modify applications configuration
- run customization script to add extra development deps (such as automatic code reload)
Historically developers had to edit dev/run to do it.
This PR adds an ability to specify additional arguments via `--extra_args` argument.
In order to run customization script create `customization.erl` which exports `start/0` and run it using:
```
dev/run --extra_args='-run customization'
```
1. Create `dev/customization.erl` with the following content:
```
-module(customization). …
```
=> Support `--extra_args` parameter in `dev/run`

src/couch_mrview/src/couch_mrview.erl
Fixes a very small typo in a comment in couch_mrview,erl
"uknown languages" to "unknown languages"
N/A
N/A
=> Fix typo in couch_mrview comment

src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_db_security_tests.erl
Make get_security and get_revs_limit calls consistent
There are two fixes:
1) In `fabric2_fdb:get_config/1`, Db was matched before and after
`ensure_current/1`. Only the db prefix path was used, which doesn't normally
change, but it's worth fixing it anyway.
2) We used a cached version of the security document outside the transaction.
Now we force it go through a transaction to call `fabric2_fdb:get_config/1`
which call `ensure_current/1`. When done, we also update the cached Db handle.
Do the same thing for revs_limit even thought it is not as critical as
security.
=> Make get_security and revs_limit calls consistent

src/couch/src/couch_db.erl, src/couch_mrview/src/couch_mrview_index.erl, src/couch_mrview/test/eunit/couch_mrview_index_info_tests.erl, src/fabric/src/fabric_db_info.erl, src/fabric/src/fabric_group_info.erl, test/elixir/test/compact_test.exs, test/javascript/tests/attachments.js, test/javascript/tests/compact.js, test/javascript/tests/design_docs.js, test/javascript/tests/view_compaction.js
These fields are all marked as deprecated in the current documentation
and they have more specific replacements in the `sizes` object.
Fauxton needs an update as well.
Closes #2162 
Documentation PR at apache/couchdb-documentation#435
=> Remove deprecated dbinfo fields

src/fabric/src/fabric2_db.erl, src/fabric/test/fabric2_rev_stemming.erl
We had it for replicated doc updates so now we do the same for interactive ones
=> Add revision stemming for interactive docs

src/chttpd/src/chttpd_view.erl
Users should send requests with multiple queries to the new endpoint:
/db/_design/{ddoc}/_view/{view}/queries
Closes #2168
=> Remove old multi-query path

src/chttpd/src/chttpd_misc.erl
The reason we don't do this in `config:features()` directly is because this one is a dynamic check for the presence of a connected clouseau node. Calling `enable_feature` every time we conduct that check seemed too heavyweight, but I didn't see a good opportunity to just call it once and be confident that it would reliably advertise the feature.
The downside here is that CouchDB will not advertise the "search" feature if Clouseau is disconnected for maintenance or whatever, although technically it's accurate since search requests submitted during that interval would fail.
Wire up CouchDB with Clouseau and see if "search" shows up in the list of features.
#2205
=> Include search in the list of advertised features

src/mango/src/mango_native_proc.erl
This check breaks if clouseau is excluded entirely from the release.
Our check for clouseau did not anticipate clouseau not existing.
Delete clouseau_rpc.beam and `make check`
N/A
=> Fix clouseau detection

src/couch_views/src/couch_views_jobs.erl
set_type_timeout takes seconds as the argument but we gave it milliseconds
=> Fix timeout in couch_views

src/dreyfus/src/clouseau_rpc.erl
Ping clouseau directly
clouseau_rpc:connected() should return false if clouseau is down.
N/A
=> Ping clouseau directly

rel/overlay/etc/default.ini, src/couch/src/couch_multidb_changes.erl
Update default config settings
In a fresh install, create a database, confirm that it is q=2. Try to create a >8mb document and confirm that it fails.
https://github.com/apache/couchdb/issues/2115
=> Update default config settings

src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_db_test.erl
Problem
-------
The request of continious _changes feed doesn't return until either:
- new change is made to the database
- the heartbeat interval is reached
This causes clients to block on subscription call.
Solution
--------
Introduce a counter to account for number of chunks sent.
Send '\n' exactly once on `waiting_for_updates` when `chunks_sent`
is still 0.
The implementation is suggested by @davisp [here](https://github.com/apache/couchdb/issues/985#issuecomment-537150907). There is only one difference from his proposal which is:
```
diff --git a/src/chttpd/src/chttpd_db.erl b/src/chttpd/src/chttpd_db.erl
index aba1bd22f..9cd6944d2 100644
--- a/src/chttpd/src/chttpd_db.erl
+++ b/src/chttpd/src/chttpd_db.erl
@@ -215,7 +215,7 @@ changes_callback(waiting_for_updates, #cacc{buffer = []} …
```
=> Return headers from _changes feed when there are no changes

rebar.config.script
Fauxton 1.2.0 failed to compile on some platforms. 1.2.1 is a patch release which updates the webpack dependency to address this.
N/A
https://github.com/apache/couchdb-fauxton/issues/1230
=> Update Fauxton to 1.2.1

src/couch_replicator/README.md, src/couch_replicator/src/couch_replicator.erl, src/couch_replicator/src/couch_replicator_docs.erl, src/couch_replicator/src/couch_replicator_sup.erl
We don't support "local" replications in 3.x so there is not need to waste resources creating this db on every node, and then continuously listening for replication doc updates from it.
=> Stop creating node local _replicator db

src/couch_jobs/src/couch_jobs_fdb.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_txids.erl
=> Use a shorter name for create_or_open_couchdb_dir

rebar.config.script
Update Fauxton to 1.2.2. This release explicitly installs peer dependencies, the lack of which were causing the webpack bundling to fail (i.e. fixes build from source).
N/A
https://github.com/apache/couchdb-fauxton/issues/1229
=> Update Fauxton to 1.2.2

rebar.config.script
* Always include 'query' as an allowed language
=> Update ken to 1.0.5

src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_db_misc_tests.erl
Take better advantage of metadata version key feature
Issue https://github.com/apache/couchdb/issues/2224
FDB's metadata version key allows more efficient metadata invalidation
(see apple/foundationdb#1213). To take advantage of
that feature update the caching logic to check the metadata version first, and
if it is current, skip checking the db version altogether.
When db version is bumped we now update the metadata version as well.
There is a bit of a subtlety when the metadata version is stale. In that case
we check the db version, and if that is current, we still don't reopen the
database, instead we continue with the transaction. Then, after the transaction
succeeds, we update the cached metadata version for that db handle. Next client
would get the updated db metadata, it will be …
=> Take better advantage of metadata version key feature

src/chttpd/src/chttpd_db.erl, test/elixir/test/changes_test.exs
Using a negative heartbeat value does not return a 400 bad request, instead getting just an empty response with no status code at all.
This commit adds extra checks so that negative and non-integer heartbeat values return 400 bad request responses.
The changes has been tested manually:
```
[donat:~/couchdb] changes-feed-input-validation 1 ± curl -XPUT http://127.0.0.1:15984/asd
{"ok":true}
[donat:~/couchdb] changes-feed-input-validation ± curl -v http://127.0.0.1:15984/asd/_changes?feed=continuous\&heartbeat=-1000
*   Trying 127.0.0.1...
* TCP_NODELAY set
* Connected to 127.0.0.1 (127.0.0.1) port 15984 (#0)
> GET /asd/_changes?feed=continuous&heartbeat=-1000 HTTP/1.1
> Host: 127.0.0.1:15984
> User-Agent: curl/7.64.1
> Accept: */*
>
< HTTP/1.1 400 Bad Request
< Cache-Control: …
```
=> Make changes feed return bad request for invalid heartbeat values

src/chttpd/src/chttpd_db.erl
Fix compiler warning about unused variable.
successful compilation would be sufficient
N/A
=> Remove compiler warning

src/chttpd/src/chttpd.erl, src/couch/src/couch_httpd.erl
The history of `send_error(_Req, {already_sent, Resp, _Error})`
clause is bellow:
- it was added on [2009/04/18](https://svn.apache.org/viewvc/couchdb/trunk/src/couchdb/couch_httpd.erl?r1=762574&r2=765819&diff_format=h)
- we triggered that clause [in couch_httpd:do](https://svn.apache.org/viewvc/couchdb/trunk/src/couchdb/couch_httpd.erl?revision=642432&view=markup#l88)
- at that time we were using inets webserver [see use of `httpd_response/3`](https://svn.apache.org/viewvc/couchdb/trunk/src/couchdb/couch_httpd.erl?revision=642432&view=markup#l170)
- The inets OTP codebase uses `already_sent` messages [here](https://github.com/erlang/otp/blob/50214f02501926fee6ec286efa68a57a47c2e531/lib/inets/src/http_server/httpd_response.erl#L220)
It should be safe to remove this clause because we are …
=> Remove old clause which is no longer used

src/fabric/include/fabric2.hrl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/test/fabric2_doc_crud_tests.erl, src/fabric/test/fabric2_local_doc_fold_tests.erl, test/elixir/test/basics_test.exs
Previously local docs were not chunkified and it was possible for replications
which checkpointed a few dozen times to create local documents above the 100KB
limit.
Documents are chunkiefied according to the same scheme as the regular docs --
rev values are in a main `?DB_LOCAL_DOCS` subspace, and doc body chunks in a
separate `?DB_LOCAL_DOC_BODIES` subspace that looks like:
`{?DB_LOCAL_DOC_BODIES, DocId, ChunkId} = BinaryChunk`
where `ChunkId` is an incrementing integer and BinaryChunk is a 100KB chunk of
the term_to_binary of the body.
We also go to some lengths to read and silently upgrade docs written with the
old encoding. Upgrades happen on doc writes as a first step, to ensure stats
update logic is not affected.
=> Chunkify local docs

src/fabric/src/fabric2_fdb.erl
Since we are dealing with upgrades and both versions start out as binaries,
make sure we add extra belts and suspenders to surface any issues with encoding
errors.
=> Add a special error for an invalid legacy local doc revsion

.travis.yml, src/fabric/src/fabric_view_all_docs.erl
This PR fixes a bug introduced in #2153 where `timeout` was passed to `Callback` as a plain atom instead of tagged tuple `{error, timeout}`, inducing a function clause crash in `couch_mrview_http`.
Ref: #2153
=> Pass timeout as an error to callback in `fabric_view_all_docs`

src/couch_jobs/src/couch_jobs.hrl, src/fabric/include/fabric2.hrl
Need to use FDB version 6.1+ and erlfdb version that has this commit: https://github.com/cloudant-labs/couchdb-erlfdb/commit/7718a3d7e1994e1384c56d39fae5cad3d8c6c4b3
Since fabric2.hrl is a public include now, use that in couch_jobs to avoid redefining a bunch of things.
=> Use "\xFF/metadataVersion" key for checking metadata

src/couch/src/couch_util.erl, src/couch_replicator/src/couch_replicator_scheduler.erl
Since we now have separate proxies for source and target, show them in `_scheduler/docs` endpoint as separate as well. Previously we just read the proxy value from the source.
When formatting the proxy url for output, make sure `socks5` schema is handled
by the url credentials stripping code to avoid exposing user credentials.
`make eunit apps=couch_replicator suites=couch_replicator_scheduler`
Start a replication with source and/or target proxies defined, then call _scheduler/docs and inspect the output.
https://github.com/apache/couchdb/commit/053d494e698181ae3b0b0698055f5a24e7995172
=> Show source and target proxies in _scheduler/docs output

src/chttpd/src/chttpd_db.erl
Since the db structure returned from fabric2_db:open and fabric2_db:create
includes `user_ctx` there is no need to pass it explicitly
in every `fabric2_db` call. This means we can simplify few things:
- Don't pass user_ctx in `chttpd_db:db_req/2` since we pass db already
- Don't have to use `db_open_options` in `chttpd_changes`
- Don't have to pass `user_ctx` to `fabric2_db:open_doc` and `fabric2_db:update_doc`
```
make eunit apps=fabric
```
N/A
=> Pass contexts to fabric2_db functions

src/couch_replicator/src/couch_replicator_doc_processor.erl
Previously if couch_replicator_doc_processor crashed, the job was marked as
"failed". We now ignore that case. It's safe to do that since supervisor will
restart it anyway, and it will rescan all the docs again. Most of all, we want
to prevent the job becoming failed permanently and needing a manual
intervention to restart it.
=> Do not mark replication jobs as failed if doc processor crashes

src/couch_mrview/src/couch_mrview.erl, src/fabric/test/fabric2_doc_crud_tests.erl
Users should be able to replicate their partitioned dbs to the new environment.
=> Ensure we can create partitioned design docs with FDB

src/dreyfus/src/clouseau_rpc.erl, src/dreyfus/src/dreyfus_index_manager.erl
The problem was originally exposed when updating search index with the following error:
```
{error, "*** eval: {'EXIT',{{badmatch,{error,<<"Lock obtain timed out: NativeFSLock@/srv/search_index/shards/20000000-3fffffff/user1/db1.1509715496/ec8bc1dc690a15d795e65f7dce409e2c/write.lock">>}},\n                   [{erl_eval,expr,3,[]}]}}"}
```
Finally, it turns out that the soft-deletion path is missing a call to evict the shard from LRU (and therefore release the associated locks). This causes that lock file was left in working directory and search index failed to be updated.
To address this, the fix is to close the corresponding index in LRU before index is to be renamed/deleted.
@theburge made excellent troubleshooting and analysis, and also wrote below script to reproduce problem. …
=> Close LRU by database path for deleted database/index

src/couch_replicator/src/couch_replicator_doc_processor.erl, src/couch_replicator/src/couch_replicator_scheduler.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_stats.erl, src/couch_replicator/src/couch_replicator_utils.erl, src/couch_replicator/test/eunit/couch_replicator_retain_stats_between_job_runs.erl
Previously `_scheduled/docs` returned detailed replication statistics for
completed jobs only. To get the same level of details from a running or pending
jobs users had to use `_active_tasks`, which is not optimal and required jumping
between monitoring endpoints.
`info` field was originally meant to hold these statistics but they were not
implemented and it just returned `null` as a placeholder. With work for 3.0
finalizing, this might be a good time to add this improvement to avoid
disturbing the API afterwards.
Just updating the `_scheduler/docs` was not quite enough since, replications
started from the `_replicate` endpoint would not be visible there and users
would still have to access `_active_tasks` to get inspect them, so let's add
the `info` field to the `_scheduler/jobs` as …
=> Return detailed replication stats for running and pending jobs

src/couch/src/couch_stream.erl
We have been failing to honor Range requests that specify an ending byte less than the final byte of an attachment. The code that was supposed to truncate the binary to the desired length was actually executing a noop statement that preserved the entire binary.
Many HTTP clients will ignore the extra bytes on the wire and so this bug has gone undetected for a long time. Newer releases of libcurl that disable HTTP/0.9 support do detect it, and so we implicitly have a test for this in attachment_ranges.js, but ideally we'd have a more explicit one at some point in the future.
Without this patch the attachment_ranges test fails when using libcurl version 7.66 or higher.
Fixes #2244
=> Send only as many bytes as requested by Range header

src/chttpd/src/chttpd_auth_request.erl, src/fabric/src/fabric2_db.erl, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_server.erl, src/fabric/test/fabric2_db_security_tests.erl
Previously we checked security properties in a separate transaction, after
opening the db or fetching it from the cache. To avoid running an extra
transaction move the check inside the main transaction right after the metadata
check runs. That ensure it will be consistent and it won't be accidentally
missed as all operations run the `ensure_current` metadata check.
Also remove the special `get_config/2` function in `fabric2_fdb` for getting
revs limit and security properties and just read them directly from the db map.
Test with:
`make && make eunit apps=fabric,couch_views,couch_jobs`
`make && make elixir tests=test/elixir/test/basics_test.exs,test/elixir/test/replication_test.exs,test/elixir/test/map_test.exs,test/elixir/test/all_docs_test.exs,test/elixir/test/bulk_docs_test.exs`
=> Check security properties in the main transaction

src/fabric/src/fabric2_fdb.erl
Forgot to push this in the previous PR so made a new commit.
Original PR: https://github.com/apache/couchdb/pull/2300#discussion_r346592418
=> Assert Db handle field existence in `load_config/1` in fabric2_fdb

Jenkinsfile, Makefile, src/mango/test/13-stable-update-test.py
Tell the auto-indexer to stand down during the unit test to prevent an occasional flake.
Also, include Mango test results in Jenkins reporting.
Jenkins is building automatically here:
https://builds.apache.org/blue/organizations/jenkins/CouchDB/activity?branch=jenkins-add-mango-test-reporting
Last build was largely successful, and every platform passed the test that is being fixed here.
=> Set autoupdate:false during update=false mango test

src/fabric/src/fabric2_db.erl, src/fabric/test/fabric2_db_security_tests.erl
Previously, membership check was disabled when fetching the security doc. That
was not correct, as membership should be checked before every db operation,
including when fetching the security doc itself.
Also, most of the security tests relied on patching the user context in the
`Db` handle then calling `check_*` functions. Those functions however call
`get_security/1` before doing the actual check, and in some cases, like when
checking for admin, the failure was coming from the membership check in
`get_security/1` instead. Also some tests were going through the regular
request path of opening a new db by name. In order, make the tests more
uniform, switch all the tests to apply the tested `UserCtx` in the open call.
=> Check membership when calling get_security/1 in fabric2_db

.gitignore, rebar.config.script, rel/overlay/etc/default.ini, src/chttpd/src/chttpd.app.src, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_handlers.erl, src/chttpd/src/chttpd_httpd_handlers.erl, src/couch/src/couch_util.erl, src/ctrace/README.md, src/ctrace/rebar.config, src/ctrace/src/ctrace.app.src, src/ctrace/src/ctrace.erl, src/ctrace/src/ctrace.hrl, src/ctrace/src/ctrace_app.erl, src/ctrace/src/ctrace_config.erl, src/ctrace/src/ctrace_dsl.erl, src/ctrace/src/ctrace_sup.erl, src/ctrace/test/ctrace_config_test.erl, src/ctrace/test/ctrace_dsl_test.erl, src/ctrace/test/ctrace_test.erl, src/fabric/src/fabric.app.src, src/fabric/src/fabric2_fdb.erl, src/fabric/src/fabric2_server.erl, src/fabric/test/fabric2_dir_prefix_tests.erl
This PR implements opentracing support. It mostly implements [RFC-011](https://github.com/apache/couchdb-documentation/blob/master/rfcs/011-opentracing.md).
0. Run test suite 
```bash
$ make eunit apps=ctrace
```
1. Write connection string into fdb.cluster file
2. Start FDB server
3. Update rel/overlay/etc/default.ini similar to this:
```ini
[tracing]
enabled = true
thrift_format = compact ; compact | binary
agent_host = 127.0.0.1
agent_port = 6831
app_name = couchdb
[tracing.filters]
; Log all traces
all = (#{}) -> true
; Disable tracing POST requests to `/dbname`
database-info.read = (#{'http.method' := Method}) when Method == 'POST' -> false
; Log 50% of all view builds
view.build = (#{}) -> 0.5
```
4. Start jaeger `docker run -d -p 6831:6831/udp   -p 16686:16686 …
=> Opentracing pd

src/chttpd/src/chttpd_app.erl, src/chttpd/src/chttpd_sup.erl, src/couch_views/src/couch_views_app.erl, src/couch_views/src/couch_views_sup.erl, src/fabric/src/fabric2_node_types.erl, src/fabric/test/fabric2_node_types_tests.erl
Implementation follows the  [RFC][1]
[1]: https://github.com/apache/couchdb-documentation/blob/master/rfcs/013-node-types.md
Run tests with:
```
make eunit apps=fabric suites=fabric2_node_types_tests
module 'fabric2_node_types_tests'
Test node types
fabric2_node_types_tests: node_types_test_ (basics)...[1.224 s] ok
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
fabric2_node_types_tests: node_types_test_ (os_env_priority)...[0.009 s] ok
[os_mon] cpu supervisor port (cpu_sup): Erlang has closed
[done in 2.135 s]
[done in 2.135 s]
=======================================================
2 tests passed.
```
=> Implement node types

src/chttpd/src/chttpd_auth.erl, src/couch/test/eunit/couchdb_auth_tests.erl
Previously with require_valid_user=true configured a user would need to supply Basic auth credentials in order to login via the _session endpoint (or have some otgher Catch-22 way of using an existing session). This patch makes it so that any attempt to POST to _session is allowed to proceed.
Try to POST to `_session` with `require_valid_user = true` and don't supply any additional basic auth header. Without this patch you would get rejected.
Closes #1947.
=> Don't require auth on login attempts

src/dreyfus/src/clouseau_rpc.erl, src/dreyfus/src/dreyfus_index_manager.erl
This is to revert "Close LRU by database path for deleted database/index" due to introduction of https://github.com/apache/couchdb/pull/2322 where writer can be closed before soft-deletion of index.
https://github.com/apache/couchdb/pull/2322 
https://github.com/apache/couchdb/pull/2130
https://github.com/cloudant-labs/clouseau/pull/25
=> Revert "Close LRU by database path for deleted database/index"

src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_handlers.erl, src/chttpd/src/chttpd_httpd_handlers.erl, src/global_changes/src/global_changes_httpd_handlers.erl, src/mango/src/mango_httpd_handlers.erl, src/mem3/src/mem3_httpd_handlers.erl, src/setup/src/setup_httpd_handlers.erl
This adds operation names to all valid HTTP end points. This covers all
of `make elixir` except for seven requests that are testing specific
error conditions in URL and Methods for various endpoints.
Set operation names for HTTP trace spans
With tracing enabled and an empty Jaeger instance:
`make && make elixir`
=> Add operation names for all HTTP endpoints

rebar.config.script, src/smoosh/README.md, src/smoosh/operator_guide.md, src/smoosh/src/smoosh.app.src, src/smoosh/src/smoosh.erl, src/smoosh/src/smoosh_app.erl, src/smoosh/src/smoosh_channel.erl, src/smoosh/src/smoosh_priority_queue.erl, src/smoosh/src/smoosh_server.erl, src/smoosh/src/smoosh_sup.erl, src/smoosh/src/smoosh_utils.erl, src/smoosh/test/exunit/scheduling_window_test.exs, src/smoosh/test/exunit/test_helper.exs
This adds the auto-compaction daemon directly into the main repo. It also adds the "Support scheduling compactions during time windows" enhancement and related unit tests that were added to couchdb-smoosh after the 1.0.1 tag.
We use git-subtree to carry the smoosh history forward, with an invocation like
```
git subtree add --prefix=src/smoosh https://github.com/apache/couchdb-smoosh.git master
```
Check that the codebase is the same as you would get by moving the "smoosh" tag in rebar to "master".
=> Bring smoosh in-tree

src/chttpd/src/chttpd_misc.erl, test/elixir/test/basics_test.exs
This changes an end-point `/_up` to verify that fdb cluster is accessible, i.e. confirms that fdb-layer node is ready to serve.
`make elixir tests=test/elixir/test/basics_test.exs:21`
=> Change end-point `/_up` to check fdb connectivity

src/chttpd/src/chttpd_db.erl, test/elixir/test/partition_crud_test.exs
Return a 400 for urls /partitiondb/_partition with no partition key
Fixes #2332
=> Return 400 error for missing partition key

src/couch_mrview/test/eunit/couch_mrview_purge_docs_tests.erl, src/couch_pse_tests/src/cpse_test_purge_docs.erl, src/couch_pse_tests/src/cpse_test_purge_seqs.erl, src/couch_pse_tests/src/cpse_util.erl, src/dreyfus/src/dreyfus_index.erl, src/fabric/test/eunit/fabric_rpc_purge_tests.erl
https://github.com/apache/couchdb/pull/1445 introduced a shim to
enable CouchDB to be compiled to use the Erlang MD5 function.
This allows CouchDB to run in FIPS environments where the crypto
module is restricted such that `crypto:hash(md5,..)` is blocked
(fails with `notsup` error).
This commit replaces usage of `crypto:hash(md5, ..)` introduced since
the original PR with the shim function.
=> Update usage of couch_hash:md5_hash shim

src/chttpd/src/chttpd_view.erl, src/couch_mrview/src/couch_mrview_http.erl, src/couch_mrview/src/couch_mrview_util.erl, test/elixir/test/view_test.exs
This change should allow users to supply all params in [POST](http://docs.couchdb.org/en/stable/api/ddoc/views.html#post--db-_design-ddoc-_view-view) that can be supplied for [GET](http://docs.couchdb.org/en/stable/api/ddoc/views.html#get--db-_design-ddoc-_view-view) now. This way we could avoid the `?key="foo"` things that would probably cause a lot of pain for users.
So far this has been tested manually and it seems to be working.
```
curl -H 'Content-Type: application/json'  -XPOST -d '{"key": "yo"}' http://127.0.0.1:15984/asd/_design/newDD/_view/newview |jq
{
"total_rows": 2,
"offset": 0,
"rows": [
{
"id": "yo",
"key": "yo",
"value": {
"fromView": "yes",
"_id": "yo",
"_rev": "1-ffdc431dc4d2660c2af2e85e3abf723e",
"asd": "dsa"
}
}
]
}
```
=> Allow all params to be passed via body for POST view

src/chttpd/src/chttpd_db.erl, src/chttpd/src/chttpd_show.erl, src/couch_mrview/src/couch_mrview_http.erl, src/couch_mrview/src/couch_mrview_show.erl, test/elixir/test/all_docs_test.exs, test/elixir/test/design_docs_test.exs, test/elixir/test/local_docs_test.exs
This change should allow users to supply all params in POST that can be supplied for GET now. This way we could avoid the ?key="foo" things that would probably cause a lot of pain for users.
As `/{db}/_design_docs` and `/{db}/_local_docs` are analogous to `_all_docs`, this change applies to all three of them.
Just run the tests included with this PR.
Let me know if you need instructions for manual testing.
https://github.com/apache/couchdb-documentation/pull/462
=> Allow all params to be passed via body for POST _all_docs

rel/files/couchdb.cmd.in, rel/overlay/etc/local.ini
* Missing `COUCHDB_FAUXTON_DOCROOT` in `couchdb.cmd`
* Since it's still working, line is `REM`med out for now
* Invalid `[query_servers]` section still present in `local.ini`
=> 2 small release file fixes
