apache/couchdb

build-aux/Jenkinsfile.full
=> Bring back POWER full builds

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
* Add Ubuntu Jammy to [full CI](https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/jenkins-erlang-25-and-ubuntu-jammy-ci-update/1/pipeline)
* Add Erlang 25.0.2 to [PR CI](https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FPullRequests/detail/PR-4088/1/pipeline)
This is using the branch new images built in https://github.com/apache/couchdb-ci/pull/39
=> Add Erlang 25 to PR CI pipeline and Ubuntu Jammy to full CI

rel/overlay/etc/default.ini, src/custodian/src/custodian_util.erl
In cases when the application prevents creating dbs with non-default n values (n=1, n=2) setting `[custodian] use_cluster_n_as_expected_n = true` can help detect case when the shard map itself was manipulated and by mistake ended up with less than `[cluster] n` copies for some ranges.
By default the behavior is unchanged and n value will be deduced from the number of copies indicated in the shard map documents.
=> Add an option to let custodian always use [cluster] n value

src/couch/src/couch_doc.erl, src/couch/src/couch_passwords.erl, src/couch/src/couch_util.erl, src/couch/src/couch_uuids.erl, src/couch/src/test_util.erl, src/couch/test/eunit/couch_auth_cache_tests.erl, src/couch/test/eunit/couch_key_tree_tests.erl, src/couch/test/eunit/couch_util_tests.erl, src/couch_index/src/couch_index_util.erl
When profiling [1] a cluster acting as a replication source, noticed a lot of time spent in `couch_util:to_hex/1`. That function is used to emit revision ids amongst other things. When processing a million documents with a 1000 revisions
each, it ends up in the hotpath, so to speak.
Remembering that in Erlang/OTP 24 there is a new [`binary:encode_hex/1`](https://www.erlang.org/doc/man/binary.html#encode_hex-1) function, decided to benchmark ours vs the OTP implementation. It turns ours is slower [2] so let's try to use the OTP one.
One difference from the OTP's version is ours emits lower case hex letters, while the OTP one emits upper case ones. 
As a bonus, replaced a few calls to `couch_util:to_hex/1` wrapped in `?l2b/1` or `list_to_binary/1` with just a single call to …
=> Optimize couch_util:to_hex/1

src/couch_replicator/src/couch_replicator_changes_reader.erl, src/couch_replicator/src/couch_replicator_docs.erl, src/couch_replicator/src/couch_replicator_ids.erl, src/couch_replicator/src/couch_replicator_js_functions.hrl, src/couch_replicator/test/eunit/couch_replicator_many_leaves_tests.erl
`winning_revs_only` option replicates only the winning revisions from the source to the target, effectively discarding conflicts.
This option may be used as an alternative to the custom VDU strategy, or manual _all_docs read and POST to target scripts, often used by users to discard conflicted document revisions.
Behind the scenes the implementation simply switches the `_changes` feed style to `main_only` from the replication default of `all_docs`.
Additionally, when enabled, the `winning_revs_only` option, will generate a different replication ID and use a different set of checkpoints than the default case. This should allows first replicating with `winning_revs_only: true`, and then later replicate normally between the same endpoints, in order to "backfill" the rest of the revisions. …
=> Implement winning_revs_only option for the replicator

test/elixir/test/design_docs_test.exs
We saw it fail quite a few times already so adding a retry around it.
Unfortunately it could now fail with a timeout instead of an assert but since we're updating a document there is no idempotent way to testing it (retry until, then do the actual assert again below).
=> Fix flaky "validate doc update" elixir test

Makefile, build-aux/logfile-uploader.py
It broke at some point so no need to keep trying to upload them
=> Skip uploading build logs for now

src/couch/test/eunit/couch_bt_engine_compactor_tests.erl, src/smoosh/src/smoosh_channel.erl, src/smoosh/src/smoosh_utils.erl, src/smoosh/test/smoosh_tests.erl
Persistence and recovery of view compaction jobs was never intended. This PR adds a check to skip the process for view compaction jobs and also improves the `is_compacting/1` test.
```
make eunit apps=smoosh
```
Add smoosh queue persistence: https://github.com/apache/couchdb/pull/3766
=> Remove view compaction jobs recovery and improve is_compacting/1 test

src/couch/test/eunit/couch_bt_engine_compactor_tests.erl
The test added in https://github.com/apache/couchdb/pull/4104 was not called and therefore never run. This PR calls the new test.
```
make eunit apps=couch suites=couch_bt_engine_compactor_tests
```
Remove view compaction jobs recovery and improve `is_compacting/1` test: https://github.com/apache/couchdb/pull/4104
=> Fix not calling is_compacting test

test/elixir/test/design_docs_test.exs
Add `retry_until()` to `create_doc()` to remove unstable tests.
```
./configure --dev --spidermonkey-version 60 && make couch
make exunit
make elixir-suite
```
=> Fix the flaky tests for `create_doc()`

src/chttpd/src/chttpd_node.erl
When getting the distribution stats, we get a list of all the connected nodes that we then loop over to get the statistics. While looping, one of the nodes can become unresponsive or offline during that check which results in `{error, einval}`. This will be more of an issue on larger clusters as there is more of a time window for the initial acquisition of open sockets and the iteration of checking each.
=> Fix stats endpoint

dev/run
recent versions of haproxy attempt to discover truncated configs
by insisting on a final blank line.
=> make haproxy config valid again

src/chttpd/src/chttpd_db.erl, src/couch/include/couch_db.hrl, src/couch/src/couch_db.erl, src/couch/src/couch_db_updater.erl, src/couch/src/couch_httpd_db.erl, src/couch/test/eunit/couch_db_plugin_tests.erl, src/couch/test/eunit/couchdb_update_conflicts_tests.erl, src/couch_mrview/test/eunit/couch_mrview_purge_docs_tests.erl, src/couch_pse_tests/src/cpse_test_purge_docs.erl, src/couch_pse_tests/src/cpse_test_purge_seqs.erl, src/couch_pse_tests/src/cpse_util.erl, src/couch_replicator/src/couch_replicator_api_wrap.erl, src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_many_leaves_tests.erl, src/fabric/src/fabric_doc_open.erl, src/fabric/src/fabric_doc_open_revs.erl, src/fabric/src/fabric_doc_update.erl, src/fabric/src/fabric_rpc.erl, src/mem3/src/mem3_bdu.erl, src/mem3/src/mem3_rep.erl
We have made some mistakes there in the past mis-typing those. For example in https://github.com/apache/couchdb/pull/3934, so as a preliminary PR to fix https://github.com/apache/couchdb/issues/4121, where we'd have to again special case logic based on the update type, let's switch them to be defines so the compiler would double-check those values for us.
=> Turn document update mode atoms into defines

src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_db_test.erl
We are already doing that for [`_bulk_docs`](https://github.com/apache/couchdb/issues/2242) but forgot to do it for individual doc updates.
Fixes: https://github.com/apache/couchdb/issues/4121
=> Return a 400 response for a single new_edits=false doc update without revisions

src/couch/src/couch_httpd_auth.erl, test/elixir/test/config/skip.elixir, test/elixir/test/proxyauth_test.exs
This reverts commit daff65d8c8772c637eb60365d6e672543163a740.
as discussed in https://github.com/apache/couchdb/issues/4119
=> Revert "Replace SHA-1 with SHA-256 for cookie authentication (#4094)"

src/couch/src/couch_debug.erl, src/couch_mrview/src/couch_mrview_debug.erl
Implement index report functions to facilitate memory leak detections.
=> Implement index report functions

src/chttpd/src/chttpd.app.src, src/chttpd/src/chttpd_auth_cache.erl, src/couch_index/src/couch_index.app.src, src/couch_index/src/couch_index.erl, src/couch_peruser/src/couch_peruser.app.src, src/couch_peruser/src/couch_peruser.erl, src/couch_replicator/src/couch_replicator.app.src, src/couch_replicator/src/couch_replicator_docs.erl, src/global_changes/src/global_changes.app.src, src/global_changes/src/global_changes_server.erl, src/ioq/src/ioq.erl, src/mem3/src/mem3.app.src, src/mem3/src/mem3_nodes.erl, src/mem3/src/mem3_shards.erl, src/mem3/src/mem3_util.erl
This addresses #4101 and adds `io_priority` labels in a number of places that they weren't previously set before. It also introduces the `system` `io_priority` for internal database operations.
I also took the opportunity to add a few utility functions for setting `io_priority` values, abstracting over the use of the process dictionary for storing these values. We could also update the existing places where `io_priority` is set to use the new functions, but that might be better in a separate PR.
Normal test suite should suffice.
=> 4101 add io priority

src/dreyfus/src/clouseau_rpc.erl, src/ioq/src/ioq.erl
Add a dedicated `ioq:call_search` function to more clearly distinguish IOQ search traffic from normal couch_file operations.
Standard test suite.
This is related to https://github.com/apache/couchdb-ioq/pull/21 for establishing a dedicated IOQ2 process for routing search requests through.
=> Add ioq:call_search

config/integration.exs, config/test.exs, test/elixir/config/test.exs
Migrate deprecated config option variable to new config option
=> Fix elixir :logger warnings

rebar.config.script, src/chttpd/rebar.config, src/couch/rebar.config.script, src/couch_dist/rebar.config, src/couch_epi/rebar.config, src/couch_event/rebar.config, src/couch_index/rebar.config, src/couch_log/rebar.config, src/couch_mrview/rebar.config, src/couch_tests/rebar.config, src/custodian/rebar.config.script, src/fabric/rebar.config, src/jwtf/rebar.config, src/ken/rebar.config.script, src/mango/rebar.config.script, src/mem3/rebar.config, src/mem3/rebar.config.script, src/rexi/rebar.config, src/smoosh/rebar.config, src/weatherreport/rebar.config
Most of the code editors select syntax highlighting language based on file name extension. However, this approach doesn't work when the extension is not standard. For such cases, there are magic lines. Without the magic lines, files with unknown extensions require extra steps to enable syntax highlighting and auto-completion. This PR adds a magic line for Vim.
Open Emacs or Vim and ensure that it uses Erlang syntax highlighting for `rebar.config*` files.
=> Add editors magic lines

src/couch/src/couch_db.erl
Don't rely on the default gen_server 5 second timeout.
Use `infinity` as that's also effectively used for doc updates.
Fixes https://github.com/apache/couchdb/issues/4142
=> Fix purge request timeouts

src/couch_replicator/test/eunit/couch_replicator_attachments_too_large.erl, src/couch_replicator/test/eunit/couch_replicator_compact_tests.erl, src/couch_replicator/test/eunit/couch_replicator_connection_tests.erl, src/couch_replicator/test/eunit/couch_replicator_create_target_with_options_tests.erl, src/couch_replicator/test/eunit/couch_replicator_error_reporting_tests.erl, src/couch_replicator/test/eunit/couch_replicator_filtered_tests.erl, src/couch_replicator/test/eunit/couch_replicator_httpc_pool_tests.erl, src/couch_replicator/test/eunit/couch_replicator_id_too_long_tests.erl, src/couch_replicator/test/eunit/couch_replicator_large_atts_tests.erl, src/couch_replicator/test/eunit/couch_replicator_many_leaves_tests.erl, src/couch_replicator/test/eunit/couch_replicator_missing_stubs_tests.erl, src/couch_replicator/test/eunit/couch_replicator_proxy_tests.erl, src/couch_replicator/test/eunit/couch_replicator_rate_limiter_tests.erl, src/couch_replicator/test/eunit/couch_replicator_retain_stats_between_job_runs.erl, src/couch_replicator/test/eunit/couch_replicator_selector_tests.erl, src/couch_replicator/test/eunit/couch_replicator_small_max_request_size_target.erl, src/couch_replicator/test/eunit/couch_replicator_test_helper.erl, src/couch_replicator/test/eunit/couch_replicator_use_checkpoints_tests.erl
The main goal is to test the clustered (chttpd/fabric) endpoints instead of the local (backend) versions. This is a more realistic test scenario since that's the API used most often in practice.
Besides switching to chttpd and fabric, also remove the extra cruft left from when we had `local` and `remote` test flavors. After a previous refactoring only the `remote` version remained, but a lot of scaffolding in the form of a parameterized `foreachx` test generators was left behind. 
Also, the majority of replication tests were using a similar set of setup and teardown functions, so those were moved to the common test helper module.
Almost all test modules benefited from the removal of the `?_test(begin...end)` construct and switched to using the `TDEF_FE` macro which makes the test …
=> Refactor replication tests

src/couch_pse_tests/src/cpse_test_ref_counting.erl
Occasionally, this test fails with the following stack trace:
```
cpse_gather: make_test_fun (cpse_incref_decref)...*failed*
in function cpse_test_ref_counting:'-cpse_incref_decref/1-fun-0-'/2 (src/cpse_test_ref_counting.erl, line 44)
in call from cpse_test_ref_counting:cpse_incref_decref/1 (src/cpse_test_ref_counting.erl, line 44)
in call from eunit_proc:run_test/1 (eunit_proc.erl, line 522)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 347)
in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 505)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 447)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 337)
**error:{assert,[{module,cpse_test_ref_counting},
{line,44}, …
```
=> Address race in cpse_incref_decref test

dev/run, rel/overlay/etc/default.ini, rel/overlay/etc/local.ini, src/chttpd/src/chttpd.erl, src/couch/src/couch_httpd.erl, src/couch/src/couch_httpd_auth.erl, src/global_changes/test/eunit/global_changes_hooks_tests.erl
If this gets merged, please also merge https://github.com/apache/couchdb-documentation/pull/753
=> config section for require_valid_user is only [chttpd]

dev/run
In #4153 we missed a "=" in the secret option for the admin party
=> fix missing "=" for admin party in #4153

rel/overlay/etc/default.ini, src/chttpd/test/eunit/chttpd_auth_hash_algorithms_tests.erl, src/couch/src/couch_httpd_auth.erl
Introduce a new config setting `hash_algorithms`.
The values of the new config parameter is a list of comma-separated values of Erlang [hash algorithms](https://www.erlang.org/doc/apps/crypto/algorithm_details.html#hmac).
An example:
```ini
hash_algorithms = sha256, sha, md5
```
This line will use and generate new cookies with the `sha256` hash algorithm and accept/verify cookies with the given hash algorithms `sha` and `md5`.
Closing #4119.
=> Upgrade hash algorithm for cookie auth

src/chttpd/test/eunit/chttpd_auth_hash_algorithms_tests.erl, src/couch/include/couch_db.hrl, src/couch/src/couch_httpd_auth.erl, src/couch/src/couch_util.erl
The test doesn't check if the hash algorithm is supported by the
erlang vm. The test for supported hash algorithms was only missing
in the test itself and not in CouchDB.
Refactor test and verify hash names during test runs.
See https://github.com/apache/couchdb/pull/4140.
=> Refactor hash algorithms test for full CI run

src/chttpd/test/eunit/chttpd_csp_tests.erl, src/chttpd/test/eunit/chttpd_db_attachment_size_tests.erl, src/chttpd/test/eunit/chttpd_delayed_test.erl, src/chttpd/test/eunit/chttpd_session_tests.erl, src/chttpd/test/eunit/chttpd_util_test.erl
OTP 25 generates warnings like the following:
```
src/chttpd/test/eunit/chttpd_util_test.erl:33:48: Warning: variable '_Persist' is already bound. If you mean to ignore this value, use '_' or a different underscore-prefixed name
```
Create an explicit `Persist` variable set `false` to suppress those warnings.
```
make eunit
```
should no longer emit those warnings under OTP 25.
=> Fix variable already bound compiler warnings

rel/overlay/etc/default.ini, src/couch/src/couch_httpd_auth.erl, test/elixir/test/jwt_roles_claim_test.exs
In a JWT token it is possible to add an attribute for role claims. If the roles are presented as top-level attribute like
```json
{
"couchdb-roles": [
"my_role_1",
"my_role_2"
]
}
```
and setting the parameter `roles_claim_name` in the config file to 
```
[jwt_auth]
roles_claim_name = couchdb-roles
```
CouchDB was able to read that attributed and take over that roles.
This doesn't work, if the claim roles are nested, eg:
```
{
"my" :{
"nested": {
"couchdb-roles": [
"my_role_1",
"my_role_2"
]
}
}
}
```
To allow this and for backwards compatibility, a new config parameter `roles_claim_path` is introduced to allow nested role claims. To allow the example from above, yo can use the following syntax:
```
[jwt_auth]
roles_claim_path = my.nested.couchdb-roles
```
If `roles_claim_path` is …
=> Allow and evaluate nested json claim roles

src/couch_replicator/src/couch_replicator_api_wrap.erl, src/couch_replicator/src/couch_replicator_changes_reader.erl, src/couch_replicator/src/couch_replicator_httpc.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_stats.erl, src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_error_reporting_tests.erl, src/couch_replicator/test/eunit/couch_replicator_retain_stats_between_job_runs.erl
By now most of the CouchDB implementations support `_bulk_get`, so let's update the replicator to take advantage of that.
To be backwards compatible assume some endpoints will not support `_bulk_get` and may return either a 500 or 400 error. In that case the replicator will fall back to fetching individual document revisions like it did previously. For additional backward compatibility, and to keep things simple, support only the `application/json` `_bulk_get` response format. (Ideally, we'd send multiple Accept headers with various `q` preference parameters for `json` and `multipart/related` content, then do the right thing based on the response, however, none of the recent Apache CouchDB implementations support that scheme properly).
Since fetching attachments with `application/json` …
=> Implement _bulk_get support for the replicator

src/chttpd/src/chttpd_db.erl
If `_bulk_get` is called with malformed input we crash with a function clause and return a broken http response;
```
curl foo:bar@localhost:15984/db1/_bulk_get -Hcontent-type:application/json -d '{"docs":["doc1"]}'
curl: (56) Illegal or missing hexadecimal sequence in chunked-encoding
{"results": [%
```
This is because `chttp_db:bulk_get_open_doc_revs` only has a clause that matches an object.
Be kinder and send an error message within the `_bulk_get` response, like we do if you send an object but omit the required `id` field;
```
curl foo:bar@localhost:15984/db1/_bulk_get -Hcontent-type:application/json -d '{"docs":[{}]}'
{"results": [{"id": null, "docs": [{"error":{"id":null,"rev":null,"error":"bad_request","reason":"document id missed"}}]}]}
```
With this PR we will send an error like; …
=> return a nice error if non-object passed to _bulk_get

src/chttpd/src/chttpd_node.erl
Show the supported hash algorithms at the node-local _version endpoint:
Example:
```json
curl -s a:a@127.0.0.1:35984/_node/_local/_versions | jq .
{
"javascript_engine": {
"version": "91",
"name": "spidermonkey"
},
"erlang": {
"version": "25.0.4",
"supported_hashes": [
"sha",
"sha224",
"sha256",
"sha384",
"sha512",
"sha3_224",
"sha3_256",
"sha3_384",
"sha3_512",
"blake2b",
"blake2s",
"md4",
"md5",
"ripemd160"
]
},
"collation_driver": {
"name": "libicu",
"library_version": "70.1",
"collator_version": "153.112",
"collation_algorithm_version": "14"
}
}
```
=> Show supported hash algorithms at node-local _version endpoint

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr, src/docs/README.md
We had an inconsistent indent in our `Jenkinsfile`s so reformat them to have a 2 space indent, as that seemed to have been the default mode.
While we are at it, remove a commented out section in `Jenksfile.full` which doesn't apply any longer.
Also fix docs title as mentioned in https://github.com/apache/couchdb/pull/4164#discussion_r965330220
=> A few docs and jenkinsfile cleanups

rel/overlay/etc/default.ini, src/couch_replicator/src/couch_replicator_docs.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_bulk_get_tests.erl, src/docs/src/config/replicator.rst, src/docs/src/json-structure.rst
Let users have the option to revert to the previous behavior. They may have some odd load balancer setup, or a custom API implementation where repeated _bulk_get attempts may cause unexpected issues.
=> Give the users the option to disable bulk_get attempts

src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_revs_diff_tests.erl
When the revisions are consistently missing from the target, for example when replicating to a new target database, it's wasteful to keep calling `_revs_diff`.  Reuse the same algorithm used when skipping calls to `_bulk_get` if there are too many attachments to statistically start skipping calls to `_revs_diff`.
Also use the same record for keeping track of stats so rename `bulk_get_stats` to `fetch_stats`.
The update and attempt functions are re-used as well, there are just separate wrappers which pass in different values for the threshold and other parameters.
=> Statistically skip _revs_diff in the replicator

src/chttpd/src/chttpd_db.erl, src/global_changes/src/global_changes_httpd.erl
At some point when the `stop` callback arg got a 3rd `Pending` element, we forgot to update the eventsource callback. As a result, we ended up in a catch-all clause and we appended an unmatched ']' and a json `"last_seq"` element.
While at it, clean up of the similar upgrade clauses in other callback instances.
=> Fix eventsource change feed

test/elixir/test/changes_async_test.exs, test/elixir/test/config/suite.elixir
`eventsource` events should only ever contain `data`, `id`, `event`, or empty lines
This PR adds a test to ensure that new code/changes will not break this rule
Pull this PR Branch into your local dev env and run the following commands:
```bash
git reset --soft 9fab3868de298b44b931a51d791b1d54bdc3c2ed
git restore --staged src/chttpd/src/chttpd_db.erl
git restore --staged src/global_changes/src/global_changes_httpd.erl
git restore src/chttpd/src/chttpd_db.erl
git restore src/global_changes/src/global_changes_httpd.erl
make
make elixir tests=test/elixir/test/changes_async_test.exs:110
git pull
make
make elixir tests=test/elixir/test/changes_async_test.exs:110
```
#4176 
- [n/a] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`
- [n/a] Documentation changes were …
=> Add test coverage to prevent junk in eventsource

src/couch_replicator/src/couch_replicator_api_wrap.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_utils.erl, src/couch_replicator/test/eunit/couch_replicator_compact_tests.erl
Previously we always encoded the sequence as json. In case of strings, the most common case, this ended up with something like `"\"1-gA..\""`. Then, the endpoints would strip out and ignore the extra `"`. So, avoid sending the extra bytes just so they can be striped out in the end anyway. This should make the logs look a bit cleaner too.
Integers or any other sequences are still json-encoded. Integers will still look like `?since=123` and, in the unlikely we case we replicate with a BigCouch 0.4 era endpoint, the `[SeqNum, OpaqueString]` should be properly encoded as before and replications should work.
This also fixes a minor annoyance when the `_scheduler/{jobs,docs}` results returning the default start sequence as `0` (an integer) even though in the majority of case they'd almost …
=> Don't double-encode changes sequence strings in the replicator

rel/overlay/etc/default.ini, src/docs/src/config/cluster.rst, src/mem3/src/mem3_distribution.erl, src/mem3/src/mem3_sup.erl, src/mem3/src/mem3_sync.erl, src/mem3/src/mem3_sync_event.erl, src/mem3/test/eunit/mem3_distribution_test.erl
Previously, it was possible for the nodes to disconnect and for that state to persist util the nodes restarted. Some fabric requests could reconnect the nodes as a side-effect of sending remote messages, but most of the fabric requests currently start a rexi monitor, which immediately delivers a `rexi_DOWN` message to the coordinator for worker nodes not in the `[node() | nodes()]` list. That happens before `erlang:send/2,3` gets called so there is nothing there to eventually reconnect the nodes.
To avoid relying on random requests reconnecting the cluster, use an explicit monitor process. It does the initial connections, as well as periodically maintains them.
[1] https://github.com/apache/couchdb/blob/main/src/rexi/src/rexi_monitor.erl#L45
=> Explicitly maintain a fully connected cluster

src/docs/src/conf.py, src/docs/templates/pages/download.html
The download page was missing the version part of the template.
Use the RTD version environment [variable](https://docs.readthedocs.io/en/stable/environment-variables.html?highlight=github_version#envvar-READTHEDOCS_VERSION)
=> Fix the documentation download links

src/fabric/src/fabric_doc_open_revs.erl
Use the TDEF_FE macro to save 2 lines per test.
=> Clean up fabric_doc_open_revs tests

src/couch/src/couch_util.erl, src/setup/src/setup.erl, src/setup/src/setup_httpd.erl
In some log messages user passwords were not redacted. 
Examples:
```
[debug] 2022-10-06T18:36:24.615459Z node1@127.0.0.1 <0.659.0> 3f924ac1d2 Enable Cluster: [{node_count,3},{bind_address,<<"0.0.0.0">>},{password,<<"a">>},{username,<<"a">>}]
[debug] 2022-10-06T18:36:24.786483Z node1@127.0.0.1 <0.821.0> 969ca45f27 add node_int: [{name,<<"node2">>},{port,25984},{host,<<"127.0.0.1">>},{password,<<"a">>},{username,<<"a">>}]
[notice] 2022-10-06T18:36:26.778453Z node1@127.0.0.1 <0.840.0> ff4625a79a Setup: [{<<"action">>,<<"add_node">>},{<<"host">>,<<"127.0.0.1">>},{<<"port">>,35984},{<<"name">>,<<"node3">>},{<<"username">>,<<"a">>},{<<"password">>,<<"****">>}]
```
Move and introduce a global helper function `remove_sensitive_data` to redact passwords.
=> Redact passwords in log file

src/ddoc_cache/test/eunit/ddoc_cache_lru_test.erl
This failure seems to occur from a race between meck:wait and the test runner:
```
ddoc_cache_tutil:109: -with/1-fun-1- (check_cache_refill)...*failed*
in function ddoc_cache_lru_test:check_cache_refill/1 (test/eunit/ddoc_cache_lru_test.erl, line 205) in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71) in call from eunit_proc:run_test/1 (eunit_proc.erl, line 531) in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 356) in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 514) in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 456) in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 346) in call from eunit_proc:run_group/2 (eunit_proc.erl, line 570) **error:{assertEqual,[{module,ddoc_cache_lru_test},
{line,205},
{expression,"ets : info ( ? …
```
=> Wait for race in ddoc cache lru test

src/jwtf/test/jwtf_keystore_tests.erl
These tests emit a lot of unnecessary noise because they start the `couch_log` application without also starting `folsom`:
```
❯ make eunit apps=jwtf suites=jwtf_keystore_tests
==> jwtf (compile)
==> rel (compile)
==> couchdb (compile)
WARN:  Missing plugins: [pc]
WARN:  Missing plugins: [covertool]
==> couchdb (setup_eunit)
==> jwtf (eunit)
======================== EUnit ======================== module 'jwtf_keystore_tests'
[notice] 2022-10-11T19:01:50.047710Z nonode@nohost <0.190.0> -------- config: [jwt_keys] hmac:hmac set to aGVsbG8= for reason nil [error] 2022-10-11T19:01:50.047718Z nonode@nohost <0.190.0> -------- unknown metric: [couch_log,level,notice] [error] 2022-10-11T19:01:50.068427Z nonode@nohost <0.190.0> -------- unknown metric: [couch_log,level,notice] [notice] …
```
=> Quiet jwtf keystore test noise

src/couch_prometheus/test/eunit/couch_prometheus_e2e_tests.erl
These tests currently pass without this config parameter being set because it gets that configuration from a test template. However, this is fragile, and it's better practice to keep everything in one place.
This makes the configuration explicit.
```
make eunit apps=couch_prometheus suites=couch_prometheus_e2e_tests
```
=> Make test prometheus port explicit

src/fabric/src/fabric.erl, src/fabric/src/fabric_open_revs.erl, src/fabric/test/eunit/fabric_open_revs_test.erl
`fabric:open_revs/3` is the batched counterpart to `fabric:open_revs/4`.
Instead of fetching revisions for only one document, like `fabric:open_revs/4`,
it can fetch batches of document revisions. The main optimization is achieved
by grouping documents by shard ranges and then spawning shard workers only once
for each range (essentially doing what fabric:update_docs/2,3 does).
The idea is to use this implementation for a more efficient version of _bulk_get.
So far this is just the fabric API, not plugged into the HTTP API yet.
The backend API for this is already available as implemented in
https://github.com/apache/couchdb/pull/4185.
While the implementation is intended to be as close as possible to
`fabric:open_revs/4` there a key difference -- since we're now dealing with
potentially …
=> Implement fabric:open_revs/3

src/docs/src/config/auth.rst
Add missing configuration option to the 3.2.2 docs.
=> Backport missing `roles_claim_name` to 3.2.2-docs

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_auth_request.erl, src/chttpd/test/eunit/chttpd_dbs_info_test.erl, src/docs/src/config/http.rst
We missed that in the 3.x versions up until now.
Also some documentation around it with version history.
Fixes #4253
=> Make sure admin_only_all_dbs applies to _dbs_info as well

src/couch/src/couch_db_updater.erl
Previously it used both leaf and intermediate nodes.
With this PR active db size should decrease when users delete documents. This, in turn, should make smoosh enqueue those dbs for compaction to recover the disk space used by the now deleted document bodies. Previously, it was possible for users to delete gigabytes worth of document bodies and smoosh never noticing and never triggering the compaction.
Original idea and patch provided by Robert Newson in CouchDB dev Slack discussion channel.
Co-authored-by: Robert Newson
Fixes: https://github.com/apache/couchdb/issues/4263
=> Update active db size calculation to use only leaf nodes

src/mem3/src/mem3_reshard_index.erl, src/mem3/src/mem3_reshard_job.erl
Db shard copy uses `db_compact` priority and view building uses `view_compact` priority to avoid inventing new priority levels.
=> Use compaction ioq priority for shard splitting

src/couch/src/couch_db.erl
Improve purge client cleanup logging
* Refactor lag logging to a separate function.
* When purge client validity throws an error log the error as well.
* Use the newer `erlang:system_time(second)` call to get time.
* When warning about update lag, log both the lag and the limit.
* Add a specific log message if update timestamp is invalid.
* Clarify that an invalid checkpoint is not always because of a malformed
checkpoint document. The most likely case is it's a stale view client
checkpoint which hasn't been cleaned up properly.
Fix: #4181
=> Improve purge client cleanup logging

src/chttpd/test/eunit/chttpd_dbs_info_test.erl
This test can time out with the following stack trace because [ibrowse sends {error, retry_later} under certain conditions](url) [1] which causes test_request:request/6 to sleep and retry [2], which can result in this failure:
```
chttpd_dbs_info_test:79: -dbs_info_test_/0-fun-20- (should_return_500_time_out_when_time_is_not_enough_for_get_dbs_info)...*timed out*
in function timer:sleep/1 (timer.erl, line 219)
in call from test_request:request/6 (src/test_request.erl, line 106) in call from chttpd_dbs_info_test:should_return_500_time_out_when_time_is_not_enough_for_get_dbs_info/1 (test/eunit/chttpd_dbs_info_test.erl, line 157) in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71) in call from eunit_proc:run_test/1 (eunit_proc.erl, line 531) in call from eunit_proc:with_timeout/3 …
```
=> Improve flaky dbs info test

src/couch/rebar.config.script
add `LDFLAGS` and `CFLAGS` environment variables to `IcuEnv` in rebar config to be able to configure ICU includes and object paths via environment variable without having to patch `rebar.config.script`.
=> chore: configurable ICU locations

rel/overlay/etc/default.ini, rel/overlay/etc/local.ini
Adjust configuration files to improve readability.
The default config files have a mix of different definition of config keys. Some lines start with
`;"WHITESPACE"config-key =`, some with (which should the default) `;config-key =`.
Adjust all config keys to use the same pattern (semi-colon w/o ws): ";key = value"
Adjust comments (semi-colon with ws): "; My comment description"
Added new-line between description and config key, if config-key has a description
=> Format config files to improve readability

src/couch_event/src/couch_event_listener.erl, src/couch_replicator/src/couch_replicator_pg.erl, src/couch_replicator/src/couch_replicator_scheduler_job.erl, src/couch_replicator/src/couch_replicator_sup.erl, src/couch_replicator/test/eunit/couch_replicator_error_reporting_tests.erl, src/couch_replicator/test/eunit/couch_replicator_test_helper.erl
Global has a tendency to create deadlocks [1], and when that happens replication jobs can't start on any of the nodes in the cluster.
We don't really need strict consistent locking for replication jobs. It's mostly to avoid replication jobs thrashing the same checkpoint docs back and forth between different session IDs. So, remove global to avoid any issues around it, and replace it with `pg` -- the new (Erlang 23+) process group implementation. (Technically `global` is still running in the runtime system as it's started by the `kernel` app. We just avoid interacting with it and registering any names to avoid deadlocks).
In `pg` we start a replication `scope`, and then in that scope make every RepId a process `group`. When replication processes spawn, their Pids becomes `members` of that …
=> Remove all usage of global

src/smoosh/test/smoosh_tests.erl
Saw this fail 2 in a the last week or so but couldn't reproduce it locally. Instead of deleting, this is an attempt to emit debug lines to see how far it goes before it times out in the CI.
=> Add debug logs to smoosh test

rel/overlay/etc/default.ini, src/config/src/config.erl, src/docs/src/api/server/authn.rst, src/docs/src/config/intro.rst
They are allowed only for the "k = v" format and not the "k=v" format. The idea is to split on " = " first, and if that fails to produce a valid kv pair we split on "=" as before.
To implement it, simplify the parsing logic and remove the undocumented multi-line config value feature. The continuation syntax is not documented anywhere and not used by our default.ini or in documentation.
Fix: #3319
=> Allow = in config key names

src/couch/src/couch_server.erl
While the variable `RelativeFileName` is not really unbound in the case-statement, use a 
more up-to-date pattern for binding the value.
=> Fix unbound variable warning

rel/overlay/etc/vm.args
It's already false in 23 and 24 but will start to be enabled in 25+. We don't rely on global for process registration any more, and have our own auto-connection module. So we don't want to be caught by surprise in Erlang 25+ since there is some additional coordination and resource usage needed when this option is true. See https://github.com/erlang/otp/issues/6470 for an example.
=> Ensure prevent_overlapping_partitions stays false in Erlang 25+

src/docs/src/replication/replicator.rst
Documentation was mentioning the exponential backoff on `Crashing` and `Error` states, but did not mention how to configure it. This commit adds note on relation of `max_history` and maximum backoff with link to appropriate configuration section.
I (hopefully correctly) assumed that `replicator.max_history` affects not only `Crashing` state, but also `Error` state as well.
#4299
=> Add note on how to configure replicaton backoff (#4299)

src/docs/src/api/server/authn.rst
Fixed wrong rendering of an inline literal with whitespaces. 
Use `:literal` as workaround, with escaping whitespaces `\ ` and added non-breakable-whitespace char (U+00A0)
Before commit:
After commit:
=> Fix rendering of inline literal with withespaces

src/chttpd/src/chttpd.erl
It's a deprecated feature but we want to make sure it still works.
Possible fix for: https://github.com/apache/couchdb/issues/4313
=> Ensure we use the chttpd vs httpd section in fix_uri

Makefile, Makefile.win, build-aux/Jenkinsfile.pr, build-aux/couchdb-build-release.sh
At some point it broke - it looks like rebar3, erlfmt and python-black usage ended up needing the network to install/update themselves.
Make sure rebar3 and erlfmt is in bin/ alongside rebar, and make python-black is in a separate source formatting stage step in CI and remove it from `make check`.
=> Return back to allowing offline configure and make release

rebar.config.script
Latest jiffy apparently is blocking windows builds so for now let's revert to the previous version. The previous version didn't quite work right off the bat as enc doesn't load on Erlang 25 any longer. So there is a new 1.0.9-2 release wiht enc rebuilt on Erlang 23.
=> Revert jiffy to CouchDB-1.0.9-2 to unblock the 3.3 release

Makefile
Instead of having it download its own every time
Another step toward being able to run `make check` on the dist output without a network
This saves some time and is a bit closer to the goal. 
The next hurdle is to do the same for hex. Hex it a bit trickier, since we don't have an explicit clone, it just auto-installs itself whenever. During configure we'd have to treat it like rebar3 -- fetch, recompile locally, stash it in `hex/hex.ez`. Then, `make dist` would copy that over to the dist tarball, and during `make check` we'd install it from that archive `mix archive.install ./hex/hex.ez`)
Related to: https://github.com/apache/couchdb/issues/4312
=> Reuse installed rebar and rebar3 for mix

configure.ps1
Write the standard relax message after configure to the standard output and not as "verbose" message.
=> Write relax-message to standard output on Windows

.gitignore
Ignore build Windows binaries to prevent an accidental check-in into source control.
=> Ignore built win binaries

Makefile, build-aux/Jenkinsfile.pr, mix.exs
This is to help unblock 3.3 windows build so make check doesn't choke on re-formatting elixir files for Windows.
=> Move elixir source checks to a separate step

.gitignore
Ignore Object-Files (*.obj) too.
=> Ignore built win binaries 2

test/elixir/lib/couch/dbtest.ex, test/elixir/test/security_validation_test.exs
Adding full url to database names when replicating.
=> Fix {eaddrnotavail} in elixir tests under Windows

src/docs/src/intro/security.rst
This updates the [Authorization documentation](http://localhost:8001/_utils/docs/intro/security.html#authorization) to reflect the change to the default value of [`default_security`](http://localhost:8001/_utils/docs/config/couchdb.html#couchdb/default_security).
This existing documentation is misleading especially for people who are just starting out (me! ✋🏽 ) and wondering why a normal user can't add a document to a database.
=> Fix documentation to reflect default_security change

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
Update all 23,24,25 to latest patch versions
Use 24 as a base for the full CI run
=> Update Erlang versions

src/couch_replicator/src/couch_replicator_parse.erl
Closes https://github.com/apache/couchdb/issues/4344
=> fix undef when parsing replication doc body

src/couch_replicator/src/couch_replicator_parse.erl
This adds a test to cover the case when a replication doc contains a user_ctx, and subsequently executes `get_json_value/3`.
See: https://github.com/apache/couchdb/pull/4343
```
make eunit apps=couch_replicator suites=couch_replicator_parse
```
should show all lines of `rep_user_ctx/1` are covered.
=> Add test coverage for replicator user_ctx parser

Makefile, rebar.config.script
some false positives for hastings (part of geo feature not present in couchdb core) but the rest need fixin'
=> add find_bugs makefile target for undefined functions

build-aux/Jenkinsfile.full
Just make it use the Erlang 24 version like all the other images
=> Fix Ubuntu Jammy CI image reference

configure.ps1
Add Prometheus port to ./configure.ps1 to catch up with ./configure
=> Add Prometheus port to Windows couchdb.config

src/docs/ext/configdomain.py
To correctly generate the configuration reference html output, escape special html characters like '<' and '>' in section names.
Before PR:
```
<a href="#cap-smoosh.<channel>"><strong>smoosh.<channel></strong></a>
```
and
```
<tr class="cap" id="cap-smoosh.<channel>"><td></td><td>
<strong>smoosh.<channel></strong></td><td></td></tr>
```
After PR:
```
<a href="#cap-smoosh.&lt;channel&gt;"><strong>smoosh.&lt;channel&gt;</strong></a>
```
and
```
<tr class="cap" id="cap-smoosh.&lt;channel&gt;"><td></td><td>
<strong>smoosh.&lt;channel&gt;</strong></td><td></td></tr>
```
=> Escape special (html) chars in section names

src/docs/ext/configdomain.py
To correctly generate the configuration reference html output, escape special html characters like '<' and '>' in section names.
=> [BP/3.2.2-docs] Escape special (html) chars in section names (#4350)

src/docs/ext/configdomain.py
To correctly generate the configuration reference html output,
escape special html characters like '<' and '>' in section names.
=> [BP/3.3.x/] Escape special (html) chars in section names (#4350)

src/chttpd/test/eunit/chttpd_dbs_info_test.erl
With more recent OTP versions, this test has been observed to fail with the following error:
```
chttpd_dbs_info_test:88: -dbs_info_test_/0-fun-22- (should_return_500_time_out_when_time_is_not_enough_for_get_dbs_info)...*failed*
in function chttpd_dbs_info_test:should_return_500_time_out_when_time_is_not_enough_for_get_dbs_info/1 (test/eunit/chttpd_dbs_info_test.erl, line 192) in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71) in call from eunit_proc:run_test/1 (eunit_proc.erl, line 531) in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 356) in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 514) in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 456) in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 346) in call from …
```
=> Wait for dbs_info 500 timeout error

Makefile
CouchDB build fails at elixir tests initialization when Elixir 1.14 is used.
Following error stops the build when any Makefile target that depends on `elixir-init` is executed.
```
** (Mix) Invalid arguments given to mix local.rebar: ["rebar", "./bin/rebar"]. To find out the proper call syntax run "mix help local.rebar"
```
Elixir 1.14 removes support for Rebar 2 which produces the error as we are initializing  Rebar 2 and Rebar 3 for test execution. 
This PR removes Rebar 2 initialization from `elixit-init` target enabling support for Elixir 1.14 in the build process. 
Windows build seems not to be affected by the same problem as it is not forcing Rebar 2 initialization, but I have not tested it. 
- Install Elixir 1.14
- Run 'make couch elixir'
None
=> Remove Rebar2 initialization for elixir tests as it is not longer supported by elixir 1.14

src/couch_replicator/src/couch_replicator_httpd_util.erl, src/couch_replicator/test/eunit/couch_replicator_scheduler_docs_tests.erl
The total_rows property was decremented by one to account for the VDU that was automatically added to the total. Now that a BDU has replaced the VDU [1] total_rows is one less than it should be.
This removes the decrement so that total_rows equals the actual doc count.
[1] https://github.com/apache/couchdb/pull/4274
```
make eunit apps=couch_replicator suites=couch_replicator_scheduler_docs_tests
```
=> Fix replication _scheduler/docs total_rows

src/couch_replicator/src/couch_replicator_worker.erl, src/couch_replicator/test/eunit/couch_replicator_bulk_get_tests.erl
Previously, when replication jobs used _bulk_get they didn't upload design docs individually like they do when not using _bulk_get.
Here were are preserving an already existing behavior which we had in the replicator without _bulk_get usage for more than 2 years. It was introduced here in https://github.com/apache/couchdb/pull/2426. Related to these issues https://github.com/apache/couchdb/issues/2415 and https://github.com/apache/couchdb/issues/2413.
Add tests to cover both attachments and ddoc cases. meck:num_calls/3 is helpful as it allows to nicely assert which API function was called and how many times.
=> Ensure design docs are uploaded individually when replicating with bulk_get

src/docs/src/api/database/find.rst, src/mango/README.md
The remainder argument for the `$mod` operator can be zero, while its documentation suggests otherwise.  It actually covers a very realistic use case where divisibility is expressed.
[Neither related restrictions could be identified in the sources](https://github.com/apache/couchdb/blob/adf17140e81d0b74f2b2ecdea48fc4f702832eaf/src/mango/src/mango_selector.erl#L512:L513) [nor MongoDB forbids this](https://www.mongodb.com/docs/manual/reference/operator/query/mod/).  Tests also seem to exercise [this specific case](https://github.com/apache/couchdb/blob/0059b8f90e58e10b199a4b768a06a762d12a30d3/src/mango/test/03-operator-test.py#L58).  Thanks @iilyak for checking on these.
Tasks:
=> docs(mango): match description of `$mod` with reality

Makefile.win
Backporting the `build-report` target from the *nix makefile to the Windows pendant.
Run this on Windows:
```
PS C:\relax\couchdb> make -f Makefile.win build-report
```
```
PS C:\relax\couchdb> cat .\test-results.log
Skipped
=======
EXUnit - AuthCacheTest - AuthCacheTest - test auth cache management: due to pending filter
EXUnit - BasicsTest - BasicsTest - test On restart, a request for creating an already existing db can not override: due to pending filter
EXUnit - BasicsTest - BasicsTest - test PUT doc has a Location header: due to pending filter
EXUnit - BasicsTest - BasicsTest - test Regression test for COUCHDB-954: due to pending filter
EXUnit - CompactTest - CompactTest - test compaction reduces size of deleted docs: due to pending filter
EXUnit - ConfigTest - ConfigTest - test …
```
=> Adding build-report makefile target on Windows

rebar.config.script
Changes since 2.5.2: https://github.com/ferd/recon/compare/2.5.2...2.5.3
=> Bump recon to 2.5.3

src/docs/src/api/database/find.rst, src/mango/README.md
Backport of aff7a6e7183e6c471a9675e37216baa0bad563a3.
=> docs(mango): match description of `$mod` with reality (3.3.x)

src/docs/src/api/database/find.rst, src/mango/README.md
Backport of aff7a6e7183e6c471a9675e37216baa0bad563a3.
=> docs(mango): match description of `$mod` with reality (3.2.2)

build-aux/Jenkinsfile.full
=> ci(mac): re-enable mac CI for the full build

src/mango/src/mango_cursor_view.erl, src/mango/src/mango_selector.erl
This PR aims to improve Mango by reducing the data transferred to
the coordinator during query execution. It may reduce memory or CPU use
at the coordinator but that isn't the primary goal.
Currently, when documents are read at the shard level, they are compared
locally at the shard with the selector to ensure they match before they
are sent to the coordinator. This ensures we're not sending documents
across the network that the coordinator immediately discards, saving
bandwidth and coordinator processing. This PR further executes field
projection (`fields` in the query) at the shard level. This should
further save bandwidth, particularly for queries that project few fields
from large documents.
One item of complexity is that a query may request a quorum read of
documents, meaning that we …
=> Mango fields pushdown

Makefile.win
- backport dynamic environment variables to Makefile.win
- return exit code 1 if EUnit test fail
- fixes some path issues
It's now possible to run only specific EUnit test instead of running the full apps suite:
```
make -f Makefile.win eunit apps=chttpd suites=chttpd_security_tests
```
Return the exit code 1, if a test fails that the CI will fail too.
=> Allow to run only specific EUnit tests on Windows

rel/overlay/etc/default.ini, src/chttpd/test/eunit/chttpd_changes_test.erl, src/couch/src/couch_changes.erl, src/fabric/src/fabric_rpc.erl
It turns out `changes_doc_ids_optimization_threshold` limit has never been applied for the clustered changes feeds. So it was effectively unlimited. This commit enables it, and also adds tests to ensure the limit works.
Since we didn't have a good Erlang integration test suite for clustered changes feeds, which allowed this case to slip through the cracks, add a few more tests along the way to test the majority of parameter combinations which might interact: sharding single shards vs multiple, continuous vs normal, reverse, row limits etc.
The previous limit was 100, but since it was never actually applied it's equivalent not having one at all, so let's pick a new one. I chose 1000 noticing that at Cloudant, close to 3000 we had fabric timeouts on a busy cluster, so that seemed too high. …
=> Enforce docs ids _changes filter optimization limit

src/dreyfus/src/dreyfus_httpd.erl
Send an immediate 503 error if a request requiring search is made when search is not available.
This avoids creating processes that will certainly fail but also improves couchdb's handling when search (meaning the clouseau jvm) is deliberately not set up.
Without this change it is possible to crash couchdb if you make `_search` (or `_search_info` / `_search_analyze`) requests at sufficient intensity to crash supervisors.
=> 503 if search not available

configure, configure.ps1, src/couch/rebar.config.script
The `configure` script does not check whether SpiderMonkey actually exists at the presumed location.  This may go wrong when the user has a version different from the default one.  The mistake is spotted only in build time, indirectly, via missing header files.  That is too late and it may not be evident for the user what the problem is.
Add a user-friendly safeguard to prevent this from happening.
=> chore(configure): be more defensive about SpiderMonkey location

configure, configure.ps1, src/couch/rebar.config.script
=> chore(configure): be more defensive about SpiderMonkey location (3.3.x)

INSTALL.Unix.md, build-aux/show-test-results.py, dev/run, src/docs/ext/configdomain.py, src/mango/test/06-text-default-field-test.py, src/mango/test/07-text-custom-field-list-test.py, src/mango/test/user_docs.py
This change aims to correct the Unix installation instructions in different ways:
- Note that a too new version of the Erlang OTP can cause build problems.
- On recent macOS systems, the `xcode-select --install` command will install a version of Python 3, along with `pip3`, hence there is no need to do that explicitly.
- Sphinx and the respective theme are installed locally via `venv` for building the documentation, so users should only provide a working Python 3 environment (thanks @nickva for mentioning this).
- Fix markdown of file and command names.
=> docs(INSTALL.Unix): update instructions

src/couch_replicator/src/couch_replicator_docs.erl, src/couch_replicator/test/eunit/couch_replicator_scheduler_docs_tests.erl, src/couch_replicator/test/eunit/couch_replicator_test_helper.erl
During the VDU -> BDU update we inadvertently blocked _local doc writes to _replicator dbs. This commit rectifies that.
Add tests for _local, _design, and regular malformed docs for both the default _replicator db as well for for the prefixed version like $db/_replicator. For completeness, update the _scheduler/docs counts test also test both cases.
=> Allow _local doc writes to the replicator dbs

README-DEV.rst
The JavaScript-based integration test suites are still referenced by the developer documentation which can create confusions.  Remove those references and mention that other ones that have been added to the `Makefile` in the meantime.
=> docs: update developer instructions

rel/overlay/etc/default.ini
Moving some top-level settings into the top-level section
to prevent an accidential setup (if enabled) in the wrong 
section (smoosh.slack_views).
=> Reorder top-level smoosh-settings to the correct section

src/mango/src/mango_cursor_special.erl, src/mango/src/mango_cursor_view.erl
Per #4413, increase the unit test coverage for the Mango JSON index selection function.  Besides that, this PR:
- introduces a type specification for the function,
- brings the assumed behavior explained in the comments in sync with the implementation,
- removes all the unused parts.
Brief code coverage stats (`make eunit apps=mango`) -- before:
```
Code Coverage:
[..]
mango_cursor_view     :  20%
[..]
Total                 : 15%
```
after:
```
module 'mango_cursor_view'
[..]
mango_cursor_view: choose_best_index_with_singleton_test...ok
mango_cursor_view: choose_best_index_lowest_difference_test...ok
mango_cursor_view: choose_best_index_least_number_of_fields_test...ok
mango_cursor_view: …
```
=> mango: JSON index selection cleanup & unit tests

src/mango/src/mango_cursor_view.erl
Comparators are not represented by binary strings in the selection ranges, captured by the `range/0` type.  Although that is how they are coming from the corresponding parsed JSON object, they are being translated to specific atoms on the fly.  Thanks for @nickva noticing this!
=> fix(mango): fix specification of `choose_best_index/1`

README-DEV.rst
This is a documentation follow-up for #4425.
=> docs(`README-DEV`): chase rename of `dreyfus-test` to `elixir-search`

Makefile, Makefile.win, README-DEV.rst
The `help` `make(1)` target is a very useful tool but it is not used consistently throughout the `Makefile` and this should be corrected.  In relation to that, fix typos and bugs in the different targets and their help descriptions in order to restore them.
As a bonus, port some of the missing functionalities to the Windows version of the `Makefile` and bring the targets there in sync with that of its sibling.
=> chore: clean up Makefiles

src/couch/src/couch_httpd_auth.erl, src/docs/src/api/server/authn.rst, src/docs/src/config/auth.rst, test/elixir/test/jwt_roles_claim_test.exs
Now it is possible to define a JWT roles claim as a comma-seperated list or as a JSON array of strings (the only allowed old behavior).
In your JWT token you had to use a JSON array of strings:
```json
{
"_couchdb.roles": ["accounting-role", "view-role"]
}
```
Now you can use a comma-seperated list too:
```json
{
"_couchdb.roles": "accounting-role, view-role"
}
```
=> Allow definition of JWT roles claim as comma-seperated list

src/docs/src/config/auth.rst, src/docs/src/config/compaction.rst, src/docs/src/maintenance/compaction.rst, src/docs/src/whatsnew/2.3.rst, src/docs/src/whatsnew/3.2.rst, src/docs/src/whatsnew/3.3.rst, src/smoosh/operator_guide.md
The pattern `{var}` has been established to clarify dynamic parameters in the documentation. 
Standardization and clarification of some not yet converted notation of parameters.
=> Unifying the notation of dynamic parameters in the docs

rel/overlay/etc/default.ini
Fix typo: paritioned -> partitioned
=> Fix typo in "feature_flags" section comment

src/chttpd/test/eunit/chttpd_auth_tests.erl, src/couch/src/couch_httpd_auth.erl, src/docs/src/api/server/authn.rst, src/docs/src/config/auth.rst
Proxy auth can now use one of the configured hash algorithms
from chttpd_auth/hash_algorithms to decode authentication tokens.
Start CouchDB with the following additional config:
```
;Start ProxyAuth Test
[chttpd]
authentication_handlers = {chttpd_auth, proxy_authentication_handler}, {chttpd_auth, default_authentication_handler}
[chttpd_auth]
proxy_use_secret = true
secret = the_secret
hash_algorithms = sha256, sha
;End ProxyAuth Test
```
```
CouchDB (sha1;working) = fc4a82fd0c313c1e95ba60b6fd4c769f3f9e230d
CouchDB (sha256;working) = 4441087d94449b0a5e58cd593cfb14341637b120c90884389d9747e93c2463cf
CouchDB (md5;failing) = 3493e0a670bb83ebcdd3fc6201e54fd2
```
```
curl -L 'http://localhost:15984/_session' -H 'X-Auth-CouchDB-UserName: CouchDB' -H 'X-Auth-CouchDB-Roles: PROXY-USER-ROLE' -H …
```
=> Upgrade hash algorithm for proxy auth

src/docs/src/api/server/authn.rst, src/docs/src/cluster/purging.rst, src/docs/src/config/replicator.rst
The pattern {var} has been established to clarify dynamic parameters in the documentation. Standardization and clarification of some not yet converted notation of parameters.
=> Unifying the notation of dynamic parameters in the docs 2

src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_local_docs_tests.erl, src/couch_mrview/src/couch_mrview.erl, src/docs/src/cluster/purging.rst
It hides the shard-sync and purge documents from the response unless a `?include_system=true` is given.
Currently the system docs are included in `_local_docs`. This has shown to confuse users, and they try to delete them, which might fail and/or lead to problems.
```
curl -X PUT http://admin:admin@127.0.0.1:15984/test-db
curl -X PUT http://admin:admin@127.0.0.1:15984/test-db/doc -d '{"a":1}'
curl -X POST http://admin:admin@127.0.0.1:15984/test-db/_purge -d '{"doc":["1-23202479633c2b380f79507a776743d5"]}' -Hcontent-type:application/json
sleep 5
curl http://admin:admin@127.0.0.1:15984/test-db/_local_docs
curl http://admin:admin@127.0.0.1:15984/test-db/_local_docs?include_system=true
```
- #3930
I think most of this is not applicable. Regarding tests, I'm not sure if there should be added …
=> hide shard-sync and purge documents from `_local_docs`

src/couch_log/src/couch_log_writer_file.erl
While investigating issues in my deployment around logrotate I discovered the file logger last_check doesn't appear to be updated after init is called, this could result in maybe_reopen being called with every log write 30 seconds after init is called. The fix works as the documentation specifies, but I wasn't able to measure a meaningful performance harm from the previous functionality. Throwing it up in case it's desirable.
With the fix observe it can take up to 30 seconds from the last check before the log is recreated after deletion. Without the fix the log gets recreated much more quickly.
=> Update last_check in file logger record

rel/overlay/etc/vm.args, src/config/src/config.erl, src/config/test/config_tests.erl, src/couch/src/couch_hash.erl, src/couch/src/couch_server.erl, src/couch/test/eunit/couch_hash_test.erl
This enables configuring FIPS mode at runtime without the need for a custom build.
Use a persistent term for this, and all other features. This should allow quick feature checks [1]
[1] Silly benchmark shows about a 0.3 microsecond overhead
```
(node1@127.0.0.1)32> element(1, timer:tc(fun() -> (fun F(0) -> ok; F(N) -> ok, F(N-1) end)(1000000) end)) / 1000000.
0.574429
(node1@127.0.0.1)33> element(1, timer:tc(fun() -> (fun F(0) -> ok; F(N) -> config:is_enabled(fips), F(N-1) end)(1000000) end)) / 1000000.
0.783567
```
Issue: #4442
=> Enable FIPS mode at runtime

rel/overlay/etc/default.ini, src/couch_prometheus/src/couch_prometheus_server.erl, src/couch_prometheus/test/eunit/couch_prometheus_e2e_tests.erl
Interval was not read from the correct section.
The tests had the correct section.
This should fix the prometheus flaky test [1]. This was apparent on MacOS a bit more. The interval in the test was still 5 seconds instead of 1, so it was right at the edge of timing out (5 seconds is the default eunit timeout).
[1] https://github.com/apache/couchdb/issues/4397#issuecomment-1425027913
=> Fix bad prometheus section name

src/ets_lru/test/ets_lru_test.erl
Try to fix flaky test which was noticed on the MacOS CI worker [1]:
```
[2023-02-17T07:40:34.978Z]     ets_lru_test:285: -test_limits/2-fun-7- (Expire leaves new entries)...ok
[2023-02-17T07:40:34.978Z]     ets_lru_test:292: -test_limits/2-fun-5- (Entry was expired)...*failed*
[2023-02-17T07:40:34.978Z] in function ets_lru_test:'-test_limits/2-fun-5-'/2 (test/ets_lru_test.erl, line 294)
```
[1] https://github.com/apache/couchdb/issues/4397#issuecomment-1434764920
=> Fix flaky LRU test

test/elixir/test/users_db_test.exs
This fails more often on MacOS CI workers [1] but it seems to be a general flaky test as the users auth ddoc is not guaranteed to be inserted synchronously.
[1] https://github.com/apache/couchdb/issues/4397#issue-1551336429
=> Fix flaky elixir users_db_tests

src/docs/src/api/server/common.rst, src/docs/src/intro/api.rst, src/docs/src/replication/conflicts.rst, src/docs/src/replication/replicator.rst
When using replication, we need to specify a username and password (`adm:pass` / `admin:password`) for the replication endpoint URL, otherwise a 401 unauthorized error will be thrown.
Fix https://github.com/apache/couchdb/issues/4127
=> Documentation: Add `adm:pass` to replication endpoint URL

Makefile, Makefile.win, README-DEV.rst
- Add `python-black-update` for `make help`.
- In the output of `make help`, diffentiate between Erlang and Python source code checks.
- Include the use of `black` in the developer documentation.
- Hide `erlfmt` commands for the respective targets.  This makes the targets consistent with their Windows versions.
=> docs(`Makefile`): improve documentation of source code format checks

src/docs/src/api/database/find.rst
While reading the documentation, noticed a couple of problems with the HTML version, of which this change covers:
- Parameter types for JSON objects are not uniform.  The type `json` could either ambigiously refer to objects or arrays and used randomly.
- The `Content-Type` header for response descriptions is not always put in a list, though probably that is the right choice because there can be many.
- Indentation of paragraphs and list items is off sometimes which causes rendering mistakes.
- Formatting of JSON examples is not uniform by indentation.
- Add a couple of missed markdown for names, such as operators, to make them stand out from the text for better readability.
- Unify style: use colons for the sentences that introduce examples, end sentences with full stops, lose …
=> docs(`_find`): tweak formatting and style

Makefile.win, dev/format_lib.py
The erlfmt executable likes POSIX paths on Windows too.
Fixes #4333.
=> Fix erlfmt-format on Windows

src/couch/src/test_util.erl, src/mango/src/mango.hrl, src/mango/src/mango_idx_text.erl, src/mango/src/mango_selector_text.erl, src/mango/test/05-index-selection-test.py, src/mango/test/16-index-selectors-test.py
Upon adding a text index, Mango queries may not return documents that should match a selector that contains the `$regex` operator.  Steps to reproduce (thanks to @willholley), that are also captured in the integration tests:
1. Create an empty database. 
2. Add a document:
```json
{ 
"_id": "foo",
"currency": "HUF",
"location": "EUROPE"
}
```
3. Run a Mango query without indexes -- this should return the document above:
```json
{
"selector": {
"currency": {
"$regex": "HUF"
}
}
}
```
4. Add a text index for `location`:
```json
{
"index": {
"fields": [
{
"name": "location",
"type": "string"
}
]
},
"name": "location-text",
"type": "text"
}
```
5. Run the query once more -- this time, no documents are returned.
This is because the text index is chosen to answer the query even if it does not …
=> mango: correct text index selection for queries with `$regex`

src/fabric/src/fabric.erl
There are some document comments in `fabric` that point to the old CouchDB wiki.  The featured links are not working any more (possibly lost during the migration), although one could still find them e.g. through the [Wayback Machine](https://web.archive.org/web/20161002083018/http://wiki.apache.org/couchdb/HTTP_view_API).  On Slack, @nickva suggested that including explicit links in the comments is not a good practice anyway, hence this proposal to remove completely.
=> chore: remove stale links from documentation comments

src/couch_prometheus/src/couch_prometheus_server.erl, src/couch_prometheus/test/eunit/couch_prometheus_e2e_tests.erl
The `_node/_local/_prometheus` was returning duplicate rows for the following metrics:
```
couchdb_erlang_memory_bytes
couchdb_erlang_gc_collections_total
couchdb_erlang_gc_words_reclaimed_total
couchdb_erlang_context_switches_total
couchdb_erlang_reductions_total
couchdb_erlang_processes
couchdb_erlang_process_limit
```
Prometheus will gracefully handle the duplication, picking the first entry only, but the duplication bloats the output and can cause some confusion when manually reading the response to get the list of metrics.
This fix is to remove a duplicate call to `get_vm_stats()` in the prometheus endpoint handler.
I added a unit test for duplicate metrics in `couch_prometheus`. This fails prior to the fix and now passes, though my Erlang is likely a bit clunky!
One can also observe …
=> fix: remove duplicate couchdb_erlang* stats from _prometheus

share/server/filter.js, share/server/loop.js, share/server/util.js
Filter view functions feature re-uses view map function for filtering _changes feeds. Instead of accumulating emitted KVs, it uses custom emit() function which just toggles a flag. However, in order to use this optimisation, the function is compiled first with the regular emit function, then the function source is queried with a non-portable toSource() method, and re-compiled again with a new sandbox where emit is overridden.
Instead of reparsing and re-compiling it, pass the sandbox to the compile function and compile filter views with that correct sandbox to start with. Moreover, this helps remove another non-portable function call.
=> Avoid re-compiling filter view functions

configure.ps1
Migrate the settings `with_proper` and `erlang_md5` to `configure.ps1` to add it to `config.erl`.
=> Migrate configure settings to Windows

src/couch_prometheus/src/couch_prometheus_server.erl, src/couch_prometheus/src/couch_prometheus_util.erl
The `/_node/_local/_prometheus` is a missing `TYPE` annotation for `couchdb_httpd_status_codes`.
In addition, it contains no `HELP` annotations, which are useful when exploring the metrics, particularly where
metrics do not strictly match those returned by the `_stats` or `_system` endpoints.
This PR adds the missing `TYPE` annotation and adds `HELP` annotations to all metrics. It also adds additional spacing between the metrics series, making it easier for humans to parse.
The spec for the prometheus text format is at https://github.com/prometheus/docs/blob/main/content/docs/instrumenting/exposition_formats.md, for reference.
`couch_prometheus_util:to_prom/3` is replaced by `couch_prometheus_util:to_prom/4` which requires a description alongside the metric name and type. …
=> feat: add type and descriptions to prometheus output

src/couch_index/src/couch_index_server.erl
Enhance the fix in 06ab38d0c7607abeea7d63aeb47a5229fe0129da to cover all errors thrown by mem3:local_shards. The consequences of a crash here takes down a couch_index_server, which messily kills any in-flight view or find requests for that server.
=> catch and log any error from mem3:local_shards

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
It fixes aliases leak and prepares for new package updates
=> Bump Erlang 24 and 25 in CI

src/couch_event/src/couch_event_listener_mfa.erl, src/couch_index/src/couch_index_server.erl, src/couch_index/test/eunit/couch_index_ddoc_updated_tests.erl
couch_index_server can crash if;
1) an index, opened with new_index, crashes while doing so
2) the db event listener pid crashes
This PR improves behaviour as follows;
1) log original stack in couch_event_listener_mfa:db_event (but still throw)
2) prevent couch_index_server:handle_db_event from crashing
3) track the opener pids in couch_index_server, don't crash couch_index_server if they terminate abnormally
=> Couch index fixes

Makefile.win
Correct env variable `ERL_AFLAGS` to suppress `sasl_error_logger` output.
Suppressing messages like:
```
=ERROR REPORT==== 22-Mar-2023::22:47:36.788000 ===
Error in process <0.998.0> with exit value:
{database_does_not_exist,
[{mem3_shards,load_shards_from_db,"_users",
[{file,"src/mem3_shards.erl"},{line,430}]},
{mem3_shards,load_shards_from_disk,1,
[{file,"src/mem3_shards.erl"},{line,405}]},
{mem3_shards,load_shards_from_disk,2,
[{file,"src/mem3_shards.erl"},{line,434}]},
{mem3_shards,for_docid,3,[{file,"src/mem3_shards.erl"},{line,100}]},
{fabric_doc_open,go,3,[{file,"src/fabric_doc_open.erl"},{line,39}]},
{chttpd_auth_cache,ensure_auth_ddoc_exists,2,
[{file,"src/chttpd_auth_cache.erl"},{line,214}]},
{chttpd_auth_cache,listen_for_changes,1, …
```
=> Suppress sasl_error_logger output on Windows

rel/files/eunit.ini, rel/plugins/eunit_plugin.erl, setup_eunit.template
To log messages of test runs to file we need to add a absoulute path to the file logger.
=> Add log directory to eunit setup template

src/couch_index/test/eunit/couch_index_crash_tests.erl
We pass in a shard name that doesn't exist, causing couch_util:with_db to throw. 
we assert that we get back {ok, St} and don't crash.
=> eunit test to assert ddoc_updated clause doesn't throw

src/docs/src/api/database/find.rst
- Unify the style of synopsis lines.
- Mention the `partitioned` parameter where applicable.
- Fix formatting of `warning` in one of the example responses.
- Trade the possibly retired `range` attribute for `mrargs` and expand the attributes within `opts` in the response of `_explain`.
=> docs(`_find`): catch up with the implementation and further fixes

share/server/loop.js, share/server/views.js, src/couch/test/eunit/couch_js_tests.erl
Spidermonkey sometimes throws an `InternalError` when exceeding memory limits, when normally we'd expect it to crash or exit with a non-0 exit code. Because we trap exceptions, and continue emitting rows, it is possible for users views to randomly miss indexed rows based on whether GC had run or not, other internal runtime state which may have been consuming more or less memory until that time.
To prevent the view continuing processing documents, and randomly dropping emitted rows, depending on memory pressure in the JS runtime at the time, choose to treat Internal errors as fatal.
After an InternalError is raised we expect the process to exit just like it would during OOM.
Add a test to assert this happens.
Fix https://github.com/apache/couchdb/issues/4504
=> Treat javascript internal errors as fatal

src/chttpd/test/eunit/chttpd_view_test.erl, src/couch_mrview/src/couch_mrview_http.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_mrview/test/eunit/couch_mrview_all_docs_tests.erl, src/couch_mrview/test/eunit/couch_mrview_http_tests.erl, src/docs/src/api/ddoc/views.rst
- Request `_view` with reduce function, treat single-element `keys` as `key`
- Add treat_single_keys_as_key/2 function for POST `_view`.
If we query `_all_docs` for deleted or nonexistent docs using single-element
`keys`, we can get {deleted:true} and {error:not_found}.
- Add documentation on using key, keys, start_key, and end_key
make eunit apps=chttpd,couch_mrview
Fixed https://github.com/apache/couchdb/issues/2243
=> Treat single-element keys as key

src/docs/src/api/database/find.rst
Acciddentally in `467e14ef`, the `use_index` field got doubled in one of the sample responses.
=> docs(_find): Remove redundancy from sample `_explain` response

build-aux/Jenkinsfile.full
Linux Z (s390x) has returned back and should now be able to run in the full CI.
Previously we had an issue with spidermonkey on in. Let's see if it still there.
=> Add s390x back into the CI matrix

src/docs/src/api/database/compact.rst, src/docs/src/api/database/shard.rst, src/docs/src/maintenance/compaction.rst
- Modified the example and add a `manual view compaction` link to the
api `/{db}/_compact/{ddoc}` to facilitate users to view `_compact`
related documents.
- Fixed example request for GET /{db}/_shards/{docid}
fixed https://github.com/apache/couchdb/issues/4219, https://github.com/apache/couchdb/issues/4223
=> docs: Fixed _compact/{ddoc} and _shards/{docid} examples

src/couch_mrview/src/couch_mrview_util.erl, src/couch_mrview/test/eunit/couch_mrview_all_docs_tests.erl
Querying `_all_docs` with a non-string `key` should return an empty list, but currently, it will return all documents. This PR should fix it.
`make eunit apps=couch_mrview suites=couch_mrview_all_docs_tests`
fix https://github.com/apache/couchdb/issues/1479
=> Querying `_all_docs` with non-string `key` should return an empty list

rel/overlay/bin/remsh
Allow space and other special characters in cookies.
First set the cookie in `vm.args`, then run the script below:
e.g.: `-setcookie 'a b\n\t\xd#{}()[]$&^!-=+?|//c\\d\\\e\\\\f'`
or `-setcookie "a b\n\t\xd#{}()[]$&^!-=+?|//c\\d\\\e\\\\f"`
```bash
make release
cd rel/couchdb
./bin/couchdb
./bin/remsh
```
fix https://github.com/apache/couchdb/issues/4405
=> Make remsh work with quoted cookie

.devcontainer/devcontainer.json, src/chttpd/src/chttpd_node.erl, src/couch_prometheus/src/couch_prometheus_server.erl, src/couch_prometheus/src/couch_prometheus_util.erl
This adds some of the metrics available via the `/_node/_local/_system` endpoint to the `/_node/_local/_prometheus` endpoint. Specifically:
1. Aggregated message queue sizes for `couch_server` and `index_server` (since these applications are sharded, the standard metrics return a queue size for each shard, which isn't useful in most cases):
```couchdb_erlang_message_queue_size{queue_name="couch_server"} 0
couchdb_erlang_message_queue_size{queue_name="index_server"} 0
```
2. `couch_db_updater` and `couch_file` message queue histogram/summaries:
```
couchdb_erlang_message_queue_couch_file{quantile="0.5"} 0
couchdb_erlang_message_queue_couch_file{quantile="0.9"} 0
couchdb_erlang_message_queue_couch_file{quantile="0.99"} 0
couchdb_erlang_message_queue_couch_file_sum 0 …
```
=> feat (prometheus): additional metrics to match _system

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_show.erl, src/couch/include/couch_db.hrl, src/couch/src/couch_changes.erl, src/couch/src/couch_db.erl, src/couch/src/couch_db_updater.erl, src/couch/src/couch_doc.erl, src/couch/src/couch_native_process.erl, src/couch/src/couch_os_process.erl, src/couch/src/couch_proc_manager.erl, src/couch/src/couch_query_servers.erl, src/couch/test/eunit/couch_auth_cache_tests.erl, src/couch/test/eunit/couch_query_servers_tests.erl, src/couch/test/eunit/couchdb_os_proc_pool.erl, src/couch_mrview/src/couch_mrview_show.erl, src/ddoc_cache/src/ddoc_cache_entry_validation_funs.erl
The main improvement is speeding up process lookup. This should result in improved latency for concurrent requests which quickly acquire and release couchjs processes. Testing with concurrent vdu and map/reduce calls showed a 1.6 -> 6x performance speedup [1].
Previously, couch_proc_manager linearly searched through all the processes and executed a custom callback function for each to match design doc IDs. Instead, use a separate ets table index for idle processes to avoid scanning assigned processes.
Use a db tag in addition to a ddoc id to quickly find idle processes. This could improve performance, but if that's not the case, allow configuring the tagging scheme to use a db prefix only, or disable the scheme altogether.
Use the new `map_get` ets select guard [2] to perform ddoc id …
=> Improve couch_proc_manager

src/ken/src/ken_server.erl, src/ken/test/ken_server_test.erl
It's not used anymore.
In a test where it was used to test config persistence, replace it with `set_delay`.
=> Remove limit parameter from ken

src/couch/src/couch_util.erl, src/docs/src/api/database/find.rst, src/mango/src/mango.hrl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_idx_text.erl, src/mango/src/mango_idx_view.erl, src/mango/src/mango_selector.erl, src/mango/src/mango_selector_text.erl, src/mango/test/22-covering-index-test.py
This pull request aims to implement the first phase of the covering indexes work (_"keys-only covering indexes"_) as it was described in the corresponding RFC document by @mikerhodes, see #4410 and #4413 for the details.
Ideally, end users should not notice any change in the behavior but speed-ups for certain kind of queries.  Performance results obtained by [k6](https://k6.io/) on my MacBook Pro 2021 M1 Max, with 10,000 documents, compared against `c5a7809f` with 3 nodes:
- 1-field index covers the query:
- before: `min=0.59ms  max=498.29ms   p(95)=313.02ms  p(98)=357.44ms  p(99)=390.75ms`
- after: `min=0.53ms max=127.26ms   p(95)=33.15ms   p(98)=37.53ms   p(99)=39.99ms`
- 2-field index covers the query:
- before: `min=19.68ms max=893.79ms   p(95)=674.84ms  p(98)=739.12ms …
=> feat(mango): keys-only covering indexes

src/mango/src/mango_httpd.erl, src/mango/test/01-index-crud-test.py
Sending `GET` requests targeting paths under the `/{db}/_index` endpoint, e.g. `/{db}/_index/something`, cause an internal error. Change the endpoint's behavior to gracefully return HTTP 405 "Method Not Allowed" instead to be inconsistent with other endpoints.
=> fix(mango): GET invalid path under `_index` should not cause 500

src/couch/test/eunit/couch_js_tests.erl
It's designed to crash and exit but depending when it does it exactly it may generate different errors. Add a few more clauses. Hopefully we don't have to completely remove it or comment it out.
=> Noticed the new internal error couchjs test was flaky

src/couch/test/eunit/couch_js_tests.erl
After the previous fix, now the flakiness moved on to the next line.
Remove the extra assertion to avoid it generating flaky tests. The main assertion is already checked above that we get a crash.
=> Another flaky couch_js fix

nouveau/src/main/java/org/apache/couchdb/nouveau/core/IndexManager.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/StripedLock.java, test/elixir/test/nouveau_test.exs
two concurrent attempts to create the same index can fail (in our case this is the fabric rpc worker racing against the ken worker). take a lock to prevent this, but use a striped pattern to allow some concurrency between independent index creations.
=> fix race condition when creating indexes

nouveau/pom.xml
Dropwizard is now registering the [Jackson Blackbird](https://github.com/FasterXML/jackson-modules-base/tree/jackson-modules-base-2.13.3/blackbird#readme) module. This is the recommended setup for Java 9 and later.
https://www.dropwizard.io/en/latest/manual/upgrade-notes/upgrade-notes-2_1_x.html#jackson-blackbird-as-default
=> remove afterburner

src/docs/src/maintenance/performance.rst
The original text  in the [documentation](https://docs.couchdb.org/en/stable/maintenance/performance.html#document-s-id) said that something that takes 16 hex digits can be represented with just 4 digits (in an hypothetical base62 encoding).
I believe that was a typo since 16 hex digits encode a 8-byte sequence that will require (8/3)*4 = 11 digits in base64 (without padding).
So I fixed the typo, and took the liberty of rephrasing it to be more clear, and reference to `base64url` encoding 
instead of base62 (since it's a base64url is a well known encoding)
=> Clarify encoding length in performance.rst

src/docs/src/cve/2023-26268.rst
Backporting https://github.com/apache/couchdb/pull/4562 to 3.3.x
=> CVE-2023-2626 details doc update

src/docs/src/ddocs/nouveau.rst
Documentation fixes for the Nouveau feature.
- Ensures all code examples have the data type as the first parameter to `index`.
- Removes `query=` and replaces with `q=`.
- Adds syntax for enabling faceting for selected fields.
n/a
n/a
=> Nouveau doc fixes

src/couch_log/include/couch_log.hrl, src/couch_log/priv/stats_descriptions.cfg, src/couch_log/src/couch_log.erl, src/couch_log/src/couch_log_config.erl, src/couch_log/src/couch_log_config_dyn.erl, src/couch_log/src/couch_log_formatter.erl, src/couch_log/src/couch_log_sup.erl, src/couch_log/src/couch_log_util.erl, src/couch_log/src/couch_log_writer_file.erl, src/couch_log/src/couch_log_writer_stderr.erl, src/couch_log/src/couch_log_writer_syslog.erl, src/couch_log/test/eunit/couch_log_config_test.erl, src/couch_log/test/eunit/couch_log_formatter_test.erl, src/couch_log/test/eunit/couch_log_writer_ets.erl, src/couch_log/test/eunit/couch_log_writer_syslog_test.erl, src/mango/src/mango_cursor_nouveau.erl, src/mango/src/mango_cursor_text.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_execution_stats.erl
This PR introduces a mechanism for logging metadata about requests and system activity outside of the normal http log entry. In particular, this work is meant to provide tooling for logging things like the quantity of work performed to fulfill a particular request.
For example, given we make a `_find` query like so:
```
(chewbranca)-(jobs:0)-(~)                                                                                                                                                                                                                                                                                                   
(! 2793)-> curl  -u adm:pass -X POST localhost:15984/foo/_find?include_docs=true -d '{"selector":{"blah":"blah …
```
=> Add report logging

src/couch/src/couch_bt_engine.erl, src/couch/src/couch_file.erl
Avoid leaking checksumming details into couch_bt_engine.
=> Encapsulate MD5 file checksums bits in couch_file

src/chttpd/src/chttpd.erl, src/couch/src/couch_httpd.erl, src/couch/test/eunit/couch_etag_tests.erl
Use the couch_httpd one as it would be odd for couch_httpd to call chttpd.
Also fix the test assertion order: the first argument should be the expected value, the second one should be the test value [1]
[1] https://www.erlang.org/doc/apps/eunit/chapter.html#Assert_macros
=> Remove duplicate etag generation function

configure
Restore the old `--dev` configure option and add a new switch
for `--disable-docs --disable-fauxton --enable nouveau`.
=> Add new configure option and restore --dev behavior

src/chttpd/src/chttpd_db.erl, src/couch/src/couch_att.erl, src/couch/src/couch_db.erl, src/couch/src/couch_httpd_db.erl, src/couch/test/eunit/couchdb_attachments_tests.erl, test/elixir/test/attachments_test.exs
Part of a series of changes to expunge MD5 entirely.
=> remove Content-MD5 header support

src/mango/src/mango_httpd.erl, src/mango/test/01-index-crud-test.py
This reverts commit c1195e43c0b55f99892bb5d6b593de178499b969.
This wasn't quite right. handle_index_req has several separate resources handled within it which each support a different set of http methods.
We should send 405 for a resource that exists but doesn't support the request's method.
We should send 404 for a resource that doesn't exist at all.
Reverting this gives us a 500 / function_clause, which is at least honest (the server has made an error) but we should circle back and send better errors.
Noting that;
1) extra paths for _all_docs gives the desired 404 but for a silly reason (it matches the clause that looks for attachments, and you can't make a doc called _all_docs to attach anything to)
2) extra paths for _changes are ignored (and the _changes request works as expected) …
=> Revert "fix(mango): GET invalid path under `_index` should not cause 500

src/couch_log/src/couch_log_writer_stderr.erl
Quick follow up to https://github.com/apache/couchdb/pull/4483 removing a variable that ended up not being used that is currently causing a compiler warning.
=> Remove extra unused variable

src/docs/src/api/database/find.rst, src/mango/src/mango.hrl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_execution_stats.erl, src/mango/test/15-execution-stats-test.py
Add another field to the shard-level Mango execution statistics to keep track of the count of keys that were examined for the query.  Note that this requires to change the way how stats are stored -- an approach similar to that of the view callback arguments was chosen, which features a map (#4394).
The change in the format also implies a potential incompatibility between different version of nodes, which may happen for mixed-version clusters.  This is handled by introducing an additional option for the view callback where the coordinator can request for the results in the new format and the old format is still recognized.  It helps to handle version differences automatically therefore no specific configuration option is required to control the migration.  Thanks @rnewson for the idea. …
=> feat(`mango`): add `keys_examined` for `execution_stats`

src/mango/src/mango_native_proc.erl
dreyfus/clouseau needs "string" type when indexing, so make a separate add_default_field_nouveau function
=> fix dreyfus after 'Improve nouveau mango integration'

src/mango/src/mango_cursor_view.erl, src/mango/test/22-covering-index-test.py, src/mango/test/mango.py, src/mango/test/user_docs.py
The previous work that introduced the keys-only covering indexes (#4512) did not count with the case that database might be partitioned. And since they use a different format for their own local indexes and the code does not handle that, it will crash.  When indexes are defined globally for the partitioned databases, there is no problem because the view row does not include information about the partition, i.e. it is transparent.
Add the missing support for these scenarios and extend the test suite to cover them as well.  That latter required some changes to the base classes in the integration test suite as it apparently completely misses out on running test cases for partitioned databases.
=> fix(`mango`): covering indexes crash on partitioned databases

nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/QueryDeserializer.java, nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/QuerySerializationTest.java
this class is currently unreachable but might be a new way to specify the query in SearchRequest rather than expanding the string-based query syntax.
=> add tests for QueryDeserializer

src/fabric/src/fabric_bench.erl, src/fabric/test/eunit/fabric_bench_test.erl
This is mostly a diagnostic tool in the spirit of couch_debug. It creates a database, fills it with some docs, and then tries to read them. It computes rough expected rates for doc operations (how many docs per second it could insert, read, get via _all_docs). When the test is done it deletes the database. If it crashes, it also deletes the database. If someone brutally kills it, the subsequent runs will still find old databases and delete them.
=> Add a simple fabric benchmark

src/docs/src/api/database/find.rst, src/mango/src/mango_httpd.erl, src/mango/test/01-index-crud-test.py
Many of the requests outside the scope of the `_index` endpoint are not handled gracefully but trigger an internal server error.  Enhance the `_index` handler logic to return proper answers for invalid queries and supply it with more exhaustive integration tests.
Provide documentation for the existing `_index/_bulk_delete` endpoint as it was missing, and mention that the `_design` prefix is not needed when deleting indexes.
This is a follow-up to #4584 and a revisited version of #4514.
=> fix(`mango`): missing parts of the `_index` API

rel/overlay/etc/vm.args
* Increase distribution buffer size from 1MB to 32MB. We've been using this value at Cloudant for years in all the clusters. RabbitMQ defaults to 128MB, which is even higher. This might speed busy clusters with lots of distribution traffic.
* Add a commented out example of scheduling flags to use in a Docker or Kube environment with CFS quotas (advice taken from https://erlangforums.com/t/vm-tuning-guide/1945/3).
=> Update default vm.args settings

src/fabric/src/fabric_db_create.erl, src/mem3/src/mem3.erl
`mem3:dbname/1` with a `<<"shard/...">>` binary is called quite a few times as
seen when profiling with fprof:
https://gist.github.com/nickva/38760462c1545bf55d98f4898ae1983d
In that case `mem3:dbname` is removing the timestamp suffix. However, because
it uses `filename:rootname/1` which handles cases pertaining to file system
paths and such, it ends up being a bit more expensive than necessary.
To optimize it assume it has a timestamp suffix and try to parse it out first,
and then verify can be parsed into an integer, if that fails fall back to using
`filename:rootname/1`.
To lower chance of the timestamp suffix changing and us not noticing move the
shard suffix generation function from fabric to mem3 so the generating and the
stripping functions are right next to each other.
A quick …
=> Optimize mem3:dbname/1 function

configure
It's the latest version. Otherwise, unexpected updates there break our CI chain.
=> Fix rebar3 version to 3.21.0

build-aux/Jenkinsfile.full
This reverts commit e6939557bcfccf63ac33d1f970904f55b24a421d.
The node is back online so we're enabling it.
=> Revert "ARM64 worker went away."

src/couch/priv/stats_descriptions.cfg, src/couch/src/couch_bt_engine.erl, src/couch/src/couch_db_updater.erl, src/couch/src/couch_file.erl, src/couch/src/couch_os_process.erl, src/couch/src/couch_proc_manager.erl, src/couch/test/eunit/couch_file_tests.erl, src/couch/test/eunit/couch_js_tests.erl, src/couch_pse_tests/src/cpse_test_read_write_docs.erl
fsync times can vary widely, especially on a remote block storage, so add a histogram and count for fsync calls. At a higher level, we can coalesce similar update doc requests from multiple clients, so add metrics to track that as well.
Improving couch_proc_manager, and experimenting with quickjs js engine [1], noticed we lacked metrics in that area. Add metrics to track query process acquires, start/stops (including crashes) as well as how many prompt and prompt errors we have. These should help gain some confidence when upgrading to a new engine version or engine type by comparing the before and after metrics output.
Trying to test some of these new metrics, noticed couch_file tests did most of the test logic in the setup part, which resulted in plenty of log noise during the test runs …
=> Add a few more commit and query engine metrics

src/couch/priv/stats_descriptions.cfg
The stats description was probably not included for the `keys_examined` counter for Mango in #4569, which causes `unknown metric: [mango, keys_examined]` messages in the logs.  This change fixes the problem by providing the necessary item.
=> fix: missing stats description for Mango `keys_examined`

src/mango/test/04-key-tests.py, src/mango/test/05-index-selection-test.py, src/mango/test/06-basic-text-test.py, src/mango/test/10-disable-array-length-field-test.py
- Fix the faulty `index_array_length` tests:
- They do not check the count of the returned documents but blindly
assume that there will be results.  Add an explicit assertion about
the expected number of documents in the response so it could be
detected if something breaks.
- The assertion on the document count revealed that the test database
is actually empty because it is immediately wiped out after creation
by a misplaced `recreate()` call.
- When the indexing on the array lengths is disabled, there shall be no
documents returned, and not the sizes of the `favorites` arrays in
the results shall be zero.  That is because there is no information
available on the sizes of the arrays.
- The result of the `mango.has_text_service()` checks is implicitly forecasted by the …
=> fix(mango): integration tests

rel/overlay/etc/default.ini, src/couch/src/couch_httpd.erl, src/docs/src/config/http.rst
Add an option to suppress including the CouchDB and OTP versions, defaulting to the current behaviour of including both.
note: If, instead, we omitted this line we would get Mochiweb's default server line rather than no server line.
=> optionally suppress version info in server response header

src/couch/src/couch_file.erl
Most of our histograms are in milliseconds. Don't deviate from that with the new fsync.time metric so make it use milliseconds as well. It turns out fractional histogram values are allowed, so we can still get the sub-millisecond precision for faster disks that way.
Example of usage during: `fabric_bench:go(#{docs=>50000, batch_size=>100}).`
```
couch_stats:sample([fsync, time]).
[{min,8.303},
{max,134.124},
{arithmetic_mean,49.3490064102564},
{geometric_mean,42.939511193319994},
{harmonic_mean,37.05011500299417},
{median,43.198},
{variance,654.1673972451199},
{standard_deviation,25.57669637082006},
{skewness,0.7276971171556265},
{kurtosis,-0.021701320829371706},
{percentile,[{50,43.198},
{75,63.858},
{90,81.22},
{95,97.231},
{99,114.86},
{999,134.124}]},
{histogram,[{25.303,48}, …
```
=> Use milliseconds for fsync time histogram

src/mango/requirements.txt
This reverts commit a4bad8d8e93eaa93a56465a082524f18fd736178.
Unfortunately 2.27.1 is the highest support version for python 3 on Ubuntu 18 and CentOS 7 workers. This is for a localhost CI test only and not part of our release artifact.
=> Revert "Bump requests from 2.27.1 to 2.31.0 in /src/mango"

.gitignore, rel/reltool.config, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_misc.erl, src/couch/include/couch_db.hrl, src/couch/src/couch_file.erl, src/couch/src/couch_native_process.erl, src/couch/src/couch_query_servers.erl, src/couch/test/eunit/couch_flags_config_tests.erl, src/couch_epi/src/couch_epi.hrl, src/couch_epi/src/couch_epi_util.erl, src/couch_log/src/couch_log_formatter.erl, src/couch_log/src/couch_log_trunc_io.erl, src/couch_log/test/eunit/couch_log_formatter_test.erl, src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_pse_tests/src/cpse_util.erl, src/couch_replicator/src/couch_replicator_ids.erl, src/couch_replicator/src/couch_replicator_utils.erl, src/ddoc_cache/src/ddoc_cache_value.erl, src/dreyfus/src/dreyfus_index.erl, src/fabric/src/fabric_view_changes.erl, src/mango/src/mango_idx.erl, src/mem3/src/mem3_hash.erl, src/mem3/src/mem3_rep.erl, src/mem3/src/mem3_util.erl, src/nouveau/src/nouveau_util.erl, src/smoosh/src/smoosh_persist.erl
Build and pass tests on OTP 26.
```
asdf install erlang 26.0
asdf local erlang 26.0
make check
```
=> OTP 26 compatibility

rel/overlay/etc/default.ini, src/couch/priv/stats_descriptions.cfg, src/couch/src/couch_file.erl, src/couch/test/eunit/couch_file_tests.erl, src/docs/src/config/couchdb.rst
Use the 128 bit variant of xxHash as it has the same output size as MD5, is non-cryptographic, and is quite a bit faster [1].
Writing xxHash checksums is disabled by default. This would allow us to make an intermediate release to which we can downgrade to as it can read both xxHash and MD5 checksums. In a future release writing xxHash checksums will flip to
`true`, but it would be possible to safely downgrade to the intermediate releases which would be aware of xxHash checksums and won't interpret them as corrupt data.
If downgrade is not a concern, using xxHash checksums can yield a noticeable speed improvement when reading larger documents (128KB+ or so).
There is metric which would indicate if any MD5 checksums are present after the xxHash has been enabled.
To avoid duplicating the …
=> Use xxHash for couch_file checksums

src/couch/test/eunit/couch_file_tests.erl
The deletion test is flaky sometimes:
```
[2023-05-31T19:44:32.096Z]     File delete tests
[2023-05-31T19:44:32.096Z]       enable_database_recovery = false, context = delete
[2023-05-31T19:44:32.096Z]         couch_file_tests:424: make_enable_recovery_test_case...ok
[2023-05-31T19:44:32.096Z]         couch_file_tests:425: make_enable_recovery_test_case...ok
[2023-05-31T19:44:32.096Z]         couch_file_tests:426: make_enable_recovery_test_case...ok
[2023-05-31T19:44:32.096Z]         couch_file_tests:427: make_enable_recovery_test_case...*failed*
[2023-05-31T19:44:32.096Z] in function couch_file_tests:'-make_enable_recovery_test_case/3-fun-8-'/2 (test/eunit/couch_file_tests.erl, line 427)
[2023-05-31T19:44:32.096Z] in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71) …
```
=> Add extra assert in flaky couch_file test

.gitignore, Makefile, configure, dev/remsh-tls, dev/run, rel/overlay/bin/remsh, src/couch_dist/.gitignore, src/couch_dist/README.md, src/couch_dist/certs/certs, src/couch_dist/certs/certs.exs, src/couch_dist/certs/parse_cert.escript, src/couch_dist/gen_certs, src/docs/src/cluster/tls_erlang_distribution.rst
When the CouchDB custom (couch) distribution is enabled, OTP 24 and 25,
you will get a warning when using `remsh-tls` or `remsh -t`; but in OTP 26,
this is an error. Because the default value of the verify option is `verify_peer`
instead of `verify_none`. We need to provide the appropriate CA certificates to
pass the validation.
```bash
$ ./dev/remsh-tls
=WARNING REPORT==== 4-May-2023::12:43:28.893022 ===
Description: "Server authenticity is not verified since certificate path validation is not enabled"
Reason: "The option {verify, verify_peer} and one of the options
'cacertfile' or 'cacerts' are required to enable this."
```
```bash
$ ./dev/remsh-tls
Could not connect to "node1@127.0.0.1"
```
- Add `{verify, verify_peer}` to enable verification
- Add `certs` in `couch_dist` app to …
=> TLS: add `{verify, verify_peer}` to enable verification

src/docs/src/cluster/sharding.rst
It was pointed out on the user@ mailing list (https://lists.apache.org/thread/s2t47t9c84bqg50gz2805gnh73qxr7fc) that the docs express a different quorum algorithm from the code (that happens to give the same answers for odd numbers of `N`).
This PR updates the docs to match the code.
=> clarify default quorum calculation

src/fabric/test/eunit/fabric_bench_test.erl
In some cases, it's possible for databases created in previous test runs to cause test failures like this:
```
fabric_bench_test:97: -with/1-fun-0- (t_db_deletion_ignores_other_dbs)...*failed*
in function fabric_bench_test:t_db_deletion_ignores_other_dbs/1 (test/eunit/fabric_bench_test.erl, line 76) in call from eunit_test:run_testfun/1 (eunit_test.erl, line 71) in call from eunit_proc:run_test/1 (eunit_proc.erl, line 531) in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 356) in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 514) in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 456) in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 346) in call from eunit_proc:run_group/2 (eunit_proc.erl, line 570) **error:{badmatch,{error,file_exists}} …
```
=> Clean up fabric_bench_test databases

src/fabric/src/fabric_view_changes.erl
When we get sequence before the split, we'll fill in the missing (now split) ranges with a special `{split, OldNodeUUid}` marker. However, when sequences are emitted in the changes API, that will make the N- prefix (SeqSum) bounce around from higher to lower numbers, while users expect those to be mostly incrementing. So take a conservative approach and assume it will be a full rewind for that range, and use 0 instead. This is a purely cosmetic thing, when we decode the sequence that prefix gets thrown away anyway.
To emphasize that the sequence prefix is mostly a visual aid, rename the `seq/1` function to `fake_packed_seq/1` with a comment about what it does and a note about the special split case.
Fixes a part of issue: #4640
=> Improve emitted change feed sequence after a split

src/config/src/config.erl
Config values may contain `;` in them as long as `;` is not preceded by a space or a tab character.
Fixes: https://github.com/apache/couchdb/issues/4651
This regression was introduced in: https://github.com/apache/couchdb/pull/4287
=> Fix the ability to use ; in config values

src/mango/src/mango_cursor_view.erl
The definition of `mango_cursor_view:composite_indexes/2` does not exploit the possibilities of fold left, it behaves much like a mapping.  Using `lists:map` here makes this explicit, which may help with readability and may be implemented in a more specialized manner.
=> chore(`mango`): replace `foldl` with a `map`

src/mango/src/mango_idx_nouveau.erl
Commit f40147b2 was not added for the Nouveau index module.  This could lead to a failure when `indexable_fields/1` is called with a selector that contains the `$regex` operator.
=> fix(`mango`): chase `idx_text` changes for Nouveau

src/mango/test/21-empty-selector-tests.py
Remove unused imports and make the definition of test suites less handcrafted via multiple inheritance.  This representation makes it possible for developers to add tests as class-specific methods when required, much like it happened for `03-operator-test`.
=> chore(`mango`): simplify implementation of empty selector tests

src/chttpd/src/chttpd_node.erl, test/elixir/test/config/suite.elixir, test/elixir/test/config_test.exs
Configuration values could be updated by sending JSON strings as the body.  But there is no safeguard in place to stop users from submitting values of arbitrary JSON type, including objects. Violating this assumption silently triggers a HTTP 500 response. Fill in this hole and provide users with a cause of rejection.
=> fix(config): updating values

src/couch_replicator/src/couch_replicator_parse.erl, src/docs/src/config/replicator.rst
in particular this allows;
```
[replicator]
ibrowse_options = [{prefer_ipv6, true}]
```
which allows the replicator to replicate with an ipv6-only source or target.
Closes: https://github.com/apache/couchdb/issues/4668
=> allow setting of some ibrowse options

Makefile, test/elixir/test/nouveau_test.exs
Only run nouveau tests if configured with `--enable-nouveau`
sidebar: is it appropriate to move the `-include install.mk` directive? Its original placement was just before the install targets, but it seems necessary to know `with_nouveau = X` elsewhere.
A similar switch is needed for dreyfus. `make elixir` still fails if you are not running a clouseau jvm. this predates the nouveau work.
=> Conditionally exclude nouveau from elixir make target

src/couch/src/couch_httpd_multipart.erl
Previously, we used a stale `Waiting` list of workers instead of the updated `NewWaiting` one. Then, when we recursed back to the top in `maybe_send_data/1`, and tried to reply to all waiting clients, we re-sent the same block to the client. That client would then get more attachment blocks than it expected and would throw an `attachment longer than expected` error.
At the API level this would manifest as an intermittent 400 (bad_request) HTTP error for multipart document + attachments PUTs. For the error to occur, a `{hello_from_writer, ...}` has to be recieved when we're in the bottom part of `maybe_send_data/1` in the couch_httpd_multipart parser. However, due to how CouchDB replicator skips over documents PUTs which generate 4xx errors, the effect was that these documents were skipped …
=> Fix multipart parser "attachment longer than expected" error

src/chttpd/test/eunit/chttpd_db_test.erl, src/fabric/src/fabric_view_all_docs.erl
Querying design/local docs with `keys` should only return design/local docs.
```bash
$ curl -X DELETE http://adm:pass@127.0.0.1:15984/db
$ curl -X PUT http://adm:pass@127.0.0.1:15984/db
{"ok":true}
$ curl -X POST http://adm:pass@127.0.0.1:15984/db/_bulk_docs'?=' \
-H 'Content-Type: application/json' \
-d '{"docs": [{"_id": "_design/user-emails","views": {"getVerifiedEmails": {"map": "function(doc) {if(doc.email_verified && doc.email_verified == true){\n  emit(doc.email, [doc.name, doc.email_verified, doc.joined]) }}"}}},{"_id": "abc123","type": "user","email": "amelie.smith@aol.com","email_verified": true}]}'
[{"ok":true,"id":"_design/user-emails","rev":"1-840ca986e193b3f5df84da0befe09af6"},{"ok":true,"id":"abc123","rev":"1-3e0944abf21b22d8d6fe70002edc2e82"}]
```
```bash
$ curl -X POST …
```
=> Fix: `_design_docs/queries` with `keys` should only return design docs

nouveau/src/main/java/org/apache/couchdb/nouveau/api/SearchRequest.java, nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/Lucene9Index.java, nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/NouveauQueryParser.java, nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/NouveauQueryParserTest.java, src/docs/src/api/ddoc/nouveau.rst, src/nouveau/src/nouveau_httpd.erl, test/elixir/test/config/nouveau.elixir, test/elixir/test/nouveau_test.exs
The expected format for numbers varies by region. Allow a query to specify its locale with a new parameter (e.g, `?locale=de` or `?locale=us`) and apply the appropriate rules. If not specified the default locale for the JVM is used.
run the test suite
n/a
=> allow locale setting for number detection

src/docs/src/install/unix.rst
we can merge this after we publish the rocky9 build rpm
=> docs: add Centos/RHEL9+, thanks for nothing RedHat

rel/overlay/etc/default.ini, src/mem3/src/mem3_rep.erl, src/mem3/src/mem3_reshard.erl, src/mem3/src/mem3_reshard_job.erl, src/mem3/src/mem3_rpc.erl, src/mem3/test/eunit/mem3_reshard_api_test.erl
failed jobs should be restartable, and with the ioq downgrade of reshard jobs, we need to make the timeout configurable, so busy clusters do not fail for no good reason.
=> [shard splitting] allow resumption of failed jobs & make timeout configurable

src/couch/src/couch_httpd_auth.erl, src/docs/src/api/server/authn.rst, test/elixir/test/cookie_auth_test.exs
This reverts commit cfee5236bcdbf0591ceed7116d5ee9bf383c8257.
The interactions here are problematic after some more thought.
before my patch, if you send a cookie for user A and basic auth for user B, the request will run as user A, because we check the cookie first.
after my patch, if you send a cookie for user A and basic auth for user B, the request will run as user B, because we ignore the cookie now because the names don't match.
I think, instead, the default_auth_handler should create its own cookie, which only it reads on future requests, that serves as a cache of the original authentication approval.
Reverting so this doesn't linger on main while I work up a better version.
=> Revert "send cookie on successful basic auth"

Makefile.win, configure.ps1, nouveau/.gitattributes, nouveau/.gitignore
Porting Nouveau to build on Windows.
Commands:
```
.\make.cmd
.\make.cmd nouveau-test
.\make.cmd clean
```
The clean target ends with the following error:
```
PS C:\Users\couchdb\Documents\couchdb> .\make.cmd clean
==> snappy (clean)
==> bear (clean)
==> meck (clean)
==> folsom (clean)
==> hyper (clean)
==> ibrowse (clean)
==> jiffy (clean)
==> mochiweb (clean)
==> recon (clean)
==> proper (clean)
==> couch_epi (clean)
==> config (clean)
==> couch_log (clean)
==> khash (clean)
WARN:  Missing plugins: [pc]
==> b64url (clean)
WARN:  Missing plugins: [pc]
==> exxhash (clean)
==> ets_lru (clean)
==> chttpd (clean)
==> couch (clean)
==> couch_event (clean)
==> mem3 (clean)
==> couch_index (clean)
==> couch_mrview (clean)
==> couch_replicator (clean)
==> couch_pse_tests (clean)
==> couch_stats …
```
=> Build Nouveau on Windows

src/couch_replicator/include/couch_replicator_api_wrap.hrl, src/couch_replicator/src/couch_replicator_auth_session.erl
User the same user agent as we do for all the other replicator requests.
=> Add "CouchDB-Replicator/..." user agent to replicator /_session requests

src/couch/src/couch_httpd_auth.erl, src/docs/src/api/server/authn.rst, test/elixir/lib/couch.ex, test/elixir/test/cookie_auth_test.exs
As a way to migrate users to a strong password hashing scheme without getting a performance hit each time, assuming the client will send back the cookie we send them. we check the cookie first and avoid the hit, but we still fall back to basic auth if necessary.
The AuthSession cookie is extended with a new field that indicates whether it was issued by the default authentication handler or the cookie authentication handler. If the cookie was issued by the default authentication handler the cookie authentication handler will check the username in the basic auth header, if present, is a match for the name in the cookie. If it is not, the cookie is ignored. This ensures that the basic auth header takes precedence for any client that got an unasked-for cookie and ensures their operations are …
=> send a session cookie after successful basic auth

LICENSE, src/couch/src/couch_lists.erl, src/couch/test/eunit/couch_lists_tests.erl, src/mango/src/mango_idx_nouveau.erl, src/mango/src/mango_idx_text.erl
Indexable fields from selectors are not de-duplicated when collected.  This means that every time when the same field is referenced in the selector, it will be added to the result.  This does not sound like a good practice in general, but addressing it would also make the implementation consistent with that of the view indexes.
In addition to all these, the change could help with exposing this information more cleanly when guiding the user in composing better queries.
=> fix(`mango`): remove duplicate elements from `indexable_fields/1` results

src/dreyfus/src/dreyfus_httpd.erl, test/elixir/test/config/search.elixir, test/elixir/test/search_test.exs
Facet results are rendered inconsistently in the JSON response because a single zero-valued scalar is added to the place of the object which would otherwise represent the detailed statistics.
For example, a "no match" search with counts faceting, such as
```
/{db}/_design/{ddoc}/_search/{idx}?limit=0&q=city1:London*&counts=["city2"]
```
(where there are no documents matching the query, i.e. no `city1` field has a value `London`) results in the following JSON:
```json
"counts": {
"city2": 0.0
}
```
but it should be like this instead:
```json
"counts": {
"city2": {}
}
```
That is because the expectation is that `city2` would contain a map of other city counts (if there were matches), e.g.
```json
"counts": {
"city2": {
"Aberystwyth": 1004,
"Bristol": 1019
}
}
```
There is a similar impact …
=> fix(`dreyfus`): make faceting produce maps on empty results

src/docs/src/api/database/find.rst, src/mango/src/mango_cursor.erl, src/mango/test/02-basic-find-test.py
Currently, the `r` query option (for read quorum) is formatted in an awkward way when added to the `_explain` JSON response (excerpt, `r` is set to `1` in the query object):
```json
...
"opts": {
...
"r": [
49
],
...
},
...
```
The value there is the ASCII code of `1` and the nesting list denotes the string.  That is because `r` is stored as a list internally and when it comes to rendering, `jiffy` will interpret the contents as an array.  Treat this issue locally, in the `_explain` code, by turning it an integer.
Thanks @ricellis for spotting this bug!
=> fix(`mango`): tweak the formatting of option r in the _explain output

src/dreyfus/src/dreyfus_httpd.erl
Commit 526e203d30acc3a29e4418a7317badddc37f5529 included a version of the fix that did not pass the Elixir tests.  Revert back to the original approach as that one appears to be the best (most flexible, shortest, and correct) solution.
=> fix(`dreyfus`): amend the fix for faceting on zero values

src/fabric/src/fabric_view.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_error.erl, src/mango/src/mango_httpd.erl, src/mango/test/02-basic-find-test.py
Add handling for invalid field errors. Previously they would emit a 500 `badmatch` error with a stack trace:
```
% curl -v -XPOST -H'Content-type:application/json' $URL/db/_find -d '{"selector":{"_id":{"":null}}}'
< HTTP/1.1 500 Internal Server Error
{"error":"badmatch","reason":"{error,{{mango_error,mango_util,{invalid_field_name...
```
With the fix it emits a 400 error:
```
< HTTP/1.1 400 Bad Request
{"error":"invalid_field_name","reason":"Invalid field name: _id."}
```
This should also handle a general class of mango errors from `$db/_find` which are sent from the workers, passed through the fabric/rexi mechanism, and handled on the coordinator side. Previously some of those would emit the same 500 badmatch + a stack trace since we didn't expect errors in a few places which generated a …
=> Handle invalid field errors in Mango

Makefile, build-aux/xref-helper.sh, test/fixtures/allowed-xref.txt
only works on Erlang 23. 24 and 25 fail
24 e.g. with:
```==> mem3 (xref)
Warning: hastings_index:await/2 is undefined function (Xref)
Warning: hastings_index:design_doc_to_indexes/1 is undefined function (Xref)
Warning: hastings_index_manager:get_index/2 is undefined function (Xref)
WARN:  Continuing on after abort: [xref]
ERROR: xref failed while processing /Users/jan/Work/asf/tmp/couchdb/src/mem3: {'EXIT',
{{badmatch,
[{attribute,{1,1},file,{"src/mem3_reshard_index.erl",1}},
{attribute,{13,2},module,mem3_reshard_index},
{attribute,
{15,2},
export,
[{design_docs,1},{target_indices,2},{spawn_builders,1},{build_index,2}]},
… big symbol dump
```
=> feat(build): fail build if xref complains

rel/overlay/etc/default.ini, rel/overlay/etc/vm.args, rel/reltool.config, src/chttpd/src/chttpd.erl, src/couch/priv/stats_descriptions.cfg, src/couch/src/couch.app.src, src/couch/src/couch_db.erl, src/couch/src/couch_disk_monitor.erl, src/couch/src/couch_secondary_sup.erl, src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_util.erl, src/docs/src/config/disk-monitor.rst, src/docs/src/config/index.rst, src/fabric/src/fabric_rpc.erl, src/fabric/src/fabric_streams.erl, src/fabric/src/fabric_view.erl, src/fabric/src/fabric_view_map.erl, src/fabric/src/fabric_view_reduce.erl, src/ken/src/ken_server.erl, test/elixir/test/config/suite.elixir, test/elixir/test/disk_monitor.exs
Add some opt-in countermeasures if disk space gets critically low, with the aim of avoiding hitting end of disk.
Enable the disk monitor, run a CouchDB node on a small disk, and add lots of data. You should find that background indexing stops (at 80% full) and then stale view queries and database updates are blocked. Reduce disk usage (allow compaction to run to completion, or delete databases) and see both interventions automatically unlock. 
N/A
=> Introduce optional countermeasures as we run out of disk space

src/docs/requirements.txt
Upgrade to the latest version 1.2.2 of sphinx-rtd-theme.
Fixes #4701.
=> Upgrade sphinx-rtd-theme

src/docs/src/api/database/find.rst, src/docs/src/config/query-servers.rst
Fix minor problems with the CouchDB documentation, related to Mango:
- Formatting issues with the description of the configuration options
- Adjust order of fields in the sample `_explain` JSON response for better readability
=> fix(`docs`): minor fixes for Mango

src/chttpd/test/eunit/chttpd_changes_test.erl, src/fabric/src/fabric_rpc.erl
Previously, pending changes count for the `descending=true` didn't indicate the number of pending changes. Instead, it returned the negative value of the already emitted rows. So for `descending=true&limit=2`, it would return -2; for `descending=true&limit=5`, it would return -5. That wasn't a very useful value, so let's fix it to return the actual number of pending changes.
When traversing the changes feed backwards, the number of pending changes until the start will be equal to the total number of changes, minus the number of changes from the current start sequence until the end.
Issue: https://github.com/apache/couchdb/issues/4714
=> Fix pending count for the reverse changes feed

Makefile, Makefile.win, mix.exs
Elixir 1.5 introduces some changes in the compilation process tha affects to the execution of our test suite. The problem has been reported here #4706
It seems that we are facing one of the incompatibility problems documented in the Elixir 1.15 release notes
> Potential incompatibilities
Due to the code path pruning, if you have an application or dependency that does not specify its dependencies on Erlang and Elixir application, it may no longer compile successfully in Elixir v1.15. You can temporarily disable code path pruning by setting prune_code_paths: false in your mix.exs, although doing so may lead to runtime bugs that are only manifested inside a [mix release](https://hexdocs.pm/mix/1.15/Mix.Tasks.Release.html).
Previous to this PR, if we try to run the elixir test suite with …
=> Unlock build using Elixir 1.15

rel/overlay/etc/default.ini, src/chttpd/priv/stats_descriptions.cfg, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_util_test.erl, src/docs/src/config/http.rst, src/fabric/src/fabric_db_update_listener.erl, src/fabric/src/fabric_streams.erl, src/fabric/src/fabric_view_changes.erl
Previously, when processing long running streaming requests, such as _find with a highly selective selector, when no rows are emitted for a while, the client could disconnect but the request process, and all the associated workers on remote nodes would continue running, consuming server resources.
We already handle remote (RPC) process cleanup if the coordinator crashes, we just need a way to kill that coordinator if the connection is closed in the case when no data may be emitted for a long time. This is what the current commit accomplishes.
It turns out there is no simple way to detect passive mode socket disconnects in current versions of Erlang/OTP. The socket at the kernel level may be closed (in close_wait state), however `inet:info/1` will continue reporting it as `connected`. The …
=> Stop client process and clean up if client disconnects

rebar.config.script, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_util_test.erl, src/fabric/src/fabric_db_update_listener.erl, src/fabric/src/fabric_streams.erl, src/fabric/src/fabric_view_changes.erl
Mochiweb [3.2.0](https://github.com/mochi/mochiweb/releases/tag/v3.2.0) has a `mochiweb_request:is_closed/1` function which we can use instead of our socket check in `chttpd_util`.
Since `mochiweb_request:is_closed/1` takes a request object, switch the client request monitoring code and tests to use requests instead of sockets. That involves doing a bunch of renames mostly which makes the PR a bit long, but otherwise, everything should work as before.
=> Update mochiweb to 3.2.0

src/mango/src/mango_cursor.erl
Noticed two consecutive failures there on ppc64le platform. That's usually the slowest executor so it's probalby just a timeout. Let's try bumping it from 5 sec to 10 sec.
Re: https://github.com/apache/couchdb/pull/4662#issuecomment-1703174645
=> Increase timeout in mango_cursor tests

src/docs/src/api/database/find.rst, src/mango/src/mango_cursor.erl
The `fields` attribute on `_explain` might have the string value `"all_fields"` when the respective query parameter (`fields`) is not set by the user.  This is to express that no projection of fields would happen on the returned documents.
The current behavior contradicts with the current contract, because by documentation, `fields` is an array of strings instead to provide information on the projected fields.  The discrepancy here makes it hard to formalize this in OpenAPI which leads to problems in the development of SDKs, among others.
Change `_explain` to return `[]` for `fields` when it was not set through the query parameters. This is thought to be semantically equivalent to `"all_fields"` therefore this would not cause problems while preserving the promised type.
Thanks @ricellis …
=> fix(`mango`): correct behavior of `fields` on `_explain`

src/chttpd/src/chttpd.erl
This reverts commit 139ac9c05148b4c97c848bbe8d4d5abdf8e7fff5.
I, very belatedly, realised this breaks the X-Forwarded-For feature from mochiweb. That's more important than the port number. Reverting for now but will attempt again later (but without altering `peer` value).
N/A
=> Revert "print peer port in http log"

nouveau/gradle/wrapper/gradle-wrapper.properties, nouveau/src/main/java/org/apache/couchdb/nouveau/api/DocumentDeleteRequest.java, nouveau/src/main/java/org/apache/couchdb/nouveau/api/DocumentUpdateRequest.java, nouveau/src/main/java/org/apache/couchdb/nouveau/api/IndexInfoRequest.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/Index.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/UpdatesOutOfOrderException.java, nouveau/src/main/java/org/apache/couchdb/nouveau/health/IndexHealthCheck.java, nouveau/src/main/java/org/apache/couchdb/nouveau/resources/IndexResource.java, nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexTest.java, src/nouveau/src/nouveau_api.erl, src/nouveau/src/nouveau_index_manager.erl, src/nouveau/src/nouveau_index_updater.erl, src/nouveau/src/nouveau_util.erl, test/elixir/test/nouveau_test.exs
This is a performance only pull request, but a complicated one.
I benchmarked nouveau against clouseau for the same database and found it was slower (2-4x slower depending on how large the documents were, the smaller the docs the bigger the difference).
This is fundamentally because clouseau's overhead between erlang and the jvm is much lower, as they are exchanging messages over an established, dedicated connection.
To improve nouveau performance I have adopted a similar approach, while ensuring index consistency.
1) nouveau on the jvm side requires each index update request (whether a document update, delete or purge, or a request to advance update_seq or purge_seq independently from an index change) to pass the current update_seq or purge_seq of the index. This is critical in detecting …
=> Nouveau ibrowse improvements

src/mango/src/mango_cursor.erl
This is a follow-up to 83e39b6d where the `all_fields` value was replaced for `[]` to preserve the JSON array type.  The same has to be done for `fields` in the `opts` nesting object as well — these two attributes should behave alike.
```shell
```
Similarly to #4751, users who based their solution on utilizing the `"all_fields"` response explicitly might need to change it to use `[]` instead. Otherwise they are not affected by the change.
=> fix(`mango`): align `opts.fields` with `fields` on `_explain`

src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_util_test.erl
Previously we saved the request "as-is", mainly to inspect it later and see if the client socket stays open during long running requests. In case of a crash there is some chance the coordinator would dump its process dictionary to the logs. So it seems prudent to remove sensitive headers from it before saving it in the process dictionary.
=> Remove sensitive headers from the mochiweb request in pdict

src/couch_replicator/src/couch_replicator_parse.erl, src/couch_replicator/src/couch_replicator_utils.erl
By default, erlang does not recognise wildcards in Server Name Indication fields (which is bizarre but they seem committed to this error).
Fortunately they also ship a function that does validate them, you just have to hook it up.
So here we do that hooking up.
We are following the published advice at https://www.erlang.org/doc/man/ssl.html#type-customize_hostname_check;
> Customizes the hostname verification of the peer certificate, as different protocols that use TLS such as HTTP or LDAP may want to do it differently. For example the get standard HTTPS handling provide the already implememnted fun from the public_key application for HTTPS. `{customize_hostname_check, [{match_fun, public_key:pkix_verify_hostname_match_fun(https)}]}`
N/A
=> Use HTTP rules for hostname verification

src/mango/src/mango_cursor_view.erl
Add a missing `eunit` case for testing error handling of `mango_cursor_view:handle_message/2`.  This was noticed while working on #4735, but I feel it is better to factor this piece out and submit in a separate (and dedicated) commit.
```
```
The coverage of `mango_cursor_view` should jump from 99% to 100%.
=> fix(`mango`): plug hole in unit test coverage of view cursor functions

src/chttpd/src/chttpd_util.erl
A follow-up commit to deddbb2 where a typo was noticed in the contents after it has been merged.
=> fix(`chttpd`): comment typo

nouveau/build.gradle
The automatic loading of test framework implementation dependencies has been deprecated. This is scheduled to be removed in Gradle 9.0. Declare the desired test framework directly on the test suite or explicitly declare the test framework implementation dependencies on the test's runtime classpath. Consult the upgrading guide for further information:
https://docs.gradle.org/8.3/userguide/upgrading_version_8.html#test_framework_implementation_dependencies
N/A
N/A
=> fix gradle deprecation warning

src/chttpd/src/chttpd_node.erl, src/docs/src/api/server/common.rst, src/smoosh/src/smoosh_channel.erl, src/smoosh/src/smoosh_persist.erl, src/smoosh/src/smoosh_priority_queue.erl, src/smoosh/src/smoosh_server.erl, src/smoosh/test/smoosh_tests.erl
Adding the status of the CouchDB auto-compaction daemon to the HTTP API.
Old behavior / result if called from `remsh`:
```
smoosh:status().
{ok,[{"upgrade_dbs",
[{active,0},{starting,0},{waiting,[{size,0}]}]},
{"slack_dbs",[{active,0},{starting,0},{waiting,[{size,0}]}]},
{"slack_views",
[{active,0},{starting,0},{waiting,[{size,0}]}]},
{"upgrade_views",
[{active,0},{starting,0},{waiting,[{size,0}]}]},
{"index_cleanup",
[{active,0},{starting,0},{waiting,[{size,0}]}]},
{"ratio_views",
[{active,0},{starting,0},{waiting,[{size,0}]}]},
{"ratio_dbs",
[{active,0},{starting,0},{waiting,[{size,0}]}]}]}
```
The function `smoosh:status/1` returns now an Erlang map, so that it can be used directly with `send_json/3`.
Calling it from a `remsh` session, the result is the following:
``` …
```
=> Add new HTTP endpoint `/_node/_local/_smoosh/status`

rel/overlay/bin/remsh
Fixed #4783 remsh extract wrong NODE name from ERL_FLAGS
There is bug sed regex `echo "$ERL_FLAGS" | sed 's/^.*name \([^ ][^ ]*\).*$/\1/g'`. If there are no `-name ` in env ERL_FLAGS will get whole string.
=> remsh extract wrong NODE name from ERL_FLAGS

src/couch/priv/stats_descriptions.cfg, src/couch/src/couch_os_process.erl, src/couch/test/eunit/couch_js_tests.erl
When evaluating various JS engine versions it's useful to track not just error metrics, but also how fast commands execute. To avoid creating a large number of histograms, and keep the metrics count reasonable, keep track of the total accumulated time spent on  some of the more frequently used commands.
To reduce counting json serialization into the JS processing time, move the writejson/2 and writeline/2 logic into the `prompt` callback. The time delta, is then taken after the data is serialized, and after it's deserialized from readjson/1. The reason for the asymmetry is that response data could be streamed back byte-by-byte, so in that case to keep it simpler, opt to record the times after json had already been parsed.
Take advantage of updating couch_js_module and switch it to use the …
=> Add extra timing stats for couch_js engine commands

src/couch/priv/stats_descriptions.cfg, src/couch/src/couch_os_process.erl, src/couch/test/eunit/couch_js_tests.erl
Just tracking total time spent in each individual query prompt may be ambiguous, unless we also keep track of the number of calls of each prompt type.
For instance, if we notice the total time spent per some call increasing, it could be because the JS engine got slower, or, because some other bottleneck was removed and now we can run more total map calls per unit of time. To disambiguate between these cases let's also track the total number of calls. This way users would be able to estimate the average time spent per call more accurately.
=> Add calls counts to couch_js engine time stats

src/docs/src/api/database/find.rst
The semantics of Mango's `use_index` query parameter has changed over time but this has not been reflected in the documentation, which causes a lot of confusion.
The `use_index` parameter was introduced in 1b0426aa to force the index selection to a specific index.  Unfortunately, this did not work out well in practice, so 743bd882 added a fallback mechanism to make it less brittle.  With that, `use_index` became only a "hint" not an "instruction".
=> fix(`docs`): amend description of `use_index` on `/{db}/_find`

src/custodian/src/custodian_util.erl, src/fabric/src/fabric_db_create.erl, src/fabric/src/fabric_db_delete.erl, src/mem3/src/mem3_shards.erl
When we're raising the error with the args list [1], the format for the args is a list of arguments not a single arg. So the previous invocations of `erlang:error(database_does_not_exist, ?b2l(Id))` would produce a args list of individual database name characters [2].
[1] https://www.erlang.org/doc/man/erlang#error-2
[2] > mem3_shards:opts_for_db(<<"doesnotexit">>).
```
** exception error: database_does_not_exist
in function  mem3_shards:opts_for_db/11
called as mem3_shards:opts_for_db(100,111,101,115,110,111,116,101,120,105,116)
```
=> Fix incorrect raising of database_does_not_exist error

src/mango/src/mango_cursor_nouveau.erl, src/mango/src/mango_cursor_text.erl, src/mango/test/24-text-paginated-test.py, src/mango/test/mango.py
When an interleaved update happens to a `text` index while it is being queried, the affected documents might appear duplicated in the collected results.  That is because `search` results are paginated where the boundaries might move due to the updates and the document might show up once more on subsequent queries.
Mitigate the situation by tracking and losing duplicated documents while the results are being streamed to the user.
In addition to that, the `mango` unit test coverage has increased:
- Test cases: 196 ⟶ 216
- `mango_cursor_text`: 0% ⟶ 100%
- Total: 55% ⟶ 62%
```shell
make mango-test MANGO_TEST_OPTS="24-text-paginated-test"
```
Note that `mango-test` requires a running Clouseau instance that is hooked up, while `eunit` does not.
The change would remove …
=> fix(`mango`): prevent occasional duplication of paginated `text` results

src/mango/src/mango_cursor_nouveau.erl, src/mango/src/mango_cursor_text.erl
This is a follow-up to #4782.  Commits d6d4ad97 and ce2607a5 missed out on the necessity of keeping the bookmark updated all the time.  Otherwise the same hits might be returned which can lead to an infinite loop at the processing and make the integration test suite hang, for example.
This change is covered by the existing unit and integration tests.
=> fix(`mango`): correct the fix for the duplicated `text` results

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
We saw repeated failures on some CI nodes, possibly from them being throttled
by hex.pm. To mitigate it, try to setup package caches for hex, gradle, pip and
npm.
So far it works with Docker builder only but requires that cache directories in
/home/jenkins are owned by the `jenkins` user. That has to happen as part of
the Jenkins node setup. Nodes controlled from couchdb-infra-cm have been
updated to have those directories and permission however the ARM64 one doesn't
yet, so we're excluding it temporarily.
=> Configure hex, gradle, pip and npm caches.

src/docs/src/install/unix.rst
We don't need curl since we don't have Javascript tests.
=> Remove suggestion to install curl/libcurl

src/mango/test/03-operator-test.py
Previously, Mango tests which only apply to JSON indexes were being skipped if the clouseau (text index) service was enabled for the CouchDB instance being tested against, resulting in tests being skipped in some CI cases.
This refactors the tests so that we execute these tests on JSON / all_docs indexes regardless of whether clouseau is present or not.
`make mango-test` with / without clouseau enabled.
Note that `nose2` will report skipped tests in the `Ran N tests` output. With this change, we see the same number of tests executed when `clouseau` is not enabled:
Before:
```
Ran 373 tests in 11.328s
OK (skipped=146)
```
After:
```
Ran 368 tests in 12.104s
OK (skipped=141)
```
With `clouseau` enabled we see fewer skipped tests after this change (so more overall):
Before:
```
Ran 373 tests …
```
=> mango: do not skip json tests when clouseau installed

src/docs/src/install/unix.rst
Add Ubuntu 22.04 Jammy Jellyfish as  supported OS in documentation. Deb packages for couchdb are available for that distribution.
=> docs: Add Ubuntu 22.04 Jammy Jellyfish as supported OS

src/couch/priv/stats_descriptions.cfg, src/couch/test/eunit/couch_js_tests.erl
Some were misnamed:
* exists -> exits
* process_prompt_errors is just errors
* description of process_errors was incorrect
Some were missing:
* process_error_exits was not defined in the cfg file
=> Fix a few couch_os_process metrics

src/couch_index/src/couch_index_server.erl
Previously, an index and opener process dying could have resulted in the index gen_server crashing. This was observed in the CI test as described in: https://github.com/apache/couchdb/issues/4809
The process in more detail was as follows:
* When an async opener result is handled in the index server, there is a period of time when the index server is linked to both the index and the opener process.
* After we reply early to the waiting clients, a client may do something to cause the indexer to crash, which would crash the opener along with it. That would generate two `{'EXIT', Pid, _}` messages queued in the indexer process' mailbox.
* The index gen_server, is still processing the async opener result callback, where it would remove the opener from the `openers` table, then it returns `ok` …
=>  Prevent delayed opener error from crashing index servers

src/couch_index/src/couch_index_compactor.erl
Noticed on a few production instances, we run a potentially long compaction, and when done, the call to commit the compacted state times out after 5 seconds. That, in turn, triggers are a `compaction_failed` call, which also may timeout and the whole thing crashes.
Since we have the ioq scheduler running and we're doing disk IO, compaction swap may be delayed in the background, and take longer than 5 seconds. Opt to wait however long it takes or crash for some other reason. gen_server calls already auto-monitor and check for called process's exits.
=> Wait for compacted indexes to flip.

src/docs/src/api/database/find.rst
The description of the `field_mismatch` reason code is missing a "not" in the documentation of the `/{db}/_explain` endpoint hence it has the opposite meaning.
=> docs(`find`): add missing negation on talking about field mismatch

src/docs/src/api/database/find.rst, src/mango/src/mango_idx_view.erl, src/mango/src/mango_selector.erl, src/mango/src/mango_selector_text.erl, src/mango/test/03-operator-test.py, src/mango/test/25-beginswith-test.py
Adds a `$beginsWith` operator to selectors, with json and text index support. This is a compliment / precursor to optimising `$regex` support as proposed in https://github.com/apache/couchdb/pull/4776.
For `json` indexes, a $beginsWith operator translates into a key range query, as is common practice for _view queries. For example, to find all rows with a key beginning with "W", we can use a range `start_key="W", end_key="W\ufff0"`. Given Mango uses compound keys, this is slightly more complex in practice, but the idea is the same. As with other range operators (`$gt`, `$gte`, etc), `$beginsWith` can be used in combination with equality operators and result sorting but must result in a contiguous key range. That is, a range of `start_key=[10, "W"], end_key=[10, "W\ufff0", {}]` would be …
=> mango: add $beginsWith operator

src/mango/src/mango_idx_view.erl, src/mango/src/mango_selector.erl, src/mango/test/25-beginswith-test.py
In the initial implementation of `$beginsWith`, the range calculation for view indexes mistakenly appends an integer with the size of 8 bits which gets maxed out at FF, rather than building a binary with an extra 3 bytes at the end.
This PR fixes the `mango_idx_view:range/5` by correctly appending the `U+FFFF` code point to create a utf-8 encoded binary. Additionally, the Erlang `utf8` binary type ensures the result is a valid utf8 string. If `Arg` is not a utf8 binary, this will throw a badarg error.
`U+FFFF` is used instead of `U+10FFFF` as it's the highest sorting code point according to the collator rules.
We expect `Arg` strings to be a valid utf8 but, to be safe, `mango_selector:norm_ops/1` is enhanced to verify that any argument to `$beginsWith` is a utf8 string.
`make mango-test` …
=> mango: fix $beginsWith range

src/setup/src/setup.erl
Previously, in the setup app, we set admin creds but didn't wait for them to be hashed. The next setup step then could fail with the 401 error.
Since we're doing setup, let's wait for the newly set creds to be hashed before continuing.
=> Wait for newly set admin creds to be hashed in setup

configure, src/mango/src/mango_cursor_view.erl
Upgrade erlfmt to v1.3.0 and apply the new formatting rules.
N/A
N/A
=> update erlfmt to 1.3.0 and fix issues

src/ets_lru/src/ets_lru.erl, src/ets_lru/test/ets_lru_test.erl
Previously, when an existing cache entry was updated, we didn't update the atime. Subsequently, when the entry was removed, we never cleaned the orphan atime entry. During trimming, we traverse the atime entries, and since the orphaned one didn't have any matching objects or ctime entries, the ets_lru cache would crash, possibly taking down the primary couch supervisor.
=> Fix update bug in ets_lru

src/ets_lru/src/ets_lru.erl, src/ets_lru/test/ets_lru_test.erl
add `max_idle` option, which evicts items by last access time (as opposed to `max_lifetime` which evicts based on creation time).
N/A
Will be used by https://github.com/apache/couchdb/pull/4814
=> add eviction for idleness to ets_lru

src/ets_lru/src/ets_lru.erl
We don't really need a strictly monotonic integer, just a unique key for each atime and ctime entry. `unique_integer([monotonic])` is also a concurrency bottleneck as indicated the warning in [1].
Even in a sequential context, it's slower:
```
> timer:tc(fun() -> [erlang:unique_integer([monotonic]) || _ <- lists:seq(1,1000000)], ok end).
{434637,ok}
> timer:tc(fun() -> [make_ref() || _ <- lists:seq(1,1000000)], ok end).
{322988,ok}
```
[1] https://www.erlang.org/docs/21/man/erlang#unique_integer-1
=> Replace unique_integer with a ref in ets_lru

src/chttpd/src/chttpd_auth_request.erl, src/chttpd/test/eunit/chttpd_handlers_tests.erl
Previously we relied on the replication endpoint authentication only, let's also add authentication for the request itself.
=> Require auth for _replicate endpoint

build-aux/Jenkinsfile.full, src/fast_pbkdf2/rebar.config
This reverts commit 0ac61812beb09353ae90de482b52f86c34a2301f.
=> Revert "Temporarily disable MacOS runner"

src/chttpd/src/chttpd_misc.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_util_test.erl, src/couch/src/couch_httpd_misc_handlers.erl, src/couch/src/couch_task_status.erl, src/couch/test/eunit/couch_task_status_tests.erl
We observed on at least one busy cluster couch_task_status gen_server would not be able to keep up with task updates and `all` task fetching calls. The singleton gen_server would start to get unbounded message backups, where the only solution was to restart couch application.
To help with that there are at least two optimizations we can do:
1) Avoiding blocking `couch_task_status` gen_sever when fetching all task
properties. That operation now happens outside of the gen_server in the `all` function.
2) Use a set ets instead of an ordered set ets table. Previously, in CouchDB
1.x, we relied on the ordered ets table to keep a sorted task list, however with clustering in CouchDB 2.x+ we had to call lists:sort/1 on the task result anyway, so there is no reason to waste time maintaining an …
=> Optimize _active_tasks

.devcontainer/devcontainer.json, Makefile, Makefile.win, README-DEV.rst, build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr, configure, configure.ps1, dev/run
Provide a way to the developers to deploy and launch the Clouseau search module more easily, therefore making it more accessible. This can help with running the Search-based Elixir tests as well as the Mango `text` search tests.  This could allow us to catch more bugs ahead of time and might even inspire more improvements in the area.
The extension is designed in a way to make it simple to integrate with the CI — only the Java environment of the proper version needs to be deployed, everything else could be managed from this repository.  Such as bumping the version of Clouseau or fine-tuning the configuration parameters.
This is an opt-in feature on two levels.  First, one has to tell `./configure --enable-clouseau` to instantiate Clouseau locally. This will create the `clouseau` …
=> feat(`dev`): add Clouseau to the developer setup

dev/run
The `./dev/run` script requires a boot script to be compiled which assumes a completed build of the source tree.  If this did not happen, the script fails to work and CouchDB cannot be started up.
The failure of the boot script's compilation by itself does not necessarily help to understand the reason, so enhance it with a suggestion for the user.
The behavior should change when one tries to run the `./dev/run` script without calling `make`.  This can also be simulated by running `make devclean` and `make clean` if the source have already been build before.  This intended to be an improvement for the developer experience, it should not break anything.  Instead, there shall be less confusion around this unhappy case.
=> chore(`dev`): provide better error message on `make` missing before `run`

test/elixir/lib/couch/dbtest.ex, test/elixir/test/cookie_auth_test.exs, test/elixir/test/reader_acl_test.exs, test/elixir/test/security_validation_test.exs, test/elixir/test/users_db_security_test.exs, test/elixir/test/users_db_test.exs
* Reset _users db before and after use to avoid polluting other tests.
* Use a common reset db and "wait for auth cache" helper function
* Since we're testing chttpd auth don't bother also setting httpd authentication_db, that just stops and resets the local port httpd listener, but we're not testing backend auth.
* Use a retry in login for security db to avoid flakiness
=> Attempt to fix flaky users db security test

src/mango/test/16-index-selectors-test.py
In `16-index-selectors-test.IndexSelectorText.test_uses_partial_index_with_non_indexable_selector`, the parametrization of the `create_text_index()` is incorrect.  It passes `["location"]` as a set of fields to index, but that is actually taken as an analyzer.  It is probably a result of copy-and-pasting over from the `json` index creation above where the first parameter to the corresponding function is the list of fields.
=> fix(`mango`): test `text` index creation

dev/run
Using Python 3.12.0 for `dev/run` gives these warnings:
```
❯ dev/run -a adm:pass --with-haproxy --no-eval REMSHID=1 dev/remsh
/Users/jay/repos/couchdb/dev/run:534: SyntaxWarning: invalid escape sequence '\d'
JAVA_VERSION_RE = re.compile('"(\d+\.\d+).*"')
/Users/jay/repos/couchdb/dev/run:686: SyntaxWarning: invalid escape sequence '\['
"^\[httpd\]$",
/Users/jay/repos/couchdb/dev/run:694: SyntaxWarning: invalid escape sequence '\['
"^\[native_query_servers\]$",
```
This changes the strings in question to "raw" format, and eliminates the warnings.
Installing Python `3.12.0` and running e.g.
```
dev/run -a adm:pass --with-haproxy --no-eval REMSHID=1 dev/remsh
```
should not display any `SyntaxWarning`s.
=> Convert some regex strings to raw format

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_external.erl, src/chttpd/src/chttpd_util.erl, src/chttpd/test/eunit/chttpd_external_test.erl
We're already doing it for the cached request object in the process dictionary so it makes sense to do it for the external json requests as well.
For compatibility, allow reverting to previous behavior using the `[chttpd] scrub_json_request` config setting.
=> Add an option to scrub some sensitive headers from external json requests

Makefile, dev/run
Keep it only for eunit tests for now.
Make cluster setup for integration tests use retries to avoid flakes. Since we don't have two separate dev/run modes we can also clean up some code from dev/run.
=> Do not use admin party for integration tests

Makefile, Makefile.win, README-DEV.rst, configure, configure.ps1, dev/run, src/mango/test/06-basic-text-test.py
This change features a set of extensions to the integration of Clouseau in the developer setup, added in 2d8a33b9:
- Introduce the `--clouseau-dir` option for the `./dev/run` script to allow for ad-hoc integration of Clouseau with CouchDB, even without being configured previously.  This facilities experimentation with various alternatives and lets the user switch between them with ease.
- The directory specified by `--clouseau-dir` could either hold an unpacked set of JAR files or `git` clone of the Clouseau source code.  The script can automagically determine which version is being used and invoke [Apache Maven](https://maven.apache.org/) to compile the sources and launch the nodes with the proper classpath.  In this latter case, check for JDK 1.7 because that is the edition that could …
=> feat(`dev`): make the Clouseau development flow more flexible

rel/files/eunit.config, rel/files/eunit.ini
We dump the logs to Jenkins console on failure, but when the volume of the logs is too large, it locks the browser and make it impossible to inspect. This should reduce the logging volume about 10MB instead of 40MB and hopefully make it more manageably to inspect in the browser.
=> Reduce EUnit log noise

dev/run
Noticed nouveau elixir tests still throw `connection refused` errors in the `finish_cluster` setup step. So try to make all the http requests in dev/run use retries. That also helps us DRY out some repeating bits like header auth and json application content type.
We also had an odd `import catch error then import again` clause. I don't think we intend this to work on python 2 any longer so I cleaned that up as well.
=> More flaky fixes for cluster setup

src/couch/test/eunit/couch_js_tests.erl
Fix the following error by increasing the timeout.
Error logs:
```
::in function gen_server:call/3 (gen_server.erl, line 385)
in call from couch_proc_manager:get_proc/1 (src/couch_proc_manager.erl, line 90)
in call from couch_query_servers:get_os_process/1 (src/couch_query_servers.erl, line 713)
in call from couch_js_tests:should_exit_on_internal_error/1 (test/eunit/couch_js_tests.erl, line 378)
in call from eunit_proc:run_test/1 (eunit_proc.erl, line 531)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 356)
in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 514)
**exit:{timeout,
{gen_server,call,
[couch_proc_manager,
{get_proc,
{client,undefined,undefined,<<"javascript">>,undefined, …
```
=> Fix flaky tests by increasing timeout

src/chttpd/test/eunit/chttpd_auth_tests.erl, src/config/src/config.erl, src/config/src/config.hrl, src/config/src/config_writer.erl, src/config/test/config_tests.erl, src/docs/src/config/intro.rst
Remove support for delete markers, and improve consistency of config values following deletion.
Calling the persistent variation of `config:delete("section", "key")` writes `key =` to the most significant `.ini` file, internally referred to as a "delete marker" which, [according to the docs](https://docs.couchdb.org/en/stable/config/intro.html#setting-parameters-via-the-configuration-file), should cause all previous values of `key` in the `.ini` file chain to be ignored, and sets the value to the atom `undefined`.
Currently, `config:reload` [ignores delete markers](https://github.com/apache/couchdb/issues/4892). Also, since `config:delete` doesn't reload values from `.ini` files at all, using the persistent variation may result in temporarily returning an inconsistent value until the …
=> Remove support for delete markers and improve config consistency

src/couch/src/couch_passwords.erl
Parts of the codebase depend on being able to pass in `nil` as the expected hash (e.g, if the user doesn't exist).
In commit 21c2dec1d4 I enhanced couch_passwords:verify/2 to use OTP 25's new `crypto:hash_equals/2` function, but foolishly omitted the final fallback clause of our original `verify/2` function. This PR restores it.
=> couch_passwords:verify should always return false for bad inputs

src/chttpd/src/chttpd_db.erl
This ensures that the coordinator process flushes on demonitoring of the attachment refs in chttpd_db. The problem here is that it's possible to receive a 'DOWN' message for the monitor ref that is not receive'ed, causing it to stick around in the coordinator message queue while the next http request is handled. The pending message will not become apparent until the next fabric call is invoked, as fabric expects to have full access to all messages in the calling process, an expectation which is violated by the pending message, causing a case clause crash in the fabric receive message callbacks.
I noticed this during eunit runs with stubbed attachment handles that generate an immediate noproc message on the monitor call. Normal operations should not result in an immediate noproc result on …
=> Flush chttpd_db monitor refs on demonitor

src/couch/src/couch_multidb_changes.erl, src/couch_replicator/test/eunit/couch_replicator_scheduler_docs_tests.erl
couch_multidb_changes is in charge of monitoring changes to multiple databases. It is what drives the couch_replicator application when users update replication docs. It starts off by scanning all the local db shards and launches changes feeds for each of them. After it processes each changes feed, it checkpoints where it stops. As the shards are updated, it starts change feeds for those updated shards and checkpoints again. The checkpoints are kept in an ets table and the main logic which decides when to start a changes feed for a particular shard is in the resume_scan/2 function.
This change makes a few small optimizations:
* Use a map to track Pid -> DbName mappings. This avoids using a O(N) operation for looking up exiting change feed processes. So `pids` is switched to be a map of …
=> Optimize and clean up couch_multidb_changes

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
The versions are:
* 24.3.4.15
* 25.3.2.8
* 26.2.1
Related: https://github.com/apache/couchdb-ci/pull/65
https://hub.docker.com/repository/docker/apache/couchdbci-debian/general https://hub.docker.com/repository/docker/apache/couchdbci-ubuntu/general https://hub.docker.com/repository/docker/apache/couchdbci-centos/general
=> Use the latest Erlang versions in CI

src/docs/src/api/database/changes.rst
* Remove redundant mention of `_changes resource` since it's already describing that resource.
* Explicitly enumerate all `filter` parameter options with references to doc section below for each.
* Explain the unexpected interaction between ``include_docs``, ``all_docs`` style and filtering, how the winning document body is returned even if it doesn't pass the filtering criteria.
* Update `POST _changes` doc to say that besides `doc_ids` it is used for selector filtering. Also, add an example of using a selector.
=> Improve changes feed API documentation

src/docs/requirements.txt, src/docs/src/conf.py
Add the sphinx-copybutton extension to get this functionality for code blocks.
Before:
After:
=> Add extension for copying code blocks with just one click

dev/run
Noticed we still get connection refused errors for nouveau tests cluster setup tests. Try to handle retries for connection errors which are thrown not just due to a status code. After retries are exhausted, then fail as before.
=> Improve retries in dev/run cluster setup

src/mango/src/mango_cursor_text.erl, src/mango/src/mango_cursor_view.erl, src/mango/src/mango_execution_stats.erl, src/mango/test/15-execution-stats-test.py
Besides the execution statistics that could be shown for the user, the number of rows and documents read are tracked separately on the global level.  (Which is more like a bug than a feature, but that is out of the scope of this change.)
With the introduction of covering indexes, these two have been become different, therefore global counting has to be taught about the number of times when no documents were read but rows only.  For `text` indexes, the number of rows and documents should be the same, the distinction makes sense only for `json` indexes.
The changes are covered by the respective portion of the tests:
```shell
make mango-test
```
The global stats should always report the same values as it is added for the (Mango) execution stats.
=> fix(`mango`): communicate rows read for global stats collection

Makefile, Makefile.win, configure, configure.ps1, dev/run, nouveau/src/main/java/org/apache/couchdb/nouveau/core/IndexManager.java, rel/nouveau.yaml, rel/overlay/etc/default.ini, rel/reltool.config
Move the generation/templating of nouveau.yaml to couchdb side to make packaging of nouveau simpler and more consistent with the rest.
=> Control nouveau.yaml in configure and dev/run

src/docs/src/install/freebsd.rst
The documentation on how to have CouchDB installed and enabled as a service on FreeBSD contains a number of outdated information. This change is to bring it to up to date along the following lines:
- The port/package has been renamed to `couchdb3`.
- The configuration options and location for the configuration files for the port have changed.
- Propagate the `service` command to work with the wrapper script instead of accessing the script itself directly.
- Mention the binary package path (installation via `pkg`) which has become quite a standard these days.
- Remove instructions on manually creating the `couchdb` user and group.  There is no need for those any more, it shall be handled by the port/package.
=> fix(docs): revamp the installation instructions for FreeBSD

dev/run
refinement of https://github.com/apache/couchdb/pull/4957 to match maybe_boot_clouseau.
=> implement this same as maybe_boot_clouseau

build-aux/Jenkinsfile.full
The CI container images have been updated and now they include support for running Clouseau with them.  Throw the switch and let Clouseau configured and used to extend the coverage.
The FreeBSD builder is not yet enabled due to failures that have been fully investigated.
See #4954 for the build logs and preliminary validation.
=> chore(Jenkins): enable Clouseau for more platforms

src/couch/src/couch_multidb_changes.erl, src/couch_replicator/priv/stats_descriptions.cfg, src/couch_replicator/src/couch_replicator_db_changes.erl, src/couch_replicator/src/couch_replicator_doc_processor.erl, src/couch_replicator/src/couch_replicator_scheduler.erl, src/docs/src/api/server/common.rst
couch_multidb_changes module is monitoring shards whose names match a particular suffix, and notifies users with found, updated and deleted events. This is the module which drives replicator jobs when `*/_replicator` databases are updated.
Previously, couch_multidb_changes reacted only to node-local shard file events and was not aware of the shard map membership of those files. This was mostly evident during shard moves: the target shard could be created long before the
shard file becomes a part of the shard map. The replicator could notice the new target shard file and spawn a replication job on the new node, but keep the same replication job running on the source node. The two replication jobs will eventually conflict in the PG system (https://www.erlang.org/doc/man/pg.html) and one of …
=> Make multidb changes shard map aware

src/fabric/src/fabric_db_purged_infos.erl
Previously, the new `_purged_infos` endpoint, would return the same purge requests multiple times when it received multiple responses from workers. Instead, we should uniquify the same requests, and return just a single copy of the purge request to the user.
Add a unit test to check multiple copies being returned and properly handling set updating and finalizing.
=> Handle multiple response copies for _purged_infos API

build-aux/Jenkinsfile.full
I was notified it has be rebuilt. In the meantime it would be nice to keep our green passing streak going in the full CI.
=> Exclude PPC64LE CI worker temporarily

build-aux/Jenkinsfile.full
Previously it had issues downloading from hex.pm
=> Let's see if we can re-enable s390x again

test/elixir/test/password_cache_test.exs
In this test we have to wait for 5 seconds as that's the hardcoded timeout in the hash worker. However let's try to wait just a bit longer (+500msec) in case there a race condition or some schedulers are blocked.
=> Try to fix password test timeout

dev/run
The `--node-number` parameter is not interpreted correctly so that the node identifiers are shifted everywhere in the same way.  For example, the lead port and node ports are assigned with no regard to what was set as the starting node index.
This could be a problem if, for example, one wants to simulate mixed-version cluster configurations and launch a set of nodes starting from a given index and use another invocation of the script to run another set of nodes with different subset of indexes.
There are no automated tests, but this can be tried out manually.  For example, with Clouseau enabled, setting the node number to 2, both the ports and the Clouseau indexes are shifted:
```console
$ make devclean
$ dev/run -a adm:pass --with-clouseau --node-number=2 -n 2
[ * ] Setup environment ... …
```
=> fix(`dev/run`): handling node number configuration

.gitignore
This directory can be created via the `--enable-clouseau` configuration flag, so ignore it.
=> Git ignore top level `clouseau` directory

.asf.yaml
~~Add additional branch checks before merging a PR.~~
~~1. Require a linear history for better redability.~~
~~2. Disable "merge commits".~~
~~3. Require at least one approval.~~
Edited:
As a first smaller change, add at least one approval before merging a PR.
=> Add at least one approval before merging a PR

src/couch_event/src/couch_event.app.src, src/couch_event/src/couch_event_server.erl
Noticed when debugging an OTP 25 memory leak that couch_event_server didn't behave well when the system was overloaded. It blocked and prevent even process info inspection or is_alive checks:
```
> s:pinfo(whereis(couch_event_server)).
...blocked...
> erlang:is_process_alive(whereis(couch_event_server)).
...blocked...
```
Added almost 100% test coverage for the couch_event_server module.
To check performance created a benchmark module to test various number of concurrent updaters and listeners:
https://gist.github.com/nickva/892ab91e9880f0dd311ac4a8f63440ef
With khash
```
> couch_event_bench:go().
N Register Unreg. EvtLatency
1  21.0  22.0  77.9
10  13.3  12.5  69.59
100  7.96  12.34  86.206
1000  9.95  14.309  390.0194
10000  10.5752  9.4972  1684789.26177
ok
```
With maps
```
> …
```
=> Replace khash with maps in couch_event_server

dev/run
run tests on Windows too; change path handling
=> feat(`nouveau`): change path handling on Windows (and *nix) for tests

src/docs/src/config/couchdb.rst
Server instance is easily misunderstood. It can be interpreted as if there should be a unique UUID per node.
=> Change server instance to cluster for UUID docs

src/chttpd/test/eunit/chttpd_changes_test.erl, src/couch/src/couch_changes.erl, src/couch/test/eunit/couch_changes_tests.erl, src/fabric/src/fabric_rpc.erl, src/fabric/test/eunit/fabric_changes_test.erl
- When filered `_changes` is triggered, `open_revs()` will
read docs. If request parameter has `include_docs=true`,
then `doc_member()` will also read docs.
Change `filter/3` to `filter/5` to avoid the above behavior.
- When using filtered `_changes` with `style=all_docs`,
`conflicts=true` and `include_docs=true`, the response should
contain the `_conflicts` field.
Add `open_all_revs_include_doc/2` to include this field.
- Add tests to verify the number of calls to `open_doc/3`.
```bash
make eunit apps=chttpd suites=chttpd_changes_test
make eunit apps=couch suites=couch_changes_tests
```
=> Avoid read docs twice when filtered `_changes` is triggered

src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_http.erl, src/couch_replicator/src/couch_replicator_fabric.erl, src/couch_replicator/src/couch_replicator_fabric_rpc.erl, src/couch_replicator/src/couch_replicator_httpd.erl, src/couch_replicator/test/eunit/couch_replicator_scheduler_docs_tests.erl, src/fabric/include/fabric.hrl, src/fabric/src/fabric.erl, src/fabric/src/fabric_rpc.erl, src/fabric/src/fabric_view.erl, src/fabric/src/fabric_view_all_docs.erl, src/fabric/src/fabric_view_map.erl, src/fabric/src/fabric_view_reduce.erl, src/fabric/src/fabric_view_row.erl, src/fabric/test/eunit/fabric_tests.erl, src/mango/src/mango.hrl, src/mango/src/mango_cursor_view.erl
The `#view_row{}` record that is used for capturing messages with row data is not flexible enough to have it extended easily.  If one wanted to introduce a fresh field, the change would have to be propagated through many functions and modules.  Especially, if support for mixed-version clusters is a concern, this would come with some degree of duplication.
Leverage Erlang/OTP's built-in maps for mitigating this issue and offer the view callbacks the `view_row_map` Boolean key in `#mrargs.extra` to request this communication format.  This way the old record-based format would be still in use unless requested otherwise.  This facilitates the smooth interoperability of old coordinators and new workers.  In parallel to that, the new coordinator could still receive view rows from old workers. …
=> feat(`fabric`): switch to maps for view rows

src/couch_replicator/src/couch_replicator_fabric.erl, src/couch_replicator/src/couch_replicator_fabric_rpc.erl, src/couch_replicator/test/eunit/couch_replicator_scheduler_docs_tests.erl
When a job is completing, there is a period of time when the document isn't updated yet with the state, and it's also not present in the scheduler ets table. In that case we return `nil`, but we don't account for that case in the _scheduler/docs fabric calls.
To fix it, account for `nil` whenever we get the doc state.
=> Fix case clause error in replicator _scheduler/docs response

src/chttpd/src/chttpd_node.erl, src/couch/src/couch_debug.erl, src/mem3/src/mem3.erl, src/mem3/src/mem3_distribution.erl, src/mem3/test/eunit/mem3_distribution_test.erl
* Monitor nodes membership in mem3_distribution and log unexpected `nodedown` reasons.
* Enhance mem3_distribution gen_sever to keep track of the last few events for each node. This can help detect nodes flapping or disconnecting often.
* Expose the last few events from mem3_distribution in the .../_system endpoint, besides the already existing dist packet stats metrics.
* Add `ping_nodes(...)` debug function. Use it to ping all connected nodes. This can help detect a still connected but slow network connection.
* Add `dead_nodes(...)` debug function. Use it to detect a partitioned cluster, where some nodes may not be connected to each other.
=> Improve dist diagnostics

src/nouveau/src/nouveau_fabric_search.erl
reported in https://github.com/apache/couchdb/issues/5002
the badrecord is because we execute the second clause of handle_message and mess up the internal state (just returning the Counters rather than a state record around it)
=> nouveau: fix rexi_DOWN clause

src/fabric/src/fabric_view_row.erl, src/mango/src/mango_cursor_view.erl, src/mango/test/15-execution-stats-test.py
In case of map-reduce views, the arrival of the `complete` message is not guaranteed for the view callback (at the shard) when a `stop` is issued during the aggregation (at the coordinator).  Due to that, internally collected shard-level statistics may not be fed back to the coordinator which can cause data loss hence inaccuracy in the overall execution statistics.
Address this issue by switching to a "rolling" model where row-level statistics are immediately streamed back to the coordinator.  Support mixed-version cluster upgrades by activating this model only if requested through the map-reduce arguments and the given shard supports that.
Note that this change shares some similarities with @chewbranca's work on Couch Stats Resource Tracker though it stems from a different origin.  In …
=> feat(`mango`): rolling execution statistics

test/elixir/test/changes_async_test.exs
Try to prevent failures like:
```
1) test continuous filtered changes (ChangesAsyncTest)
src/couchdb/test/elixir/test/changes_async_test.exs:193
Expected truthy, got false
code: assert Enum.member?(changes_ids, "rusty")
arguments:
["bingo"]
"rusty"
stacktrace:
src/couchdb/test/elixir/test/changes_async_test.exs:220: (test)
```
`make elixir`
=> Fix flaky changes async test

nouveau/src/main/java/org/apache/couchdb/nouveau/core/ser/NullWrapper.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/ser/PrimitiveWrapper.java, nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/Lucene9Index.java, nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexSchema.java, nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/NouveauQueryParser.java, nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexTest.java, nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/NouveauQueryParserTest.java, src/docs/src/api/ddoc/nouveau.rst, src/docs/src/ddocs/nouveau.rst, src/mango/src/mango_cursor_nouveau.erl, src/mango/src/mango_selector_text.erl, test/elixir/test/config/nouveau.elixir, test/elixir/test/nouveau_test.exs
Nouveau has a (somewhat ugly) extension to the query syntax that auto-detects if the searched _value_ is a number. if so,
it switches to querying the field as a number.
If, however, you've indexed a string that looks like a number, this behaviour prevents you from querying the field correctly.
Instead of that, this PR switches to the 'normal' approach in Lucene, namely the StandardQueryParser with a "points config"
that details which fields are numbers. With this extra information the query parser performs the correct kind of query for text or string fields that happen to have values that look like numbers and double fields, which actually have numbers.
The fundamental problem is that we don't declare a schema ahead of time, so we don't know which fields are numbers and which are not. In …
=> use PointsConfigMap so numeric query and numeric range query work cleanly

src/couch_mrview/src/couch_mrview_index.erl
When we upgrade empty view files from 2.x, we end up skipping the commit. Subsequently, we will see a "wrong signature" error when the view is opened later. The error is benign as we'd end up resetting an empty view, but it may surprise an operator. To avoid this, ensure to always commit after upgrading old views.
Issue: https://github.com/apache/couchdb/issues/4994
=> Always commit if we upgrade 2.x view files

rebar.config.script, rel/overlay/etc/default.ini, rel/reltool.config, src/couch_scanner/README.md, src/couch_scanner/include/couch_scanner_plugin.hrl, src/couch_scanner/src/couch_scanner.app.src, src/couch_scanner/src/couch_scanner.erl, src/couch_scanner/src/couch_scanner_app.erl, src/couch_scanner/src/couch_scanner_checkpoint.erl, src/couch_scanner/src/couch_scanner_plugin.erl, src/couch_scanner/src/couch_scanner_plugin_ddoc_features.erl, src/couch_scanner/src/couch_scanner_plugin_find.erl, src/couch_scanner/src/couch_scanner_rate_limiter.erl, src/couch_scanner/src/couch_scanner_server.erl, src/couch_scanner/src/couch_scanner_sup.erl, src/couch_scanner/src/couch_scanner_util.erl, src/couch_scanner/test/eunit/couch_scanner_test.erl, src/docs/src/config/index.rst, src/docs/src/config/scanner.rst
An application to scan the cluster with a plugin system to report various things about databases and documents. The initial idea was to have something like this to scan all the javascript design docs to check for compatibility with the new QuickJS engine. It had since been split apart from the QuickJS branch and made into a separate pull request.
The current implementation includes two plugins:
* couch_scanner_plugin_find : scan for regexes in doc bodies
* couch_scanner_ddoc_features : report various design doc features
A more detailed description is in the README.md file. The plugin API is defined in the `couch_scanner_plugin` module. There are additional details in the comments in the included Erlang modules. What follows is as summary description
of some of the implementation details …
=> Couch Scanner

src/couch_scanner/src/couch_scanner_plugin.erl, src/mem3/test/eunit/mem3_bdu_test.erl
Sometimes eunit tests leave design docs behind and the scanner would crash with a case clause error. Test cleanup is fixed in its own commit, however it's possible for users to have their own design documents, so we should handle that case anyway.
=> Account for possible design docs in shardmap

build-aux/Jenkinsfile.full
I pinged people at AWS a few times since last year but got no response so far. Remove the entry as it seems the program is either discontinued or they don't want to support Apache CouchDB any longer.
=> WorksOnArm Amazon instance seems to be gone for good

src/fabric/src/fabric.erl, src/fabric/src/fabric_bench.erl, src/fabric/test/eunit/fabric_tests.erl, src/mem3/src/mem3.erl, src/mem3/src/mem3_shards.erl
Previous version was awfully inefficient: we only need the dbname, but we opened each document body, parsed the shards out of it, generated Q*N shards, then put them in a list and usorted them back down to a list of dbnames.
We don't use this in many places (mem3 security sync, fabric bench) but it might be nice to have an efficient version of it anyway.
=> Optimise fabric:all_dbs()

src/docs/src/intro/overview.rst
Conflicts are not purged while compaction and have to be deleted manually
There is a little error in the docs, stating that conflicts could be purged during compaction. This is removed because its not correct.
- [ x] Documentation changes were made in the `src/docs` folder
=> Fix small detail about conflicts in overview.rst

Makefile.win, src/docs/setup.bat
Add an equivalent setup script for Windows to
init python dev environment for building docs.
=> Create Python virtualenv on Windows for docs

nouveau/build.gradle
This release is addressing [CVE-2024-22201](https://github.com/advisories/GHSA-rggv-cv7r-mw98)  via upgrade to Jetty 11.0.20.
N/A
N/A
=> upgrade dropwizard to 4.0.7

build-aux/Jenkinsfile.full
Remove deprecated buster, centos 7 and bionic.
=> Update CI OSes

build-aux/Jenkinsfile.full, src/docs/requirements.txt, src/mango/requirements.txt
Some dependencies were held back due to older CentOS and Ubuntu, now we can update them.
Try to replace CentOS7 with CentOS9 in the full CI and use the "no spidermonkey whatsoever" CI variant as well.
Full CI green pass: https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/jenkins-update-repos-and-reqs/5/pipeline
=> Update a few deps and improve CI

build-aux/Jenkinsfile.full
Better than not running any tests at all for now, at least.
FreeBSD ARM64 tests are green in full CI tests again:
=> On ARM64 FreeBSD use QuickJS

rel/overlay/etc/default.ini, src/couch/src/couch_httpd_auth.erl
Users of JWT rightly expect tokens to be considered invalid once they expire. It is a surprise to some that this requires a change to the default configuration. In the interest of security we will now require a valid `exp` claim in tokens. Administrators can disable the check by changing `required_claims` back to the empty string.
We do not add `nbf` as a required claim as it seems to not be set often in practice.
N/A
https://github.com/apache/couchdb/issues/5046
=> JWT: require valid `exp` claim by default

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
Previously we tried to run the VDU query prompt even if there was not VDU. That would have yielded a match anyway as both result in an error, but it added noise to the logs.
Handle the missing VDU like we handle the missing filters in filter_doc_validate.
=> Handle missing VDU better in In QuickJS scanner plugin

src/fabric/include/fabric.hrl, src/fabric/src/fabric_view_changes.erl
`#changes{}` record and old `complete` format was deprecated 10 years ago [1].
While at it, cleanup un-necessarily long arg per line call formats.
Coincidentally, this also improve code coverage a bit:
```
fabric_view_changes           :  72% (pr)
fabric_view_changes           :  71% (main)
```
[1] https://github.com/apache/couchdb/commit/865b5555771e6099c9b34b1b14d2428ce02e50c3
=> Cleanup a few clauses in fabric_view_changes

src/docs/src/api/database/find.rst
RFC-8259 discourages using duplicate keys in JS/JSON, and the ECMA-262 standard explicitly says that the last key will overwrite the first key.
This probably means these never actually worked!
=> Fix duplicate keys in find query

src/couch_replicator/src/couch_replicator_auth_session.erl
Previously, replicator auth session plugin crashed if additional cookie headers were added besides the default `AuthSession` one.
Fix replicator session plugin to consider only `Set-Cookie` headers with `AuthSession` set and ignore others.
Co-Authored-By: Robert Newson
Fix: #5064
=> Handle multiple Set-Cookie headers in replicator session plugin

configure, rebar.config.script, src/couch_scanner/include/couch_scanner_plugin.hrl, src/mango/src/mango.hrl, src/mango/src/mango_cursor_view.erl
* Updates a few dependencies
* Don't use maybe as a type name, it's a reserved keyword
* Don't update map literals in a row, it now emits a warning
=> Enable Erlang/OTP 27

src/fabric/src/fabric_bench.erl, src/fabric/test/eunit/fabric_bench_test.erl
`{error, timeout}` sometimes fails, especially on FreeBSD workers.
So handle errors in the docs callback and also half the batch size.
Example of error:
```
module 'fabric_bench_test'
fabric_bench_test:99: -with/1-fun-1- (t_default_doc_size)...*failed*
in function fabric_bench:all_docs_cb/2 (src/fabric_bench.erl, line 179)
called as all_docs_cb({error,timeout},7)
```
=> Fix flakiness in fabric_bench

rel/reltool.config.script
Erlang 26 removed the ability to create ez archive files in releases. We had to remove the `excl_archive_filters` option from our reltool.config file [1], as otherwise we couldn't make releases on 26 (`make release` barfed). However, that meant on 24 and 25 our releases would be generated with beam files packed in lots of silly .ez archives, which is not great.
Sadly, since 26, refuses to silently ignore `excl_archive_filters` we have to use a script file and only apply the config on <26 versions.
[1] https://github.com/apache/couchdb/commit/a4bbb87d11d40dfee9808a7d5025a65845c6a4cd
=> Prevent release from generating ez archives

src/fabric/src/fabric_view.erl
Since we use meck:expect(...) in a few places in the test suite, we should run `meck:unload()` in teardown. To make it more obvious we're mocking things, explicitly use meck:new() in setup as well.
=> Make sure to unload mecked modules in fabric_view

src/couch_quickjs/.gitignore, src/couch_quickjs/build_js.escript, src/couch_quickjs/priv/.gitignore
Previously, the `.gitignore` file in priv was mainly there to keep the directory around in git. But that's a bit dirty as the debian packager will complain if we package the `.gitignore`, as it packages the whole `priv` directory.
To fix, move the `.gitignore` entries to the app's main `.gitignore`, and make sure to create and clean the whole priv directory as needed.
=> Move priv direcotry gitignore from quickjs app to main gitignore

rel/reltool.config, src/setup/src/setup.app.src
Previously, some apps/release used `git` version others had a fixed version number. Each approach has it's benefits and downsides but since we're using git in most cases, let's be uniform and use that uniformly.
=> Make app and release versions uniform

rebar.config.script
https://github.com/davisp/jiffy/releases/tag/1.1.2
=> Bump jiffy to 1.1.2

Makefile, Makefile.win, nouveau/src/main/java/org/apache/couchdb/nouveau/api/SearchRequest.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/Index.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/IndexManager.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/StaleIndexException.java, nouveau/src/test/java/org/apache/couchdb/nouveau/health/IndexHealthCheckTest.java, src/nouveau/src/nouveau_api.erl, src/nouveau/src/nouveau_index_updater.erl, src/nouveau/src/nouveau_rpc.erl
Ensure index is up to date when querying
the IndexHealthCheckTest exposed a sequence of events that lead to
test failure, but also point to an undesirable state during production.
Namely;
1) an index is opened
2) an index is updated
3) the IndexManager closes the index due to LRU pressure, and rolls back
the changes in step 2
4) an index is queried, which returns results that don't reflect the
changes made in step 2.
This change modifies the SearchRequest so that the caller can ensure
the index is at least up to a certain sequence.
Some attributes are added to IndexManager member variables to clarify
their valid ranges.
add --rerun to the test goal so we can run the tests again even if
the code under test has not changed.
=> Ensure index is up to date when querying

nouveau/src/main/java/org/apache/couchdb/nouveau/health/IndexHealthCheck.java, nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexTest.java
Set minSeq so we can tell if the health check fails for conflict versus something else (a conflict can arise if the index was rolled back between the update and the search, by the IndexManager LRU)
=> Use the minSeq check in more places and add a test

nouveau/build.gradle, nouveau/src/main/java/org/apache/couchdb/nouveau/NouveauApplication.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/Index.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/IndexManager.java, nouveau/src/test/java/org/apache/couchdb/nouveau/health/IndexHealthCheckTest.java
Use our own logic for index management
Caffeine complaines when eviction is slow (because we might commit the index).
Build our own logic for opening and closing indexes which allows opening and
closing to be very slow, while ensuring we don't close an index that's in use.
N/A
=> Use our own logic for index management

src/nouveau/src/nouveau_index_manager.erl
Hard to induce in a unit test but under stress it is possible to get back Reason's like `{timeout, {gen_server, call, ...` among others. Pass these along to the client processes and do not crash the manager.
With this patch we log anything that wasn't `ok` but always reply with whatever `Reason` was so clients aren't left waiting.
=> don't crash nouveau_index_updater for any DOWN Reason

nouveau/src/main/java/org/apache/couchdb/nouveau/core/IndexManager.java
fixes regression in https://github.com/apache/couchdb/pull/5088 where once over capacity we'd never return to below maxIndexesOpen.
=> close oldest indexes before opening new if over capacity

share/server/dispatch-quickjs.js, src/couch/test/eunit/couch_js_tests.erl, src/couch_quickjs/c_src/couchjs.c, src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl, src/couch_scanner/include/couch_scanner_plugin.hrl
A few QuickJS Improvements
1. Make QuickJS memory limits match Spidermonkey
Spidermonkey only sets the stack limit size, so do the same for QuickJS.
This changes how the oom test behaves and since already have two oom tests remove the flaky one.
2. Make QuickJS dispatch respond with an error instead of throwing a null
For some internal errors, especially when bumping into memory limits, a null exception is thrown, instead of re-throwing try to behave like the SM loop.js and other error handling by returning an error line and then indicating we shouldn't continue. This way process crashes will be reserved for segfaults and such.
3. Improve QuickJS scanner plugin
* Be more resilient to errors, so we log the errors but do not get do not get stuck forever retrying to rescan the same …
=> Quickjs Fixes

rel/files/couchdb.cmd.in
After removing the version number from `start_erl.data` and updating the startup script in [1], we forgot to update the Windows startup script. Let's make up for this now.
[1] https://github.com/apache/couchdb/pull/5085
=> Simplify couchdb.cmd.in and remove app version

rel/files/eunit.ini
This interval is used for scheduling jobs as well as for polling in the multidb changes module. Use a shorter default in tests to catch more edge case and possibly avoiding the need to set a per-test shorter interval.
=> Use a shorter replicator scheduling interval for tests

src/exxhash/README.md, src/exxhash/c_src/xxhash.c, src/exxhash/c_src/xxhash.h
https://github.com/Cyan4973/xxHash/releases/tag/v0.8.2
Notably there is a speedup improvements and fixes on PowerPC and s390x, as well some ARM variants.
Otherwise, it's mostly comments and doxygen updates.
=> Update xxhash from upstream

configure
This was introduced in 99b5331ce9 to support a snap package and not removed when we removed the snap option in e9d703c2139cd
=> remove last remnant of snap install

Makefile, Makefile.win
Previously, they were in server but should be in share/server
To verify:
`./configure && make && make release`
cd to rel/couchdb
add admin/pass user to ./etc/local.ini
start ./bin/couchdb
goto to `http://localhost:5984/_utils/#/verifyinstall` and run "verify"
that builds a view which uses the js files
Fixes: https://github.com/apache/couchdb/issues/5112
=> Ensure js files end up in the correct release directory

src/config/src/config.erl, src/config/src/config_app.erl, src/config/test/config_tests.erl
Previously we expanded the paths once at startup and then cached them.
Now we keep the directories around and expand them on reload.
Fixes: https://github.com/apache/couchdb/issues/5111
=> Make sure config reload finds new .ini files in .d directories

src/chttpd/src/chttpd_db.erl, src/couch/src/couch_httpd_db.erl, test/elixir/test/copy_doc_test.exs
closes #5117
The COPY handler did not validate the target doc id, allowing the insertion of doc ids that begin with `_`, which is prohibited by all other document creation methods.
unit tests
https://github.com/apache/couchdb/issues/5117
=> Validate target doc id for COPY method

src/couch_quickjs/patches/01-spidermonkey-185-mode.patch, src/couch_quickjs/quickjs/Makefile, src/couch_quickjs/quickjs/libregexp.c, src/couch_quickjs/quickjs/tests/test262.patch
Relevant fixes:
* regexp: fix non greedy quantizers with zero length matches https://github.com/bellard/quickjs/commit/36911f0d3ab1a4c190a4d5cbe7c2db225a455389
=> Update QuickJS from upstream master

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
* Fix incorrect handling of view `lib`s. These should be under `views` not at the top level.
* Reduce false positive log noise when both results fail with a similar errors like compilation errors or a common TypError but their exact message format will be different. An example I noticed was:
```
{error,{throw,{compilation_error,<<"SyntaxError: unexpected token in expression: 'if' ...
{error,{throw,{compilation_error,<<"Expression does not eval to a function. ...
```
* Make the scanner a bit more resilient and skip unsupported junk like map/views/filters that are not the expected object or types. Previously we assumed if they exist (not undefined) or they will be valid.
=> More QuickJS scanner improvements

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr, mix.exs
Erlang: 25.3.2.13, 26.2.5.2
Elixir was also updated to: 1.17.2 in the images.
[Full CI passes](https://ci-couchdb.apache.org/blue/organizations/jenkins/jenkins-cm1%2FFullPlatformMatrix/detail/jenkins-erlang-25.3.2.13/1/pipeline/847) with the new images
=> Update Erlang in CI, support Elixir 1.17

build-aux/Jenkinsfile.full
It's not coming back from an upgrade and reboot cycle and we'd like to keep our full CI green until the issue is resolved.
=> Exclude PPC64LE worker for now

src/config/src/config.erl, src/config/test/config_tests.erl, src/couch/src/couch_bt_engine_header.erl
Validate epoch transitions
We've learned that `node()` can return `nonode@nohost` in a distributed
node while it is crashing (if net_kernel dies, say, but perhaps other causes).
We've assumed this can never happen, and have seen cases where `nonode@nohost`
has been recorded in the epoch list.
Tighten the code so we get the node name from the init arguments instead as these
are immutable.
Also validate that the associated update sequence never goes down (it can stay the
same, which happens if the file is copied from one machine to another).
=> Validate epoch transitions

src/couch_log/src/couch_log_writer_file.erl, src/couch_log/src/couch_log_writer_journald.erl, src/couch_log/src/couch_log_writer_stderr.erl, src/fabric/src/fabric_rpc.erl, src/mem3/src/mem3.erl, src/mem3/src/mem3_nodes.erl, src/mem3/src/mem3_rep.erl, src/mem3/src/mem3_reshard.erl, src/mem3/src/mem3_reshard_job.erl, src/mem3/src/mem3_reshard_store.erl, src/mem3/src/mem3_rpc.erl, src/mem3/src/mem3_seeds.erl, src/mem3/src/mem3_shards.erl, src/mem3/src/mem3_sync.erl
Continuation of https://github.com/apache/couchdb/pull/5132
Use the persistent node name in cases where the node may end up persisted on disk:
* shard map (dbs db)
* nodes db
* checkpoints (purge, internal replicator, reshard jobs)
* resharding job ids
* changes sequences
* logging
* nodes database
=> Use permanent node names in more applications

build-aux/Jenkinsfile.full
We got some assistance hard rebooting it.
It turns out my `apt update` was stuck while updating docker. I tried a soft reboot `sudo reboot` and that made it and not come back.
It looks good now after running `dpkg reconfigure ...` to finish package updates, and then did another `apt update &$ upgrade &$ sudo reboot` to make sure it comes back up.
=> Bring PPC64LE worker back

src/chttpd/src/chttpd.erl, src/couch/src/couch_emsort.erl, src/couch/src/couch_key_tree.erl, src/couch/src/couch_util.erl, src/couch_prometheus/src/couch_prometheus_util.erl, src/couch_replicator/src/couch_replicator_api_wrap.erl, src/rexi/src/rexi.erl, src/rexi/src/rexi_utils.erl
Local external calls are fairly simple: it's when we use the function in the module via the external reference. Previously, with hotcode upgrades that might have made sense, but currently it doesn't, maybe even adds a tiny bit of overhead on each call. A couple of these were cleaned up in chttpd module.
Unused externals are functions which are exported but not used anywhere.
In some cases we didn't even use the function at all, like in the case of `stream_init/1,2` or `rexi:stream/1,2,3` we can remove their bodies as well.
Since `stream_init` is removed, update the `init_stream` as per https://github.com/apache/couchdb/issues/5122, where we noticed that the newer `init_stream` doesn't actually update the timeout metric, so before cleaning up `stream_init` move that to the `init_stream`.
=> Remove unused external functions and local external calls

rel/overlay/etc/default.ini, src/docs/src/config/cluster.rst, src/fabric/src/fabric_view.erl, src/rexi/src/rexi.erl, src/rexi/src/rexi_server.erl, src/rexi/src/rexi_sup.erl, src/rexi/src/rexi_utils.erl
Continuing the cleanup started in #5143
The `server_per_node` setting had been defaulted to `true` for the last 6 years. Default it to `true` always. However, keep the `rexi_server` around for longer so that mixed cluster upgrades continue working.
The `kill_all` optimization has been enabled since 3.3.3. We can remove any calls to rexi:kill/1 and replace with rexi:kill_all/1 leaving the server handling of `{kill, ...}` messages in for longer to allow mixed cluster upgrades from older nodes.
`async_server_call` code is not used anywhere, so that's also cleaned up.
[1] https://github.com/apache/couchdb/pull/1627
=> Cleanup deprecated and unused functionality in rexi

src/chttpd/src/chttpd_node.erl, src/chttpd/test/eunit/chttpd_misc_test.erl, src/rexi/src/rexi.erl, src/rexi/src/rexi_server_mon.erl
We have aggregate couch_server and index server metrics, but rexi server and buffers, which are also sharded were missing, so this commit adds them.
In addition noticed we didn't have an test for `/_system` test so added one which check most of the functionality: base VM metrics, computed, aggregated and simple message queue length, etc.
=> Add aggregate rexi server and rexi buffer message queue metrics

src/dreyfus/src/dreyfus_fabric.erl, src/dreyfus/src/dreyfus_fabric_group1.erl, src/dreyfus/src/dreyfus_fabric_group2.erl, src/dreyfus/src/dreyfus_fabric_search.erl, src/fabric/src/fabric_streams.erl
We added client monitoring [1] for streaming fabric requests (_all_docs, _change, etc), but never added them to dreyfus since it's not using the streams abstraction.
Add client monitoring to dreyfus but exporting a few internal functions from `fabric_stream`, otherwise the pattern is the same:
* Start a client monitor process with the set of initial workers to monitor the coordinator and the client socket connection state.
* In case of replacements, update the monitor with the newly spawned replacement workers.
* On cleanup, call the previous `fabric_stream:cleanup/1` function, and also stop the monitor process.
[1] https://github.com/apache/couchdb/commit/d5701f437183c3742aab5812e298d5bb80cb0c15
=> Add passively closed client monitoring to search

src/rexi/src/rexi_buffer.erl, src/rexi/src/rexi_server_mon.erl, src/rexi/test/rexi_buffer_tests.erl, src/rexi/test/rexi_tests.erl
Previously, the rexi_buffer metric reported just the mailbox size of the buffers. However rexi buffers are special as they themselves act as explicit message queues, and current length of those explicit buffers wasn't reflected anywhere in metrics.
So, improve the metric usefulness and reflect both the explicit and the implicit queue lengths.
There was already an existent `gen_buffered_count` gen_server call, however since the buffers could potentially be in the hot path, avoid using and instead use a persistent term + a counter scheme similar how we do for all couch_stats metrics.
In addition, noticed that rexi had no tests at all. It is of course, battle tested in production, but since we made changes to it, added some tests to cover the changed bits.
=> Ensure rexi_buffer metric includes the internal bufferd messages

src/couch_replicator/src/couch_replicator_fabric.erl, src/fabric/src/fabric_streams.erl, src/fabric/src/fabric_view_all_docs.erl, src/fabric/src/fabric_view_map.erl, src/fabric/src/fabric_view_reduce.erl, src/rexi/src/rexi.erl, src/rexi/test/rexi_tests.erl
Previously, if the coordinator process is killed too quickly, before the stream worker cleanup process is spawned, remote workers may be left around waiting until the default 5 minute timeout expires.
In order to reliably clean up processes in that state, need to start the cleaner process, with all the job references, before we start submitting them for execution.
At first, it may seem impossible to monitor a process until after it's already spawned. That's true for regular processes, however rexi operates on plain references. For each process we spawn remotely we create a reference on the coordinator side, which we can then use to track that job. Those are just plain manually created references. Nothing stops us from creating them first, adding them to a cleaner process, and only then …
=> Improve worker cleanup on early coordinator exit

rebar.config.script, src/couch/src/couch_ejson_size.erl
Synced couchdb-recon with upstream ferd/recon to 2.5.5 
Fix compiler warnings for Erlang/OTP 26
Fixes #5153.
=> fix(dev): Upgrade recon and fix Erlang/OTP 27 compiler warnings

nouveau/build.gradle
We encounter issues launching nouveau on Windows as it cAnnoT haNdle LoNG LiNEs iN ScripTs. Instead we list the dependency jars in the manifest and only need to include one jar in the classpath.
NB: I really dislike how I construct the name of the jar file, as I'm sure it must just be available in a variable already.
=> Put classpath in main jar manifest

src/couch_replicator/src/couch_replicator_fabric.erl, src/fabric/include/fabric.hrl, src/fabric/src/fabric_streams.erl, src/fabric/src/fabric_view_all_docs.erl, src/fabric/src/fabric_view_changes.erl, src/fabric/src/fabric_view_map.erl, src/fabric/src/fabric_view_reduce.erl
Previously, we performed cleanup only for specific errors such as `ddoc_updated`, and `insufficient_storage`. In case of other errors, or timeouts, there was a chance we would leak workers waiting to be either started or canceled. Those workers would then wait around until the 5 minute rexi timeout fires, and then they emit an error in the logs. It's not a big deal as that happens on errors only, and the processes are all waiting in receive, however, they do hold a Db handle open, so they can waste resources from that point of view.
To fix that, this commit extends cleanup to other errors and timeouts.
Moreover, in case of timeouts, we log fabric worker timeout errors. In order to do that we export the `fabric_streams` internal `#stream_acc` record to every `fabric_streams` user. That's a …
=> Improve fabric streams cleanup on error and timeouts

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_scanner/src/couch_scanner_plugin.erl
Noticed a few more expected error clauses we could handle to reduce log noise.
It should handle `{vdu_doc,{error,{throw,{<<"TypeError">>,{Stack..}}}}, ...}` cases.
Also noticed that the scanner might leave a db opened and not close if it throws an exception from a loop, so be more resilient and put it in the `after` clause of a `try`.
=> A few more quickjs scanner fixes

src/couch/src/couch_server.erl
We close the lru via make_room/2 only. Nothing seems to call gen_server call, so let's not keep it around as it's confusing when inspecting the already tricky lru cache logic.
=> Removed unused close_lru gen_server call

src/couch/src/couch_bt_engine_header.erl
When updating various places to use persistent node names, we forgot probably one of the most important one: the epoch list in the header.
Continuation of: #5138
=> Use persistent node name in a new header

src/couch/src/couch_lru.erl
Previously, couch_lru used `unique_integer([monotonic,positive])` to generate incrementing integer keys. That call take a global VM lock [1]:
> Strictly monotonically increasing values are inherently quite expensive to generate and scales poorly.
This is especially bad now that we have sharded couch_server instances, each with it's own LRU. We don't want them all to bottleneck waiting on each other to generate their integers.
[1] https://www.erlang.org/doc/apps/erts/erlang.html#unique_integer/1
=> Remove unique_integer bottleneck from couch_lru

src/couch_replicator/priv/stats_descriptions.cfg, src/docs/src/api/server/common.rst
The metric is not needed any longer as of #5093 so we're just cleaning it up.
=> Remove replicator stability metric

mix.exs
This is mostly a min version setting. 1.13 is pretty old by this point. The only time it would fail is when Elixir `< 1.15` or `> 2` would be used.
=> Update min Elixir version to 1.15

src/couch/test/eunit/couchdb_os_proc_pool.erl
The `wait_tagged_idle_count/1` function already [performs an assertion](https://github.com/apache/couchdb/blob/main/src/couch/test/eunit/couchdb_os_proc_pool.erl#L654) on the idle count, so the final `?assertEqual` is both redundant, and also apparently racy based on this test failure:
```
::in function couchdb_os_proc_pool:if_no_tagged_process_found_new_must_be_spawned/1 (test/eunit/couchdb_os_proc_pool.erl, line 397)
in call from eunit_proc:run_test/1 (eunit_proc.erl, line 543)
in call from eunit_proc:with_timeout/3 (eunit_proc.erl, line 368)
in call from eunit_proc:handle_test/2 (eunit_proc.erl, line 526)
in call from eunit_proc:tests_inorder/3 (eunit_proc.erl, line 468)
in call from eunit_proc:with_timeout/3 …
```
=> Remove redundant and racy assertion

src/couch_replicator/src/couch_replicator_doc_processor.erl
The config value uses seconds, it's a legacy value we maintained after updating couch_replicator in [1]. Previously, the value was used as milliseconds when in fact it was seconds.
[1] github.com/apache/couchdb/pull/5093
=> Fix units in replicator cluster_start_period

configure.ps1
When Windows users decide to disable SpiderMonkey, it is likely the case they do not have it installed either.  In those scenarios it makes no sense to check for the presence of the static libraries.  Instead, `configure.ps1` fails to proceed untruly, which has to be fixed.
On Windows the following invocation of `configure.ps1` should just work when no SpiderMonkey is installed:
```console
.\configure.ps1 -DisableSpiderMonkey
```
Note that the current version of [`apache/couchdb-glazier`](https://github.com/apache/couchdb-glazier) will just install SpiderMonkey unconditionally.  Before testing with that, it must be made sure that the SpiderMonkey installation is not accessible.
=> fix(`configure.ps1`): do not test SpiderMonkey libs when it is disabled

configure, configure.ps1, dev/run
The latest version of Clouseau now fixes the incompatibility issue with OTP 26 and later (*), so pull that in and remove the related checks.
At the same time, replace SLF4J Simple with [Logback Classic](https://logback.qos.ch/) since that has been the standard logging backend for a while.  Note that Clouseau is still shipped with SLF4J API 1.7, which supports Logback up to 1.2 only.
(*) Thanks @jaydoane!
Configure with Clouseau enabled (UNIX-like systems, including macOS):
```console
./configure --with-clouseau
```
or on Windows:
```console
.\configure.ps1 -WithClouseau
```
Run the Mango tests (which should automatically utilize Clouseau):
```console
make mango-test
```
Run the Elixir search tests (which should automatically utilize Clouseau):
```console
make elixir-search
```
This should …
=> chore(`clouseau`): bump to 2.23.1

build-aux/Jenkinsfile.full
It stopped working as of https://github.com/apache/couchdb/pull/5180. It works for all the other CI runners and locally on at least two macos dev machine. We tried to debug it a bit in dev but without a result, there was no clouseau.log file create yet to dump.
It can still be debugged and investigated on a `jenkins-*` branch, but for now, try to restore the CI back to a green state.
=> Exclude clouseau from macos full CI variant

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
This is generated by our own dispatch loop [1] as a catch-all. It emits a traceback so will always look different across engine. We handle it as an expected error so it doesn't pollute the logs with false positives.
[1]
https://github.com/apache/couchdb/blob/d38f14f7d777b7cda79b9862ee304150ad3418ea/share/server/loop.js#L159
=> Account for another expected error in quickjs scanner

src/couch/src/couch_util.erl, src/couch/test/eunit/couch_util_tests.erl, src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
After scanning some production clusters, noticed that QuickJS and SM 91 seems to be using a different json order than SM 1.8.5. A KV proplist ejson prompt result could show up as a compatibility issue when the JSON key order is different.
To fix it, use maps instead of ejson KVs. Could have just used a jiffy:encode/decode pair, but it seemed wasteful to serialize everything when we just want to transform the proplists so created a small utility function.
=> Fix json order false positives in quickjs scanner plugin

src/docs/src/config/scanner.rst
Plugin skip section can be full regexes, not just plain strings.
Initially they were just plain strings, but since the `find` plugin got regexes, it was easy to just re-use the same logic. In the meantime, I forgot to update the docs.
=> Correct scanner docs

src/chttpd/test/eunit/chttpd_changes_test.erl, src/fabric/src/fabric_view_changes.erl
=> End continuous feed after emitting limit number of rows

src/chttpd/src/chttpd.erl, src/chttpd/test/eunit/chttpd_invalid_path_test.erl
Currently a path that doesn't begin with a `/` causes a no match error and crash. This can fill up logs with unwanted junk, and be generally annoying.
```
2024-08-23 17:54:26.603 08/23 17:54:26.603 somehost db13  -              CRASH REPORT Process  (<0.19262.7388>) with 0 neighbors crashed with reason: no match of right hand value {"..\\..\\..\\..\\..\\..\\..\\..\\..\\..\\windows\\win.ini",[],[]} at chttpd:handle_request_int/1(line:239) <= mochiweb_http:headers/6(line:140) <= proc_lib:init_p_do_apply/3(line:240); initial_call: {mochiweb_acceptor,init,['Argument__1','Argument__2',...]}, ancestors: [chttpd,chttpd_sup,<0.1261.0>], message_queue_len: 0, links: [<0.1450.0>,#Port<0.891112>], dictionary: [{couch_rewrite_count,0}], trap_exit: false, status: running, heap_size: 610, stack_size: …
```
=> Abort response when path doesn't start with slash

src/chttpd/test/eunit/chttpd_changes_test.erl, src/docs/src/whatsnew/3.4.rst, src/fabric/src/fabric_view_changes.erl
Previously, `_changes?feed=continuous&descending=true&limit=N` with `N` greater than total rows would block and wait on database changes. On each change the first few sequence rows (sequences `1-...`, `2-...`) were repeatedly emitted. The new behavior is to return after all the rows are emitted.
Fix: #5203
=> Fix reverse continuous changes feeds with limit greater than total

nouveau/build.gradle
toggle the native access support for Lucene (requires launching with `java -jar` in packages/scripts though)
=> enable native access for Lucene

Makefile, Makefile.win
Stale Elixir dependencies can cause test failures after upgrading Erlang or Elixir, so remove them whenever we `make clean`.
Confirm it removes Elixir test artifacts.
```
❯ mix deps.compile
❯ tree -L 3 _build/
_build/
└── dev
└── lib
├── b64url
├── bunt
├── couchdbtest
├── credo
├── file_system
├── httpotion
├── ibrowse
├── jason
├── jiffy
├── junit_formatter
├── jwtf
└── ssl_verify_fun
15 directories, 0 files
❯ make clean
❯ tree -L 3 _build/
_build/
0 directories, 0 files
```
=> Clean elixir build artifacts with `make clean`

src/chttpd/src/chttpd.erl, src/docs/src/config/http.rst
Allow configuration of signature algorithms and allowed ECC curves
closes https://github.com/apache/couchdb/issues/5211
=> allow further TLS configuration of clustered port

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
Handle a SyntaxError as expected. This is raised, for instance by `JSON.parse([])`.
=> Another QuickJS expected error

src/couch_replicator/src/couch_replicator_auth_session.erl
Use the new `uri_string:resolve/2` [1] function instead.
This should fix handling for IPv6 addresses.
Fix: #5223
[1] https://www.erlang.org/doc/apps/stdlib/uri_string.html#resolve/2
=> Fix bespoke parsing/composing in couch_replicator_auth_session

rel/overlay/etc/default.ini, src/couch/src/couch_auth_lockout.erl, src/couch/src/couch_httpd_auth.erl, src/couch/src/couch_primary_sup.erl, src/docs/src/config/auth.rst, src/ets_lru/src/ets_lru.erl, test/elixir/test/auth_lockout_test.exs, test/elixir/test/config/suite.elixir
Enhance couchdb to efficiently reject requests for a given user if repeated requests have failed for authentication reasons, from the same IP address. This helps slow brute-force password attacks and is especially helpful if each authentication attempt is very expensive (pbkdf2 with a high iteration count, typically).
will be covered by automated tests
=> Temporary account lockout for repeated auth failure

rel/files/eunit.ini, rel/overlay/etc/default.ini, src/couch/src/couch_auth_lockout.erl, src/couch/src/couch_password_hasher.erl, src/couch/src/couch_passwords.erl, src/couch/src/couch_users_db.erl, src/docs/src/whatsnew/3.4.rst
* enable the lockout protections against online password attacks
* increase workfactor of new PBKDF2 hashes to protect against offline password attacks
=> enhance default security of passwords

src/couch/src/couch_password_hasher.erl
only upgrade password hashes if there is a user doc
N/A
https://github.com/apache/couchdb/pull/4814
=> only upgrade password hashes if there is a user doc

src/docs/src/api/database/bulk-api.rst
Update the documentation for /{db}/_bulk_get to reference the /{db}/{docid} query parameters.  This code indicates that they share the same query parsing function:
```
bulk_get_parse_doc_query(Req) ->
lists:foldl(
fun({Key, Value}, Args) ->
ok = validate_query_param(Key),
parse_doc_query({Key, Value}, Args)
end,   
#doc_query_args{},
chttpd:qs(Req)
).
```
- https://github.com/apache/couchdb/issues/5236
=> Bulk get query documentation

src/couch_quickjs/src/couch_quickjs.erl, src/couch_quickjs/test/couch_quickjs_tests.erl
We used to quote the spawnkiller path like this to handle spaces in paths:
```
"\"" ++ filename:join(PrivDir, "couchspawnkillable") ++ "\""
```
So we stick with the same pattern here as well for QuickJS path.
=> Quote QuickJS path

configure.ps1
Additional detections:
- if we are in a release tarball and don't have proper, disable it
- use quickjs, if spidermonkey isn't available and/or set
=> (dev): Align both configure scripts (*nix / Windows) even more

src/couch/src/couch_debug.erl
Fix an annoying terminal pop-up issue on Windows and the test leaving processes behind.
=> Fix debug test

Makefile
`@mix clean --deps` apparently requires hex to be installed. If it's not there, it stops and prompts the user to install it. If configure hasn't run yet, as in the case when building our deb package from the dist tarball, package build fails.
This was mitigated in couchdb-pkg by adding hex to `/home/jenkins/.mix` for CI images, but let's also handle it better in the Makefile.
Makefile.win already has `|| true` added to it so no need to updated it.
=> Don't fail make clean if hex is not installed

src/couch/test/eunit/couch_work_queue_tests.erl
The following test constantly fails in Windows, so double the timeout:
Before:
```
module 'couch_work_queue_tests'
Single producer and consumer
Queue with 3 max items
couch_work_queue_tests:145: -should_have_no_items_for_new_queue/1-fun-1-...ok
undefined
*** instantiation of subtests failed ***
**in function couch_work_queue_tests:produce/4 (test/eunit/couch_work_queue_tests.erl, line 379)
in call from couch_work_queue_tests:should_block_producer_on_full_queue_count/1 (test/eunit/couch_work_queue_tests.erl, line 205)
**error:{assertion_failed,[{module,couch_work_queue_tests},
{line,382},
{reason,"Timeout asking producer to produce an item"}]}
```
After:
```
module 'couch_work_queue_tests'
Single producer and consumer
Queue with 3 max items
couch_work_queue_tests:145: …
```
=> [tests]: Increase timeout for producer test

src/couch/src/couch_httpd_auth.erl, src/couch/src/couch_password_hasher.erl
Restores the original ability from https://github.com/apache/couchdb/commit/3e8286d40664fa0d7f32a3d375f64e64d181022c and https://github.com/apache/couchdb/commit/f9b549e68d40df01683867de22779d21fe0b90d0 to have extra context when updating user creds
=> pass AuthCtx from get_user_creds to update_user_creds

src/docs/src/whatsnew/3.4.rst, version.mk
Merge the two commits from 3.4.x to main.
The way this was generated:
```
$ git checkout -b 3.4.x-merge-to-main
Switched to a new branch '3.4.x-merge-to-main'
$ git rebase main
warning: skipped previously applied commit 84cad523e
warning: skipped previously applied commit ea8add932
warning: skipped previously applied commit 46ec0c82c
warning: skipped previously applied commit 27950e539
warning: skipped previously applied commit 106873ded
hint: use --reapply-cherry-picks to include skipped commits
hint: Disable this message with "git config advice.skippedCherryPicks false"
Successfully rebased and updated refs/heads/3.4.x-merge-to-main.
```
git successfully figured out the rebased commits were already applied except the two new ones.
=> 3.4.x merge to main

src/docs/src/api/database/common.rst
The default value of q is 2 when creating a database.
=> chore(docs): correct default q value in POST /{db}

rel/overlay/etc/default.ini, src/couch_event/src/couch_event.erl, src/couch_event/src/couch_event_server.erl
There are two improvements to the `couch_event_server` as separate commits:
* Switch to use an off-heap message queue.
* Do not rely on the default gen_server timeout, that just made things worse in production.
=> Improve couch event server

src/docs/src/ddocs/nouveau.rst
Update docs, nouveau dropped the old infinity/-infinity from dreyfus/clouseau as part of https://github.com/apache/couchdb/pull/5021 but the docs were not updated till now.
N/A
Closes https://github.com/apache/couchdb/issues/5271
=> Nouveau uses the normal lucene syntax for unbounded range

src/docs/src/config/scanner.rst
In the new scanner docs I used `$plugin` while in other parts of the docs we had `{...}` aready. Switch to use the already established format for consistency. Though, I personally, think `$plugin` reads a tiny bit better than `{plugin}`.
=> Use {var} format for parameters in docs instead of $var

rel/overlay/etc/default.ini
The default settings for certain fabric timeout actions do not reflect the reality in the comments of `default.ini`.  Adjust those to match with the constants are laid down in the sources.
Note that apparently search requests are also associated with configurable timeouts, so document those as well.
=> fix(`default.ini`): sync suggested fabric timeout settings with the sources

src/docs/src/best-practices/jsdevel.rst
This is gnarly as this is something a user might put in a filter function, so they'd start getting unexpected results after the upgrade.
```
% js
js> "abc".match(undefined)
null
% js91
js> "abc".match(undefined)
[""]
```
=> Document another incompatibility between SM 1.8.5 and 78+

nouveau/src/main/java/org/apache/couchdb/nouveau/api/SearchRequest.java, nouveau/src/test/java/org/apache/couchdb/nouveau/api/SearchRequestTest.java, nouveau/src/test/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexTest.java, nouveau/src/test/resources/fixtures/SearchRequest.json, src/docs/src/api/ddoc/nouveau.rst, src/docs/src/ddocs/nouveau.rst, src/nouveau/src/nouveau_fabric_search.erl, src/nouveau/src/nouveau_httpd.erl, src/nouveau/src/nouveau_int.hrl, test/elixir/test/config/nouveau.elixir, test/elixir/test/nouveau_test.exs
Add `top_n` to control how many facets are returned by group (up to a limit of 1000 for now).
run the tests
https://github.com/apache/couchdb/issues/5284
=> nouveau: Add ?top_n=X query parameter for facets

nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/Lucene9IndexSchema.java, test/elixir/test/nouveau_test.exs
a stored field (`index('stored', 'foo', 'bar');`) was not returned in search results and gave a 500 error instead. 
=> fix stored fields in search results

Makefile, Makefile.win
By default, use the shipped Gradle wrapper script to build Nouveau.
As an option, we can now override the GRADLE variable to point to another gradle script, e.g. what the system provides.
=> chore(dev): Make Gradle script choosable

src/nouveau/priv/stats_descriptions.cfg, src/nouveau/src/nouveau_fabric_search.erl, src/nouveau/src/nouveau_httpd.erl, src/nouveau/src/nouveau_rpc.erl, test/elixir/test/config/nouveau.elixir, test/elixir/test/nouveau_test.exs
Return the amount of time in a nouveau query spent waiting for the index to be updated to current.
N/A
N/A
=> return time spent waiting to update index before query starts

build-aux/Jenkinsfile.pr
These ones are also built with `--enable-fips`
https://github.com/apache/couchdb-ci/pull/76
=> Update Erlang 26 and 27

src/couch_quickjs/rebar.config.script
Enable link-time-optimization for QuickJS on Windows and link pthreads static into couchjs_*.exe.
Reduced binary sizes of ~1.3 MB per couchjs_*.exe.
Before:
```
PS C:\Users\couchdb\Documents\couchdb-otp25> ls .\src\couch_quickjs\priv\
Directory: C:\Users\couchdb\Documents\couchdb-otp25\src\couch_quickjs\priv
Mode                 LastWriteTime         Length Name
----                 -------------         ------ ----
-a----        12.10.2024     14:29         204581 bundle_coffee.js
-a----        12.10.2024     14:29          42578 bundle_mainjs.js
-a----        12.10.2024     14:30        5392102 couchjs_coffee.exe
-a----        12.10.2024     14:30        5225702 couchjs_mainjs.exe
PS C:\Users\couchdb\Documents\couchdb-otp25> dumpbin.exe /dependents …
```
=> feat(quickjs): LTO and static linking pthreads on Win

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
It's the same idea as `SyntaxError` and `TypeError` above.
While at it improve the filter test to use individual ddocs for each error. This way one error or crash won't influence the others.
=> Handle another expected error in the scanner

src/docs/src/api/database/find.rst, src/mango/src/mango_cursor.erl, src/mango/src/mango_error.erl, src/mango/src/mango_opts.erl, src/mango/test/02-basic-find-test.py, src/mango/test/05-index-selection-test.py, src/mango/test/mango.py
*This is an alternative to #4710 based on the results of the related discussion.*
It is not always beneficial for the performance if the Mango query planner tries to assign an index to the selector.  User-specified indexes may save the day, but since they are only hints for the planner, fallbacks may still happen.
Introduce the `allow_fallback` flag which can be used to tell if falling back to other indexes is acceptable when an index is explicitly specified by the user or when only the "catch-all" `all_docs` index could be picked.  When set to `false`, give up on planning and return an HTTP 400 response right away.  This way the user has the chance to learn about the requested but missing index, optionally create it and try again.
By default, fallbacks are allowed to maintain backwards …
=> feat(`mango`): add `allow_fallback` to control falling back to other indexes on `_find`

src/dreyfus/src/clouseau_rpc.erl
This PR serves as a code documentation since we don't run type checks during CI. It doesn't modify existing code just adding type specs.
Since we don't run dyalizer during CI and given the fact that it fails on main. There is no good way to test correctness of the spec other than comparing the output of dilayzer on main and on the current branch.
on *main* branch
```
couchdb on *main* 
❯ make
...
couchdb on *main*
❯ make dialyze apps=dreyfus
==> dreyfus (build-plt)
WARN:  ''build-plt'' command does not apply to directory /Users/iilyak/Code/couchdb/rel
WARN:  ''build-plt'' command does not apply to directory /Users/iilyak/Code/couchdb
==> dreyfus (dialyze)
src/dreyfus_bookmark.erl:61:29: Record construction
#shard{name :: '_', ref :: '_', opts :: '_'} violates the declared type of field …
```
=> Add type specs to clouseau_rpc

src/chttpd/src/chttpd_misc.erl, src/chttpd/test/eunit/chttpd_misc_test.erl, src/docs/src/api/server/common.rst
Since we have nouveau and clouseau there, it makes sense to add quickjs as well. Otherwise, unless a user is a server a admin, there is no way for them to figure out if their views will be built with QuickJS or SpiderMonkey.
Also, it looks like our welcome message in the docs is quite old so take the opportunity to update it with the latest version.
=> Add quickjs to the list of welcome features

src/docs/src/best-practices/jsdevel.rst
In SpiderMonkey 1.8.5 allow this type of syntax:
```
foo : function(doc){emit(doc._id, 1);}
```
While later versions started throwing a compilation error.
=> Document junk before function() SM 1.8.5 vs 78+

src/chttpd/src/chttpd.erl, src/docs/src/api/basics.rst, test/elixir/test/basics_test.exs, test/elixir/test/config/suite.elixir
This allows tracing of requests that fail to start in a timely manner when using a load balancer in front.
covered by an integration test.
N/A
=> allow client to specify request id

src/chttpd/src/chttpd.erl, src/docs/src/api/basics.rst, test/elixir/test/basics_test.exs
X-Couch-Request-Id has always been hardcoded to 5 random bytes, expressed as hex. This is perfectly fine for pretty much everyone but is overly prescriptive. Allow up to 36 alphanumeric characters plus underscore and dash, so as to accommodate a UUID as well as other patterns.
covered by test
=> expand x-couch-request-id to allow uuids

src/couch/src/couch_proc_manager.erl, src/couch_quickjs/test/couch_quickjs_tests.erl
This should make it possible to toggle between engines without having to restart the node.
We already had a config listener so make sure it also sets up the `js_engine` bits, as well.
Add a test to demonstrate it works both when setting a non-default value and reverting back to the default value.
=> Allow online js_engine reconfiguration

src/couch/src/couch_server.erl, src/couch_quickjs/test/couch_quickjs_tests.erl
In the previous PR [1] Jessica had discovered that an invalid engine setting crashes the server. Initially I had thought we would be strict about it and just let it crash, but that seems a bit harsh for this. Especially if there is a large cluster and configuration is pushed to all nodes. It would crash the whole cluster.
Instead, since we have a default, stick with that. Especially now users can validate if a non-default js_engine is active from the welcome endpoint.
[1] https://github.com/apache/couchdb/pull/5327
=> Do not crash the server on invalid js_engine setting

src/mango/src/mango_httpd.erl, src/mango/test/01-index-crud-test.py
Mango indexes allow specifying a custom ddoc ID in the `_index` POST request. Previously it was possible to insert `_design/` which is an illegal doc ID.
=> Prevent inserting illegal ddocs via mango

src/couch_scanner/src/couch_scanner_plugin.erl
Previously, if users had invalid ddocs in the cluster, for instance something like `_design/`, the scanner would crash when transforming them into `#doc{}` records. That happened because the `couch_doc` function would automatically revalidate them: check max doc length ID, attachments format, revision format, doc ID format, etc. Which is altogether silly, since they are already saved in our cluster.
So, to avoid wasting resources revalidating existing documents, and crashing the scanner process, use a much simpler function to transform the ddocs: make a new `#doc{}` record with the ID and body by throwing away all the "special" doc fields we don't care about (`_rev`, `_conflicts`, ...).
=> Skip validation for ddocs in the scanner

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
When users call list functions from maps it ends up confusing the map protocol and we get more emitted results than we have views. That results in a function_clause error emitted in the logs from lists:zip/2. Having seen enough of these cases let's add check for it, and if the view engines map results match but we end up with total emits no matching the view count, restart the js processes and continue on.
While at it fix an erroneous copy-and-paste error in the comment of the random/date test.
=> Fix QuickJS scanner function_clause error

nouveau/build.gradle
include lucene backward-codecs so we can read older 9.x indexes.
=> nouveau: include lucene backward-codecs

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl, src/couch_scanner/src/couch_scanner_util.erl
Expand scanning for update handlers and text indexes.
* Even though Nouveau is experimental, users seem to be excited to try it out, so ensure we also check compatibility for it. Once we check Nouveau, checking Clouseau is not a big deal then, so let's do that as well.
* Deliberately use `RegExp.$1` incompatibility to exercise warning logs.
* We still have `lists` and `shows` left. `lists` are quite a bit trickier to test as they involved a streaming sub-protocol. So maybe leave them for later.
=> Add more features to QuickJS scanner

Makefile, Makefile.win, src/mango/test/01-index-crud-test.py, src/mango/test/12-use-correct-index-test.py, src/mango/test/13-stable-update-test.py, src/mango/test/14-json-pagination-test.py, src/mango/test/16-index-selectors-test.py, src/mango/test/17-multi-type-value-test.py, src/mango/test/18-json-sort.py, src/mango/test/19-find-conflicts.py, src/mango/test/20-no-timeout-test.py, src/mango/test/24-text-paginated-test.py, src/mango/test/25-beginswith-test.py, src/mango/test/mango.py
When running mango tests, sometimes get `org.apache.lucene.store.NoSuchDirectoryException` error. This is because each test in the same class used the same database name, and in the setUp function always delete and recreate it, which caused a race condition. Using custom database names should solve it.
- Makefile: Add `-F, --failfast` to stop mango tests early on failures
- Add `setUp()` and `teardown()` to create/delete db for each test to  
avoid `org.apache.lucene.store.NoSuchDirectory Exception` errors.
- Replace `self.db.recreate()` with `super().setUp(db_per_test=True)`
`make mango-test`
=> Fix mango tests using custom db name

src/couch_scanner/src/couch_scanner_plugin.erl, src/couch_scanner/test/eunit/couch_scanner_test.erl
Apparently `""` is a valid doc field and `binary:first(<<>>)` was crashing on it, so make sure to handle that case.
=> Allow empty doc fields in the scanner

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl
Improve the QuickJS update function scanning
* Noticed some design documents crashing because they are missing some of the expected `req` fields. When an early `TypeError("req.form is undefined")` error is thrown, it shortcuts the evaluation and we're missing covering that ddoc. To fix it, fill out [1] more of the mock request object so we get better coverage in the scanner.
* Handle error raised from the update function similar to how we handle other such errors in other function. From update functions they look like `render_error`.
[1] https://docs.couchdb.org/en/stable/json-structure.html#request-object
=>  Improve the QuickJS update function scanning

src/chttpd/test/eunit/chttpd_db_attachment_size_tests.erl, src/couch/src/couch_db_updater.erl, test/elixir/test/compact_test.exs
Previously, we included attachment sizes in the active size totals even if they attachments were deleted from the doc revision leafs.
The fix is, unsurprisingly, to do what the compactor does when it copies and updates sizes: only update sizes for leaf revision during the rev-tree traversal. We did this for doc bodies already in #4264, but forgot to consider attachments then.
In general we're aiming for the active size to approximate the size of the file after compaction. That is what drives smoosh (autocompaction) priority. If we don't remove non-leaf attachments from the calculation, the active/file ratio in smoosh may never trigger properly as ratio will stay low for shards with large attachments.
Until a release goes out with this fix, a workaround could be to compact shards with …
=> Fix attachment size calculation

build-aux/Jenkinsfile.full
Moved from the original PR https://github.com/apache/couchdb/pull/5356 since macos fail in the full CI currently
=> Bring FreeBSD AMD64 worker back

build-aux/Jenkinsfile.full
Disable SpiderMonkey on macOS CI builder until >91 support lands
=> Disable SpiderMonkey on macOS CI builder until >91 support lands

src/couch/rebar.config.script
The Homebrew package `icu4c` is keg-only and not linked into the standard path on macOS after installation.
Use the command `brew --prefix` for finding the location of the library.
=> feat(dev): Use `brew --prefix` to find ICU paths on macOS

src/couch/rebar.config.script
To get `couchjs` compiled on Windows with newer
SpiderMonkeys (102, 115 and 128), we need to tell
the MS compiler (cl.exe) to compile macros with
`__VA_ARGS__` correctly. To get this, we need to
add an extra compile flag `/Zc:preprocessor`.
Add `/utf-8` to correctly parse source files.
Fixes #5322.
=> fix(dev): Add compiler flags for MSVC

build-aux/Jenkinsfile.full
These run a bunch at a time in parallel, and a failure in any one means having to re-run all again which has a pretty high chance of hitting some other flaky failure.
=> Try adding retries to our full CI steps

dev/run
If authentication is required via config file, the node live check of `dev/run` will fail. Now we send the basic authentication headers for the live check.
=> chore(dev): Also use authentication for live node checks

build-aux/Jenkinsfile.full
Use the latest Debian version for building the release tarball.
=> chore(ci): Use Bookworm for "Build Release Tarball" stage

src/fabric/src/fabric_doc_update.erl
refactor fabric_doc_update to use a record for accumulator, to make https://github.com/apache/couchdb/pull/5371 enhancement easier.
=> introduce acc record

Makefile, Makefile.win
When running `make distclean` the docs source folder is fully wiped, if not run from a dist tarball. Since the docs are now included in the couchdb source, it's a leftover, where the docs were in a separate repository.
=> chore(dev): Don't wipe documentation source files on `distclean`

test/elixir/test/uuids_test.exs
Fix the following warnings
```
warning: negative steps are not supported in String.slice/2, pass 14..-1//1 instead
(elixir 1.17.3) lib/string.ex:2404: String.slice/2
test/elixir/test/uuids_test.exs:91: anonymous fn/2 in UUIDsTest."test utc_id uuids are correct"/1
(elixir 1.17.3) lib/enum.ex:2531: Enum."-reduce/2-lists^foldl/2-1-"/3
test/elixir/test/uuids_test.exs:89: UUIDsTest."test utc_id uuids are correct"/1
(ex_unit 1.17.3) lib/ex_unit/runner.ex:485: ExUnit.Runner.exec_test/2
(stdlib 4.3.1.5) timer.erl:235: :timer.tc/1
(ex_unit 1.17.3) lib/ex_unit/runner.ex:407: anonymous fn/6 in ExUnit.Runner.spawn_test_monitor/4
```
Related PR: https://github.com/apache/couchdb/pull/5372
Related issue: https://github.com/apache/couchdb/issues/5386
`make elixir`
=> Elixir: Fix negative steps

src/couch/src/couch_file.erl
We can use fdatasync to save 1 extra write per call, for a total of 2 writes per commit, since we do two sync, one for data block up to the header, then another after the header.
As of OTP 25 (our oldest supported version):
* On Linux/BSDs: fdatasync()
* On Window: FlushFileBuffers() i.e. the same as for file:sync/1
* On MacOS: fcntl(fd,F_FULLFSYNC/F_BARRIERFSYNC)
According to https://linux.die.net/man/2/fdatasync
> fdatasync() is similar to fsync(), but does not flush modified metadata
unless that metadata is needed in order to allow a subsequent data retrieval
to be correctly handled. For example, changes to st_atime or
st_mtime (respectively, time of last access and time of last modification; see
stat(2)) do not require flushing because they are not necessary for a
subsequent data read …
=> Use fdatasync for commits

src/couch/src/couch_bt_engine.erl, src/couch/src/couch_db_engine.erl, src/couch/src/couch_db_updater.erl, src/couch/src/couch_file.erl, src/couch/test/eunit/couch_file_tests.erl
7 years ago we added an idle-check timeout to force idle system shard to close [1]. It seemed like a relevant setting for Cloudant, where at the time we had a large number of open `_replicator` dbs per server. However, at Cloudant we only
enabled it once, it failed as it closed too many shards too quickly, and then they had to be re-opened, which added extra load, we disabled ran with `infinity` ever since.
We also never documented it anywhere so let's remove it.
[1] https://github.com/apache/couchdb-couch/pull/236
=> Remove idle check timeout

CONTRIBUTING.md, src/docs/src/api/database/changes.rst
Extremely minor changes:
- Fix the wrong tense on the last note of api/database/changes
- Fix the wrong use of two verbs in that last paragraph of the last note of api/database/changes
- Fix a broken link in CONTRIBUTING.rst
Test documentation generation in various formats
Fixes #5403
As these are extremely minor fixes to documentation, I don't think they affect the listed checklist?
=> Fix contributing and api/database/changes minor typos documentation

build-aux/Jenkinsfile.full
It was graciously replaced by the IBM POWER team. Thanks!
=> POWER CI worker is back

src/chttpd/src/chttpd_node.erl
When running with old version of Clouseau, it will return `{ok, null}`
when we call `clouseau_rpc:version().`. So add `is_binary/1` to prevent
`badarg` errors. Also simplify the code by extracting the response to
`get_versions/0` function.
=> Extract the response of `_versions` endpoint

share/server/dispatch-quickjs.js, share/server/util.js
Prior to landing SpiderMonkey 102+ we relied on a global `seal()` function that we defined in our custom `couchjs` C/C++ code.
SM 102+ no longer exposes the API needed to implement this, but the JS standard also includes a userspace `Object.freeze()` method we can use.
Our initial implementation of SM 102+ support introduced[1] a global `deepFreeze()` function that relied on `Reflect .ownKeys()` which is not available in SpiderMonkey 1.8.5, but all later ones we support.
To fix the build for SM 1.8.5, we partly reverted[2] the use of `deepFreeze()`, but we missed a few spots in `main.js` where we seal our own new globals like `Couch`[3].
This commit reinstates the use of `deepFreeze()` everywhere and adds a safe fallback inside `deepFreeze()` to do the right thing for SM 1.8.5 and > …
=> fix(js): re-instate `deepFreeze()` for all object freezing duties

src/couch/src/couch_work_queue.erl, src/couch/test/eunit/couch_work_queue_tests.erl
Nothing was using it so let's remove it. "Deleted code is debugged code" as they say.
It turns out its unit tests never covered the actual use case of the work queue -- sending terms back and form, it just tested binaries. So add a few tests for terms and check some other error cases, thus increasing test coverage to 100%.
=> Remove multi_workers option from couch_work_queue

src/couch_mrview/src/couch_mrview_updater.erl
Previously, we reversed Acc in `process_doc/3` but not in `finish_update/1`. So were processing elements out of order. For example: 1,2,...,22,32,31,...,23.
The view still build correctly but let's make it tidier and more consistent.
=> Ensure we always map the documents in order map mrview updater

src/dreyfus/src/clouseau_rpc.erl
A ping is not enough. A clouseau instance is not usable if we it's just connected, it's main process should be up and running as well.
We have observed that it is possible for the clouseau node to be connected and respond to pings, but the main process was down. We want to alert or catch cases when that happens so we ask the main process for the version.
=> Add a version check to clouseau connected() function

src/couch/src/couch_proc_manager.erl, src/couch_quickjs/test/couch_quickjs_tests.erl
Previously, we set the default JS engine dynamically, so that newly spawned processes would use the new setting. However, we didn't actively try to kill the old JS processes. Since a quiet cluster, without much concurrent indexing activity, could hang on to the same set of spawned processes for a while, it may take an indeterminate amount of time until the couchjs processes actually switch to the new engine.
To fix that let's force a `reload()` as well, which will immediately kill all the free (available) processes and then kill the acquired processes when the user is done with them and releases them back to the process manager.
=> Kill all couchjs processes right after updating the engine setting

src/couch_quickjs/src/couch_quickjs_scanner_plugin.erl, src/couch_quickjs/test/couch_quickjs_scanner_plugin_tests.erl, src/couch_scanner/src/couch_scanner_util.erl
* In the scanner, emit just the db name in the `db:...` field and skip the range. After processing scan results for months I never once needed or used the range, it just adds extra noise, so let's remove it.
* In the QuickJS doc update scanner, the mock request body should be string not an object [1].
* Expect search indexes to be broken so there may not be any valid fields  returned. In that case don't crash the scanner with a `{badmatch, []}`
[1] https://docs.couchdb.org/en/stable/json-structure.html#request-object
=> Scanner improvements

src/docs/src/best-practices/jsdevel.rst
`String.substring("abcd", 1, 2)` stopped working at some point between 1.8.5 and 91. My 52 and 78 installs broke, so can only test those two.
Also noticed some of the discrepancies had been indented while others were not, so made them all non-indented as that looked better and saved some horizontal space.
=> Document another spidermonkey vs spidermonkey discrepancy

src/couch/include/couch_js_functions.hrl, src/couch/src/couch_httpd_auth.erl, src/docs/src/intro/security.rst
Introduces a new password scheme intended to help administrators transitioning from the legacy "simple" scheme to the strong "pbkdf2" scheme. By wrapping existing simple credentials with pbkdf2 we protect them better until such times as they are used (at which point they will be upgraded to the currently configured scheme).
N/A
N/A
=> Add simple+pbkdf2 migration password scheme

CONTRIBUTING.md
This PR fixes a typo in the examples in CONTRIBUTING.md
None
None
- ~~[ ] Code is written and works correctly~~
- ~~[ ] Changes are covered by tests~~
- ~~[ ] Any new configurable parameters are documented in `rel/overlay/etc/default.ini`~~
- ~~[ ] Documentation changes were made in the `src/docs` folder~~
- ~~[ ] Documentation changes were backported (separated PR) to affected branches~~
=> Fix wrong link in example within CONTRIBUTING.md

rel/overlay/etc/default.ini, src/chttpd/src/chttpd.erl, src/chttpd/src/chttpd_sup.erl, src/chttpd/test/eunit/chttpd_util_test.erl, src/docs/src/api/server/configuration.rst, src/docs/src/maintenance/performance.rst
Discussing with Jan in CouchDB slack, he reported benchmarking a recent release of Apache CouchDB and noticing a large difference in performance using these chttpd mochiweb server options:
```
[chttpd]
server_options = [{backlog, 128}, {acceptor_pool_size, 32}, {max, 65536}]
```
Let's make those the new defaults, and also remove the unused separate `backlog` setting. We diligently documented and carried it along for many years a while it turns out it doesn't do anything.
Only the `backlog` from `server_options` changes the backlog, and that default is 128, so we've been running with 128 all these years anyway.
=> Improve default chttpd server options

share/server/util.js, share/server/views.js, src/couch/test/eunit/couch_js_tests.erl
~~In Javascript 1.8.5 we were able to just emit an error and it would serialized to json with a name, message and stacktrace. That can help during debugging.~~
~~With later Spidermonkey versions and now QuickJS, the error is serialized to "{}". That is expected based on [1] as Error fields are not enumerable ("Only enumerable own properties are visited"). But we could still do it perhaps if we detect that we have an Error in our emit wrapper and serialize it there to a string. But somehow `intanceof` doesn't work in the wrapper.~~
The mystery is solved (thanks, @janl!) I updated the PR and the new commit message is:
In views we drop any rows which throw errors. Sometimes users may want to either record which docs throw errors and build an error "key space" by doing `emit(['error', …
=> Restore the ability to return error object from maps

LICENSE, rel/overlay/etc/default.ini, src/couch/.gitignore, src/couch/priv/couch_cfile/couch_cfile.c, src/couch/rebar.config.script, src/couch/src/couch_cfile.erl, src/couch/src/couch_file.erl, src/couch/test/eunit/couch_cfile_prop_tests.erl, src/couch/test/eunit/couch_cfile_tests.erl, src/couch/test/eunit/couch_file_tests.erl, src/ioq/src/ioq.erl
Implement parallel preads
Let clients issue concurrent pread calls without blocking each other or having to wait for all the writes and fsync calls.
Even though at the POSIX level pread calls are thread-safe [1], Erlang OTP file backend forces a single controlling process for raw file handles. So, all our reads were always funneled through the couch_file gen_server, having to queue up behind potentially slower writes. In particular this is problematic with remote file systems, where fsyncs and writes may take a lot longer while preads can hit the cache and return quicker.
Parallel pread calls are implemented via a NIF which copies some of the file functions OTP's prim_file NIF [2]. The original OTP handle is dup-ed, and then closed, then our NIF takes control of the new duplicated file …
=> Implement parallel preads

src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_db_doc_get_tests.erl, test/elixir/test/attachments_multipart_test.exs
Previously, atts_since didn't work for doc GETs with `open_revs=[...]` parameters so we always re-replicated all the attachments bodies on every update, even if the user just updated the doc without touching the attachment.
Our `_revs_diff` endpoint returns the `possible_ancestors` list (which is what `atts_since` is), the replicator app passes it along to the source, and even our node-level couch_db API handles `atts_since`, but we somehow never passed that parameter to the fabric call in the `chttpd_db`. It's like we ran the whole marathon, then stumbled and fell right before the finish line.
=> Fix atts_since functionality for doc gets

src/chttpd/test/eunit/chttpd_purge_tests.erl, src/couch/src/couch_bt_engine.erl, src/couch/src/couch_db.erl, src/couch/src/couch_db_split.erl, src/couch_index/src/couch_index_updater.erl, src/fabric/src/fabric_rpc.erl
Previously, when the number of purges exceeded the `purged_infos_limit`, and the database was compacted, `purged_infos` would crash because it would always fold purges starting at 0 instead of the minimal start sequence. In all the other places like mem3, shard splitter, etc we looked up the minimal sequence and started from there, but we didnt' for purge_infos.
To fix it, add a helper couch_db API to always do the start sequence lookup at the minimal sequence. Also, explain in the couch_bt_engine in a comment why we validate the minimal sequence and ensure if/when we throw assert we show the minimal value in addition to the start sequence.
To ensure we don't miss this again add a test to set a low purged infos limit, compact and fetch purged infos.
Fix: #5438
=> Fix purge_infos when exceeding purged_infos_limit

src/couch/priv/couch_cfile/couch_cfile.c, src/couch/src/couch_cfile.erl
Load it opportunistically, and if it's not available on some platforms keep returning {error, einval}, couch_file already expects that.
=> Fix couch_cfile on Windows

src/docs/src/best-practices/jsdevel.rst
Document Spidermonkey 1.8.5 leaking nested `const` references into outer scopes as `undefined` values. All other engines, including later Spidermonkey 91, throw a ReferenceError in that case.
This could affect views which may declare a value inside an if expression and emit that value outside of it.
=> Document consts leaking from nested scopes SM 1.8.5 vs 91/QuickJS/V8

src/couch/test/eunit/couch_cfile_tests.erl
In the test must wait for the file to close, since closing is asynchronous with respect to the process exit.
=> Fix flaky cfile closing test

src/docs/src/best-practices/jsdevel.rst
This discrepancy can be especially problematic when parsing dates, where `parseInt(Month)` may seem to work correctly, however it will fail for August `"08"` and September `"09"`, where both would parse as ``0``.
h/t to Will Holley for the reminder to document this discrepancy
=> Document the parseInt Spidermonkey 1.8.5 discrepancy

src/docs/src/best-practices/jsdevel.rst
Spidermonkey 1.8.5 allowed calling regular expression objects directly. The call worked the same as calling `exec()` [1].
[1] https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Releases/5#javascript
=> Document callable regex in Spidermonkey 1.8.5

src/config/src/config.erl, src/config/test/config_tests.erl, src/couch/src/couch_file.erl, src/couch/test/eunit/couch_file_tests.erl, src/couch_replicator/src/couch_replicator_parse.erl, src/smoosh/src/smoosh_utils.erl
When toggling the xxHash checksum setting we noticed that it was kind of annoying that we had to restart the nodes for it to take effect. The setting was optimised to be cached in a persistent term [1], so instead of making some extra process monitor or extra config listener, let's instead optimise all the config settings to use persistent terms. We may get a tiny bit of a performance boost from lookup, and maybe less memory pressure as persistent terms are referenced instead of copied unlike those read from an ets table (which are copied, unless they are refc binaries).
The change was smaller than expected, it's just swapping out internal ets operations for the persistent term ones. The external API stays the same.
The changes in the smoosh and replicator tests are because they were …
=> Optimise config to use persistent terms

build-aux/Jenkinsfile.full, build-aux/Jenkinsfile.pr
This PR adds the pipeline for building CouchDB on a Windows Jenkins agent node.
=> Add Windows Jenkins pipeline

src/couch/test/eunit/couch_js_tests.erl, src/couch_quickjs/c_src/couchjs.c
Literals have the `n` suffix: `0n`, `-20n`. They can be parsed from a string:(ex: `x = BigInt("12..34")`) and serialized back to a string with `toString()` (ex: `emit(x.toString())`).
Currently this is a minimal, standards compliant implementation which doesn't do automatic JSON parsing directly to BigInts or automatically serializing to JSON. It should be possible to introduce that in the future, but it's better to start from something simpler first.
=> BigInt support for QuickJS

src/config/src/config.erl
The callback was not called as we didn't trap exits. This is not a big deal at runtime, as the process would go down anyway after config app terminates, and even if it restarts, we'd clean up all the config values anyway in init. However, when running tests this could leave config value set from the previous config app run.
=> Make sure terminate/2 is called in config

src/couch/src/couch_file.erl
Pids could be remote when processing attachments and `is_process_alive/1` will throw an error then, so ensure a fallback for non-local processes.
=> Use local pids for cfile

src/couch/src/couch_file.erl, src/couch/test/eunit/couch_file_tests.erl
In a mixed cluster, with nodes before and after #5373 where `pread_iolist` and `append_bin` were removed, attachment operations may throw function_clause errors on the new couch_file gen_servers. That's because attachment streams may be opened on one node, but operations on them maybe called from another node. As such, we have to handle the old gen_server messages until the next version.
=> Fix compatibility clause for attachments

src/nouveau/src/nouveau_bookmark.erl
jiffy may return an iolist but base64:encode() cannot take iolists as input. since we also want urlsafe encoding we switch base64:encode to b64url:encode/1 as it will accept iolists. this matches dreyfus behaviour too.
closes #5453
Run test suite
https://github.com/apache/couchdb/issues/5453
=> nouveau: base64 only takes binaries

src/nouveau/priv/stats_descriptions.cfg, src/nouveau/src/nouveau_api.erl
add a metric for connection_closed errors
N/A
https://github.com/apache/couchdb/pull/5469
=> nouveau: add a metric for connection_closed errors

build-aux/Jenkinsfile.full
Exclude Nouveau tests on Windows, because of flaky and failing tests on Windows CI runs.
=> dev(CI): Temporary exclude Nouveau tests on Windows

src/fabric/src/fabric.erl, src/fabric/src/fabric_db_create.erl, src/fabric/src/fabric_doc_open.erl, src/fabric/src/fabric_doc_open_revs.erl, src/fabric/src/fabric_ring.erl, src/fabric/src/fabric_streams.erl, src/fabric/src/fabric_view_changes.erl, src/fabric/test/eunit/fabric_db_create_tests.erl, src/fabric/test/eunit/fabric_db_info_tests.erl, src/fabric/test/eunit/fabric_db_uuids_tests.erl, src/fabric/test/eunit/fabric_tests.erl
- After upgrading `meck`, CI got errors about `context setup failed`.
Cleaning up `meck` functions in `fabric` to fix this issue.
```
[2025-03-12T20:04:15.632Z] module 'fabric_view_map'
[2025-03-12T20:04:16.552Z]   fabric_view_map_meck_original:330: -handle_message_test_/0-fun-20- (t_handle_message_rexi_down)...[0.005 s] ok
[2025-03-12T20:04:17.472Z]   undefined
[2025-03-12T20:04:17.472Z]   *** context setup failed ***
[2025-03-12T20:04:17.472Z] **in function persistent_term:get/1
[2025-03-12T20:04:17.472Z]   called as get({cover,fabric_view_map_meck_original})
[2025-03-12T20:04:17.472Z] in call from fabric_view_map_meck_original:'-handle_message_test_/0-fun-23-'/0
[2025-03-12T20:04:17.472Z] **error:badarg
```
- Simplify tests with `?TDEF` and `?TDEF_FE`
`make eunit apps=fabric`
=> chore: Clean up `meck` functions in `fabric`

.asf.yaml
It turns out we need to set up a notification ML target
Otherwise it doesn't work. See [1] for more details
[1] https://github.com/apache/infrastructure-asfyaml?tab=readme-ov-file#repo_features
=> Try to enable discussions again

src/docs/src/install/unix.rst
- adding new supported SpiderMonkeys
- adding Ubuntu 24.04 (noble) as convenience binary target
=> Update *nix install instructions

src/docs/src/install/unix.rst, src/docs/src/whatsnew/3.4.rst, version.mk
Squash all 3.4.2 to 3.4.3 commits on 3.4.x to bring them into main.
Start commit is:
```
commit 6e5ad2a5c5479cb09722b4a7d13b3d59b7bb2a23
Author: Nick Vatamaniuc <vatamane@gmail.com>
Date:   Mon Oct 14 14:21:20 2024
Bump version to 3.4.2
```
Squash with command below and apply fixups
```
git rebase -i 6e5ad2a5c5479cb09722b4a7d13b3d59b7bb2a23
```
=> All 3.4.2 to 3.4.3 commits on 3.4.x

src/couch/src/couch_proc_manager.erl, src/ken/src/ken_server.erl
We discovered that `ken` was not indexing `erlang` design documents in the background, because it was relying on the old environment variables to determine that the native query server is enabled. This patch adds `erlang` to its list of allowed languages, if the native query server is enabled.
I checked this by creating a database with these two design docs in it:
```json
{
"views": {
"by-n": {
"map": "function (doc) { emit(doc.n) }"
}
}
}
{
"language": "erlang",
"views": {
"by-n": {
"map": "fun({Doc}) -> N = proplists:get_value(<<\"n\">>, Doc, null), Emit(N, null) end."
}
}
}
```
Before this fix, the `_info` endpoint for each doc shows that `updates_pending` remains high for the Erlang view, when the JS one goes to zero. The index files on disk for the Erlang view do not get updated when …
=> Add "erlang" to the set of allowed languages in ken

build-aux/Jenkinsfile.full
The macOS worker has Java 8 installed but it could not be leveraged because it was not configured through the `CLOUSEAU_JAVA_HOME` environment variable.  Address this gap and un-break running Clouseau on that platform as well.
=> chore(`ci`): enable Clouseau for macOS

rel/overlay/etc/default.ini, src/docs/src/install/nouveau.rst, src/nouveau/src/nouveau_api.erl
Allow an administrator to configure ssl options, in particular to add a client certificate, so that communication between couchdb and nouveau can be secured and authenticated when nouveau is deployed remotely.
Nouveau itself can be configured to listen with TLS and can be configured to require a valid client certificate on all requests.
https://www.dropwizard.io/en/stable/manual/configuration.html#https
=> Allow admin to configure ssl options for nouveau requests

build-aux/Jenkinsfile.full
Java 8 has now been installed to both FreeBSD workers, so enable the Clouseau integration for them.  Kudos to @dch for making this happen!
=> chore(`ci`): enable Clouseau for FreeBSD

src/couch/src/couch_query_servers.erl, src/couch_mrview/src/couch_mrview.erl, src/docs/src/ddocs/ddocs.rst, test/elixir/test/config/suite.elixir, test/elixir/test/reduce_builtin_test.exs
These should work with the already existing grouping functionality to keep track of last update times, or top sales numbers or anything of that sort.
For example, with a map function with a compound key like: 
```
function(doc){
emit([doc.year, doc.month], doc.sales);
}
```
We can make requests like these:
```
http $DB/db/_design/d1/_view/top_1'?group=true&group_level=2&start_key=[2021]&limit=3'
{
"rows": [
{"key": [2021, 1], "value": [145.47625983483155]},
{"key": [2021, 2], "value": [250.70341326647355]},
{"key": [2021, 3], "value": [4484.3909590737285]}
]
}
```
=> Implement top_N/bottom_N built-in reducers

src/couch/src/couch_query_servers.erl, src/couch_mrview/src/couch_mrview.erl, src/docs/src/ddocs/ddocs.rst, test/elixir/test/reduce_builtin_test.exs
`_first` and `_last` reducers return the first, and respectively, the last value in a view group. They can be useful with complex keys, for example, when there are some timestamped entries that may have keys like `[device, timestamp]`, and we would like to get only the latest value by timestamp by grouping by device with `group_level=1`:
```
[dev1, 2025-03-28T00:01:02] : 100.0
[dev1, 2025-03-28T00:03:04] : 91.5
[dev2, 2025-03-29T00:10:15] : 87.6
[dev2, 2025-03-29T00:13:09] : 97.8
```
We could use the `_last` reducer with it to return:
```
[dev1] : 91.5
[dev2] : 97.8
```
=> _first/_last reducers

src/docs/src/ddocs/ddocs.rst
I had messed up the docs update in the previous PR
Before:
After:
=> Fix missing documentation section title for _top_N reducer

rel/overlay/etc/default.ini, src/couch_scanner/README.md, src/couch_scanner/src/couch_scanner_plugin.erl, src/couch_scanner/src/couch_scanner_plugin_conflict_finder.erl, src/couch_scanner/test/eunit/couch_scanner_test.erl
Add `couch_scanner_plugin_conflict_finder` to find conflicting docs
in the database.
- If `doc_report` is set to true, the report will show doc name and
revision information.
e.g.: `couch_scanner_plugin_conflict_finder s:1742238038-9e432378f2f1 db:db doc:d1 conflicts:["2-y","2-x"] deleted_conflicts:["2-d"]`
- Otherwise, only conflicted revision numbers are accumulated.
e.g.: `couch_scanner_plugin_conflict_finder s:1742238038-9e432378f2f1 db:db conflicts:2 deleted_conflicts:1`
- If `max_revs = 1`, and the document has more than 1 revision, the
doc report will only show the length of the revs info, without the
details. By default, `max_revs = 10`.
e.g.: `couch_scanner_plugin_conflict_finder s:1742238038-9e432378f2f1 db:db doc:d1 conflicts:2 deleted_conflicts:["2-d"]`
Create a conflict …
=> Couch scanner plugin: conflict finder

src/couch_quickjs/patches/01-spidermonkey-185-mode.patch, src/couch_quickjs/quickjs/Changelog, src/couch_quickjs/quickjs/Makefile, src/couch_quickjs/quickjs/quickjs-atom.h, src/couch_quickjs/quickjs/quickjs-libc.c, src/couch_quickjs/quickjs/quickjs.c, src/couch_quickjs/quickjs/quickjs.h, src/couch_quickjs/quickjs/test262.conf
* break statement with labels fixes [1]
* fix buffer overflow in bjson string + bigint reader [2]
* bigint fixes [3] [4]
* weak map gc fix [5]
* segfault on large number of properties [6]
* undefined is a valid variable name in global scope [7]
[1] https://github.com/bellard/quickjs/issues/275
[2] https://github.com/bellard/quickjs/issues/399
[3] https://github.com/bellard/quickjs/commit/083b7bab01
[4] https://github.com/bellard/quickjs/commit/fa706d5622
[5] https://github.com/bellard/quickjs/pull/393
[6] https://github.com/bellard/quickjs/issues/111
[7] https://github.com/bellard/quickjs/issues/370
=> Bring in latest QuickJS fixes

rebar.config.script
Fauxton: https://github.com/apache/couchdb-fauxton/releases/tag/v1.3.3
Proper: https://github.com/proper-testing/proper/pull/322
=> Update Fauxton to latest v1.3.3

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_misc.erl, src/chttpd/test/eunit/chttpd_csp_tests.erl, src/docs/src/config/misc.rst
Fauxton’s News page fails with CSP error in the browser console
Set the config yourself and see Fauxton News working again.
=> fix: Add blog.couchdb.org to frame-src CSP header to fix Fauxton News

src/couch_quickjs/patches/01-spidermonkey-185-mode.patch, src/couch_quickjs/quickjs/quickjs.c, src/couch_quickjs/quickjs/quickjs.h, src/couch_quickjs/quickjs/test262_errors.txt
* Fix exporting destructured variables [1]
* Fix class field name get or set [2]
* TypeError compat fix [3]
* Fixed JS_IsString() with ropes [4]
* Fixed the handling of unicode identifiers [5]
[1] https://github.com/bellard/quickjs/commit/7adeb5c56e18858ab92337c59b393f0704538e22
[2] https://github.com/bellard/quickjs/commit/949c105aff1ff0c3edc0a1cb7c713c68509fc156
[3] https://github.com/bellard/quickjs/commit/d546fbfdb7d0f236c30a6c2a1a5641341e9d6aa7
[4] https://github.com/bellard/quickjs/commit/c505ac0f39d1b185a35c518b37db928b7b9bc2a9
[5] https://github.com/bellard/quickjs/commit/25ffdb418ea221eaab7605f24aa3087323cd501d
=> QuickJS updates

src/mango/src/mango_util.erl
Persistent terms are built-in nowadays, and `mochiglobal:put/2` with a regex compiled object is incompatible with OTP28, so we're killing two birds with one stone here.
=> Use persistent terms to cache Mango RE expressions

src/mango/src/mango_cursor.erl, src/mango/src/mango_idx.erl, src/mango/src/mango_idx_nouveau.erl, src/mango/src/mango_idx_text.erl, src/mango/src/mango_idx_view.erl
We already use new ones everywhere else and when switching to OTP 28 we got a bunch of failure do to various order changes, so make sure to use new ones everywhere.
Moreover, do not rely on implementation order of `sets:to_list()`, but sort the result to produce deterministic results regardless of the internal representation.
=> Use new sets only in mango

src/couch_quickjs/patches/01-spidermonkey-185-mode.patch, src/couch_quickjs/quickjs/Makefile, src/couch_quickjs/quickjs/quickjs.c, src/couch_quickjs/quickjs/run-test262.c, src/couch_quickjs/quickjs/test262.conf, src/couch_quickjs/quickjs/test262_errors.txt, src/couch_quickjs/quickjs/tests/test262.patch
* New CI types and test fixes (we don't run these) [1]
* Future reserved keywords are forbidden in function name and arguments when the function body is in strict mode [2]
* Setters cannot have rest arguments [3]
* Fix property ordering in the object returned by RegExp.prototype.exec() [4]
* Fixed operation order in Object.prototype.propertyIsEnumerable() [5]
* Fixed `RegExp.prototype[Symbol.split]` [6]
* Fixed GeneratorFunction prototype [7]
* Typed array fixes [8] [9]
[1]
https://github.com/bellard/quickjs/commit/c0958ee2d03a2faf23237de123883e6002276dde
[2]
https://github.com/bellard/quickjs/commit/99a855f2c76d0b94ede87ef0c1ff416903203313
[3]
https://github.com/bellard/quickjs/commit/5e71d148f229f9a5ee6824902366844178026966
[4] …
=> QuickJS updates: RegExp and TypeArray fixes

src/couch_quickjs/rebar.config.script
This is a result of me updating the QuickJS makefile upstream
- Skip LTO
- Make sure to use the .exe suffix
- Add dtoa source file to the list of source files
=> Fix QuickJS Windows build

src/couch/src/couch_multidb_changes.erl, src/couch/src/couch_util.erl, src/couch_prometheus/test/eunit/couch_prometheus_e2e_tests.erl, src/couch_replicator/src/couch_replicator_httpd_util.erl, src/fabric/src/fabric_db_purged_infos.erl, src/fabric/src/fabric_group_info.erl, src/fabric/src/fabric_streams.erl, src/global_changes/src/global_changes_listener.erl, src/global_changes/src/global_changes_server.erl, src/mango/src/mango_cursor.erl, src/mango/src/mango_cursor_nouveau.erl, src/mango/src/mango_cursor_text.erl, src/mango/src/mango_idx.erl, src/mango/src/mango_idx_nouveau.erl, src/mango/src/mango_idx_text.erl, src/mango/src/mango_idx_view.erl, src/mem3/src/mem3_sync_event_listener.erl, src/mem3/test/eunit/mem3_ring_prop_tests.erl
With OTP 28 sets switched to using version 2 by default. That caused various tests to fail, as Jan discovered in #5507
In the previous PR #5510 we switched few mango instances to use a helper utility, but it was repeated a few times and Gábor made a good suggestion to use utility functions instead, so that's what this PR does. But it does it for the whole code base.
Once we're post OTP 28 we can remove the utility and just use plain set functions.
=> Use new sets everywhere

src/docs/ext/linter.py, src/docs/src/api/basics.rst, src/docs/src/api/database/bulk-api.rst, src/docs/src/api/database/changes.rst, src/docs/src/api/database/cleanup.rst, src/docs/src/api/database/common.rst, src/docs/src/api/database/compact.rst, src/docs/src/api/database/find.rst, src/docs/src/api/database/misc.rst, src/docs/src/api/database/security.rst, src/docs/src/api/database/shard.rst, src/docs/src/api/ddoc/common.rst, src/docs/src/api/ddoc/nouveau.rst, src/docs/src/api/ddoc/render.rst, src/docs/src/api/ddoc/search.rst, src/docs/src/api/ddoc/views.rst, src/docs/src/api/document/attachments.rst, src/docs/src/api/document/common.rst, src/docs/src/api/local.rst, src/docs/src/api/partitioned-dbs.rst, src/docs/src/api/server/authn.rst, src/docs/src/api/server/common.rst, src/docs/src/api/server/configuration.rst
Adding missing HTTP status codes 401 and 403 to API endpoints.
=> chore(docs): Add 401 and 403 status code to API docs

rel/overlay/etc/default.ini, src/couch/src/couch_file.erl, src/docs/src/config/couchdb.rst
=> Enable xxhash checksums by default

nouveau/src/main/java/org/apache/couchdb/nouveau/core/Index.java, nouveau/src/main/java/org/apache/couchdb/nouveau/core/IndexManager.java, nouveau/src/main/java/org/apache/couchdb/nouveau/lucene9/Lucene9Index.java, nouveau/src/test/java/org/apache/couchdb/nouveau/core/IndexManagerTest.java
Detect if an index is closed (by Lucene itself) on fetch and re-open it if so.
Unfortunately inducing Lucene to close an index itself is quite tricky. #5521 has observed it in the wild, though. 
Note: This is not a fix for the `CorruptIndexException` aspect, that remains unexplained. It just allows nouveau to recover _if_ the index can be reopened.
=> 5521 handle closed index

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_db.erl, src/chttpd/test/eunit/chttpd_view_test.erl, src/couch_mrview/include/couch_mrview.hrl, src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_http.erl, src/couch_mrview/src/couch_mrview_show.erl, src/couch_mrview/src/couch_mrview_test_util.erl, src/couch_mrview/src/couch_mrview_util.erl, src/couch_mrview/test/eunit/couch_mrview_all_docs_tests.erl, src/couch_mrview/test/eunit/couch_mrview_show_list_tests.erl, src/fabric/src/fabric.erl, src/fabric/src/fabric_util.erl, src/fabric/test/eunit/fabric_tests.erl
Previously, we set a default limit that was an effective infinity (2^28). It seems back in the 32 bit days that was the Erlang's largest small integer [1]. However, that turned out to be too low and it surprised a user when it truncated their all_docs output skipping some of the data. Fix that by increasing the limit to a larger "infinity" (highest 64 bit Erlang small integer [1]).
We did have a "query_limit" config parameter to customize the limit, however that turned out to be broken and did not take effect when the user tried it for all_docs, so fix that as well. Test to ensure the limit gets reduced appropriately. To make the setting more user friendly, allow `infinity` as the value.
Also, in the case of all_docs, we validated args and applied the limit check twice: once in the …
=> Fix query limit

rel/overlay/etc/default.ini, src/couch/src/couch_password_hasher.erl, src/docs/src/config/auth.rst
Initially this was set to ``true`` for ``3.4.0`` however, realizing users wouldn't be able to downgrade we defaulted it to ``false`` and quickly released ``3.4.1`` to replace ``3.4.0``. Since users now can safely downgrade to 3.4.x we can default it to ``true`` in 3.5.x releases.
See #5255 for more background
=> Default upgrade_hash_on_auth to true

src/docs/src/whatsnew/3.5.rst
* Add a few more related prs to parallel preads highlights
* Add _top_N/_bottom_N/_first/_last reducers to highlights
* Add conflict finder to highlights
* Mention defaults flipping and what versions it's safe to downgrade to.
* Fix a few PR number typos
=> Update and fix whatsnew for 3.5

Makefile, Makefile.win, README-DEV.rst, dev/run
The `--erlang-cookie` configuration flag for the `dev/run` script does not propagate the cookie value for `vm.args` so that the nodes will not have it configured on starting up.  That is why, for example, pinging the Clouseau nodes with user-provided cookie will not work, as well as Clouseau nodes will not be able to connect even though they picked up the right value already.
Add the missing parts to tweak `vm.args` accordingly and make the Erlang cookie configurable through the `Makefile` too.
There are different ways to see if the change is working.  For example, one could launch `dev/run` directly to start the nodes with a specific Erlang cookie:
```console
% dev/run -a adm:pass -n 1 --erlang-cookie=crumbles
...
```
Then one should be able to see the cookie configured in …
=> fix(`dev/run`): complete Erlang cookie configuration

src/couch/priv/couch_cfile/couch_cfile.c
In principle we could support it with a few more extra macros to figure out if we should use `enif_get_int64()` vs `enif_get_int()` for `size_t` values, but since we don't have a way to test it (no CI machine for armhf), we'll just opt to not support it for now. This doesn't mean we'd crash the build: we still support 32bit systems just with a default file module, like we do on Windows.
=> No cfile support for 32bit systems

src/mem3/src/mem3_util.erl
Previously we started the `{min, max}` accumulator as `{0, ?RANGE_END}` while it should have been `{?RANGE_END, 0}` so during the fold they'd be reduced to the actual min/max seen in the list of shards.
Another bug was that the unit test was never run as it didn't end in `_` and it emitted test generators `?_assertEqual(...)` so make sure the test runs and add a few cases: empty list of shards and when range doesn't start or end at `0` or `?RANGE_END`.
Thanks to @rnewson for finding the bug!
=> Fix mem3_util overlapping shards

src/couch/src/couch_db.erl
We introduced a feature in https://github.com/apache/couchdb/pull/4681 to allow couchdb to reject writes at a configurable disk usage threshold, in order to ensure couchdb does not hit end of disk. We intentionally excluded internal replication from this mechanism. Unfortunately this work was flawed and did not allow mem3 checkpoint documents to be written. This PR adds a general bypass mechanism in couch_db module and alters internal replication to use the bypass. 
Closes https://github.com/apache/couchdb/issues/5528
Place a node (or cluster) under sustained write load (a curl loop making new empty documents is sufficient). Alter the write threshold of all nodes to 0. Observe the absence of errors of this form;
```
with exit value:#012{{nocatch,{insufficient_storage,<<"database_dir is …
```
=> Always allow mem3_rep checkpoints

build-aux/Jenkinsfile.full
Noticed a few flaky failures in FreeBSD ARM worker. We see those in the docker workers but there we have retries, so they don't stop the build.
Also, noticed on the s390x worker, we had two flaky failures with eunit crashing towards the end of the runs and there was not enough time to re-run a 3rd time as the job died due a timeout, so expand all the timeouts a bit. They are clearly not enough for all 3 timeouts.
=> Add retries to native full CI stage

src/couch_replicator/src/couch_replicator_auth_session.erl
Previously, the replictor session plugin emitted an error log line if it found only non-`AuthSession` cookies in the headers.
It turns out, as we saw in #1851, some proxies can set their own cookies, and so CouchDb replicator should expect and skip over those without generating excessive log noise.
Fix #1851
=> Ignore extraneous cookie in replicator session plugin

build-aux/Jenkinsfile.full
Implement the `with_clouseau` flag for the Windows worker.  The `elixir-search` target could be safely run unconditionally, the `Makefile` is going to skip the tests when Clouseau is not present.
At the moment, sharing the Erlang cookie between the CouchDB and Clouseau nodes for orchestrating the tests does not work in the current setup.  By default, we rely on the `.erlang.cookie` file in the user's home directory, but this file could only be opened exclusively.  Work this around by setting the cookie string through the command line.
For the full CI run (as a verification), please see [`jenkins-clouseau-windows` #16](https://ci-couchdb.apache.org/job/jenkins-cm1/job/FullPlatformMatrix/job/jenkins-clouseau-windows/16/pipeline-console/).
=> chore(`ci`): enable Clouseau for Windows

rel/overlay/etc/vm.args
In Erlang < 27, it defaulted to `262144` and that's too easy to hit with medium and larger clusters these days. In Erlang >= 27 the deafult was bumped to 1M so set it at that default in vm.args with a note to help users configure it, and know when it may need to be increased.
Issue: https://github.com/apache/couchdb/issues/5544
=> Bump process limit to 1M

src/docs/src/config/resharding.rst, src/mem3/src/mem3_reshard_dbdoc.erl
Thanks to Robert Newson for finding the error
=> Fix config key typo in mem3_reshard_dbdoc

src/couch/src/couch_file.erl, src/couch/src/couch_server.erl
Two improvements for `init_delete_dir`:
* Avoid spawning more than one `init_delete_dir/1` instances from `couch_server`
* Use `filelib:ensure_path/1` since it's now available as of OTP 25
=> Fix init delete dir

src/mem3/src/mem3_shards.erl, src/mem3/src/mem3_sup.erl, src/rexi/src/rexi_server_mon.erl
Improve cluster startup behavior as three separate commits:
* Sometimes if `mem3` is not initialized yet but `rexi` could start calling us, and so we have to handle `mem3_shards` ets tables not being created yet. Previously, we handled the case of missing ets tables by catching `error:badarg` in places like `for_db/2`, but then forgot to handle it the lower level `maybe_spawn_shard_writer/3` function, so call was still crashing and making a mess in the logs. This is more apparent on startup with nodes being upgraded in a busy cluster.
* Improve mem3 supervisor. There was a question there left from years back if order is important, it turns out it is. So fix the order. See the reasoning in the commit message. Also since order is important we want to use a [rest_for_one]( …
=> Improve mem3

src/couch_replicator/src/couch_replicator_httpc.erl
Previously users noticed periodic `ibrowse_stream_cleanup` crashes. Replication jobs would restart as expected, but it looks kind of messy and takes longer.
To improve the situation a bit:
* Increase the number of flushed messages. Flushing is quick so we can clean a few more messages than 16 if need be, so pick 100.
* If we found the worker was dead, we set the stream status to `ended` but we didn't actually flush the mailbox, just exited with `ok`. So make sure to also do the flushing.
* Streamer also emits `ibrowse_async_response_timeout` messages, but we never flushed those, so make sure do so.
* `ibrowse:stream_next(ReqId)` may fail if the request ID to Pid ets table was already cleaned. Previously we would then wait for 30 seconds without getting the response and crash the job. So …
=> Improve replicator client mailbox flush

src/mango/requirements.txt, src/mango/test/mango.py
Bump requests to the latest version 2.32.4. This is predicated that we also update our Almalinux(CentOS) 8 image to install a later Python.
But as a belt and suspenders, or in case the python update fails also set `trust_env=False` in mango tests. The only place we use requests.
=> Bump requests to 2.32.4

build-aux/Jenkinsfile.full
Ubuntu Focal, released in 2020, went out of support in May 2025
MacOS is temporally disabled to get a few green builds going.
=> Skip macos CI for now and remove Ubuntu Focal

Makefile, build-aux/Jenkinsfile.full, src/couch_quickjs/.gitignore, src/couch_quickjs/patches/02-test262-makefile.patch, src/couch_quickjs/patches/03-test262-yield.patch, src/couch_quickjs/patches/04-test262-errors.patch, src/couch_quickjs/quickjs/Makefile, src/couch_quickjs/quickjs/test262_errors.txt, src/couch_quickjs/quickjs/tests/test262.patch, src/couch_quickjs/update_patches.sh
Test262 are 70k+ Javascript conformance tests [1].
There is an upstream PR [2] to run these in CI there but until then we can patch our own QuickJS and run them in our CI.
One of the patches we have `04-test262-errors.patch` patches one of the exception we expect to get since modified the parser to accept the `function` expression syntax.
For now run the test in the full CI only for Linux and skip s390x. Some architectures/os combinations show various discrepancies around TypedArrays or rounding errors.
[1] https://github.com/tc39/test262
[2] https://github.com/bellard/quickjs/pull/408
=> Run test262 JS conformance tests for QuickJS

src/couch_replicator/src/couch_replicator_scheduler_job.erl
Previously we used `gen_server:stop/3` with an infinity timeout.
We have observed that it's possible for jobs to be stuck waiting for network requests so they may take indefinitely to process the shutdown request (and call their `terminate/2` callback) and that can block the replicator scheduler. To fix it add a 5 second timeout to the stop call and then forcibly kill the process.
=> Don't wait indefinitely for replication jobs to stop

src/mem3/src/mem3_rep.erl
* When we don't find the checkpoint doc at all log just the db name, not the whole `#db{}` record.
* When we don't find a suitable history entry, log db name, otherwise it's impossible to tell which db it refers to.
=> Improve mem3_rep:find_source_seq/4 logging

src/couch/src/couch_util.erl, src/docs/src/cluster/databases.rst, src/docs/src/cluster/sharding.rst, src/mem3/src/mem3_nodes.erl, src/mem3/test/eunit/mem3_zone_test.erl
This adds a feature to populate the zone field in the `nodes` database by setting the
`COUCHDB_ZONE` environment variable. Setting the zone for a node was previously an awkward piece of cluster setup orchestration because it required editing the a document on each of the local "nodes" after CouchDB has started but before creating any other system databases.
This implementation reads the `COUCHDB_ZONE` environment variable when mem3 starts and, if present, updates the local node document with that zone string.
One nuance is that multiple nodes in the cluster might create the same first revision of a node document due to the seedlist feature, which pre-emptively adds the seeds to the nodes database. To prevent conflicts when the nodes database is replicated between peers, the zone is set …
=> Populate zone attribute from COUCHDB_ZONE environment variable

src/couch_replicator/src/couch_replicator_notifier.erl, src/couch_replicator/src/couch_replicator_pg.erl, src/couch_replicator/src/couch_replicator_scheduler.erl
There are two related commits, both related to improving replicator app shutdown
1. Tolerate  pg and notifier gen_servers not being there when jobs leave the pg group or do the final notification. This should avoid log noise.
2. Perform a more orderly job shutdown. Give replication jobs a limited time opportunity to shutdown cleanly and even perform one final checkpoint.
=> Improve replicator app stopping

src/docs/src/setup/cluster.rst
Just a tiny wording change at setup cluster docs: changes "master" node to primary node.
=> chore(docs): avoid master wording at setup cluster

Makefile, configure, rebar.config.script
I made a branch called `couchdb` in the apache/couchdb-gun repo based on the `2.2.0` tag. I added a commit that changes where the `cowlib` dep comes from and tagged that as `2.2.0-couchdb`. This PR switches couchdb to point to that tag.
=> use ASF fork of gun for cowlib dep

src/docs/src/install/nouveau.rst
the method for securing nouveau is slightly different now we've switched to http/2.
=> docs: securing nouveau on http/2

rel/overlay/etc/default.ini, src/couch/src/couch_bt_engine_header.erl
Currently, CouchDB on-disk header record allows appending new fields to it in such a way that newer versions can upgrade themselves from the old versions easily if the ?LATEST_DISK_VERSION stays the same. However, it was not possible to perform a downgrade back to an old version in case something went wrong.
While in general it may not be safe to downgrade in such cases, it may be possible for some features, so allow for such an option and make it configurable.
This is essentially a counterpart to this feature:
```
% As long the changes are limited to new header fields (with inline
% defaults) added to the end of the record, then there is no need to increment
% the disk revision number.
```
The release notes of future releases may indicate which version are downgrade safe. Then, to …
=> Implement the ability to downgrade CouchDB versions even on header field changes

src/nouveau/src/nouveau_rpc.erl, test/elixir/test/config/nouveau.elixir, test/elixir/test/nouveau_test.exs
optimize searches when index is fresh
Send the search request first and use the 409 Conflict response to trigger index update (as long as query param 'update' is not set to false). This eliminates a round-trip on every search request when the index is up to date at the cost of an additional search request when it isn't (though the additional search request is rejected with a 409 based on the index state, no additional Lucene query is executed).
I also fixed a bug for the update=false case. If the index never becomes fresh (via `ken` background) the search request loops until we hit a timeout. What now happens is we'll return whatever the out-of-date search indexes return.
Test added for the update=false bug, existing tests cover the rest.
N/A
=> Nouveau search optimization

src/couch_quickjs/patches/01-spidermonkey-185-mode.patch, src/couch_quickjs/patches/02-test262-makefile.patch, src/couch_quickjs/patches/03-test262-yield.patch, src/couch_quickjs/patches/04-test262-errors.patch, src/couch_quickjs/quickjs/Makefile, src/couch_quickjs/quickjs/libregexp.c, src/couch_quickjs/quickjs/quickjs-libc.c, src/couch_quickjs/quickjs/quickjs.c, src/couch_quickjs/quickjs/run-test262.c, src/couch_quickjs/quickjs/test262.conf, src/couch_quickjs/quickjs/test262_errors.txt, src/couch_quickjs/quickjs/tests/test262.patch
* TypedArray.prototype.subarray: fixed the step at which '[[ByteOffset]]' is read https://github.com/bellard/quickjs/commit/c942978927a2a806517598a22a07c50766b3e125
* Fixed buffer overflow in `js_bigint_from_string()` https://github.com/bellard/quickjs/commit/e1c18befb8ef661d9ee8a34ebc54e545a0214df9
* Fixed crash in OP_add_loc if the variable is modified in `JS_ToPrimitiveFree()` https://github.com/bellard/quickjs/commit/1168c215d1daf2765a24d950079b1d5538305417
* Fixed buffer overflow in `js_bigint_to_string1()` https://github.com/bellard/quickjs/commit/9ce544289fe86acdb8fb33e6a425da151438be05
* Fixed buffer overflow in `TypedArray.prototype.lastIndexOf()` https://github.com/bellard/quickjs/commit/c927eca49a326326181a5db12627ffb48f191fe2
* Avoid side effects in `JS_PrintValue()` which may …
=> QuickJS Update

rel/overlay/etc/default.ini, src/chttpd/src/chttpd_node.erl, src/couch/priv/stats_descriptions.cfg, src/couch/src/couch_bt_engine.erl, src/couch/src/couch_bt_engine_cache.erl, src/couch/src/couch_btree.erl, src/couch/src/couch_primary_sup.erl, src/couch/test/eunit/couch_bt_engine_cache_test.erl, src/couch/test/eunit/couch_btree_tests.erl, src/couch_prometheus/src/couch_prometheus.erl
Cache the top b-tree nodes and header terms. In order to get or update any kv leaf nodes in the b-trees, we always have to read the top few kp nodes closer to the root. Even with parallel preads and data being in the page cache the cost of system calls, marshaling the term, going through the erlang IO system can add up.
The cache is limited in size. The size defaults to 64MB and is configurable by the user. If the cache is full, no more entries will be added until more space frees up.
Since multiple processes are accessing the data concurrently, ets tables are sharded by the number of schedulers, not unlike how we shard our couch_server processes. Each ets table has an associated cleaner process which evicts unused entries. Cleaners traverse table entries and "decay" the usage counters …
=> BTree engine term cache

src/couch/src/couch_btree.erl, src/couch/test/eunit/couch_btree_tests.erl
It turns out we never tested the reversed keys case instead we tried to test the sorted case again. However that made the test fail, so to fix that we just disabled the checking to always pass. Luckily the btree logic itself seem to work after the test is fixed.
We never tested various chunk sizes so add two new test with larger and smaller chunk sizes.
As a separate commit, update the chunk size config getter function to use `config:get_integer/3`.
=> Fix couch_btree tests and refactor chunk size config

src/couch/test/eunit/couch_btree_prop_tests.erl
The PPC64LE managed to time out after running 4600 tests so use 3000 as the test count.
=> Reduce btree prop test count a bit

src/chttpd/src/chttpd_external.erl, src/chttpd/test/eunit/chttpd_purge_tests.erl, src/config/src/config.erl, src/couch/src/couch_att.erl, src/couch/src/couch_db.erl, src/couch/src/couch_doc.erl, src/couch/src/couch_httpd_multipart.erl, src/couch/src/couch_native_process.erl, src/couch/src/couch_util.erl, src/couch_mrview/src/couch_mrview.erl, src/couch_mrview/src/couch_mrview_test_util.erl, src/couch_mrview/test/eunit/couch_mrview_collation_tests.erl, src/couch_mrview/test/eunit/couch_mrview_purge_docs_tests.erl, src/couch_pse_tests/src/cpse_util.erl, src/couch_replicator/src/couch_replicator_utils.erl, src/couch_replicator/test/eunit/couch_replicator_compact_tests.erl, src/couch_replicator/test/eunit/couch_replicator_small_max_request_size_target.erl, src/couch_stats/src/couch_stats_httpd.erl, src/ddoc_cache/test/eunit/ddoc_cache_lru_test.erl, src/fabric/src/fabric_rpc.erl, src/fabric/src/fabric_view_changes.erl, src/fabric/test/eunit/fabric_rpc_purge_tests.erl, src/mango/src/mango_doc.erl, src/mango/src/mango_json.erl, src/mango/src/mango_selector_text.erl, src/mem3/src/mem3_util.erl, src/setup/src/setup.erl
At some point Erlang/OTP didn't have direct *_to_binary, binary_to_* and similar functions, and we had to go through lists. Since now we have direct functions simplify some of the code to avoid redunant list conversions.
It's mostly for readability, but in microbenchmarks it's also a bit faster:
```
1> timer:tc(fun() -> lists:foreach(fun(_) -> list_to_binary(integer_to_list(123456789)) end, lists:seq(1, 1000000)) end).
{1609116,ok}
2> timer:tc(fun() -> lists:foreach(fun(_) -> list_to_binary(integer_to_list(123456789)) end, lists:seq(1, 1000000)) end).
{1593957,ok}
3> timer:tc(fun() -> lists:foreach(fun(_) -> list_to_binary(integer_to_list(123456789)) end, lists:seq(1, 1000000)) end).
{1595424,ok}
```
```
4> timer:tc(fun() -> lists:foreach(fun(_) -> integer_to_binary(123456789) end, …
```
=> Remove redundant *_to_list / list_to_* conversion

configure
For erlfmt it's mainly the ability to format newer syntax constructs in OTP 28.
For rebar3 it's mainly staying current with it
Changelogs:
* erlfmt v1.3.0 -> v1.7.0 : https://github.com/WhatsApp/erlfmt/compare/v1.3.0...v1.7.0
* rebar3 3.23.0 -> 3.25.1 : https://github.com/erlang/rebar3/compare/3.23.0...3.25.1
=> Upgrade erlfmt and rebar3

build-aux/Jenkinsfile
* ppc64le : new workers seem to be over-provisioned, take about an hour to run and still fail, while other ci worker run in half the time.
* s390x : is usually faster, however since there are now asf provided s390x worker those don't have the /home/jenkins cache paths set up so elixir tests consistently fail there. Disable for now until we figure that out.
=> Disable ppc64le and s390x builds

src/mem3/src/mem3.erl, src/mem3/src/mem3_db_doc_updater.erl, src/mem3/src/mem3_reshard_dbdoc.erl, src/mem3/src/mem3_reshard_sup.erl, src/mem3/src/mem3_sup.erl, src/mem3/test/eunit/mem3_shards_test.erl
Resharding implements db doc updates with extra steps to ensure some resilience in case the replication ring is broken and to avoid generating conflicts. However, the implementation was specific to resharding used the `#job{}` record as an argument, so change it make it more general and expose it as a top level mem3 API.
The pattern is the same as used in the resharding logic:
* Changes, reading and writing happen on the first live node -- the leader
* Before reading, replicate all the update from other nodes to the leader. This is to handle the case when the replication ring may be broken and to avoid conflicts.
* After updating, to ensure all copies get the update immediately, the change is broadcast to all the live copies.
=> Implement db doc updating

src/couch_scanner/src/couch_scanner_plugin.erl
`run_on_first_node` feature is a running mode for plugins which are only interested in design documents, and may want to avoid fetching clustered design docs on all nodes.
However that feature didn't work since it clashed with a premature optimization in plugin's `scan_db/2` function, which avoided scanning the db if no shards were scheduled to be scanned on the first node. For example, with a 3 node cluster and a q=2 db, it was possible to have both of its shards scheduled to be scanned on db2 and db3, respectively, while the plugin was running on db1 only. In that case the plugin would have skipped calling the main part of `scan_db` which does ddoc processing.
The fix is to remove the premature optimization and load the ddoc even if no shards are scheduled to be scanned on that node …
=> Fix run_on_first_node scanner features

build-aux/Jenkinsfile
Once in a while when centos 8 builder lands on the ARM64 host ubuntu-nc-arm64-12 the build fails. That's because of Spidermonkey. Version 60 on CentOS 8 doesn't build on ARM64. To help with that sequestrate it such that we only explicitly run Debian builds on that host and no other flavor. It's sad to lose a host like that but it's preferable to having to mash reply probably.
To help a bit with available worker switch to fail early mode. This way on first failure the build will stop so it will free up workes quickly.
=> Sequestrate docker ARM builds and fail early
